### ISSUE TITLE
Problems with pip installation of the new napari version

### ISSUE THREAD

**Issue by vigji** [napari/napari#1009]
Trying to pip install napari in anaconda 3 on a Windows produces an error.

## To Reproduce

1. From terminal, `pip install napari` gives me:

```
ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\lpetrucco\anaconda3\lib\site-packages\pip\_internal\cli\base_command.py", line 188, in main
    status = self.run(options, args)
  File "C:\Users\lpetrucco\anaconda3\lib\site-packages\pip\_internal\commands\install.py", line 407, in run
    use_user_site=options.use_user_site,
  File "C:\Users\lpetrucco\anaconda3\lib\site-packages\pip\_internal\req\__init__.py", line 58, in install_given_reqs
    **kwargs
  File "C:\Users\lpetrucco\anaconda3\lib\site-packages\pip\_internal\req\req_install.py", line 928, in install
    use_user_site=use_user_site, pycompile=pycompile,
  File "C:\Users\lpetrucco\anaconda3\lib\site-packages\pip\_internal\req\req_install.py", line 461, in move_wheel_files
    warn_script_location=warn_script_location,
  File "C:\Users\lpetrucco\anaconda3\lib\site-packages\pip\_internal\wheel.py", line 432, in move_wheel_files
    clobber(source, lib_dir, True)
  File "C:\Users\lpetrucco\anaconda3\lib\site-packages\pip\_internal\wheel.py", line 381, in clobber
    ', '.join(info_dir))
AssertionError: Multiple .dist-info directories: C:\Users\lpetrucco\anaconda3\Lib\site-packages\napari\plugins\_tests\fixtures\napari_working_plugin-0.1.0.dist-info, C:\Users\lpetrucco\anaconda3\Lib\site-packages\napari-0.2.12.dist-info
```

I have tried also in a completely new conda env and the same happens. I was able to install using conda-forge.

**Comment by tlambert03** [comment]
Thanks for reporting @vigji and sorry we let that windows issue through!

@jni @sofroniewn, i guess my distributing my plugin discovery testing strategy is problematic for pip on windows.  I tried to emulate the discovery as closely as possible with my dist-info fixtures, but I guess I'll need to rethink that strategy if we are distributing those fixtures with the releases.  I am giving an off campus seminar today so won't be able to attend to this until this evening.

**Comment by guiwitz** [comment]
FYI I just had exactly the same problem on MacOSX-10.13. Conda installation worked fine but pip produced the exact same error message as in the original post.

**Comment by tlambert03** [comment]
thanks @guiwitz ... we obviously need to change some things on our side.  but just out of curiosity, what version of pip are you running?  on `20.0.2` I'm not getting any errors.

**Comment by guiwitz** [comment]
This happened with 19.2.3 (I actually used the wrong environment with an old pip version). Installation works fine with pip 20.0.2 for me too.
