### ISSUE TITLE
Update of napari to 0.2.12 via pip failed with AssertionError

### ISSUE THREAD

**Issue by sebi06** [napari/napari#1036]
## Bug

Update of napari via pip failed on Ubuntu 18.04 LTS. 

## Console Output 

```
(imageanalysis) sebi06@sebastian-tuxedo:~$ pip install napari -U
Collecting napari
  Downloading https://files.pythonhosted.org/packages/83/31/6becfb1e0c342ff6078c2284d2ac3f23cb38a100b666ec76a2ee2af703e1/napari-0.2.12.tar.gz (569kB)
     |████████████████████████████████| 573kB 1.2MB/s 
Requirement already satisfied, skipping upgrade: dask[array]>=2.1.0 in ./miniconda3/envs/imageanalysis/lib/python3.7/site-packages (from napari) (2.9.1)
Requirement already satisfied, skipping upgrade: fsspec>=0.3.3 in ./miniconda3/envs/imageanalysis/lib/python3.7/site-packages (from napari) (0.6.2)
Requirement already satisfied, skipping upgrade: imageio>=2.5.0 in ./miniconda3/envs/imageanalysis/lib/python3.7/site-packages (from napari) (2.6.1)
Requirement already satisfied, skipping upgrade: ipykernel>=5.1.1 in ./miniconda3/envs/imageanalysis/lib/python3.7/site-packages (from napari) (5.1.3)
Requirement already satisfied, skipping upgrade: numpy>=1.10.0 in ./miniconda3/envs/imageanalysis/lib/python3.7/site-packages (from napari) (1.17.3)
Requirement already satisfied, skipping upgrade: qtpy>=1.7.0 in ./miniconda3/envs/imageanalysis/lib/python3.7/site-packages (from napari) (1.9.0)
Requirement already satisfied, skipping upgrade: qtconsole>=4.5.1 in ./miniconda3/envs/imageanalysis/lib/python3.7/site-packages (from napari) (4.6.0)
Requirement already satisfied, skipping upgrade: jupyter-client<6.0.0 in ./miniconda3/envs/imageanalysis/lib/python3.7/site-packages (from napari) (5.3.4)
Requirement already satisfied, skipping upgrade: scipy>=1.2.0 in ./miniconda3/envs/imageanalysis/lib/python3.7/site-packages (from napari) (1.4.1)
Requirement already satisfied, skipping upgrade: scikit-image>=0.15.0 in ./miniconda3/envs/imageanalysis/lib/python3.7/site-packages (from napari) (0.16.2)
Requirement already satisfied, skipping upgrade: vispy>=0.6.4 in ./miniconda3/envs/imageanalysis/lib/python3.7/site-packages (from napari) (0.6.4)
Requirement already satisfied, skipping upgrade: IPython>=7.7.0 in ./miniconda3/envs/imageanalysis/lib/python3.7/site-packages (from napari) (7.11.1)
Requirement already satisfied, skipping upgrade: backcall>=0.1.0 in ./miniconda3/envs/imageanalysis/lib/python3.7/site-packages (from napari) (0.1.0)
Requirement already satisfied, skipping upgrade: PyOpenGL>=3.1.0 in ./miniconda3/envs/imageanalysis/lib/python3.7/site-packages (from napari) (3.1.5)
Requirement already satisfied, skipping upgrade: PySide2>=5.12.3 in ./miniconda3/envs/imageanalysis/lib/python3.7/site-packages (from napari) (5.14.0)
Requirement already satisfied, skipping upgrade: wrapt>=1.11.1 in ./miniconda3/envs/imageanalysis/lib/python3.7/site-packages (from napari) (1.11.2)
Requirement already satisfied, skipping upgrade: numpydoc>=0.9.2 in ./miniconda3/envs/imageanalysis/lib/python3.7/site-packages (from napari) (0.9.2)
Collecting pluggy>=0.13.0
  Using cached https://files.pythonhosted.org/packages/a0/28/85c7aa31b80d150b772fbe4a229487bc6644da9ccb7e427dd8cc60cb8a62/pluggy-0.13.1-py2.py3-none-any.whl
Requirement already satisfied, skipping upgrade: toolz>=0.7.3; extra == "array" in ./miniconda3/envs/imageanalysis/lib/python3.7/site-packages (from dask[array]>=2.1.0->napari) (0.10.0)
Requirement already satisfied, skipping upgrade: pillow in ./miniconda3/envs/imageanalysis/lib/python3.7/site-packages (from imageio>=2.5.0->napari) (7.0.0)
Requirement already satisfied, skipping upgrade: tornado>=4.2 in ./miniconda3/envs/imageanalysis/lib/python3.7/site-packages (from ipykernel>=5.1.1->napari) (6.0.3)
Requirement already satisfied, skipping upgrade: traitlets>=4.1.0 in ./miniconda3/envs/imageanalysis/lib/python3.7/site-packages (from ipykernel>=5.1.1->napari) (4.3.3)
Requirement already satisfied, skipping upgrade: ipython-genutils in ./miniconda3/envs/imageanalysis/lib/python3.7/site-packages (from qtconsole>=4.5.1->napari) (0.2.0)
Requirement already satisfied, skipping upgrade: jupyter-core in ./miniconda3/envs/imageanalysis/lib/python3.7/site-packages (from qtconsole>=4.5.1->napari) (4.6.1)
Requirement already satisfied, skipping upgrade: pygments in ./miniconda3/envs/imageanalysis/lib/python3.7/site-packages (from qtconsole>=4.5.1->napari) (2.5.2)
Requirement already satisfied, skipping upgrade: pyzmq>=13 in ./miniconda3/envs/imageanalysis/lib/python3.7/site-packages (from jupyter-client<6.0.0->napari) (18.1.1)
Requirement already satisfied, skipping upgrade: python-dateutil>=2.1 in ./miniconda3/envs/imageanalysis/lib/python3.7/site-packages (from jupyter-client<6.0.0->napari) (2.8.1)
Requirement already satisfied, skipping upgrade: PyWavelets>=0.4.0 in ./miniconda3/envs/imageanalysis/lib/python3.7/site-packages (from scikit-image>=0.15.0->napari) (1.1.1)
Requirement already satisfied, skipping upgrade: matplotlib!=3.0.0,>=2.0.0 in ./miniconda3/envs/imageanalysis/lib/python3.7/site-packages (from scikit-image>=0.15.0->napari) (3.1.2)
Requirement already satisfied, skipping upgrade: networkx>=2.0 in ./miniconda3/envs/imageanalysis/lib/python3.7/site-packages (from scikit-image>=0.15.0->napari) (2.4)
Requirement already satisfied, skipping upgrade: freetype-py in ./miniconda3/envs/imageanalysis/lib/python3.7/site-packages (from vispy>=0.6.4->napari) (2.1.0.post1)
Requirement already satisfied, skipping upgrade: setuptools>=18.5 in ./miniconda3/envs/imageanalysis/lib/python3.7/site-packages (from IPython>=7.7.0->napari) (44.0.0.post20200102)
Requirement already satisfied, skipping upgrade: pexpect; sys_platform != "win32" in ./miniconda3/envs/imageanalysis/lib/python3.7/site-packages (from IPython>=7.7.0->napari) (4.7.0)
Requirement already satisfied, skipping upgrade: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in ./miniconda3/envs/imageanalysis/lib/python3.7/site-packages (from IPython>=7.7.0->napari) (3.0.2)
Requirement already satisfied, skipping upgrade: jedi>=0.10 in ./miniconda3/envs/imageanalysis/lib/python3.7/site-packages (from IPython>=7.7.0->napari) (0.15.2)
Requirement already satisfied, skipping upgrade: pickleshare in ./miniconda3/envs/imageanalysis/lib/python3.7/site-packages (from IPython>=7.7.0->napari) (0.7.5)
Requirement already satisfied, skipping upgrade: decorator in ./miniconda3/envs/imageanalysis/lib/python3.7/site-packages (from IPython>=7.7.0->napari) (4.4.1)
Requirement already satisfied, skipping upgrade: shiboken2==5.14.0 in ./miniconda3/envs/imageanalysis/lib/python3.7/site-packages (from PySide2>=5.12.3->napari) (5.14.0)
Requirement already satisfied, skipping upgrade: sphinx>=1.6.5 in ./miniconda3/envs/imageanalysis/lib/python3.7/site-packages (from numpydoc>=0.9.2->napari) (2.3.1)
Requirement already satisfied, skipping upgrade: Jinja2>=2.3 in ./miniconda3/envs/imageanalysis/lib/python3.7/site-packages (from numpydoc>=0.9.2->napari) (2.10.3)
Collecting importlib-metadata>=0.12; python_version < "3.8"
  Downloading https://files.pythonhosted.org/packages/8b/03/a00d504808808912751e64ccf414be53c29cad620e3de2421135fcae3025/importlib_metadata-1.5.0-py2.py3-none-any.whl
Requirement already satisfied, skipping upgrade: six in ./miniconda3/envs/imageanalysis/lib/python3.7/site-packages (from traitlets>=4.1.0->ipykernel>=5.1.1->napari) (1.13.0)
Requirement already satisfied, skipping upgrade: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in ./miniconda3/envs/imageanalysis/lib/python3.7/site-packages (from matplotlib!=3.0.0,>=2.0.0->scikit-image>=0.15.0->napari) (2.4.6)
Requirement already satisfied, skipping upgrade: cycler>=0.10 in ./miniconda3/envs/imageanalysis/lib/python3.7/site-packages (from matplotlib!=3.0.0,>=2.0.0->scikit-image>=0.15.0->napari) (0.10.0)
Requirement already satisfied, skipping upgrade: kiwisolver>=1.0.1 in ./miniconda3/envs/imageanalysis/lib/python3.7/site-packages (from matplotlib!=3.0.0,>=2.0.0->scikit-image>=0.15.0->napari) (1.1.0)
Requirement already satisfied, skipping upgrade: ptyprocess>=0.5 in ./miniconda3/envs/imageanalysis/lib/python3.7/site-packages (from pexpect; sys_platform != "win32"->IPython>=7.7.0->napari) (0.6.0)
Requirement already satisfied, skipping upgrade: wcwidth in ./miniconda3/envs/imageanalysis/lib/python3.7/site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->IPython>=7.7.0->napari) (0.1.8)
Requirement already satisfied, skipping upgrade: parso>=0.5.2 in ./miniconda3/envs/imageanalysis/lib/python3.7/site-packages (from jedi>=0.10->IPython>=7.7.0->napari) (0.5.2)
Requirement already satisfied, skipping upgrade: sphinxcontrib-jsmath in ./miniconda3/envs/imageanalysis/lib/python3.7/site-packages (from sphinx>=1.6.5->numpydoc>=0.9.2->napari) (1.0.1)
Requirement already satisfied, skipping upgrade: packaging in ./miniconda3/envs/imageanalysis/lib/python3.7/site-packages (from sphinx>=1.6.5->numpydoc>=0.9.2->napari) (20.0)
Requirement already satisfied, skipping upgrade: alabaster<0.8,>=0.7 in ./miniconda3/envs/imageanalysis/lib/python3.7/site-packages (from sphinx>=1.6.5->numpydoc>=0.9.2->napari) (0.7.12)
Requirement already satisfied, skipping upgrade: docutils>=0.12 in ./miniconda3/envs/imageanalysis/lib/python3.7/site-packages (from sphinx>=1.6.5->numpydoc>=0.9.2->napari) (0.15.2)
Requirement already satisfied, skipping upgrade: sphinxcontrib-applehelp in ./miniconda3/envs/imageanalysis/lib/python3.7/site-packages (from sphinx>=1.6.5->numpydoc>=0.9.2->napari) (1.0.1)
Requirement already satisfied, skipping upgrade: requests>=2.5.0 in ./miniconda3/envs/imageanalysis/lib/python3.7/site-packages (from sphinx>=1.6.5->numpydoc>=0.9.2->napari) (2.22.0)
Requirement already satisfied, skipping upgrade: imagesize in ./miniconda3/envs/imageanalysis/lib/python3.7/site-packages (from sphinx>=1.6.5->numpydoc>=0.9.2->napari) (1.2.0)
Requirement already satisfied, skipping upgrade: sphinxcontrib-devhelp in ./miniconda3/envs/imageanalysis/lib/python3.7/site-packages (from sphinx>=1.6.5->numpydoc>=0.9.2->napari) (1.0.1)
Requirement already satisfied, skipping upgrade: sphinxcontrib-htmlhelp in ./miniconda3/envs/imageanalysis/lib/python3.7/site-packages (from sphinx>=1.6.5->numpydoc>=0.9.2->napari) (1.0.2)
Requirement already satisfied, skipping upgrade: snowballstemmer>=1.1 in ./miniconda3/envs/imageanalysis/lib/python3.7/site-packages (from sphinx>=1.6.5->numpydoc>=0.9.2->napari) (2.0.0)
Requirement already satisfied, skipping upgrade: babel!=2.0,>=1.3 in ./miniconda3/envs/imageanalysis/lib/python3.7/site-packages (from sphinx>=1.6.5->numpydoc>=0.9.2->napari) (2.8.0)
Requirement already satisfied, skipping upgrade: sphinxcontrib-serializinghtml in ./miniconda3/envs/imageanalysis/lib/python3.7/site-packages (from sphinx>=1.6.5->numpydoc>=0.9.2->napari) (1.1.3)
Requirement already satisfied, skipping upgrade: sphinxcontrib-qthelp in ./miniconda3/envs/imageanalysis/lib/python3.7/site-packages (from sphinx>=1.6.5->numpydoc>=0.9.2->napari) (1.0.2)
Requirement already satisfied, skipping upgrade: MarkupSafe>=0.23 in ./miniconda3/envs/imageanalysis/lib/python3.7/site-packages (from Jinja2>=2.3->numpydoc>=0.9.2->napari) (1.1.1)
Collecting zipp>=0.5
  Downloading https://files.pythonhosted.org/packages/b2/34/bfcb43cc0ba81f527bc4f40ef41ba2ff4080e047acb0586b56b3d017ace4/zipp-3.1.0-py3-none-any.whl
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in ./miniconda3/envs/imageanalysis/lib/python3.7/site-packages (from requests>=2.5.0->sphinx>=1.6.5->numpydoc>=0.9.2->napari) (2019.11.28)
Requirement already satisfied, skipping upgrade: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in ./miniconda3/envs/imageanalysis/lib/python3.7/site-packages (from requests>=2.5.0->sphinx>=1.6.5->numpydoc>=0.9.2->napari) (1.25.7)
Requirement already satisfied, skipping upgrade: chardet<3.1.0,>=3.0.2 in ./miniconda3/envs/imageanalysis/lib/python3.7/site-packages (from requests>=2.5.0->sphinx>=1.6.5->numpydoc>=0.9.2->napari) (3.0.4)
Requirement already satisfied, skipping upgrade: idna<2.9,>=2.5 in ./miniconda3/envs/imageanalysis/lib/python3.7/site-packages (from requests>=2.5.0->sphinx>=1.6.5->numpydoc>=0.9.2->napari) (2.8)
Requirement already satisfied, skipping upgrade: pytz>=2015.7 in ./miniconda3/envs/imageanalysis/lib/python3.7/site-packages (from babel!=2.0,>=1.3->sphinx>=1.6.5->numpydoc>=0.9.2->napari) (2019.3)
Building wheels for collected packages: napari
  Building wheel for napari (setup.py) ... done
  Created wheel for napari: filename=napari-0.2.12-cp37-none-any.whl size=695596 sha256=ccb76d9b3ebc3af0fc0c24c3fb1d5e417a22e302f14c4b1486690c583f6e0c29
  Stored in directory: /home/sebi06/.cache/pip/wheels/d3/c5/d5/a0fa9f9188ce2fbc81451e4785ecc1cfd7b515213b71114e18
Successfully built napari
Installing collected packages: zipp, importlib-metadata, pluggy, napari
  Found existing installation: napari 0.2.9
    Uninstalling napari-0.2.9:
      Successfully uninstalled napari-0.2.9
  Rolling back uninstall of napari
  Moving to /home/sebi06/miniconda3/envs/imageanalysis/bin/napari
   from /tmp/pip-uninstall-_sjwg9g7/napari
  Moving to /home/sebi06/miniconda3/envs/imageanalysis/lib/python3.7/site-packages/benchmarks/
   from /home/sebi06/miniconda3/envs/imageanalysis/lib/python3.7/site-packages/~enchmarks
  Moving to /home/sebi06/miniconda3/envs/imageanalysis/lib/python3.7/site-packages/napari-0.2.9.dist-info/
   from /home/sebi06/miniconda3/envs/imageanalysis/lib/python3.7/site-packages/~apari-0.2.9.dist-info
  Moving to /home/sebi06/miniconda3/envs/imageanalysis/lib/python3.7/site-packages/napari/
   from /home/sebi06/miniconda3/envs/imageanalysis/lib/python3.7/site-packages/~apari
ERROR: Exception:
Traceback (most recent call last):
  File "/home/sebi06/miniconda3/envs/imageanalysis/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 153, in _main
    status = self.run(options, args)
  File "/home/sebi06/miniconda3/envs/imageanalysis/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 455, in run
    use_user_site=options.use_user_site,
  File "/home/sebi06/miniconda3/envs/imageanalysis/lib/python3.7/site-packages/pip/_internal/req/__init__.py", line 62, in install_given_reqs
    **kwargs
  File "/home/sebi06/miniconda3/envs/imageanalysis/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 861, in install
    use_user_site=use_user_site, pycompile=pycompile,
  File "/home/sebi06/miniconda3/envs/imageanalysis/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 495, in move_wheel_files
    warn_script_location=warn_script_location,
  File "/home/sebi06/miniconda3/envs/imageanalysis/lib/python3.7/site-packages/pip/_internal/wheel.py", line 461, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/home/sebi06/miniconda3/envs/imageanalysis/lib/python3.7/site-packages/pip/_internal/wheel.py", line 410, in clobber
    ', '.join(info_dir))
AssertionError: Multiple .dist-info directories: /home/sebi06/miniconda3/envs/imageanalysis/lib/python3.7/site-packages/napari/plugins/_tests/fixtures/napari_working_plugin-0.1.0.dist-info, /home/sebi06/miniconda3/envs/imageanalysis/lib/python3.7/site-packages/napari-0.2.12.dist-info
```

**Comment by sofroniewn** [comment]
This is likely the same error as in #1009 which can be fixed up updating your `pip` - `20.0.2` should work `19.2.3` should fail. We've fixed this in master so it shouldn't be an issue for our next release, but updating pip will probably be your fastest fix

**Comment by sebi06** [comment]
pip 20.0.2 did the job for me.

**Comment by sofroniewn** [comment]
Great! I will close as this is fixed in master and will be fixed on our next release.
