### ISSUE TITLE
Assertion failed when adding shapes

### ISSUE THREAD

**Issue by sumanthratna** [napari/napari#1058]
## 🐛 Bug

When I try to add shapes, I get an `AssertionError`:`assert (c, b) not in self._edges_lookup`. Switching to paths works as expected.

## To Reproduce

```python
import numpy as np
import napari

regions = [np.array([[124.8, 669.8],
       [124.6, 669.8],
       [124.2, 669.8],
       [123.8, 669.8],
       [123.4, 669.8],
       [122.8, 669.4],
       [122.4, 669.2],
       [122.2, 669.2],
       [122. , 669. ],
       [121.8, 669. ],
       [121.6, 668.8],
       [121.2, 668.6],
       [121. , 668.4],
       [120.8, 668.2],
       [120.6, 668. ],
       [120.4, 667.8],
       [120.2, 667.6],
       [120.2, 667.4],
       [120.2, 667.2],
       [120. , 666.8],
       [119.8, 666.6],
       [119.8, 666.4],
       [119.8, 666.2],
       [119.8, 666. ],
       [119.6, 665.8],
       [119.6, 665.6],
       [119.6, 665.4],
       [119.4, 665.2],
       [119.2, 664.8],
       [119. , 664.4],
       [118.8, 664. ],
       [118.8, 663.8],
       [118.8, 663.6],
       [118.8, 663.4],
       [118.8, 663.2],
       [118.8, 663. ],
       [118.8, 662.6],
       [118.8, 662.4],
       [118.8, 662. ],
       [118.8, 661.8],
       [118.8, 661.6],
       [118.8, 661.2],
       [118.8, 661. ],
       [118.8, 660.8],
       [119. , 660.4],
       [119. , 659.6],
       [119. , 659.4],
       [119. , 659.2],
       [119.2, 659. ],
       [119.4, 658.4],
       [119.6, 658.2],
       [119.8, 658. ],
       [119.8, 657.8],
       [120. , 657.6],
       [120.2, 657.4],
       [120.4, 657.2],
       [120.6, 657. ],
       [120.8, 656.8],
       [121. , 656.6],
       [121.2, 656.4],
       [121.4, 656.2],
       [121.6, 656. ],
       [121.8, 655.8],
       [122. , 655.6],
       [122.2, 655.4],
       [122.4, 655.2],
       [122.6, 655. ],
       [122.8, 654.8],
       [123. , 654.6],
       [123.2, 654.4],
       [123.4, 654.2],
       [123.6, 654. ],
       [123.8, 653.8],
       [124. , 653.8],
       [124.2, 653.6],
       [124.4, 653.4],
       [124.6, 653.4],
       [124.8, 653.2],
       [125. , 653. ],
       [125.2, 652.8],
       [125.6, 652.6],
       [125.8, 652.4],
       [126. , 652.4],
       [126.4, 652.2],
       [126.6, 652.2],
       [126.8, 652. ],
       [127. , 652. ],
       [127.2, 652. ],
       [127.4, 651.8],
       [127.6, 651.8],
       [127.8, 651.8],
       [128.2, 651.6],
       [128.4, 651.6],
       [128.6, 651.6],
       [128.8, 651.6],
       [129. , 651.4],
       [129.2, 651.4],
       [129.4, 651.4],
       [129.6, 651.2],
       [129.8, 651.2],
       [130. , 651.2],
       [130.2, 651.2],
       [130.4, 651. ],
       [130.6, 651. ],
       [130.8, 651. ],
       [131. , 651. ],
       [131.2, 651. ],
       [131.4, 651. ],
       [131.6, 651. ],
       [131.8, 651. ],
       [132. , 651. ],
       [132.2, 651. ],
       [132.4, 651. ],
       [132.6, 651. ],
       [132.8, 650.8],
       [133. , 650.8],
       [133.2, 650.8],
       [133.4, 650.8],
       [133.6, 651. ],
       [133.8, 651. ],
       [134. , 651. ],
       [134.2, 651. ],
       [134.4, 651. ],
       [134.6, 651. ],
       [134.8, 651. ],
       [135. , 651. ],
       [135.2, 651. ],
       [135.4, 651. ],
       [135.6, 651. ],
       [135.8, 651. ],
       [136. , 651.2],
       [136.2, 651.2],
       [136.4, 651.2],
       [136.6, 651.2],
       [136.8, 651.2],
       [137. , 651.2],
       [137.4, 651.4],
       [137.6, 651.4],
       [137.8, 651.4],
       [138. , 651.4],
       [138.2, 651.4],
       [138.6, 651.6],
       [139. , 651.6],
       [139.2, 651.6],
       [139.4, 651.6],
       [139.8, 651.6],
       [140. , 651.6],
       [140.4, 651.6],
       [140.6, 651.6],
       [140.8, 651.6],
       [141. , 651.6],
       [141.2, 651.8],
       [141.4, 651.8],
       [141.6, 652. ],
       [141.8, 652. ],
       [142.2, 652. ],
       [142.4, 652. ],
       [142.6, 652. ],
       [143. , 652.2],
       [143.4, 652.2],
       [143.6, 652.2],
       [144. , 652.2],
       [144.2, 652.2],
       [144.6, 652.2],
       [145. , 652. ],
       [145.2, 651.8],
       [145.4, 651.8],
       [145.6, 651.8],
       [145.8, 651.6],
       [146. , 651.6],
       [146.2, 651.6],
       [146.4, 651.4],
       [146.6, 651.4],
       [146.8, 651.4],
       [147. , 651.4],
       [147.2, 651.4],
       [147.4, 651.4],
       [147.6, 651.4],
       [147.8, 651.4],
       [148. , 651.4],
       [148.2, 651.6],
       [148.4, 651.8],
       [148.6, 652. ],
       [148.8, 652.2],
       [149. , 652.4],
       [149.2, 652.6],
       [149.4, 652.8],
       [149.6, 653. ],
       [149.8, 653.2],
       [149.8, 653.4],
       [149.8, 653.6],
       [149.8, 654. ],
       [149.8, 654.2],
       [149.8, 654.6],
       [150. , 654.8],
       [150. , 655. ],
       [150. , 655.4],
       [150. , 655.8],
       [150. , 656.4],
       [150.2, 656.8],
       [150.2, 657. ],
       [150.2, 657.2],
       [150.2, 657.8],
       [150.2, 658.2],
       [150.2, 658.6],
       [150.2, 658.8],
       [150.2, 659.2],
       [150.2, 659.4],
       [150. , 659.8],
       [150. , 660. ],
       [150. , 660.4],
       [150. , 660.6],
       [150. , 661. ],
       [150. , 661.2],
       [150. , 661.4],
       [150. , 661.8],
       [150. , 662. ],
       [150. , 662.2],
       [149.8, 662.6],
       [149.6, 662.8],
       [149.4, 663. ],
       [149.2, 663.2],
       [149. , 663.4],
       [149. , 663.6],
       [148.6, 664.2],
       [148.4, 664.4],
       [148. , 664.6],
       [147.8, 664.8],
       [147.6, 665. ],
       [147.4, 665.2],
       [147.2, 665.4],
       [147. , 665.6],
       [146.8, 665.8],
       [146.6, 666. ],
       [146.6, 666.2],
       [146.4, 666.6],
       [146.2, 666.8],
       [146. , 667. ],
       [145.8, 667.2],
       [145.6, 667.6],
       [145.4, 668. ],
       [145.2, 668.2],
       [145. , 668.4],
       [144.8, 668.6],
       [144.6, 668.8],
       [144.4, 669. ],
       [144. , 669.2],
       [143.8, 669.4],
       [143.6, 669.4],
       [143.4, 669.6],
       [143.2, 669.6],
       [142.8, 669.8],
       [142.4, 670.2],
       [142.2, 670.2],
       [142. , 670.2],
       [141.8, 670.2],
       [141.4, 670.4],
       [141.2, 670.6],
       [141. , 670.6],
       [140.8, 670.8],
       [140.2, 671. ],
       [140. , 671.2],
       [139.8, 671.2],
       [139.6, 671.2],
       [139.4, 671.4],
       [139. , 671.6],
       [138.8, 671.6],
       [138.6, 671.6],
       [138.4, 671.6],
       [138.2, 671.8],
       [138. , 671.8],
       [137.8, 671.8],
       [137.6, 671.8],
       [137.4, 671.8],
       [137.2, 671.8],
       [137. , 671.8],
       [136.8, 671.8],
       [136.4, 671.6],
       [136.2, 671.6],
       [136. , 671.6],
       [135.8, 671.6],
       [135.6, 671.6],
       [135.4, 671.6],
       [135.2, 671.6],
       [135. , 671.6],
       [134.8, 671.4],
       [134.6, 671.4],
       [134.4, 671.4],
       [134.2, 671.4],
       [134. , 671.4],
       [133.8, 671.2],
       [133.6, 671.2],
       [133.4, 671.2],
       [133.2, 671.2],
       [133. , 671.2],
       [132.8, 671.2],
       [132.6, 671.2],
       [132.4, 671. ],
       [132.2, 671. ],
       [132. , 671. ],
       [131.8, 671. ],
       [131.6, 671. ],
       [131.4, 671. ],
       [131.2, 671. ],
       [131. , 670.8],
       [130.4, 670.6],
       [130.2, 670.4],
       [130. , 670.2],
       [129.8, 670.2],
       [129.6, 670.2],
       [129.4, 670.2],
       [129.2, 670. ],
       [129. , 670. ],
       [128.8, 669.8],
       [128.6, 669.8],
       [128.4, 669.8],
       [128.2, 669.8],
       [128. , 669.8],
       [127.8, 669.6],
       [127.6, 669.6],
       [127.4, 669.6],
       [127.2, 669.6],
       [127. , 669.6],
       [126.8, 669.6],
       [126.6, 669.6],
       [126.4, 669.6],
       [126.2, 669.6],
       [126. , 669.6],
       [125.8, 669.6],
       [125.6, 669.8],
       [125.4, 669.8],
       [125.2, 669.8],
       [125. , 669.8],
       [124.8, 669.8],
       [124.6, 669.6],
       [124.4, 669.6],
       [124.2, 669.4]])]

with napari.gui_qt():
    viewer = napari.Viewer()
    _ = viewer.add_shapes(regions, shape_type='polygon')
    # this works:
    # _ = viewer.add_shapes(regions, shape_type='path')
```
Results in the following error:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/suman/Library/Caches/pypoetry/virtualenvs/viewmask-FY58-nbg-py3.6/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/suman/Library/Caches/pypoetry/virtualenvs/viewmask-FY58-nbg-py3.6/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/suman/Library/Caches/pypoetry/virtualenvs/viewmask-FY58-nbg-py3.6/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/suman/Library/Caches/pypoetry/virtualenvs/viewmask-FY58-nbg-py3.6/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/suman/Library/Caches/pypoetry/virtualenvs/viewmask-FY58-nbg-py3.6/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/suman/quantum/viewmask/bin/cli.py", line 79, in view_overlay
    regions, shape_type='polygon', edge_color=f"#{line_color}")
  File "/Users/suman/Library/Caches/pypoetry/virtualenvs/viewmask-FY58-nbg-py3.6/lib/python3.6/site-packages/napari/components/add_layers_mixin.py", line 547, in add_shapes
    visible=visible,
  File "/Users/suman/Library/Caches/pypoetry/virtualenvs/viewmask-FY58-nbg-py3.6/lib/python3.6/site-packages/napari/layers/shapes/shapes.py", line 309, in __init__
    z_index=z_index,
  File "/Users/suman/Library/Caches/pypoetry/virtualenvs/viewmask-FY58-nbg-py3.6/lib/python3.6/site-packages/napari/layers/shapes/shapes.py", line 698, in add
    ndisplay=self.dims.ndisplay,
  File "/Users/suman/Library/Caches/pypoetry/virtualenvs/viewmask-FY58-nbg-py3.6/lib/python3.6/site-packages/napari/layers/shapes/shape_models/polygon.py", line 56, in __init__
    self.data = data
  File "/Users/suman/Library/Caches/pypoetry/virtualenvs/viewmask-FY58-nbg-py3.6/lib/python3.6/site-packages/napari/layers/shapes/shape_models/polygon.py", line 80, in data
    self._update_displayed_data()
  File "/Users/suman/Library/Caches/pypoetry/virtualenvs/viewmask-FY58-nbg-py3.6/lib/python3.6/site-packages/napari/layers/shapes/shape_models/polygon.py", line 84, in _update_displayed_data
    self._set_meshes(self.data_displayed)
  File "/Users/suman/Library/Caches/pypoetry/virtualenvs/viewmask-FY58-nbg-py3.6/lib/python3.6/site-packages/napari/layers/shapes/shape_models/shape.py", line 322, in _set_meshes
    vertices, triangles = triangulate_face(clean_data)
  File "/Users/suman/Library/Caches/pypoetry/virtualenvs/viewmask-FY58-nbg-py3.6/lib/python3.6/site-packages/napari/layers/shapes/shape_utils.py", line 555, in triangulate_face
    vertices, triangles = PolygonData(vertices=data).triangulate()
  File "/Users/suman/Library/Caches/pypoetry/virtualenvs/viewmask-FY58-nbg-py3.6/lib/python3.6/site-packages/vispy/geometry/polygon.py", line 130, in triangulate
    tri.triangulate()
  File "/Users/suman/Library/Caches/pypoetry/virtualenvs/viewmask-FY58-nbg-py3.6/lib/python3.6/site-packages/vispy/geometry/triangulation.py", line 187, in triangulate
    self._edge_event(i, j)
  File "/Users/suman/Library/Caches/pypoetry/virtualenvs/viewmask-FY58-nbg-py3.6/lib/python3.6/site-packages/vispy/geometry/triangulation.py", line 407, in _edge_event
    polygon[ind+1])
  File "/Users/suman/Library/Caches/pypoetry/virtualenvs/viewmask-FY58-nbg-py3.6/lib/python3.6/site-packages/vispy/geometry/triangulation.py", line 775, in _add_tri
    assert (c, b) not in self._edges_lookup
AssertionError
```

## Expected behavior

The shapes should render just as they did with `shape_type='path'`, but the shapes should be filled in. 

## Environment

 - Please copy and paste the information at napari info option in help menubar here: 
```
napari: 0.2.12
Platform: Darwin-19.4.0-x86_64-i386-64bit
Python: 3.6.8 (v3.6.8:3c6b436a57, Dec 24 2018, 02:04:31) [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]
Qt: 5.13.2
PySide2: 5.13.2
VisPy: 0.6.4
NumPy: 1.18.1
SciPy: 1.4.1
scikit-image: 0.16.2
Dask: 2.12.0

GL version: 2.1 INTEL-14.5.21
MAX_TEXTURE_SIZE: 16384
```

 - Any other relevant information: `opencv-python` is also installed (I do see the Qt warnings)

**Comment by sofroniewn** [comment]
Thanks for reporting this @sumanthratna. This looks like a corner case in vispy's triangulation code. I will dig in and take a look. Ultimately this might require a PR to vispy to fix.

**Comment by sofroniewn** [comment]
Note that this error can be reproduced with the following minimal example shape

```python
regions = [np.array([[1248, 6698],
       [1246, 6698],
       [1242, 6698],
       [1248, 6698],
       [1242, 6694]])]
```

and that the following
```python
regions = [np.array([[1248, 6698],
       [1246, 6697],
       [1242, 6698],
       [1248, 6698],
       [1242, 6694]])]
```
leads to an incorrect triangulation.

The issue seems to arise with collinear / overlapping points

<img width="1200" alt="Screen Shot 2020-12-06 at 4 20 10 PM" src="https://user-images.githubusercontent.com/6531703/101297667-f81f4b80-37de-11eb-9e77-57b347301674.png">

**Comment by andy-sweet** [comment]
I took a quick look at this, found the same issues as @sofroniewn, found some of the underlying causes in vispy, and added a comment to [an existing vispy issue](https://github.com/vispy/vispy/issues/1847#issuecomment-958181091) that runs into the same problem.

I think it's relatively easy to fix vispy to avoid the assertion failure (at least in the simple case described), but I'm unsure how to fix the unexpected triangulation in the screenshot above. I'll wait for feedback from a vispy maintainer to understand what our best path forward on this bug is. Note that if desired we could pull in a dependency other than vispy to perform the triangulation.

**Comment by sofroniewn** [comment]
Thanks for investigating @andy-sweet - let's see what happens on the vispy thread and then make a decision from there

**Comment by kcpevey** [comment]
Current state on napari 0.4.17 and vispy 0.11.0:

```
regions = [np.array([[1248, 6698],
       [1246, 6698],
       [1242, 6698],
       [1248, 6698],
       [1242, 6694]])]
viewer.add_shapes(regions, shape_type='polygon')
```
Still fails with the error from OP. 

<details><summary>Full traceback</summary>

```
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
Cell In[11], line 1
----> 1 viewer.add_shapes(regions, shape_type='polygon')

File ~/miniconda3/envs/napari_main_39/lib/python3.9/site-packages/napari/components/viewer_model.py:4, in add_shapes(self, data, ndim, features, properties, property_choices, text, shape_type, edge_width, edge_color, edge_color_cycle, edge_colormap, edge_contrast_limits, face_color, face_color_cycle, face_colormap, face_contrast_limits, z_index, name, metadata, scale, translate, rotate, shear, affine, opacity, blending, visible, cache, experimental_clipping_planes)
      1 from __future__ import annotations
      3 import inspect
----> 4 import itertools
      5 import os
      6 import warnings

File ~/miniconda3/envs/napari_main_39/lib/python3.9/site-packages/napari/layers/shapes/shapes.py:508, in Shapes.__init__(self, data, ndim, features, properties, property_choices, text, shape_type, edge_width, edge_color, edge_color_cycle, edge_colormap, edge_contrast_limits, face_color, face_color_cycle, face_colormap, face_contrast_limits, z_index, name, metadata, scale, translate, rotate, shear, affine, opacity, blending, visible, cache, experimental_clipping_planes)
    505 self.mode = Mode.PAN_ZOOM
    506 self._status = self.mode
--> 508 self._init_shapes(
    509     data,
    510     shape_type=shape_type,
    511     edge_width=edge_width,
    512     edge_color=edge_color,
    513     edge_color_cycle=edge_color_cycle,
    514     edge_colormap=edge_colormap,
    515     edge_contrast_limits=edge_contrast_limits,
    516     face_color=face_color,
    517     face_color_cycle=face_color_cycle,
    518     face_colormap=face_colormap,
    519     face_contrast_limits=face_contrast_limits,
    520     z_index=z_index,
    521 )
    523 # set the current_* properties
    524 if len(data) > 0:

File ~/miniconda3/envs/napari_main_39/lib/python3.9/site-packages/napari/layers/shapes/shapes.py:2077, in Shapes._init_shapes(self, data, shape_type, edge_width, edge_color, edge_color_cycle, edge_colormap, edge_contrast_limits, face_color, face_color_cycle, face_colormap, face_contrast_limits, z_index)
   2072     face_color = self._initialize_color(
   2073         face_color, attribute='face', n_shapes=n_shapes
   2074     )
   2076 with self.block_thumbnail_update():
-> 2077     self._add_shapes(
   2078         data,
   2079         shape_type=shape_type,
   2080         edge_width=edge_width,
   2081         edge_color=edge_color,
   2082         face_color=face_color,
   2083         z_index=z_index,
   2084         z_refresh=False,
   2085     )
   2086     self._data_view._update_z_order()
   2087     self.refresh_colors()

File ~/miniconda3/envs/napari_main_39/lib/python3.9/site-packages/napari/layers/shapes/shapes.py:2192, in Shapes._add_shapes(self, data, shape_type, edge_width, edge_color, face_color, z_index, z_refresh)
   2182     # Turn input arguments into iterables
   2183     shape_inputs = zip(
   2184         data,
   2185         ensure_iterable(shape_type),
   (...)
   2189         ensure_iterable(z_index),
   2190     )
-> 2192     self._add_shapes_to_view(shape_inputs, self._data_view)
   2194 self._display_order_stored = copy(self._dims_order)
   2195 self._ndisplay_stored = copy(self._ndisplay)

File ~/miniconda3/envs/napari_main_39/lib/python3.9/site-packages/napari/layers/shapes/shapes.py:2204, in Shapes._add_shapes_to_view(self, shape_inputs, data_view)
   2201 shape_inputs = tuple(shape_inputs)
   2203 # build all shapes
-> 2204 sh_inp = tuple(
   2205     (
   2206         shape_classes[ShapeType(st)](
   2207             d,
   2208             edge_width=ew,
   2209             z_index=z,
   2210             dims_order=self._dims_order,
   2211             ndisplay=self._ndisplay,
   2212         ),
   2213         ec,
   2214         fc,
   2215     )
   2216     for d, st, ew, ec, fc, z in shape_inputs
   2217 )
   2219 shapes, edge_colors, face_colors = tuple(zip(*sh_inp))
   2221 # Add all shapes at once (faster than adding them one by one)

File ~/miniconda3/envs/napari_main_39/lib/python3.9/site-packages/napari/layers/shapes/shapes.py:2206, in <genexpr>(.0)
   2201 shape_inputs = tuple(shape_inputs)
   2203 # build all shapes
   2204 sh_inp = tuple(
   2205     (
-> 2206         shape_classes[ShapeType(st)](
   2207             d,
   2208             edge_width=ew,
   2209             z_index=z,
   2210             dims_order=self._dims_order,
   2211             ndisplay=self._ndisplay,
   2212         ),
   2213         ec,
   2214         fc,
   2215     )
   2216     for d, st, ew, ec, fc, z in shape_inputs
   2217 )
   2219 shapes, edge_colors, face_colors = tuple(zip(*sh_inp))
   2221 # Add all shapes at once (faster than adding them one by one)

File ~/miniconda3/envs/napari_main_39/lib/python3.9/site-packages/napari/layers/shapes/_shapes_models/polygon.py:30, in Polygon.__init__(self, data, edge_width, z_index, dims_order, ndisplay)
     20 def __init__(
     21     self,
     22     data,
   (...)
     27     ndisplay=2,
     28 ):
---> 30     super().__init__(
     31         data=data,
     32         edge_width=edge_width,
     33         z_index=z_index,
     34         dims_order=dims_order,
     35         ndisplay=ndisplay,
     36         closed=True,
     37         filled=True,
     38         name='polygon',
     39     )

File ~/miniconda3/envs/napari_main_39/lib/python3.9/site-packages/napari/layers/shapes/_shapes_models/_polgyon_base.py:51, in PolygonBase.__init__(self, data, edge_width, z_index, dims_order, ndisplay, filled, closed, name)
     49 self._filled = filled
     50 self._closed = closed
---> 51 self.data = data
     52 self.name = name

File ~/miniconda3/envs/napari_main_39/lib/python3.9/site-packages/napari/layers/shapes/_shapes_models/_polgyon_base.py:76, in PolygonBase.data(self, data)
     67     raise ValueError(
     68         trans._(
     69             "Shape needs at least two vertices, {number} provided.",
   (...)
     72         )
     73     )
     75 self._data = data
---> 76 self._update_displayed_data()

File ~/miniconda3/envs/napari_main_39/lib/python3.9/site-packages/napari/layers/shapes/_shapes_models/_polgyon_base.py:81, in PolygonBase._update_displayed_data(self)
     79 """Update the data that is to be displayed."""
     80 # For path connect every all data
---> 81 self._set_meshes(
     82     self.data_displayed, face=self._filled, closed=self._closed
     83 )
     84 self._box = create_box(self.data_displayed)
     86 data_not_displayed = self.data[:, self.dims_not_displayed]

File ~/miniconda3/envs/napari_main_39/lib/python3.9/site-packages/napari/layers/shapes/_shapes_models/shape.py:223, in Shape._set_meshes(self, data, closed, face, edge)
    221 if not is_collinear(clean_data[:, -2:]):
    222     if clean_data.shape[1] == 2:
--> 223         vertices, triangles = triangulate_face(clean_data)
    224     elif len(np.unique(clean_data[:, 0])) == 1:
    225         val = np.unique(clean_data[:, 0])

File ~/miniconda3/envs/napari_main_39/lib/python3.9/site-packages/napari/layers/shapes/_shapes_utils.py:562, in triangulate_face(data)
    560     vertices, triangles = res['vertices'], res['triangles']
    561 else:
--> 562     vertices, triangles = PolygonData(vertices=data).triangulate()
    564 triangles = triangles.astype(np.uint32)
    566 return vertices, triangles

File ~/miniconda3/envs/napari_main_39/lib/python3.9/site-packages/vispy/geometry/polygon.py:125, in PolygonData.triangulate(self)
    122     edges[:, 1] = edges[:, 0] + 1
    124 tri = Triangulation(self._vertices, edges)
--> 125 tri.triangulate()
    126 return tri.pts, tri.tris

File ~/miniconda3/envs/napari_main_39/lib/python3.9/site-packages/vispy/geometry/triangulation.py:186, in Triangulation.triangulate(self)
    182     if i in self._tops:
    183         for j in self._bottoms[self._tops == i]:
    184             # Make sure edge (j, i) is present in mesh
    185             # because edge event may have created a new front list
--> 186             self._edge_event(i, j)
    187             front = self._front
    189 self._finalize()

File ~/miniconda3/envs/napari_main_39/lib/python3.9/site-packages/vispy/geometry/triangulation.py:405, in Triangulation._edge_event(self, i, j)
    403 while len(polygon) > 2:
    404     ind = np.argmax(dist)
--> 405     self._add_tri(polygon[ind], polygon[ind-1],
    406                   polygon[ind+1])
    407     polygon.pop(ind)
    408     dist.pop(ind)

File ~/miniconda3/envs/napari_main_39/lib/python3.9/site-packages/vispy/geometry/triangulation.py:772, in Triangulation._add_tri(self, a, b, c)
    770 else:
    771     assert (b, a) not in self._edges_lookup
--> 772     assert (c, b) not in self._edges_lookup
    773     assert (a, c) not in self._edges_lookup
    774     self._edges_lookup[(b, a)] = c

AssertionError: 
```

</details>

The second example that @sofroniewn posted _does_ load into napari without error. I'm not sure what "incorrect triangulation" means - just that it was meshed incorrectly, but it loads just fine? [I'm unsure if this is related, but I couldn't change the colors on this shape after it loaded.]

Second example:  
```
regions = [np.array([[1248, 6698],
       [1246, 6697],
       [1242, 6698],
       [1248, 6698],
       [1242, 6694]])]
```
<hr>

Also, following up with overview because there are a lot related things going on here. 

We have the [original vispy issue](https://github.com/vispy/vispy/issues/1847#issuecomment-958181091) that @andy-sweet  commented on 
The [separate vispy issue](https://github.com/vispy/vispy/issues/2247) that @djhoese opened for this specific issue
And the [vispy PR](https://github.com/vispy/vispy/pull/2248) that @andy-sweet opened. 



Other related napari issue which may be affected:
[Assertion error when meshing certain polygons #4674](https://github.com/napari/napari/issues/4674)
[Error with certain polygon data #1653](https://github.com/napari/napari/issues/1653)

<hr>

@andy-sweet can you update here on the status of your vispy PR?
