### ISSUE TITLE
Deleting layer throws error and viewing area is empty

### ISSUE THREAD

**Issue by hectormz** [napari/napari#1157]
## To Reproduce

1. Load images or create other layers in `napari`
2. Select layer and click trash button, or drag to trash
3. Viewing area goes black and following trace is printed:

```
Traceback (most recent call last):
  File "XXXX\lib\site-packages\vispy\app\backends\_qt.py", line 825, in paintGL
    self._vispy_canvas.events.draw(region=None)
  File "XXXX\lib\site-packages\vispy\util\event.py", line 455, in __call__
    self._invoke_callback(cb, event)
  File "XXXX\lib\site-packages\vispy\util\event.py", line 473, in _invoke_callback
    _handle_exception(self.ignore_callback_errors,
  File "XXXX\lib\site-packages\vispy\util\event.py", line 471, in _invoke_callback
    cb(event)
  File "YYY\napari\napari\_vispy\vispy_base_layer.py", line 234, in on_draw
    self.layer.scale_factor = self.scale_factor
  File "YYY\napari\napari\_vispy\vispy_base_layer.py", line 131, in scale_factor
    transform = self.node.canvas.scene.node_transform(self.node)
AttributeError: 'NoneType' object has no attribute 'scene'
```

I checked out various commits, and narrowed it down to `f9ca768` (#1053 Fix pyramid clipping). 

Perhaps @sofroniewn might have the best idea.

## Environment

 - Please copy and paste the information at napari info option in help menubar here:

```
napari: 0.2.12+61.g5c30662
Platform: Windows-10-10.0.19041-SP0
Python: 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)]
Qt: 5.14.1
PySide2: 5.14.1
NumPy: 1.18.1
SciPy: 1.4.1
Dask: 2.12.0
VisPy: 0.6.4

GL version: 4.6.0 NVIDIA 441.45
MAX_TEXTURE_SIZE: 32768

Plugins:
- mat-images: 0.1.0
```

**Comment by sofroniewn** [comment]
Yup, that's a bug, will work on a fix + test right now
