### ISSUE TITLE
Installation fails with "AssertionError: Multiple .dist-info directories"

### ISSUE THREAD

**Issue by emmanuelle** [napari/napari#1167]
I cannot install napari inside a fresh Python venv, using `pip install napari`. Here is the error message
```
Installing collected packages: numpy, toolz, dask, qtpy, ipython-genutils, decorator, six, traitlets, jupyter-core, tornado, python-dateutil, pyzmq, jupyter-client, wcwidth, prompt-toolkit, pickleshare, ptyprocess, pexpect, backcall, parso, jedi, pygments, IPython, ipykernel, qtconsole, PyOpenGL, pillow, imageio, scipy, PyWavelets, networkx, cycler, pyparsing, kiwisolver, matplotlib, scikit-image, shiboken2, PySide2, fsspec, wrapt, zipp, importlib-metadata, pluggy, freetype-py, vispy, pytz, babel, packaging, docutils, urllib3, idna, chardet, certifi, requests, alabaster, sphinxcontrib-htmlhelp, sphinxcontrib-serializinghtml, sphinxcontrib-applehelp, sphinxcontrib-qthelp, imagesize, snowballstemmer, sphinxcontrib-devhelp, MarkupSafe, Jinja2, sphinxcontrib-jsmath, sphinx, numpydoc, napari
  Running setup.py install for tornado ... done
  Running setup.py install for wrapt ... done
Exception:
Traceback (most recent call last):
  File "/home/emma/sandbox/venv_napari/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 143, in main
    status = self.run(options, args)
  File "/home/emma/sandbox/venv_napari/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 386, in run
    use_user_site=options.use_user_site,
  File "/home/emma/sandbox/venv_napari/lib/python3.7/site-packages/pip/_internal/req/__init__.py", line 49, in install_given_reqs
    **kwargs
  File "/home/emma/sandbox/venv_napari/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 760, in install
    use_user_site=use_user_site, pycompile=pycompile,
  File "/home/emma/sandbox/venv_napari/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 382, in move_wheel_files
    warn_script_location=warn_script_location,
  File "/home/emma/sandbox/venv_napari/lib/python3.7/site-packages/pip/_internal/wheel.py", line 324, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/home/emma/sandbox/venv_napari/lib/python3.7/site-packages/pip/_internal/wheel.py", line 273, in clobber
    ', '.join(info_dir))
AssertionError: Multiple .dist-info directories: /home/emma/sandbox/venv_napari/lib/python3.7/site-packages/napari/plugins/_tests/fixtures/napari_working_plugin-0.1.0.dist-info, /home/emma/sandbox/venv_napari/lib/python3.7/site-packages/napari-0.2.12.dist-info
```
I'm using python 3.7 on Ubuntu.

**Comment by tlambert03** [comment]
This will be fixed in the next version, but for now please try updating pip.  See also #1009 and #1036

**Comment by emmanuelle** [comment]
ok thank you!

**Comment by emmanuelle** [comment]
how about warning about this problem in this napari doc? I'm happy to submit a PR if you think this is appropriate (unless of course the next release is very soon)

**Comment by tlambert03** [comment]
Yeah, it’s already fixed in master and the next release is soon, aaand most people won’t have pip <v20 at this point anyway... so I’m a little hesitant to make it official in the docs.  We are working hard to get the next release out very soon!

**Comment by emmanuelle** [comment]
Great to hear about the release coming soon, thanks for your hard work! pip 20 was released this January so I guess most of your users started using Python a while before (and pip is not something you think of upgrading, or you just upgrade when there is a problem which does not happen often).
