### ISSUE TITLE
Pyramid rendering failing for ndisplay=3

### ISSUE THREAD

**Issue by jni** [napari/napari#1178]
## 🐛 Bug

Trying to view pyramids in 3D results in a hard crash.

## To Reproduce

```python
import napari
import numpy as np

pyr = [np.random.random((128,) * 3),
       np.random.random((64,) * 3)]

with napari.gui_qt():
    v = napari.view_image(pyr)
    v.dims.ndisplay = 3
```

gives:

```pytb
Traceback (most recent call last):
  File "/home/jni/miniconda3/envs/f7/lib/python3.7/site-packages/vispy/app/backends/_qt.py", line 825, in paintGL
    self._vispy_canvas.events.draw(region=None)
  File "/home/jni/miniconda3/envs/f7/lib/python3.7/site-packages/vispy/util/event.py", line 455, in __call__
    self._invoke_callback(cb, event)
  File "/home/jni/miniconda3/envs/f7/lib/python3.7/site-packages/vispy/util/event.py", line 475, in _invoke_callback
    self, cb_event=(cb, event))
  File "/home/jni/miniconda3/envs/f7/lib/python3.7/site-packages/vispy/util/event.py", line 471, in _invoke_callback
    cb(event)
  File "/home/jni/projects/napari/napari/_vispy/vispy_base_layer.py", line 241, in on_draw
    shape_threshold=self.node.canvas.size,
  File "/home/jni/projects/napari/napari/layers/base/base.py", line 675, in _update_multiscale
    downsample_factors,
  File "/home/jni/projects/napari/napari/layers/utils/layer_utils.py", line 249, in compute_multiscale_level
    locations = np.argwhere(np.all(scaled_shape > shape_threshold, axis=1))
ValueError: operands could not be broadcast together with shapes (2,3) (2,) 
```
## Expected behavior

The lowest resolution level of the pyramid should be displayed.

## Environment

 - Please copy and paste the information at napari info option in help menubar here:

```
napari: 0.2.12+78.g6933f5bc
Platform: Linux-4.15.0-29-generic-x86_64-with-debian-buster-sid
Python: 3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 21:52:21)  [GCC 7.3.0]
Qt: 5.13.0
PyQt5: 5.13.1
NumPy: 1.18.3
SciPy: 1.3.1
Dask: 2.5.2
VisPy: 0.6.4

GL version:  3.0 Mesa 19.2.8
MAX_TEXTURE_SIZE: 16384

Plugins:
  - napari-plugin-engine: 0.1.4
  - napari-plugins: 0.1.0
```

**Comment by sofroniewn** [comment]
This is closed by #1179
