### ISSUE TITLE
Program validation error on 3D activation

### ISSUE THREAD

**Issue by joshmoore** [napari/napari#1224]
## To Reproduce

1. see https://github.com/ome/ome-zarr-py/pull/9
2. 
```
>>> from tests.create_test_data import create_zarr
>>> create_zarr("test_data.zarr")
```
3. `napari test_data.zarr`
4. activate 3D

<details>
<summary>stack trace</summary>

```
(py36) /opt/ome-zarr-py $napari /tmp/test_data.zarr/
INFO:napari_plugin_engine.manager:loaded 3 plugins:
  <module 'napari.plugins._builtins' from '/opt/anaconda/envs/py36/lib/python3.6/site-packages/napari/plugins/_builtins.py'>
  <module 'napari_svg' from '/opt/anaconda/envs/py36/lib/python3.6/site-packages/napari_svg/__init__.py'>
  <module 'ome_zarr' from '/opt/ome-zarr-py/ome_zarr.py'>
  <module 'napari_plugin_engine' from '/opt/anaconda/envs/py36/lib/python3.6/site-packages/napari_plugin_engine/__init__.py'>
root_attrs {'multiscales': [{'datasets': [{'path': '0'}, {'path': '1'}, {'path': '2'}, {'path': '3'}, {'path': '4'}], 'version': '0.1'}]}
resolutions ['0', '1', '2', '3', '4']
resolution 0 shape (t, c, z, y, x) (1, 3, 1, 1024, 1024) chunks ['1', '1', '1', '256', '256'] dtype float64
resolution 1 shape (t, c, z, y, x) (1, 3, 1, 512, 512) chunks ['1', '1', '1', '256', '256'] dtype float64
resolution 2 shape (t, c, z, y, x) (1, 3, 1, 256, 256) chunks ['1', '2 (+ 1)', '1', '128', '128'] dtype float64
resolution 3 shape (t, c, z, y, x) (1, 3, 1, 128, 128) chunks ['1', '2 (+ 1)', '1', '128', '128'] dtype float64
resolution 4 shape (t, c, z, y, x) (1, 3, 1, 64, 64) chunks ['1', '3', '1', '64', '64'] dtype float64
INFO:OpenGL.acceleratesupport:No OpenGL_accelerate module loaded: No module named 'OpenGL_accelerate'
WARNING: Error drawing visual <Volume at 0x7fd2e0640ac8>
WARNING:vispy:Error drawing visual <Volume at 0x7fd2e0640ac8>
WARNING: Traceback (most recent call last):
  File "/opt/anaconda/envs/py36/lib/python3.6/site-packages/vispy/app/backends/_qt.py", line 825, in paintGL
    self._vispy_canvas.events.draw(region=None)
  File "/opt/anaconda/envs/py36/lib/python3.6/site-packages/vispy/util/event.py", line 455, in __call__
    self._invoke_callback(cb, event)
  File "/opt/anaconda/envs/py36/lib/python3.6/site-packages/vispy/util/event.py", line 475, in _invoke_callback
    self, cb_event=(cb, event))
  File "/opt/anaconda/envs/py36/lib/python3.6/site-packages/vispy/util/event.py", line 471, in _invoke_callback
    cb(event)
  File "/opt/anaconda/envs/py36/lib/python3.6/site-packages/vispy/scene/canvas.py", line 217, in on_draw
    self._draw_scene()
  File "/opt/anaconda/envs/py36/lib/python3.6/site-packages/vispy/scene/canvas.py", line 266, in _draw_scene
    self.draw_visual(self.scene)
  File "/opt/anaconda/envs/py36/lib/python3.6/site-packages/vispy/scene/canvas.py", line 304, in draw_visual
    node.draw()
  File "/opt/anaconda/envs/py36/lib/python3.6/site-packages/vispy/scene/visuals.py", line 99, in draw
    self._visual_superclass.draw(self)
  File "/opt/anaconda/envs/py36/lib/python3.6/site-packages/vispy/visuals/visual.py", line 443, in draw
    self._vshare.index_buffer)
  File "/opt/anaconda/envs/py36/lib/python3.6/site-packages/vispy/visuals/shaders/program.py", line 101, in draw
    Program.draw(self, *args, **kwargs)
  File "/opt/anaconda/envs/py36/lib/python3.6/site-packages/vispy/gloo/program.py", line 533, in draw
    canvas.context.flush_commands()
  File "/opt/anaconda/envs/py36/lib/python3.6/site-packages/vispy/gloo/context.py", line 176, in flush_commands
    self.glir.flush(self.shared.parser)
  File "/opt/anaconda/envs/py36/lib/python3.6/site-packages/vispy/gloo/glir.py", line 572, in flush
    self._shared.flush(parser)
  File "/opt/anaconda/envs/py36/lib/python3.6/site-packages/vispy/gloo/glir.py", line 494, in flush
    parser.parse(self._filter(self.clear(), parser))
  File "/opt/anaconda/envs/py36/lib/python3.6/site-packages/vispy/gloo/glir.py", line 819, in parse
    self._parse(command)
  File "/opt/anaconda/envs/py36/lib/python3.6/site-packages/vispy/gloo/glir.py", line 779, in _parse
    ob.draw(*args)
  File "/opt/anaconda/envs/py36/lib/python3.6/site-packages/vispy/gloo/glir.py", line 1329, in draw
    self._pre_draw()
  File "/opt/anaconda/envs/py36/lib/python3.6/site-packages/vispy/gloo/glir.py", line 1289, in _pre_draw
    self._validate()
  File "/opt/anaconda/envs/py36/lib/python3.6/site-packages/vispy/gloo/glir.py", line 1301, in _validate
    % gl.glGetProgramInfoLog(self._handle))
RuntimeError: Program validation error:
WARNING:vispy:Traceback (most recent call last):
  File "/opt/anaconda/envs/py36/lib/python3.6/site-packages/vispy/app/backends/_qt.py", line 825, in paintGL
    self._vispy_canvas.events.draw(region=None)
  File "/opt/anaconda/envs/py36/lib/python3.6/site-packages/vispy/util/event.py", line 455, in __call__
    self._invoke_callback(cb, event)
  File "/opt/anaconda/envs/py36/lib/python3.6/site-packages/vispy/util/event.py", line 475, in _invoke_callback
    self, cb_event=(cb, event))
  File "/opt/anaconda/envs/py36/lib/python3.6/site-packages/vispy/util/event.py", line 471, in _invoke_callback
    cb(event)
  File "/opt/anaconda/envs/py36/lib/python3.6/site-packages/vispy/scene/canvas.py", line 217, in on_draw
    self._draw_scene()
  File "/opt/anaconda/envs/py36/lib/python3.6/site-packages/vispy/scene/canvas.py", line 266, in _draw_scene
    self.draw_visual(self.scene)
  File "/opt/anaconda/envs/py36/lib/python3.6/site-packages/vispy/scene/canvas.py", line 304, in draw_visual
    node.draw()
  File "/opt/anaconda/envs/py36/lib/python3.6/site-packages/vispy/scene/visuals.py", line 99, in draw
    self._visual_superclass.draw(self)
  File "/opt/anaconda/envs/py36/lib/python3.6/site-packages/vispy/visuals/visual.py", line 443, in draw
    self._vshare.index_buffer)
  File "/opt/anaconda/envs/py36/lib/python3.6/site-packages/vispy/visuals/shaders/program.py", line 101, in draw
    Program.draw(self, *args, **kwargs)
  File "/opt/anaconda/envs/py36/lib/python3.6/site-packages/vispy/gloo/program.py", line 533, in draw
    canvas.context.flush_commands()
  File "/opt/anaconda/envs/py36/lib/python3.6/site-packages/vispy/gloo/context.py", line 176, in flush_commands
    self.glir.flush(self.shared.parser)
  File "/opt/anaconda/envs/py36/lib/python3.6/site-packages/vispy/gloo/glir.py", line 572, in flush
    self._shared.flush(parser)
  File "/opt/anaconda/envs/py36/lib/python3.6/site-packages/vispy/gloo/glir.py", line 494, in flush
    parser.parse(self._filter(self.clear(), parser))
  File "/opt/anaconda/envs/py36/lib/python3.6/site-packages/vispy/gloo/glir.py", line 819, in parse
    self._parse(command)
  File "/opt/anaconda/envs/py36/lib/python3.6/site-packages/vispy/gloo/glir.py", line 779, in _parse
    ob.draw(*args)
  File "/opt/anaconda/envs/py36/lib/python3.6/site-packages/vispy/gloo/glir.py", line 1329, in draw
    self._pre_draw()
  File "/opt/anaconda/envs/py36/lib/python3.6/site-packages/vispy/gloo/glir.py", line 1289, in _pre_draw
    self._validate()
  File "/opt/anaconda/envs/py36/lib/python3.6/site-packages/vispy/gloo/glir.py", line 1301, in _validate
    % gl.glGetProgramInfoLog(self._handle))
RuntimeError: Program validation error:
Abort trap: 6
```
</details>

## Expected behavior

Not exactly sure. I'd assume a very flat 3D representation.

## Environment

 - `napari==0.3.0`
 - `ome-zarr-py==0.0.2`

**Comment by jni** [comment]
Hmm, I was trying to replicate this locally without zarr and got a different error. Both need fixing.

```python
import numpy as np
import napari

with napari.gui_qt():
    napari.view_image(np.ones((4, 4)), ndisplay=3)    
```

```pytb
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-3-991bc3d56023> in <module>
----> 1 napari.view_image(np.ones((4, 4)), ndisplay=3)

~/miniconda3/envs/all/lib/python3.8/site-packages/napari/view_layers.py in view_image(data, channel_axis, rgb, colormap, contrast_limits, gamma, interpolation, rendering, iso_threshold, attenuation, name, metadata, scale, translate, opacity, blending, visible, multiscale, title, ndisplay, order, axis_labels, show)
    119         show=show,
    120     )
--> 121     viewer.add_image(
    122         data=data,
    123         channel_axis=channel_axis,

~/miniconda3/envs/all/lib/python3.8/site-packages/napari/components/add_layers_mixin.py in add_image(self, data, channel_axis, rgb, colormap, contrast_limits, gamma, interpolation, rendering, iso_threshold, attenuation, name, metadata, scale, translate, opacity, blending, visible, multiscale)
    226                     )
    227 
--> 228             return self.add_layer(layers.Image(data, **kwargs))
    229         else:
    230             # Determine if data is a multiscale

~/miniconda3/envs/all/lib/python3.8/site-packages/napari/components/add_layers_mixin.py in add_layer(self, layer)
     58         layer.dims.events.order.connect(self._on_layers_change)
     59         layer.dims.events.range.connect(self._on_layers_change)
---> 60         self.layers.append(layer)
     61         self._update_layers(layers=[layer])
     62 

~/miniconda3/envs/all/lib/python3.8/site-packages/napari/utils/list/_model.py in append(self, obj)
     58     def append(self, obj):
     59         TypedList.append(self, obj)
---> 60         self.events.added(item=obj, index=len(self) - 1)
     61 
     62     def pop(self, key):

~/miniconda3/envs/all/lib/python3.8/site-packages/napari/utils/event.py in __call__(self, *args, **kwargs)
    506                     continue
    507 
--> 508                 self._invoke_callback(cb, event)
    509                 if event.blocked:
    510                     break

~/miniconda3/envs/all/lib/python3.8/site-packages/napari/utils/event.py in _invoke_callback(self, cb, event)
    523             cb(event)
    524         except Exception:
--> 525             _handle_exception(
    526                 self.ignore_callback_errors,
    527                 self.print_callback_errors,

~/miniconda3/envs/all/lib/python3.8/site-packages/napari/utils/event.py in _invoke_callback(self, cb, event)
    521     def _invoke_callback(self, cb, event):
    522         try:
--> 523             cb(event)
    524         except Exception:
    525             _handle_exception(

~/miniconda3/envs/all/lib/python3.8/site-packages/napari/utils/event.py in __call__(self, *args, **kwargs)
    506                     continue
    507 
--> 508                 self._invoke_callback(cb, event)
    509                 if event.blocked:
    510                     break

~/miniconda3/envs/all/lib/python3.8/site-packages/napari/utils/event.py in _invoke_callback(self, cb, event)
    523             cb(event)
    524         except Exception:
--> 525             _handle_exception(
    526                 self.ignore_callback_errors,
    527                 self.print_callback_errors,

~/miniconda3/envs/all/lib/python3.8/site-packages/napari/utils/event.py in _invoke_callback(self, cb, event)
    521     def _invoke_callback(self, cb, event):
    522         try:
--> 523             cb(event)
    524         except Exception:
    525             _handle_exception(

~/miniconda3/envs/all/lib/python3.8/site-packages/napari/components/viewer_model.py in _update_grid(self, event)
    508         """Update grid with current grid values.
    509         """
--> 510         self.grid_view(
    511             n_row=self.grid_size[0],
    512             n_column=self.grid_size[1],

~/miniconda3/envs/all/lib/python3.8/site-packages/napari/components/viewer_model.py in grid_view(self, n_row, n_column, stride)
    498             i_row = adj_i // n_column
    499             i_column = adj_i % n_column
--> 500             self._subplot(layer, (i_row, i_column))
    501 
    502     def stack_view(self):

~/miniconda3/envs/all/lib/python3.8/site-packages/napari/components/viewer_model.py in _subplot(self, layer, position)
    526             Size of the grid that is being used.
    527         """
--> 528         scene_size, corner = self._scene_shape()
    529         translate_2d = np.multiply(scene_size[-2:], position)
    530         translate = [0] * layer.ndim

~/miniconda3/envs/all/lib/python3.8/site-packages/napari/components/viewer_model.py in _scene_shape(self)
    264         min_shape, max_shape = self._calc_bbox()
    265         size = np.subtract(max_shape, min_shape)
--> 266         size = [size[i] for i in self.dims.displayed]
    267         corner = [min_shape[i] for i in self.dims.displayed]
    268 

~/miniconda3/envs/all/lib/python3.8/site-packages/napari/components/viewer_model.py in <listcomp>(.0)
    264         min_shape, max_shape = self._calc_bbox()
    265         size = np.subtract(max_shape, min_shape)
--> 266         size = [size[i] for i in self.dims.displayed]
    267         corner = [min_shape[i] for i in self.dims.displayed]
    268 

IndexError: index 2 is out of bounds for axis 0 with size 2
```

**Comment by jni** [comment]
... And oddly enough, if I load a 2D numpy array and then activate 3D, I *do* get a flat 3D oblong!

![cube](https://user-images.githubusercontent.com/492549/81392933-0ee4af00-90e5-11ea-9246-5a22d86cde3d.png)

**Comment by sofroniewn** [comment]
Hmm ok, I will look into and try fixing for next release, I think @jni comments give me enough to go on

**Comment by liu-ziyang** [comment]
trying to reproduce this on macbook, when I Load the data directly, I get a 2x2 astronaut image matrix, and when I switch to 3D, it seems to be rotating as a plane just fine, one thing I noticed is that the plane has much less resolution than the original 2D plane, meaning the image gets blurry. other than that no error/exception happens whatsoever. I am looking up how to capture gifs on MacBook... once I get that I can upload a screen shot

**Comment by liu-ziyang** [comment]
I do notice this ticket is reported on a relatively old napari version, can you maybe try reproducing this on the latest release and see if that helps? I am on my local build reporting `napari-0.3.5.dev20+g9d95e8e.d20200617`, (weird that it says 0.3.5 since we are on 0.3.6 now)

**Comment by tlambert03** [comment]
> weird that it says 0.3.5 since we are on 0.3.6 now

You would need to fetch tags and run `pip install -e .` to update your local version

**Comment by liu-ziyang** [comment]
here's what it looks like on my mac when reproduced:

![demo](https://user-images.githubusercontent.com/41968256/90276844-6d72a500-de19-11ea-826a-7bfc6caff282.gif)

**Comment by sofroniewn** [comment]
Nice gif @ziyangczi! Looks like you were replicating the second comment from @jni 

> Hmm, I was trying to replicate this locally without zarr and got a different error. Both need fixing.
>```python
> import numpy as np
> import napari
>
> with napari.gui_qt():
>    napari.view_image(np.ones((4, 4)), ndisplay=3)    
>```

which I think was fixed by #1360. Good to see that appears to be the case.

I think though that was potentially unrelated to the original zarr 3D activation error at the top of the PR.

> Steps to reproduce the behavior:
>
> 1. see ome/ome-zarr-py#9
> 2.
>  ```
> from tests.create_test_data import create_zarr
> create_zarr("test_data.zarr")
> ```
> 3. napari test_data.zarr
> 4. activate 3D

I think this error may still remain as the stack trace was a vispy one. @ziyangczi can you try reproducing this error using the zarr test dataset from the ome group. Maybe @joshmoore can also test again with that dataset on the latest version of napari on main (master).

**Comment by liu-ziyang** [comment]
I was reproducing from the zarr test dataset, I was running napari test_data.zarr. let me include that in the gif as well

**Comment by liu-ziyang** [comment]
![demo1](https://user-images.githubusercontent.com/41968256/90277906-53d25d00-de1b-11ea-9aea-49cd4a0c8d2f.gif)

**Comment by sofroniewn** [comment]
> I was reproducing from the zarr test dataset, I was running napari test_data.zarr. let me include that in the gif as well

Amazing, sorry I didn't understand the astronauts came from the zarr dataset!!! Likely also this was fixed by #1360.

It looks like this is fixed on our main branch now, so maybe @joshmoore can confirm this now works for him and then we can get to closing.

Looking through our tests though, and remembering what happened on #1360 I don't think we have an explicit test for this though. Maybe @ziyangczi you can add the minimal example from @jni 

```python
napari.view_image(np.ones((4, 4)), ndisplay=3)
```

Into our tests here https://github.com/napari/napari/blob/master/napari/_tests/test_view_layers.py#L175 and then we can close this issue, confident it won't come back!!!

**Comment by joshmoore** [comment]
_Whoa!_ Earlier crash. Never properly launches:

```
(demo) /opt/napari $napari test_data.zarr/
22:02:03 ERROR Unhandled exception:
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/demo/lib/python3.6/site-packages/vispy/app/backends/_qt.py", line 825, in paintGL
    self._vispy_canvas.events.draw(region=None)
  File "/usr/local/anaconda3/envs/demo/lib/python3.6/site-packages/vispy/util/event.py", line 455, in __call__
    self._invoke_callback(cb, event)
  File "/usr/local/anaconda3/envs/demo/lib/python3.6/site-packages/vispy/util/event.py", line 475, in _invoke_callback
    self, cb_event=(cb, event))
  File "/usr/local/anaconda3/envs/demo/lib/python3.6/site-packages/vispy/util/event.py", line 471, in _invoke_callback
    cb(event)
  File "/opt/napari/napari/_vispy/vispy_base_layer.py", line 247, in on_draw
    shape_threshold=self.node.canvas.size,
  File "/opt/napari/napari/layers/base/base.py", line 715, in _update_multiscale
    self.data_level = data_level
  File "/opt/napari/napari/layers/image/image.py", line 326, in data_level
    self.refresh()
  File "/opt/napari/napari/layers/base/base.py", line 655, in refresh
    self.set_view_slice()
  File "/opt/napari/napari/layers/base/base.py", line 608, in set_view_slice
    self._set_view_slice()
  File "/opt/napari/napari/layers/image/image.py", line 565, in _set_view_slice
    self.events.scale()
  File "/opt/napari/napari/utils/event.py", line 508, in __call__
    self._invoke_callback(cb, event)
  File "/opt/napari/napari/utils/event.py", line 529, in _invoke_callback
    cb_event=(cb, event),
  File "/opt/napari/napari/utils/event.py", line 523, in _invoke_callback
    cb(event)
  File "/opt/napari/napari/_vispy/vispy_base_layer.py", line 157, in _on_scale_change
    self.layer.corner_pixels = self.coordinates_of_canvas_corners()
  File "/opt/napari/napari/_vispy/vispy_base_layer.py", line 215, in coordinates_of_canvas_corners
    self._transform_position(self.node.canvas.size) + offset[::-1]
  File "/usr/local/anaconda3/envs/demo/lib/python3.6/site-packages/vispy/app/canvas.py", line 336, in size
    size = self._backend._vispy_get_size()
  File "/usr/local/anaconda3/envs/demo/lib/python3.6/site-packages/vispy/app/backends/_qt.py", line 434, in _vispy_get_size
    g = self.geometry()
RuntimeError: wrapped C/C++ object of type CanvasBackendDesktop has been deleted
```

from ```* 12a7c30 - (HEAD, origin/master, origin/HEAD) Prevent napari crashing after layer is dragged into trash (#1487) (3 days ago) <Hector>```

```
(demo) /opt/napari $napari --info
napari: 0.3.7.dev22+g12a7c30
Platform: Darwin-19.6.0-x86_64-i386-64bit
Python: 3.6.10 | packaged by conda-forge | (default, Apr 24 2020, 16:27:41)  [GCC Clang 9.0.1 ]
Qt: 5.12.5
PyQt5: 5.12.3
NumPy: 1.18.4
SciPy: 1.4.1
Dask: 2.16.0
VisPy: 0.6.4

GL version:  2.1 ATI-3.10.15
MAX_TEXTURE_SIZE: 16384

Plugins:
  - napari-plugin-engine: 0.1.5
  - ome_zarr: 0.0.11.dev0
  - omero: 0.1.1.dev5+g6d45d4c
  - svg: 0.1.3
```

**Comment by joshmoore** [comment]
In a fresh 3.8.5 environment, it works fine:

```
  515  conda create -n napari -c conda-forge napari
  516  pip install -e '.[qt]'
  517  napari test_data.zarr/
```

:+1:

**Comment by sofroniewn** [comment]
> In a fresh 3.8.5 environment, it works fine:

any idea @joshmoore what might be causing the environment difference? looks like it might be some vispy/ qt interplay. not clear if there is more digging we can do on our end, or if we just add that missing test and then close. let me know what you think?

**Comment by joshmoore** [comment]
I don't know of any particular reason this would be happening in the Python 3.6 environment. I'm happy to test things, but I assume there are diminishing returns.

**Comment by sofroniewn** [comment]
> I don't know of any particular reason this would be happening in the Python 3.6 environment. I'm happy to test things, but I assume there are diminishing returns.

Agreed. Let's close after we get that additional test in, and then we can always re-open if a new error appears. We'll be dropping Python 3.6 relatively soon too (likely the release after our next one)

**Comment by jni** [comment]
@sofroniewn I actually reproduced the second error reported by @joshmoore just yesterday:

```pytb
File "/usr/local/anaconda3/envs/demo/lib/python3.6/site-packages/vispy/app/backends/_qt.py", line 434, in _vispy_get_size
    g = self.geometry()
RuntimeError: wrapped C/C++ object of type CanvasBackendDesktop has been deleted
```

This was on napari 0.3.6 on conda-forge, Python 3.8. (was investigating #1304). I'm uncomfortable closing this issue until we understand where it comes from...

We should probably make a "vispy" tag for errors that have to do with GL or the canvas, as the errors are scattered a little all over the place...

**Comment by jni** [comment]
btw to reproduce I did:

```
conda create -n napari-cf --channel conda-forge python=3.8 napari=0.3.6
conda activate napari-cf
pip install ome-zarr==0.0.8  # 0.0.11 had the missing mask issue discussed on Zulip
napari https://s3.embassy.ebi.ac.uk/idr/zarr/v0.1/6001240.zarr
```

then I absentmindedly played around with the 3D volume for about 1-2 minutes while chatting with @joshmoore. 😂 Unfortunately I don't know what actually caused the error! One possibility is the macOS automatic graphics card switching? 🤷 

Anyway, as I said, I'd love to keep these open until we understand them, or maybe until VisPy makes a new release and then neither I nor @joshmoore can find these errors again.

**Comment by liu-ziyang** [comment]
I am not able to access the dataset to help reproduce this issue (https://s3.embassy.ebi.ac.uk/idr/zarr/v0.1/6001240.zarr), so far I had no luck in getting any error to show up with the dataset from the original report (test_data.zarr)

**Comment by joshmoore** [comment]
@ziyangczi : if you can let me know what you've tried and what error you are seeing, happy to try to set you up with access to the S3 data.

**Comment by liu-ziyang** [comment]
making a little progress on this, I used anaconda to set up the env as @jni had, I can see the same error when running `napari test_data.zarr`, so I made a bit more experimentation. I opened napari directly, and tried to drag and drop the test_data into the viewer afterwards, then I don't see a crash immediately, the error only happens when I try to switch to 3D mode.

interestingly, then I tried the same thing from pycharm while using the anaconda environment as the python interpreter, everything works fine, so there is something about the shell from anaconda that is glitching with vispy

from the message below, I suspect anaconda shell might be having some issue accessing GL resource/graphic card?

**Comment by liu-ziyang** [comment]
fwiw, the anaconda environments also gives me 
```
INFO:OpenGL.acceleratesupport:No OpenGL_accelerate module loaded: No module named 'OpenGL_accelerate'
/usr/local/anaconda3/envs/napari-cf/lib/python3.8/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 3 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```
which I have not seen from my own python environment

**Comment by sofroniewn** [comment]
I wonder if this is related to #1811. Did anyone ever check PySide2 vs PyQt5? That problem is PyQt5 only

**Comment by psobolewskiPhD** [comment]
I'm not able to reproduce this with 2D ome-zarr and switching to 3D on 0747da5660ddd1c9b4eba0dea74116c461b84236

Is this still an issue?

**Comment by joshmoore** [comment]
SOOO much has happened since then, I am more than happy for this to be closed and I'll re-open when/if it occurs. Thanks for the reminder, @psobolewskiPhD
