### ISSUE TITLE
Issue with using wrong pyrcc

### ISSUE THREAD

**Issue by hectormz** [napari/napari#1254]
## 🐛 Bug

I updated `napari` to post- #1229 and `napari` started failing when trying to build icons on Windows after importing napari:
https://github.com/napari/napari/blob/96e9722419a5b0adddbc14fe12c69a7d769f8758/napari/resources/build_icons.py#L178

## Cause

This may be a non-issue for others, but became an issue for me. Basically, each of these binaries were called:
`'pyrcc5.bat', 'pyrcc5', 'pyside2-rcc'`

and my vanilla python virtual environment didn't have `pyrcc5.bat`, but my base anaconda install was on path (bottom of list), and was the only source of `pyrcc5.bat`. This then failed, because it was found, but didn't have `pyqt5-sip` I believe. Rearranging so that `pyrcc5` was tried first fixed the issue for me.

This is a weird bug because I happened to have an Anaconda install on my path that happened to have `pyrcc5.bat`, and is kind of my fault. I don't know if it makes sense for you to rearrange the binaries to try, or ensure it's coming from the same environment. At least this is an explanation for anyone else getting a similar error:

```
subprocess.CalledProcessError: Command '['pyrcc5.bat', '-o', 'XXX\\lib\\site-packages\\napari\\resources\\_qt_resources_0.3.1_pyqt5_5.14.0.py', 'XXX\\lib\\site-packages\\napari\\resources\\res.qrc']' returned non-zero exit status 1.
```

@tlambert03

**Comment by tlambert03** [comment]
wow!   \*shakes fist\*
thank you for your _very_ helpful debugging!

so wait... you _do_ have a binary called `pyrcc5` on windows?  Can you tell exactly where that one was coming from?  (i.e. was it from pyqt5 installed in your environment?  with conda?  with pip?). I don't _think_ it would be a problem to just try pyrcc5 first... but need to check some things.  I think it should also be possible to check in the environment first...

**Comment by hectormz** [comment]
I was losing my mind as I tried to figure it out. I thought I just had some incompatible `pyqt5` version.

From within my virtual environment:
```
(venv) λ where pyrcc5
XXX\venv\Scripts\pyrcc5.exe
XXX\AppData\Local\Programs\Python\Python38\Scripts\pyrcc5.exe
XXX\AppData\Local\Programs\Python\Python37\Scripts\pyrcc5.exe
XXX\Anaconda3\Library\bin\pyrcc5.bat
```

I believe `pyrcc5.exe` is coming from `pyqt5` or `pyqt5-sip` installed in those environments

**Comment by tlambert03** [comment]
yeah I feel your pain!  😂 thanks again.  And just to double check, the pyqt5 that is installed in `venv\Scripts` and `Python<38|37>\Scripts` came from pip right?

**Comment by hectormz** [comment]
Correct. Completely pip installs

**Comment by VolkerH** [comment]
running into the same issue. Clean conda environments, `pip install napari` and end up with:

```
(cp4rc1) λ napari
Traceback (most recent call last):
  File "C:\Users\Volker\Anaconda3\envs\napari\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Volker\Anaconda3\envs\napari\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Volker\Anaconda3\envs\napari\lib\site-packages\PyQt5\pyrcc_main.py", line 21, in <module>
    from PyQt5.QtCore import PYQT_VERSION_STR, QDir, QFile
ImportError: DLL load failed: The specified procedure could not be found.
Traceback (most recent call last):
  File "c:\users\volker\anaconda3\envs\cp4rc1\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\volker\anaconda3\envs\cp4rc1\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Volker\Anaconda3\envs\cp4rc1\Scripts\napari.exe\__main__.py", line 4, in <module>
  File "c:\users\volker\anaconda3\envs\cp4rc1\lib\site-packages\napari\__init__.py", line 50, in <module>
    from .viewer import Viewer
  File "c:\users\volker\anaconda3\envs\cp4rc1\lib\site-packages\napari\viewer.py", line 6, in <module>
    from ._qt.qt_update_ui import QtUpdateUI
  File "c:\users\volker\anaconda3\envs\cp4rc1\lib\site-packages\napari\_qt\__init__.py", line 5, in <module>
    import_resources()
  File "c:\users\volker\anaconda3\envs\cp4rc1\lib\site-packages\napari\resources\__init__.py", line 119, in import_resources
    respath = build_pyqt_resources(fspath(target_file), overwrite=overwrite)
  File "c:\users\volker\anaconda3\envs\cp4rc1\lib\site-packages\napari\resources\build_icons.py", line 178, in build_pyqt_resources
    check_call([binary, '-o', out_path, qrc_path])
  File "c:\users\volker\anaconda3\envs\cp4rc1\lib\subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['pyrcc5.bat', '-o', 'c:\\users\\volker\\anaconda3\\envs\\cp4rc1\\lib\\site-packages\\napari\\resources\\_qt_resources_0.3.1_pyside2_5.14.2.py', 'c:\\users\\volker\\anaconda3\\envs\\cp4rc1\\lib\\site-packages\\napari\\resources\\res.qrc']' returned non-zero exit status 1.
```

**Comment by jni** [comment]
@tlambert03 I guess one way to prevent this is to only look for executables sitting next to `sys.executable`?

**Comment by tlambert03** [comment]
@hectormz @VolkerH , can you guys try deleting your `_qt_resources.py` file and replace the bit in `napari/resources/build_icons.py` [at line 176](https://github.com/napari/napari/blob/f0ab04af8bf3854325af1e44b5214c4710cab980/napari/resources/build_icons.py#L176-L187) with the following:
```python
    for bin_name in ('pyrcc5', 'pyside2-rcc'):
        binary = shutil.which(bin_name)
        if binary:
            check_call([binary, '-o', out_path, qrc_path])
            break
    else:
        raise FileNotFoundError(
            "Unable to find an executable to build Qt resources (icons).\n"
            "Tried: 'pyrcc5.bat', 'pyrcc5', 'pyside2-rcc'.\n"
            "Please open issue at https://github.com/napari/napari/issues/."
        )
```

in my test on windows `shutil.which` was able to find both `pyrcc5.bat` and `pyrcc5.exe` and prefers things higher up on the PATH.

**Comment by hectormz** [comment]
@tlambert03 Works for me!

**Comment by tlambert03** [comment]
thanks for testing!

**Comment by sfcaracciolo** [comment]
> 
> 
> @hectormz @VolkerH , can you guys try deleting your `_qt_resources.py` file and replace the bit in `napari/resources/build_icons.py` [at line 176](https://github.com/napari/napari/blob/f0ab04af8bf3854325af1e44b5214c4710cab980/napari/resources/build_icons.py#L176-L187) with the following:
> 
> ```python
>     for bin_name in ('pyrcc5', 'pyside2-rcc'):
>         binary = shutil.which(bin_name)
>         if binary:
>             check_call([binary, '-o', out_path, qrc_path])
>             break
>     else:
>         raise FileNotFoundError(
>             "Unable to find an executable to build Qt resources (icons).\n"
>             "Tried: 'pyrcc5.bat', 'pyrcc5', 'pyside2-rcc'.\n"
>             "Please open issue at https://github.com/napari/napari/issues/."
>         )
> ```
> 
> in my test on windows `shutil.which` was able to find both `pyrcc5.bat` and `pyrcc5.exe` and prefers things higher up on the PATH.

Hi,

I have same error than @hectormz, but I can't found the `_qt_resources.py` file in `napari/resources/` to delete it. Besides, I'm not sure where replace the code fragment in `build_icons.py` (at line 176 I see `build_pyqt_resources` definition). I tried copy/paste at line 209 (after `qrc_path` assignment) but doesn't work.

Thanks for your help!

**Comment by tlambert03** [comment]
Hi @sfcaracciolo, this is a pretty old issue, and there should no longer be a need to edit `build_icons.py` since #1261 has merged...  Is this an old install/environment you're working in?  Can you provide the output of your `napari --info`?   Does it happen if you create a new environment and reinstall napari?

**Comment by sfcaracciolo** [comment]
> 
> 
> Hi @sfcaracciolo, this is a pretty old issue, and there should no longer be a need to edit `build_icons.py` since #1261 has merged... Is this an old install/environment you're working in? Can you provide the output of your `napari --info`? Does it happen if you create a new environment and reinstall napari?

Indeed, if I create a new venv the problem is solved, thanks! Probably, the issue is related to my original venv because is a Intel distro in order to use MKL. Unfortunately, napari installation upgraded Numpy and I lost the MKL support. Maybe, in this case is better separated both projects.

Thanks again @tlambert03 !

**Comment by tlambert03** [comment]
>  Unfortunately, napari installation upgraded Numpy and I lost the MKL support.

hmmm... well that's no good either.  i can play with this later... but if you pre-install just numpy with `conda` or use conda to install napari, are you able to keep MKL?

**Comment by sfcaracciolo** [comment]
> 
> 
> > Unfortunately, napari installation upgraded Numpy and I lost the MKL support.
> 
> hmmm... well that's no good either. i can play with this later... but if you pre-install just numpy with `conda` or use conda to install napari, are you able to keep MKL?

Hi @tlambert03,

At the moment I don't use conda, but I created a new venv of python intel distro, then I installed napari and it works. Finally, I executed my requirements.txt in order to use my project and MKL it´s ok. I don't know why doesn't work when I install napari after to the other packages.

Good luck and thanks!

**Comment by tlambert03** [comment]
I see...  if pip doesn't see `numpy>=1.10.0` from PyPI when it tries to install napari, it will likely overwrite whatever is already there.  You might have better luck with conda, which is pretty good about [compatibility with MKL](https://docs.anaconda.com/mkl-optimizations/).  cheers

**Comment by ajitjohnson** [comment]
I still get a similar issue on a windows machine.

I get this within a fresh conda installation. I tried uninstalling and reinstalling anaconda as well. 

However, note that this issue only exists in certain computers. I know of 2 machines where I have got this issue and 3 more, where I did not encounter this issue (taking only about windows).

Any help is much appreciated. Thank you :) 

```
c:\users\ajn16\.conda\envs\scimap\lib\site-packages\napari\__init__.py:44: UserWarning: 
    napari was tested with QT library `>=5.12.3`.
    The version installed is 5.9.3. Please report any issues with this
    specific QT version at https://github.com/Napari/napari/issues.
    
  warn(message=warn_message)
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-1-1e1049a33073> in <module>
----> 1 import napari

c:\users\ajn16\.conda\envs\scimap\lib\site-packages\napari\__init__.py in <module>
     58 # decorated with keybindings during that process, but it is not directly needed
     59 # by our users and so is deleted below
---> 60 from . import _viewer_key_bindings  # noqa: F401
     61 from ._qt import gui_qt
     62 from .plugins.io import save_layers

c:\users\ajn16\.conda\envs\scimap\lib\site-packages\napari\_viewer_key_bindings.py in <module>
      1 import numpy as np
      2 
----> 3 from .viewer import Viewer
      4 
      5 

c:\users\ajn16\.conda\envs\scimap\lib\site-packages\napari\viewer.py in <module>
      7 
      8 from . import __version__
----> 9 from ._qt.qt_main_window import Window
     10 from ._qt.qt_viewer import QtViewer
     11 from ._qt.qthreading import create_worker, wait_for_workers_to_quit

c:\users\ajn16\.conda\envs\scimap\lib\site-packages\napari\_qt\__init__.py in <module>
      3 from .widgets.qt_range_slider import QHRangeSlider, QVRangeSlider
      4 
----> 5 import_resources()

c:\users\ajn16\.conda\envs\scimap\lib\site-packages\napari\resources\__init__.py in import_resources(version, overwrite)
    117     # regenerated.
    118     overwrite = overwrite or bool(environ.get('NAPARI_REBUILD_RESOURCES'))
--> 119     respath = build_pyqt_resources(fspath(target_file), overwrite=overwrite)
    120 
    121     # import the python resources file and add to sys.modules

c:\users\ajn16\.conda\envs\scimap\lib\site-packages\napari\resources\build_icons.py in build_pyqt_resources(out_path, overwrite)
    216     #     3.7.4/envs/napari-pyqt5
    217     #     napari-pyqt5
--> 218     for name in _find_rcc_or_raise():
    219         try:
    220             check_call([name, '-o', out_path, qrc_path])

c:\users\ajn16\.conda\envs\scimap\lib\site-packages\napari\resources\build_icons.py in _find_rcc_or_raise()
    168             yield rcc_binary
    169     raise FileNotFoundError(
--> 170         "Unable to find an executable to build Qt resources (icons).\n"
    171         "Tried: 'pyrcc5.bat', 'pyrcc5', 'pyside2-rcc'.\n"
    172         "Please open issue at https://github.com/napari/napari/issues/."

FileNotFoundError: Unable to find an executable to build Qt resources (icons).
Tried: 'pyrcc5.bat', 'pyrcc5', 'pyside2-rcc'.
Please open issue at https://github.com/napari/napari/issues/.
```

**Comment by tlambert03** [comment]
hi @ajitjohnson, sorry that you're running into this.  can you tell us a little more about how you're installing napari?  You say it's a fresh conda installation, but are you creating a fresh environment to install napari?  are you installing via pip?  or conda?
The fact that it's saying "` The version installed is 5.9.3.`" suggests that maybe you're installing this into an existing environment, or something other than:
```
conda create -y -n napari-env python=3.8
conda activate napari-env
pip install napari[all]
```

**Comment by ajitjohnson** [comment]
Hi @tlambert03 thank you for your response. 

Previously I did this:

```
conda create --name napari-env python=3.7
pip install notebook napari pyqt5
```

However, after a bit of digging around, I realized that the issue was with `pyqt5`.  So if I do the following it works:

```
conda create --name napari-env python=3.7
pip install notebook napari pyside2
```

When I import `napari` I still get the following warning though. But it works!

```
C:\Users\ajn16\.conda\envs\napari-env5\lib\site-packages\napari\__init__.py:44: UserWarning:
    napari was tested with QT library `>=5.12.3`.
    The version installed is 5.9.3. Please report any issues with this
    specific QT version at https://github.com/Napari/napari/issues.
```

The warning goes away when I use `python 3.8`. Additionally, `pyqt5` works with `python 3.8`

So this works:

```
conda create --name napari-env python=3.8
pip install notebook napari pyqt5
```

Wonder if there is some problem with the path or something.

Having said that I have used napari and pyqt5 previously with `python=3.7` and it still works on other workstations.

**Comment by tlambert03** [comment]
yeah, we still support python 3.7, and it _should_ work with either pyqt5 or pyside2 ... the main variable here is notebook (and it's qt dependencies).  So, I'm not sure why you're seeing it on some computers and not the others, but perhaps on the computers where you _do_ see it they , could you try first installing `pip install napari[all]` and _then_ installing notebook after it's already installed?  and then run `napari --info` (or `conda list`) to see what you end up with?  In the end, this is a qt-issue, and having multiple qt backends (like _both_ pyside2 and pyqt5)  installed can be problematic.  You can also run `conda list` on the working PC environment and send the results along with `conda list` from a broken PC environment and I can try to help figure out what's going on

**Comment by ajitjohnson** [comment]
Hi @tlambert03 I do not think it is an issue with the notebook. I have tried without notebook previously, and I repeated it again. 

See below for a step by step output of things I did in the working and broken PC. Hope it helps :) 

## Broken PC (reproducing the error and running `conda list`)

```
conda create --name napari python=3.7
conda activate napari
pip install napari pyqt5

python
>>> import napari

# I get the error as expected

conda list

# packages in environment at C:\Users\ajn16\.conda\envs\napari:
#
# Name                    Version                   Build  Channel
alabaster                 0.7.12                   pypi_0    pypi
appdirs                   1.4.4                    pypi_0    pypi
babel                     2.9.0                    pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
ca-certificates           2020.11.8            h5b45459_0    conda-forge
cachey                    0.2.1                    pypi_0    pypi
certifi                   2020.11.8        py37h03978a9_0    conda-forge
chardet                   3.0.4                    pypi_0    pypi
colorama                  0.4.4                    pypi_0    pypi
dask                      2.30.0                   pypi_0    pypi
decorator                 4.4.2                    pypi_0    pypi
docutils                  0.16                     pypi_0    pypi
heapdict                  1.0.1                    pypi_0    pypi
idna                      2.10                     pypi_0    pypi
imagesize                 1.2.0                    pypi_0    pypi
importlib-metadata        3.1.0                    pypi_0    pypi
ipykernel                 5.3.4                    pypi_0    pypi
ipython                   7.19.0                   pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
jedi                      0.17.2                   pypi_0    pypi
jinja2                    2.11.2                   pypi_0    pypi
jupyter-client            6.1.7                    pypi_0    pypi
jupyter-core              4.7.0                    pypi_0    pypi
markupsafe                1.1.1                    pypi_0    pypi
napari                    0.4.2                    pypi_0    pypi
napari-plugin-engine      0.1.8                    pypi_0    pypi
napari-svg                0.1.4                    pypi_0    pypi
numpy                     1.19.4                   pypi_0    pypi
numpydoc                  1.1.0                    pypi_0    pypi
openssl                   1.1.1h               he774522_0    conda-forge
packaging                 20.7                     pypi_0    pypi
parso                     0.7.1                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    8.0.1                    pypi_0    pypi
pip                       20.3               pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.8                    pypi_0    pypi
psutil                    5.7.3                    pypi_0    pypi
pygments                  2.7.2                    pypi_0    pypi
pyparsing                 2.4.7                    pypi_0    pypi
pyqt5                     5.15.2                   pypi_0    pypi
pyqt5-sip                 12.8.1                   pypi_0    pypi
python                    3.7.8           h7840368_3_cpython    conda-forge
python-dateutil           2.8.1                    pypi_0    pypi
python_abi                3.7                     1_cp37m    conda-forge
pytz                      2020.4                   pypi_0    pypi
pywin32                   300                      pypi_0    pypi
pyyaml                    5.3.1                    pypi_0    pypi
pyzmq                     20.0.0                   pypi_0    pypi
qtconsole                 5.0.1                    pypi_0    pypi
qtpy                      1.9.0                    pypi_0    pypi
requests                  2.25.0                   pypi_0    pypi
scipy                     1.5.4                    pypi_0    pypi
setuptools                49.6.0           py37hf50a25e_2    conda-forge
six                       1.15.0                   pypi_0    pypi
snowballstemmer           2.0.0                    pypi_0    pypi
sphinx                    3.3.1                    pypi_0    pypi
sphinxcontrib-applehelp   1.0.2                    pypi_0    pypi
sphinxcontrib-devhelp     1.0.2                    pypi_0    pypi
sphinxcontrib-htmlhelp    1.0.3                    pypi_0    pypi
sphinxcontrib-jsmath      1.0.1                    pypi_0    pypi
sphinxcontrib-qthelp      1.0.3                    pypi_0    pypi
sphinxcontrib-serializinghtml 1.1.4                    pypi_0    pypi
sqlite                    3.33.0               he774522_1    conda-forge
tifffile                  2020.11.26               pypi_0    pypi
tornado                   6.1                      pypi_0    pypi
traitlets                 5.0.5                    pypi_0    pypi
typing-extensions         3.7.4.3                  pypi_0    pypi
urllib3                   1.26.2                   pypi_0    pypi
vc                        14.1                 h869be7e_1    conda-forge
vs2015_runtime            14.16.27012          h30e32a0_2    conda-forge
wcwidth                   0.2.5                    pypi_0    pypi
wheel                     0.35.1             pyh9f0ad1d_0    conda-forge
wincertstore              0.2             py37hc8dfbb8_1005    conda-forge
wrapt                     1.12.1                   pypi_0    pypi
zipp                      3.4.0                    pypi_0    pypi
```

## Broken PC with working installation using `pyside2`

```
conda create --name napari_1 python=3.7
conda activate napari_1
pip install napari pyside2

python
>>> import napari

# Loads napari with the following warning
C:\Users\ajn16\.conda\envs\napari_1\lib\site-packages\napari\__init__.py:44: UserWarning:
    napari was tested with QT library `>=5.12.3`.
    The version installed is 5.9.3. Please report any issues with this
    specific QT version at https://github.com/Napari/napari/issues.

  warn(message=warn_message)

conda list

# packages in environment at C:\Users\ajn16\.conda\envs\napari_1:
#
# Name                    Version                   Build  Channel
alabaster                 0.7.12                   pypi_0    pypi
appdirs                   1.4.4                    pypi_0    pypi
babel                     2.9.0                    pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
ca-certificates           2020.11.8            h5b45459_0    conda-forge
cachey                    0.2.1                    pypi_0    pypi
certifi                   2020.11.8        py37h03978a9_0    conda-forge
chardet                   3.0.4                    pypi_0    pypi
colorama                  0.4.4                    pypi_0    pypi
dask                      2.30.0                   pypi_0    pypi
decorator                 4.4.2                    pypi_0    pypi
docutils                  0.16                     pypi_0    pypi
heapdict                  1.0.1                    pypi_0    pypi
idna                      2.10                     pypi_0    pypi
imagesize                 1.2.0                    pypi_0    pypi
importlib-metadata        3.1.0                    pypi_0    pypi
ipykernel                 5.3.4                    pypi_0    pypi
ipython                   7.19.0                   pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
jedi                      0.17.2                   pypi_0    pypi
jinja2                    2.11.2                   pypi_0    pypi
jupyter-client            6.1.7                    pypi_0    pypi
jupyter-core              4.7.0                    pypi_0    pypi
markupsafe                1.1.1                    pypi_0    pypi
napari                    0.4.2                    pypi_0    pypi
napari-plugin-engine      0.1.8                    pypi_0    pypi
napari-svg                0.1.4                    pypi_0    pypi
numpy                     1.19.4                   pypi_0    pypi
numpydoc                  1.1.0                    pypi_0    pypi
openssl                   1.1.1h               he774522_0    conda-forge
packaging                 20.7                     pypi_0    pypi
parso                     0.7.1                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    8.0.1                    pypi_0    pypi
pip                       20.3               pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.8                    pypi_0    pypi
psutil                    5.7.3                    pypi_0    pypi
pygments                  2.7.2                    pypi_0    pypi
pyparsing                 2.4.7                    pypi_0    pypi
python                    3.7.8           h7840368_3_cpython    conda-forge
python-dateutil           2.8.1                    pypi_0    pypi
python_abi                3.7                     1_cp37m    conda-forge
pytz                      2020.4                   pypi_0    pypi
pywin32                   300                      pypi_0    pypi
pyyaml                    5.3.1                    pypi_0    pypi
pyzmq                     20.0.0                   pypi_0    pypi
qtconsole                 5.0.1                    pypi_0    pypi
qtpy                      1.9.0                    pypi_0    pypi
requests                  2.25.0                   pypi_0    pypi
scipy                     1.5.4                    pypi_0    pypi
setuptools                49.6.0           py37hf50a25e_2    conda-forge
six                       1.15.0                   pypi_0    pypi
snowballstemmer           2.0.0                    pypi_0    pypi
sphinx                    3.3.1                    pypi_0    pypi
sphinxcontrib-applehelp   1.0.2                    pypi_0    pypi
sphinxcontrib-devhelp     1.0.2                    pypi_0    pypi
sphinxcontrib-htmlhelp    1.0.3                    pypi_0    pypi
sphinxcontrib-jsmath      1.0.1                    pypi_0    pypi
sphinxcontrib-qthelp      1.0.3                    pypi_0    pypi
sphinxcontrib-serializinghtml 1.1.4                    pypi_0    pypi
sqlite                    3.33.0               he774522_1    conda-forge
tifffile                  2020.11.26               pypi_0    pypi
tornado                   6.1                      pypi_0    pypi
traitlets                 5.0.5                    pypi_0    pypi
typing-extensions         3.7.4.3                  pypi_0    pypi
urllib3                   1.26.2                   pypi_0    pypi
vc                        14.1                 h869be7e_1    conda-forge
vs2015_runtime            14.16.27012          h30e32a0_2    conda-forge
wcwidth                   0.2.5                    pypi_0    pypi
wheel                     0.35.1             pyh9f0ad1d_0    conda-forge
wincertstore              0.2             py37hc8dfbb8_1005    conda-forge
wrapt                     1.12.1                   pypi_0    pypi
zipp                      3.4.0                    pypi_0    pypi

```

## Working PC 

```
conda create --name napari python=3.7
conda activate napari
pip install napari pyqt5

python
>>> import napari

# loads without any warning

conda list

# packages in environment at C:\Users\LSP\.conda\envs\napari:
#
# Name                    Version                   Build  Channel
alabaster                 0.7.12                   pypi_0    pypi
appdirs                   1.4.4                    pypi_0    pypi
babel                     2.9.0                    pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
ca-certificates           2020.10.14                    0
cachey                    0.2.1                    pypi_0    pypi
certifi                   2020.11.8        py37haa95532_0
chardet                   3.0.4                    pypi_0    pypi
colorama                  0.4.4                    pypi_0    pypi
dask                      2.30.0                   pypi_0    pypi
decorator                 4.4.2                    pypi_0    pypi
docutils                  0.16                     pypi_0    pypi
freetype-py               2.2.0                    pypi_0    pypi
heapdict                  1.0.1                    pypi_0    pypi
idna                      2.10                     pypi_0    pypi
imageio                   2.9.0                    pypi_0    pypi
imagesize                 1.2.0                    pypi_0    pypi
importlib-metadata        3.1.0                    pypi_0    pypi
ipykernel                 5.3.4                    pypi_0    pypi
ipython                   7.19.0                   pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
jedi                      0.17.2                   pypi_0    pypi
jinja2                    2.11.2                   pypi_0    pypi
jupyter-client            6.1.7                    pypi_0    pypi
jupyter-core              4.7.0                    pypi_0    pypi
markupsafe                1.1.1                    pypi_0    pypi
napari                    0.4.2                    pypi_0    pypi
napari-plugin-engine      0.1.8                    pypi_0    pypi
napari-svg                0.1.4                    pypi_0    pypi
numpy                     1.19.4                   pypi_0    pypi
numpydoc                  1.1.0                    pypi_0    pypi
openssl                   1.1.1h               he774522_0
packaging                 20.7                     pypi_0    pypi
parso                     0.7.1                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    8.0.1                    pypi_0    pypi
pip                       20.2.4           py37haa95532_0
prompt-toolkit            3.0.8                    pypi_0    pypi
psutil                    5.7.3                    pypi_0    pypi
pygments                  2.7.2                    pypi_0    pypi
pyopengl                  3.1.5                    pypi_0    pypi
pyparsing                 2.4.7                    pypi_0    pypi
pyqt5                     5.15.2                   pypi_0    pypi
pyqt5-sip                 12.8.1                   pypi_0    pypi
python                    3.7.9                h60c2a47_0
python-dateutil           2.8.1                    pypi_0    pypi
pytz                      2020.4                   pypi_0    pypi
pywin32                   300                      pypi_0    pypi
pyyaml                    5.3.1                    pypi_0    pypi
pyzmq                     20.0.0                   pypi_0    pypi
qtconsole                 5.0.1                    pypi_0    pypi
qtpy                      1.9.0                    pypi_0    pypi
requests                  2.25.0                   pypi_0    pypi
scipy                     1.5.4                    pypi_0    pypi
setuptools                50.3.1           py37haa95532_1
six                       1.15.0                   pypi_0    pypi
snowballstemmer           2.0.0                    pypi_0    pypi
sphinx                    3.3.1                    pypi_0    pypi
sphinxcontrib-applehelp   1.0.2                    pypi_0    pypi
sphinxcontrib-devhelp     1.0.2                    pypi_0    pypi
sphinxcontrib-htmlhelp    1.0.3                    pypi_0    pypi
sphinxcontrib-jsmath      1.0.1                    pypi_0    pypi
sphinxcontrib-qthelp      1.0.3                    pypi_0    pypi
sphinxcontrib-serializinghtml 1.1.4                    pypi_0    pypi
sqlite                    3.33.0               h2a8f88b_0
tifffile                  2020.11.26               pypi_0    pypi
toolz                     0.11.1                   pypi_0    pypi
tornado                   6.1                      pypi_0    pypi
traitlets                 5.0.5                    pypi_0    pypi
typing-extensions         3.7.4.3                  pypi_0    pypi
urllib3                   1.26.2                   pypi_0    pypi
vc                        14.1                 h0510ff6_4
vispy                     0.6.6                    pypi_0    pypi
vs2015_runtime            14.16.27012          hf0eaf9b_3
wcwidth                   0.2.5                    pypi_0    pypi
wheel                     0.35.1             pyhd3eb1b0_0
wincertstore              0.2                      py37_0
wrapt                     1.12.1                   pypi_0    pypi
zipp                      3.4.0                    pypi_0    pypi
zlib                      1.2.11               h62dcd97_4
```

**Comment by tlambert03** [comment]
ok thanks.  The fact that you're still getting the qt 5.9 notice in the "broken" pyside2 install _and_ the fact that pyside2 didn't end up in your `conda list` suggests that you might have some environment/path pollution, with an outdate "global" pyqt somewhere that is getting chosen instead of the ones you're installing.  This might very well lead to a "working" environment with pyside2 (that really just isn't using it at all ... i'd be curious what happens if you did `pip install napari` alone without _any_ backend ...)

This is all starting to look a lot like https://github.com/napari/napari/issues/1112
So, as with that case, I'd be curious to see the output of your `python -c "import sys; print(sys.path)"`
If you do find a global `site-packages` folder somewhere on your path (as in #1112), then [read through this comment](https://github.com/napari/napari/issues/1112#issuecomment-609759779) and see if anything in there is useful.  and feel free to paste the output of `sys.path` here

**Comment by ajitjohnson** [comment]
@tlambert03 You were right, I think `python 3.7` outside conda was causing the issue. Here is what I did to fix it, 

1. Uninstalled native python through the add/remove programs interface in windows 
2. removed the native version from PATH [like so](https://docs.oracle.com/en/database/oracle/r-enterprise/1.5.1/oread/creating-and-modifying-environment-variables-on-windows.html#GUID-DD6F9982-60D5-48F6-8270-A27EC53807D0)
3. Deleted the entire python folder that was in the PATH- Mine was within `C:\Users\ajn16\AppData\Roaming\Python`
4. Restarted the computer.

After that,

```
conda create --name napari_new python=3.7
conda activate napari_new
pip install napari pyqt5

python
>>> import napari

# loads napari without any warnings. YEYY!!
```

Thanks for figuring this out @tlambert03 and hope it is helpful for others who find this thread :) 

Best,
Ajit.

**Comment by tlambert03** [comment]
Hooray!  I'm glad you were able to fix it, and thanks for posting your process here for others.
