### ISSUE TITLE
Support for Zarr files with multiple datasets (groups)

### ISSUE THREAD

**Issue by ximeg** [napari/napari#1406]
## 🚀 Feature

`napari` 0.3.5 does not open a Zarr folder if it contains several datasets (for example, saved with `dask.array.to_zarr(data, 'data.zarr', component='myimage')`, where 'myimage' is the name of the group). `napari` says

> 'Could not find a format to read the specified file in single-image mode'*.

If the argument `component` of `to_zarr` is omitted, the resulting image can be opened by `napari` with menu 'file->open folder'.

It is easy to specify the group to be opened as it is represented by a folder in the file system, inside of the .zarr directory.

## Motivation

During data analysis I often want to have several related datasets saved together in a single Zarr container. For example, I may want to do dark frame and flat field correction of an image stack, and then store the dark frame and the flat frame alongside with the image stack. This way I can have a pre-processed dataset that contains data used for pre-processing, so I can restore the uncorrected raw dataset, if necessary.

## Pitch

I want to open a group (e.g. named 'myimage') from a Zarr folder using command line
```
$ napari data.zarr/path/to/myimage
```
or using menu option 'file->open folder'.

## Alternatives

Currently I use this as a workaround:

```python
import zarr as z
import napari

g = z.open_group('data.zarr')
with napari.gui_qt(): 
    napari.view_image(g['myimage']) 
```

**Comment by ximeg** [comment]
I wrote as simple command-line script `np.py` that I use as workaround:

```python

"""Open Zarr image(s) in napari

Usage:
  np <filename.zarr>...
"""
import zarr
import napari

import os.path as p
from docopt import docopt

import re


def np():
    """
    Command line tool to start napari with multi-image Zarr
    and/or multiple zarr archives
    """
    arguments = docopt(doc=__doc__)

    arrays = []
    for f in arguments['<filename.zarr>']:
        try:
            data = zarr.open_array(f, 'r')
            arrays.append(dict(data=data, name=get_zarr_name(f)))
        except ValueError as e:
            z = zarr.open(f, 'r')
            for name, data in z.arrays():
                name = p.join(get_zarr_name(f), name)
                arrays.append(dict(data=data, name=name))

    with napari.gui_qt():
        v = napari.viewer.Viewer()
        for ar in arrays:
            v.add_image(**ar)


def get_zarr_name(fname):
    fname = fname.rstrip('/').rstrip('\\')
    pattern = r'(.*\/)?(?P<name>.*\.zarr\/?.*)\/?\\?'
    match = re.search(pattern, fname, re.IGNORECASE)

    if match:
        return match.group('name')


if __name__ == '__main__':
    np()

```

**Comment by jni** [comment]
@ximeg thanks for reporting!

We are purposefully keeping our "default" reader plugin slim. Right now, this means that for a zarr file, we just do `dask.array.from_zarr()` if we see a `.zarr` extension. The *correct* fix for this would be to develop a more full-feature zarr reader plugin, creatively called `napari-zarr-io`, for example. User-installed plugins always have a higher priority than the built-in.

Thanks to @tlambert03, we have documentation on how to create an IO plugin here:

https://napari.org/docs/plugins/for_plugin_developers.html

We would be super happy to help you (or anyone else who wants to tackle this... @rabernat? :grimacing: :wave:) write such a plugin if you run into problems with the guide above — it would help us improve the guide for everyone!

**Comment by manzt** [comment]
One thing to keep in mind here is that a zarr store may implement the [multiscale extension]( https://github.com/zarr-developers/zarr-specs/issues/50), where arrays within the same group may be intended to be visualized as a single image layer (rather than separate layers for each array). 

It should be simple to check for this use case by adding a check for `"multiscales"` property of the `.zattrs` for a desired group. I think the question then is whether this plugin should return `None` for the `@napari_hook_implementation`, or try to deal with that use case as well. The reader provided by `ome-zarr-py` handles this to my knowledge currently. 

Also happy to help/give feedback. Not being a napari "power user", my insight into the desired use case isn't the best, but I do have some familiarity with zarr.

EDIT: One last thought. Zarr groups can contain a nested hierarchy, so whether the reader finds all arrays in a hierarchy and adds them as image layers, or just the arrays within the first level of the group. I think the latter makes the most sense and would be more simple to implement.

**Comment by manzt** [comment]
I've started working on [`napari-zarr-io`](https://github.com/manzt/napari-zarr-io) to address this issue. I've tried to be conservative with what `.zarr` paths the plugin will yield a reader, handling paths to groups or arrays referenced from a local `zarr.DirectoryStore`.

**Comment by sofroniewn** [comment]
@manzt @jni @tlambert03 can this now be closed given the #1441 has merged? Or are there parts of this not addressed there?

**Comment by manzt** [comment]
#1441 extends napari's previous heuristics for loading arrays and groups in a `zarr.DirectoryStore`s which are:

1.) if path is for `zarr.Array`, create an image layer.
2.) if path is for `zarr.Group`, try to load arrays in group as a pyramid image layer (sort array keys an create list of dask arrays).

Looking at the `np` snippet above from @ximeg, it seems a different behavior is desired when a path is for a group (load arrays in group as _separate_ image layers -- not pyramid). But, #1441 addresses the case of opening an array directly from a nested path. 

Probably up for debate what the behavior should be when a path leads to a `zarr.Group`. There is an multiscale extension for zarr now, which napari doesn't currently (but could) use for deciding what to do with groups. But as @jni said originally, all this extra logic for deciding what to do with zarr is probably best suited for a plugin IMO.

**Comment by ximeg** [comment]
@manzt Amazing progress, thank you very much for a very quick fix. I tested it and it works - I can specify a path to an array (or arrays) inside of the .zarr directory, or use menu file->open folder, and napari displays the content! Thank you!

```sh
$ napari --version
napari version 0.3.6.dev30+gfc12b65
# works
$ napari timelapse.zarr/dark_subtraction
# works with two images
$ napari timelapse.zarr/dark_subtraction timelapse.zarr/dark_frame

# even this works
$ cd timelapse.zarr/
$ napari dark_subtraction dark_frame
```

However, as I read above, you assume that `zarr.Group` is a pyramid, which is not the case in my data. As a result, napari crashes if I try to open my .zarr folder directly. The error message is a bit cryptic for me:

```sh
$ napari timelapse.zarr
Traceback (most recent call last):
  File "/home/ximeg/.anaconda3/envs/sandbox/bin/napari", line 33, in <module>
    sys.exit(load_entry_point('napari', 'console_scripts', 'napari')())
  File "/home/ximeg/dev/napari/napari/__main__.py", line 181, in main
    view_path(
  File "/home/ximeg/dev/napari/napari/view_layers.py", line 207, in view_path
    viewer.open(
  File "/home/ximeg/dev/napari/napari/components/add_layers_mixin.py", line 874, in open
    self._add_layers_with_plugins(
  File "/home/ximeg/dev/napari/napari/components/add_layers_mixin.py", line 941, in _add_layers_with_plugins
    new = self._add_layer_from_data(*_data)
  File "/home/ximeg/dev/napari/napari/components/add_layers_mixin.py", line 1013, in _add_layer_from_data
    layer = add_method(data, **(meta or {}))
  File "/home/ximeg/dev/napari/napari/components/add_layers_mixin.py", line 230, in add_image
    return self.add_layer(layers.Image(data, **kwargs))
  File "/home/ximeg/dev/napari/napari/layers/image/image.py", line 159, in __init__
    multiscale, data = guess_multiscale(data)
  File "/home/ximeg/dev/napari/napari/layers/image/_image_utils.py", line 69, in guess_multiscale
    raise ValueError(
ValueError: Input data should be an array-like object, or a sequence of arrays of decreasing size. Got arrays in incorrect order, shapes: [(20, 28), (8, 20, 28), (8,)]
```

I don't know whether this is an expected behavior... I decided to share my small test dataset (9KB)
[timelapse.zarr.zip](https://github.com/napari/napari/files/4935675/timelapse.zarr.zip):

```
# contents
timelapse.zarr/dark_subtraction   # stack of images (3D)
timelapse.zarr/dark_frame         # single image (2D)
timelapse.zarr/time               # time axis, 1D numpy array
```

As a workaround, I can manually specify path to each array inside using `find` or wildcards. If there are no 1D datasets inside, it works just fine, but it will crash upon encountering of a 1D array `timelapse.zarr/time` - I opened a separate issue #1471 for that.

```sh
$ rm -rf timelapse.zarr/time
# this works
$ napari timelapse.zarr/*
$ napari `find timelapse.zarr/ -type d`
```

As correctly stated above, opening of the root `.zarr` is a subject to debate. Some people might have a pyramid in there, others separate images.

**Comment by ximeg** [comment]
IMHO this issue can be closed. Once #1471 is resolved, one can easily open all images in a zarr directory
```
napari timelapse.zarr/*   # if separate images
napari timelapse.zarr     # if pyramid
```

**Comment by jni** [comment]
@ximeg @manzt 

> 2.) if path is for zarr.Group, try to load arrays in group as a pyramid image layer (sort array keys an create list of dask arrays).

> However, as I read above, you assume that zarr.Group is a pyramid, which is not the case in my data. As a result, napari crashes if I try to open my .zarr folder directly. 

I dunno, I feel like maybe we settled on (2) too quickly, since clearly it can cause issues. I suggest we do one of the following:

- if there is no multiscale metadata (see e.g. https://forum.image.sc/t/multiscale-arrays-v0-1/37930/2) and you have a group, then don't treat as multiscale, and instead treat as many different arrays, or
- if there is no multiscale metadata and you have a group, then *try to check* whether it is a pyramid, and if not, treat as many different arrays (equivalent to `napari timelapse.zarr/*`)

@ximeg 

> The error message is a bit cryptic for me:

You should have seen it [before we improved it](https://github.com/napari/napari/issues/1231)! 😂

**Comment by sofroniewn** [comment]
> I dunno, I feel like maybe we settled on (2) too quickly, since clearly it can cause issues. I suggest we do one of the following:
> 
> - if there is no multiscale metadata (see e.g. https://forum.image.sc/t/multiscale-arrays-v0-1/37930/2) and you have a group, then don't treat as multiscale, and instead treat as many different arrays, or
> - if there is no multiscale metadata and you have a group, then try to check whether it is a pyramid, and if not, treat as many different arrays (equivalent to napari timelapse.zarr/*)

I like the second option - it would involve putting the `guess_multiscale` outside of `Image` and into `add_image` too where if the `guess_multiscale` passes then I would just press on as before but if `guess_multiscale` fails then I would make one call to `add_image` for each array in the group.

I do worry this is becoming a bit magical though and wonder what the desired behavior above is and if that behavior can't be better achieved by two or three explicit function calls instead of guessing based on one function call. More real-world use cases would help here!

**Comment by ximeg** [comment]
@sofroniewn your proposal seems logical, I'm in support of this. It does not seem magical at all to me, though :)
