### ISSUE TITLE
Napari crashes when encounters a 1D array (in .zarr/ folder)

### ISSUE THREAD

**Issue by ximeg** [napari/napari#1471]
## 🐛 Bug

`napari file_1 file_2 ... file_n` would result in a crash if any of the files is a 1D array, as e.g. in `napari mydata.zarr/one-dimensional-array`.

## To Reproduce

1. Download and extract the test dataset (9KB) [timelapse.zarr.zip](https://github.com/napari/napari/files/4935727/timelapse.zarr.zip). It contains 3 numpy arrays with shapes (8, 20, 28), (20, 28), and (8,)
2. Run `napari timelapse.zarr/*` or `napari timelapse.zarr/time`
3. napari crashes on `timelapse.zarr/time`, which is a 1D numpy array

```sh
$ napari timelapse.zarr/*
Traceback (most recent call last):
  File "/home/ximeg/.anaconda3/envs/sandbox/bin/napari", line 33, in <module>
    sys.exit(load_entry_point('napari', 'console_scripts', 'napari')())
  File "/home/ximeg/dev/napari/napari/__main__.py", line 181, in main
    view_path(
  File "/home/ximeg/dev/napari/napari/view_layers.py", line 207, in view_path
    viewer.open(
  File "/home/ximeg/dev/napari/napari/components/add_layers_mixin.py", line 874, in open
    self._add_layers_with_plugins(
  File "/home/ximeg/dev/napari/napari/components/add_layers_mixin.py", line 941, in _add_layers_with_plugins
    new = self._add_layer_from_data(*_data)
  File "/home/ximeg/dev/napari/napari/components/add_layers_mixin.py", line 1013, in _add_layer_from_data
    layer = add_method(data, **(meta or {}))
  File "/home/ximeg/dev/napari/napari/components/add_layers_mixin.py", line 230, in add_image
    return self.add_layer(layers.Image(data, **kwargs))
  File "/home/ximeg/dev/napari/napari/layers/image/image.py", line 159, in __init__
    multiscale, data = guess_multiscale(data)
  File "/home/ximeg/dev/napari/napari/layers/image/_image_utils.py", line 63, in guess_multiscale
    raise ValueError(
ValueError: Input data should be an array-like object, or a sequence of arrays of decreasing size. Got arrays of single shape: ()
```

## Expected behavior

I think napari should show a warning, ignore the 1D dataset, and go on. Raising and error and crashing is annoying, especially if my objective is to see all images inside of a Zarr directory.

## Environment

```
napari: 0.3.6.dev30+gfc12b65
Platform: Linux-4.18.0-25-generic-x86_64-with-glibc2.10
Python: 3.8.3 (default, May 19 2020, 18:47:26) [GCC 7.3.0]
Qt: 5.14.2
PyQt5: 5.14.2
NumPy: 1.19.0
SciPy: 1.5.1
Dask: 2.20.0
VisPy: 0.6.4

GL version: 3.0 Mesa 18.2.8
MAX_TEXTURE_SIZE: 16384

Plugins:
- napari-plugin-engine: 0.1.6
- svg: 0.1.3
```

## Additional context

Related: #1406

**Comment by jni** [comment]
Thanks for the report @ximeg! This should definitely be fixed.

**Comment by sofroniewn** [comment]
> I think napari should show a warning, ignore the 1D dataset, and go on. Raising and error and crashing is annoying, especially if my objective is to see all images inside of a Zarr directory.

We should definitely fix - we could either ignore the 1D dataset or we could change `Image` to expand the dims of any 1D datasets that it receives so that you would see a `1xN` image on the screen, so that the following call works too

```python
viewer.add_image(np.ones(10))
```

which currently errors on

```python-traceback
Traceback (most recent call last):
  File "test-examples/1D_image.py", line 7, in <module>
    viewer.add_image(np.ones(10))
  File "/Users/nsofroniew/GitHub/napari/napari/components/add_layers_mixin.py", line 230, in add_image
    return self.add_layer(layers.Image(data, **kwargs))
  File "/Users/nsofroniew/GitHub/napari/napari/layers/image/image.py", line 159, in __init__
    multiscale, data = guess_multiscale(data)
  File "/Users/nsofroniew/GitHub/napari/napari/layers/image/_image_utils.py", line 64, in guess_multiscale
    'Input data should be an array-like object, or a sequence of '
ValueError: Input data should be an array-like object, or a sequence of arrays of decreasing size. Got arrays of single shape: ()
```

I like the `expand_dims` idea, curious what @jni thinks. We might revisit this when we have better support for 1D plots.

A full solution to your use case might require some of the changes mentioned here https://github.com/napari/napari/issues/1406#issuecomment-660178206

**Comment by jni** [comment]
> I like the expand_dims idea, curious what @jni thinks.

I'm into ignoring for now. I think it's very unlikely that these arrays are there to be seen as an image. More likely they are part of xarray groups to e.g. indicate scale along an axis. So I think it would be super weird to display them.

**Comment by ximeg** [comment]
I'm using the 1D datasets inside of Zarr to store some additional data, like e.g. a time axis. I am also thinking about saving data frames with some metadata or image analysis results. Yes, it would be really weird to display them as images.
