### ISSUE TITLE
Error with certain polygon data

### ISSUE THREAD

**Issue by jni** [napari/napari#1653]
## 🐛 Bug

I recently provided the Shapes layer with some funky data (result of an algorithm converging incorrectly), and got a rather mysterious error. It might well be VisPy's fault, but I don't have time to investigate now so I'll note it here for followup.

<details>

<summary>
Geometry error traceback
</summary>

```pytb
Traceback (most recent call last):
  File "/Users/jni/projects/napari/napari/_qt/event_loop.py", line 79, in gui_qt
    yield app
  File "shapes-bug.py", line 69, in <module>
    _ = viewer.add_shapes([polygon], shape_type=['polygon'])
  File "/Users/jni/projects/napari/napari/components/add_layers_mixin.py", line 587, in add_shapes
    layer = layers.Shapes(
  File "/Users/jni/projects/napari/napari/layers/shapes/shapes.py", line 421, in __init__
    self._init_shapes(
  File "/Users/jni/projects/napari/napari/layers/shapes/shapes.py", line 1562, in _init_shapes
    self._add_shapes(
  File "/Users/jni/projects/napari/napari/layers/shapes/shapes.py", line 1680, in _add_shapes
    shape = shape_cls(
  File "/Users/jni/projects/napari/napari/layers/shapes/_shapes_models/polygon.py", line 34, in __init__
    self.data = data
  File "/Users/jni/projects/napari/napari/layers/shapes/_shapes_models/polygon.py", line 58, in data
    self._update_displayed_data()
  File "/Users/jni/projects/napari/napari/layers/shapes/_shapes_models/polygon.py", line 62, in _update_displayed_data
    self._set_meshes(self.data_displayed)
  File "/Users/jni/projects/napari/napari/layers/shapes/_shapes_models/shape.py", line 227, in _set_meshes
    vertices, triangles = triangulate_face(clean_data)
  File "/Users/jni/projects/napari/napari/layers/shapes/_shapes_utils.py", line 556, in triangulate_face
    vertices, triangles = PolygonData(vertices=data).triangulate()
  File "/Users/jni/conda/envs/all/lib/python3.8/site-packages/vispy/geometry/polygon.py", line 130, in triangulate
    tri.triangulate()
  File "/Users/jni/conda/envs/all/lib/python3.8/site-packages/vispy/geometry/triangulation.py", line 187, in triangulate
    self._edge_event(i, j)
  File "/Users/jni/conda/envs/all/lib/python3.8/site-packages/vispy/geometry/triangulation.py", line 295, in _edge_event
    assert next_tri is not None
AssertionError
```

</details>

## To Reproduce

Run the following script ([gist](https://gist.github.com/jni/7e4e32e815c68e5761ba9a844bbc0e73)):

<details>

<summary>Failing script</summary>

```python
import numpy as np
import napari


image = np.random.random((2019, 1826))

polygon = np.array(
      [[1029.4772481 ,  897.47365667],
       [1029.47376005,  897.47340959],
       [1029.46661985,  897.47171907],
       [1029.45362593,  897.46735903],
       [1029.43194205,  897.4586955 ],
       [1029.39813338,  897.44369019],
       [1029.3483479 ,  897.41996813],
       [1029.27873604,  897.38496552],
       [1029.18620352,  897.33618016],
       [1029.06953907,  897.27159954],
       [1028.93079474,  897.19052716],
       [1028.77645299,  897.09520463],
       [1028.61738263,  896.99351831],
       [1028.46587633,  896.89667225],
       [1028.33215388,  896.81414229],
       [1028.22230446,  896.75103188],
       [1028.13802554,  896.70792076],
       [1028.07749293,  896.68219106],
       [1028.0367732 ,  896.66971003],
       [1028.01118779,  896.66617254],
       [1027.99628852,  896.66788204],
       [1027.98837781,  896.67204385],
       [1027.98466953,  896.67674615],
       [1027.98323318,  896.68079289],
       [1027.9828447 ,  896.68350171],
       [1027.98282925,  896.68453086],
       [1027.98294609,  896.68376481],
       [1027.98334123,  896.6812699 ],
       [1027.98457615,  896.67732273],
       [1027.98772772,  896.67250979],
       [1027.99453842,  896.66788977],
       [1028.00757362,  896.66519434],
       [1028.03030978,  896.66701314],
       [1028.06703902,  896.67686172],
       [1028.12244859,  896.69897813],
       [1028.20075946,  896.73766695],
       [1028.30443902,  896.796077  ],
       [1028.43275425,  896.8745452 ],
       [1028.5807052 ,  896.96908406],
       [1028.73896101,  897.07105886],
       [1028.89543067,  897.16917892],
       [1029.03852709,  897.25402552],
       [1029.16067553,  897.32247022],
       [1029.25886404,  897.37478076],
       [1029.33365718,  897.41278665],
       [1029.38781126,  897.43892735],
       [1029.42506957,  897.45577251],
       [1029.44932344,  897.4657491 ],
       [1029.4641231 ,  897.47097653],
       [1029.47244944,  897.47318253],
       [1029.47665082,  897.4736857 ],
       [1029.47846788,  897.47342572],
       [1029.4790933 ,  897.47301841],
       [1029.47923321,  897.4728137 ],
       [1029.47915162,  897.47293904],
       [1029.47868846,  897.47331756]],
)

with napari.gui_qt():
    viewer = napari.Viewer()
    _ = viewer.add_image(image)
    _ = viewer.add_shapes([polygon], shape_type=['polygon'])
```

</details>

## Expected behavior

Either a clear error message or a tiny shape.

## Environment

```
napari: 0.3.7rc3.dev132+g48b8f383
Platform: macOS-10.15.6-x86_64-i386-64bit
Python: 3.8.2 (default, Mar 26 2020, 10:43:30)  [Clang 4.0.1 (tags/RELEASE_401/final)]
Qt: 5.14.2
PyQt5: 5.14.2
NumPy: 1.18.4
SciPy: 1.5.1
Dask: 2.15.0
VisPy: 0.6.4

GL version:  2.1 ATI-3.10.16
MAX_TEXTURE_SIZE: 16384
```

**Comment by sofroniewn** [comment]
Possible duplicate of #1058
