### ISSUE TITLE
Broadcast error when viewing ome-zarr data

### ISSUE THREAD

**Issue by jni** [napari/napari#1717]
7d288e5c37a2c46c3ca3f4c31d8a3f51a4603797 / #1673 broke viewing ome-zarr multiscale data. I'm not sure yet what exactly is broken. Reproducible example (requires `pip install ome-zarr`):

```python
import napari

with napari.gui_qt():
    v = napari.Viewer()
    v.open('https://s3.embassy.ebi.ac.uk/idr/zarr/v0.1/6001240.zarr')
```

Results in:

```pytb
Traceback (most recent call last):
  File "/home/jni/miniconda3/envs/all/lib/python3.8/site-packages/vispy/app/backends/_qt.py", line 825, in paintGL
    self._vispy_canvas.events.draw(region=None)
  File "/home/jni/miniconda3/envs/all/lib/python3.8/site-packages/vispy/util/event.py", line 455, in __call__
    self._invoke_callback(cb, event)
  File "/home/jni/miniconda3/envs/all/lib/python3.8/site-packages/vispy/util/event.py", line 473, in _invoke_callback
    _handle_exception(self.ignore_callback_errors,
  File "/home/jni/miniconda3/envs/all/lib/python3.8/site-packages/vispy/util/event.py", line 471, in _invoke_callback
    cb(event)
  File "/home/jni/projects/napari/napari/_qt/qt_viewer.py", line 673, in on_draw
    layer._update_draw(
  File "/home/jni/projects/napari/napari/layers/base/base.py", line 771, in _update_draw
    level, corners = compute_multiscale_level_and_corners(
  File "/home/jni/projects/napari/napari/layers/utils/layer_utils.py", line 268, in compute_multiscale_level_and_corners
    level = compute_multiscale_level(
  File "/home/jni/projects/napari/napari/layers/utils/layer_utils.py", line 231, in compute_multiscale_level
    locations = np.argwhere(np.all(scaled_shape > shape_threshold, axis=1))
ValueError: operands could not be broadcast together with shapes (2,4) (2,) 
```

**Comment by sofroniewn** [comment]
Ok good to know, thanks!! I can look into tomorrow

**Comment by jni** [comment]
@sofroniewn here's a reproducible example with just numpy:

```python
import numpy as np
import napari


r0 = np.random.random((1, 2, 236, 275, 271))
r1 = np.random.random((1, 2, 236, 137, 135))

with napari.gui_qt():
    v = napari.view_image([r0, r1])
```
