### ISSUE TITLE
Tracks layer crashes with greater than 3D + t data

### ISSUE THREAD

**Issue by AbigailMcGovern** [napari/napari#1806]
## 🐛 Bug

The tracks layer (which is fantastic in every other sensce) does not allow for greater than 3D + t dimensional data. The tracks layer is designed to take a two dimensional array of track vertices with columns representing track ID (0), then time (1), then up to three spatial dimensions (2-3). Attempting to display n-D data (e.g., 5D data - tracks data with columns representing ID, channel, time, z, y, x), will produce an error. 

## To Reproduce

1. Generate tracks data - ndarray of shape (n , D + 1), where D is greater than 4 (i.e., 5D)
2. view the data using `viewer.add_tracks(tracks)`

The error can be reproduced with [this script](https://gist.github.com/AbigailMcGovern/14138503dfc70037fe62c7f1bc74df4e) 

Returns this error
```
ERROR:root:Unhandled exception:
Traceback (most recent call last):
  File "/Users/amcg0011/GitRepos/napari/napari/_qt/event_loop.py", line 79, in gui_qt
    yield app
  File "./tracks_5d.py", line 50, in <module>
    viewer.add_tracks(
  File "<string>", line 2, in add_tracks
  File "/Users/amcg0011/GitRepos/napari/napari/layers/tracks/tracks.py", line 172, in __init__
    self.data = data
  File "/Users/amcg0011/GitRepos/napari/napari/layers/tracks/tracks.py", line 339, in data
    self._manager.data = data
  File "/Users/amcg0011/GitRepos/napari/napari/layers/tracks/_track_utils.py", line 107, in data
    self._data = self._validate_track_data(data)
  File "/Users/amcg0011/GitRepos/napari/napari/layers/tracks/_track_utils.py", line 191, in _validate_track_data
    raise ValueError('track vertices should be 4 or 5-dimensional')
ValueError: track vertices should be 4 or 5-dimensional
```

## Expected behavior

Display n-D tracks equivalently to n-D image.

**Comment by sofroniewn** [comment]
Hi @AbigailMcGovern, thanks for writing this up in more detail! I'm linking to this  https://github.com/napari/napari/issues/1776#issuecomment-716249499 where @jni mentioned you'd been running into that problem. I really like the ideas from @quantumjot https://github.com/napari/napari/issues/1776#issuecomment-716443856 to make a more general graph layer or move the full nD layer to the shader for slicing.

As an aside, these examples where we might want to move nD data to the shader and do slicing there might force some further reconsiderations of some of the proposals in #1775 too, which I think @d-v-b had been alluding to at some points during the discussion

**Comment by quantumjot** [comment]
I think the `Tracks` layer should display nD data (if you remove that check in `_validate_track_data`), it's just that there will be no slicing in the non-displayed dims.

In general, I think that slicing the data directly in the shader makes a lot of sense, and could be achieved using an extension of what the `Tracks` layer already does.  Depending on how the slicing "window" is set up, you could imagine a user defined window for each non displayed dimension, along the lines of how time is handled currently, or extending that, for example as in this  https://github.com/napari/napari/issues/693#issuecomment-638090099, with something like `window_width` for each dim.

**Comment by psobolewskiPhD** [comment]
Just double checked and this is still an issue post 0.4.19 27851ee92913e02b16d05b0aba19b126fa1e29e3
