### ISSUE TITLE
Fresh install failure on Windows with UnicodeDecodeError

### ISSUE THREAD

**Issue by twilow** [napari/napari#1824]
## 🐛 Bug

After following the install instructions, Napari fails to run with the following error

Traceback (most recent call last):
  File "C:\Users\jon\anaconda3\envs\napari-env\lib\site-packages\IPython\core\interactiveshell.py", line 3418, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-a8600dcd8f7a>", line 1, in <module>
    runfile('C:/Users/jon/PycharmProjects/pythonProjectPT/pytorch-unsupervised-segmentation-tip-master/Napari_demo.py', wdir='C:/Users/jon/PycharmProjects/pythonProjectPT/pytorch-unsupervised-segmentation-tip-master')
  File "C:\Program Files\JetBrains\PyCharm 2020.2.3\plugins\python\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2020.2.3\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/jon/PycharmProjects/pythonProjectPT/pytorch-unsupervised-segmentation-tip-master/Napari_demo.py", line 2, in <module>
    import napari
  File "C:\Program Files\JetBrains\PyCharm 2020.2.3\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "c:\users\jon\napari\napari\__init__.py", line 48, in <module>
    from vispy import app
  File "C:\Program Files\JetBrains\PyCharm 2020.2.3\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\jon\anaconda3\envs\napari-env\lib\site-packages\vispy\app\__init__.py", line 15, in <module>
    from .canvas import Canvas, MouseEvent, KeyEvent  # noqa
  File "C:\Program Files\JetBrains\PyCharm 2020.2.3\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\jon\anaconda3\envs\napari-env\lib\site-packages\vispy\app\canvas.py", line 17, in <module>
    from ..gloo.context import (GLContext, set_current_canvas, forget_canvas)
  File "C:\Program Files\JetBrains\PyCharm 2020.2.3\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\jon\anaconda3\envs\napari-env\lib\site-packages\vispy\gloo\__init__.py", line 47, in <module>
    from . import gl  # noqa
  File "C:\Program Files\JetBrains\PyCharm 2020.2.3\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\jon\anaconda3\envs\napari-env\lib\site-packages\vispy\gloo\gl\__init__.py", line 34, in <module>
    from ._constants import *  # noqa
  File "C:\Program Files\JetBrains\PyCharm 2020.2.3\plugins\python\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\jon\anaconda3\envs\napari-env\lib\site-packages\vispy\gloo\gl\_constants.py", line 326, in <module>
    if repr(ob).startswith('GL_'):
  File "C:\Users\jon\anaconda3\envs\napari-env\lib\_sitebuiltins.py", line 61, in __repr__
    self.__setup()
  File "C:\Users\jon\anaconda3\envs\napari-env\lib\_sitebuiltins.py", line 51, in __setup
    data = fp.read()
  File "C:\Users\jon\anaconda3\envs\napari-env\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 188: character maps to <undefined>

**Comment by twilow** [comment]
Solved by adding PYTHONUTF8=1 to the environment variables

**Comment by sofroniewn** [comment]
Hmm interesting to know about `PYTHONUTF8=1`, I don't think I'd seen that issue before - cc @ziyangczi @jni.

Sorry things weren't working for you, but glad they are now! Can you maybe tell us a little more about your system/ python versions etc. to help know when this might come up again

**Comment by twilow** [comment]
Windows 10
python 3.8

instructions followed to create new env in conda and do a "requirements" install after downloading latest from github

**Comment by twilow** [comment]
sorry windows 10 pro.... in case that makes a difference.

**Comment by sofroniewn** [comment]
thanks @twilow - did you also preinstall Microsoft Visual C++ Build Tools on windows?

Right now we list that in the [instructions in our readme on this repo](https://github.com/napari/napari#from-pip-with-batteries-included) but I noticed its missing in our full tutorial on [installation on the website]( https://napari.org/tutorials/fundamentals/installation) (I just asked @ziyangczi who added those to our readme in #1758 to add to our tutorials repo here too https://github.com/napari/tutorials/blob/master/fundamentals/installation.md so the instructions match)

**Comment by twilow** [comment]
yes, I did

**Comment by sofroniewn** [comment]
Thanks!!!

**Comment by liu-ziyang** [comment]
opened PR to add instruction to specify UTF8 in tutorial: https://github.com/napari/tutorials/pull/97 I think this only impacts a small percentage of users
