### ISSUE TITLE
Index error when adding/deleting layer from GUI

### ISSUE THREAD

**Issue by kevinyamauchi** [napari/napari#184]
## 🐛 Bug
When adding and the deleting a layer from the GUI, I receive the following error:
```python
WARNING: Traceback (most recent call last):
  File "add_shapes.py", line 49, in <module>
    layer._qt_properties.setExpanded(True)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
  File "/Users/kevin.yamauchi/Documents/napari/napari/util/app.py", line 26, in app_context
    app.exec()
  File "/Users/kevin.yamauchi/Documents/napari/napari/components/_layers_list/model.py", line 182, in remove_selected
    self.pop(i)
  File "/Users/kevin.yamauchi/Documents/napari/napari/util/list/_model.py", line 55, in pop
    self.changed.removed(item=obj)
  File "/Users/kevin.yamauchi/Documents/napari/napari/util/event.py", line 489, in __call__
    self._invoke_callback(cb, event)
  File "/Users/kevin.yamauchi/Documents/napari/napari/util/event.py", line 504, in _invoke_callback
    cb(event)
  File "/Users/kevin.yamauchi/Documents/napari/napari/components/_layers_list/model.py", line 29, in _remove
    layer.viewer = None
  File "/Users/kevin.yamauchi/Documents/napari/napari/layers/_base_layer/model.py", line 162, in viewer
    self._parent = parent
  File "/Users/kevin.yamauchi/Documents/napari/napari/layers/_base_layer/_visual_wrapper.py", line 82, in _parent
    self._node.parent = parent
  File "/Users/kevin.yamauchi/Documents/napari/.venv/lib/python3.6/site-packages/vispy/util/frozen.py", line 17, in __setattr__
    object.__setattr__(self, key, value)
  File "/Users/kevin.yamauchi/Documents/napari/.venv/lib/python3.6/site-packages/vispy/scene/node.py", line 209, in parent
    self._update_trsys(None)
  File "/Users/kevin.yamauchi/Documents/napari/napari/_vispy/scene/visuals.py", line 82, in _update_trsys
    self.transforms.scene_transform = scene.node_transform(doc)
  File "/Users/kevin.yamauchi/Documents/napari/.venv/lib/python3.6/site-packages/vispy/visuals/transforms/transform_system.py", line 276, in scene_transform
    self._scene_transform.transforms = tr
  File "/Users/kevin.yamauchi/Documents/napari/.venv/lib/python3.6/site-packages/vispy/visuals/transforms/chain.py", line 96, in transforms
    self.update()
  File "/Users/kevin.yamauchi/Documents/napari/.venv/lib/python3.6/site-packages/vispy/visuals/transforms/base_transform.py", line 153, in update
    self.changed(*args)
  File "/Users/kevin.yamauchi/Documents/napari/.venv/lib/python3.6/site-packages/vispy/util/event.py", line 455, in __call__
    self._invoke_callback(cb, event)
  File "/Users/kevin.yamauchi/Documents/napari/.venv/lib/python3.6/site-packages/vispy/util/event.py", line 471, in _invoke_callback
    cb(event)
  File "/Users/kevin.yamauchi/Documents/napari/.venv/lib/python3.6/site-packages/vispy/visuals/transforms/chain.py", line 212, in _subtr_changed
    self.update(ev)
  File "/Users/kevin.yamauchi/Documents/napari/.venv/lib/python3.6/site-packages/vispy/visuals/transforms/base_transform.py", line 153, in update
    self.changed(*args)
  File "/Users/kevin.yamauchi/Documents/napari/.venv/lib/python3.6/site-packages/vispy/util/event.py", line 455, in __call__
    self._invoke_callback(cb, event)
  File "/Users/kevin.yamauchi/Documents/napari/.venv/lib/python3.6/site-packages/vispy/util/event.py", line 475, in _invoke_callback
    self, cb_event=(cb, event))
  << caught exception here: >>
  File "/Users/kevin.yamauchi/Documents/napari/.venv/lib/python3.6/site-packages/vispy/util/event.py", line 471, in _invoke_callback
    cb(event)
  File "/Users/kevin.yamauchi/Documents/napari/.venv/lib/python3.6/site-packages/vispy/visuals/transforms/chain.py", line 281, in source_changed
    new_tr = [tr[0]]
IndexError: list index out of range
ERROR: Invoking <bound method SimplifiedChainTransform.source_changed of <ChainTransform [<STTransform scale=[1. 1. 1. 1.] translate=[0. 0. 0. 0.] at 0x5073328616>,
                 <STTransform scale=[1.0653409e+00 1.0653409e+00 1.0000000e-06 1.0000000e+00] translate=[34.272728 27.272728  0.        0.      ] at 0x5067659696>] at 0x12e6570b8>> for Event
```

## To Reproduce

1. `git checkout shapes` or `git checkout labels`
2. launch a demo script (e.g., `add_shapes.py`)
3. Add a layer via the "+" button
4. Delete the layer via the trash can button

## Expected behavior

Layers should be added/deleted without an error.

## Environment

 - napari Version 0.0.6, `shapes` or `labels` branch
 - OS (e.g., Linux): Mac OS X
 - Python version: 3.6

**Comment by sofroniewn** [comment]
This is a duplicate of #170

**Comment by kevinyamauchi** [comment]
Oops, sorry!
