### ISSUE TITLE
Tab completion in QT console causes float divide by zero error

### ISSUE THREAD

**Issue by VolkerH** [napari/napari#1854]
## 🐛 Bug

When trying do to tab completion in the Qt console the current master, I get a float divide by zero error popping up.

![tab_completion](https://user-images.githubusercontent.com/2210044/98876662-dcbc6b80-24d2-11eb-9186-6989c0941348.gif)

In a slightly earlier version (not sure which one I had installed before pulling the latest master) there was no error message but napari crashed with the following traceback. 
This suggests it may be an upstream error in qtconsole.

```
(napari) volker@gpubox:~$ napari
WARNING: Traceback (most recent call last):
  File "/home/volker/miniconda3/envs/napari/lib/python3.7/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "/home/volker/miniconda3/envs/napari/lib/python3.7/site-packages/qtconsole/jupyter_widget.py", line 178, in _handle_complete_reply
    self._complete_with_items(cursor, matches)
  File "/home/volker/miniconda3/envs/napari/lib/python3.7/site-packages/qtconsole/console_widget.py", line 1054, in _complete_with_items
    prefix_length=len(prefix))
  File "/home/volker/miniconda3/envs/napari/lib/python3.7/site-packages/qtconsole/completion_html.py", line 313, in show_items
    displaywidth = int(max(10, (width / char_width) - 1))
ZeroDivisionError: float division by zero
10:24:13 WARNING Traceback (most recent call last):
  File "/home/volker/miniconda3/envs/napari/lib/python3.7/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "/home/volker/miniconda3/envs/napari/lib/python3.7/site-packages/qtconsole/jupyter_widget.py", line 178, in _handle_complete_reply
    self._complete_with_items(cursor, matches)
  File "/home/volker/miniconda3/envs/napari/lib/python3.7/site-packages/qtconsole/console_widget.py", line 1054, in _complete_with_items
    prefix_length=len(prefix))
  File "/home/volker/miniconda3/envs/napari/lib/python3.7/site-packages/qtconsole/completion_html.py", line 313, in show_items
    displaywidth = int(max(10, (width / char_width) - 1))
ZeroDivisionError: float division by zero
```

## To Reproduce

1. start napari
2. open ipython console
3. type viewer.
4. press TAB

## Expected behavior

Possible completions shown, no error message.

## Environment

```
napari: 0.4.1a1
Platform: Linux-5.4.0-52-generic-x86_64-with-debian-bullseye-sid
Python: 3.7.7 (default, May 7 2020, 21:25:33) [GCC 7.3.0]
Qt: 5.14.2
PyQt5: 5.14.2
NumPy: 1.19.1
SciPy: 1.5.2
Dask: 2.25.0
VisPy: 0.6.4

GL version: 4.6.0 NVIDIA 450.80.02
MAX_TEXTURE_SIZE: 32768

Plugins:
- napari_plugin_engine: 0.1.8
- svg: 0.1.4
```

likely relevant:

![image](https://user-images.githubusercontent.com/2210044/98876870-4ccaf180-24d3-11eb-9f53-c8f4964db12c.png)

**Comment by VolkerH** [comment]
Ok, this is upstream

https://github.com/jupyter/qtconsole/issues/439

updating qtconsole to version `4.7.7` fixed this.

**Comment by VolkerH** [comment]
Will bump the requirements in `setup.cfg` for qtconsole. PR forthcoming.
