### ISSUE TITLE
ERROR:root:Unhandled exception - When trying to add a layer to the Napari Viewer

### ISSUE THREAD

**Issue by sebi06** [napari/napari#1915]
## 🐛 Bug

When I try to add a NumPy.Array as layer to the Napari viewer I get the following error:

```text
/home/sebi06/miniconda3/envs/imageanalysis/lib/python3.7/site-packages/aicsimageio/transforms.py:178: UserWarning: Data has dimension B with depth 1, assuming B=0 is the desired value, if not the case specify B=x where x is an integer, list, tuple, range, or slice.
  f"Data has dimension {dim} with depth {data.shape[dim_index]}, "
Extract Channel NumPy.Array
Adding Channel  :  Dye-CH0
Shape Channel   :  0 (1, 600, 1, 512, 512)
Scaling Factors :  [1.0, 1.0, 0.0, 1.0, 1.0]
Scaling:  0.0 3776.0
ERROR:root:Unhandled exception:
Traceback (most recent call last):
  File "/datadisk1/tuxedo/Github/napari_zeiss/napari_browser_cz.py", line 198, in open_image_stack
    rename_sliders=True)
  File "/datadisk1/tuxedo/Github/napari_zeiss/napari_browser_cz.py", line 276, in show_image_napari
    gamma=gamma)
  File "/home/sebi06/miniconda3/envs/imageanalysis/lib/python3.7/site-packages/napari/components/add_layers_mixin.py", line 271, in add_image
    return self.add_layer(_image_class(data, **kwargs))
  File "/home/sebi06/miniconda3/envs/imageanalysis/lib/python3.7/site-packages/napari/layers/image/image.py", line 278, in __init__
    self._update_dims()
  File "/home/sebi06/miniconda3/envs/imageanalysis/lib/python3.7/site-packages/napari/layers/base/base.py", line 518, in _update_dims
    self.refresh()
  File "/home/sebi06/miniconda3/envs/imageanalysis/lib/python3.7/site-packages/napari/layers/base/base.py", line 890, in refresh
    self.set_view_slice()
  File "/home/sebi06/miniconda3/envs/imageanalysis/lib/python3.7/site-packages/napari/layers/base/base.py", line 785, in set_view_slice
    self._set_view_slice()
  File "/home/sebi06/miniconda3/envs/imageanalysis/lib/python3.7/site-packages/napari/layers/image/image.py", line 562, in _set_view_slice
    indices = np.array(self._slice_indices)
  File "/home/sebi06/miniconda3/envs/imageanalysis/lib/python3.7/site-packages/napari/layers/base/base.py", line 580, in _slice_indices
    inv_transform = self._transforms['data2world'].inverse
  File "/home/sebi06/miniconda3/envs/imageanalysis/lib/python3.7/site-packages/napari/utils/transforms/transforms.py", line 399, in inverse
    return Affine(affine_matrix=np.linalg.inv(self.affine_matrix))
  File "<__array_function__ internals>", line 6, in inv
  File "/home/sebi06/miniconda3/envs/imageanalysis/lib/python3.7/site-packages/numpy/linalg/linalg.py", line 546, in inv
    ainv = _umath_linalg.inv(a, signature=signature, extobj=extobj)
  File "/home/sebi06/miniconda3/envs/imageanalysis/lib/python3.7/site-packages/numpy/linalg/linalg.py", line 88, in _raise_linalgerror_singular
    raise LinAlgError("Singular matrix")
numpy.linalg.LinAlgError: Singular matrix
``

The image open correctly in Fiji. It is a CZI TimeSeries,

![image](https://user-images.githubusercontent.com/3833249/99881587-e3f22080-2c1a-11eb-9b30-d03fd5eb6575.png)



## Environment
Ubuntu 20.04. 1 LTS 64bit Python 3.7.6

Napari Info:

napari: 0.4.0
Platform: Linux-5.6.0-1028-oem-x86_64-with-debian-bullseye-sid
Python: 3.7.6 | packaged by conda-forge | (default, Mar 5 2020, 15:27:18) [GCC 7.3.0]
Qt: 5.12.7
PyQt5: 5.12.3
NumPy: 1.19.4
SciPy: 1.5.3
Dask: 2.30.0
VisPy: 0.6.4

GL version: 4.6.0 NVIDIA 450.80.02
MAX_TEXTURE_SIZE: 32768

Plugins:
- aicsimageio: 0.1.3
- aicsimageio_delayed: 0.1.3
- napari-plugin-engine: 0.1.5
- napari_browser_cz
- ome_zarr: 0.0.15
- svg: 0.1.4

**Comment by sofroniewn** [comment]
Hi @sebi06 

It looks like we can't handle `Scaling Factors :  [1.0, 1.0, 0.0, 1.0, 1.0]` where one of the scaling factors is `0.0` because we can't calculate an inverse. Just curious do you know why that factor is `0.0` or have recommendations on how to interpret it. We shouldn't fail, but not immediately clear to me how best to fix.

**Comment by sebi06** [comment]
Hi, now you mention it I think I got an idea how to fix this on my side. 0.0 does make sense as a sale for a dimension...

I have to dig a bit depper why this CZI file gives me "strange" metadata...

**Comment by sebi06** [comment]
Hi @sofroniewn 

I found the underlying issue. As mostly in such cases a good candidate are "faulty" metadata .... 



![image](https://user-images.githubusercontent.com/3833249/99887448-d18cdc80-2c44-11eb-9036-7cea5e3a6b5f.png)

The image (causing the problem) is an old CZI from an AiryScan. And as you probably know, to get the final image from an AiryScan acquisition the raw images have to be processed. The acquisition was a time series and back in the days there was a bug in our software ....

Long story short: The ZScale for that CZI file was set to 0.0 (grrrr) because it has only one Z-plane. That cause the problem. I added any extra check to set ZScale = 1.0 (as shown in the image). And now it works as expected. You might still want to catch that problem as well on your side, but the cause was clearly the metadata issue on my side. So feel free to close the issue.

```text
Extract Channel as NumPy.Array
Adding Channel  :  Dye-CH0
Shape Channel   :  0 (1, 600, 1, 512, 512)
Scaling Factors :  [1.0, 1.0, 22.727, 1.0, 1.0]
Scaling:  0.0 3776.0
Extract Channel as NumPy.Array
Adding Channel  :  Dye-CH1
Shape Channel   :  1 (1, 600, 1, 512, 512)
Scaling Factors :  [1.0, 1.0, 22.727, 1.0, 1.0]
Scaling:  0.0 4617.0
Renaming the Sliders based on the Dimension String ....
```

**Comment by sofroniewn** [comment]
> Long story short: The ZScale for that CZI file was set to 0.0 (grrrr) because it has only one Z-plane. That cause the problem. I added any extra check to set ZScale = 1.0 (as shown in the image). And now it works as expected. You might still want to catch that problem as well on your side, but the cause was clearly the metadata issue on my side. So feel free to close the issue.

Nice, ok glad we got to the bottom of this. We should probably fail more gracefully / give a better error. Thanks for the report!!

**Comment by psobolewskiPhD** [comment]
This was closed by https://github.com/napari/napari/pull/4906
