### ISSUE TITLE
Errors after napari installation & launch on Windows 7

### ISSUE THREAD

**Issue by GenevieveBuckley** [napari/napari#1981]
## 🐛 Bug

Errors after napari installation & launch on Windows 7.

## To Reproduce

1. Create a new conda environment including python 3.7 and pip
2. Pip install napari into the new conda environment
3. Start ipython and launch the napari viewer

<details><summary>CLICK ME</summary>
<p>

```
conda create -n napari python=3.7 pip
conda activate napari
python -m pip install napari[all]

Successfully installed IPython-7.19.0 Jinja2-2.11.2 MarkupSafe-1.1.1 Pillow-8.0.
1 PyOpenGL-3.1.5 PyQt5-5.15.2 PyQt5-sip-12.8.1 PyYAML-5.3.1 alabaster-0.7.12 app
dirs-1.4.4 babel-2.9.0 backcall-0.2.0 cachey-0.2.1 chardet-3.0.4 colorama-0.4.4
dask-2.30.0 decorator-4.4.2 docutils-0.16 freetype-py-2.2.0 heapdict-1.0.1 idna-
2.10 imageio-2.9.0 imagesize-1.2.0 importlib-metadata-3.1.1 ipykernel-5.3.4 ipyt
hon-genutils-0.2.0 jedi-0.17.2 jupyter-client-6.1.7 jupyter-core-4.7.0 napari-0.
4.2 napari-plugin-engine-0.1.8 napari-svg-0.1.4 numpy-1.19.4 numpydoc-1.1.0 pack
aging-20.7 parso-0.7.1 pickleshare-0.7.5 prompt-toolkit-3.0.8 psutil-5.7.3 pygme
nts-2.7.2 pyparsing-2.4.7 python-dateutil-2.8.1 pytz-2020.4 pywin32-300 pyzmq-20
.0.0 qtconsole-5.0.1 qtpy-1.9.0 requests-2.25.0 scipy-1.5.4 six-1.15.0 snowballs
temmer-2.0.0 sphinx-3.3.1 sphinxcontrib-applehelp-1.0.2 sphinxcontrib-devhelp-1.
0.2 sphinxcontrib-htmlhelp-1.0.3 sphinxcontrib-jsmath-1.0.1 sphinxcontrib-qthelp
-1.0.3 sphinxcontrib-serializinghtml-1.1.4 tifffile-2020.11.26 toolz-0.11.1 torn
ado-6.1 traitlets-5.0.5 typing-extensions-3.7.4.3 urllib3-1.26.2 vispy-0.6.6 wcw
idth-0.2.5 wrapt-1.12.1 zipp-3.4.0

(napari) C:\Users\Admin\MICROSCOPE\DeMarcoLab\liftout>ipython
Python 3.7.9 (default, Aug 31 2020, 17:10:11) [MSC v.1916 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.19.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: %gui qt

In [2]: import napari

In [3]: viewer = napari.Viewer()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
c:\users\admin\anaconda3\envs\napari\lib\site-packages\vispy\app\backends\_qt.py
 in paintGL(self)
    823         # (0, 0, self.width(), self.height()))
    824         self._vispy_canvas.set_current()
--> 825         self._vispy_canvas.events.draw(region=None)
    826
    827

c:\users\admin\anaconda3\envs\napari\lib\site-packages\vispy\util\event.py in __
call__(self, *args, **kwargs)
    453                     continue
    454
--> 455                 self._invoke_callback(cb, event)
    456                 if event.blocked:
    457                     break

c:\users\admin\anaconda3\envs\napari\lib\site-packages\vispy\util\event.py in _i
nvoke_callback(self, cb, event)
    473             _handle_exception(self.ignore_callback_errors,
    474                               self.print_callback_errors,
--> 475                               self, cb_event=(cb, event))
    476
    477     def _prepare_event(self, *args, **kwargs):

c:\users\admin\anaconda3\envs\napari\lib\site-packages\vispy\util\event.py in _i
nvoke_callback(self, cb, event)
    469     def _invoke_callback(self, cb, event):
    470         try:
--> 471             cb(event)
    472         except Exception:
    473             _handle_exception(self.ignore_callback_errors,

c:\users\admin\anaconda3\envs\napari\lib\site-packages\vispy\gloo\context.py in
flush_commands(self, event)
    173             else:
    174                 fbo = 0
--> 175             self.shared.parser.parse([('CURRENT', 0, fbo)])
    176         self.glir.flush(self.shared.parser)
    177

c:\users\admin\anaconda3\envs\napari\lib\site-packages\vispy\gloo\glir.py in par
se(self, commands)
    817
    818         for command in commands:
--> 819             self._parse(command)
    820
    821     def get_object(self, id_):

c:\users\admin\anaconda3\envs\napari\lib\site-packages\vispy\gloo\glir.py in _pa
rse(self, command)
    741             # This context is made current
    742             self.env.clear()
--> 743             self._gl_initialize()
    744             self.env['fbo'] = args[0]
    745             gl.glBindFramebuffer(gl.GL_FRAMEBUFFER, args[0])

c:\users\admin\anaconda3\envs\napari\lib\site-packages\vispy\gloo\glir.py in _gl
_initialize(self)
    849
    850             this_version = LooseVersion(this_version)
--> 851             if this_version < '2.1':
    852                 if os.getenv('VISPY_IGNORE_OLD_VERSION', '').lower() !=
'true':
    853                     logger.warning('OpenGL version 2.1 or higher recomme
nded, '

c:\users\admin\anaconda3\envs\napari\lib\distutils\version.py in __lt__(self, ot
her)
     50
     51     def __lt__(self, other):
---> 52         c = self._cmp(other)
     53         if c is NotImplemented:
     54             return c

c:\users\admin\anaconda3\envs\napari\lib\distutils\version.py in _cmp(self, othe
r)
    333             other = LooseVersion(other)
    334
--> 335         if self.version == other.version:
    336             return 0
    337         if self.version < other.version:

AttributeError: 'LooseVersion' object has no attribute 'version'

Traceback (most recent call last):
  File "c:\users\admin\anaconda3\envs\napari\lib\site-packages\vispy\gloo\gl\_gl
2.py", line 53, in glBindFramebuffer
    nativefunc = glBindFramebuffer._native
AttributeError: 'function' object has no attribute '_native'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\admin\anaconda3\envs\napari\lib\site-packages\vispy\gloo\gl\gl2
.py", line 72, in _get_gl_func
    func = getattr(_lib, name)
  File "c:\users\admin\anaconda3\envs\napari\lib\ctypes\__init__.py", line 377,
in __getattr__
    func = self.__getitem__(name)
  File "c:\users\admin\anaconda3\envs\napari\lib\ctypes\__init__.py", line 382,
in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'glBindFramebuffer' not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\admin\anaconda3\envs\napari\lib\site-packages\vispy\app\backend
s\_qt.py", line 825, in paintGL
    self._vispy_canvas.events.draw(region=None)
  File "c:\users\admin\anaconda3\envs\napari\lib\site-packages\vispy\util\event.
py", line 455, in __call__
    self._invoke_callback(cb, event)
  File "c:\users\admin\anaconda3\envs\napari\lib\site-packages\vispy\util\event.
py", line 475, in _invoke_callback
    self, cb_event=(cb, event))
  File "c:\users\admin\anaconda3\envs\napari\lib\site-packages\vispy\util\event.
py", line 471, in _invoke_callback
    cb(event)
  File "c:\users\admin\anaconda3\envs\napari\lib\site-packages\vispy\gloo\contex
t.py", line 175, in flush_commands
    self.shared.parser.parse([('CURRENT', 0, fbo)])
  File "c:\users\admin\anaconda3\envs\napari\lib\site-packages\vispy\gloo\glir.p
y", line 819, in parse
    self._parse(command)
  File "c:\users\admin\anaconda3\envs\napari\lib\site-packages\vispy\gloo\glir.p
y", line 745, in _parse
    gl.glBindFramebuffer(gl.GL_FRAMEBUFFER, args[0])
  File "c:\users\admin\anaconda3\envs\napari\lib\site-packages\vispy\gloo\gl\_gl
2.py", line 55, in glBindFramebuffer
    nativefunc = glBindFramebuffer._native = _get_gl_func("glBindFramebuffer", N
one, (ctypes.c_uint, ctypes.c_uint,))
  File "c:\users\admin\anaconda3\envs\napari\lib\site-packages\vispy\gloo\gl\gl2
.py", line 87, in _get_gl_func
    raise RuntimeError('Using %s with no OpenGL context.' % name)
RuntimeError: Using glBindFramebuffer with no OpenGL context.

If you suspect this is an IPython 7.19.0 bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

In [4]: exit
```

</p>
</details>

Additionally, I can't add images to the napari viewer. When I try I get an error like this:

<details><summary>CLICK ME</summary>
<p>

```
In [4]: from tifffile import imread

In [5]: image = imread('orig_eb.tif')

In [6]: viewer.add_image(image)
Out[6]: <Image layer 'image' at 0x256ac0c8>

In [7]: WARNING: Error drawing visual <Image at 0x1f14ed08>
Traceback (most recent call last):
  File "c:\users\admin\anaconda3\envs\napari\lib\site-packages\vispy\gloo\gl\_gl
2.py", line 53, in glBindFramebuffer
    nativefunc = glBindFramebuffer._native
AttributeError: 'function' object has no attribute '_native'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\admin\anaconda3\envs\napari\lib\site-packages\vispy\gloo\gl\gl2
.py", line 72, in _get_gl_func
    func = getattr(_lib, name)
  File "c:\users\admin\anaconda3\envs\napari\lib\ctypes\__init__.py", line 377,
in __getattr__
    func = self.__getitem__(name)
  File "c:\users\admin\anaconda3\envs\napari\lib\ctypes\__init__.py", line 382,
in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'glBindFramebuffer' not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\admin\anaconda3\envs\napari\lib\site-packages\vispy\app\backend
s\_qt.py", line 825, in paintGL
    self._vispy_canvas.events.draw(region=None)
  File "c:\users\admin\anaconda3\envs\napari\lib\site-packages\vispy\util\event.
py", line 455, in __call__
    self._invoke_callback(cb, event)
  File "c:\users\admin\anaconda3\envs\napari\lib\site-packages\vispy\util\event.
py", line 475, in _invoke_callback
    self, cb_event=(cb, event))
  File "c:\users\admin\anaconda3\envs\napari\lib\site-packages\vispy\util\event.
py", line 471, in _invoke_callback
    cb(event)
  File "c:\users\admin\anaconda3\envs\napari\lib\site-packages\vispy\scene\canva
s.py", line 217, in on_draw
    self._draw_scene()
  File "c:\users\admin\anaconda3\envs\napari\lib\site-packages\vispy\scene\canva
s.py", line 266, in _draw_scene
    self.draw_visual(self.scene)
  File "c:\users\admin\anaconda3\envs\napari\lib\site-packages\vispy\scene\canva
s.py", line 304, in draw_visual
    node.draw()
  File "c:\users\admin\anaconda3\envs\napari\lib\site-packages\vispy\scene\visua
ls.py", line 99, in draw
    self._visual_superclass.draw(self)
  File "c:\users\admin\anaconda3\envs\napari\lib\site-packages\vispy\visuals\vis
ual.py", line 443, in draw
    self._vshare.index_buffer)
  File "c:\users\admin\anaconda3\envs\napari\lib\site-packages\vispy\visuals\sha
ders\program.py", line 101, in draw
    Program.draw(self, *args, **kwargs)
  File "c:\users\admin\anaconda3\envs\napari\lib\site-packages\vispy\gloo\progra
m.py", line 533, in draw
    canvas.context.flush_commands()
  File "c:\users\admin\anaconda3\envs\napari\lib\site-packages\vispy\gloo\contex
t.py", line 175, in flush_commands
    self.shared.parser.parse([('CURRENT', 0, fbo)])
  File "c:\users\admin\anaconda3\envs\napari\lib\site-packages\vispy\gloo\glir.p
y", line 819, in parse
    self._parse(command)
  File "c:\users\admin\anaconda3\envs\napari\lib\site-packages\vispy\gloo\glir.p
y", line 745, in _parse
    gl.glBindFramebuffer(gl.GL_FRAMEBUFFER, args[0])
  File "c:\users\admin\anaconda3\envs\napari\lib\site-packages\vispy\gloo\gl\_gl
2.py", line 55, in glBindFramebuffer
    nativefunc = glBindFramebuffer._native = _get_gl_func("glBindFramebuffer", N
one, (ctypes.c_uint, ctypes.c_uint,))
  File "c:\users\admin\anaconda3\envs\napari\lib\site-packages\vispy\gloo\gl\gl2
.py", line 87, in _get_gl_func
    raise RuntimeError('Using %s with no OpenGL context.' % name)
RuntimeError: Using glBindFramebuffer with no OpenGL context.

If you suspect this is an IPython 7.19.0 bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True
```

</p>
</details>

## Expected behavior

I expected napari to launch without any error messages, and to be able to add images to the viewer.

## Environment

 - Please copy and paste the information at napari info option in help menubar here:

```
napari: 0.4.2
Platform: Windows-7-6.1.7601-SP1
Python: 3.7.9 (default, Aug 31 2020, 17:10:11) [MSC v.1916 64 bit (AMD64)]
Qt: 5.15.2
PyQt5: 5.15.2
NumPy: 1.19.4
SciPy: 1.5.4
Dask: 2.30.0
VisPy: 0.6.6

GL version: 
MAX_TEXTURE_SIZE: ()

Plugins:
- napari_plugin_engine: 0.1.8
- svg: 0.1.4
```

 - Any other relevant information:

Conda packages list:

<details><summary>CLICK ME</summary>
<p>

```
(napari) C:\Users\Admin\MICROSCOPE\DeMarcoLab\liftout>conda list
# packages in environment at C:\Users\Admin\Anaconda3\envs\napari:
#
# Name                    Version                   Build  Channel
alabaster                 0.7.12                    <pip>
appdirs                   1.4.4                     <pip>
Babel                     2.9.0                     <pip>
backcall                  0.2.0                     <pip>
ca-certificates           2020.10.14                    0
cachey                    0.2.1                     <pip>
certifi                   2020.11.8        py37haa95532_0
chardet                   3.0.4                     <pip>
colorama                  0.4.4                     <pip>
dask                      2.30.0                    <pip>
decorator                 4.4.2                     <pip>
docutils                  0.16                      <pip>
freetype-py               2.2.0                     <pip>
HeapDict                  1.0.1                     <pip>
idna                      2.10                      <pip>
imageio                   2.9.0                     <pip>
imagesize                 1.2.0                     <pip>
importlib-metadata        3.1.1                     <pip>
ipykernel                 5.3.4                     <pip>
ipython                   7.19.0                    <pip>
ipython-genutils          0.2.0                     <pip>
jedi                      0.17.2                    <pip>
Jinja2                    2.11.2                    <pip>
jupyter-client            6.1.7                     <pip>
jupyter-core              4.7.0                     <pip>
MarkupSafe                1.1.1                     <pip>
napari                    0.4.2                     <pip>
napari-plugin-engine      0.1.8                     <pip>
napari-svg                0.1.4                     <pip>
numpy                     1.19.4                    <pip>
numpydoc                  1.1.0                     <pip>
openssl                   1.1.1h               he774522_0
packaging                 20.7                      <pip>
parso                     0.7.1                     <pip>
pickleshare               0.7.5                     <pip>
Pillow                    8.0.1                     <pip>
pip                       20.3             py37haa95532_0
prompt-toolkit            3.0.8                     <pip>
psutil                    5.7.3                     <pip>
Pygments                  2.7.2                     <pip>
PyOpenGL                  3.1.5                     <pip>
pyparsing                 2.4.7                     <pip>
PyQt5                     5.15.2                    <pip>
PyQt5-sip                 12.8.1                    <pip>
python                    3.7.9                h60c2a47_0
python-dateutil           2.8.1                     <pip>
pytz                      2020.4                    <pip>
pywin32                   300                       <pip>
PyYAML                    5.3.1                     <pip>
pyzmq                     20.0.0                    <pip>
qtconsole                 5.0.1                     <pip>
QtPy                      1.9.0                     <pip>
requests                  2.25.0                    <pip>
scipy                     1.5.4                     <pip>
setuptools                50.3.2           py37haa95532_2
six                       1.15.0                    <pip>
snowballstemmer           2.0.0                     <pip>
Sphinx                    3.3.1                     <pip>
sphinxcontrib-applehelp   1.0.2                     <pip>
sphinxcontrib-devhelp     1.0.2                     <pip>
sphinxcontrib-htmlhelp    1.0.3                     <pip>
sphinxcontrib-jsmath      1.0.1                     <pip>
sphinxcontrib-qthelp      1.0.3                     <pip>
sphinxcontrib-serializinghtml 1.1.4                     <pip>
sqlite                    3.33.0               h2a8f88b_0
tifffile                  2020.11.26                <pip>
toolz                     0.11.1                    <pip>
tornado                   6.1                       <pip>
traitlets                 5.0.5                     <pip>
typing-extensions         3.7.4.3                   <pip>
urllib3                   1.26.2                    <pip>
vc                        14.1                 h0510ff6_4
vispy                     0.6.6                     <pip>
vs2015_runtime            14.16.27012          hf0eaf9b_3
wcwidth                   0.2.5                     <pip>
wheel                     0.36.0             pyhd3eb1b0_0
wincertstore              0.2                      py37_0
wrapt                     1.12.1                    <pip>
zipp                      3.4.0                     <pip>
zlib                      1.2.11               h62dcd97_4

```

</p>
</details>

**Comment by sofroniewn** [comment]
This seems to be a vispy issue. I'm curious have you ever used napari on this machine before? Maybe some people with more windows experience like @ziyangczi can offer a suggestion here. Thanks for the very detailed report!!! Sorry I'm not immediately of more help

**Comment by GenevieveBuckley** [comment]
No, I haven't used napari on this machine before. I wonder if it's just too old in general.

**Comment by liu-ziyang** [comment]
curious about the machine config 
* does it have a graphics card?
* what driver is installed now?
* installed with vc++?

also smelling vispy issue with opengl, so my bet is on missing vc++ library or incompatible opengl versions, etc

**Comment by sofroniewn** [comment]
Agreed, sounds like this might be an old windows/ opengl issue as vispy can't find any GL version, notice `GL version: ` in the system info.

Unless @GenevieveBuckley or anyone else has any ideas I'll close this issue shortly, sorry we couldn't be of more help!
