### ISSUE TITLE
Broken build on Scientific Linux 7.3

### ISSUE THREAD

**Issue by d-v-b** [napari/napari#207]
## 🐛 Bug

The build is broken -- napari can't find `PyQt5.sip` 

## To Reproduce

I get the error when I import napari, or try to run an example

```bash
(napari) [bennettd@c11u25 napari]$ python examples/nD_image.py 
Traceback (most recent call last):
  File "examples/nD_image.py", line 7, in <module>
    from napari import ViewerApp
  File "/groups/ahrens/home/bennettd/miniconda/envs/napari/lib/python3.6/site-packages/napari-0.0.6+16.gcb0830c-py3.6.egg/napari/__init__.py", line 1, in <module>
    from .components import Window, Viewer
  File "/groups/ahrens/home/bennettd/miniconda/envs/napari/lib/python3.6/site-packages/napari-0.0.6+16.gcb0830c-py3.6.egg/napari/components/__init__.py", line 21, in <module>
    from ._window import Window, QtApplication
  File "/groups/ahrens/home/bennettd/miniconda/envs/napari/lib/python3.6/site-packages/napari-0.0.6+16.gcb0830c-py3.6.egg/napari/components/_window/__init__.py", line 5, in <module>
    from PyQt5.QtWidgets import QApplication as QtApplication
ModuleNotFoundError: No module named 'PyQt5.sip'
```
## Expected behavior

The example should run

## Environment

 - napari Version:  I can't tell, because I can't run `import napari` without getting the above crash :P I pulled from github today, when the latest commit was #205 
 - OS (e.g., Linux): Scientific Linux 7.3
 - Python version: 3.6
 - Any other relevant information: I'm running this on the janelia compute cluster in its own conda env, I installed it by running `python setup.py install`

**Comment by sofroniewn** [comment]
Hmm I'm not sure about this - the best I could find was https://www.riverbankcomputing.com/static/Docs/PyQt5/installation.html#downloading-sip, we'll look into it soon

**Comment by jni** [comment]
We should add "PyQt version" to the template... ;) @d-v-b could you provide the output of `conda list` as well?

Also, you mentioned the cluster — I guess you're doing X-forwarding? Can you confirm that other Qt-based things work? e.g. matplotlib from `ipython --matplotlib=qt5`

**Comment by d-v-b** [comment]
Here's the output of `conda list`. The big red flag that I forgot to mention: I added conda-forge to the default channel list, so basically all these packages are from there (this was necessary for getting an obscure image library to work a while ago)

```bash
(napari) [bennettd@c11u25 ~]$ conda list
WARNING: The conda.compat module is deprecated and will be removed in a future release.
# packages in environment at /groups/ahrens/home/bennettd/miniconda/envs/napari:
#
# Name                    Version                   Build  Channel
backcall                  0.1.0                      py_0    conda-forge
bzip2                     1.0.6             h14c3975_1002    conda-forge
ca-certificates           2019.3.9             hecc5488_0    conda-forge
certifi                   2019.3.9                 py37_0    conda-forge
cloudpickle               0.8.1                      py_0    conda-forge
cycler                    0.10.0                     py_1    conda-forge
cytoolz                   0.9.0.1         py37h14c3975_1001    conda-forge
dask-core                 1.1.5                      py_0    conda-forge
decorator                 4.4.0                      py_0    conda-forge
freetype                  2.10.0               he983fc9_0    conda-forge
icu                       58.2              hf484d3e_1000    conda-forge
imageio                   2.5.0                    py37_0    conda-forge
ipython                   7.4.0            py37h24bf2e0_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
jedi                      0.13.3                   py37_0    conda-forge
jpeg                      9c                h14c3975_1001    conda-forge
kiwisolver                1.0.1           py37h6bb024c_1002    conda-forge
libblas                   3.8.0                4_openblas    conda-forge
libcblas                  3.8.0                4_openblas    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 8.2.0                hdf63c60_1  
libgfortran-ng            7.3.0                hdf63c60_0  
liblapack                 3.8.0                4_openblas    conda-forge
libpng                    1.6.36            h84994c4_1000    conda-forge
libstdcxx-ng              8.2.0                hdf63c60_1  
libtiff                   4.0.10            h648cc4a_1001    conda-forge
matplotlib-base           3.0.3            py37h167e16e_0    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
networkx                  2.2                        py_1    conda-forge
numpy                     1.16.2           py37h8b7e671_1    conda-forge
olefile                   0.46                       py_0    conda-forge
openblas                  0.3.5             h9ac9557_1001    conda-forge
openssl                   1.1.1b               h14c3975_1    conda-forge
parso                     0.3.4                      py_0    conda-forge
pexpect                   4.7.0                    py37_0    conda-forge
pickleshare               0.7.5                 py37_1000    conda-forge
pillow                    6.0.0            py37he7afcd5_0    conda-forge
pip                       19.0.3                   py37_0    conda-forge
prompt_toolkit            2.0.9                      py_0    conda-forge
ptyprocess                0.6.0                 py37_1000    conda-forge
pygments                  2.3.1                      py_0    conda-forge
pyparsing                 2.3.1                      py_0    conda-forge
python                    3.7.3                h5b0a415_0    conda-forge
python-dateutil           2.8.0                      py_0    conda-forge
pywavelets                1.0.2            py37h3010b51_0    conda-forge
readline                  7.0               hf8c457e_1001    conda-forge
scikit-image              0.15.0           py37he1b5a44_0    conda-forge
scipy                     1.2.1            py37h09a28d5_1    conda-forge
setuptools                41.0.0                   py37_0    conda-forge
six                       1.12.0                py37_1000    conda-forge
sqlite                    3.26.0            h67949de_1001    conda-forge
tk                        8.6.9             h84994c4_1001    conda-forge
toolz                     0.9.0                      py_1    conda-forge
tornado                   6.0.2            py37h516909a_0    conda-forge
traitlets                 4.3.2                 py37_1000    conda-forge
wcwidth                   0.1.7                      py_1    conda-forge
wheel                     0.33.1                   py37_0    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
zlib                      1.2.11            h14c3975_1004    conda-forge
```

**Comment by d-v-b** [comment]
also, matplotlib-backed-by-qt does not work in this env: 
```python
In [1]: %gui qt                                                                                                           
ERROR:root:
    Could not load requested Qt binding. Please ensure that
    PyQt4 >= 4.7, PyQt5, PySide >= 1.0.3 or PySide2 is available,
    and only one is imported per session.

    Currently-imported Qt library:                              None
    PyQt4 available (requires QtCore, QtGui, QtSvg):            False
    PyQt5 available (requires QtCore, QtGui, QtSvg, QtWidgets): False
    PySide >= 1.0.3 installed:                                  False
    PySide2 installed:                                          False
    Tried to load:                                              ['pyqtdefault', 'pyside', 'pyqt5', 'pyside2']
```

**Comment by jni** [comment]
Erm, I literally see **no** PyQt installed?

**Comment by d-v-b** [comment]
looks like I had a brain-fart and didn't run `python setup.py install` before looking at `conda-list`. I re-built the env, ran `python setup.py install`:

I get the same issue with `PyQt5.sip` even with a much more reasonable list of packages:

```bash
(napari) [bennettd@c11u25 ~]$ conda list
WARNING: The conda.compat module is deprecated and will be removed in a future release.
# packages in environment at /groups/ahrens/home/bennettd/miniconda/envs/napari:
#
# Name                    Version                   Build  Channel
ca-certificates           2019.3.9             hecc5488_0    conda-forge
certifi                   2019.3.9                 py36_0    conda-forge
cloudpickle               0.8.1                      py_0    conda-forge
cycler                    0.10.0                     py_1    conda-forge
cytoolz                   0.9.0.1         py36h14c3975_1001    conda-forge
dask-core                 1.1.5                      py_0    conda-forge
decorator                 4.4.0                      py_0    conda-forge
freetype                  2.10.0               he983fc9_0    conda-forge
icu                       58.2              hf484d3e_1000    conda-forge
imageio                   2.5.0                    py36_0    conda-forge
jpeg                      9c                h14c3975_1001    conda-forge
kiwisolver                1.0.1           py36h6bb024c_1002    conda-forge
libblas                   3.8.0                4_openblas    conda-forge
libcblas                  3.8.0                4_openblas    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 8.2.0                hdf63c60_1  
libgfortran-ng            7.3.0                hdf63c60_0  
liblapack                 3.8.0                4_openblas    conda-forge
libpng                    1.6.36            h84994c4_1000    conda-forge
libstdcxx-ng              8.2.0                hdf63c60_1  
libtiff                   4.0.10            h648cc4a_1001    conda-forge
matplotlib-base           3.0.3            py36h167e16e_0    conda-forge
napari                    0.0.6+16.gcb0830c          pypi_0    pypi
ncurses                   6.1               hf484d3e_1002    conda-forge
networkx                  2.2                        py_1    conda-forge
numpy                     1.16.2                   pypi_0    pypi
olefile                   0.46                       py_0    conda-forge
openblas                  0.3.5             h9ac9557_1001    conda-forge
openssl                   1.1.1b               h14c3975_1    conda-forge
pillow                    6.0.0            py36he7afcd5_0    conda-forge
pip                       19.0.3                   py36_0    conda-forge
pyopengl                  3.1.3b2                  pypi_0    pypi
pyparsing                 2.4.0                      py_0    conda-forge
pyqt5                     5.12.1                   pypi_0    pypi
pyqt5-sip                 4.19.15                  pypi_0    pypi
python                    3.6.7             h381d211_1004    conda-forge
python-dateutil           2.8.0                      py_0    conda-forge
pywavelets                1.0.2            py36h3010b51_0    conda-forge
readline                  7.0               hf8c457e_1001    conda-forge
scikit-image              0.15.0           py36he1b5a44_0    conda-forge
scipy                     1.2.1                    pypi_0    pypi
setuptools                41.0.0                   py36_0    conda-forge
sip                       4.19.8                   pypi_0    pypi
six                       1.12.0                py36_1000    conda-forge
sqlite                    3.26.0            h67949de_1001    conda-forge
tk                        8.6.9             h84994c4_1001    conda-forge
toolz                     0.9.0                      py_1    conda-forge
tornado                   6.0.2            py36h516909a_0    conda-forge
vispy                     0.5.3                    pypi_0    pypi
wheel                     0.33.1                   py36_0    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
zlib                      1.2.11            h14c3975_1004    conda-forge
```

**Comment by d-v-b** [comment]
In case it's helpful, here's the output of the install process: https://gist.github.com/d-v-b/601842fcf5f879173011599956359af7

**Comment by jni** [comment]
Thanks @d-v-b! 

(a) does matplotlib qt5 work now?
(b) could you try again (sorry) but installing PyQt5 from conda-forge instead of PyPI? My suspicion is that you need to install Qt5 separately when getting PyQt5 from PyPI.

**Comment by d-v-b** [comment]
a) matplotlib qt5 does work
b) installing pyqt5 from conda forge does not work, but now with different errors. At this point I think these issues derive from your minimum pyqt5 version (5.10.1) not being on any conda channel I could find. The highest version I could find on `conda` and `conda-forge` is 5.9.2.

**Comment by jni** [comment]
(a) dang. =P
(b) what about pip installing a later version of PyQt5 from PyPI on top of a conda-forge install of it?

**Comment by d-v-b** [comment]
b) doesn't work (the nD_image.py example runs, but no image is displayed, and trying to use ViewerApp in ipython suggests that napari is asking for a Qt api that doesn't exist: see here: https://gist.github.com/d-v-b/8c0e839da32aca7b2c431678490f6394)

Also i start getting binary incompatibility warnings, suggesting that we're in the "dont mix conda and pip packages" territory

**Comment by sofroniewn** [comment]
@d-v-b - we've now switched over to `PySide2` so curious if it is any better now? Can you try again with the latest napari release `0.1.4`

**Comment by d-v-b** [comment]
I just checked and nD_image.py is working now. So it's fixed, as far as I can tell. I'm not going to do any more extensive testing for now, but you can feel free to close this.

**Comment by sofroniewn** [comment]
Ok sounds good, thanks for checking -  i'm closing this now - we can always reopen if we have more problems in the future
