### ISSUE TITLE
Export Tracks Layer as tiff image

### ISSUE THREAD

**Issue by kapoorlab** [napari/napari#2090]
## 🚀 Feature
Napari Track layer in 3D is a (N, 5) dimensional vector associated with a corresponding (TZYX) image, I can export the images as tiff but not the track overlay as tif, the best I could do is to write it as a csv file, however it would be nice to have tracks layer exported as tif as well, with the actual tracks as overlay on the exported image.

## Motivation

It makes biological analysis more presentable when you have the files saved as tif in folders and exportable as tiff/avi.

## Pitch

Export track_layer with imwrite as tiff file.

**Comment by jni** [comment]
I think https://github.com/sofroniewn/napari-animation is what is needed here, @kapoorlab?

**Comment by kapoorlab** [comment]
The link is broken :(

**Comment by jni** [comment]
Oops, sorry, that's what I get for trying to type from memory. Try now?

**Comment by kapoorlab** [comment]
It is almost working, I found one bug and I get one error message.

Bug:
This wont work from __init__.py as there is not hookimpls.py file: 
from ._hookimpls import napari_experimental_provide_dock_widget
So I commeted it out and then the widget opens but when I try to capture frame I get this error messge.

Error:


'''
ERROR:root:Unhandled exception:
Traceback (most recent call last):
  File "/Users/aimachine/SmartSeeds/AnalysisTools/napatrackmater/napari_animation/_qt/animation_widget.py", line 87, in _capture_keyframe_callback
    self.animation.capture_keyframe(steps=self._get_interpolation_steps(),
  File "/Users/aimachine/SmartSeeds/AnalysisTools/napatrackmater/napari_animation/animation.py", line 52, in capture_keyframe
    new_state = {'viewer': self._get_viewer_state(), 'steps': steps, 'ease': ease}
  File "/Users/aimachine/SmartSeeds/AnalysisTools/napatrackmater/napari_animation/animation.py", line 81, in _get_viewer_state
    'camera': self.viewer.camera.asdict(),
AttributeError: 'Camera' object has no attribute 'asdict' 
'''

**Comment by jni** [comment]
Cool! napari version? I think you need a slightly newer version, `viewer.camera.asdict()` just worked for me on 0.4.3.

**Comment by kapoorlab** [comment]
I am on 0.4.2, trying the 0.4.3 now

**Comment by kapoorlab** [comment]
The error goes away but then when I try to Save Animation as mp4 I get this error coming from the png saving part of the code. I do not want to save it as png anyway just mp4 but I do not see any mp4 files saved also. 

'''
ERROR:root:Unhandled exception:
Traceback (most recent call last):
  File "/Users/aimachine/SmartSeeds/AnalysisTools/napatrackmater/napari_animation/_qt/animation_widget.py", line 121, in _save_callback
    self.animation.animate(path)
  File "/Users/aimachine/SmartSeeds/AnalysisTools/napatrackmater/napari_animation/animation.py", line 203, in animate
    folder_path.joinpath(path_obj.stem + '_' + str(ind) + '.png'),
UnboundLocalError: local variable 'folder_path' referenced before assignment

Saving animation to demo.mp4
To use the imageio ffmpeg plugin you need to 'pip install imageio-ffmpeg'
Your movie will be saved as a series of PNG files.
'''

**Comment by kapoorlab** [comment]
Then I specified the path as directory in the animation wizard but still an error and no mp4 saved:

'''
ERROR:root:Unhandled exception:
Traceback (most recent call last):
  File "/Users/aimachine/SmartSeeds/AnalysisTools/napatrackmater/napari_animation/_qt/animation_widget.py", line 121, in _save_callback
    self.animation.animate(path)
  File "/Users/aimachine/SmartSeeds/AnalysisTools/napatrackmater/napari_animation/animation.py", line 189, in animate
    folder_path = path_obj.parent.joinpath(path.stem)
AttributeError: 'str' object has no attribute 'stem'

Saving animation to /Users/aimachine/1cell_Tracking/
ERROR:root:Unhandled exception:
Traceback (most recent call last):
  File "/Users/aimachine/SmartSeeds/AnalysisTools/napatrackmater/napari_animation/_qt/animation_widget.py", line 121, in _save_callback
    self.animation.animate(path)
  File "/Users/aimachine/SmartSeeds/AnalysisTools/napatrackmater/napari_animation/animation.py", line 189, in animate
    folder_path = path_obj.parent.joinpath(path.stem)
AttributeError: 'str' object has no attribute 'stem'

Saving animation to /Users/aimachine/1cell_Tracking
'''

**Comment by kapoorlab** [comment]
I am on python version 3.9.0

**Comment by kapoorlab** [comment]
I fixed those code lines to make it work for me. I think this is what I was looking for, now I just have to dig a bit deep into using it properly for my use case, which would be to make a button that runs the viewer with visible layers in time to record the animation to save. Many thanks.

**Comment by jni** [comment]
UnboundLocalError is always a bug. Nick built that very quickly recently and it's not yet battle tested, so thanks for helping us do that! 😊 But I think this discussion now belongs in the napari animation repo. I'll close this for now. Good luck!
