### ISSUE TITLE
Exception when drawing polygon in shape layer 

### ISSUE THREAD

**Issue by royerloic** [napari/napari#223]
## 🐛 Bug

An exception showed up. Could not reproduce but the stack trace might give some hints.
Maybe adding some checks could help make the responsible code more robust to corner cases:

`/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/bin/python3.6 /Users/royer/workspace/python/napari/examples/add_shapes.py
WARNING: Traceback (most recent call last):
  File "/Users/royer/workspace/python/napari/examples/add_shapes.py", line 51, in <module>
    layer._qt_properties.setExpanded(True)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
  File "/Users/royer/workspace/python/napari/napari/util/app.py", line 26, in app_context
    app.exec()
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/vispy/app/backends/_qt.py", line 436, in event
    out = super(QtBaseCanvasBackend, self).event(ev)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/vispy/app/backends/_qt.py", line 375, in mousePressEvent
    modifiers=self._modifiers(ev),
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/vispy/app/base.py", line 176, in _vispy_mouse_press
    ev = self._vispy_canvas.events.mouse_press(**kwargs)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/vispy/util/event.py", line 455, in __call__
    self._invoke_callback(cb, event)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/vispy/util/event.py", line 475, in _invoke_callback
    self, cb_event=(cb, event))
  << caught exception here: >>
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/vispy/util/event.py", line 471, in _invoke_callback
    cb(event)
  File "/Users/royer/workspace/python/napari/napari/components/_viewer/view/view.py", line 93, in on_mouse_press
    layer.on_mouse_press(event)
  File "/Users/royer/workspace/python/napari/napari/layers/_shapes_layer/model.py", line 1286, in on_mouse_press
    self.data.edit(index, vertices, new_type=new_type)
  File "/Users/royer/workspace/python/napari/napari/layers/_shapes_layer/shape_list.py", line 278, in edit
    z_index=cur_shape.z_index)
  File "/Users/royer/workspace/python/napari/napari/layers/_shapes_layer/shapes/polygon.py", line 36, in __init__
    self.data = np.array(data)
  File "/Users/royer/workspace/python/napari/napari/layers/_shapes_layer/shapes/polygon.py", line 51, in data
    self._set_meshes(data)
  File "/Users/royer/workspace/python/napari/napari/layers/_shapes_layer/shapes/shape.py", line 193, in _set_meshes
    vertices, triangles = triangulate_face(data)
  File "/Users/royer/workspace/python/napari/napari/layers/_shapes_layer/shape_util.py", line 490, in triangulate_face
    vertices, triangles = PolygonData(vertices=data).triangulate()
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/vispy/geometry/polygon.py", line 130, in triangulate
    tri.triangulate()
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/vispy/geometry/triangulation.py", line 141, in triangulate
    while pts[front[idx+1], 0] <= pi[0]:
IndexError: list index out of range
ERROR: Invoking <bound method QtViewer.on_mouse_press of <napari.components._viewer.view.view.QtViewer object at 0x12a8d4ca8>> for MouseEvent
WARNING: Traceback (most recent call last):
  File "/Users/royer/workspace/python/napari/examples/add_shapes.py", line 51, in <module>
    layer._qt_properties.setExpanded(True)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
  File "/Users/royer/workspace/python/napari/napari/util/app.py", line 26, in app_context
    app.exec()
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/vispy/app/backends/_qt.py", line 436, in event
    out = super(QtBaseCanvasBackend, self).event(ev)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/vispy/app/backends/_qt.py", line 404, in mouseMoveEvent
    modifiers=self._modifiers(ev),
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/vispy/app/base.py", line 208, in _vispy_mouse_move
    ev = self._vispy_canvas.events.mouse_move(**kwargs)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/vispy/util/event.py", line 455, in __call__
    self._invoke_callback(cb, event)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/vispy/util/event.py", line 475, in _invoke_callback
    self, cb_event=(cb, event))
  << caught exception here: >>
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/vispy/util/event.py", line 471, in _invoke_callback
    cb(event)
  File "/Users/royer/workspace/python/napari/napari/components/_viewer/view/view.py", line 86, in on_mouse_move
    layer.on_mouse_move(event)
  File "/Users/royer/workspace/python/napari/napari/layers/_shapes_layer/model.py", line 1455, in on_mouse_move
    self._move(coord)
  File "/Users/royer/workspace/python/napari/napari/layers/_shapes_layer/model.py", line 1168, in _move
    vertices[vertex] = coord
IndexError: index 2 is out of bounds for axis 0 with size 2`

## To Reproduce

Cannot reproduce, but did this:
1. open shape layer
2. draw polygons.
3. sometimes theexceptionn shows up

## Expected behavior

no exception.

## Environment

 - napari Version (e.g., 1.0): latest dim PR
 - OS (e.g., Linux): OSX
 - Python version: 3.7
 - Any other relevant information:

## Additional context

N/A

**Comment by sofroniewn** [comment]
This is likely due to the dims refactor - I have a guess at what is causing it but can you tell me a little more about which example you are using and what you did.

i.e. did you run the `examples/add_shapes.py` and draw new shapes in the existing shape layer, or did you run `examples/add_shapes.py` and click the `add_shape_layer` button in the bottom right to add a new empty shape layer and start drawing in that, or did you run another example ....

**Comment by sofroniewn** [comment]
Bug identified - it happens when you create a polygon of zero size. Will fix it in a new PR. It is unrelated to the dims PR stuff

**Comment by sofroniewn** [comment]
Also note that there is a bug when drawing a line right now that I fix in #220. I could make a separate PR to just fix that bug or it will get fixed when that PR merges

**Comment by sofroniewn** [comment]
these have now been fixed with #230 and #231
