### ISSUE TITLE
Unhandled exeption when adding dask array as an image layer

### ISSUE THREAD

**Issue by sebi06** [napari/napari#2245]
Hi,

I try to achieve the following (napari=0.4.4, Python 3.7.4, Win10 64bit)

* load and CZI that has 96 scenes via dask-delayed (per scene) into an dask array  - OK
*  cutout every channel from this array and add it as a layer to the napari viewer

It fails here with the error message below. The the shape of the complete array looks good and also the shape of the individual channel has the correct shape.
When I try this whole thing using numpy arrays only, it works so it has to do something with the dask array, but I cannot figure out what. Any help is appreciated.

```python
# add channel to napari viewer
new_layer = viewer.add_image(channel,
                             name=chname,
                             scale=scalefactors_ch,
                             blending=blending,
                             gamma=gamma)
```

Info about channel array:

```text
dask.array<getitem, shape=(96, 1, 1, 1, 1416, 1960), dtype=uint16, chunksize=(1, 1, 1, 1, 1416, 1960), chunktype=numpy.ndarray>
```

Output:

```bash
(96, 1, 2, 1, 1416, 1960)
Adding Channel  : AF568
Shape Channel   : 0 (96, 1, 1, 1, 1416, 1960)
Scaling Factors : [1.0, 1.0, 1.0, 1.0, 1.0]
ERROR:root:Unhandled exception:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\imageanalysis\lib\site-packages\napari\_qt\qt_event_loop.py", line 179, in gui_qt
    yield app
  File "c:\Users\m1srh\Documents\GitHub\czi_demos\test_czi_scenes_dask_zarr.py", line 121, in <module>
    rename_sliders=True)
  File "c:\Users\m1srh\Documents\GitHub\czi_demos\imgfile_tools.py", line 1384, in show_napari
    gamma=gamma)
  File "C:\ProgramData\Anaconda3\envs\imageanalysis\lib\site-packages\napari\components\viewer_model.py", line 737, in add_image
    layer = image_class(data, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\imageanalysis\lib\site-packages\napari\layers\image\image.py", line 276, in __init__
    self._update_dims()
  File "C:\ProgramData\Anaconda3\envs\imageanalysis\lib\site-packages\napari\layers\base\base.py", line 530, in _update_dims
    self.refresh()
  File "C:\ProgramData\Anaconda3\envs\imageanalysis\lib\site-packages\napari\layers\base\base.py", line 940, in refresh
    self.set_view_slice()
  File "C:\ProgramData\Anaconda3\envs\imageanalysis\lib\site-packages\napari\layers\base\base.py", line 800, in set_view_slice
    self._set_view_slice()
  File "C:\ProgramData\Anaconda3\envs\imageanalysis\lib\site-packages\napari\layers\image\image.py", line 613, in _set_view_slice
    self._load_slice(data)
  File "C:\ProgramData\Anaconda3\envs\imageanalysis\lib\site-packages\napari\layers\image\image.py", line 624, in _load_slice
    self._on_data_loaded(data, sync=True)
  File "C:\ProgramData\Anaconda3\envs\imageanalysis\lib\site-packages\napari\layers\image\image.py", line 645, in _on_data_loaded
    data.transpose(self._get_order())
  File "C:\ProgramData\Anaconda3\envs\imageanalysis\lib\site-packages\napari\layers\image\_image_slice_data.py", line 53, in transpose
    self.image = self.image.transpose(order)
ValueError: axes don't match array
```

**Comment by sofroniewn** [comment]
Hi @sebi06 thanks for filing, someone will look at this soon :-)

**Comment by andy-sweet** [comment]
I could not reproduce this at v0.4.4 on macOS. I suspect it's not OS dependent, but can try on Windows too later.

From the initial description, I was not sure on the exact setup here, but here's the example I put together.

```python
import dask
import dask.array as da
import numpy as np

import napari

shape = (96, 1, 1, 1, 1416, 1960)
delayed = dask.delayed(np.ones)(shape)
array = da.from_delayed(delayed, shape, dtype=float)

viewer = napari.Viewer()
scale = (1, 1, 1, 1, 1)
viewer.add_image(array[0], scale=scale)

napari.run()
``` 

This also works if I pass the whole `array` instead of `array[0]`.

@sebi06 : if this is still an issue for you, let me know how I should update the example above to reflect your data and then I can take a look at potential fixes.

**Comment by jni** [comment]
Another important bit of info is @sebi06 if you could run the script with `python -m pdb script.py`, then when you hit the error:

```pytb
    self.image = self.image.transpose(order)
ValueError: axes don't match array
```

You can tell us what `self.image` contains and what `order` contains. To me it smells of an issue with arrays of different dimensionality in the viewer and/or transposed axes.

**Comment by sebi06** [comment]
Hi all,

meanwhile I am running Python 3.9.12 and napari 0.4.16 and the problem is not occurring to me anymore. It works as expected and the individual scenes can be loaded  "lazy" without any problems.

<img width="1447" alt="image" src="https://user-images.githubusercontent.com/3833249/172386307-0afe2bf7-8bb1-400d-93a2-8e714cc31881.png">

**Comment by jni** [comment]
Great! I'll close this then, thanks for reporting back @sebi06! Please feel free to reopen if the problem reappears, and of course raise new issues as they come up! :pray:
