### ISSUE TITLE
magicgui integration problem

### ISSUE THREAD

**Issue by alisterburt** [napari/napari#2315]
I'm running into an issue with the napari/magicgui integration, looks like it may be a version mismatch somewhere but I'm fairly up to date

```
napari: 0.4.5
Platform: macOS-11.2.1-x86_64-i386-64bit
System: MacOS 11.2.1
Python: 3.9.1 | packaged by conda-forge | (default, Jan 26 2021, 01:32:59)  [Clang 11.0.1 ]
Qt: 5.12.9
PyQt5: 5.12.3
NumPy: 1.20.1
SciPy: 1.6.0
Dask: 2021.02.0
VisPy: 0.6.6

OpenGL:
  - GL version:  2.1 Metal - 71.0.7
  - MAX_TEXTURE_SIZE: 16384

Screens:
  - screen 1: resolution 1440x900, scale 2.0

Plugins:
  - console: 0.0.3
  - svg: 0.1.4
```

with magicgui 0.2.6

When I try to run the [magicgui napari example](https://napari.org/magicgui/examples/napari/napari_img_math.html#code) the `FunctionGui` is created fine but when I click the execute button I get

```
ERROR:root:Unhandled exception:
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py39/lib/python3.9/site-packages/magicgui/widgets/_bases/value_widget.py", line 44, in <lambda>
    lambda *x: self.changed(value=x[0] if x else None)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py39/lib/python3.9/site-packages/magicgui/events.py", line 603, in __call__
    self._invoke_callback(cb, event)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py39/lib/python3.9/site-packages/magicgui/events.py", line 621, in _invoke_callback
    _handle_exception(
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py39/lib/python3.9/site-packages/magicgui/events.py", line 619, in _invoke_callback
    cb(event)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py39/lib/python3.9/site-packages/magicgui/widgets/_function_gui.py", line 179, in <lambda>
    self._call_button.changed.connect(lambda e: self.__call__())
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py39/lib/python3.9/site-packages/magicgui/widgets/_function_gui.py", line 272, in __call__
    callback(self, value, return_type)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py39/lib/python3.9/site-packages/napari/utils/_magicgui.py", line 341, in add_layer_to_viewer
    viewer.add_layer(result)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py39/lib/python3.9/site-packages/napari/components/viewer_model.py", line 479, in add_layer
    self.layers.append(layer)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py39/lib/python3.9/_collections_abc.py", line 988, in append
    self.insert(len(self), value)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py39/lib/python3.9/site-packages/napari/components/layerlist.py", line 68, in insert
    new_layer = self._type_check(value)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py39/lib/python3.9/site-packages/napari/utils/events/containers/_typed.py", line 164, in _type_check
    raise TypeError(
TypeError: Cannot add object with type <class 'numpy.ndarray'> to TypedList expecting type (<class 'napari.layers.base.base.Layer'>,)

ERROR:root:Unhandled exception:
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py39/lib/python3.9/site-packages/magicgui/widgets/_bases/value_widget.py", line 44, in <lambda>
    lambda *x: self.changed(value=x[0] if x else None)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py39/lib/python3.9/site-packages/magicgui/events.py", line 603, in __call__
    self._invoke_callback(cb, event)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py39/lib/python3.9/site-packages/magicgui/events.py", line 621, in _invoke_callback
    _handle_exception(
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py39/lib/python3.9/site-packages/magicgui/events.py", line 619, in _invoke_callback
    cb(event)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py39/lib/python3.9/site-packages/magicgui/widgets/_function_gui.py", line 179, in <lambda>
    self._call_button.changed.connect(lambda e: self.__call__())
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py39/lib/python3.9/site-packages/magicgui/widgets/_function_gui.py", line 272, in __call__
    callback(self, value, return_type)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py39/lib/python3.9/site-packages/napari/utils/_magicgui.py", line 341, in add_layer_to_viewer
    viewer.add_layer(result)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py39/lib/python3.9/site-packages/napari/components/viewer_model.py", line 479, in add_layer
    self.layers.append(layer)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py39/lib/python3.9/_collections_abc.py", line 988, in append
    self.insert(len(self), value)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py39/lib/python3.9/site-packages/napari/components/layerlist.py", line 68, in insert
    new_layer = self._type_check(value)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py39/lib/python3.9/site-packages/napari/utils/events/containers/_typed.py", line 164, in _type_check
    raise TypeError(
TypeError: Cannot add object with type <class 'numpy.ndarray'> to TypedList expecting type (<class 'napari.layers.base.base.Layer'>,)

ERROR:root:Unhandled exception:
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py39/lib/python3.9/site-packages/magicgui/widgets/_bases/value_widget.py", line 44, in <lambda>
    lambda *x: self.changed(value=x[0] if x else None)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py39/lib/python3.9/site-packages/magicgui/events.py", line 603, in __call__
    self._invoke_callback(cb, event)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py39/lib/python3.9/site-packages/magicgui/events.py", line 621, in _invoke_callback
    _handle_exception(
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py39/lib/python3.9/site-packages/magicgui/events.py", line 619, in _invoke_callback
    cb(event)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py39/lib/python3.9/site-packages/magicgui/widgets/_function_gui.py", line 179, in <lambda>
    self._call_button.changed.connect(lambda e: self.__call__())
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py39/lib/python3.9/site-packages/magicgui/widgets/_function_gui.py", line 272, in __call__
    callback(self, value, return_type)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py39/lib/python3.9/site-packages/napari/utils/_magicgui.py", line 341, in add_layer_to_viewer
    viewer.add_layer(result)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py39/lib/python3.9/site-packages/napari/components/viewer_model.py", line 479, in add_layer
    self.layers.append(layer)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py39/lib/python3.9/_collections_abc.py", line 988, in append
    self.insert(len(self), value)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py39/lib/python3.9/site-packages/napari/components/layerlist.py", line 68, in insert
    new_layer = self._type_check(value)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/py39/lib/python3.9/site-packages/napari/utils/events/containers/_typed.py", line 164, in _type_check
    raise TypeError(
TypeError: Cannot add object with type <class 'numpy.ndarray'> to TypedList expecting type (<class 'napari.layers.base.base.Layer'>,)
```

I guess I could fix it by returning a layer directly but thought I should let you know in case it's a bug!

**Comment by tlambert03** [comment]
arg... this might be another case of what @sofroniewn fixed in https://github.com/napari/magicgui/pull/154/files

The return annotation shouldn't be `Image` anymore unless you're actually returning an `Image`.  To return just a numpy array (as is done in that example), try a return annotation of `napari.types.ImageData` (as in [this example](https://github.com/napari/magicgui/blob/master/examples/napari_image_arithmetic.py))

Sorry, need to update the docs (I thought we had a deprecation warning for this ... but maybe that's already been removed).

**Comment by alisterburt** [comment]
Brilliant, changing the return type sorted it - thanks for the quick reply!

**Comment by sofroniewn** [comment]
> Sorry, need to update the docs (I thought we had a deprecation warning for this ... but maybe that's already been removed).

Yeah we did, we could add back in, sorry, it was there for 2 releases but maybe that was too quick!
