### ISSUE TITLE
Deleting points data is broken with an index error

### ISSUE THREAD

**Issue by jni** [napari/napari#2382]
## 🐛 Bug

Using git bisect I tracked the problem to #2204 (sorry @kevinyamauchi 😬), which broke resetting of a Points layer data, which now raises an IndexError (see below).

## To Reproduce

```python
import numpy as np
import napari

viewer = napari.Viewer()
points = np.random.random((4, 2)) * 4

pts_layer = viewer.add_points(points)
pts_layer.data = np.zeros([0, 2])
```

raises:

```pytb
Traceback (most recent call last):
  File "test-points-delete.py", line 8, in <module>
    pts_layer.data = np.zeros([0, 2])
  File "/Users/jni/projects/napari/napari/layers/points/points.py", line 422, in data
    self._edge._remove(
  File "/Users/jni/projects/napari/napari/layers/utils/color_manager.py", line 330, in _remove
    self.colors = np.delete(self.colors, selected_indices, axis=0)
  File "/Users/jni/projects/napari/napari/utils/events/evented_model.py", line 154, in __setattr__
    getattr(self.events, name)(value=after)  # emit event
  File "/Users/jni/projects/napari/napari/utils/events/event.py", line 550, in __call__
    self._invoke_callback(cb, event)
  File "/Users/jni/projects/napari/napari/utils/events/event.py", line 567, in _invoke_callback
    _handle_exception(
  File "/Users/jni/projects/napari/napari/utils/events/event.py", line 565, in _invoke_callback
    cb(event)
  File "/Users/jni/projects/napari/napari/_vispy/vispy_points_layer.py", line 41, in _on_data_change
    edge_color = self.layer._view_edge_color
  File "/Users/jni/projects/napari/napari/layers/points/points.py", line 1187, in _view_edge_color
    return self.edge_color[self._indices_view]
IndexError: index 0 is out of bounds for axis 0 with size 0
```

Interestingly, the below doesn't have any issues:

```python
import numpy as np
import napari

points = np.random.random((4, 2)) * 4

pts_layer = napari.layers.Points(points)
pts_layer.data = np.zeros([0, 2])
```

Which suggests that it's the event callback system that's broken, *not* the points layer itself. That would explain why this got past testing.

## Expected behavior

The color elements should be removed together with the data.

## Environment

```
napari: 0.4.6.dev45+geaa54747.d20210303
Platform: macOS-10.15.7-x86_64-i386-64bit
System: MacOS 10.15.7
Python: 3.8.2 (default, Mar 26 2020, 10:43:30)  [Clang 4.0.1 (tags/RELEASE_401/final)]
Qt: 5.14.2
PyQt5: 5.14.2
NumPy: 1.19.2
SciPy: 1.5.1
Dask: 2021.01.1
VisPy: 0.6.5.dev320+gc275797b

OpenGL:
  - GL version:  2.1 ATI-3.10.19
  - MAX_TEXTURE_SIZE: 16384

Screens:
  - screen 1: resolution 2048x1152, scale 2.0
  - screen 2: resolution 1536x960, scale 2.0

Plugins:
  - affinder: 0.1.dev16+g189efd8
  - animation: 0.1.dev78+g5716ec8
  - btrack-reader: 0.1.0
  - console: 0.0.3
  - napari-sentinel-zip: 0.2.2
  - ome_zarr: 0.0.18.dev0
  - s3zarr: 0.0.2
  - svg: 0.1.4
  - tracks: 0.0.2
```

**Comment by jni** [comment]
I'll also take this opportunity to thank @tlambert03 for all his work cleaning up our Qt launching which makes testing these things way cleaner!
