### ISSUE TITLE
Napari crashes on Mac OS Big Sur

### ISSUE THREAD

**Issue by ColasDroin** [napari/napari#2485]
## 🐛 Bug

When running napari in the terminal, it doesn't open and I get the following error:
```
(napari-env) cdroin@MacBook-Pro-de-Colas ~ % napari
Traceback (most recent call last):
  File "/Users/cdroin/opt/anaconda3/envs/napari-env/bin/napari", line 5, in <module>
    from napari.__main__ import main
  File "/Users/cdroin/opt/anaconda3/envs/napari-env/lib/python3.8/site-packages/napari/__init__.py", line 7, in <module>
    from .viewer import Viewer  # isort:skip
  File "/Users/cdroin/opt/anaconda3/envs/napari-env/lib/python3.8/site-packages/napari/viewer.py", line 3, in <module>
    from .components import ViewerModel
  File "/Users/cdroin/opt/anaconda3/envs/napari-env/lib/python3.8/site-packages/napari/components/__init__.py", line 17, in <module>
    from .camera import Camera
  File "/Users/cdroin/opt/anaconda3/envs/napari-env/lib/python3.8/site-packages/napari/components/camera.py", line 5, in <module>
    from ..utils.events import EventedModel
  File "/Users/cdroin/opt/anaconda3/envs/napari-env/lib/python3.8/site-packages/napari/utils/__init__.py", line 1, in <module>
    from .colormaps import Colormap
  File "/Users/cdroin/opt/anaconda3/envs/napari-env/lib/python3.8/site-packages/napari/utils/colormaps/__init__.py", line 2, in <module>
    from .colormap import Colormap
  File "/Users/cdroin/opt/anaconda3/envs/napari-env/lib/python3.8/site-packages/napari/utils/colormaps/colormap.py", line 6, in <module>
    from ..events import EventedModel
  File "/Users/cdroin/opt/anaconda3/envs/napari-env/lib/python3.8/site-packages/napari/utils/events/__init__.py", line 1, in <module>
    from .event import EmitterGroup, Event, EventEmitter  # isort:skip
  File "/Users/cdroin/opt/anaconda3/envs/napari-env/lib/python3.8/site-packages/napari/utils/events/event.py", line 69, in <module>
    from vispy.util.logs import _handle_exception, logger
  File "/Users/cdroin/opt/anaconda3/envs/napari-env/lib/python3.8/site-packages/vispy/__init__.py", line 30, in <module>
    from .util import config, set_log_level, keys, sys_info  # noqa
  File "/Users/cdroin/opt/anaconda3/envs/napari-env/lib/python3.8/site-packages/vispy/util/__init__.py", line 14, in <module>
    from . import fonts       # noqa
  File "/Users/cdroin/opt/anaconda3/envs/napari-env/lib/python3.8/site-packages/vispy/util/fonts/__init__.py", line 13, in <module>
    from ._triage import _load_glyph, list_fonts  # noqa, analysis:ignore
  File "/Users/cdroin/opt/anaconda3/envs/napari-env/lib/python3.8/site-packages/vispy/util/fonts/_triage.py", line 14, in <module>
    from ._quartz import _load_glyph, _list_fonts
  File "/Users/cdroin/opt/anaconda3/envs/napari-env/lib/python3.8/site-packages/vispy/util/fonts/_quartz.py", line 12, in <module>
    from ...ext.cocoapy import cf, ct, quartz, CFRange, CFSTR, CGGlyph, UniChar, \
  File "/Users/cdroin/opt/anaconda3/envs/napari-env/lib/python3.8/site-packages/vispy/ext/cocoapy.py", line 930, in <module>
    cf.CFStringCreateWithCString.restype = c_void_p
  File "/Users/cdroin/opt/anaconda3/envs/napari-env/lib/python3.8/ctypes/__init__.py", line 394, in __getattr__
    func = self.__getitem__(name)
  File "/Users/cdroin/opt/anaconda3/envs/napari-env/lib/python3.8/ctypes/__init__.py", line 399, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: dlsym(RTLD_DEFAULT, CFStringCreateWithCString): symbol not found
```

## To Reproduce

I'm using Mac OS Big Sur 11.2.3, I installed napari in a virtual environment following the tutorial on the official doc, namely:
```
conda create -y -n napari-env python=3.8
conda activate napari-env
pip install napari
```
In practice, napari-0.4.7 is the one that has been installed.

## Environment

Mac OS Big Sur 11.2.3
Virtual environment with Python 3.8
napari-0.4.7

## Additional context
I'm not sure it's linked but the bundled app also happens to crash at launch on my laptop.

**Comment by tlambert03** [comment]
as far as we've seen so far, big sur requires python 3.9 (see some related discussion [here](https://github.com/napari/napari/issues/1393)).  Can you try again with `conda create -y -n napari-env python=3.9`?

**Comment by ColasDroin** [comment]
Thank you, unfortunately this doesn't work either, but I actually found a workaround from [one of your older posts](https://github.com/napari/napari/issues/2287):

```
conda create -y -n napari-env -c conda-forge python=3.9
conda activate napari-env
pip install 'napari[all]'
```
Not sure I understand why, but it seems that using a different channel to get Python 3.9 seems needed. Also, using  `'napari[all]'` (with quotes) is needed. Indeed, it doesn't seem to work without the quotes, and installing napari without the `[all]` creates some dependency problem with PyQt afterwards.

**Comment by tlambert03** [comment]
great, glad you got it working:

> it seems that using a different channel to get Python 3.9 seems needed

ah, yep... the major thing that changed in big sur relates to how shared libraries are accessed, and i think that there are some subtle differences in the different python distributions.  conda-forge seems to be working well at this point.

> Also, using 'napari[all]' (with quotes) is needed

yeah, if you're using zsh (now the default on macOS) instead of bash, you need to escape the brackets (see explanation [here](https://stackoverflow.com/a/30539963))

> installing napari without the [all] creates some dependency problem with PyQt afterwards.

indeed, napari requires a Qt backend (it can be either PyQt5 or PySide2), but we don't include it by default.  `napari[all]` is currently an alias for `pip install napari pyqt5` (see slightly more explanation [here](https://napari.org/index.html#from-pip-with-batteries-included))

**Comment by ColasDroin** [comment]
Yep, thank you for the explanation!
