### ISSUE TITLE
translations._load_language (& all settings loads) needs a try/except

### ISSUE THREAD

**Issue by tlambert03** [napari/napari#2504]
## 🐛 Bug

I was just running some pytests on a non-napari package, in an environment that happened to have napari installed, and started getting errors because napari is registered as a pytest plugin, but was failing to import.  Here's the full trace:

<details>

```pytb
Traceback (most recent call last):
  File "/Users/talley/miniconda3/envs/magicdev/bin/pytest", line 8, in <module>
    sys.exit(console_main())
  File "/Users/talley/miniconda3/envs/magicdev/lib/python3.8/site-packages/_pytest/config/__init__.py", line 185, in console_main
    code = main()
  File "/Users/talley/miniconda3/envs/magicdev/lib/python3.8/site-packages/_pytest/config/__init__.py", line 143, in main
    config = _prepareconfig(args, plugins)
  File "/Users/talley/miniconda3/envs/magicdev/lib/python3.8/site-packages/_pytest/config/__init__.py", line 318, in _prepareconfig
    config = pluginmanager.hook.pytest_cmdline_parse(
  File "/Users/talley/miniconda3/envs/magicdev/lib/python3.8/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/Users/talley/miniconda3/envs/magicdev/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/Users/talley/miniconda3/envs/magicdev/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "/Users/talley/miniconda3/envs/magicdev/lib/python3.8/site-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "/Users/talley/miniconda3/envs/magicdev/lib/python3.8/site-packages/_pytest/helpconfig.py", line 100, in pytest_cmdline_parse
    config: Config = outcome.get_result()
  File "/Users/talley/miniconda3/envs/magicdev/lib/python3.8/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/Users/talley/miniconda3/envs/magicdev/lib/python3.8/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/Users/talley/miniconda3/envs/magicdev/lib/python3.8/site-packages/_pytest/config/__init__.py", line 1003, in pytest_cmdline_parse
    self.parse(args)
  File "/Users/talley/miniconda3/envs/magicdev/lib/python3.8/site-packages/_pytest/config/__init__.py", line 1283, in parse
    self._preparse(args, addopts=addopts)
  File "/Users/talley/miniconda3/envs/magicdev/lib/python3.8/site-packages/_pytest/config/__init__.py", line 1172, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File "/Users/talley/miniconda3/envs/magicdev/lib/python3.8/site-packages/pluggy/manager.py", line 299, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/Users/talley/miniconda3/envs/magicdev/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/Users/talley/miniconda3/envs/magicdev/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/Users/talley/miniconda3/envs/magicdev/lib/python3.8/site-packages/_pytest/assertion/rewrite.py", line 170, in exec_module
    exec(co, module.__dict__)
  File "/Users/talley/Dropbox (HMS)/Python/forks/napari/napari/__init__.py", line 7, in <module>
    from .viewer import Viewer  # isort:skip
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/Users/talley/miniconda3/envs/magicdev/lib/python3.8/site-packages/_pytest/assertion/rewrite.py", line 170, in exec_module
    exec(co, module.__dict__)
  File "/Users/talley/Dropbox (HMS)/Python/forks/napari/napari/viewer.py", line 3, in <module>
    from .components import ViewerModel
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/Users/talley/miniconda3/envs/magicdev/lib/python3.8/site-packages/_pytest/assertion/rewrite.py", line 170, in exec_module
    exec(co, module.__dict__)
  File "/Users/talley/Dropbox (HMS)/Python/forks/napari/napari/components/__init__.py", line 19, in <module>
    from .layerlist import LayerList
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/Users/talley/miniconda3/envs/magicdev/lib/python3.8/site-packages/_pytest/assertion/rewrite.py", line 170, in exec_module
    exec(co, module.__dict__)
  File "/Users/talley/Dropbox (HMS)/Python/forks/napari/napari/components/layerlist.py", line 8, in <module>
    from ..layers import Layer
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/Users/talley/miniconda3/envs/magicdev/lib/python3.8/site-packages/_pytest/assertion/rewrite.py", line 170, in exec_module
    exec(co, module.__dict__)
  File "/Users/talley/Dropbox (HMS)/Python/forks/napari/napari/layers/__init__.py", line 10, in <module>
    from .base import Layer
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/Users/talley/miniconda3/envs/magicdev/lib/python3.8/site-packages/_pytest/assertion/rewrite.py", line 170, in exec_module
    exec(co, module.__dict__)
  File "/Users/talley/Dropbox (HMS)/Python/forks/napari/napari/layers/base/__init__.py", line 1, in <module>
    from .base import Layer
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/Users/talley/miniconda3/envs/magicdev/lib/python3.8/site-packages/_pytest/assertion/rewrite.py", line 170, in exec_module
    exec(co, module.__dict__)
  File "/Users/talley/Dropbox (HMS)/Python/forks/napari/napari/layers/base/base.py", line 22, in <module>
    from ._base_constants import Blending
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/Users/talley/miniconda3/envs/magicdev/lib/python3.8/site-packages/_pytest/assertion/rewrite.py", line 170, in exec_module
    exec(co, module.__dict__)
  File "/Users/talley/Dropbox (HMS)/Python/forks/napari/napari/layers/base/_base_constants.py", line 5, in <module>
    from ...utils.translations import trans
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/Users/talley/miniconda3/envs/magicdev/lib/python3.8/site-packages/_pytest/assertion/rewrite.py", line 170, in exec_module
    exec(co, module.__dict__)
  File "/Users/talley/Dropbox (HMS)/Python/forks/napari/napari/utils/translations.py", line 476, in <module>
    _Translator._set_locale(_load_language())
  File "/Users/talley/Dropbox (HMS)/Python/forks/napari/napari/utils/translations.py", line 468, in _load_language
    data = safe_load(fh) or {}
  File "/Users/talley/miniconda3/envs/magicdev/lib/python3.8/site-packages/yaml/__init__.py", line 162, in safe_load
    return load(stream, SafeLoader)
  File "/Users/talley/miniconda3/envs/magicdev/lib/python3.8/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/Users/talley/miniconda3/envs/magicdev/lib/python3.8/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/Users/talley/miniconda3/envs/magicdev/lib/python3.8/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/Users/talley/miniconda3/envs/magicdev/lib/python3.8/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/Users/talley/miniconda3/envs/magicdev/lib/python3.8/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/Users/talley/miniconda3/envs/magicdev/lib/python3.8/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/Users/talley/miniconda3/envs/magicdev/lib/python3.8/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/Users/talley/miniconda3/envs/magicdev/lib/python3.8/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/Users/talley/miniconda3/envs/magicdev/lib/python3.8/site-packages/yaml/composer.py", line 82, in compose_node
    node = self.compose_sequence_node(anchor)
  File "/Users/talley/miniconda3/envs/magicdev/lib/python3.8/site-packages/yaml/composer.py", line 110, in compose_sequence_node
    while not self.check_event(SequenceEndEvent):
  File "/Users/talley/miniconda3/envs/magicdev/lib/python3.8/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/Users/talley/miniconda3/envs/magicdev/lib/python3.8/site-packages/yaml/parser.py", line 403, in parse_indentless_sequence_entry
    if self.check_token(BlockEntryToken):
  File "/Users/talley/miniconda3/envs/magicdev/lib/python3.8/site-packages/yaml/scanner.py", line 115, in check_token
    while self.need_more_tokens():
  File "/Users/talley/miniconda3/envs/magicdev/lib/python3.8/site-packages/yaml/scanner.py", line 152, in need_more_tokens
    self.stale_possible_simple_keys()
  File "/Users/talley/miniconda3/envs/magicdev/lib/python3.8/site-packages/yaml/scanner.py", line 291, in stale_possible_simple_keys
    raise ScannerError("while scanning a simple key", key.mark,
yaml.scanner.ScannerError: while scanning a simple key
  in "/Users/talley/Library/Application Support/Napari/settings.yaml", line 31, column 1
could not find expected ':'
  in "/Users/talley/Library/Application Support/Napari/settings.yaml", line 32, column 19
```
</details>

but the key part is right here:
```python
  File "/Users/talley/Dropbox (HMS)/Python/forks/napari/napari/utils/translations.py", line 476, in <module>
    _Translator._set_locale(_load_language())
  File "/Users/talley/Dropbox (HMS)/Python/forks/napari/napari/utils/translations.py", line 468, in _load_language
    data = safe_load(fh) or {}
...
yaml.scanner.ScannerError: while scanning a simple key
  in "/Users/talley/Library/Application Support/Napari/settings.yaml", line 31, column 1
could not find expected ':'
  in "/Users/talley/Library/Application Support/Napari/settings.yaml", line 32, column 19
```

we should add some tests to make sure that _every_ time we read from from settings, even if that settings file is complete nonsense, napari doesn't crash.

cc @goanpeca

**Comment by goanpeca** [comment]
Will fix!

Indeed not nice!

**Comment by tlambert03** [comment]
thanks!
