### ISSUE TITLE
Better error message for erroneous scale

### ISSUE THREAD

**Issue by tlambert03** [napari/napari#2569]
## 🐛 Bug

If the user enters a scale of `0` for any axis when creating a `Layer` or using (e.g.) `viewer.add_image()`, then the transformation (unsurprisingly) fails and an exception is raised.  However, that exception is pretty deep and hard to interpret:

<details>

```pytb
In [15]: v.add_image(np.random.rand(64,64), scale=(0,1))
---------------------------------------------------------------------------
LinAlgError                               Traceback (most recent call last)
<ipython-input-15-9c30dae6b2d8> in <module>
----> 1 v.add_image(np.random.rand(64,64), scale=(0,1))

~/Dropbox (HMS)/Python/forks/napari/napari/components/viewer_model.py in add_image(self, data, channel_axis, rgb, colormap, contrast_limits, gamma, interpolation, rendering, iso_threshold, attenuation, name, metadata, scale, translate, rotate, shear, affine, opacity, blending, visible, multiscale)
    649                         "did you mean to specify a 'channel_axis'? "
    650                     )
--> 651             layer = Image(data, **kwargs)
    652             self.layers.append(layer)
    653

~/Dropbox (HMS)/Python/forks/napari/napari/layers/image/image.py in __init__(self, data, rgb, colormap, contrast_limits, gamma, interpolation, rendering, iso_threshold, attenuation, name, metadata, scale, translate, rotate, shear, affine, opacity, blending, visible, multiscale)
    276
    277         # Trigger generation of view slice and thumbnail
--> 278         self._update_dims()
    279
    280     def _new_empty_slice(self):

~/Dropbox (HMS)/Python/forks/napari/napari/layers/base/base.py in _update_dims(self, event)
    553         self._ndim = ndim
    554
--> 555         self.refresh()
    556
    557     @property

~/Dropbox (HMS)/Python/forks/napari/napari/layers/base/base.py in refresh(self, event)
    951         """Refresh all layer data based on current view slice."""
    952         if self.visible:
--> 953             self.set_view_slice()
    954             self.events.set_data()
    955             self._update_thumbnail()

~/Dropbox (HMS)/Python/forks/napari/napari/layers/base/base.py in set_view_slice(self)
    815     def set_view_slice(self):
    816         with self.dask_optimized_slicing():
--> 817             self._set_view_slice()
    818
    819     @abstractmethod

~/Dropbox (HMS)/Python/forks/napari/napari/layers/image/image.py in _set_view_slice(self)
    505
    506         # Check if requested slice outside of data range
--> 507         indices = np.array(self._slice_indices)
    508         extent = self._extent_data
    509         if np.any(

~/Dropbox (HMS)/Python/forks/napari/napari/layers/base/base.py in _slice_indices(self)
    621     def _slice_indices(self):
    622         """(D, ) array: Slice indices in data coordinates."""
--> 623         inv_transform = self._transforms['data2world'].inverse
    624
    625         if self.ndim > self._ndisplay:

~/Dropbox (HMS)/Python/forks/napari/napari/utils/transforms/transforms.py in inverse(self)
    439     def inverse(self) -> 'Affine':
    440         """Return the inverse transform."""
--> 441         return Affine(affine_matrix=np.linalg.inv(self.affine_matrix))
    442
    443     def compose(self, transform: 'Affine') -> 'Affine':

<__array_function__ internals> in inv(*args, **kwargs)

~/miniconda3/envs/napdev/lib/python3.9/site-packages/numpy/linalg/linalg.py in inv(a)
    543     signature = 'D->D' if isComplexType(t) else 'd->d'
    544     extobj = get_linalg_error_extobj(_raise_linalgerror_singular)
--> 545     ainv = _umath_linalg.inv(a, signature=signature, extobj=extobj)
    546     return wrap(ainv.astype(result_t, copy=False))
    547

~/miniconda3/envs/napdev/lib/python3.9/site-packages/numpy/linalg/linalg.py in _raise_linalgerror_singular(err, flag)
     86
     87 def _raise_linalgerror_singular(err, flag):
---> 88     raise LinAlgError("Singular matrix")
     89
     90 def _raise_linalgerror_nonposdef(err, flag):

LinAlgError: Singular matrix
```

</details>

Would be nice to catch this earlier on and raise a helpful error.  

(Note: I came about this by trying to use a plugin that returned a scale of `0`... so while it might be obvious enough for the user who directly entered the scale, it's not always the user that provides it)

**Comment by sofroniewn** [comment]
Agreed, good idea!!

**Comment by sebgoti** [comment]
Hello again, may I attempt to solve this issue?

**Comment by tlambert03** [comment]
Yes please! Don't hesitate to reach out if we can be of help :)

**Comment by tlambert03** [comment]
Hi @sebgoti ... just checking in.  still wanting to take this on?  anything I can do to help?

**Comment by sebgoti** [comment]
Hi @tlambert03 , yes this week will get back to it, had some complications with the installation from source (using MacOS BigSur) but things seem to be working now. Will come back to you over the next days if I have any questions, sorry about the delay!

**Comment by sofroniewn** [comment]
No pressure, but just wanted to follow up here to see if you're still interested in taking this on @sebgoti, if not someone else can pick this up. Thanks for your interest though!!

**Comment by sebgoti** [comment]
Hi @sofroniewn I am still interested in taking this up, was somehow busy the last weeks but would like to give it a try if that's ok, thanks in advance.

**Comment by kephale** [comment]
Hi all,

I started on this one and have run into another issue.

This is my branch: https://github.com/kephale/napari/tree/singular_layer_exception

This throws a more clear exception when the error happens, but when I was writing a test for this I found that there is some funky behaviors when a layer that is added throws an exception:

<details>
  <summary>Detailed exception</summary>

```
>>> import numpy as np
... import napari
... 
... viewer = napari.Viewer()
... 
... try:
...     viewer.add_image(np.random.rand(64, 64), scale=(0, 1))
... except Exception as e:
...     print(e)
... 
... print('Number of layers: ', len(viewer.layers))
... 
... viewer.layers.remove(viewer.layers[0])
... 
... print('Number of layers: ', len(viewer.layers))

Layer "Image" has a singular affine matrix. This can be caused by the Layer's scale having zero values. The layer's scale is currently "[0. 1.]"
Number of layers:  1
Traceback (most recent call last):
  File "<string>", line 17, in __PYTHON_EL_eval
  File "/Users/kharrington/git/kephale/napari/test_issue_2569.py", line 13, in <module>
    viewer.layers.remove(viewer.layers[0])
  File "/Users/kharrington/miniconda3/envs/napari-dev/lib/python3.9/_collections_abc.py", line 1108, in remove
    del self[self.index(value)]
  File "/Users/kharrington/git/kephale/napari/napari/utils/events/containers/_evented_list.py", line 179, in __delitem__
    parent.events.removed(index=index, value=item)
  File "/Users/kharrington/git/kephale/napari/napari/utils/events/event.py", line 757, in __call__
    self._invoke_callback(cb, event if pass_event else None)
  File "/Users/kharrington/git/kephale/napari/napari/utils/events/event.py", line 794, in _invoke_callback
    _handle_exception(
  File "/Users/kharrington/git/kephale/napari/napari/utils/events/event.py", line 781, in _invoke_callback
    cb(event)
  File "/Users/kharrington/git/kephale/napari/napari/_qt/qt_viewer.py", line 527, in _remove_layer
    vispy_layer = self.layer_to_visual[layer]
KeyError: <Image layer 'Image' at 0x166ff05e0>
>>> print('Number of layers: ', len(viewer.layers))

Number of layers:  0
```
</details>

The issue seems to be that even though an exception is thrown while the `Layer` is added, the exception raising Layer still ends up in `Viewer.layers`. However, when you try to remove the layer it disappears, triggering another exception. I haven't tracked down the source of this behavior yet.

**Comment by tlambert03** [comment]
hey @kephale!  nice to see you here!  :) glad to hear you'll be working on napari more these days. 

> even though an exception is thrown while the Layer is added,

by putting the exception in `_vispy/layers/base`, the exception is only being thrown when the layer is _visualzed_ ... this check should probably be in the base layer `__init__`  (`layers.base.base.Layer.__init__`).  It might need to take a slightly different form than `if np.linalg.det(affine_matrix) == 0:`  (i.e. maybe just directly check if any of the scale values are zero?), but if the exception is raised there, it then it will prevent new layer creation and it won't be added to the layer list.

That should also fix your second `KeyError`, which relates to the fact that no vispy layer was created (since the exception was raised in the vispy layer init).  that is, if a "real" layer isn't created, then there will be no key error when removing that layer

**Comment by kephale** [comment]
@tlambert03 Awesome. Thank you for the tips! I've made the changes and submitted a corresponding PR https://github.com/napari/napari/pull/4906
