### ISSUE TITLE
Import error on new environment

### ISSUE THREAD

**Issue by FerdinandGreiss** [napari/napari#2667]
## 🐛 Bug

Hi, really great project! I wanted to give it a try today and installed the latest napari with a new conda environment (I tried with Python 3.7, 3.8, 3.9). After `import napari`, it always raised the following error:

```
Python 3.7.10 (default, Feb 26 2021, 10:16:00) 
[Clang 10.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/feschiessl/anaconda3/envs/napari-env/lib/python3.7/site-packages/napari/__init__.py", line 7, in <module>
    from .viewer import Viewer  # isort:skip
  File "/Users/feschiessl/anaconda3/envs/napari-env/lib/python3.7/site-packages/napari/viewer.py", line 3, in <module>
    from .components import ViewerModel
  File "/Users/feschiessl/anaconda3/envs/napari-env/lib/python3.7/site-packages/napari/components/__init__.py", line 17, in <module>
    from .camera import Camera
  File "/Users/feschiessl/anaconda3/envs/napari-env/lib/python3.7/site-packages/napari/components/camera.py", line 5, in <module>
    from ..utils.events import EventedModel
  File "/Users/feschiessl/anaconda3/envs/napari-env/lib/python3.7/site-packages/napari/utils/__init__.py", line 1, in <module>
    from .colormaps import Colormap
  File "/Users/feschiessl/anaconda3/envs/napari-env/lib/python3.7/site-packages/napari/utils/colormaps/__init__.py", line 2, in <module>
    from .colormap import Colormap
  File "/Users/feschiessl/anaconda3/envs/napari-env/lib/python3.7/site-packages/napari/utils/colormaps/colormap.py", line 6, in <module>
    from ..events import EventedModel
  File "/Users/feschiessl/anaconda3/envs/napari-env/lib/python3.7/site-packages/napari/utils/events/__init__.py", line 1, in <module>
    from .event import EmitterGroup, Event, EventEmitter  # isort:skip
  File "/Users/feschiessl/anaconda3/envs/napari-env/lib/python3.7/site-packages/napari/utils/events/event.py", line 69, in <module>
    from vispy.util.logs import _handle_exception, logger
  File "/Users/feschiessl/anaconda3/envs/napari-env/lib/python3.7/site-packages/vispy/__init__.py", line 30, in <module>
    from .util import config, set_log_level, keys, sys_info  # noqa
  File "/Users/feschiessl/anaconda3/envs/napari-env/lib/python3.7/site-packages/vispy/util/__init__.py", line 14, in <module>
    from . import fonts       # noqa
  File "/Users/feschiessl/anaconda3/envs/napari-env/lib/python3.7/site-packages/vispy/util/fonts/__init__.py", line 13, in <module>
    from ._triage import _load_glyph, list_fonts  # noqa, analysis:ignore
  File "/Users/feschiessl/anaconda3/envs/napari-env/lib/python3.7/site-packages/vispy/util/fonts/_triage.py", line 14, in <module>
    from ._quartz import _load_glyph, _list_fonts
  File "/Users/feschiessl/anaconda3/envs/napari-env/lib/python3.7/site-packages/vispy/util/fonts/_quartz.py", line 12, in <module>
    from ...ext.cocoapy import cf, ct, quartz, CFRange, CFSTR, CGGlyph, UniChar, \
  File "/Users/feschiessl/anaconda3/envs/napari-env/lib/python3.7/site-packages/vispy/ext/cocoapy.py", line 930, in <module>
    cf.CFStringCreateWithCString.restype = c_void_p
  File "/Users/feschiessl/anaconda3/envs/napari-env/lib/python3.7/ctypes/__init__.py", line 377, in __getattr__
    func = self.__getitem__(name)
  File "/Users/feschiessl/anaconda3/envs/napari-env/lib/python3.7/ctypes/__init__.py", line 382, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: dlsym(RTLD_DEFAULT, CFStringCreateWithCString): symbol not found
```

## Environment

Further information `conda info`:

```
     active environment : base
    active env location : /Users/feschiessl/anaconda3
            shell level : 1
       user config file : /Users/feschiessl/.condarc
 populated config files : /Users/feschiessl/.condarc
          conda version : 4.10.1
    conda-build version : 3.21.4
         python version : 3.7.3.final.0
       virtual packages : __osx=10.16=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /Users/feschiessl/anaconda3  (writable)
      conda av data dir : /Users/feschiessl/anaconda3/etc/conda
  conda av metadata url : https://repo.anaconda.com/pkgs/main
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/feschiessl/anaconda3/pkgs
                          /Users/feschiessl/.conda/pkgs
       envs directories : /Users/feschiessl/anaconda3/envs
                          /Users/feschiessl/.conda/envs
               platform : osx-64
             user-agent : conda/4.10.1 requests/2.25.1 CPython/3.7.3 Darwin/20.3.0 OSX/10.16
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```

 - Any other relevant information:
 
I am on a MacOS Big Sur (11.2.2)

## Additional context

Hope you can help me. Thanks!

**Comment by tlambert03** [comment]
Hmm. One thing to note is that you will definitely need python 3.9 on Big Sur...

Can you provide your complete command line steps, including environment creation and napari installation?  (Using python 3.9)... and paste the output of "napari --info" as well

**Comment by FerdinandGreiss** [comment]
Sure! Here is the full input and output...
***

> conda create -y -n napari-env python=3.9

```
Collecting package metadata (current_repodata.json): done
Solving environment: done

  environment location: /Users/feschiessl/anaconda3/envs/napari-env

  added / updated specs:
    - python=3.9


The following NEW packages will be INSTALLED:

  ca-certificates    pkgs/main/osx-64::ca-certificates-2021.4.13-hecd8cb5_1
  certifi            pkgs/main/osx-64::certifi-2020.12.5-py39hecd8cb5_0
  libcxx             pkgs/main/osx-64::libcxx-10.0.0-1
  libffi             pkgs/main/osx-64::libffi-3.3-hb1e8313_2
  ncurses            pkgs/main/osx-64::ncurses-6.2-h0a44026_1
  openssl            pkgs/main/osx-64::openssl-1.1.1k-h9ed2024_0
  pip                pkgs/main/osx-64::pip-21.0.1-py39hecd8cb5_0
  python             pkgs/main/osx-64::python-3.9.4-h88f2d9e_0
  readline           pkgs/main/osx-64::readline-8.1-h9ed2024_0
  setuptools         pkgs/main/osx-64::setuptools-52.0.0-py39hecd8cb5_0
  sqlite             pkgs/main/osx-64::sqlite-3.35.4-hce871da_0
  tk                 pkgs/main/osx-64::tk-8.6.10-hb0a8c7a_0
  tzdata             pkgs/main/noarch::tzdata-2020f-h52ac0ba_0
  wheel              pkgs/main/noarch::wheel-0.36.2-pyhd3eb1b0_0
  xz                 pkgs/main/osx-64::xz-5.2.5-h1de35cc_0
  zlib               pkgs/main/osx-64::zlib-1.2.11-h1de35cc_3


Preparing transaction: done
Verifying transaction: done
Executing transaction: done
```

> (base) Ferdinands-MacBook-Pro:~ feschiessl$ conda activate napari-env

> (napari-env) Ferdinands-MacBook-Pro:~ feschiessl$ pip install 'napari[all]'

```
Collecting napari[all]
  Using cached napari-0.4.7-py3-none-any.whl (1.4 MB)
Collecting Pillow!=7.1.0,!=7.1.1
  Using cached Pillow-8.2.0-cp39-cp39-macosx_10_10_x86_64.whl (2.8 MB)
Collecting wrapt>=1.11.1
  Using cached wrapt-1.12.1-py3-none-any.whl
Collecting jsonschema>=3.2.0
  Using cached jsonschema-3.2.0-py2.py3-none-any.whl (56 kB)
Collecting PyOpenGL>=3.1.0
  Using cached PyOpenGL-3.1.5-py3-none-any.whl (2.4 MB)
Collecting dask[array]!=2.28.0,>=2.1.0
  Using cached dask-2021.4.1-py3-none-any.whl (952 kB)
Collecting pydantic>=1.8.1
  Using cached pydantic-1.8.1-cp39-cp39-macosx_10_9_x86_64.whl (2.7 MB)
Collecting appdirs>=1.4.4
  Using cached appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Collecting cachey>=0.2.1
  Using cached cachey-0.2.1-py3-none-any.whl (6.4 kB)
Collecting numpy>=1.16.5
  Using cached numpy-1.20.2-cp39-cp39-macosx_10_9_x86_64.whl (16.1 MB)
Collecting PyYAML>=5.1
  Using cached PyYAML-5.4.1-cp39-cp39-macosx_10_9_x86_64.whl (259 kB)
Collecting vispy>=0.6.4
  Using cached vispy-0.6.6-cp39-cp39-macosx_10_9_x86_64.whl (2.3 MB)
Collecting toolz>=0.10.0
  Using cached toolz-0.11.1-py3-none-any.whl (55 kB)
Collecting scipy>=1.2.0
  Using cached scipy-1.6.3-cp39-cp39-macosx_10_9_x86_64.whl (30.9 MB)
Collecting magicgui>=0.2.5
  Using cached magicgui-0.2.9-py2.py3-none-any.whl (123 kB)
Collecting tifffile>=2020.2.16
  Using cached tifffile-2021.4.8-py3-none-any.whl (165 kB)
Collecting imageio>=2.5.0
  Using cached imageio-2.9.0-py3-none-any.whl (3.3 MB)
Collecting napari-console>=0.0.2
  Using cached napari_console-0.0.3-py3-none-any.whl (7.7 kB)
Collecting numpydoc>=0.9.2
  Using cached numpydoc-1.1.0-py3-none-any.whl (47 kB)
Collecting napari-svg>=0.1.4
  Using cached napari_svg-0.1.5-py3-none-any.whl (12 kB)
Collecting psutil>=5.0
  Using cached psutil-5.8.0-cp39-cp39-macosx_10_9_x86_64.whl (236 kB)
Collecting qtpy>=1.7.0
  Using cached QtPy-1.9.0-py2.py3-none-any.whl (54 kB)
Collecting typing-extensions
  Using cached typing_extensions-3.10.0.0-py3-none-any.whl (26 kB)
Collecting napari-plugin-engine>=0.1.9
  Using cached napari_plugin_engine-0.1.9-py3-none-any.whl (32 kB)
Collecting PyQt5!=5.15.0,>=5.12.3
  Using cached PyQt5-5.15.4-cp36.cp37.cp38.cp39-abi3-macosx_10_13_intel.whl (7.0 MB)
Collecting heapdict
  Using cached HeapDict-1.0.1-py3-none-any.whl (3.9 kB)
Collecting partd>=0.3.10
  Using cached partd-1.2.0-py3-none-any.whl (19 kB)
Collecting cloudpickle>=1.1.1
  Using cached cloudpickle-1.6.0-py3-none-any.whl (23 kB)
Collecting fsspec>=0.6.0
  Using cached fsspec-2021.4.0-py3-none-any.whl (108 kB)
Requirement already satisfied: setuptools in ./anaconda3/envs/napari-env/lib/python3.9/site-packages (from jsonschema>=3.2.0->napari[all]) (52.0.0.post20210125)
Collecting six>=1.11.0
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting pyrsistent>=0.14.0
  Using cached pyrsistent-0.17.3-cp39-cp39-macosx_10_9_x86_64.whl
Collecting attrs>=17.4.0
  Using cached attrs-21.1.0-py2.py3-none-any.whl (55 kB)
Collecting docstring-parser
  Using cached docstring_parser-0.7.3-py3-none-any.whl
Collecting ipykernel>=5.2.0
  Using cached ipykernel-5.5.4-py3-none-any.whl (120 kB)
Collecting qtconsole!=4.7.6,>=4.5.1
  Using cached qtconsole-5.1.0-py3-none-any.whl (119 kB)
Collecting IPython>=7.7.0
  Using cached ipython-7.23.1-py3-none-any.whl (785 kB)
Collecting appnope
  Using cached appnope-0.1.2-py2.py3-none-any.whl (4.3 kB)
Collecting jupyter-client
  Using cached jupyter_client-6.1.12-py3-none-any.whl (112 kB)
Collecting tornado>=4.2
  Using cached tornado-6.1-cp39-cp39-macosx_10_9_x86_64.whl (416 kB)
Collecting traitlets>=4.1.0
  Using cached traitlets-5.0.5-py3-none-any.whl (100 kB)
Collecting prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0
  Using cached prompt_toolkit-3.0.18-py3-none-any.whl (367 kB)
Collecting jedi>=0.16
  Using cached jedi-0.18.0-py2.py3-none-any.whl (1.4 MB)
Collecting pexpect>4.3
  Using cached pexpect-4.8.0-py2.py3-none-any.whl (59 kB)
Collecting matplotlib-inline
  Using cached matplotlib_inline-0.1.2-py3-none-any.whl (8.2 kB)
Collecting decorator
  Using cached decorator-5.0.7-py3-none-any.whl (8.8 kB)
Collecting backcall
  Using cached backcall-0.2.0-py2.py3-none-any.whl (11 kB)
Collecting pygments
  Using cached Pygments-2.9.0-py3-none-any.whl (1.0 MB)
Collecting pickleshare
  Using cached pickleshare-0.7.5-py2.py3-none-any.whl (6.9 kB)
Collecting parso<0.9.0,>=0.8.0
  Using cached parso-0.8.2-py2.py3-none-any.whl (94 kB)
Collecting Jinja2>=2.3
  Using cached Jinja2-2.11.3-py2.py3-none-any.whl (125 kB)
Collecting sphinx>=1.6.5
  Using cached Sphinx-3.5.4-py3-none-any.whl (2.8 MB)
Collecting MarkupSafe>=0.23
  Using cached MarkupSafe-1.1.1-cp39-cp39-macosx_10_9_x86_64.whl (16 kB)
Collecting locket
  Using cached locket-0.2.1-py2.py3-none-any.whl (4.1 kB)
Collecting ptyprocess>=0.5
  Using cached ptyprocess-0.7.0-py2.py3-none-any.whl (13 kB)
Collecting wcwidth
  Using cached wcwidth-0.2.5-py2.py3-none-any.whl (30 kB)
Collecting PyQt5-sip<13,>=12.8
  Using cached PyQt5_sip-12.8.1-cp39-cp39-macosx_10_9_x86_64.whl (63 kB)
Collecting PyQt5-Qt5>=5.15
  Using cached PyQt5_Qt5-5.15.2-py3-none-macosx_10_13_intel.whl (40.5 MB)
Collecting pyzmq>=17.1
  Using cached pyzmq-22.0.3-cp39-cp39-macosx_10_15_universal2.whl (1.9 MB)
Collecting ipython-genutils
  Using cached ipython_genutils-0.2.0-py2.py3-none-any.whl (26 kB)
Collecting jupyter-core
  Using cached jupyter_core-4.7.1-py3-none-any.whl (82 kB)
Collecting python-dateutil>=2.1
  Using cached python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
Collecting sphinxcontrib-devhelp
  Using cached sphinxcontrib_devhelp-1.0.2-py2.py3-none-any.whl (84 kB)
Collecting sphinxcontrib-serializinghtml
  Using cached sphinxcontrib_serializinghtml-1.1.4-py2.py3-none-any.whl (89 kB)
Collecting snowballstemmer>=1.1
  Using cached snowballstemmer-2.1.0-py2.py3-none-any.whl (93 kB)
Collecting imagesize
  Using cached imagesize-1.2.0-py2.py3-none-any.whl (4.8 kB)
Collecting sphinxcontrib-jsmath
  Using cached sphinxcontrib_jsmath-1.0.1-py2.py3-none-any.whl (5.1 kB)
Collecting sphinxcontrib-htmlhelp
  Using cached sphinxcontrib_htmlhelp-1.0.3-py2.py3-none-any.whl (96 kB)
Collecting docutils<0.17,>=0.12
  Using cached docutils-0.16-py2.py3-none-any.whl (548 kB)
Collecting babel>=1.3
  Using cached Babel-2.9.1-py2.py3-none-any.whl (8.8 MB)
Collecting packaging
  Using cached packaging-20.9-py2.py3-none-any.whl (40 kB)
Collecting sphinxcontrib-qthelp
  Using cached sphinxcontrib_qthelp-1.0.3-py2.py3-none-any.whl (90 kB)
Collecting sphinxcontrib-applehelp
  Using cached sphinxcontrib_applehelp-1.0.2-py2.py3-none-any.whl (121 kB)
Collecting alabaster<0.8,>=0.7
  Using cached alabaster-0.7.12-py2.py3-none-any.whl (14 kB)
Collecting requests>=2.5.0
  Using cached requests-2.25.1-py2.py3-none-any.whl (61 kB)
Collecting pytz>=2015.7
  Using cached pytz-2021.1-py2.py3-none-any.whl (510 kB)
Requirement already satisfied: certifi>=2017.4.17 in ./anaconda3/envs/napari-env/lib/python3.9/site-packages (from requests>=2.5.0->sphinx>=1.6.5->numpydoc>=0.9.2->napari[all]) (2020.12.5)
Collecting chardet<5,>=3.0.2
  Using cached chardet-4.0.0-py2.py3-none-any.whl (178 kB)
Collecting idna<3,>=2.5
  Using cached idna-2.10-py2.py3-none-any.whl (58 kB)
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.4-py2.py3-none-any.whl (153 kB)
Collecting freetype-py
  Using cached freetype_py-2.2.0-py3-none-macosx_10_9_x86_64.whl (852 kB)
Collecting pyparsing>=2.0.2
  Using cached pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
Installing collected packages: ipython-genutils, wcwidth, traitlets, six, ptyprocess, parso, tornado, pyzmq, python-dateutil, pygments, prompt-toolkit, pickleshare, pexpect, matplotlib-inline, jupyter-core, jedi, decorator, backcall, appnope, urllib3, toolz, pytz, pyparsing, MarkupSafe, locket, jupyter-client, IPython, idna, chardet, sphinxcontrib-serializinghtml, sphinxcontrib-qthelp, sphinxcontrib-jsmath, sphinxcontrib-htmlhelp, sphinxcontrib-devhelp, sphinxcontrib-applehelp, snowballstemmer, requests, qtpy, PyYAML, Pillow, partd, packaging, numpy, Jinja2, ipykernel, imagesize, fsspec, freetype-py, docutils, cloudpickle, babel, alabaster, vispy, typing-extensions, sphinx, qtconsole, pyrsistent, napari-plugin-engine, imageio, heapdict, docstring-parser, dask, attrs, wrapt, tifffile, scipy, PyQt5-sip, PyQt5-Qt5, PyOpenGL, pydantic, psutil, numpydoc, napari-svg, napari-console, magicgui, jsonschema, cachey, appdirs, PyQt5, napari
Successfully installed IPython-7.23.1 Jinja2-2.11.3 MarkupSafe-1.1.1 Pillow-8.2.0 PyOpenGL-3.1.5 PyQt5-5.15.4 PyQt5-Qt5-5.15.2 PyQt5-sip-12.8.1 PyYAML-5.4.1 alabaster-0.7.12 appdirs-1.4.4 appnope-0.1.2 attrs-21.1.0 babel-2.9.1 backcall-0.2.0 cachey-0.2.1 chardet-4.0.0 cloudpickle-1.6.0 dask-2021.4.1 decorator-5.0.7 docstring-parser-0.7.3 docutils-0.16 freetype-py-2.2.0 fsspec-2021.4.0 heapdict-1.0.1 idna-2.10 imageio-2.9.0 imagesize-1.2.0 ipykernel-5.5.4 ipython-genutils-0.2.0 jedi-0.18.0 jsonschema-3.2.0 jupyter-client-6.1.12 jupyter-core-4.7.1 locket-0.2.1 magicgui-0.2.9 matplotlib-inline-0.1.2 napari-0.4.7 napari-console-0.0.3 napari-plugin-engine-0.1.9 napari-svg-0.1.5 numpy-1.20.2 numpydoc-1.1.0 packaging-20.9 parso-0.8.2 partd-1.2.0 pexpect-4.8.0 pickleshare-0.7.5 prompt-toolkit-3.0.18 psutil-5.8.0 ptyprocess-0.7.0 pydantic-1.8.1 pygments-2.9.0 pyparsing-2.4.7 pyrsistent-0.17.3 python-dateutil-2.8.1 pytz-2021.1 pyzmq-22.0.3 qtconsole-5.1.0 qtpy-1.9.0 requests-2.25.1 scipy-1.6.3 six-1.16.0 snowballstemmer-2.1.0 sphinx-3.5.4 sphinxcontrib-applehelp-1.0.2 sphinxcontrib-devhelp-1.0.2 sphinxcontrib-htmlhelp-1.0.3 sphinxcontrib-jsmath-1.0.1 sphinxcontrib-qthelp-1.0.3 sphinxcontrib-serializinghtml-1.1.4 tifffile-2021.4.8 toolz-0.11.1 tornado-6.1 traitlets-5.0.5 typing-extensions-3.10.0.0 urllib3-1.26.4 vispy-0.6.6 wcwidth-0.2.5 wrapt-1.12.1
```

> (napari-env) Ferdinands-MacBook-Pro:~ feschiessl$ python

Then running`import napari` with

Python 3.9.4 (default, Apr  9 2021, 09:32:38) 
[Clang 10.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/feschiessl/anaconda3/envs/napari-env/lib/python3.9/site-packages/napari/__init__.py", line 7, in <module>
    from .viewer import Viewer  # isort:skip
  File "/Users/feschiessl/anaconda3/envs/napari-env/lib/python3.9/site-packages/napari/viewer.py", line 3, in <module>
    from .components import ViewerModel
  File "/Users/feschiessl/anaconda3/envs/napari-env/lib/python3.9/site-packages/napari/components/__init__.py", line 17, in <module>
    from .camera import Camera
  File "/Users/feschiessl/anaconda3/envs/napari-env/lib/python3.9/site-packages/napari/components/camera.py", line 5, in <module>
    from ..utils.events import EventedModel
  File "/Users/feschiessl/anaconda3/envs/napari-env/lib/python3.9/site-packages/napari/utils/__init__.py", line 1, in <module>
    from .colormaps import Colormap
  File "/Users/feschiessl/anaconda3/envs/napari-env/lib/python3.9/site-packages/napari/utils/colormaps/__init__.py", line 2, in <module>
    from .colormap import Colormap
  File "/Users/feschiessl/anaconda3/envs/napari-env/lib/python3.9/site-packages/napari/utils/colormaps/colormap.py", line 6, in <module>
    from ..events import EventedModel
  File "/Users/feschiessl/anaconda3/envs/napari-env/lib/python3.9/site-packages/napari/utils/events/__init__.py", line 1, in <module>
    from .event import EmitterGroup, Event, EventEmitter  # isort:skip
  File "/Users/feschiessl/anaconda3/envs/napari-env/lib/python3.9/site-packages/napari/utils/events/event.py", line 69, in <module>
    from vispy.util.logs import _handle_exception, logger
  File "/Users/feschiessl/anaconda3/envs/napari-env/lib/python3.9/site-packages/vispy/__init__.py", line 30, in <module>
    from .util import config, set_log_level, keys, sys_info  # noqa
  File "/Users/feschiessl/anaconda3/envs/napari-env/lib/python3.9/site-packages/vispy/util/__init__.py", line 14, in <module>
    from . import fonts       # noqa
  File "/Users/feschiessl/anaconda3/envs/napari-env/lib/python3.9/site-packages/vispy/util/fonts/__init__.py", line 13, in <module>
    from ._triage import _load_glyph, list_fonts  # noqa, analysis:ignore
  File "/Users/feschiessl/anaconda3/envs/napari-env/lib/python3.9/site-packages/vispy/util/fonts/_triage.py", line 14, in <module>
    from ._quartz import _load_glyph, _list_fonts
  File "/Users/feschiessl/anaconda3/envs/napari-env/lib/python3.9/site-packages/vispy/util/fonts/_quartz.py", line 12, in <module>
    from ...ext.cocoapy import cf, ct, quartz, CFRange, CFSTR, CGGlyph, UniChar, \
  File "/Users/feschiessl/anaconda3/envs/napari-env/lib/python3.9/site-packages/vispy/ext/cocoapy.py", line 1126, in <module>
    NSEventTrackingRunLoopMode = c_void_p.in_dll(
ValueError: dlsym(RTLD_DEFAULT, NSEventTrackingRunLoopMode): symbol not found

```
*** 
`napari --info` gives:

Traceback (most recent call last):
  File "/Users/feschiessl/anaconda3/envs/napari-env/bin/napari", line 5, in <module>
    from napari.__main__ import main
  File "/Users/feschiessl/anaconda3/envs/napari-env/lib/python3.9/site-packages/napari/__init__.py", line 7, in <module>
    from .viewer import Viewer  # isort:skip
  File "/Users/feschiessl/anaconda3/envs/napari-env/lib/python3.9/site-packages/napari/viewer.py", line 3, in <module>
    from .components import ViewerModel
  File "/Users/feschiessl/anaconda3/envs/napari-env/lib/python3.9/site-packages/napari/components/__init__.py", line 17, in <module>
    from .camera import Camera
  File "/Users/feschiessl/anaconda3/envs/napari-env/lib/python3.9/site-packages/napari/components/camera.py", line 5, in <module>
    from ..utils.events import EventedModel
  File "/Users/feschiessl/anaconda3/envs/napari-env/lib/python3.9/site-packages/napari/utils/__init__.py", line 1, in <module>
    from .colormaps import Colormap
  File "/Users/feschiessl/anaconda3/envs/napari-env/lib/python3.9/site-packages/napari/utils/colormaps/__init__.py", line 2, in <module>
    from .colormap import Colormap
  File "/Users/feschiessl/anaconda3/envs/napari-env/lib/python3.9/site-packages/napari/utils/colormaps/colormap.py", line 6, in <module>
    from ..events import EventedModel
  File "/Users/feschiessl/anaconda3/envs/napari-env/lib/python3.9/site-packages/napari/utils/events/__init__.py", line 1, in <module>
    from .event import EmitterGroup, Event, EventEmitter  # isort:skip
  File "/Users/feschiessl/anaconda3/envs/napari-env/lib/python3.9/site-packages/napari/utils/events/event.py", line 69, in <module>
    from vispy.util.logs import _handle_exception, logger
  File "/Users/feschiessl/anaconda3/envs/napari-env/lib/python3.9/site-packages/vispy/__init__.py", line 30, in <module>
    from .util import config, set_log_level, keys, sys_info  # noqa
  File "/Users/feschiessl/anaconda3/envs/napari-env/lib/python3.9/site-packages/vispy/util/__init__.py", line 14, in <module>
    from . import fonts       # noqa
  File "/Users/feschiessl/anaconda3/envs/napari-env/lib/python3.9/site-packages/vispy/util/fonts/__init__.py", line 13, in <module>
    from ._triage import _load_glyph, list_fonts  # noqa, analysis:ignore
  File "/Users/feschiessl/anaconda3/envs/napari-env/lib/python3.9/site-packages/vispy/util/fonts/_triage.py", line 14, in <module>
    from ._quartz import _load_glyph, _list_fonts
  File "/Users/feschiessl/anaconda3/envs/napari-env/lib/python3.9/site-packages/vispy/util/fonts/_quartz.py", line 12, in <module>
    from ...ext.cocoapy import cf, ct, quartz, CFRange, CFSTR, CGGlyph, UniChar, \
  File "/Users/feschiessl/anaconda3/envs/napari-env/lib/python3.9/site-packages/vispy/ext/cocoapy.py", line 1126, in <module>
    NSEventTrackingRunLoopMode = c_void_p.in_dll(
ValueError: dlsym(RTLD_DEFAULT, NSEventTrackingRunLoopMode): symbol not found

**Comment by tlambert03** [comment]
ok, I think we've had better luck with the python from conda-forge in big sur... and yours is coming from `pkgs/main` can you try this?

```
conda create -y -n napari-env -c conda-forge python=3.9
```

**Comment by FerdinandGreiss** [comment]
That worked. Absolutely fantastic support! Thanks.

**Comment by tlambert03** [comment]
awesome :)  I can't say I fully understand what the conda-forge distribution is doing that the one from the main channel isn't... but we should make that clearer in our install guide.  Glad it's working for you!

**Comment by FerdinandGreiss** [comment]
The only helpful discussion (before your insights) that I found on the internet was around vispy issues with macOS Big Sur: https://github.com/vispy/vispy/issues/1885
