### ISSUE TITLE
Deleting a layer during the inserted layer event

### ISSUE THREAD

**Issue by jmcleanSW** [napari/napari#2815]
## 🐛 Bug

An error is thrown when you delete a layer that was created through a drop event in a function connected to viewer.layers.events.inserted

## To Reproduce

1. Run the provided sample code to create a viewer instance.
2. Add some points to the point layer and save the layer as a .csv.
3. Drop the .csv back into napari.

CODE SAMPLE
```python
import napari

viewer = napari.Viewer()

point_layer = viewer.add_points(name='A')

def transfer_and_delete(event):
    new_index = event.index
    new_layer = event.value

    point_layer.data = new_layer.data.copy()

    viewer.layers.remove(new_layer.name)

viewer.layers.events.inserted.connect(transfer_and_delete)

napari.run()
```
ERROR MESSAGE
```pytb
~\Anaconda3\envs\napariUI\lib\site-packages\napari\_qt\qt_viewer.py in _remove_layer(self=, event=)
    444         """
    445         layer = event.value
--> 446         vispy_layer = self.layer_to_visual[layer]
        vispy_layer = undefined
        self.layer_to_visual = {: }
        layer = 
    447         vispy_layer.close()
    448         del vispy_layer

KeyError: <Points layer 'test_layer' at 0x21117138c1fd90>
```
## Expected behavior

The point of this function is to catch reloaded layer data, transfer the data to an existing layer, and then delete the layer created for the dropped in data.

## Environment

napari: 0.4.8
Platform: Windows-10-10.0.19041-SP0
Python: 3.9.5 (default, May 18 2021, 14:42:02) [MSC v.1916 64 bit (AMD64)]
Qt: 5.15.2
PyQt5: 5.15.4
NumPy: 1.20.2
SciPy: 1.6.2
Dask: 2021.05.0
VisPy: 0.6.6

OpenGL:
- GL version: 4.6.0 NVIDIA 452.66
- MAX_TEXTURE_SIZE: 32768

Screens:
- screen 1: resolution 1920x1080, scale 1.0
- screen 2: resolution 1920x1080, scale 1.0

Plugins:
- console: 0.0.3
- scikit-image: 0.4.8
- svg: 0.1.5

## Additional context

To clarify, this task is accomplished with the provided code, but the error is thrown immediately afterwards which interrupts the process when multiple .csv files are dropped in together.

**Comment by tlambert03** [comment]
thanks for the code!  [commented](https://forum.image.sc/t/how-to-trigger-on-a-drop-data-event-in-napari/53308/6) back in the ongoing image.sc thread.  This is "bug like" ... but it's also a slightly unusual use case that I need a little more understanding of before suggesting a potential resolution

**Comment by psobolewskiPhD** [comment]
I'm going to close this as `won't fix`: immediately removing a layer before it’s even completed adding is an antipattern we should not enable?
FYI With npe2, it's possible for a reader to not return a layer using `return [(None,)]` and then you can handle the data as you wish.

**Comment by psobolewskiPhD** [comment]
On 0.5.4 this gives a different traceback:
```
Traceback (most recent call last):
  File "/Users/piotrsobolewski/Dev/napari/napari/components/viewer_model.py", line 1332, in _open_or_raise_error
    added = self._add_layers_with_plugins(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/piotrsobolewski/Dev/napari/napari/components/viewer_model.py", line 1450, in _add_layers_with_plugins
    added.extend(self._add_layer_from_data(*_data))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/piotrsobolewski/Dev/napari/napari/components/viewer_model.py", line 1523, in _add_layer_from_data
    layer = add_method(data, **(meta or {}))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/piotrsobolewski/Dev/napari/napari/utils/migrations.py", line 101, in _update_from_dict
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/piotrsobolewski/Dev/napari/napari/utils/migrations.py", line 101, in _update_from_dict
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/piotrsobolewski/Dev/napari/napari/utils/migrations.py", line 101, in _update_from_dict
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 3 more times]
  File "/Users/piotrsobolewski/Dev/napari/napari/utils/add_layer.py_tmpl", line 11, in add_points
    self.layers.append(layer)
  File "<frozen _collections_abc>", line 1130, in append
  File "/Users/piotrsobolewski/Dev/napari/napari/components/layerlist.py", line 188, in insert
    super().insert(index, new_layer)
  File "/Users/piotrsobolewski/Dev/napari/napari/utils/events/containers/_selectable_list.py", line 71, in insert
    self.selection.active = value
    ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/piotrsobolewski/Dev/napari/napari/utils/events/containers/_selection.py", line 117, in active
    self.clear() if value is None else self.select_only(value)
                                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/piotrsobolewski/Dev/napari/napari/utils/events/containers/_selection.py", line 145, in select_only
    self.add(obj)
  File "/Users/piotrsobolewski/Dev/napari/napari/utils/events/containers/_set.py", line 79, in add
    value = self._pre_add_hook(value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/piotrsobolewski/Dev/napari/napari/utils/events/containers/_selectable_list.py", line 55, in _preselect_hook
    raise ValueError(
ValueError: Cannot select item that is not in list: <Points layer 'Points' at 0x310c1e600>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/piotrsobolewski/Dev/napari/napari/_qt/qt_viewer.py", line 981, in _qt_open
    self.viewer.open(
  File "/Users/piotrsobolewski/Dev/napari/napari/components/viewer_model.py", line 1232, in open
    layers = self._open_or_raise_error(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/piotrsobolewski/Dev/napari/napari/components/viewer_model.py", line 1341, in _open_or_raise_error
    raise ReaderPluginError(
napari.errors.reader_errors.ReaderPluginError: Tried opening with napari, but failed.

```

**Comment by jni** [comment]
The OP case currently works for me (new points get added to 'A') *but* with a traceback captured in the viewer:

```pytb
File ~/projects/napari/napari/utils/add_layer.py_tmpl:11, in add_points(self=Viewer(camera=Camera(center=(0.0, np.float64(255...use_drag_gen={}, _mouse_wheel_gen={}, _keymap={}), data=array([[253., 504.],
       [180., 450.],
       ...,
       [594., 577.],
       [466., 696.]]), ndim=None, affine=None, antialiasing=1, axis_labels=None, blending='translucent', border_color='dimgray', border_color_cycle=None, border_colormap='viridis', border_contrast_limits=None, border_width=0.05, border_width_is_relative=True, cache=True, canvas_size_limits=(2, 10000), experimental_clipping_planes=None, face_color='white', face_color_cycle=None, face_colormap='viridis', face_contrast_limits=None, feature_defaults=None, features=None, metadata=None, n_dimensional=None, name='points', opacity=1.0, out_of_slice_display=False, projection_mode='none', properties=None, property_choices=None, rotate=None, scale=None, shading='none', shear=None, shown=True, size=10, symbol='o', text=None, translate=None, units=None, visible=True)
     10         setattr(layer, name, value)
---> 11 self.layers.append(layer)
     12 return layer

File <frozen _collections_abc>:1078, in append(self=[<Points layer 'A' at 0x16c2a8290>], value=<Points layer 'points'>)

File ~/projects/napari/napari/components/layerlist.py:188, in LayerList.insert(self=[<Points layer 'A' at 0x16c2a8290>], index=1, value=<Points layer 'points'>)
    187 new_layer.events._extent_augmented.connect(self._clean_cache)
--> 188 super().insert(index, new_layer)
        new_layer = <Points layer 'points' at 0x16af23550>
        index = 1

File ~/projects/napari/napari/utils/events/containers/_selectable_list.py:71, in SelectableEventedList.insert(self=[<Points layer 'A' at 0x16c2a8290>], index=1, value=<Points layer 'points'>)
     69 if self._activate_on_insert:
     70     # Make layer selected and unselect all others
---> 71     self.selection.active = value
        value = <Points layer 'points' at 0x16af23550>
        self = [<Points layer 'A' at 0x16c2a8290>]

File ~/projects/napari/napari/utils/events/containers/_selection.py:117, in Selection.active(self=Selection(set()), value=<Points layer 'points'>)
    116 self._active = value
--> 117 self.clear() if value is None else self.select_only(value)
        value = <Points layer 'points' at 0x16af23550>
        self = Selection(set())
        value is None = False
    118 self._current = value

File ~/projects/napari/napari/utils/events/containers/_selection.py:145, in Selection.select_only(self=Selection(set()), obj=<Points layer 'points'>)
    144 self.intersection_update({obj})
--> 145 self.add(obj)
        obj = <Points layer 'points' at 0x16af23550>
        self = Selection(set())

File ~/projects/napari/napari/utils/events/containers/_set.py:79, in EventedSet.add(self=Selection(set()), value=<Points layer 'points'>)
     78 if value not in self:
---> 79     value = self._pre_add_hook(value)
        value = <Points layer 'points' at 0x16af23550>
        self = Selection(set())
        self._pre_add_hook = <bound method SelectableEventedList._preselect_hook of [<Points layer 'A' at 0x16c2a8290>]>
     80     self._set.add(value)

File ~/projects/napari/napari/utils/events/containers/_selectable_list.py:55, in SelectableEventedList._preselect_hook(self=[<Points layer 'A' at 0x16c2a8290>], value=<Points layer 'points'>)
     54 if value not in self:
---> 55     raise ValueError(
        trans = <napari.utils.translations.TranslationBundle object at 0x11ec35390>
        value = <Points layer 'points' at 0x16af23550>
     56         trans._(
     57             'Cannot select item that is not in list: {value!r}',
     58             deferred=True,
     59             value=value,
     60         )
     61     )
     62 return value

ValueError: Cannot select item that is not in list: <Points layer 'points' at 0x16af23550>
```

So it's trying to select the newly added layer but fails.

@psobolewskiPhD 

> immediately removing a layer before it’s even completed adding is an antipattern we should not enable?

I don't think the intent is "before it's even completed adding" — the event is "layers.inserted", past tense, so I think it's reasonable to expect that it *has* completed adding, and now I'm gonna do my thing in response.

I looked at the `connect()` method and it has a `position` kwarg, where `position='last'` is supposed to make this callback fire after all other callbacks. But it doesn't get rid of the above error, for some reason that I don't understand...

**Comment by jni** [comment]
Here's the script that I *think* should work, but doesn't:

```python
import numpy as np
import napari

viewer = napari.Viewer()

point_layer = viewer.add_points(name='A')

def transfer_and_delete(event):
    new_index = event.index
    new_layer = event.value

    point_layer.data = new_layer.data.copy()

    viewer.layers.remove(new_layer.name)

viewer.layers.events.inserted.connect(transfer_and_delete, position='last')

viewer.add_points(np.random.random((10, 2)) * 512)

napari.run()
```

(Note the `position='last'` when connecting.)

@Czaki any idea why that doesn't help?

**Comment by Czaki** [comment]
> @Czaki any idea why that doesn't help?

Because setting active happens after emit all events:

https://github.com/napari/napari/blob/7648fdce08af9249cd36eea61b0a38aad5b29c8b/napari/utils/events/containers/_selectable_list.py#L67-L71

The events are emitted in line https://github.com/napari/napari/blob/7648fdce08af9249cd36eea61b0a38aad5b29c8b/napari/utils/events/containers/_selectable_list.py#L68

End error is triggered in line:
https://github.com/napari/napari/blob/7648fdce08af9249cd36eea61b0a38aad5b29c8b/napari/utils/events/containers/_selectable_list.py#L71

the `"last"` only impacts the order of events (and is currently the default value)

**Comment by jni** [comment]
aaaaah well-spotted! Thank you!

**Comment by Czaki** [comment]
You have missed #7150 that changes the default position to last, so `position='last'` is default now.
