### ISSUE TITLE
Application has crashed

### ISSUE THREAD

**Issue by mariavmukhina** [napari/napari#3082]
Application 0.4.10-macOS crashes at initiation with following error:

Traceback (most recent call last):
  File "napari.app/Contents/Resources/app_packages/vispy/gloo/gl/_gl2.py", line 682, in _glGetIntegerv
    nativefunc = _glGetIntegerv._native
AttributeError: 'function' object has no attribute '_native'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "napari.app/Contents/Resources/app/napari/__main__.py", line 418, in <module>
    sys.exit(main())
  File "napari.app/Contents/Resources/app/napari/__main__.py", line 414, in main
    _run()
  File "napari.app/Contents/Resources/app/napari/__main__.py", line 298, in _run
    viewer = view_path(  # noqa: F841
  File "napari.app/Contents/Resources/app/napari/view_layers.py", line 169, in view_path
    return _make_viewer_then('open', args, kwargs)
  File "napari.app/Contents/Resources/app/napari/view_layers.py", line 115, in _make_viewer_then
    viewer = Viewer(**vkwargs)
  File "napari.app/Contents/Resources/app/napari/viewer.py", line 52, in __init__
    self._window = Window(self, show=show)
  File "napari.app/Contents/Resources/app/napari/_qt/qt_main_window.py", line 361, in __init__
    self.qt_viewer = QtViewer(viewer, show_welcome_screen=True)
  File "napari.app/Contents/Resources/app/napari/_qt/qt_viewer.py", line 199, in __init__
    self._create_canvas()
  File "napari.app/Contents/Resources/app/napari/_qt/qt_viewer.py", line 283, in _create_canvas
    self.canvas = VispyCanvas(
  File "napari.app/Contents/Resources/app/napari/_vispy/vispy_canvas.py", line 35, in __init__
    self.max_texture_sizes = get_max_texture_sizes()
  File "napari.app/Contents/Resources/app/napari/_vispy/utils_gl.py", line 55, in get_max_texture_sizes
    max_size_2d = gl.glGetParameter(gl.GL_MAX_TEXTURE_SIZE)
  File "napari.app/Contents/Resources/app_packages/vispy/gloo/gl/_gl2.py", line 792, in glGetParameter
    return _glGetIntegerv(pname)
  File "napari.app/Contents/Resources/app_packages/vispy/gloo/gl/_gl2.py", line 684, in _glGetIntegerv
    nativefunc = _glGetIntegerv._native = _get_gl_func("glGetIntegerv", None, (ctypes.c_uint, ctypes.POINTER(ctypes.c_int),))
  File "napari.app/Contents/Resources/app_packages/vispy/gloo/gl/gl2.py", line 69, in _get_gl_func
    raise RuntimeError('Could not load OpenGL library, gl cannot be used')
RuntimeError: Could not load OpenGL library, gl cannot be used

**Comment by sofroniewn** [comment]
Hmm, looks like this might be a vispy related issue @mmuxika. Have you ever been able to get napari working or this happens on first launch? Are you using the bundled app that you downloaded, or did you install napari with `pip` or something else? If you could add a little more info here it might help us track down the issue. Sorry you're running into problems!!

**Comment by jni** [comment]
@sofroniewn this path in the traceback: `napari.app/Contents/Resources/app_packages/vispy/gloo/gl/_gl2.py` shows that this is an issue with the bundled app.

**Comment by jni** [comment]
@mmuxika could you tell us about your macOS version and what Mac you are using?

To me it looks like an issue with OpenGL drivers, which is not going to be fun to deal with. But also, maybe @mmuxika you are using a new Apple Silicon Mac? In which case the bundle is not expected to work yet...

**Comment by mariavmukhina** [comment]
@sofroniewn, @jni yes, I was trying to start the bundled app for the first time. 
My system:
Model Name:	iMac Pro
  Model Identifier:	iMacPro1,1
  Processor Name:	18-Core Intel Xeon W
  Processor Speed:	2.3 GHz
  Number of Processors:	1
  Total Number of Cores:	18
  L2 Cache (per Core):	1 MB
  L3 Cache:	24.8 MB
  Hyper-Threading Technology:	Enabled
  Memory:	128 GB
  System Firmware Version:	1554.120.19.0.0 (iBridge: 18.16.14663.0.0,0)

**Comment by liu-ziyang** [comment]
@mariavmukhina we recently released a new packaging app with conda: https://napari.org/tutorials/fundamentals/installation.html#installing-as-a-bundled-app

I hope this resolves the issue. feel free to leave a comment if you still have trouble with the new packaging method. I would like to close this bug unless you have more information on reproducing this. Many thanks for bringing it to our attention!
