### ISSUE TITLE
It is not possible to create an empty tracks layer.

### ISSUE THREAD

**Issue by JoOkuma** [napari/napari#3111]
## 🐛 Bug

The tracks layer can't be created without data.

## To Reproduce

Execute:

```python3
import napari

viewer = napari.Viewer()
viewer.add_tracks()
```

Error:
```python3
Traceback (most recent call last):
  File "bug.py", line 5, in <module>
    viewer.add_tracks()  # doesn't work
TypeError: add_tracks() missing 1 required positional argument: 'data'
```

## Expected behavior

I expected it to allow to be constructed without data like the points layer since it already allows updating existing data:

```python3
import napari

viewer = napari.Viewer()                                                                                

starting_tracks = [[1, 0, 4, 4], 
                   [1, 1, 5, 5]] 

layer = viewer.add_tracks(starting_tracks)

additional_tracks = [[2, 0, 6, 6], 
                     [2, 1, 3, 3]] 

layer.data = starting_tracks + additional_tracks

napari.run()
```

## Environment
```
napari: 0.4.10
Platform: Linux-5.8.0-63-generic-x86_64-with-glibc2.17
System: Ubuntu 20.04.2 LTS
Python: 3.8.10 (default, Jun 4 2021, 15:09:15) [GCC 7.5.0]
Qt: 5.15.2
PyQt5: 5.15.4
NumPy: 1.20.3
SciPy: 1.7.0
Dask: 2021.05.1
VisPy: 0.7.0

OpenGL:
- GL version: 4.6.0 NVIDIA 460.73.01
- MAX_TEXTURE_SIZE: 32768

Screens:
- screen 1: resolution 3440x1440, scale 1.0

Plugins:
- animation: 0.0.2
- console: 0.0.3
- napari-dexp: 0.0.1.dev1
- ndtiffs: 0.1.2
- scikit-image: 0.4.10
- svg: 0.1.5
```

**Comment by QuaternionsRock** [comment]
Can you not pass `np.empty((0,4))` to achieve this behavior?

**Comment by JoOkuma** [comment]
No, it raises

```python3
Traceback (most recent call last):
  File "bug.py", line 6, in <module>
    viewer.add_tracks(np.empty((0, 4)))  # doesn't work
  File "<string>", line 4, in add_tracks
  File ".../napari/napari/layers/tracks/tracks.py", line 172, in __init__
    self.data = data
  File ".../napari/napari/layers/tracks/tracks.py", line 351, in data
    self._manager.data = data
  File ".../napari/napari/layers/tracks/_track_utils.py", line 131, in data
    self._id2idxs = coo_matrix(
  File "/miniconda3/envs/napari/lib/python3.8/site-packages/scipy/sparse/coo.py", line 147, in __init__
    raise ValueError('cannot infer dimensions from zero '
ValueError: cannot infer dimensions from zero sized index arrays
```

**Comment by kephale** [comment]
Bump because @cmalinmayor and i just ran into this again.

**Comment by DragaDoncila** [comment]
Thanks for the bump @kephale. I tend to agree this should be possible. I think the error message is giving a hint at what the hardest part of fixing this is going to be, namely, how to give dimensions to a data-less layer. 

I will note `viewer.add_labels()` doesn't work either, for the same reason. Buuut `viewer.add_shapes()` does work, because that's just an empty list. I feel like `viewer.add_tracks()` is more like `viewer.add_shapes()`, in that you should be able to pass an empty dataframe and it justworks™️. @jni thoughts?
