### ISSUE TITLE
Console freezes napari when `SyntaxError` due to `.` in unexpected places

### ISSUE THREAD

**Issue by brisvag** [napari/napari#3314]
## 🐛 Bug

A misplaced `.` that would normally just cause a `SyntaxError`, in the console it causes napari to freeze completely. Below the stack trace. Note that this does not happen with all SyntaxErrors, just when a `.` causes it (as far as I can tell), and sometimes it takes a couple errors before it freezes.

After some time (~1 min?), napari will unfreeze, only to freeze again at the next command (even correct ones).

## To Reproduce

To replicate, open napari and then simply enter `.` in the console (or stuff like `print().`. If nothing bad happens, to it again.

```python
11:20:12 ERROR Uncaught exception in ZMQStream callback
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 431, in _run_callback
    callback(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/ipykernel/iostream.py", line 126, in _handle_event
    event_f()
  File "/usr/lib/python3.9/site-packages/ipykernel/iostream.py", line 223, in <lambda>
    self.schedule(lambda : self._really_send(*args, **kwargs))
  File "/usr/lib/python3.9/site-packages/ipykernel/iostream.py", line 231, in _really_send
    self.socket.send_multipart(msg, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/ipykernel/inprocess/socket.py", line 35, in send_multipart
    self.message_sent += 1
  File "/usr/lib/python3.9/site-packages/traitlets/traitlets.py", line 604, in __set__
    self.set(obj, value)
  File "/usr/lib/python3.9/site-packages/traitlets/traitlets.py", line 593, in set
    obj._notify_trait(self.name, old_value, new_value)
  File "/usr/lib/python3.9/site-packages/traitlets/traitlets.py", line 1217, in _notify_trait
    self.notify_change(Bunch(
  File "/usr/lib/python3.9/site-packages/traitlets/traitlets.py", line 1227, in notify_change
    return self._notify_observers(change)
  File "/usr/lib/python3.9/site-packages/traitlets/traitlets.py", line 1264, in _notify_observers
    c(event)
  File "/usr/lib/python3.9/site-packages/ipykernel/inprocess/ipkernel.py", line 134, in _io_dispatch
    ident, msg = self.session.recv(self.iopub_socket, copy=False)
  File "/usr/lib/python3.9/site-packages/jupyter_client/session.py", line 809, in recv
    msg_list = socket.recv_multipart(mode, copy=copy)
  File "/usr/lib/python3.9/site-packages/ipykernel/iostream.py", line 255, in __getattr__
    warnings.warn("Accessing zmq Socket attribute %s on BackgroundSocket" % attr,
DeprecationWarning: Accessing zmq Socket attribute recv_multipart on BackgroundSocket
11:20:12 ERROR Uncaught exception in zmqstream callback
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 448, in _handle_events
    self._handle_recv()
  File "/usr/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 477, in _handle_recv
    self._run_callback(callback, msg)
  File "/usr/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 431, in _run_callback
    callback(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/ipykernel/iostream.py", line 126, in _handle_event
    event_f()
  File "/usr/lib/python3.9/site-packages/ipykernel/iostream.py", line 223, in <lambda>
    self.schedule(lambda : self._really_send(*args, **kwargs))
  File "/usr/lib/python3.9/site-packages/ipykernel/iostream.py", line 231, in _really_send
    self.socket.send_multipart(msg, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/ipykernel/inprocess/socket.py", line 35, in send_multipart
    self.message_sent += 1
  File "/usr/lib/python3.9/site-packages/traitlets/traitlets.py", line 604, in __set__
    self.set(obj, value)
  File "/usr/lib/python3.9/site-packages/traitlets/traitlets.py", line 593, in set
    obj._notify_trait(self.name, old_value, new_value)
  File "/usr/lib/python3.9/site-packages/traitlets/traitlets.py", line 1217, in _notify_trait
    self.notify_change(Bunch(
  File "/usr/lib/python3.9/site-packages/traitlets/traitlets.py", line 1227, in notify_change
    return self._notify_observers(change)
  File "/usr/lib/python3.9/site-packages/traitlets/traitlets.py", line 1264, in _notify_observers
    c(event)
  File "/usr/lib/python3.9/site-packages/ipykernel/inprocess/ipkernel.py", line 134, in _io_dispatch
    ident, msg = self.session.recv(self.iopub_socket, copy=False)
  File "/usr/lib/python3.9/site-packages/jupyter_client/session.py", line 809, in recv
    msg_list = socket.recv_multipart(mode, copy=copy)
  File "/usr/lib/python3.9/site-packages/ipykernel/iostream.py", line 255, in __getattr__
    warnings.warn("Accessing zmq Socket attribute %s on BackgroundSocket" % attr,
DeprecationWarning: Accessing zmq Socket attribute recv_multipart on BackgroundSocket
11:20:12 ERROR Exception in callback BaseAsyncIOLoop._handle_events(69, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(69, 1)>
Traceback (most recent call last):
  File "/usr/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3.9/site-packages/tornado/platform/asyncio.py", line 189, in _handle_events
    handler_func(fileobj, events)
  File "/usr/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 448, in _handle_events
    self._handle_recv()
  File "/usr/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 477, in _handle_recv
    self._run_callback(callback, msg)
  File "/usr/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 431, in _run_callback
    callback(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/ipykernel/iostream.py", line 126, in _handle_event
    event_f()
  File "/usr/lib/python3.9/site-packages/ipykernel/iostream.py", line 223, in <lambda>
    self.schedule(lambda : self._really_send(*args, **kwargs))
  File "/usr/lib/python3.9/site-packages/ipykernel/iostream.py", line 231, in _really_send
    self.socket.send_multipart(msg, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/ipykernel/inprocess/socket.py", line 35, in send_multipart
    self.message_sent += 1
  File "/usr/lib/python3.9/site-packages/traitlets/traitlets.py", line 604, in __set__
    self.set(obj, value)
  File "/usr/lib/python3.9/site-packages/traitlets/traitlets.py", line 593, in set
    obj._notify_trait(self.name, old_value, new_value)
  File "/usr/lib/python3.9/site-packages/traitlets/traitlets.py", line 1217, in _notify_trait
    self.notify_change(Bunch(
  File "/usr/lib/python3.9/site-packages/traitlets/traitlets.py", line 1227, in notify_change
    return self._notify_observers(change)
  File "/usr/lib/python3.9/site-packages/traitlets/traitlets.py", line 1264, in _notify_observers
    c(event)
  File "/usr/lib/python3.9/site-packages/ipykernel/inprocess/ipkernel.py", line 134, in _io_dispatch
    ident, msg = self.session.recv(self.iopub_socket, copy=False)
  File "/usr/lib/python3.9/site-packages/jupyter_client/session.py", line 809, in recv
    msg_list = socket.recv_multipart(mode, copy=copy)
  File "/usr/lib/python3.9/site-packages/ipykernel/iostream.py", line 255, in __getattr__
    warnings.warn("Accessing zmq Socket attribute %s on BackgroundSocket" % attr,
DeprecationWarning: Accessing zmq Socket attribute recv_multipart on BackgroundSocket
```

## Expected behavior

Just a normal `SyntaxError`.

## Environment

```yaml
napari: 0.4.11rc3
Platform: Linux-5.13.13-arch1-1-x86_64-with-glibc2.33
System: Arch Linux
Python: 3.9.6 (default, Jun 30 2021, 10:22:16) [GCC 11.1.0]
Qt: 5.15.2
PyQt5: 5.15.4
NumPy: 1.20.3
SciPy: 1.7.1
Dask: 2020.12.0
VisPy: 0.7.3

OpenGL:
- GL version: 4.6.0 NVIDIA 470.63.01
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1920x1080, scale 1.0
- screen 2: resolution 1920x1200, scale 1.0

Plugins:
- animation: 0.0.2
- console: 0.0.3
- mrcfile-reader: 0.1.2
- napari-em-reader: 0.1.0
- napari-oriented-points-picker: 0.1.dev1+g7336e66.d20210713
- napari-properties-plotter: 0.2.0
- ndtiffs: 0.1.1
- scikit-image: 0.4.9
- svg: 0.1.5
```

**Comment by goanpeca** [comment]
Any ideas on this one @Carreau 🤔 ?

**Comment by Carreau** [comment]
Would you mind checking your version of ipykernel ? That seem to me like an issue with the 5.x series that has been fixed in the 6.x series.

**Comment by Carreau** [comment]
(you may need to try to update jupyter_client as well)

**Comment by brisvag** [comment]
Just tried on a different computer, same issue arises. Here, I have this:
```
ipykernel==6.0.3
jupyter-client==6.1.12
```
updating to `jupyter-client 7` did not help. Can anyone reproduce this?

**Comment by Carreau** [comment]
ok, let me test with this specific combinaison.

**Comment by Carreau** [comment]
ha ! it seem to be random, so it might be a race condition.

**Comment by Carreau** [comment]
Ha, I think it's a thread thing. I'm trying to dump the state of the warning filters when reaching this place after setting it to "ignore" all warnings, and it often has a different set of filters. Something else is likely marking warnings as error and it is not restored. The docs mention that catch_warning in multiple thread is undefined.

I'll see if I can come up with a better workaround, but it might be a bit more tough. 
Maybe a custom subclass of BackgroundSocket that does not deprecate recv_multipart.

**Comment by sofroniewn** [comment]
i just tried and could not reproduce, but sounds like it is non-deterministic

**Comment by Carreau** [comment]
> i just tried and could not reproduce, but sounds like it is non-deterministic

Yeah, sometime I need to send a syntax error a dozen time before it triggers it, and as soon as I add debugs statements it can become less frequent.

**Comment by Carreau** [comment]
Ok, I think I'm happy with the fix on the ipykernel – Thanks for being patient I'll try to remember to notify here where the is a new release of ipykernel with the fix.
In addition in the next version the error messages should be a bit better if there is another issue.

**Comment by brisvag** [comment]
Great, thanks @Carreau!

**Comment by brisvag** [comment]
Checking back on this; it seems that napari no longer freezes if a simple `.` is entered! Instead, we get a normal `SyntaxError` and napari keeps working fine. We do get an additional Warning, but I would say we can close this issue and maybe @Carreau can address this upstream, if it makes sense.

```py
In [1]: .
  Input In [1]
    .
    ^
SyntaxError: invalid syntax

/home/lorenzo/venv/napari/lib/python3.10/site-packages/ipykernel/kernelbase.py:757: RuntimeWarning: coroutine 'InProcessKernel._abort_queues' was never awaited!

```
