### ISSUE TITLE
Removing a layer and immediately adding new one raises AttributeError

### ISSUE THREAD

**Issue by hanjinliu** [napari/napari#3337]
## 🐛 Bug

When I tried to remove a old layer and add a new one in a same code block or in a function, it stopped due to AttributeError. Same code worked with `napari==0.4.10`.

## To Reproduce

1. Open a viewer and add a layer
```python
import napari
viewer = napari.Viewer()
viewer.add_points([[0,0]], name="old")
```

2. Remove the old layer and add a new one in the same code block
```python
viewer.layers.remove("old")
viewer.add_points([[0,0]], name="new") # error!!
```

<details><summary>full traceback</summary><div>

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_20784/247010421.py in <module>
      1 viewer.layers.remove("old")
----> 2 viewer.add_points([[0,0]], name="new")

<string> in add_points(self, data, ndim, properties, text, symbol, size, edge_width, edge_color, edge_color_cycle, edge_colormap, edge_contrast_limits, face_color, face_color_cycle, face_colormap, face_contrast_limits, n_dimensional, name, metadata, scale, translate, rotate, shear, affine, opacity, blending, visible, property_choices, experimental_clipping_planes)

~\Anaconda3\envs\py39\lib\_collections_abc.py in append(self, value)
   1070     def append(self, value):
   1071         'S.append(value) -- append value to the end of the sequence'
-> 1072         self.insert(len(self), value)
   1073 
   1074     def clear(self):

~\Anaconda3\envs\py39\lib\site-packages\napari\components\layerlist.py in insert(self, index, value)
     78         new_layer = self._type_check(value)
     79         new_layer.name = self._coerce_name(new_layer.name)
---> 80         super().insert(index, new_layer)
     81 
     82         # required for deprecated layer.selected property.  remove after 0.4.9

~\Anaconda3\envs\py39\lib\site-packages\napari\utils\events\containers\_selectable_list.py in insert(self, index, value)
     61 
     62     def insert(self, index: int, value: _T):
---> 63         super().insert(index, value)
     64         if self._activate_on_insert:
     65             # Make layer selected and unselect all others

~\Anaconda3\envs\py39\lib\site-packages\napari\utils\events\containers\_evented_list.py in insert(self, index, value)
    177         self.events.inserting(index=index)
    178         super().insert(index, value)
--> 179         self.events.inserted(index=index, value=value)
    180         self._connect_child_emitters(value)
    181 

~\Anaconda3\envs\py39\lib\site-packages\napari\utils\events\event.py in __call__(self, *args, **kwargs)
    573                     continue
    574 
--> 575                 self._invoke_callback(cb, event)
    576                 if event.blocked:
    577                     break

~\Anaconda3\envs\py39\lib\site-packages\napari\utils\events\event.py in _invoke_callback(self, cb, event)
    605                 self.disconnect(cb)
    606                 return
--> 607             _handle_exception(
    608                 self.ignore_callback_errors,
    609                 self.print_callback_errors,

~\Anaconda3\envs\py39\lib\site-packages\napari\utils\events\event.py in _invoke_callback(self, cb, event)
    594     def _invoke_callback(self, cb: Callback, event: Event):
    595         try:
--> 596             cb(event)
    597         except Exception as e:
    598             # dead Qt object with living python pointer. not importing Qt

~\Anaconda3\envs\py39\lib\site-packages\napari\_qt\layer_controls\qt_layer_controls_container.py in _add(self, event)
    116         """
    117         layer = event.value
--> 118         controls = create_qt_layer_controls(layer)
    119         self.addWidget(controls)
    120         self.widgets[layer] = controls

~\Anaconda3\envs\py39\lib\site-packages\napari\_qt\layer_controls\qt_layer_controls_container.py in create_qt_layer_controls(layer)
     47     for layer_type, controls in layer_to_controls.items():
     48         if isinstance(layer, layer_type):
---> 49             return controls(layer)
     50 
     51     raise TypeError(

~\Anaconda3\envs\py39\lib\site-packages\napari\_qt\layer_controls\qt_points_controls.py in __init__(self, layer)
    133             Mode.SELECT,
    134         )
--> 135         action_manager.bind_button(
    136             'napari:activate_points_select_mode', self.select_button
    137         )

~\Anaconda3\envs\py39\lib\site-packages\napari\utils\action_manager.py in bind_button(self, name, button, extra_tooltip_text)
    329         button.destroyed.connect(lambda: self._buttons[name].remove(button))
    330         self._buttons[name].add(button)
--> 331         self._update_gui_elements(name)
    332 
    333     def bind_shortcut(self, name: str, shortcut: str) -> None:

~\Anaconda3\envs\py39\lib\site-packages\napari\utils\action_manager.py in _update_gui_elements(self, name)
    277         else:
    278             append = ''
--> 279         self._update_buttons(buttons, desc + shortcut_str + append, callable_)
    280 
    281     def _update_shortcut_bindings(self, name: str):

~\Anaconda3\envs\py39\lib\site-packages\napari\utils\action_manager.py in _update_buttons(self, buttons, tooltip, callback)
    242         for button in buttons:
    243             # test if only tooltip makes crash
--> 244             button.setToolTip(tooltip)
    245             button.clicked_maybe_connect(callback)
    246 

~\Anaconda3\envs\py39\lib\site-packages\napari\utils\action_manager.py in setToolTip(self, value)
     82 
     83     def setToolTip(self, value):
---> 84         return self._button().setToolTip(
     85             value + ' ' + self._extra_tooltip_text
     86         )

AttributeError: 'NoneType' object has no attribute 'setToolTip'
```

</div></details>

When I add a new layer before removing the old one, it was fine.

```python
viewer.add_points([[0,0]], name="old")
```

```python
viewer.add_points([[0,0]], name="new")
viewer.layers.remove("old") # OK
```

## Expected behavior

Old layer replaced by new one correctly.

## Environment

napari: 0.4.11
Platform: Windows-10-10.0.19042-SP0
Python: 3.9.6 (default, Aug 18 2021, 15:44:49) [MSC v.1916 64 bit (AMD64)]
Qt: 5.12.9
PyQt5: 5.12.3
NumPy: 1.20.3
SciPy: 1.6.2
Dask: 2021.08.1
VisPy: 0.8.1

OpenGL:
- GL version: 4.6.0 - Build 27.20.100.8681
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1368x912, scale 2.0

Plugins:
- console: 0.0.4
- scikit-image: 0.4.11
- svg: 0.1.5

**Comment by brisvag** [comment]
Can reproduce. Strangely, this does not happen if one separates the calls in different ipython cells:
```python
In [5]: viewer.add_points([[0,0]], name="old")
   ...: viewer.layers.remove("old")

In [6]: viewer.add_points([[0,0]], name="new") # no error!
```

PS: adding a sleep in between changes nothing.

**Comment by tlambert03** [comment]
even stranger, I can't get it to happen, regardless of whether I break the cells up or not in ipython, or run in a script directly.  @brisvag ... are you also on windows by chance?

the stack trace is pretty clear nonetheless

**Comment by brisvag** [comment]
Nope, linux here, on python3.9.6.

**Comment by psobolewskiPhD** [comment]
I get the same error on Mac OS Big Sur, running in VS Code Interactive Window (Python)
BUT, it works? The "old" layer is removed and "new" replaces it:
<img width="1202" alt="image" src="https://user-images.githubusercontent.com/76622105/132096059-0e4c9102-8a3f-44e7-a6ad-746c0d50a055.png">
Edit: NO, it does not work, see: https://github.com/napari/napari/issues/3337#issuecomment-912989446
Going line by line in separate cells has the same end, but no error.
Full Stack trace.
<details>

```
AttributeError: 'NoneType' object has no attribute 'setToolTip'
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Untitled-1 in <module>
      1 viewer.layers.remove("old")
----> 2 viewer.add_points([[0,0]], name="new") # error!!

<string> in add_points(self, data, ndim, properties, text, symbol, size, edge_width, edge_color, edge_color_cycle, edge_colormap, edge_contrast_limits, face_color, face_color_cycle, face_colormap, face_contrast_limits, n_dimensional, name, metadata, scale, translate, rotate, shear, affine, opacity, blending, visible, property_choices, experimental_clipping_planes)

~/Dev/miniforge3/envs/TF-StarDist-napari/lib/python3.9/_collections_abc.py in append(self, value)
   1070     def append(self, value):
   1071         'S.append(value) -- append value to the end of the sequence'
-> 1072         self.insert(len(self), value)
   1073 
   1074     def clear(self):

~/Dev/miniforge3/envs/TF-StarDist-napari/lib/python3.9/site-packages/napari/components/layerlist.py in insert(self, index, value)
     78         new_layer = self._type_check(value)
     79         new_layer.name = self._coerce_name(new_layer.name)
---> 80         super().insert(index, new_layer)
     81 
     82         # required for deprecated layer.selected property.  remove after 0.4.9

~/Dev/miniforge3/envs/TF-StarDist-napari/lib/python3.9/site-packages/napari/utils/events/containers/_selectable_list.py in insert(self, index, value)
     61 
     62     def insert(self, index: int, value: _T):
---> 63         super().insert(index, value)
     64         if self._activate_on_insert:
     65             # Make layer selected and unselect all others

~/Dev/miniforge3/envs/TF-StarDist-napari/lib/python3.9/site-packages/napari/utils/events/containers/_evented_list.py in insert(self, index, value)
    177         self.events.inserting(index=index)
    178         super().insert(index, value)
--> 179         self.events.inserted(index=index, value=value)
    180         self._connect_child_emitters(value)
    181 

~/Dev/miniforge3/envs/TF-StarDist-napari/lib/python3.9/site-packages/napari/utils/events/event.py in __call__(self, *args, **kwargs)
    573                     continue
    574 
--> 575                 self._invoke_callback(cb, event)
    576                 if event.blocked:
    577                     break

~/Dev/miniforge3/envs/TF-StarDist-napari/lib/python3.9/site-packages/napari/utils/events/event.py in _invoke_callback(self, cb, event)
    605                 self.disconnect(cb)
    606                 return
--> 607             _handle_exception(
    608                 self.ignore_callback_errors,
    609                 self.print_callback_errors,

~/Dev/miniforge3/envs/TF-StarDist-napari/lib/python3.9/site-packages/napari/utils/events/event.py in _invoke_callback(self, cb, event)
    594     def _invoke_callback(self, cb: Callback, event: Event):
    595         try:
--> 596             cb(event)
    597         except Exception as e:
    598             # dead Qt object with living python pointer. not importing Qt

~/Dev/miniforge3/envs/TF-StarDist-napari/lib/python3.9/site-packages/napari/_qt/layer_controls/qt_layer_controls_container.py in _add(self, event)
    116         """
    117         layer = event.value
--> 118         controls = create_qt_layer_controls(layer)
    119         self.addWidget(controls)
    120         self.widgets[layer] = controls

~/Dev/miniforge3/envs/TF-StarDist-napari/lib/python3.9/site-packages/napari/_qt/layer_controls/qt_layer_controls_container.py in create_qt_layer_controls(layer)
     47     for layer_type, controls in layer_to_controls.items():
     48         if isinstance(layer, layer_type):
---> 49             return controls(layer)
     50 
     51     raise TypeError(

~/Dev/miniforge3/envs/TF-StarDist-napari/lib/python3.9/site-packages/napari/_qt/layer_controls/qt_points_controls.py in __init__(self, layer)
    133             Mode.SELECT,
    134         )
--> 135         action_manager.bind_button(
    136             'napari:activate_points_select_mode', self.select_button
    137         )

~/Dev/miniforge3/envs/TF-StarDist-napari/lib/python3.9/site-packages/napari/utils/action_manager.py in bind_button(self, name, button, extra_tooltip_text)
    329         button.destroyed.connect(lambda: self._buttons[name].remove(button))
    330         self._buttons[name].add(button)
--> 331         self._update_gui_elements(name)
    332 
    333     def bind_shortcut(self, name: str, shortcut: str) -> None:

~/Dev/miniforge3/envs/TF-StarDist-napari/lib/python3.9/site-packages/napari/utils/action_manager.py in _update_gui_elements(self, name)
    277         else:
    278             append = ''
--> 279         self._update_buttons(buttons, desc + shortcut_str + append, callable_)
    280 
    281     def _update_shortcut_bindings(self, name: str):

~/Dev/miniforge3/envs/TF-StarDist-napari/lib/python3.9/site-packages/napari/utils/action_manager.py in _update_buttons(self, buttons, tooltip, callback)
    242         for button in buttons:
    243             # test if only tooltip makes crash
--> 244             button.setToolTip(tooltip)
    245             button.clicked_maybe_connect(callback)
    246 

~/Dev/miniforge3/envs/TF-StarDist-napari/lib/python3.9/site-packages/napari/utils/action_manager.py in setToolTip(self, value)
     82 
     83     def setToolTip(self, value):
---> 84         return self._button().setToolTip(
     85             value + ' ' + self._extra_tooltip_text
     86         )

AttributeError: 'NoneType' object has no attribute 'setToolTip'
```


</details>

Napari Info:
<details>

```
napari: 0.4.11
Platform: macOS-11.5.2-arm64-arm-64bit
System: MacOS 11.5.2
Python: 3.9.6 | packaged by conda-forge | (default, Jul 6 2021, 08:51:19) [Clang 11.1.0 ]
Qt: 5.15.2
PyQt5: 5.15.4
NumPy: 1.21.0
SciPy: 1.7.0
Dask: 2021.06.2
VisPy: 0.7.0

OpenGL:
- GL version: 2.1 Metal - 71.7.1
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1680x1050, scale 2.0

Plugins:
- 3 Utilities: 0.1.4
- 4 Measurements (skimage): 0.1.4
- StarDist: 2021.6.28
- aicsimageio-in-memory: 0.3.5
- aicsimageio-out-of-memory: 0.3.5
- animation: 0.0.2
- clEsperanto: 0.9.10
- console: 0.0.4
- ome-types: 0.2.6
- scikit-image: 0.4.11
- svg: 0.1.5
- video
```
</details>

**Comment by tlambert03** [comment]
the broader context here is that we probably need to get rid of the `bind_button` concept on the action_manager and come up with a better way to encapsulate the connection between a particular button in the viewer and some action resulting from pressing it (without passing around a literal pointer to the button, that may get destroyed).

see also #2914 #2977 #3227

**Comment by brisvag** [comment]
(yes, it works for me as well, it's a non-blocking error)

**Comment by hanjinliu** [comment]
No it's not. The new layer looks OK, but when I select it, the layer control does not respond (no widget appears) and KeyError is sent out from the layer list. It seems like the new layer is not completely added to the layer list.

**Comment by psobolewskiPhD** [comment]
Shit, you're right! Same here, the new layer is busted!
Sorry for not checking more carefully!
Full traceback:
<details>

```
Traceback (most recent call last):
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/TF-StarDist-napari/lib/python3.9/site-packages/napari/_qt/containers/_base_item_view.py", line 78, in selectionChanged
    self._root.selection.update(sel)
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/TF-StarDist-napari/lib/python3.9/site-packages/napari/utils/events/containers/_set.py", line 102, in update
    self.events.changed(added=set(to_add), removed={})
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/TF-StarDist-napari/lib/python3.9/site-packages/napari/utils/events/event.py", line 575, in __call__
    self._invoke_callback(cb, event)
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/TF-StarDist-napari/lib/python3.9/site-packages/napari/utils/events/event.py", line 607, in _invoke_callback
    _handle_exception(
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/TF-StarDist-napari/lib/python3.9/site-packages/napari/utils/events/event.py", line 596, in _invoke_callback
    cb(event)
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/TF-StarDist-napari/lib/python3.9/site-packages/napari/utils/events/containers/_selection.py", line 108, in _update_active
    self.active = list(self)[0]
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/TF-StarDist-napari/lib/python3.9/site-packages/napari/utils/events/containers/_selection.py", line 100, in active
    self.events.active(value=value)
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/TF-StarDist-napari/lib/python3.9/site-packages/napari/utils/events/event.py", line 575, in __call__
    self._invoke_callback(cb, event)
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/TF-StarDist-napari/lib/python3.9/site-packages/napari/utils/events/event.py", line 607, in _invoke_callback
    _handle_exception(
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/TF-StarDist-napari/lib/python3.9/site-packages/napari/utils/events/event.py", line 596, in _invoke_callback
    cb(event)
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/TF-StarDist-napari/lib/python3.9/site-packages/napari/_qt/layer_controls/qt_layer_controls_container.py", line 106, in _display
    controls = self.widgets[layer]
KeyError: <Points layer 'new' at 0x2bf284b20>
```


</details>

**Comment by tlambert03** [comment]
@hanjinlui (or anyone else who was able to reproduce this), can you check whether https://github.com/napari/napari/pull/3352 has solved this?

**Comment by psobolewskiPhD** [comment]
Works as expected on my end.

**Comment by hanjinliu** [comment]
Worked fine too!

**Comment by tlambert03** [comment]
Thanks!
