### ISSUE TITLE
3d click coordinates broken when viewer is displaying mixed-dimension data

### ISSUE THREAD

**Issue by jni** [napari/napari#3391]
## 🐛 Bug

Trying to do a 3D editing operation on a 3D labels volume *overlaid on a higher-dimensional image* results in:

```pytb
~/conda/envs/all/lib/python3.9/site-packages/napari/layers/labels/_labels_mouse_bindings.py in draw(layer=<Labels layer 'labels'>, event=<ReadOnlyWrapper at 0x1f1eb4a40 for MouseEvent>)
     28     """
     29     ndisplay = len(layer._dims_displayed)
---> 30     coordinates = mouse_event_to_labels_coordinate(layer, event)
        coordinates = undefined
        global mouse_event_to_labels_coordinate = <function mouse_event_to_labels_coordinate at 0x1ba88cd30>
        layer = <Labels layer 'labels' at 0x1fb851d90>
        event = <ReadOnlyWrapper at 0x1f1eb4a40 for MouseEvent at 0x1fde87e20>
     31 
     32     # on press

~/conda/envs/all/lib/python3.9/site-packages/napari/layers/labels/_labels_utils.py in mouse_event_to_labels_coordinate(layer=<Labels layer 'labels'>, event=<ReadOnlyWrapper at 0x1f1eb4a40 for MouseEvent>)
    195         coordinates = layer.world_to_data(event.position)
    196     else:  # 3d
--> 197         start, end = layer.get_ray_intersections(
        start = undefined
        end = undefined
        layer.get_ray_intersections = <bound method Layer.get_ray_intersections of <Labels layer 'labels' at 0x1fb851d90>>
        global position = undefined
        event.position = (5.0, 34.44371709653947, 32.51933079459317, 26.66526329906371)
        global view_direction = undefined
        event.view_direction = <class 'numpy.ndarray'> (4,) float64
        global dims_displayed = undefined
        layer._dims_displayed = [0, 1, 2]
        global world = undefined
    198             position=event.position,
    199             view_direction=event.view_direction,

~/conda/envs/all/lib/python3.9/site-packages/napari/layers/base/base.py in get_ray_intersections(self=<Labels layer 'labels'>, position=(5.0, 34.44371709653947, 32.51933079459317, 26.66526329906371), view_direction=<class 'numpy.ndarray'> (4,) float64, dims_displayed=[0, 1, 2], world=True)
   1281 
   1282             # create the bounding box in data coordinates
-> 1283             bbox = self._display_bounding_box(dims_displayed_mask)
        bbox = undefined
        self._display_bounding_box = <bound method Layer._display_bounding_box of <Labels layer 'labels' at 0x1fb851d90>>
        dims_displayed_mask = <class 'numpy.ndarray'> (4,) bool
   1284 
   1285             # get the view direction in data coords (only displayed dims)

~/conda/envs/all/lib/python3.9/site-packages/napari/layers/base/base.py in _display_bounding_box(self=<Labels layer 'labels'>, dims_displayed_mask=<class 'numpy.ndarray'> (4,) bool)
   1233     def _display_bounding_box(self, dims_displayed_mask: np.ndarray):
   1234         """An axis aligned (self._ndisplay, 2) bounding box around the data"""
-> 1235         return self._extent_data[:, dims_displayed_mask].T
        self._extent_data = <class 'numpy.ndarray'> (2, 3) float64
        dims_displayed_mask.T = <class 'numpy.ndarray'> (4,) bool
   1236 
   1237     def get_ray_intersections(

IndexError: boolean index did not match indexed array along dimension 1; dimension is 3 but corresponding boolean dimension is 4
```

That's because `dims_displayed_mask` is created using the *full* dims model but this layer only has 3 of those dims.

## To Reproduce

```python
from skimage.data import binary_blobs
from scipy import ndimage as ndi
import numpy as np
import napari

blobs3d = binary_blobs(length=64, volume_fraction=0.1, n_dim=3).astype(float)

blobs3dt = np.stack([np.roll(blobs3d, 3*i, axis=2) for i in range(10)])

labels = ndi.label(blobs3dt[5])[0]

viewer = napari.Viewer(ndisplay=3)

image_layer = viewer.add_image(blobs3dt)
labels_layer = viewer.add_labels(labels)
labels_layer.mode = 'fill'

viewer.dims.current_step = (5, 0, 0, 0)

napari.run()
```

Then click on an arbitrary label.

## Expected behavior

The label should be filled. It is sufficient to change `viewer.add_image(blobs3dt)` to `viewer.add_image(blobs3dt[5])` to get working behavior.

## Environment

```
napari: 0.4.12.dev18+gc53f34e85
Platform: macOS-11.4-x86_64-i386-64bit
System: MacOS 11.4
Python: 3.9.7 | packaged by conda-forge | (default, Sep  2 2021, 17:58:46)  [Clang 11.1.0 ]
Qt: 5.15.2
PyQt5: 5.15.4
NumPy: 1.20.3
SciPy: 1.7.1
Dask: 2021.09.0
VisPy: 0.8.1

OpenGL:
  - GL version:  2.1 ATI-4.5.14
  - MAX_TEXTURE_SIZE: 16384

Screens:
  - screen 1: resolution 2304x1296, scale 2.0
  - screen 2: resolution 1792x1120, scale 2.0

Plugins:
  - animation: 0.0.2
  - console: 0.0.4
  - napari-midi: 0.1.dev5+g16c91f6.d20210914
  - nd2-reader: 0.0.6
  - platelet-unet-watershed: 0.0.2
  - scikit-image: 0.4.12.dev18+gc53f34e85
  - svg: 0.1.5
  - tracks: 0.0.2
  - zarpaint: 0.2.0
```

**Comment by jni** [comment]
@nclack you were asking what sort of issues arise with having the slicing info on the layer, here's a good one! 😂

**Comment by psobolewskiPhD** [comment]
Bumping this, with main 4f4c063ae5dd79d6d188e201d44b8d57eba71909
I get a different traceback using the script from OP:
```
Traceback (most recent call last):
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/napari-dev/lib/python3.11/site-packages/vispy/app/backends/_qt.py", line 496, in mousePressEvent
    self._vispy_mouse_press(
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/napari-dev/lib/python3.11/site-packages/vispy/app/base.py", line 184, in _vispy_mouse_press
    ev = self._vispy_canvas.events.mouse_press(**kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/napari-dev/lib/python3.11/site-packages/vispy/util/event.py", line 453, in __call__
    self._invoke_callback(cb, event)
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/napari-dev/lib/python3.11/site-packages/vispy/util/event.py", line 471, in _invoke_callback
    _handle_exception(self.ignore_callback_errors,
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/napari-dev/lib/python3.11/site-packages/vispy/util/event.py", line 469, in _invoke_callback
    cb(event)
  File "/Users/piotrsobolewski/Dev/napari/napari/_vispy/canvas.py", line 462, in _on_mouse_press
    self._process_mouse_event(mouse_press_callbacks, event)
  File "/Users/piotrsobolewski/Dev/napari/napari/_vispy/canvas.py", line 409, in _process_mouse_event
    mouse_callbacks(layer, event)
  File "/Users/piotrsobolewski/Dev/napari/napari/utils/interactions.py", line 130, in mouse_press_callbacks
    next(gen)
  File "/Users/piotrsobolewski/Dev/napari/napari/layers/labels/_labels_mouse_bindings.py", line 30, in draw
    coordinates = mouse_event_to_labels_coordinate(layer, event)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/piotrsobolewski/Dev/napari/napari/layers/labels/_labels_utils.py", line 204, in mouse_event_to_labels_coordinate
    coordinates = first_nonzero_coordinate(layer.data, start, end)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/piotrsobolewski/Dev/napari/napari/layers/labels/_labels_utils.py", line 165, in first_nonzero_coordinate
    clipped_coords = np.clip(np.round(coords), 0, shape - 1).astype(int)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/napari-dev/lib/python3.11/site-packages/numpy/core/fromnumeric.py", line 2169, in clip
    return _wrapfunc(a, 'clip', a_min, a_max, out=out, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/napari-dev/lib/python3.11/site-packages/numpy/core/fromnumeric.py", line 59, in _wrapfunc
    return bound(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/napari-dev/lib/python3.11/site-packages/numpy/core/_methods.py", line 99, in _clip
    return um.clip(a, min, max, out=out, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: operands could not be broadcast together with shapes (65,4) () (3,) 
```

**Comment by jni** [comment]
😬 This will continue to be an issue as long as our axis broadcasting is so messy. CC @melonora
