### ISSUE TITLE
possible bug in affine transform slicing

### ISSUE THREAD

**Issue by grlee77** [napari/napari#3410]
## 🐛 Bug

When trying to open a volume with a supplied affine matrix of shape (4, 4), some permutations of axes can result in a crash.  I understand that general affines are not currently supported, but in this case, the data is aligned along the orthogonal axes, just in a permuted order. Is this currently expected to work? 

cc @andy-sweet (I mentioned this in the architecture working group meeting earlier today)

## To Reproduce

Below is a minimal example with an affine that permutes the order of the dimensions in the data (e.g. axis 2 of data corresponds to axis 0 in world coordinates, etc.).

```Python
import numpy as np
import napari
viewer = napari.Viewer()

vol = np.ones((128, 128, 128))

affine = [
    [0, 0, 1, 0],
    [1, 0, 0, 0],
    [0, 1, 0, 0],
    [0, 0, 0, 1]
]
viewer.add_image(vol, affine=affine)

napari.run()
```
This fails with the following traceback:

```
napari/napari/layers/base/base.py:745: UserWarning: Non-orthogonal slicing is being requested, but is not fully supported. Data is displayed without applying an out-of-slice rotation or shear component.
  warnings.warn(
Traceback (most recent call last):
  File "affine_crash.py", line 13, in <module>
    viewer.add_image(vol, affine=affine)
  File "napari/napari/components/viewer_model.py", line 753, in add_image
    self.layers.append(layer)
  File "_collections_abc.py", line 962, in append
    self.insert(len(self), value)
  File "napari/napari/components/layerlist.py", line 80, in insert
    super().insert(index, new_layer)
  File "napari/napari/utils/events/containers/_selectable_list.py", line 63, in insert
    super().insert(index, value)
  File "napari/napari/utils/events/containers/_evented_list.py", line 179, in insert
    self.events.inserted(index=index, value=value)
  File "napari/napari/utils/events/event.py", line 575, in __call__
    self._invoke_callback(cb, event)
  File "napari/napari/utils/events/event.py", line 607, in _invoke_callback
    _handle_exception(
  File "napari/napari/utils/events/event.py", line 596, in _invoke_callback
    cb(event)
  File "napari/napari/_qt/qt_viewer.py", line 405, in _on_add_layer_change
    self._add_layer(layer)
  File "napari/napari/_qt/qt_viewer.py", line 415, in _add_layer
    vispy_layer = create_vispy_visual(layer)
  File "napari/napari/_vispy/utils.py", line 62, in create_vispy_visual
    return visual_class(layer)
  File "napari/napari/_vispy/vispy_image_layer.py", line 67, in __init__
    self._on_display_change()
  File "napari/napari/_vispy/vispy_image_layer.py", line 90, in _on_display_change
    self.reset()
  File "napari/napari/_vispy/vispy_image_layer.py", line 187, in reset
    self._reset_base()
  File "napari/napari/_vispy/vispy_base_layer.py", line 165, in _reset_base
    self._on_matrix_change()
  File "napari/napari/_vispy/vispy_base_layer.py", line 153, in _on_matrix_change
    self._master_transform.matrix = affine_matrix
  File "site-packages/vispy/visuals/transforms/linear.py", line 401, in matrix
    self.shader_imap()
  File "site-packages/vispy/visuals/transforms/linear.py", line 389, in shader_imap
    fn['inv_matrix'] = self.inv_matrix  # uniform mat4
  File "site-packages/vispy/visuals/transforms/linear.py", line 407, in inv_matrix
    self._inv_matrix = np.linalg.inv(self.matrix)
  File "<__array_function__ internals>", line 5, in inv
  File "site-packages/numpy/linalg/linalg.py", line 545, in inv
    ainv = _umath_linalg.inv(a, signature=signature, extobj=extobj)
  File "site-packages/numpy/linalg/linalg.py", line 88, in _raise_linalgerror_singular
    raise LinAlgError("Singular matrix")
numpy.linalg.LinAlgError: Singular matrix

```

There is no problem if `affine=np.eye(4)` is used instead.

Aside from the crash, I was surprised to see the warning:
`UserWarning: Non-orthogonal slicing is being requested, but is not fully supported. Data is displayed without applying an out-of-slice rotation or shear component.`

## Expected behavior

As this type of permutation does not involve rotation or shear, I thought it would be supported. Is it instead the case that the matrix can only be diagonal with scale factors in the upper (3x3)?

## Environment

Current main branch of napari on linux.

## Additional context

My current workaround is to permute the data dimensions and make the corresponding changes to the affine before calling `add_image`.

An example real-world image with this type of affine is the following file: 
https://github.com/grlee77/parrec_oblique/blob/master/NIFTI/T1W_sag_0_0_0_SENSE_8_1.nii
which corresponds to a single sagittal slice MRI scan. It's affine is:
```
array([[  0.        ,   0.        ,   5.        ,   2.40481853],
       [ -0.42857143,   0.        ,   0.        , 130.22042847],
       [  0.        ,  -0.42857143,   0.        , 120.        ],
       [  0.        ,   0.        ,   0.        ,   1.        ]])
```

**Comment by andy-sweet** [comment]
Thanks @grlee77.

My first reaction is that this represents a general bug around `Affine.set_slice` when that represents a transform 3 or more dimensions with more than just scale and translate. If so, this should probably be bumped up in priority.

For example, if we slice a 3D matrix in 2 dimensions (as happens when visualizing a 3D volume in 2-dimensions), then `Affine.set_slice` effectively transforms an nxn affine transform matrix to a (n-1)x(n-1) affine transform matrix, by removing the unused dimension. Using your permutation matrix example, we get 

```python
affine = Affine(affine_matrix=[
    [0, 0, 1, 0],
    [1, 0, 0, 0],
    [0, 1, 0, 0],
    [0, 0, 0, 1],
])
sliced_affine = affine.set_slice([1, 2])
# Affine(affine_matrix=[
#    [0, 0, 0],
#    [1, 0, 0],
#    [0, 0, 1],
# ])
```

where `sliced_affine` is clearly singular.

When the affine just contains scale and translation, I think set_slice is well defined, because the dimensions aren't mixed when applying that transform. But as soon as we introduce rotation, shear, or general affine transforms (including pure permutations), then it is no longer well defined and will lose important information (in the case of a pure permutation, it will actually lose rank and cause this error).

I may be mistaken or missing some context around this used in napari, so it would be good to hear from others - maybe @sofroniewn?

**Comment by nclack** [comment]
It looks like `set_slices`

**Comment by sofroniewn** [comment]
Yeah this is definitely a bit funky - I think the warning was being thrown as we knew this was quite going to work out, but we should try and do better now - at least for these cases when an orthogonal view is actually being requested, just a permuted one.

we now though have a lot better support for non-orthogonal slicing in the shader. So we could try and take advantage of that here or implement a better slicing in the cpu

I’m very open to suggestions here!!

**Comment by andy-sweet** [comment]
Removed myself from this because it has multiple assignees and because it may be something that is fixed by general updates to slicing.

**Comment by liu-ziyang** [comment]
@grlee77 Hi there, do you still plan to take this one on? If not I can unassign it, Thanks!

**Comment by grlee77** [comment]
This should be working aside from Shapes layers. If someone more familiar with that layer type could help, that would be great. Alternatively, we can raise an error for that layer type if an affine with permutations is provided.

**Comment by psobolewskiPhD** [comment]
On main 22a5018f9e8c7b8ecbe4df86786db45e6ecc1f2e
The script from the OP still triggers a traceback:
```
---------------------------------------------------------------------------
LinAlgError                               Traceback (most recent call last)
File ~/Dev/vispy/vispy/app/backends/_qt.py:928, in CanvasBackendDesktop.paintGL(self=<vispy.app.backends._qt.CanvasBackendDesktop object>)
    926 # (0, 0, self.width(), self.height()))
    927 self._vispy_canvas.set_current()
--> 928 self._vispy_canvas.events.draw(region=None)
        self._vispy_canvas = <NapariSceneCanvas (PyQt6) at 0x12bdc1460>
        self._vispy_canvas.events.draw = <vispy.util.event.EventEmitter object at 0x12bdd4c50>
        self = <vispy.app.backends._qt.CanvasBackendDesktop object at 0x139a50a50>
        self._vispy_canvas.events = <vispy.util.event.EmitterGroup object at 0x11fdecbc0>
    930 # Clear the alpha channel with QOpenGLWidget (Qt >= 5.4), otherwise the
    931 # window is translucent behind non-opaque objects.
    932 # Reference:  MRtrix3/mrtrix3#266
    933 if QT5_NEW_API or PYSIDE6_API or PYQT6_API:

File ~/Dev/vispy/vispy/util/event.py:453, in EventEmitter.__call__(self=<vispy.util.event.EventEmitter object>, *args=(), **kwargs={'region': None})
    450 if self._emitting > 1:
    451     raise RuntimeError('EventEmitter loop detected!')
--> 453 self._invoke_callback(cb, event)
        event = <DrawEvent blocked=False handled=False native=None region=None source=None sources=[] type=draw>
        self = <vispy.util.event.EventEmitter object at 0x12bdd4c50>
        cb = <bound method VispyCanvas.on_draw of <napari._vispy.canvas.VispyCanvas object at 0x12bdc1b50>>
    454 if event.blocked:
    455     break

File ~/Dev/vispy/vispy/util/event.py:471, in EventEmitter._invoke_callback(self=<vispy.util.event.EventEmitter object>, cb=<bound method VispyCanvas.on_draw of <napari._vispy.canvas.VispyCanvas object>>, event=<DrawEvent blocked=False handled=False native=None region=None source=None sources=[] type=draw>)
    469     cb(event)
    470 except Exception:
--> 471     _handle_exception(self.ignore_callback_errors,
        self = <vispy.util.event.EventEmitter object at 0x12bdd4c50>
        cb = <bound method VispyCanvas.on_draw of <napari._vispy.canvas.VispyCanvas object at 0x12bdc1b50>>
        event = <DrawEvent blocked=False handled=False native=None region=None source=None sources=[] type=draw>
        (cb, event) = (<bound method VispyCanvas.on_draw of <napari._vispy.canvas.VispyCanvas object at 0x12bdc1b50>>, <DrawEvent blocked=False handled=False native=None region=None source=None sources=[] type=draw>)
    472                       self.print_callback_errors,
    473                       self, cb_event=(cb, event))

File ~/Dev/vispy/vispy/util/event.py:469, in EventEmitter._invoke_callback(self=<vispy.util.event.EventEmitter object>, cb=<bound method VispyCanvas.on_draw of <napari._vispy.canvas.VispyCanvas object>>, event=<DrawEvent blocked=False handled=False native=None region=None source=None sources=[] type=draw>)
    467 def _invoke_callback(self, cb, event):
    468     try:
--> 469         cb(event)
        cb = <bound method VispyCanvas.on_draw of <napari._vispy.canvas.VispyCanvas object at 0x12bdc1b50>>
        event = <DrawEvent blocked=False handled=False native=None region=None source=None sources=[] type=draw>
    470     except Exception:
    471         _handle_exception(self.ignore_callback_errors,
    472                           self.print_callback_errors,
    473                           self, cb_event=(cb, event))

File ~/Dev/napari/napari/_vispy/canvas.py:542, in VispyCanvas.on_draw(self=<napari._vispy.canvas.VispyCanvas object>, event=<DrawEvent blocked=False handled=False native=None region=None source=None sources=[] type=draw>)
    540 else:
    541     displayed_axes = list(self.viewer.dims.displayed[-nd:])
--> 542 layer._update_draw(
        layer = <Image layer 'vol' at 0x14cd28890>
        self = <napari._vispy.canvas.VispyCanvas object at 0x12bdc1b50>
        self.viewer = Viewer(camera=Camera(center=(0.0, np.float64(63.5), np.float64(63.5)), zoom=np.float64(4.453125), angles=(0.0, 0.0, 90.0), perspective=0.0, mouse_pan=True, mouse_zoom=True), cursor=Cursor(position=(np.float64(63.0), np.float64(129.92400192472397), np.float64(143.4606461725546)), scaled=True, style=<CursorStyle.STANDARD: 'standard'>, size=1.0), dims=Dims(ndim=3, ndisplay=2, order=(0, 1, 2), axis_labels=('0', '1', '2'), rollable=(True, True, True), range=(RangeTuple(start=np.float64(0.0), stop=np.float64(127.0), step=np.float64(1.0)), RangeTuple(start=np.float64(0.0), stop=np.float64(127.0), step=np.float64(1.0)), RangeTuple(start=np.float64(0.0), stop=np.float64(127.0), step=np.float64(1.0))), margin_left=(0.0, 0.0, 0.0), margin_right=(0.0, 0.0, 0.0), point=(np.float64(63.0), np.float64(63.0), np.float64(63.0)), last_used=0), grid=GridCanvas(stride=1, shape=(-1, -1), enabled=False), layers=[<Image layer 'vol' at 0x14cd28890>], help='', status='Ready', tooltip=Tooltip(visible=False, text=''), theme='dark', title='napari', mouse_over_canvas=True, mouse_move_callbacks=[], mouse_drag_callbacks=[], mouse_double_click_callbacks=[], mouse_wheel_callbacks=[<function dims_scroll at 0x11fa08360>], _persisted_mouse_event={}, _mouse_drag_gen={}, _mouse_wheel_gen={}, _keymap={})
        self.viewer.camera.zoom = np.float64(4.453125)
        self.viewer.camera = Camera(center=(0.0, np.float64(63.5), np.float64(63.5)), zoom=np.float64(4.453125), angles=(0.0, 0.0, 90.0), perspective=0.0, mouse_pan=True, mouse_zoom=True)
        canvas_corners_world = array([[ 63.     ,  -3.86842, -36.92302],
       [ 63.     , 130.86842, 163.92302]])
        displayed_axes = [1, 2]
        self._scene_canvas = <NapariSceneCanvas (PyQt6) at 0x12bdc1460>
    543     scale_factor=1 / self.viewer.camera.zoom,
    544     corner_pixels_displayed=canvas_corners_world[
    545         :, displayed_axes
    546     ],
    547     shape_threshold=self._scene_canvas.size,
    548 )

File ~/Dev/napari/napari/layers/base/base.py:2002, in Layer._update_draw(self=<Image layer 'vol'>, scale_factor=np.float64(0.22456140350877193), corner_pixels_displayed=array([[ -3.86842, -36.92302],
       [130.86842, 163.92302]]), shape_threshold=(638, 428))
   1997 all_corners = list(itertools.product(*corner_pixels_displayed.T))
   1998 # Note that we ignore the first transform which is tile2data
   1999 data_corners = (
   2000     self._transforms[1:]
   2001     .simplified.set_slice(displayed_axes)
-> 2002     .inverse(all_corners)
        self = <Image layer 'vol' at 0x14cd28890>
        self._transforms = [<napari.utils.transforms.transforms.Affine object at 0x14cea3ec0>, <napari.utils.transforms.transforms.CompositeAffine object at 0x14cd70080>, <napari.utils.transforms.transforms.Affine object at 0x14cd2bce0>, <napari.utils.transforms.transforms.Affine object at 0x14cd720f0>]
        displayed_axes = [np.int64(1), np.int64(2)]
        all_corners = [(np.float64(-3.868421054606724), np.float64(-36.92302057369593)), (np.float64(-3.868421054606724), np.float64(163.92301674586398)), (np.float64(130.86841902810747), np.float64(-36.92302057369593)), (np.float64(130.86841902810747), np.float64(163.92301674586398))]
   2003 )
   2005 # find the maximal data-axis-aligned bounding box containing all four
   2006 # canvas corners and round them to ints
   2007 data_bbox = np.stack(
   2008     [np.min(data_corners, axis=0), np.max(data_corners, axis=0)]
   2009 )

File ~/Dev/napari/napari/utils/transforms/transforms.py:665, in Affine.inverse(self=<napari.utils.transforms.transforms.Affine object>)
    662 """Return the inverse transform."""
    663 if 'inverse' not in self._cache_dict:
    664     self._cache_dict['inverse'] = Affine(
--> 665         affine_matrix=np.linalg.inv(self.affine_matrix)
        self._cache_dict = {}
        self = <napari.utils.transforms.transforms.Affine object at 0x14cd28dd0>
        np.linalg.inv = <function inv at 0x1056f1230>
        np.linalg = <module 'numpy.linalg' from '/Users/piotrsobolewski/Dev/miniforge3/envs/napari-dev/lib/python3.12/site-packages/numpy/linalg/__init__.py'>
        np = <module 'numpy' from '/Users/piotrsobolewski/Dev/miniforge3/envs/napari-dev/lib/python3.12/site-packages/numpy/__init__.py'>
    666     )
    667 return self._cache_dict['inverse']

File ~/Dev/miniforge3/envs/napari-dev/lib/python3.12/site-packages/numpy/linalg/_linalg.py:608, in inv(a=array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.]]))
    605 signature = 'D->D' if isComplexType(t) else 'd->d'
    606 with errstate(call=_raise_linalgerror_singular, invalid='call',
    607               over='ignore', divide='ignore', under='ignore'):
--> 608     ainv = _umath_linalg.inv(a, signature=signature)
        signature = 'd->d'
        a = array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.]])
        _umath_linalg.inv = <ufunc 'inv'>
        _umath_linalg = <module 'numpy.linalg._umath_linalg' from '/Users/piotrsobolewski/Dev/miniforge3/envs/napari-dev/lib/python3.12/site-packages/numpy/linalg/_umath_linalg.cpython-312-darwin.so'>
    609 return wrap(ainv.astype(result_t, copy=False))

File ~/Dev/miniforge3/envs/napari-dev/lib/python3.12/site-packages/numpy/linalg/_linalg.py:104, in _raise_linalgerror_singular(err='invalid value', flag=8)
    103 def _raise_linalgerror_singular(err, flag):
--> 104     raise LinAlgError("Singular matrix")

LinAlgError: Singular matrix
```
