### ISSUE TITLE
Displaying images/points in Spyder breaks event loop

### ISSUE THREAD

**Issue by jo-mueller** [napari/napari#3489]
## 🐛 Bug

Hi napari-community, I am having ongoing issues with using napari from the Spyder IDE. My current issue is, that I can not add data (images, points, etc) without breaking napari, i.e. some of its functionality.

Right now, I am trying to add an image and points to the viewer which prompts the following error. In practice, **the points layer does not respond to the size slider and the color selector anymore**, while the same still works for the points' shape property or the properties of the image layer.

```
ERROR:tornado.general:Uncaught exception in ZMQStream callback
Traceback (most recent call last):
  File "C:\Users\johan\anaconda3\envs\STRESS\lib\site-packages\zmq\eventloop\zmqstream.py", line 431, in _run_callback
    callback(*args, **kwargs)
  File "C:\Users\johan\anaconda3\envs\STRESS\lib\site-packages\jupyter_client\threaded.py", line 121, in _handle_recv
    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))
  File "C:\Users\johan\anaconda3\envs\STRESS\lib\asyncio\base_events.py", line 618, in run_until_complete
    self._check_running()
  File "C:\Users\johan\anaconda3\envs\STRESS\lib\asyncio\base_events.py", line 580, in _check_running
    raise RuntimeError(
RuntimeError: Cannot run the event loop while another loop is running
ERROR:tornado.general:Uncaught exception in zmqstream callback
Traceback (most recent call last):
  File "C:\Users\johan\anaconda3\envs\STRESS\lib\site-packages\zmq\eventloop\zmqstream.py", line 448, in _handle_events
    self._handle_recv()
  File "C:\Users\johan\anaconda3\envs\STRESS\lib\site-packages\zmq\eventloop\zmqstream.py", line 477, in _handle_recv
    self._run_callback(callback, msg)
  File "C:\Users\johan\anaconda3\envs\STRESS\lib\site-packages\zmq\eventloop\zmqstream.py", line 431, in _run_callback
    callback(*args, **kwargs)
  File "C:\Users\johan\anaconda3\envs\STRESS\lib\site-packages\jupyter_client\threaded.py", line 121, in _handle_recv
    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))
  File "C:\Users\johan\anaconda3\envs\STRESS\lib\asyncio\base_events.py", line 618, in run_until_complete
    self._check_running()
  File "C:\Users\johan\anaconda3\envs\STRESS\lib\asyncio\base_events.py", line 580, in _check_running
    raise RuntimeError(
RuntimeError: Cannot run the event loop while another loop is running
```

## To Reproduce

1. New conda environment with Spyder (installed through navigator)
2. ```conda install -c conda-forge napari```
3. Running this sample code (basically the example from [here](https://napari.org/tutorials/fundamentals/points.html))

```python
import numpy as np
import napari
from skimage import data

viewer = napari.view_image(data.astronaut(), rgb=True)
points = np.array([[100, 100], [200, 200], [300, 100]])
point_properties = {
    'good_point': np.array([True, True, False]),
    'confidence': np.array([0.99, 0.8, 0.2]),
}

points_layer = viewer.add_points(
    points,
    properties=point_properties,
    face_color='confidence',
    face_colormap='viridis',
)
```

## Expected behavior

Add points to viewer allows changing size and color with napari controls

## Environment

napari: 0.4.11
Platform: Windows-10-10.0.19043-SP0
Python: 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)]
Qt: 5.9.7
PyQt5: 5.9.2
NumPy: 1.21.2
SciPy: 1.7.1
Dask: 2021.09.1
VisPy: 0.9.0

OpenGL:
- GL version: 4.6.0 - Build 26.20.100.7985
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1920x1080, scale 1.0

Plugins:
- console: 0.0.4
- scikit-image: 0.4.11
- svg: 0.1.5

**Comment by jo-mueller** [comment]
Also, note: I stumbled over the exact same error on the [Vectors layer tutorial page](https://napari.org/tutorials/fundamentals/vectors.html). Is it intended known behaviour and my error may have a different origin?

**Comment by melissawm** [comment]
Related: napari/napari.github.io#161, napari/napari.github.io#172

**Comment by sofroniewn** [comment]
@goanpeca can you take a look at this one, thanks!!

**Comment by psobolewskiPhD** [comment]
I think I've posted this in the other Docs issues, but that same `zmq` error is on the root Tutorials page too:
https://napari.org/tutorials/index.html

Come to think of it, I got a spam of `zmq` warnings with @haesleinhuepf latest gem: napari-atari. 
His plugin isn't using anything related to `zmq` and it only happened when launching napari from the terminal, never from within ipython/jupyter. 
Here's that issue if it has some kernel of insight: https://github.com/haesleinhuepf/natari/issues/3 )

**Comment by goanpeca** [comment]
>@goanpeca can you take a look at this one, thanks!!

I can try!

**Comment by Czaki** [comment]
itt looks like loop detection (for example for pycharm) does not detect that qt loop is already started.

**Comment by VolkerH** [comment]
I stumbled on this error too, in a jupyter notebook. It doesn't seem to break anything though:

I run a cell that plots a bunch of points
```
imzml_pts_layer = v.add_points(
    data=coords[:, :2], face_color="white", edge_color="white", size=0.01, opacity=0.5
)
```

and receive the following error

```
ERROR:tornado.general:Uncaught exception in ZMQStream callback
Traceback (most recent call last):
  File "/home/hilsenst/miniconda3/envs/spacem_ht/lib/python3.8/site-packages/zmq/eventloop/zmqstream.py", line 431, in _run_callback
    callback(*args, **kwargs)
  File "/home/hilsenst/miniconda3/envs/spacem_ht/lib/python3.8/site-packages/jupyter_client/threaded.py", line 121, in _handle_recv
    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))
  File "/home/hilsenst/miniconda3/envs/spacem_ht/lib/python3.8/asyncio/base_events.py", line 592, in run_until_complete
    self._check_running()
  File "/home/hilsenst/miniconda3/envs/spacem_ht/lib/python3.8/asyncio/base_events.py", line 554, in _check_running
    raise RuntimeError(
RuntimeError: Cannot run the event loop while another loop is running
ERROR:tornado.general:Uncaught exception in zmqstream callback
Traceback (most recent call last):
  File "/home/hilsenst/miniconda3/envs/spacem_ht/lib/python3.8/site-packages/zmq/eventloop/zmqstream.py", line 452, in _handle_events
    self._handle_recv()
  File "/home/hilsenst/miniconda3/envs/spacem_ht/lib/python3.8/site-packages/zmq/eventloop/zmqstream.py", line 481, in _handle_recv
    self._run_callback(callback, msg)
  File "/home/hilsenst/miniconda3/envs/spacem_ht/lib/python3.8/site-packages/zmq/eventloop/zmqstream.py", line 431, in _run_callback
    callback(*args, **kwargs)
  File "/home/hilsenst/miniconda3/envs/spacem_ht/lib/python3.8/site-packages/jupyter_client/threaded.py", line 121, in _handle_recv
    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))
  File "/home/hilsenst/miniconda3/envs/spacem_ht/lib/python3.8/asyncio/base_events.py", line 592, in run_until_complete
    self._check_running()
  File "/home/hilsenst/miniconda3/envs/spacem_ht/lib/python3.8/asyncio/base_events.py", line 554, in _check_running
    raise RuntimeError(
RuntimeError: Cannot run the event loop while another loop is running
Exception in callback BaseAsyncIOLoop._handle_events(106, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(106, 1)>
Traceback (most recent call last):
  File "/home/hilsenst/miniconda3/envs/spacem_ht/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/home/hilsenst/miniconda3/envs/spacem_ht/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 189, in _handle_events
    handler_func(fileobj, events)
  File "/home/hilsenst/miniconda3/envs/spacem_ht/lib/python3.8/site-packages/zmq/eventloop/zmqstream.py", line 452, in _handle_events
    self._handle_recv()
  File "/home/hilsenst/miniconda3/envs/spacem_ht/lib/python3.8/site-packages/zmq/eventloop/zmqstream.py", line 481, in _handle_recv
    self._run_callback(callback, msg)
  File "/home/hilsenst/miniconda3/envs/spacem_ht/lib/python3.8/site-packages/zmq/eventloop/zmqstream.py", line 431, in _run_callback
    callback(*args, **kwargs)
  File "/home/hilsenst/miniconda3/envs/spacem_ht/lib/python3.8/site-packages/jupyter_client/threaded.py", line 121, in _handle_recv
    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))
  File "/home/hilsenst/miniconda3/envs/spacem_ht/lib/python3.8/asyncio/base_events.py", line 592, in run_until_complete
    self._check_running()
  File "/home/hilsenst/miniconda3/envs/spacem_ht/lib/python3.8/asyncio/base_events.py", line 554, in _check_running
    raise RuntimeError(
RuntimeError: Cannot run the event loop while another loop is running
/home/hilsenst/miniconda3/envs/spacem_ht/lib/python3.8/site-packages/napari/_qt/widgets/qt_welcome.py:86: RuntimeWarning: coroutine 'get_msg' was never awaited
  option = QStyleOption()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

The viewer has just been set up before as `v=napari.Viewer()` and other than some code that loads the point coordinates there is nothing else. I don't have a `qui %qt` statement (I also tried with, but it doesn't make a difference).

Jupyter environment:

```
Server Information:

You are using Jupyter notebook.

The version of the notebook server is: 6.4.6
The server is running on this version of Python:

Python 3.8.12 (default, Oct 12 2021, 13:49:34) 
[GCC 7.5.0]

Current Kernel Information:

Python 3.8.12 (default, Oct 12 2021, 13:49:34) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.30.1 -- An enhanced Interactive Python. Type '?' for help.
```

Napari info:

```
napari: 0.4.13.dev156+g7341615b
Platform: Linux-5.13.0-27-generic-x86_64-with-glibc2.17
System: Ubuntu 20.04.3 LTS
Python: 3.8.12 (default, Oct 12 2021, 13:49:34) [GCC 7.5.0]
Qt: 5.15.2
PyQt5: 5.15.6
NumPy: 1.21.5
SciPy: 1.7.3
Dask: 2021.06.2
VisPy: 0.9.4

OpenGL:
- GL version: 4.6.0 NVIDIA 460.91.03
- MAX_TEXTURE_SIZE: 32768

Screens:
- screen 1: resolution 3840x2160, scale 1.0

Plugins:
- console: 0.0.4
- napari-ome-zarr: 0.2.1.dev6+gb626109
- napari-sample-layout: 0.0.1
- scikit-image: 0.4.13.dev156+g7341615b
```

Maybe relevant:
```
tornado==6.1
pyzmq==22.3.0
```

**Comment by dalthviz** [comment]
Hi, checked this creating an env using only the conda-forge channel with Python 3.9 running the following commands:

     conda create -n spyder-napari -c conda-forge python=3.9 spyder
     conda activate spyder-napari
     conda install -c conda-forge napari

<details>

```
# Name                    Version                   Build  Channel
alabaster                 0.7.12                     py_0    conda-forge
aom                       3.5.0                h63175ca_0    conda-forge
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
arrow                     1.2.3              pyhd8ed1ab_0    conda-forge
asciitree                 0.3.3                      py_2    conda-forge
astroid                   2.12.13          py39hcbf5309_0    conda-forge
atomicwrites              1.4.1              pyhd8ed1ab_0    conda-forge
attrs                     22.2.0             pyh71513ae_0    conda-forge
autopep8                  1.6.0              pyhd8ed1ab_1    conda-forge
babel                     2.11.0             pyhd8ed1ab_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                pyhd8ed1ab_3    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
bcrypt                    3.2.2            py39ha55989b_1    conda-forge
beautifulsoup4            4.11.1             pyha770c72_0    conda-forge
binaryornot               0.4.4                      py_1    conda-forge
black                     22.10.0          py39hcbf5309_2    conda-forge
bleach                    5.0.1              pyhd8ed1ab_0    conda-forge
blosc                     1.21.3               hdccc3a2_0    conda-forge
bokeh                     2.4.3              pyhd8ed1ab_3    conda-forge
brotlipy                  0.7.0           py39ha55989b_1005    conda-forge
bzip2                     1.0.8                h8ffe710_4    conda-forge
c-blosc2                  2.6.1                h183a6f4_0    conda-forge
ca-certificates           2022.12.7            h5b45459_0    conda-forge
cachey                    0.2.1              pyh9f0ad1d_0    conda-forge
certifi                   2022.12.7          pyhd8ed1ab_0    conda-forge
cffi                      1.15.1           py39h68f70e3_3    conda-forge
cfitsio                   4.2.0                h9ebe7e4_0    conda-forge
chardet                   5.1.0            py39hcbf5309_0    conda-forge
charls                    2.3.4                h39d44d4_0    conda-forge
charset-normalizer        2.1.1              pyhd8ed1ab_0    conda-forge
click                     8.1.3           win_pyhd8ed1ab_2    conda-forge
cloudpickle               2.2.0              pyhd8ed1ab_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
comm                      0.1.2              pyhd8ed1ab_0    conda-forge
commonmark                0.9.1                      py_0    conda-forge
cookiecutter              2.1.1              pyh6c4a22f_0    conda-forge
cryptography              38.0.4           py39hb6bd5e6_0    conda-forge
cytoolz                   0.12.0           py39ha55989b_1    conda-forge
dask                      2022.12.1          pyhd8ed1ab_0    conda-forge
dask-core                 2022.12.1          pyhd8ed1ab_0    conda-forge
dataclasses               0.8                pyhc8e2a94_3    conda-forge
dav1d                     1.0.0                h8ffe710_1    conda-forge
debugpy                   1.6.4            py39h99910a6_0    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
diff-match-patch          20200713           pyh9f0ad1d_0    conda-forge
dill                      0.3.6              pyhd8ed1ab_1    conda-forge
distributed               2022.12.1          pyhd8ed1ab_0    conda-forge
docstring-to-markdown     0.11               pyhd8ed1ab_0    conda-forge
docstring_parser          0.15               pyhd8ed1ab_0    conda-forge
docutils                  0.19             py39hcbf5309_1    conda-forge
entrypoints               0.4                pyhd8ed1ab_0    conda-forge
fasteners                 0.17.3             pyhd8ed1ab_0    conda-forge
flake8                    5.0.4              pyhd8ed1ab_0    conda-forge
freetype                  2.12.1               h546665d_1    conda-forge
freetype-py               2.3.0              pyhd8ed1ab_0    conda-forge
fsspec                    2022.11.0          pyhd8ed1ab_0    conda-forge
future                    0.18.2             pyhd8ed1ab_6    conda-forge
gettext                   0.21.1               h5728263_0    conda-forge
giflib                    5.2.1                h8d14728_2    conda-forge
glib                      2.74.1               h12be248_1    conda-forge
glib-tools                2.74.1               h12be248_1    conda-forge
gst-plugins-base          1.21.3               h001b923_1    conda-forge
gstreamer                 1.21.3               h6b5321d_1    conda-forge
heapdict                  1.0.1                      py_0    conda-forge
hsluv                     5.0.2              pyh44b312d_0    conda-forge
icu                       70.1                 h0e60522_0    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
imagecodecs               2022.12.24       py39h17e3817_0    conda-forge
imageio                   2.23.0             pyhfa7a67d_0    conda-forge
imagesize                 1.4.1              pyhd8ed1ab_0    conda-forge
importlib-metadata        5.2.0              pyha770c72_0    conda-forge
importlib_metadata        5.2.0                hd8ed1ab_0    conda-forge
importlib_resources       5.10.1             pyhd8ed1ab_1    conda-forge
inflection                0.5.1              pyh9f0ad1d_0    conda-forge
intel-openmp              2023.0.0         h57928b3_25922    conda-forge
intervaltree              3.0.2                      py_0    conda-forge
ipykernel                 6.19.4             pyh025b116_0    conda-forge
ipython                   7.33.0           py39hcbf5309_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
isort                     5.11.4             pyhd8ed1ab_0    conda-forge
jaraco.classes            3.2.3              pyhd8ed1ab_0    conda-forge
jedi                      0.18.2             pyhd8ed1ab_0    conda-forge
jellyfish                 0.9.0            py39ha55989b_2    conda-forge
jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
jinja2-time               0.2.0              pyhd8ed1ab_3    conda-forge
jpeg                      9e                   h8ffe710_2    conda-forge
jsonschema                4.17.3             pyhd8ed1ab_0    conda-forge
jupyter_client            7.4.8              pyhd8ed1ab_0    conda-forge
jupyter_core              5.1.0            py39hcbf5309_0    conda-forge
jupyterlab_pygments       0.2.2              pyhd8ed1ab_0    conda-forge
jxrlib                    1.1                  h8ffe710_2    conda-forge
keyring                   23.13.1          py39hcbf5309_0    conda-forge
kiwisolver                1.4.4            py39h1f6ef14_1    conda-forge
krb5                      1.20.1               heb0366b_0    conda-forge
lazy-object-proxy         1.8.0            py39ha55989b_0    conda-forge
lcms2                     2.14                 ha5c8aab_1    conda-forge
lerc                      4.0.0                h63175ca_0    conda-forge
libaec                    1.0.6                h39d44d4_0    conda-forge
libavif                   0.11.1               h8f5c5bc_0    conda-forge
libblas                   3.9.0              16_win64_mkl    conda-forge
libbrotlicommon           1.0.9                hcfcfb64_8    conda-forge
libbrotlidec              1.0.9                hcfcfb64_8    conda-forge
libbrotlienc              1.0.9                hcfcfb64_8    conda-forge
libcblas                  3.9.0              16_win64_mkl    conda-forge
libclang                  15.0.6          default_h77d9078_0    conda-forge
libclang13                15.0.6          default_h77d9078_0    conda-forge
libcurl                   7.87.0               h68f0423_0    conda-forge
libdeflate                1.14                 hcfcfb64_0    conda-forge
libffi                    3.4.2                h8ffe710_5    conda-forge
libglib                   2.74.1               he8f3873_1    conda-forge
libhwloc                  2.8.0                h039e092_1    conda-forge
libiconv                  1.17                 h8ffe710_0    conda-forge
liblapack                 3.9.0              16_win64_mkl    conda-forge
libogg                    1.3.4                h8ffe710_1    conda-forge
libpng                    1.6.39               h19919ed_0    conda-forge
libsodium                 1.0.18               h8d14728_1    conda-forge
libspatialindex           1.9.3                h39d44d4_4    conda-forge
libsqlite                 3.40.0               hcfcfb64_0    conda-forge
libssh2                   1.10.0               h9a1e1f7_3    conda-forge
libtiff                   4.5.0                hc4f729c_0    conda-forge
libvorbis                 1.3.7                h0e60522_0    conda-forge
libwebp                   1.2.4                hcfcfb64_1    conda-forge
libwebp-base              1.2.4                h8ffe710_0    conda-forge
libxcb                    1.13              hcd874cb_1004    conda-forge
libxml2                   2.10.3               hc3477c8_0    conda-forge
libzlib                   1.2.13               hcfcfb64_4    conda-forge
libzopfli                 1.0.3                h0e60522_0    conda-forge
locket                    1.0.0              pyhd8ed1ab_0    conda-forge
lz4                       4.0.2            py39hf617134_0    conda-forge
lz4-c                     1.9.3                h8ffe710_1    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
magicgui                  0.6.1              pyhd8ed1ab_0    conda-forge
markupsafe                2.1.1            py39ha55989b_2    conda-forge
matplotlib-inline         0.1.6              pyhd8ed1ab_0    conda-forge
mccabe                    0.7.0              pyhd8ed1ab_0    conda-forge
mistune                   2.0.4              pyhd8ed1ab_0    conda-forge
mkl                       2022.1.0           h6a75c08_874    conda-forge
more-itertools            9.0.0              pyhd8ed1ab_0    conda-forge
msgpack-python            1.0.4            py39h1f6ef14_1    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
mypy_extensions           0.4.3            py39hcbf5309_6    conda-forge
napari                    0.4.16          pyh275ddea_0_pyqt    conda-forge
napari-console            0.0.7              pyhd8ed1ab_0    conda-forge
napari-plugin-engine      0.2.0              pyhd8ed1ab_2    conda-forge
napari-svg                0.1.6              pyhd8ed1ab_0    conda-forge
nbclient                  0.7.2              pyhd8ed1ab_0    conda-forge
nbconvert                 7.2.7              pyhd8ed1ab_0    conda-forge
nbconvert-core            7.2.7              pyhd8ed1ab_0    conda-forge
nbconvert-pandoc          7.2.7              pyhd8ed1ab_0    conda-forge
nbformat                  5.7.1              pyhd8ed1ab_0    conda-forge
nest-asyncio              1.5.6              pyhd8ed1ab_0    conda-forge
networkx                  2.8.8              pyhd8ed1ab_0    conda-forge
npe2                      0.6.1              pyhd8ed1ab_1    conda-forge
numcodecs                 0.11.0           py39h99910a6_1    conda-forge
numpy                     1.24.0           py39hbccbffa_0    conda-forge
numpydoc                  1.5.0              pyhd8ed1ab_0    conda-forge
openjpeg                  2.5.0                ha2aaf27_2    conda-forge
openssl                   3.0.7                hcfcfb64_1    conda-forge
packaging                 22.0               pyhd8ed1ab_0    conda-forge
pandas                    1.5.2            py39h2ba5b7c_0    conda-forge
pandoc                    2.19.2               h57928b3_1    conda-forge
pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
paramiko                  2.12.0             pyhd8ed1ab_0    conda-forge
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
partd                     1.3.0              pyhd8ed1ab_0    conda-forge
pathspec                  0.10.3             pyhd8ed1ab_0    conda-forge
pcre2                     10.40                h17e33f8_0    conda-forge
pep517                    0.13.0             pyhd8ed1ab_0    conda-forge
pexpect                   4.8.0              pyh1a96a4e_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    9.2.0            py39hcebd2be_4    conda-forge
pint                      0.20.1             pyhd8ed1ab_0    conda-forge
pip                       22.3.1             pyhd8ed1ab_0    conda-forge
pkgutil-resolve-name      1.3.10             pyhd8ed1ab_0    conda-forge
platformdirs              2.6.0              pyhd8ed1ab_0    conda-forge
pluggy                    1.0.0              pyhd8ed1ab_5    conda-forge
ply                       3.11                       py_1    conda-forge
pooch                     1.6.0              pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.36             pyha770c72_0    conda-forge
psutil                    5.9.4            py39ha55989b_0    conda-forge
psygnal                   0.6.1            py39h1f6ef14_0    conda-forge
pthread-stubs             0.4               hcd874cb_1001    conda-forge
pthreads-win32            2.9.1                hfa6e2cd_3    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pycodestyle               2.9.1              pyhd8ed1ab_0    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pydantic                  1.10.3           py39ha55989b_0    conda-forge
pydocstyle                6.1.1              pyhd8ed1ab_0    conda-forge
pyflakes                  2.5.0              pyhd8ed1ab_0    conda-forge
pygments                  2.13.0             pyhd8ed1ab_0    conda-forge
pylint                    2.15.9             pyhd8ed1ab_0    conda-forge
pylint-venv               2.3.0              pyhd8ed1ab_0    conda-forge
pyls-spyder               0.4.0              pyhd8ed1ab_0    conda-forge
pynacl                    1.5.0            py39h09fa780_2    conda-forge
pyopengl                  3.1.6              pyhd8ed1ab_1    conda-forge
pyopenssl                 22.1.0             pyhd8ed1ab_0    conda-forge
pyqt                      5.15.7           py39hb77abff_2    conda-forge
pyqt5-sip                 12.11.0          py39h99910a6_2    conda-forge
pyqtwebengine             5.15.7           py39hb77abff_2    conda-forge
pyrsistent                0.19.2           py39ha55989b_0    conda-forge
pysocks                   1.7.1              pyh0701188_6    conda-forge
python                    3.9.15          h4de0772_0_cpython    conda-forge
python-build              0.9.0              pyhd8ed1ab_1    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-fastjsonschema     2.16.2             pyhd8ed1ab_0    conda-forge
python-lsp-black          1.2.1              pyhd8ed1ab_0    conda-forge
python-lsp-jsonrpc        1.0.0              pyhd8ed1ab_0    conda-forge
python-lsp-server         1.6.0                hd8ed1ab_0    conda-forge
python-lsp-server-base    1.6.0              pyhd8ed1ab_0    conda-forge
python-slugify            7.0.0              pyhd8ed1ab_0    conda-forge
python_abi                3.9                      3_cp39    conda-forge
pytomlpp                  1.0.11           py39h1f6ef14_1    conda-forge
pytoolconfig              1.2.4              pyhd8ed1ab_1    conda-forge
pytz                      2022.7             pyhd8ed1ab_0    conda-forge
pywavelets                1.3.0            py39hc266a54_2    conda-forge
pywin32                   304              py39h99910a6_2    conda-forge
pywin32-ctypes            0.2.0           py39hcbf5309_1006    conda-forge
pyyaml                    6.0              py39ha55989b_5    conda-forge
pyzmq                     24.0.1           py39hea35a22_1    conda-forge
qdarkstyle                3.0.3              pyhd8ed1ab_0    conda-forge
qstylizer                 0.2.2              pyhd8ed1ab_0    conda-forge
qt-main                   5.15.6               h9580fe5_5    conda-forge
qt-webengine              5.15.4               h0bdee70_3    conda-forge
qtawesome                 1.2.2              pyhd8ed1ab_0    conda-forge
qtconsole                 5.4.0              pyhd8ed1ab_0    conda-forge
qtconsole-base            5.4.0              pyha770c72_0    conda-forge
qtpy                      2.3.0              pyhd8ed1ab_0    conda-forge
requests                  2.28.1             pyhd8ed1ab_1    conda-forge
rich                      12.6.0             pyhd8ed1ab_0    conda-forge
rope                      1.6.0              pyhd8ed1ab_0    conda-forge
rtree                     1.0.1            py39h09fdee3_1    conda-forge
scikit-image              0.19.3           py39h2ba5b7c_2    conda-forge
scipy                     1.9.3            py39hfbf2dce_2    conda-forge
setuptools                65.6.3             pyhd8ed1ab_0    conda-forge
shellingham               1.5.0              pyhd8ed1ab_0    conda-forge
sip                       6.7.5            py39h99910a6_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
snappy                    1.1.9                hfb803bf_2    conda-forge
snowballstemmer           2.2.0              pyhd8ed1ab_0    conda-forge
sortedcontainers          2.4.0              pyhd8ed1ab_0    conda-forge
soupsieve                 2.3.2.post1        pyhd8ed1ab_0    conda-forge
sphinx                    5.3.0              pyhd8ed1ab_0    conda-forge
sphinxcontrib-applehelp   1.0.2                      py_0    conda-forge
sphinxcontrib-devhelp     1.0.2                      py_0    conda-forge
sphinxcontrib-htmlhelp    2.0.0              pyhd8ed1ab_0    conda-forge
sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
sphinxcontrib-qthelp      1.0.3                      py_0    conda-forge
sphinxcontrib-serializinghtml 1.1.5              pyhd8ed1ab_2    conda-forge
spyder                    5.4.0            py39hcbf5309_0    conda-forge
spyder-kernels            2.4.0           win_pyhd8ed1ab_1    conda-forge
superqt                   0.4.1              pyhd8ed1ab_0    conda-forge
tbb                       2021.7.0             h91493d7_1    conda-forge
tblib                     1.7.0              pyhd8ed1ab_0    conda-forge
text-unidecode            1.3                        py_0    conda-forge
textdistance              4.5.0              pyhd8ed1ab_0    conda-forge
three-merge               0.1.1              pyh9f0ad1d_0    conda-forge
tifffile                  2022.10.10         pyhd8ed1ab_0    conda-forge
tinycss2                  1.2.1              pyhd8ed1ab_0    conda-forge
tk                        8.6.12               h8ffe710_0    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
tomlkit                   0.11.6             pyha770c72_0    conda-forge
toolz                     0.12.0             pyhd8ed1ab_0    conda-forge
tornado                   6.2              py39ha55989b_1    conda-forge
tqdm                      4.64.1             pyhd8ed1ab_0    conda-forge
traitlets                 5.8.0              pyhd8ed1ab_0    conda-forge
typer                     0.7.0              pyhd8ed1ab_0    conda-forge
typing                    3.10.0.0           pyhd8ed1ab_0    conda-forge
typing-extensions         4.4.0                hd8ed1ab_0    conda-forge
typing_extensions         4.4.0              pyha770c72_0    conda-forge
tzdata                    2022g                h191b570_0    conda-forge
ucrt                      10.0.22621.0         h57928b3_0    conda-forge
ujson                     5.5.0            py39h99910a6_1    conda-forge
unidecode                 1.3.6              pyhd8ed1ab_0    conda-forge
urllib3                   1.26.13            pyhd8ed1ab_0    conda-forge
vc                        14.3                 h3d8a991_9    conda-forge
vispy                     0.10.0           py39h5d4886f_0    conda-forge
vs2015_runtime            14.32.31332          h1d6e394_9    conda-forge
watchdog                  2.2.0            py39hcbf5309_0    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                      py_1    conda-forge
whatthepatch              1.0.3              pyhd8ed1ab_0    conda-forge
wheel                     0.38.4             pyhd8ed1ab_0    conda-forge
win_inet_pton             1.1.0              pyhd8ed1ab_6    conda-forge
wrapt                     1.14.1           py39ha55989b_1    conda-forge
xorg-libxau               1.0.9                hcd874cb_0    conda-forge
xorg-libxdmcp             1.1.3                hcd874cb_0    conda-forge
xz                        5.2.6                h8d14728_0    conda-forge
yaml                      0.2.5                h8ffe710_2    conda-forge
yapf                      0.32.0             pyhd8ed1ab_0    conda-forge
zarr                      2.13.3             pyhd8ed1ab_0    conda-forge
zeromq                    4.3.4                h0e60522_1    conda-forge
zfp                       1.0.0                h63175ca_3    conda-forge
zict                      2.2.0              pyhd8ed1ab_0    conda-forge
zipp                      3.11.0             pyhd8ed1ab_0    conda-forge
zlib-ng                   2.0.6                h8ffe710_0    conda-forge
zstd                      1.5.2                h7755175_4    conda-forge
```

</details>

While running the code with Spyder on that env no traceback was produced (the env has Spyder 5.4.0 and Napari 0.4.16 installed). Regarding the behavior of the size slider/color selector, seems like you need to first do a selection (even though the layer controls seems like its showing the values for a specific point actually there are no points selected):

![example_slim](https://user-images.githubusercontent.com/16781833/209997529-23cfa9fe-2152-4d17-a75d-6455e857c122.gif)

Also, checked launching the code from a standalone IPython console from the same env and the behavior seems like is the same (the layer controls shows the size and color for a point but there is no update if you change the values unless you actually select a point).

**Comment by Czaki** [comment]
Yes, you need to select the point to change its parameters. Otherwise, you will change the parameters of the next point that will be added.

**Comment by psobolewskiPhD** [comment]
@jo-mueller I'm going to close this, but if it's still occurring with 0.4.17 (or 0.4.18rc) do let us know
