### ISSUE TITLE
Uninstallation of plugins on Windows may fail if the plugin was previously loaded

### ISSUE THREAD

**Issue by haesleinhuepf** [napari/napari#3510]
## 🐛 Bug

Hi all,

I just installed and uninstalled two plugins (~~napari-live-recording~~ (edit: I can't reproduce it with this one) and napari-zelda). Afterwards, there is an error for both in the `Plugins > Plugin errors...` dialog. (see message below)

## To Reproduce

1. Setup a fresh conda environment
2. `pip install napari[all]`
3. Start `napari`
4. Install napari-zelda from the menu Plugins > Install/uninstall plugins.
5. Restart napari
6. Uninstall napari-zelda from the menu Plugins > Install/uninstall plugins.
7. Restart napari
8. Check the errors in Plugins > Plugin errors...

```
========================= Errors for plugin 'napari-zelda' =========================

napari version: 0.4.12
plugin package: napari-zelda
version: 0.1.2
module: 


ERROR #1: Error in plugin 'napari-zelda', hook 'napari_experimental_provide_dock_widget': No module named 'napari_zelda.napari_zelda' 

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
    [... skipping hidden 1 frame]

~\miniconda3\envs\bio_38\lib\site-packages\napari_plugin_engine\implementation.py in __call__(self=, *args=())
     65     def __call__(self, *args):
---> 66         return self.function(*args)
        self.function = 
        args = ()
     67 

~\miniconda3\envs\bio_38\lib\site-packages\napari_zelda\__init__.py in napari_experimental_provide_dock_widget()
     10 def napari_experimental_provide_dock_widget():
---> 11     from .napari_zelda import launch_ZELDA
        global napari_zelda = undefined
        launch_ZELDA = undefined
     12     return launch_ZELDA

ModuleNotFoundError: No module named 'napari_zelda.napari_zelda'

The above exception was the direct cause of the following exception:

PluginCallError                           Traceback (most recent call last)
PluginCallError: Error in plugin 'napari-zelda', hook 'napari_experimental_provide_dock_widget': No module named 'napari_zelda.napari_zelda'
================================================================================
```

Furthermore, after uninstalling the plugin, it still shows up in the Plugin installer, but without authors and suggesting to update:
![image](https://user-images.githubusercontent.com/12660498/138477361-72f36f97-61a1-4527-8013-aed6dd0da341.png)

## Expected behavior

Uninstalling a plugin should actually remove it entirely.

## Environment

 - Please copy and paste the information at napari info option in help menubar here:

```
napari: 0.4.12
Platform: Windows-10-10.0.19042-SP0
Python: 3.8.12 | packaged by conda-forge | (default, Oct 12 2021, 21:19:05) [MSC v.1916 64 bit (AMD64)]
Qt: 5.15.2
PyQt5: 5.15.5
NumPy: 1.21.3
SciPy: 1.7.1
Dask: 2021.09.1
VisPy: 0.9.2

OpenGL:
- GL version: 4.6.14761 Compatibility Profile Context 21.30.02.01 30.0.13002.1001
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1920x1200, scale 1.0

Plugins:
- Measurements (Plot profile): 0.1.6
- Measurements (skimage regionprops): 0.1.7
- PlatyMatch: 0.0.3
- Search (Plugin): 0.1.1
- Segment (blobs and things with membranes): 0.2.2
- Segmentation (Accelerated Pixel and Object Classification): 0.5.4
- Segmentation (split/merge): 0.1.3
- Utilities (skimage regionprops): 0.1.7
- Visualization(B/C): 0.1.3
- aicsimageio-in-memory: 0.4.1
- aicsimageio-out-of-memory: 0.4.1
- animation: 0.0.2
- clEsperanto: 0.10.3
- console: 0.0.4
- devbio: 0.1.4
- napari-folder-browser: 0.1.2
- napari-itk-io: 0.1.0
- napari-ome-zarr: 0.3.0
- napari-tools-menu: 0.1.3
- napari-zelda: 0.1.2
- ome-types: 0.2.9
- scikit-image: 0.4.12
- svg: 0.1.5
```

 - Any other relevant information:

**Comment by haesleinhuepf** [comment]
One more aspect: The folder where napari-zelda was installed still exists:
![image](https://user-images.githubusercontent.com/12660498/138478245-805c7a65-e43a-41f6-ac6b-d12b7b417448.png)

but contains half only [of the plugin](https://github.com/RoccoDAnt/napari-zelda/tree/main/napari_zelda):
![image](https://user-images.githubusercontent.com/12660498/138478111-bffabe2d-a06f-4083-bf7a-53ab6b31f01f.png)

**Comment by tlambert03** [comment]
hmm... just gave this a try and wasn't able to reproduce (it installed fine, I restarted, it uninstalled fine, restarted it was gone).

> The folder where napari-zelda was installed still exists:

~aha! this is the key detail... can you try to figure out where your "real" site-packages folder lives?  Looks like this installed into the wrong place for you... might be a  snafu on our windows environment awareness, but it also might be an idiosyncrasy of your environment... hard to say at the moment~

edit: the error you found in https://github.com/napari/napari/issues/3510#issuecomment-949723621 is the real key :)

**Comment by haesleinhuepf** [comment]
> but it also might be an idiosyncrasy of your environment... hard to say at the moment

The conda installation is less than two hours old 😄

**Comment by tlambert03** [comment]
no no, I don't necessarily mean your conda installation, I mean something more global to your machine about where pip installs things (reminder, the built in installer uses pip, not conda)

**Comment by haesleinhuepf** [comment]
Ok, likely it has something to do with this:
![image](https://user-images.githubusercontent.com/12660498/138479183-bb1f2761-ea34-44ca-8973-c0f0c0babe0f.png)

**Comment by tlambert03** [comment]
trying now on PC

**Comment by haesleinhuepf** [comment]
Ok, 
* I deleted the four marked folders above.
* Then started napari
* Installed napari-zelda
* Restarted napari
* Uninstalled napari-zelda

And when clicking on "show status" I can read this error:
```
Found existing installation: napari-zelda 0.1.2

Uninstalling napari-zelda-0.1.2:

ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\rober\miniconda3\envs\bio_38\lib\shutil.py", line 791, in move
    os.rename(src, real_dst)
PermissionError: [WinError 5] Access is denied: 'c:\\users\\rober\\miniconda3\\envs\\bio_38\\lib\\site-packages\\napari_zelda\\' -> 'C:\\Users\\rober\\miniconda3\\envs\\bio_38\\Lib\\site-packages\\~apari_zelda'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\rober\miniconda3\envs\bio_38\lib\site-packages\pip\_internal\cli\base_command.py", line 164, in exc_logging_wrapper
    status = run_func(*args)
  File "C:\Users\rober\miniconda3\envs\bio_38\lib\site-packages\pip\_internal\commands\uninstall.py", line 97, in run
    uninstall_pathset = req.uninstall(
  File "C:\Users\rober\miniconda3\envs\bio_38\lib\site-packages\pip\_internal\req\req_install.py", line 696, in uninstall
    uninstalled_pathset.remove(auto_confirm, verbose)
  File "C:\Users\rober\miniconda3\envs\bio_38\lib\site-packages\pip\_internal\req\req_uninstall.py", line 384, in remove
    moved.stash(path)
  File "C:\Users\rober\miniconda3\envs\bio_38\lib\site-packages\pip\_internal\req\req_uninstall.py", line 282, in stash
    renames(path, new_path)
  File "C:\Users\rober\miniconda3\envs\bio_38\lib\site-packages\pip\_internal\utils\misc.py", line 307, in renames
    shutil.move(old, new)
  File "C:\Users\rober\miniconda3\envs\bio_38\lib\shutil.py", line 809, in move
    rmtree(src)
  File "C:\Users\rober\miniconda3\envs\bio_38\lib\shutil.py", line 740, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Users\rober\miniconda3\envs\bio_38\lib\shutil.py", line 618, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Users\rober\miniconda3\envs\bio_38\lib\shutil.py", line 616, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'c:\\users\\rober\\miniconda3\\envs\\bio_38\\lib\\site-packages\\napari_zelda\\protocols_dict.json'
```

And afterwards these zombie-installations are back:
![image](https://user-images.githubusercontent.com/12660498/138479630-5c354e47-7421-480a-b464-1fcd52e8673e.png)

Thus, this error might be related or duplicate to https://github.com/napari/napari/issues/3223

**Comment by haesleinhuepf** [comment]
I think on (some) Windows, you cannot uninstall python packages when they are in use...

**Comment by haesleinhuepf** [comment]
Might this mean the error could go away with the new `npe2`... as packages are not loaded at startup? =-)

**Comment by tlambert03** [comment]
great, I think what you found in https://github.com/napari/napari/issues/3510#issuecomment-949723621 is the key.  and you're probably right that Windows doesn't let us remove a file that is in use... _and_ it looks like napari-zelda uses `open()` outside of a context manager and never closes the file:

https://github.com/RoccoDAnt/napari-zelda/blob/3e7455457e37fd4bac60557ea0d86aeae14632bd/napari_zelda/napari_zelda.py#L33

> Might this mean the error could go away with the new npe2... as packages are not loaded at startup? =-)

Unfortunately, this would only work in npe2 if no one loads the zelda dock widget, but once they do, _then_ [this function](https://github.com/RoccoDAnt/napari-zelda/blob/3e7455457e37fd4bac60557ea0d86aeae14632bd/napari_zelda/__init__.py#L10-L12) would be called, `.napari_zelda` would be imported, and the file handle would dangle and we'd be back where we are.

The best short term solution here is a PR to napari_zelda to help clean up the open resource after the json is extracted.

on the napari side, I'm not sure that there's anything we can (safely) do to cleanup/delete an actively open file on windows, but it would be nice if our uninstaller were more atomic, so that it would at least revert to an installed state when an error occurs, telling you to uninstall manually with napari closed

**Comment by haesleinhuepf** [comment]
> on the napari side, I'm not sure that there's anything we can (safely) do to

After npe2 is released and in use routinely, one could check if a plugin was loaded and then error "Please restart napari to uninstall this plugin"; potentially on Windows only...

**Comment by jaimergp** [comment]
This potential pitfall is mentioned in the NAP2; I am both glad and sad there's a concrete example in the wild.

The solution on Windows is to schedule the uninstallation for the next napari start-up (before napari itself loads). With conda environments this can be achieved via ephemeral activation scripts, but I am not sure if we can do this in other virtual environment types.

May I suggest we rename this issue to something like "Uninstallation of plugins on Windows may fail if the plugin was previously loaded"?

**Comment by tlambert03** [comment]
changed, thanks
