### ISSUE TITLE
bug creating thumbnail for rgb tiff

### ISSUE THREAD

**Issue by tlambert03** [napari/napari#3581]
## 🐛 Bug
haven't had the time to dig into it yet, but loading this tiff from the cellpose test data causes an exception in thumbnail creation (i think it has to do with it being an RGB tiff):

https://www.dropbox.com/s/93fqj6usq26u980/000_img.tif?dl=0

```
Traceback (most recent call last):
  File "/Users/talley/Dropbox (HMS)/Python/forks/napari/napari/_qt/qt_viewer.py", line 947, in dropEvent
    self.viewer.open(filenames, stack=bool(shift_down))
  File "/Users/talley/Dropbox (HMS)/Python/forks/napari/napari/components/viewer_model.py", line 857, in open
    self._add_layers_with_plugins(
  File "/Users/talley/Dropbox (HMS)/Python/forks/napari/napari/components/viewer_model.py", line 930, in _add_layers_with_plugins
    added.extend(self._add_layer_from_data(*_data))
  File "/Users/talley/Dropbox (HMS)/Python/forks/napari/napari/components/viewer_model.py", line 1004, in _add_layer_from_data
    layer = add_method(data, **(meta or {}))
  File "/Users/talley/Dropbox (HMS)/Python/forks/napari/napari/components/viewer_model.py", line 695, in add_image
    layer = Image(data, **kwargs)
  File "/Users/talley/Dropbox (HMS)/Python/forks/napari/napari/layers/image/image.py", line 290, in __init__
    self._update_dims()
  File "/Users/talley/Dropbox (HMS)/Python/forks/napari/napari/layers/base/base.py", line 570, in _update_dims
    self.refresh()
  File "/Users/talley/Dropbox (HMS)/Python/forks/napari/napari/layers/base/base.py", line 974, in refresh
    self._update_thumbnail()
  File "/Users/talley/Dropbox (HMS)/Python/forks/napari/napari/layers/image/image.py", line 740, in _update_thumbnail
    self.thumbnail = colormapped
  File "/Users/talley/Dropbox (HMS)/Python/forks/napari/napari/layers/base/base.py", line 735, in thumbnail
    thumbnail = np.pad(thumbnail, pad_amounts, mode='constant')
  File "<__array_function__ internals>", line 5, in pad
  File "/Users/talley/miniconda3/envs/napdev/lib/python3.9/site-packages/numpy/lib/arraypad.py", line 743, in pad
    pad_width = _as_pairs(pad_width, array.ndim, as_index=True)
  File "/Users/talley/miniconda3/envs/napdev/lib/python3.9/site-packages/numpy/lib/arraypad.py", line 514, in _as_pairs
    raise ValueError("index can't contain negative values")
```

```py
> /Users/talley/Dropbox (HMS)/Python/forks/napari/napari/layers/base/base.py(735)thumbnail()
    733         padding_needed = np.subtract(self._thumbnail_shape, thumbnail.shape)
    734         pad_amounts = [(p // 2, (p + 1) // 2) for p in padding_needed]
--> 735         thumbnail = np.pad(thumbnail, pad_amounts, mode='constant')
    736
    737         # blend thumbnail with opaque black background

ipdb> padding_needed
array([  31,    0, -509])
ipdb> self._thumbnail_shape
(32, 32, 4)
ipdb> thumbnail.shape
(1, 32, 513)
```

**Comment by stefanv** [comment]
EDIT: In my case, it was mistaken usage of `rgb=True` when the data had 50 channels. See also #3923 

I have the same issue, but it seems unrelated to TIFF. Reproduced with:

```
import napari
import numpy as np

image = np.random.random((1024, 1024, 50))
viewer = napari.view_image(image, rgb=True)
```

Confirmed on current main.

**Comment by tlambert03** [comment]
this is fixed in that a better error message is now given in #4630

```
ValueError: 'rgb' was set to True but data does not have suitable dimensions.
```
