### ISSUE TITLE
Test seem to be tearing down QApp when they should not ? 

### ISSUE THREAD

**Issue by Carreau** [napari/napari#3690]
Ok, this is fairly complex:

Apply this given patch:

```python
--- a/napari/conftest.py
+++ b/napari/conftest.py
@@ -376,3 +376,8 @@ if sys.version_info > (
             if dask.threaded.default_pool is not None:
                 dask.threaded.default_pool.shutdown()
                 dask.threaded.default_pool = None

+from IPython.core.history import HistoryManager
+
+HistoryManager.enabled = False
```
This will make IPython use one less thread, and not access disk during test.

And run this minimal test suite:

```
pytest 'napari/_tests/test_advanced.py::test_update_console' 'napari/_tests/test_examples.py::test_examples[interactive_move_point_3d.py]' 'napari/utils/_tests/test_magicgui.py::test_magicgui_add_threadworker'
```

You will get something along

```python
========================================================== FAILURES ==========================================================
_______________________________________________ test_magicgui_add_threadworker _______________________________________________

qtbot = <pytestqt.qtbot.QtBot object at 0x7fe15c8e0d60>
make_napari_viewer = <function make_napari_viewer.<locals>.actual_factory at 0x7fe1881d71f0>

    @pytest.mark.sync_only
    def test_magicgui_add_threadworker(qtbot, make_napari_viewer):
        """Test that annotating with FunctionWorker works."""
        from napari.qt.threading import FunctionWorker, thread_worker

        viewer = make_napari_viewer()
        DATA = np.random.rand(10, 10)

        @magicgui
        def add_data(x: int) -> FunctionWorker[types.ImageData]:
            @thread_worker(start_thread=False)
            def _slow():
                time.sleep(0.1)
                return DATA

            return _slow()

        viewer.window.add_dock_widget(add_data)

        assert len(viewer.layers) == 0
        worker = add_data()
        # normally you wouldn't start the worker outside of the mgui function
        # this is just to make testing with threads easier
        with qtbot.waitSignal(worker.finished):
>           worker.start()
E           pytestqt.exceptions.TimeoutError

napari/utils/_tests/test_magicgui.py:130: TimeoutError



================================================== short test summary info ===================================================
FAILED napari/utils/_tests/test_magicgui.py::test_magicgui_add_threadworker - pytestqt.exceptions.TimeoutError
========================================== 1 failed, 2 passed, 5 warnings in 2.14s ===========================================
Traceback (most recent call last):
  File "/Users/bussonniermatthias/miniconda3-intel/envs/napari/lib/python3.9/site-packages/superqt/utils/_qthreading.py", line 192, in run
    self.returned.emit(result)
  File "/Users/bussonniermatthias/miniconda3-intel/envs/napari/lib/python3.9/site-packages/superqt/utils/_qthreading.py", line 122, in __getattr__
    return getattr(self.signals, name)
RuntimeError: wrapped C/C++ object of type WorkerBaseSignals has been deleted

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/bussonniermatthias/miniconda3-intel/envs/napari/lib/python3.9/site-packages/superqt/utils/_qthreading.py", line 194, in run
    self.errored.emit(exc)
  File "/Users/bussonniermatthias/miniconda3-intel/envs/napari/lib/python3.9/site-packages/superqt/utils/_qthreading.py", line 122, in __getattr__
    return getattr(self.signals, name)
RuntimeError: wrapped C/C++ object of type WorkerBaseSignals has been deleted
Fatal Python error: Aborted

Current thread 0x0000000303e5a000 (most recent call first):
<no Python frame>

Thread 0x00000002011d4600 (most recent call first):
<no Python frame>
[1]    68941 abort      pytest 'napari/_tests/test_advanced.py::test_update_console'
```

Now if you _add_ or _remove_ tests, it might not be the case anymore. 

My understanding is that this is due to subtle interaction between a few things in many placed. 

1) test_example does:

```
@pytest.fixture
def qapp():
    from qtpy.QtCore import QTimer

    from napari._qt.qt_event_loop import get_app

    # it's important that we use get_app so that it connects to the
    # app.aboutToQuit.connect(wait_for_workers_to_quit)
    app = get_app()

    # quit examples that explicitly start the event loop with `napari.run()`
    # so that tests aren't waiting on a manual exit
    QTimer.singleShot(100, app.quit).  

    yield app
```

And so tries to quit the QApplication instance.

but 2) get_app seem to not be completely correct either:

```
def get_app(
...
    if not _ipython_has_eventloop():
        notification_manager.notification_ready.connect(
            NapariQtNotification.show_notification
        )
        notification_manager.notification_ready.connect(
            show_console_notification
        )

    if app.windowIcon().isNull():
        app.setWindowIcon(QIcon(kwargs.get('icon')))

    if ipy_interactive is None:
        ipy_interactive = get_settings().application.ipy_interactive
    if _IPYTHON_WAS_HERE_FIRST:
        _try_enable_ipython_gui('qt' if ipy_interactive else None)
```

Try to setup IPython event loop intergration if it was started before. Note that the conditional notification manager is wrong as the eventloop will be set later in the function.

3) quit_app seem to also have incorrect logic, and maybe should be used in test_examples ?

```
def quit_app():
    """Close all windows and quit the QApplication if napari started it."""
    QApplication.closeAllWindows()
    # if we started the application then the app will be named 'napari'.
    if (
        QApplication.applicationName() == 'napari'
        and not _ipython_has_eventloop()
    ):
        QApplication.quit()
....
```
It does things conditionally if IPython has event loop setup, but this my be incorrect as the eventloop might have been setup by something else than get_app... for example `test_advanced.py`...

and 4) `test_advanced.py`

```
@pytest.mark.filterwarnings("ignore::DeprecationWarning:jupyter_client")
def test_update_console(make_napari_viewer):
    """Test updating the console with local variables."""
    viewer = make_napari_viewer()
    view = viewer.window.qt_viewer

    # Check viewer in console
    assert view.console.kernel_client is not None
    assert 'viewer' in view.console.shell.user_ns
    assert view.console... # <- view.console is a property that setup an interactiveshell with qt integration
```

Which create an ipython instance after get_app is called, leading likely to weird teardown, and tricking next get_app call to belive we are running from within IPython and to not setup/teardown QApps, while definitely we should ? 

I'm not sure if the above make sens, and for whatever reason it is finicky on which other test you may be running.

I'm tempted to think that this may be related to mac slowness.

I can suggest to maybe run test_examples separately in another matrix element, maybe, but I'm wondering if a proper fix investigation is necessary.

**Comment by tlambert03** [comment]
interesting points.  I'm roughly following, and it definitely makes sense that it could all be relevant!

> I can suggest to maybe run test_examples separately in another matrix element, maybe, but I'm wondering if a proper fix investigation is necessary.

I think this is well worth a try.  I mean, even just skipping examples on CI altogether and seeing if it helps is a start.  (We used to do that, and we can go back there, if it's easier to make it independent of PR tests that fine)
