### ISSUE TITLE
PySide2 rcc binary not found

### ISSUE THREAD

**Issue by pskeshu** [napari/napari#3713]
I get this traceback when I try `viewer = napari.view_image(imgs, name="image")`

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dna/Documents/ndsys/technical/deepthought/deepthought/view.py", line 20, in view
    viewer = napari.view_image(imgs, name="image")
  File "/home/dna/.local/lib/python3.9/site-packages/napari/view_layers.py", line 6, in view_image
    function signature is a merged version of one of the ``Viewer.__init__`` method
  File "/home/dna/.local/lib/python3.9/site-packages/napari/viewer.py", line 52, in __init__
    self._window = Window(self, show=show)
  File "/home/dna/.local/lib/python3.9/site-packages/napari/_qt/qt_main_window.py", line 337, in __init__
    get_app()
  File "/home/dna/.local/lib/python3.9/site-packages/napari/_qt/qt_event_loop.py", line 182, in get_app
    _register_napari_resources()
  File "/home/dna/.local/lib/python3.9/site-packages/napari/_qt/qt_resources/_icons.py", line 359, in _register_napari_resources
    resources = _compile_napari_resources(save_path=persist and save_path)
  File "/home/dna/.local/lib/python3.9/site-packages/napari/_qt/qt_resources/_icons.py", line 319, in _compile_napari_resources
    output = compile_qrc(qrc)
  File "/home/dna/.local/lib/python3.9/site-packages/napari/_qt/qt_resources/_icons.py", line 225, in compile_qrc
    return _compile_qrc_pyside2(qrc).replace(b'PySide2', b'qtpy')
  File "/home/dna/.local/lib/python3.9/site-packages/napari/_qt/qt_resources/_icons.py", line 212, in _compile_qrc_pyside2
    raise RuntimeError(f"PySide2 rcc binary not found in {pyside_root}")
RuntimeError: PySide2 rcc binary not found in /usr/lib/python3.9/site-packages/PySide2

```

**Comment by pskeshu** [comment]
These are the binaries at `pyside_root` 

```ls /usr/lib/python3.9/site-packages/PySide2

_config.py
_git_pyside_version.py
__init__.py
Qt3DAnimation.cpython-39-x86_64-linux-gnu.so
Qt3DCore.cpython-39-x86_64-linux-gnu.so
Qt3DExtras.cpython-39-x86_64-linux-gnu.so
Qt3DInput.cpython-39-x86_64-linux-gnu.so
Qt3DLogic.cpython-39-x86_64-linux-gnu.so
Qt3DRender.cpython-39-x86_64-linux-gnu.so
QtCharts.cpython-39-x86_64-linux-gnu.so
QtConcurrent.cpython-39-x86_64-linux-gnu.so
QtCore.cpython-39-x86_64-linux-gnu.so
QtDataVisualization.cpython-39-x86_64-linux-gnu.so
QtGui.cpython-39-x86_64-linux-gnu.so
QtHelp.cpython-39-x86_64-linux-gnu.so
QtLocation.cpython-39-x86_64-linux-gnu.so
QtMultimedia.cpython-39-x86_64-linux-gnu.so
QtMultimediaWidgets.cpython-39-x86_64-linux-gnu.so
QtNetwork.cpython-39-x86_64-linux-gnu.so
QtOpenGL.cpython-39-x86_64-linux-gnu.so
QtOpenGLFunctions.cpython-39-x86_64-linux-gnu.so
QtPositioning.cpython-39-x86_64-linux-gnu.so
QtPrintSupport.cpython-39-x86_64-linux-gnu.so
QtQml.cpython-39-x86_64-linux-gnu.so
QtQuickControls2.cpython-39-x86_64-linux-gnu.so
QtQuick.cpython-39-x86_64-linux-gnu.so
QtQuickWidgets.cpython-39-x86_64-linux-gnu.so
QtRemoteObjects.cpython-39-x86_64-linux-gnu.so
QtScript.cpython-39-x86_64-linux-gnu.so
QtScriptTools.cpython-39-x86_64-linux-gnu.so
QtScxml.cpython-39-x86_64-linux-gnu.so
QtSensors.cpython-39-x86_64-linux-gnu.so
QtSerialPort.cpython-39-x86_64-linux-gnu.so
QtSql.cpython-39-x86_64-linux-gnu.so
QtSvg.cpython-39-x86_64-linux-gnu.so
QtTest.cpython-39-x86_64-linux-gnu.so
QtTextToSpeech.cpython-39-x86_64-linux-gnu.so
QtUiTools.cpython-39-x86_64-linux-gnu.so
QtWebChannel.cpython-39-x86_64-linux-gnu.so
QtWebEngineCore.cpython-39-x86_64-linux-gnu.so
QtWebEngine.cpython-39-x86_64-linux-gnu.so
QtWebEngineWidgets.cpython-39-x86_64-linux-gnu.so
QtWebSockets.cpython-39-x86_64-linux-gnu.so
QtWidgets.cpython-39-x86_64-linux-gnu.so
QtX11Extras.cpython-39-x86_64-linux-gnu.so
QtXml.cpython-39-x86_64-linux-gnu.so
QtXmlPatterns.cpython-39-x86_64-linux-gnu.so
```

**Comment by pskeshu** [comment]
interestingly, running napari in command line works. napari in interactive python interpreter seems fine too.

```Python 3.9.7 (default, Aug 31 2021, 13:28:12) 
[GCC 11.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import napari
>>> napari.Viewer()
Viewer(axes=Axes(visible=False, labels=True, colored=True, dashed=False, arrows=True), camera=Camera(center=(0.0, 0.0, 0.0), zoom=1.0, angles=(0.0, 0.0, 90.0), perspective=0.0, interactive=True), cursor=Cursor(position=(1.0, 1.0), scaled=True, size=1, style='standard'), dims=Dims(ndim=2, ndisplay=2, last_used=0, range=((0, 2, 1), (0, 2, 1)), current_step=(0, 0), order=(0, 1), axis_labels=('0', '1')), grid=GridCanvas(enabled=False, stride=1, shape=(-1, -1)), layers=[], scale_bar=ScaleBar(visible=False, colored=False, ticks=True, position='bottom_right', font_size=10.0, unit=None), text_overlay=TextOverlay(visible=False, color=array([1., 1., 1., 1.]), font_size=10.0, position='top_left', text=''), help='', status='Ready', theme='dark', title='napari', mouse_move_callbacks=[], mouse_drag_callbacks=[], mouse_wheel_callbacks=[<function dims_scroll at 0x7f343aa5caf0>], _persisted_mouse_event={}, _mouse_drag_gen={}, _mouse_wheel_gen={}, keymap={'Control-Shift-C': <bound method QtViewer.toggle_console_visibility of <napari._qt.qt_viewer.QtViewer object at 0x7f3432c2d4c0>>})
>>> 

```
