### ISSUE TITLE
napari crashes when attempting to display an array of zeros

### ISSUE THREAD

**Issue by royerloic** [napari/napari#375]
## 🐛 Bug

Napari crashes when clim slider is touched and an image layer
consisting only of zero values is displayed:
np.zeros((10, 10), dtype=float)
This is because of the min max values being the same and 
leading to a division by zero. 

The clim must be set to [0,1] by default if the min max values computed from the array are
identical. 

`  << caught exception here: >>
  File "/Users/royer/anaconda3/envs/pitl/lib/python3.7/site-packages/napari/util/event.py", line 523, in _invoke_callback
    cb(event)
  File "/Users/royer/anaconda3/envs/pitl/lib/python3.7/site-packages/napari/layers/_image_layer/view/controls.py", line 40, in clim_slider_update
    self.climSlider.setValues((slidermin, slidermax))
  File "/Users/royer/anaconda3/envs/pitl/lib/python3.7/site-packages/napari/_qt/range_slider/range_slider.py", line 103, in setValues
    self.updateDisplayValues()
  File "/Users/royer/anaconda3/envs/pitl/lib/python3.7/site-packages/napari/_qt/range_slider/range_slider.py", line 246, in updateDisplayValues
    range = int(size * (self.scale_min - self.start) / self.scale)
ValueError: cannot convert float NaN to integer
ERROR: Invoking <bound method QtImageControls.clim_slider_update of <napari.layers._image_layer.view.controls.QtImageControls object at 0x128a33d38>> for Event
WARNING: Traceback (most recent call last):
  File "/Users/royer/anaconda3/envs/pitl/lib/python3.7/site-packages/napari/_qt/range_slider/range_slider.py", line 148, in mouseMoveEvent
    self.updateScaleValues()
  File "/Users/royer/anaconda3/envs/pitl/lib/python3.7/site-packages/napari/_qt/range_slider/range_slider.py", line 263, in updateScaleValues
    self.updateDisplayValues()
  File "/Users/royer/anaconda3/envs/pitl/lib/python3.7/site-packages/napari/_qt/range_slider/range_slider.py", line 246, in updateDisplayValues
    range = int(size * (self.scale_min - self.start) / self.scale)
ValueError: cannot convert float NaN to integer`

## Environment

 - napari Version (e.g., 1.0): 0.0.9
 - OS (e.g., Linux): osx
 - Python version: 3.7
 - Any other relevant information: n/a

**Comment by sofroniewn** [comment]
noted - will fix
