### ISSUE TITLE
Unhandled exception in `napari_experimental_provide_function` depending on docstrings?

### ISSUE THREAD

**Issue by jo-mueller** [napari/napari#3865]
## 🐛 Bug

Helllo napari community, I stumbled over an unhandled exception when using `napari_experimental_provide_function` to create a magicgui plugin. Calling the plugin from the menu (not even executing it)  kills napari when one variable in the docstring is not named exactly like in the function definition. The console does not show any error tracebook so it is difficult to say what exactly triggers this.

See below for example to reproduce.

## To Reproduce

1. Create an empty cookiecutter plugin template for a function plugin
2. Modify plugin example a little. 

**This works:**

```Python
from typing import TYPE_CHECKING

from enum import Enum
import numpy as np
from napari_plugin_engine import napari_hook_implementation

if TYPE_CHECKING:
    import napari

@napari_hook_implementation
def napari_experimental_provide_function():
    # we can return a single function
    # or a tuple of (function, magicgui_options)
    # or a list of multiple functions with or without options, as shown here:
    return [threshold]


# 1.  First example, a simple function that thresholds an image and creates a labels layer
def threshold(data: "napari.types.ImageData", threshold: int) -> "napari.types.LabelsData":
    """

    Parameters
    ----------
    data: "napari.types.ImageData"
        DESCRIPTION.
    threshold : int
        DESCRIPTION.

    Returns
    -------
    TYPE
        DESCRIPTION.

    """

    return (data > threshold).astype(int)
```

3. Modifiy the docstring  

```
    Parameters
    ----------
    data: "napari.types.ImageData"
```
to 

```    
    Parameters
    ----------
    something: "napari.types.ImageData"
```

4. Open napari and click on the plugin entry from the menu. In my case, this crashes napari.

## Expected behavior

While I agree that docstrings should always refer to the correctly written variable name, it seems odd to me that the docstring is apparently parsed somehow and takes napari to the grave with it ^^"

## Environment

Napari info:
```
napari: 0.4.12
Platform: Windows-10-10.0.19042-SP0
Python: 3.8.12 (default, Oct 12 2021, 03:01:40) [MSC v.1916 64 bit (AMD64)]
Qt: 5.12.9
PyQt5: 5.12.3
NumPy: 1.21.5
SciPy: 1.7.3
Dask: 2021.12.0
VisPy: 0.9.4

OpenGL:
- GL version: 4.6.0 NVIDIA 496.13
- MAX_TEXTURE_SIZE: 32768

Screens:
- screen 1: resolution 2560x1440, scale 1.0
- screen 2: resolution 1080x1920, scale 1.0

Plugins:
- console: 0.0.4
- napari_test: 0.0.1
- scikit-image: 0.4.12
- svg: 0.1.5
```

Environment:
 ```
# Name                    Version                   Build  Channel
alabaster                 0.7.12                     py_0    conda-forge
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
arrow                     1.2.1                    pypi_0    pypi
asciitree                 0.3.3                      py_2    conda-forge
attrs                     21.2.0             pyhd8ed1ab_0    conda-forge
babel                     2.9.1              pyh44b312d_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
binaryornot               0.4.4                    pypi_0    pypi
blosc                     1.21.0               h0e60522_0    conda-forge
bokeh                     2.4.2            py38haa244fe_0    conda-forge
brotli                    1.0.9                h8ffe710_6    conda-forge
brotli-bin                1.0.9                h8ffe710_6    conda-forge
brotlipy                  0.7.0           py38h294d835_1003    conda-forge
bzip2                     1.0.8                h8ffe710_4    conda-forge
c-blosc2                  2.0.4                h09319c2_1    conda-forge
ca-certificates           2021.10.8            h5b45459_0    conda-forge
cachey                    0.2.1              pyh9f0ad1d_0    conda-forge
certifi                   2021.10.8        py38haa244fe_1    conda-forge
cffi                      1.15.0           py38hd8c33c5_0    conda-forge
cfitsio                   4.0.0                hd67004f_0    conda-forge
chardet                   4.0.0                    pypi_0    pypi
charls                    2.2.0                h39d44d4_0    conda-forge
charset-normalizer        2.0.9              pyhd8ed1ab_0    conda-forge
click                     8.0.3            py38haa244fe_1    conda-forge
cloudpickle               2.0.0              pyhd8ed1ab_0    conda-forge
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
cookiecutter              1.7.3                    pypi_0    pypi
cryptography              36.0.1           py38hb7941b4_0    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
cytoolz                   0.11.2           py38h294d835_1    conda-forge
dask                      2021.12.0          pyhd8ed1ab_0    conda-forge
dask-core                 2021.12.0          pyhd8ed1ab_0    conda-forge
debugpy                   1.5.1            py38h885f38d_0    conda-forge
decorator                 5.1.0              pyhd8ed1ab_0    conda-forge
distributed               2021.12.0        py38haa244fe_0    conda-forge
docstring_parser          0.13               pyhd8ed1ab_0    conda-forge
docutils                  0.15.2           py38haa244fe_3    conda-forge
entrypoints               0.3             pyhd8ed1ab_1003    conda-forge
fasteners                 0.16               pyhd8ed1ab_0    conda-forge
fonttools                 4.28.5           py38h294d835_0    conda-forge
freetype                  2.10.4               h546665d_1    conda-forge
freetype-py               2.2.0              pyh9f0ad1d_0    conda-forge
fsspec                    2021.11.1          pyhd8ed1ab_0    conda-forge
giflib                    5.2.1                h8d14728_2    conda-forge
heapdict                  1.0.1                      py_0    conda-forge
hsluv                     5.0.2              pyh44b312d_0    conda-forge
icu                       68.2                 h0e60522_0    conda-forge
idna                      3.3                      pypi_0    pypi
imagecodecs               2021.11.20       py38h84a8deb_1    conda-forge
imageio                   2.13.4             pyh239f2a4_0    conda-forge
imagesize                 1.3.0              pyhd8ed1ab_0    conda-forge
importlib-metadata        4.10.0           py38haa244fe_0    conda-forge
importlib_metadata        4.10.0               hd8ed1ab_0    conda-forge
importlib_resources       5.4.0              pyhd8ed1ab_0    conda-forge
intel-openmp              2021.4.0          h57928b3_3556    conda-forge
ipykernel                 6.4.1            py38haa95532_1
ipython                   7.30.1           py38haa244fe_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
jbig                      2.1               h8d14728_2003    conda-forge
jedi                      0.18.1           py38haa244fe_0    conda-forge
jinja2                    3.0.3              pyhd8ed1ab_0    conda-forge
jinja2-time               0.2.0                    pypi_0    pypi
jpeg                      9d                   h8ffe710_0    conda-forge
jsonschema                4.3.2              pyhd8ed1ab_0    conda-forge
jupyter_client            7.1.0              pyhd8ed1ab_0    conda-forge
jupyter_core              4.9.1            py38haa244fe_1    conda-forge
jxrlib                    1.1                  h8ffe710_2    conda-forge
kiwisolver                1.3.2            py38hbd9d945_1    conda-forge
krb5                      1.19.2               h20d022d_3    conda-forge
lcms2                     2.12                 h2a16943_0    conda-forge
lerc                      3.0                  h0e60522_0    conda-forge
libaec                    1.0.6                h39d44d4_0    conda-forge
libblas                   3.9.0              12_win64_mkl    conda-forge
libbrotlicommon           1.0.9                h8ffe710_6    conda-forge
libbrotlidec              1.0.9                h8ffe710_6    conda-forge
libbrotlienc              1.0.9                h8ffe710_6    conda-forge
libcblas                  3.9.0              12_win64_mkl    conda-forge
libclang                  11.1.0          default_h5c34c98_1    conda-forge
libcurl                   7.80.0               h789b8ee_1    conda-forge
libdeflate                1.8                  h8ffe710_0    conda-forge
liblapack                 3.9.0              12_win64_mkl    conda-forge
libpng                    1.6.37               h1d00b33_2    conda-forge
libsodium                 1.0.18               h8d14728_1    conda-forge
libssh2                   1.10.0               h680486a_2    conda-forge
libtiff                   4.3.0                hd413186_2    conda-forge
libwebp-base              1.2.1                h8ffe710_0    conda-forge
libzlib                   1.2.11            h8ffe710_1013    conda-forge
libzopfli                 1.0.3                h0e60522_0    conda-forge
locket                    0.2.0                      py_2    conda-forge
lz4-c                     1.9.3                h8ffe710_1    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
magicgui                  0.3.3              pyhd8ed1ab_0    conda-forge
markupsafe                2.0.1            py38h294d835_1    conda-forge
matplotlib-base           3.5.1            py38h1f000d6_0    conda-forge
matplotlib-inline         0.1.3              pyhd8ed1ab_0    conda-forge
mkl                       2021.4.0           h0e2418a_729    conda-forge
monotonic                 1.5                        py_0    conda-forge
msgpack-python            1.0.3            py38hbd9d945_0    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
napari                    0.4.12             pyhd8ed1ab_0    conda-forge
napari-console            0.0.4              pyhd8ed1ab_0    conda-forge
napari-plugin-engine      0.2.0              pyhd8ed1ab_2    conda-forge
napari-svg                0.1.5              pyhd8ed1ab_0    conda-forge
napari-test               0.0.1                     dev_0    <develop>
nest-asyncio              1.5.4              pyhd8ed1ab_0    conda-forge
networkx                  2.6.3              pyhd8ed1ab_1    conda-forge
numcodecs                 0.9.1            py38h885f38d_2    conda-forge
numpy                     1.21.5           py38hcf66579_0    conda-forge
numpydoc                  1.1.0                      py_1    conda-forge
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openjpeg                  2.4.0                hb211442_1    conda-forge
openssl                   1.1.1l               h8ffe710_0    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pandas                    1.3.5            py38h5d928e2_0    conda-forge
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
partd                     1.2.0              pyhd8ed1ab_0    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    8.4.0            py38h794f750_0    conda-forge
pint                      0.18               pyhd8ed1ab_0    conda-forge
pip                       21.2.2           py38haa95532_0
poyo                      0.5.0                    pypi_0    pypi
prompt-toolkit            3.0.24             pyha770c72_0    conda-forge
psutil                    5.8.0            py38h294d835_2    conda-forge
psygnal                   0.2.0            py38hbd9d945_1    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pydantic                  1.8.2            py38h294d835_2    conda-forge
pygments                  2.10.0             pyhd8ed1ab_0    conda-forge
pyopengl                  3.1.5                      py_0    conda-forge
pyopenssl                 21.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.6              pyhd8ed1ab_0    conda-forge
pyqt                      5.12.3           py38haa244fe_8    conda-forge
pyqt-impl                 5.12.3           py38h885f38d_8    conda-forge
pyqt5-sip                 4.19.18          py38h885f38d_8    conda-forge
pyqtchart                 5.12             py38h885f38d_8    conda-forge
pyqtwebengine             5.12.1           py38h885f38d_8    conda-forge
pyrsistent                0.18.0           py38h294d835_0    conda-forge
pysocks                   1.7.1            py38haa244fe_4    conda-forge
python                    3.8.12               h6244533_0
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-slugify            5.0.2                    pypi_0    pypi
python_abi                3.8                      2_cp38    conda-forge
pytz                      2021.3             pyhd8ed1ab_0    conda-forge
pywavelets                1.2.0            py38h6f4d8f0_1    conda-forge
pywin32                   302              py38h294d835_2    conda-forge
pyyaml                    6.0              py38h294d835_3    conda-forge
pyzmq                     22.3.0           py38h09162b1_1    conda-forge
qt                        5.12.9               h5909a2a_4    conda-forge
qtconsole                 5.2.2              pyhd8ed1ab_0    conda-forge
qtpy                      1.11.3             pyhd8ed1ab_0    conda-forge
requests                  2.26.0             pyhd8ed1ab_1    conda-forge
scikit-image              0.19.1           py38h5d928e2_0    conda-forge
scipy                     1.7.3            py38ha1292f7_0    conda-forge
setuptools                58.0.4           py38haa95532_0
six                       1.16.0             pyh6c4a22f_0    conda-forge
snappy                    1.1.8                ha925a31_3    conda-forge
snowballstemmer           2.2.0              pyhd8ed1ab_0    conda-forge
sortedcontainers          2.4.0              pyhd8ed1ab_0    conda-forge
sphinx                    4.3.2              pyh6c4a22f_0    conda-forge
sphinxcontrib-applehelp   1.0.2                      py_0    conda-forge
sphinxcontrib-devhelp     1.0.2                      py_0    conda-forge
sphinxcontrib-htmlhelp    2.0.0              pyhd8ed1ab_0    conda-forge
sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
sphinxcontrib-qthelp      1.0.3                      py_0    conda-forge
sphinxcontrib-serializinghtml 1.1.5              pyhd8ed1ab_1    conda-forge
sqlite                    3.36.0               h2bbff1b_0
superqt                   0.2.5.post1        pyhd8ed1ab_0    conda-forge
tbb                       2021.4.0             h2d74725_1    conda-forge
tblib                     1.7.0              pyhd8ed1ab_0    conda-forge
text-unidecode            1.3                      pypi_0    pypi
tifffile                  2021.11.2          pyhd8ed1ab_0    conda-forge
tk                        8.6.11               h8ffe710_1    conda-forge
toolz                     0.11.2             pyhd8ed1ab_0    conda-forge
tornado                   6.1              py38h294d835_2    conda-forge
tqdm                      4.62.3             pyhd8ed1ab_0    conda-forge
traitlets                 5.1.1              pyhd8ed1ab_0    conda-forge
typing-extensions         4.0.1                hd8ed1ab_0    conda-forge
typing_extensions         4.0.1              pyha770c72_0    conda-forge
unicodedata2              14.0.0           py38h294d835_0    conda-forge
urllib3                   1.26.7             pyhd8ed1ab_0    conda-forge
vc                        14.2                 h21ff451_1
vispy                     0.9.4            py38h6f4d8f0_0    conda-forge
vs2015_runtime            14.27.29016          h5e58377_2
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
wheel                     0.37.0             pyhd3eb1b0_1
win_inet_pton             1.1.0            py38haa244fe_3    conda-forge
wincertstore              0.2              py38haa95532_2
wrapt                     1.13.3           py38h294d835_1    conda-forge
xz                        5.2.5                h62dcd97_1    conda-forge
yaml                      0.2.5                he774522_0    conda-forge
zarr                      2.10.3             pyhd8ed1ab_0    conda-forge
zeromq                    4.3.4                h0e60522_1    conda-forge
zfp                       0.5.5                h0e60522_8    conda-forge
zict                      2.0.0                      py_0    conda-forge
zipp                      3.6.0              pyhd8ed1ab_0    conda-forge
zlib                      1.2.11            h8ffe710_1013    conda-forge
zstd                      1.5.0                h6255e5f_0    conda-forge
```

## Additional context

Thanks in advance for looking into it!

**Comment by tlambert03** [comment]
Thanks @jo-mueller, this is a magicgui bug (it uses docstrings to provide tooltips).    General tip when troubleshooting plugins: try to "remove" napari from it when possible.  In this case, all napari does with your function is call `magicgui.magicgui()` on it, so we can see the exact error here with:

```python
from magicgui import magicgui
magicgui(threshold).show(run=True)
```

```pytb
Traceback (most recent call last):
  File "/Users/talley/Dropbox (HMS)/Python/magicgui/x.py", line 31, in <module>
    magicgui(threshold).show(run=True)
  File "/Users/talley/Dropbox (HMS)/Python/magicgui/magicgui/_magicgui.py", line 90, in magicgui
    return _magicgui(**locals())
  File "/Users/talley/Dropbox (HMS)/Python/magicgui/magicgui/_magicgui.py", line 246, in _magicgui
    return inner_func(function)
  File "/Users/talley/Dropbox (HMS)/Python/magicgui/magicgui/_magicgui.py", line 241, in inner_func
    return magic_class(func, **kwargs)
  File "/Users/talley/Dropbox (HMS)/Python/magicgui/magicgui/widgets/_function_gui.py", line 148, in __init__
    _inject_tooltips_from_docstrings(function.__doc__, sig)
  File "/Users/talley/Dropbox (HMS)/Python/magicgui/magicgui/widgets/_function_gui.py", line 59, in _inject_tooltips_from_docstrings
    sig.parameters[argname].options.setdefault("tooltip", desc)
KeyError: 'something'
```

100% agree this should fail gracefully.  I've opened https://github.com/napari/magicgui/issues/335 at magicgui.  thanks!

**Comment by tlambert03** [comment]
fixed in https://github.com/napari/magicgui/pull/336
