### ISSUE TITLE
surface timeseries example regression

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#3876]
## 🐛 Bug
When I run the following `python examples/surface_timeseries.py` on main I get an error. Looks like some assumptions were made when we passed `view_direction` to `get_value`. We should fix this before next release

```python-traceback
(base) czirwc1macos2701:napari nsofroniew$ python examples/surface_timeseries.py
/Users/nsofroniew/opt/anaconda3/lib/python3.7/site-packages/nilearn/surface/surface.py:555: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  return np.asarray([arr.data for arr in gifti_img.darrays]).T.squeeze()
Traceback (most recent call last):
  File "examples/surface_timeseries.py", line 36, in <module>
    contrast_limits=[-1.5, 3.5], name='timeseries')
  File "/Users/nsofroniew/GitHub/napari/napari/components/viewer_model.py", line 5, in add_surface
    import os
  File "/Users/nsofroniew/opt/anaconda3/lib/python3.7/_collections_abc.py", line 971, in append
    self.insert(len(self), value)
  File "/Users/nsofroniew/GitHub/napari/napari/components/layerlist.py", line 90, in insert
    super().insert(index, new_layer)
  File "/Users/nsofroniew/GitHub/napari/napari/utils/events/containers/_selectable_list.py", line 65, in insert
    super().insert(index, value)
  File "/Users/nsofroniew/GitHub/napari/napari/utils/events/containers/_evented_list.py", line 179, in insert
    self.events.inserted(index=index, value=value)
  File "/Users/nsofroniew/GitHub/napari/napari/utils/events/event.py", line 715, in __call__
    self._invoke_callback(cb, event if pass_event else None)
  File "/Users/nsofroniew/GitHub/napari/napari/utils/events/event.py", line 756, in _invoke_callback
    cb_event=(cb, event),
  File "/Users/nsofroniew/GitHub/napari/napari/utils/events/event.py", line 739, in _invoke_callback
    cb(event)
  File "/Users/nsofroniew/GitHub/napari/napari/components/viewer_model.py", line 462, in _on_add_layer
    self._on_layers_change()
  File "/Users/nsofroniew/GitHub/napari/napari/components/viewer_model.py", line 354, in _on_layers_change
    list(self.cursor.position) + [0] * dim_diff
  File "/Users/nsofroniew/GitHub/napari/napari/utils/events/evented_model.py", line 228, in __setattr__
    getattr(self.events, name)(value=after)  # emit event
  File "/Users/nsofroniew/GitHub/napari/napari/utils/events/event.py", line 715, in __call__
    self._invoke_callback(cb, event if pass_event else None)
  File "/Users/nsofroniew/GitHub/napari/napari/utils/events/event.py", line 756, in _invoke_callback
    cb_event=(cb, event),
  File "/Users/nsofroniew/GitHub/napari/napari/utils/events/event.py", line 741, in _invoke_callback
    cb()
  File "/Users/nsofroniew/GitHub/napari/napari/components/viewer_model.py", line 390, in _on_cursor_position_change
    world=True,
  File "/Users/nsofroniew/GitHub/napari/napari/layers/base/base.py", line 1586, in get_status
    world=world,
  File "/Users/nsofroniew/GitHub/napari/napari/layers/base/base.py", line 1062, in get_value
    list(view_direction)
TypeError: 'NoneType' object is not iterable
```

**Comment by kevinyamauchi** [comment]
Sorry about that! I hadn't realized that the `get_status()` would be called when a layer is added (I think it's part of a refresh when the dims change). See #3881 for the fix.
