### ISSUE TITLE
Bug: no longer possible to set contrast limits on a subset of images passed to view_image

### ISSUE THREAD

**Issue by tlambert03** [napari/napari#3934]
## 🐛 Bug
This code used to work (it would manually set contrast limits on the first channel, but autoscale the second):

```py
import napari
import numpy as np

v = napari.view_image(
    np.random.rand(2, 64, 64),
    channel_axis=0,
    contrast_limits=[(0.2, 0.8), None],
)
```

as of #3140, it no longer works, failing with:

```pytb
❯ python x.py
Traceback (most recent call last):
  File "/Users/talley/Dropbox (HMS)/Python/forks/napari/x.py", line 4, in <module>
    v = napari.view_image(
  File "/Users/talley/Dropbox (HMS)/Python/forks/napari/napari/view_layers.py", line 134, in view_image
    return _make_viewer_then('add_image', args, kwargs)
  File "/Users/talley/Dropbox (HMS)/Python/forks/napari/napari/view_layers.py", line 119, in _make_viewer_then
    method(*args, **kwargs)
  File "/Users/talley/Dropbox (HMS)/Python/forks/napari/napari/components/viewer_model.py", line 755, in add_image
    layer = Image(image, **i_kwargs)
  File "/Users/talley/Dropbox (HMS)/Python/forks/napari/napari/layers/image/image.py", line 299, in __init__
    self.colormap = colormap
  File "/Users/talley/Dropbox (HMS)/Python/forks/napari/napari/layers/intensity_mixin.py", line 61, in colormap
    self._update_thumbnail()
  File "/Users/talley/Dropbox (HMS)/Python/forks/napari/napari/layers/image/image.py", line 791, in _update_thumbnail
    downsampled = np.clip(downsampled, low, high)
  File "<__array_function__ internals>", line 5, in clip
  File "/Users/talley/miniconda3/envs/napdev/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 2115, in clip
    return _wrapfunc(a, 'clip', a_min, a_max, out=out, **kwargs)
  File "/Users/talley/miniconda3/envs/napdev/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 57, in _wrapfunc
    return bound(*args, **kwds)
  File "/Users/talley/miniconda3/envs/napdev/lib/python3.9/site-packages/numpy/core/_methods.py", line 156, in _clip
    return _clip_dep_invoke_with_casting(
  File "/Users/talley/miniconda3/envs/napdev/lib/python3.9/site-packages/numpy/core/_methods.py", line 113, in _clip_dep_invoke_with_casting
    return ufunc(*args, out=out, **kwargs)
ValueError: operands could not be broadcast together with shapes (32,32) (2,)
```

@brisvag, would you mind taking a look to see what in that PR might have affected this?

**Comment by tlambert03** [comment]
ohhh... it's the damn `ensure_sequence_of_iterables` thing again :)

**Comment by sofroniewn** [comment]
@tlambert03 is this a regression that we should fix before 0.4.13? sounds like it might be

**Comment by tlambert03** [comment]
It would be nice, but clearly it's been there for a couple versions, so it's obviously not that common :)

**Comment by brisvag** [comment]
> ohhh... it's the damn `ensure_sequence_of_iterables` thing again :)

Dang it :) I'll take a look, but I'm not sure I can do something before release!

**Comment by brisvag** [comment]
So basically the problem here seems to be that `None` is (rightfully?) not considered iterable. This means that `[iterable, None]` is not a "sequence of iterables`, and therefore it is passed as a whole to every slice of the stack. Instead, what we want is to pass `iterable` to slice 0, and `None` to slice 1.

Should we simply add a special case for `None`?

**Comment by tlambert03** [comment]
> So basically the problem here seems to be that None is (rightfully?) not considered iterable.

exactly right.  The function name is now doing exactly what it says, but the usage of the function (in `add_image()`) wants some special cases for null values. 

> Should we simply add a special case for None?

If it's easy enough to keep all of the current tests passing, while also making the minimal code in my original post pass, then I'm all for special casing it for now.  `None` is often a special case anyway

**Comment by brisvag** [comment]
If #3941 passes all the tests then I'd say we're good to go.

**Comment by tlambert03** [comment]
thanks!

**Comment by brisvag** [comment]
All seems good :)
