### ISSUE TITLE
napari_write_tracks doesn't save tracks layer

### ISSUE THREAD

**Issue by thanushipeiris** [napari/napari#3936]
## 🐛 Bug

Tracks layer cannot be saved individually or with other layers. When you have a canvas with a track layer and other layer types and try to "Save all layers", none of them save.

## To Reproduce

1. Open a tracks layer using the tutorial [here](https://github.com/quantumjot/BayesianTracker/blob/master/examples/napari_btrack.ipynb)
2. Try to save all layers `Ctrl+Shift+S`
3. Specify filepath and watch as it buffers but no files are saved 😅

```
Traceback (most recent call last):
  File "C:\Users\thanushi.peiris\Anaconda3\envs\warmflash-v1\lib\site-packages\napari\_qt\menus\file_menu.py", line 51, in <lambda>
    'slot': lambda: window.qt_viewer._save_layers_dialog(
  File "C:\Users\thanushi.peiris\Anaconda3\envs\warmflash-v1\lib\site-packages\napari\_qt\qt_viewer.py", line 530, in _save_layers_dialog
    saved = self.viewer.layers.save(filename, selected=selected)
  File "C:\Users\thanushi.peiris\Anaconda3\envs\warmflash-v1\lib\site-packages\napari\components\layerlist.py", line 367, in save
    return save_layers(path, layers, plugin=plugin)
  File "C:\Users\thanushi.peiris\Anaconda3\envs\warmflash-v1\lib\site-packages\napari\plugins\io.py", line 237, in save_layers
    _written = _write_single_layer_with_plugins(
  File "C:\Users\thanushi.peiris\Anaconda3\envs\warmflash-v1\lib\site-packages\napari\plugins\io.py", line 415, in _write_single_layer_with_plugins
    hook_caller = getattr(
  File "C:\Users\thanushi.peiris\Anaconda3\envs\warmflash-v1\lib\site-packages\napari_plugin_engine\manager.py", line 903, in __getattribute__
    return object.__getattribute__(self, name)
AttributeError: '_HookRelay' object has no attribute 'napari_write_tracks'
```
## Expected behavior

Tracks layer saves in some kind of file format that can be read back in when you drag and drop it (maybe output data, graph, properties as a csv or xml). 
Or at least, the other non-track layers are saved and an error message produced for the tracks layer.

## Environment

```
napari: 0.4.12
Platform: Windows-10-10.0.14393-SP0
Python: 3.9.9 | packaged by conda-forge | (main, Dec 20 2021, 02:36:06) [MSC v.1929 64 bit (AMD64)]
Qt: 5.12.9
PyQt5: 5.12.3
NumPy: 1.22.0
SciPy: 1.7.3
Dask: 2021.12.0
VisPy: 0.9.4

OpenGL:
- GL version: 4.6.0 NVIDIA 431.70
- MAX_TEXTURE_SIZE: 32768

Screens:
- screen 1: resolution 3440x1440, scale 1.0

Plugins:
- StarDist: 2021.10.25
- animation: 0.0.2
- console: 0.0.4
- napari-arboretum: 0.0.2
- scikit-image: 0.4.12
- svg: 0.1.5
```

## Additional context

This may be related to [Issue #2857](https://github.com/napari/napari/issues/2857)

**Comment by sofroniewn** [comment]
I think this is because we don't have a default `napari_write_tracks`? Right @nclack @tlambert03 @alisterburt @JoOkuma? We should probably add one, but i think this will come after 0.4.13 as it's not a regression (we're close to releasing soon which is why i mention it)

**Comment by nclack** [comment]
that's correct. Is there an opinion on how we should save tracks?

**Comment by JoOkuma** [comment]
I don't have a formed opinion yet.
In the general case, the track layers have two inputs a table (`data`) and a dictionary (`graph`).
I think this is an opportunity to revisit this and use a single `data` input.

**Comment by JoOkuma** [comment]
@thanushipeiris I have a tracking plugin (under development) that has a tracks writer.
You can install it with `pip install git+https://github.com/JoOkuma/track-utils.git@track-addition`.

**Comment by psobolewskiPhD** [comment]
napari 0.5.4 still doesn't have a way to save a track layer 😭 
Do we expect anyone using tracks to roll their own? I'm not familiar enough with the nuance of tracking data.

**Comment by DragaDoncila** [comment]
Hmmm yeah. There is a **lot** of nuance with saving tracks, **but** I think having a barebones writer shouldn't be that hard. The hard bit is that we would need two files - one csv for the tracks data - probably a csv - and the other for the track graph, which could be a json file or another dataframe. Since we can't save it in a single file then it begs the question of the roundtrip... Although I suppose we don't have a tracks reader either so the roundtrip is our least concern.

I guess my vote would be for writing out a folder with a custom extension 🥲 and the two necessary files, that we can then read back in...
