### ISSUE TITLE
typing_extensions version issue: should be pinned >3.10?

### ISSUE THREAD

**Issue by psobolewskiPhD** [napari/napari#4019]
## 🐛 Bug

Trying to launch `napari` from a conda env with typing_extensions Version: 3.7.4.3
results in an error and napari doesn't launch.

## To Reproduce

1. Setup a conda env and install tensorflow following Apple instructions here: https://developer.apple.com/metal/tensorflow-plugin/
2. Install napari using conda: 
```
conda install -c andfoy pyqt
conda install napari
```
3. try to launch napari from terminal.

```
Traceback (most recent call last):
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/test-env2/bin/napari", line 10, in <module>
    sys.exit(main())
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/test-env2/lib/python3.9/site-packages/napari/__main__.py", line 449, in main
    _run()
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/test-env2/lib/python3.9/site-packages/napari/__main__.py", line 303, in _run
    from napari._qt.widgets.qt_splash_screen import NapariSplashScreen
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/test-env2/lib/python3.9/site-packages/napari/_qt/__init__.py", line 56, in <module>
    from .qt_event_loop import get_app, gui_qt, quit_app, run
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/test-env2/lib/python3.9/site-packages/napari/_qt/qt_event_loop.py", line 23, in <module>
    from .dialogs.qt_notification import NapariQtNotification
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/test-env2/lib/python3.9/site-packages/napari/_qt/dialogs/qt_notification.py", line 26, in <module>
    from superqt import QElidingLabel, ensure_main_thread
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/test-env2/lib/python3.9/site-packages/superqt/__init__.py", line 21, in <module>
    from .utils import QMessageHandler, ensure_main_thread, ensure_object_thread
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/test-env2/lib/python3.9/site-packages/superqt/utils/__init__.py", line 15, in <module>
    from ._qthreading import (
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/test-env2/lib/python3.9/site-packages/superqt/utils/_qthreading.py", line 23, in <module>
    from typing_extensions import Literal, ParamSpec
ImportError: cannot import name 'ParamSpec' from 'typing_extensions' (/Users/piotrsobolewski/Dev/miniforge3/envs/test-env2/lib/python3.9/site-packages/typing_extensions.py)
```
## Expected behavior

Napari should launch

## Environment

Env is setup by Apple and has typing_extensions version 3.7.4.3

## Additional context

Upgrading typing_extensions to 3.10.0.0 resolves the issue. As far as I can tell this is related to PEP612, which was added to `typing_extensions` here:
https://github.com/python/typing/pull/774/
So that would require 3.10 or later.
Also, for the record this is all on macOS 12 and arm64.

**Comment by tlambert03** [comment]
That is a superqt issue and was addressed in https://github.com/napari/superqt/pull/46
it's also now in the [conda recipe](https://github.com/conda-forge/superqt-feedstock/blob/master/recipe/meta.yaml#L27) ... so I'm surprised you didn't get it!

**Comment by tlambert03** [comment]
if you just run `conda install superqt` in a new env, what version of typing_extensions do you get

**Comment by psobolewskiPhD** [comment]
So in a totally new conda, I get 4.0.1
But in the Apple conda env, which comes with 3.7.4.3 I stay at 3.7.4.3.
If i use pip to install napari then I get 4.0.1 and everything is gucci.

So install tensorflow per Apple, install pyqt via conda -c andfoy, install napari via pip.

**Comment by psobolewskiPhD** [comment]
Following Apple instructions here: 
https://developer.apple.com/metal/tensorflow-plugin/
Followed by 
```
conda install -c andfoy pyqt
conda install napari
```
JustWorks(tm) now, so the issue was related to the TF depends/env.
(BTW I think pyqt will be on conda-forge soon!)
