### ISSUE TITLE
Adding empty points layer is broken

### ISSUE THREAD

**Issue by jni** [napari/napari#4087]
## 🐛 Bug

This was broken by #3999:

```python
import napari
from skimage import data

viewer = napari.view_image(data.camera())
_ = viewer.add_points()

napari.run()
```

Now results in:

```pytb
Traceback (most recent call last):
  File "/home/jni/projects/napari/examples/add-empty-points.py", line 5, in <module>
    _ = viewer.add_points()
  File "/home/jni/projects/napari/napari/components/viewer_model.py", line 5, in add_points
    import os
  File "/home/jni/miniconda3/envs/all/lib/python3.9/_collections_abc.py", line 1072, in append
    self.insert(len(self), value)
  File "/home/jni/projects/napari/napari/components/layerlist.py", line 106, in insert
    super().insert(index, new_layer)
  File "/home/jni/projects/napari/napari/utils/events/containers/_selectable_list.py", line 65, in insert
    super().insert(index, value)
  File "/home/jni/projects/napari/napari/utils/events/containers/_evented_list.py", line 183, in insert
    self.events.inserted(index=index, value=value)
  File "/home/jni/projects/napari/napari/utils/events/event.py", line 715, in __call__
    self._invoke_callback(cb, event if pass_event else None)
  File "/home/jni/projects/napari/napari/utils/events/event.py", line 752, in _invoke_callback
    _handle_exception(
  File "/home/jni/projects/napari/napari/utils/events/event.py", line 739, in _invoke_callback
    cb(event)
  File "/home/jni/projects/napari/napari/_qt/qt_viewer.py", line 488, in _on_add_layer_change
    self._add_layer(layer)
  File "/home/jni/projects/napari/napari/_qt/qt_viewer.py", line 498, in _add_layer
    vispy_layer = create_vispy_visual(layer)
  File "/home/jni/projects/napari/napari/_vispy/utils/visual.py", line 63, in create_vispy_visual
    return visual_class(layer)
  File "/home/jni/projects/napari/napari/_vispy/layers/points.py", line 39, in __init__
    self._on_data_change()
  File "/home/jni/projects/napari/napari/_vispy/layers/points.py", line 74, in _on_data_change
    set_data(
  File "/home/jni/miniconda3/envs/all/lib/python3.9/site-packages/vispy/visuals/markers.py", line 680, in set_data
    if edge_width_rel < 0:
TypeError: '<' not supported between instances of 'list' and 'int'
```

I think the culprit is [this line](https://github.com/napari/napari/blob/6f639ca031785f2303a33273fa15fe346db51b78/napari/_vispy/layers/points.py#L55), which should instead be `edge_width = 0`?

**Comment by jni** [comment]
I also wonder whether it's really not possible to set empty data in vispy visuals? This "make an invisibly-small point" approach creeps me out. LOL

**Comment by jni** [comment]
Ignore me! Just needed to update my VisPy :sweat_smile:
