### ISSUE TITLE
Error using `read_data_with_plugins` with a URL 

### ISSUE THREAD

**Issue by dstansby** [napari/napari#4277]
## 🐛 Bug

I'm getting an odd error when trying to use `napari.plugins.io.read_data_with_plugins` with a URL. Reading the same file available locally is working fine.

## To Reproduce

```python
from napari.plugins.io import read_data_with_plugins

# Works fine
file = '/Users/dstansby/Downloads/ch00000.tif'
read_data_with_plugins([file])

# Errors
url = 'https:/raw.githubusercontent.com/brainglobe/cellfinder/master/tests/data/integration/detection/crop_planes/ch0/ch00000.tif'
read_data_with_plugins([url])
```

Error message:
```python
Traceback (most recent call last):
  File "/Users/dstansby/projects/napari/napari/napari/plugins/io.py", line 118, in read_data_with_plugins
    layer_data = reader(npe1_path)  # try to read data
  File "/Users/dstansby/projects/napari/napari/napari/types.py", line 144, in reader_function
    result = func(*args, **kwargs)
  File "/Users/dstansby/projects/napari/napari/napari/utils/io.py", line 244, in magic_imread
    image = imread(filename)
  File "/Users/dstansby/projects/napari/napari/napari/utils/io.py", line 137, in imread
    return tifffile.imread(filename)
  File "/Users/dstansby/mambaforge/envs/napari/lib/python3.9/site-packages/tifffile/tifffile.py", line 908, in imread
    with TiffFile(files, **kwargs_file) as tif:
  File "/Users/dstansby/mambaforge/envs/napari/lib/python3.9/site-packages/tifffile/tifffile.py", line 3202, in __init__
    fh = FileHandle(arg, mode=mode, name=name, offset=offset, size=size)
  File "/Users/dstansby/mambaforge/envs/napari/lib/python3.9/site-packages/tifffile/tifffile.py", line 10536, in __init__
    self.open()
  File "/Users/dstansby/mambaforge/envs/napari/lib/python3.9/site-packages/tifffile/tifffile.py", line 10549, in open
    self._fh = open(self._file, self._mode)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/dstansby/projects/napari/cellfinder-napari/https:/raw.githubusercontent.com/brainglobe/cellfinder/master/tests/data/integration/detection/crop_planes/ch0/ch00000.tif'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/dstansby/projects/napari/cellfinder-napari/test_sample.py", line 1, in <module>
    from cellfinder_napari.sample_data import get_sample_data
  File "/Users/dstansby/projects/napari/cellfinder-napari/cellfinder_napari/sample_data.py", line 7, in <module>
    read_data_with_plugins([url])
  File "/Users/dstansby/projects/napari/napari/napari/plugins/io.py", line 121, in read_data_with_plugins
    raise PluginCallError(result.implementation, cause=exc) from exc
napari_plugin_engine.exceptions.PluginCallError: Error in plugin 'builtins', hook 'napari_get_reader': [Errno 2] No such file or directory: '/Users/dstansby/projects/napari/cellfinder-napari/https:/raw.githubusercontent.com/brainglobe/cellfinder/master/tests/data/integration/detection/crop_planes/ch0/ch00000.tif'
```

## Expected behavior
File is downloaded and loaded with no error.

## Environment
napari version '0.4.16.dev14+g67556aaf'

**Comment by liu-ziyang** [comment]
Hi @dstansby, Thank you for reporting this bug. However, as of now the default implementation for reading tiff does not support reading a URL with HTTP/HTTPS protocol. I went back and checked the history versions and it seems we never supported using a remote URL. 

In the documentation for this method, there is indeed mention of using a URL, but it seems this URL is referring to a local address instead of a remote location using HTTP/HTTPS protocol. 

@tlambert03 If you can confirm ^ is correct, I can update the documentation of this method to clarify the URL part

**Comment by tlambert03** [comment]
@potating-potato 

I think the issue here is not about our builtin reader support for tiff URLs, but the fact that the local file system is being prepended to the url before passing to plugins

**Comment by dstansby** [comment]
Yes, it looks odd.... I thought I would post and see if anyone had any immediate ideas, but I can spend some time debugging and working out what's going on today.

**Comment by dstansby** [comment]
Somewhere down the call stack `napari.utils.io.magic_imread` is being identified as being capable of reading the URL, but a look at the source code indicates it isn't. I think fixing this errornous identification will then propagate through to https://github.com/napari/napari/blob/9355fdbea01dbec6f01a9ff6409fc67825598e27/napari/plugins/io.py#L123

and a nice "no plugin found" error message will be raised.

**Comment by tlambert03** [comment]
thanks @dstansby!  See comment over in https://github.com/napari/napari/pull/4284#issuecomment-1072319473 ... it's a little bit more complicated than that.  it's just tiffs that don't work for urls.  the imageio fallback will work for non-tiff urls
