### ISSUE TITLE
read_zarr_dataset errors on non-zarr content

### ISSUE THREAD

**Issue by joshmoore** [napari/napari#4358]
## To Reproduce

1. `bioformats2raw --scale-format-string '%2$d' a.fake sample.ome.zarr`
2. `napari sample.ome.zarr`
3. exception thrown:

```
(gbi2022) /opt/NGFF-GBI-2022-Workshop $napari sample.ome.zarr
WARNING: Layer-backing cannot be explicitly controlled on 10.14 when built against the 10.14 SDK
12:38:11 WARNING Layer-backing cannot be explicitly controlled on 10.14 when built against the 10.14 SDK
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/gbi2022/bin/napari", line 10, in <module>
    sys.exit(main())
  File "/usr/local/anaconda3/envs/gbi2022/lib/python3.9/site-packages/napari/__main__.py", line 447, in main
    _run()
  File "/usr/local/anaconda3/envs/gbi2022/lib/python3.9/site-packages/napari/__main__.py", line 312, in _run
    viewer = view_path(  # noqa: F841
  File "/usr/local/anaconda3/envs/gbi2022/lib/python3.9/site-packages/napari/view_layers.py", line 178, in view_path
    return _make_viewer_then('open', args, kwargs)
  File "/usr/local/anaconda3/envs/gbi2022/lib/python3.9/site-packages/napari/view_layers.py", line 126, in _make_viewer_then
    method(*args, **kwargs)
  File "/usr/local/anaconda3/envs/gbi2022/lib/python3.9/site-packages/napari/components/viewer_model.py", line 918, in open
    self._add_layers_with_plugins(
  File "/usr/local/anaconda3/envs/gbi2022/lib/python3.9/site-packages/napari/components/viewer_model.py", line 983, in _add_layers_with_plugins
    layer_data, hookimpl = read_data_with_plugins(
  File "/usr/local/anaconda3/envs/gbi2022/lib/python3.9/site-packages/napari/plugins/io.py", line 68, in read_data_with_plugins
    res = _npe2.read(paths, plugin, stack=stack)
  File "/usr/local/anaconda3/envs/gbi2022/lib/python3.9/site-packages/napari/plugins/_npe2.py", line 52, in read
    raise e
  File "/usr/local/anaconda3/envs/gbi2022/lib/python3.9/site-packages/napari/plugins/_npe2.py", line 48, in read
    layer_data, reader = read_get_reader(npe1_path, plugin_name=plugin)
  File "/usr/local/anaconda3/envs/gbi2022/lib/python3.9/site-packages/npe2/io_utils.py", line 45, in read_get_reader
    return _read(path, plugin_name=plugin_name, return_reader=True)
  File "/usr/local/anaconda3/envs/gbi2022/lib/python3.9/site-packages/npe2/io_utils.py", line 132, in _read
    layer_data = read_func(path_or_paths)
  File "/usr/local/anaconda3/envs/gbi2022/lib/python3.9/site-packages/napari/types.py", line 144, in reader_function
    result = func(*args, **kwargs)
  File "/usr/local/anaconda3/envs/gbi2022/lib/python3.9/site-packages/napari/utils/io.py", line 236, in magic_imread
    image, zarr_shape = read_zarr_dataset(filename)
  File "/usr/local/anaconda3/envs/gbi2022/lib/python3.9/site-packages/napari/utils/io.py", line 328, in read_zarr_dataset
    image.append(read_zarr_dataset(os.path.join(path, subpath))[0])
  File "/usr/local/anaconda3/envs/gbi2022/lib/python3.9/site-packages/napari/utils/io.py", line 331, in read_zarr_dataset
    raise ValueError(
ValueError: Not a zarr dataset or group: sample.ome.zarr/OME
```

## Expected behavior

* The primary expectation is that the ome-zarr would get a chance to interpret the fileset. (A workaround is to pass `--plugin napari-ome-zarr`.) Catching this exception would likely allow that.
* In general, though, zarr implementations should likely ignore content that is outside of the spec: https://github.com/zarr-developers/zarr-specs/issues/112

## Environment

```
(gbi2022) /opt/NGFF-GBI-2022-Workshop $napari --info
napari: 0.4.15
Platform: macOS-12.0.1-x86_64-i386-64bit
System: MacOS 12.0.1
Python: 3.9.12 | packaged by conda-forge | (main, Mar 24 2022, 23:23:20)  [Clang 12.0.1 ]
Qt: 5.13.2
PyQt5: 5.13.2
NumPy: 1.22.3
SciPy: 1.8.0
Dask: 2022.04.0
VisPy: 0.9.6

OpenGL:
  - GL version:  2.1 ATI-4.7.29
  - MAX_TEXTURE_SIZE: 16384

Screens:
  - screen 1: resolution 3440x1440, scale 1.0
  - screen 2: resolution 1792x1120, scale 2.0

Plugins:
  - napari-ome-zarr: 0.4.0
  - scikit-image: 0.4.15
  - svg: 0.1.5
```

**Comment by jni** [comment]
Interesting, thanks for the context @joshmoore!

So would you say that in order to be compliant with the spec, we should just remove this bit:

https://github.com/napari/napari/blob/c9b4ba538c95a84cfbce122f507ed25ac950cd32/napari/utils/io.py#L341-L346

?

Regarding the plugin, you *should* have a chance to open it, not sure what's going on there, but you might need #4347 for this...

**Comment by joshmoore** [comment]
> we should just remove this bit:

i.e. return `None` and check for it, yes. (Possibly logging...)

> not sure what's going on there, but you might need #4347 for this...

🤷🏽. But I can play 🇬🇳🐷 if need be.

**Comment by neuromusic** [comment]
>🇬🇳🐷

🤣

**Comment by joshmoore** [comment]
> Regarding the plugin, you _should_ have a chance to open it, not sure what's going on there

@jni : possibly related to https://github.com/ome/napari-ome-zarr/issues/41#issuecomment-1097155814?

**Comment by DragaDoncila** [comment]
> Regarding the plugin, you should have a chance to open it, not sure what's going on there, but you might need https://github.com/napari/napari/pull/4347 for this...

@jni I thought we decided we didn't want the dialog behaviour when calling `napari` from the command line? With #4347 this would now raise a `MultiplePluginError`.

~~Although I will say I just tried it and while the error is raised, `napari-ome-zarr` isn't listed as one of the available plugins so there is something fishy here. I'm taking a closer look at this today~~ 🕵️  This was a classic case of PEBCAK.

**Comment by psobolewskiPhD** [comment]
This is still an issue, see confusion in https://github.com/napari/napari/issues/8150 with ome.zarr from bioformats2raw
However, I inspected and the OME dir has a .zgroup in it. This is throwing things off.
I'm not actually sure the issue is on the napari side or the bioformats side for writing .zgroup there.

**Comment by psobolewskiPhD** [comment]
So apparently putting .zgroup in the OME subdir which contains the xml is within the spec?
https://ngff.openmicroscopy.org/0.4/#bf2raw
So I think for the builtins reader (see #8150) we should just ignore subdir named 'OME' when iterating directories? then 
`napari foo.ome.zarr` would have a chance to work for bf2raw images that have just 1 image, so where inside the .zarr is just `/0` and `/OME`, with `/0` containing the pyramids.

Note I get prompted to select the plugin (napari-ome-zarr) and if I select it, I still get the error:
ValueError: Reader 'napari-ome-zarr' was selected to open ['CMU-1_Crop.ome.zarr'], but returned no data.
If I append `/0` then it works. Now napari has no special OME-zarr handling (as noted above), but i would expect napari-ome-zarr to know about the `/OME` dir and know to ignore it?

**Comment by psobolewskiPhD** [comment]
I'm going to close. 
Right now when opening the ome-zarr you do get the prompt for builtins or napari-ome-zarr if installed, as expected. So that part is fixed.
Alas, nothing is loaded.
So https://github.com/napari/napari/pull/8355 will improve this case for builtins. 
But for napari-ome-zarr, this is not supported, see: https://github.com/ome/napari-ome-zarr/issues/127#issuecomment-3397132906
