### ISSUE TITLE
Can not import napari Viewer

### ISSUE THREAD

**Issue by Raphael-Gronauer** [napari/napari#4359]
## 🐛 Bug

error when loading napari Viewer

## To Reproduce
from napari import Viewer

```python-traceback
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/raphael/.local/lib/python3.8/site-packages/napari/_lazy.py", line 47, in __getattr__
    submod = import_module(f'{module_name}.{attr_to_modules[name]}')
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/raphael/.local/lib/python3.8/site-packages/napari/viewer.py", line 5, in <module>
    import magicgui as mgui
  File "/home/raphael/.local/lib/python3.8/site-packages/magicgui/__init__.py", line 11, in <module>
    from ._magicgui import magic_factory, magicgui
  File "/home/raphael/.local/lib/python3.8/site-packages/magicgui/_magicgui.py", line 7, in <module>
    from magicgui.widgets import FunctionGui, MainFunctionGui
  File "/home/raphael/.local/lib/python3.8/site-packages/magicgui/widgets/__init__.py", line 14, in <module>
    from ._bases import Widget, create_widget
  File "/home/raphael/.local/lib/python3.8/site-packages/magicgui/widgets/_bases/__init__.py", line 45, in <module>
    from .button_widget import ButtonWidget
  File "/home/raphael/.local/lib/python3.8/site-packages/magicgui/widgets/_bases/button_widget.py", line 3, in <module>
    from magicgui.events import Signal, SignalInstance
  File "/home/raphael/.local/lib/python3.8/site-packages/magicgui/events.py", line 7, in <module>
    import psygnal
  File "/home/raphael/.local/lib/python3.8/site-packages/psygnal/__init__.py", line 57, in <module>
    from ._group import EmissionInfo, SignalGroup
  File "psygnal/_group.py", line 13, in init psygnal._group
  File "psygnal/_signal.py", line 27, in init psygnal._signal
ImportError: cannot import name get_args
```

## Environment
Ubuntu 20.04 LTS
Python 3.8.10
napari version 0.4.15

**Comment by Czaki** [comment]
Could you provide your `typing_etensions` version, and could you check if error is solved if you update it to latest version?

**Comment by Raphael-Gronauer** [comment]
my version of typing_extensions is already 4.1.1

**Comment by Czaki** [comment]
> my version of typing_extensions is already 4.1.1

`pip install --force-reinstall typing-extensions` 

I even check typing extension code and see no other option that failed installation

**Comment by Raphael-Gronauer** [comment]
re-installation of typing-extensions solved the problem,
thanks

**Comment by Czaki** [comment]
Could you close this issue?
