### ISSUE TITLE
Some types (int64) are not supported yet.

### ISSUE THREAD

**Issue by royerloic** [napari/napari#447]
## 🐛 Bug

By mistake i tried to add an image (array) of type int64 and boom -- it crashes.

We might want to have some tests or examples for more exotic types.
For example, complex types would be cool but are outside the scope of this issue...
(but exciting!)

## To Reproduce

Create an array of int64 dtype and try to view it in napari... 

You get this:

```
WARNING: Traceback (most recent call last):
  File "/Users/royer/workspace/python/pitl/pitl/it/demo/demo_it_n2s_gbm_2D_rgb.py", line 76, in <module>
    demo(astronaut())
  File "/Users/royer/workspace/python/pitl/pitl/it/demo/demo_it_n2s_gbm_2D_rgb.py", line 31, in demo
    rescale_intensity(noisy, in_range='image', out_range=(0, 1)), name='noisy'
  File "/Users/royer/anaconda3/envs/pitl/lib/python3.7/contextlib.py", line 119, in __exit__
    next(self.gen)
  File "/Users/royer/anaconda3/envs/pitl/lib/python3.7/site-packages/napari/_qt/event_loop.py", line 31, in gui_qt
    app.exec_()
  File "/Users/royer/anaconda3/envs/pitl/lib/python3.7/site-packages/vispy/app/backends/_qt.py", line 501, in event
    out = super(QtBaseCanvasBackend, self).event(ev)
  File "/Users/royer/anaconda3/envs/pitl/lib/python3.7/site-packages/vispy/app/backends/_qt.py", line 818, in paintGL
    self._vispy_canvas.events.draw(region=None)
  File "/Users/royer/anaconda3/envs/pitl/lib/python3.7/site-packages/vispy/util/event.py", line 455, in __call__
    self._invoke_callback(cb, event)
  File "/Users/royer/anaconda3/envs/pitl/lib/python3.7/site-packages/vispy/util/event.py", line 475, in _invoke_callback
    self, cb_event=(cb, event))
  << caught exception here: >>
  File "/Users/royer/anaconda3/envs/pitl/lib/python3.7/site-packages/vispy/util/event.py", line 471, in _invoke_callback
    cb(event)
  File "/Users/royer/anaconda3/envs/pitl/lib/python3.7/site-packages/vispy/scene/canvas.py", line 217, in on_draw
    self._draw_scene()
  File "/Users/royer/anaconda3/envs/pitl/lib/python3.7/site-packages/vispy/scene/canvas.py", line 266, in _draw_scene
    self.draw_visual(self.scene)
  File "/Users/royer/anaconda3/envs/pitl/lib/python3.7/site-packages/vispy/scene/canvas.py", line 304, in draw_visual
    node.draw()
  File "/Users/royer/anaconda3/envs/pitl/lib/python3.7/site-packages/vispy/scene/visuals.py", line 99, in draw
    self._visual_superclass.draw(self)
  File "/Users/royer/anaconda3/envs/pitl/lib/python3.7/site-packages/vispy/visuals/visual.py", line 443, in draw
    self._vshare.index_buffer)
  File "/Users/royer/anaconda3/envs/pitl/lib/python3.7/site-packages/vispy/visuals/shaders/program.py", line 101, in draw
    Program.draw(self, *args, **kwargs)
  File "/Users/royer/anaconda3/envs/pitl/lib/python3.7/site-packages/vispy/gloo/program.py", line 533, in draw
    canvas.context.flush_commands()
  File "/Users/royer/anaconda3/envs/pitl/lib/python3.7/site-packages/vispy/gloo/context.py", line 176, in flush_commands
    self.glir.flush(self.shared.parser)
  File "/Users/royer/anaconda3/envs/pitl/lib/python3.7/site-packages/vispy/gloo/glir.py", line 572, in flush
    self._shared.flush(parser)
  File "/Users/royer/anaconda3/envs/pitl/lib/python3.7/site-packages/vispy/gloo/glir.py", line 494, in flush
    parser.parse(self._filter(self.clear(), parser))
  File "/Users/royer/anaconda3/envs/pitl/lib/python3.7/site-packages/vispy/gloo/glir.py", line 819, in parse
    self._parse(command)
  File "/Users/royer/anaconda3/envs/pitl/lib/python3.7/site-packages/vispy/gloo/glir.py", line 787, in _parse
    ob.set_data(*args)
  File "/Users/royer/anaconda3/envs/pitl/lib/python3.7/site-packages/vispy/gloo/glir.py", line 1537, in set_data
    raise ValueError("Type %r not allowed for texture" % data.dtype)
ValueError: Type dtype('int64') not allowed for texture
ERROR: Invoking <bound method SceneCanvas.on_draw of <SceneCanvas (PySide2) at 0x128724438>> for DrawEvent
WARNING: Error drawing visual <Image at 0x133fde5f8>
ERROR: Invoking <bound method SceneCanvas.on_draw of <SceneCanvas (PySide2) at 0x128724438>> repeat 2
```

## Environment

 - napari Version (e.g., 1.0): 0.1.3
 - OS (e.g., Linux): OSX
 - Python version: 3.7
 - Any other relevant information:

**Comment by sofroniewn** [comment]
I can reproduce this bug - probably fixable by checking the type and casting the `_data_view` which is what we actually send over to vispy, that way the original data is unchanged.

@kne42 @jni do you have thoughts on how best to do this? Something like?

```python
if X.dypte == np.int64:
   X = X.astype(int)
```

**Comment by kne42** [comment]
If modifying the original array is not something that we'll be doing, I would use the following instead:
```python
if arr.dtype == np.int64:
    warn("Type dtype('int64') not allowed for texture")
    arr = arr.view(np.int)
```

This way we aren't creating a new copy every time :)

**Comment by kne42** [comment]
you'd also probably want to cover all of the other exotic data types:
```python
from vispy.gloo.glir import GlirTexture
texture_dtypes = GlirTexture._types.keys()

...

dtype = np.dtype(arr.dtype)
msg = f'type {dtype} not allowed for texture; must be one of {set(texture_dtypes)}'
if dtype not in texture_dtypes:
    try:
        dtype = dict(i=np.int32, f=np.float32)[dtype.kind]
    except KeyError: # not an int or float
        raise TypeError(msg)
    warn(msg)
    arr = arr.view(dtype)
```

**Comment by jni** [comment]
@kne42 doesn't np.int resolve to np.int64 on most platforms these days?

**Comment by kne42** [comment]
@jni correct, so it should explicitly be `np.int32` in the first example
