### ISSUE TITLE
Assertion error when meshing certain polygons

### ISSUE THREAD

**Issue by perlman** [napari/napari#4674]
## 🐛 Bug

While testing performance of the shapes layer, I found it increasingly easy to produce "complex" shapes (subjective term, not math) which would cause an exception in the triangulation code used to generate the meshes.

This may be a `vispy` issue instead. I need to first verify that napari isn't doing anything weird with the vertices.

## To Reproduce

Sample code:
```python
import numpy as np
import napari
viewer = napari.Viewer()
polygons = np.array([[0, 118.947067, 168.501535],
    [0, 3.79592571, 466.985975],
    [0, 224.699302, 86.0571976],
    [0, .216867871, 402.016053]])
viewer.add_shapes(polygons, shape_type='polygon')
napari.run()
```

Traceback:
```
Traceback (most recent call last):
  File "/Users/eric/czi/napari/minshape.py", line 8, in <module>
    viewer.add_shapes(polygons, shape_type='polygon')
  File "/Users/eric/czi/napari/napari/components/viewer_model.py", line 4, in add_shapes
    import itertools
  File "/Users/eric/czi/napari/napari/layers/shapes/shapes.py", line 550, in __init__
    self._init_shapes(
  File "/Users/eric/czi/napari/napari/layers/shapes/shapes.py", line 2116, in _init_shapes
    self._add_shapes(
  File "/Users/eric/czi/napari/napari/layers/shapes/shapes.py", line 2231, in _add_shapes
    self._add_shapes_to_view(shape_inputs, self._data_view)
  File "/Users/eric/czi/napari/napari/layers/shapes/shapes.py", line 2243, in _add_shapes_to_view
    sh_inp = tuple(
  File "/Users/eric/czi/napari/napari/layers/shapes/shapes.py", line 2245, in <genexpr>
    shape_classes[ShapeType(st)](
  File "/Users/eric/czi/napari/napari/layers/shapes/_shapes_models/polygon.py", line 30, in __init__
    super().__init__(
  File "/Users/eric/czi/napari/napari/layers/shapes/_shapes_models/_polgyon_base.py", line 51, in __init__
    self.data = data
  File "/Users/eric/czi/napari/napari/layers/shapes/_shapes_models/_polgyon_base.py", line 76, in data
    self._update_displayed_data()
  File "/Users/eric/czi/napari/napari/layers/shapes/_shapes_models/_polgyon_base.py", line 81, in _update_displayed_data
    self._set_meshes(
  File "/Users/eric/czi/napari/napari/layers/shapes/_shapes_models/shape.py", line 223, in _set_meshes
    vertices, triangles = triangulate_face(clean_data)
  File "/Users/eric/czi/napari/napari/layers/shapes/_shapes_utils.py", line 562, in triangulate_face
    vertices, triangles = PolygonData(vertices=data).triangulate()
  File "/Users/eric/czi/czi-env-39/lib/python3.9/site-packages/vispy/geometry/polygon.py", line 125, in triangulate
    tri.triangulate()
  File "/Users/eric/czi/czi-env-39/lib/python3.9/site-packages/vispy/geometry/triangulation.py", line 186, in triangulate
    self._edge_event(i, j)
  File "/Users/eric/czi/czi-env-39/lib/python3.9/site-packages/vispy/geometry/triangulation.py", line 405, in _edge_event
    self._add_tri(polygon[ind], polygon[ind-1],
  File "/Users/eric/czi/czi-env-39/lib/python3.9/site-packages/vispy/geometry/triangulation.py", line 747, in _add_tri
    assert a != b and b != c and c != a
AssertionError
```
## Expected behavior

Not to crash. 🙃 

## Environment

 - Please copy and paste the information at napari info option in help menubar here:
 - 
napari: 0.4.16rc2.dev95+g0bc0826e
Platform: macOS-12.4-arm64-arm-64bit
System: MacOS 12.4
Python: 3.9.12 (main, May 8 2022, 17:57:49) [Clang 13.1.6 (clang-1316.0.21.2)]
Qt: 5.15.3
PyQt5: 5.15.6
NumPy: 1.22.3
SciPy: 1.8.1
Dask: 2022.05.0
VisPy: 0.10.0

OpenGL:
- GL version: 2.1 Metal - 76.3
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1512x982, scale 2.0

Plugins:
- console: 0.0.4
- napari-svg: 0.1.6
- scikit-image: 0.4.16rc2.dev95+g0bc0826e

 - Any other relevant information:

## Additional context

I don't believe this is related to #3867. I am able to reproduce with a commit immediately before the merge.

**Comment by perlman** [comment]
Similar, but not identical, to #1058. The exceptions are different -- #1058 is regarding an edge not being generated, whereas this exception is from a triangle being created with duplicate vertices.

**Comment by psobolewskiPhD** [comment]
still getting this on 22a5018f9e8c7b8ecbe4df86786db45e6ecc1f2e

**Comment by jni** [comment]
Actually looking at the polygon data in the OP I don't expect #6654 to have any effect, ignore me 😅

**Comment by psobolewskiPhD** [comment]
With bermuda, the shape from the OP does not error.
If I uninstall it, it still does not error, with just numba and triangle:
```
Optional:
- numba: 0.62.1
- triangle: 20250106
- napari-plugin-manager: 0.1.6
- bermuda not installed
- PartSegCore not installed
```
If I uninstall triangle, then I get the error from OP and a runtime error:

<details>

```
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
File ~/Dev/napari/src/napari/layers/shapes/_shapes_utils.py:835, in triangulate_face_vispy(raw_vertices, edges, polygon_vertices)
    834 tri = Triangulation(raw_vertices, edges)
--> 835 tri.triangulate()
    836 vertices, triangles = tri.pts, tri.tris

File ~/Dev/miniforge3/envs/napari-dev/lib/python3.13/site-packages/vispy/geometry/triangulation.py:188, in Triangulation.triangulate(self)
    185 for j in self._bottoms[self._tops == i]:
    186     # Make sure edge (j, i) is present in mesh
    187     # because edge event may have created a new front list
--> 188     self._edge_event(i, int(j))
    189     front = self._front

File ~/Dev/miniforge3/envs/napari-dev/lib/python3.13/site-packages/vispy/geometry/triangulation.py:407, in Triangulation._edge_event(self, i, j)
    406 ind = np.argmax(dist)
--> 407 self._add_tri(polygon[ind], polygon[ind-1],
    408               polygon[ind+1])
    409 polygon.pop(ind)

File ~/Dev/miniforge3/envs/napari-dev/lib/python3.13/site-packages/vispy/geometry/triangulation.py:742, in Triangulation._add_tri(self, a, b, c)
    740 def _add_tri(self, a, b, c):
    741     # sanity check
--> 742     assert a != b and b != c and c != a
    744     # ignore tris with duplicate points

AssertionError:

The above exception was the direct cause of the following exception:

RuntimeError                              Traceback (most recent call last)
Cell In[1], line 8
      3 viewer = napari.Viewer()
      4 polygons = np.array([[0, 118.947067, 168.501535],
      5     [0, 3.79592571, 466.985975],
      6     [0, 224.699302, 86.0571976],
      7     [0, .216867871, 402.016053]])
----> 8 viewer.add_shapes(polygons, shape_type='polygon')

File ~/Dev/napari/src/napari/utils/add_layer.py_tmpl:7, in add_shapes(self, data, ndim, affine, axis_labels, blending, cache, edge_color, edge_color_cycle, edge_colormap, edge_contrast_limits, edge_width, experimental_clipping_planes, face_color, face_color_cycle, face_colormap, face_contrast_limits, feature_defaults, features, metadata, name, opacity, projection_mode, properties, property_choices, rotate, scale, shape_type, shear, text, translate, units, visible, z_index)
      5 for name in getattr({cls_name}.__init__, "_deprecated_constructor_args", []):
      6     pos_kwargs[name] = kwargs.pop(name, None)
----> 7 layer = {cls_name}(**kwargs)
      8 for name, value in pos_kwargs.items():
      9     if value is not None:

File ~/Dev/napari/src/napari/layers/base/base.py:115, in PostInit.__call__(self, *args, **kwargs)
    114 def __call__(self, *args, **kwargs):
--> 115     obj = super().__call__(*args, **kwargs)
    116     obj._post_init()
    117     return obj

File ~/Dev/napari/src/napari/layers/shapes/shapes.py:582, in Shapes.__init__(self, data, ndim, affine, axis_labels, blending, cache, edge_color, edge_color_cycle, edge_colormap, edge_contrast_limits, edge_width, experimental_clipping_planes, face_color, face_color_cycle, face_colormap, face_contrast_limits, feature_defaults, features, metadata, name, opacity, projection_mode, properties, property_choices, rotate, scale, shape_type, shear, text, translate, units, visible, z_index)
    578 self._clipboard: dict[str, Shapes] = {}
    580 self._status = self.mode
--> 582 self._init_shapes(
    583     data,
    584     shape_type=shape_type,
    585     edge_width=edge_width,
    586     edge_color=edge_color,
    587     edge_color_cycle=edge_color_cycle,
    588     edge_colormap=edge_colormap,
    589     edge_contrast_limits=edge_contrast_limits,
    590     face_color=face_color,
    591     face_color_cycle=face_color_cycle,
    592     face_colormap=face_colormap,
    593     face_contrast_limits=face_contrast_limits,
    594     z_index=z_index,
    595 )
    597 # set the current_* properties
    598 if len(data) > 0:

File ~/Dev/napari/src/napari/layers/shapes/shapes.py:2216, in Shapes._init_shapes(self, data, shape_type, edge_width, edge_color, edge_color_cycle, edge_colormap, edge_contrast_limits, face_color, face_color_cycle, face_colormap, face_contrast_limits, z_index)
   2211     face_color = self._initialize_color(
   2212         face_color, attribute='face', n_shapes=n_shapes
   2213     )
   2215 with self.block_thumbnail_update():
-> 2216     self._add_shapes(
   2217         data,
   2218         shape_type=shape_type,
   2219         edge_width=edge_width,
   2220         edge_color=edge_color,
   2221         face_color=face_color,
   2222         z_index=z_index,
   2223         n_new_shapes=n_shapes,
   2224     )
   2225     self._data_view._update_z_order()
   2226     self.refresh_colors()

File ~/Dev/napari/src/napari/layers/shapes/shapes.py:2343, in Shapes._add_shapes(self, data, shape_type, edge_width, edge_color, face_color, z_index, n_new_shapes)
   2332     # Turn input arguments into iterables
   2333     shape_inputs = zip(
   2334         data,
   2335         ensure_iterable(shape_type),
   (...)   2340         strict=False,
   2341     )
-> 2343     self._add_shapes_to_view(shape_inputs, self._data_view)
   2345 self._display_order_stored = copy(self._slice_input.order)
   2346 self._ndisplay_stored = copy(self._slice_input.ndisplay)

File ~/Dev/napari/src/napari/layers/shapes/shapes.py:2355, in Shapes._add_shapes_to_view(self, shape_inputs, data_view)
   2352 shape_inputs = tuple(shape_inputs)
   2354 # build all shapes
-> 2355 sh_inp = tuple(
   2356     (
   2357         shape_classes[st](
   2358             d,
   2359             edge_width=ew,
   2360             z_index=z,
   2361             dims_order=self._slice_input.order,
   2362             ndisplay=self._slice_input.ndisplay,
   2363         ),
   2364         ec,
   2365         fc,
   2366     )
   2367     for d, st, ew, ec, fc, z in shape_inputs
   2368 )
   2370 shapes, edge_colors, face_colors = tuple(zip(*sh_inp, strict=False))
   2372 # Add all shapes at once (faster than adding them one by one)

File ~/Dev/napari/src/napari/layers/shapes/shapes.py:2357, in <genexpr>(.0)
   2352 shape_inputs = tuple(shape_inputs)
   2354 # build all shapes
   2355 sh_inp = tuple(
   2356     (
-> 2357         shape_classes[st](
   2358             d,
   2359             edge_width=ew,
   2360             z_index=z,
   2361             dims_order=self._slice_input.order,
   2362             ndisplay=self._slice_input.ndisplay,
   2363         ),
   2364         ec,
   2365         fc,
   2366     )
   2367     for d, st, ew, ec, fc, z in shape_inputs
   2368 )
   2370 shapes, edge_colors, face_colors = tuple(zip(*sh_inp, strict=False))
   2372 # Add all shapes at once (faster than adding them one by one)

File ~/Dev/napari/src/napari/layers/shapes/_shapes_models/polygon.py:30, in Polygon.__init__(self, data, edge_width, z_index, dims_order, ndisplay, interpolation_order)
     20 def __init__(
     21     self,
     22     data,
   (...)     28     interpolation_order=1,
     29 ) -> None:
---> 30     super().__init__(
     31         data=data,
     32         edge_width=edge_width,
     33         z_index=z_index,
     34         dims_order=dims_order,
     35         ndisplay=ndisplay,
     36         closed=True,
     37         filled=True,
     38         name='polygon',
     39         interpolation_order=interpolation_order,
     40     )

File ~/Dev/napari/src/napari/layers/shapes/_shapes_models/_polygon_base.py:64, in PolygonBase.__init__(self, data, edge_width, z_index, dims_order, ndisplay, filled, closed, name, interpolation_order, interpolation_sampling)
     61 self.interpolation_order = interpolation_order
     62 self.interpolation_sampling = interpolation_sampling
---> 64 self.data = data

File ~/Dev/napari/src/napari/layers/shapes/_shapes_models/_polygon_base.py:94, in PolygonBase.data(self, data)
     87 self._data = data
     88 self._bounding_box = np.array(
     89     [
     90         np.min(data, axis=0),
     91         np.max(data, axis=0),
     92     ]
     93 )
---> 94 self._update_displayed_data()

File ~/Dev/napari/src/napari/layers/shapes/_shapes_models/_polygon_base.py:129, in PolygonBase._update_displayed_data(self)
    126         data = np.stack(splev(u, tck), axis=1)[:-1].astype(np.float32)
    128 # For path connect every all data
--> 129 self._set_meshes(data, face=self._filled, closed=self._closed)
    130 bbox = self._bounding_box[:, self.dims_displayed]
    131 self._box = create_box_from_bounding(bbox)

File ~/Dev/napari/src/napari/layers/shapes/_shapes_models/shape.py:572, in Shape._set_meshes_py(self, data, closed, face, edge)
    569 data = remove_path_duplicates(data, closed=closed)
    570 if edge and face:
    571     (f_vertices, f_triangles), (centers, offsets, triangles) = (
--> 572         triangulate_face_and_edges(data, triangulate_face_vispy)
    573     )
    574     self._edge_vertices = centers
    575     self._edge_offsets = offsets

File ~/Dev/napari/src/napari/layers/shapes/_shapes_utils.py:714, in triangulate_face_and_edges(polygon_vertices, triangulate_face_)
    708     return face_tri, edge_tri
    710 raw_vertices, edges = _triangulate_dispatch.normalize_vertices_and_edges(
    711     data2d, close=True
    712 )
--> 714 vertices, triangles = triangulate_face_(
    715     raw_vertices.copy(), edges.copy(), polygon_vertices
    716 )
    718 face_tri_ = (
    719     _fix_vertices_if_needed(vertices, axis=axis, value=value),
    720     triangles,
    721 )
    723 if len(edges) == len(polygon_vertices):
    724     # There is no removed edge

File ~/Dev/napari/src/napari/layers/shapes/_shapes_utils.py:841, in triangulate_face_vispy(raw_vertices, edges, polygon_vertices)
    837 except Exception as e:  # pragma: no cover
    838     path, text_path = _save_failed_triangulation(
    839         raw_vertices, backend='vispy'
    840     )
--> 841     raise RuntimeError(
    842         f'Triangulation failed. Data saved to {path} and {text_path}'
    843     ) from e
    845 triangles = triangles.astype(np.uint32)
    847 return vertices, triangles

RuntimeError: Triangulation failed. Data saved to /var/folders/sy/y3_x27j14cxg3_vhycs6cr_h0000gn/T/napari_vispy_triang_wdpy6b83.npz and /var/folders/sy/y3_x27j14cxg3_vhycs6cr_h0000gn/T/napari_vispy_triang_sl18dhwl.txt
```

</details>

So it seems like this issue is resolved when using one of the fast triangulation approaches, but not without them.
CC: @Czaki
