### ISSUE TITLE
Dask array not computed in Labels layer _raw_to_displayed

### ISSUE THREAD

**Issue by aeisenbarth** [napari/napari#4769]
## 🐛 Bug

The function `_raw_to_displayed` may raise an exception when called with a Dask array and direct color mode.

In several places in Napari, Numpy and Dask arrays seem to be used interchangeably (`ArrayLike`). For some uses like thumbnail generation, it is assumed that at some point dask arrays are converted to Numpy. It seems I have an edge case where this does not happen.

https://github.com/napari/napari/blob/0863b409943b8bd089fe11433d3b2398a984b9f8/napari/layers/labels/labels.py#L951
```
Traceback (most recent call last):
  File "my_script.py", line 99, in _
    layer.color = mapped_colors.to_dict()
  File "…/env/lib/python3.8/site-packages/napari/layers/labels/labels.py", line 525, in color
    self.color_mode = color_mode
  File "…/env/lib/python3.8/site-packages/napari/layers/labels/labels.py", line 663, in color_mode
    self.refresh()
  File "…/env/lib/python3.8/site-packages/napari/layers/base/base.py", line 1178, in refresh
    self.set_view_slice()
  File "…/env/lib/python3.8/site-packages/napari/layers/base/base.py", line 928, in set_view_slice
    self._set_view_slice()
  File "…/env/lib/python3.8/site-packages/napari/layers/image/image.py", line 756, in _set_view_slice
    self._load_slice(data)
  File "…/env/lib/python3.8/site-packages/napari/layers/image/image.py", line 779, in _load_slice
    self._on_data_loaded(data, sync=True)
  File "…/env/lib/python3.8/site-packages/napari/layers/image/image.py", line 803, in _on_data_loaded
    if not self._slice.on_loaded(data):
  File "…/env/lib/python3.8/site-packages/napari/layers/image/_image_slice.py", line 142, in on_loaded
    self._set_raw_images(data.image, data.thumbnail_source)
  File "…/env/lib/python3.8/site-packages/napari/layers/image/_image_slice.py", line 107, in _set_raw_images
    self.thumbnail.raw = thumbnail_source
  File "…/env/lib/python3.8/site-packages/napari/layers/image/_image_view.py", line 79, in raw
    self._view = self.image_converter(raw_image)
  File "…/env/lib/python3.8/site-packages/napari/layers/image/image.py", line 1041, in _raw_to_displayed
    return self.obj()._raw_to_displayed(*args, **kwarg)
  File "…/env/lib/python3.8/site-packages/napari/layers/labels/labels.py", line 943, in _raw_to_displayed
    [
  File "…/env/lib/python3.8/site-packages/napari/layers/labels/labels.py", line 943, in <listcomp>
    [
  File "…/env/lib/python3.8/site-packages/dask/array/core.py", line 1680, in __iter__
    for i in range(len(self)):
  File "…/env/lib/python3.8/site-packages/dask/array/core.py", line 1551, in __len__
    raise ValueError(msg)
ValueError: Cannot call len() on object with unknown chunk size.

A possible solution: https://docs.dask.org/en/latest/array-chunks.html#unknown-chunks
Summary: to compute chunks sizes, use

   x.compute_chunk_sizes()  # for Dask Array `x`
   ddf.to_dask_array(lengths=True)  # for Dask DataFrame `ddf`
```

## To Reproduce

- I can always reproduce it in my Napari-based application, but have not yet succeeded to extract it into a stand-alone test case. I will update with steps once I have identified them.
- It happens when assigning colors to a labels layer.

Preconditions for reproducing this situation:

- Labels layer is loaded from a Zarr file (thus backed by a Dask array)
- `napari.utils.config.async_loading` is True (default?, with False it does not occur)
- `LabelColorMode.DIRECT`
- It happens somewhere in thumbnail generation, where thumbnail source is still a Dask array and not converted to Numpy. 

## Expected behavior

- Before entering functions that don't support Dask arrays, `ArrayLike` should be converted. `ImageView.raw` is type-hinted to accept `ArrayLike`, and then it passes the argument via `_weakref_hide._raw_to_displayed` to `Labels._raw_to_displayed` which is not type-hinted.
- Maybe a simple solution would be in `_raw_to_displayed` to wrap [`np.unique`](https://github.com/napari/napari/blob/0863b409943b8bd089fe11433d3b2398a984b9f8/napari/layers/labels/labels.py#L945) into `np.asarray`.

## Environment

napari: 0.4.16
Platform: Linux-5.15.0-30-generic-x86_64-with-glibc2.17
System: Ubuntu 22.04 LTS
Python: 3.8.13 (default, Mar 28 2022, 11:38:47) [GCC 7.5.0]
Qt: 5.15.2
PyQt5: 5.15.6
NumPy: 1.22.4
SciPy: 1.8.1
Dask: 2022.05.2
VisPy: 0.10.0

OpenGL:
- GL version: 4.6.0 NVIDIA 470.129.06
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1920x1200, scale 1.0
- screen 2: resolution 1920x1200, scale 1.0

Plugins:
- console: 0.0.4
- napari-ome-zarr: 0.1.2
- napari-svg: 0.1.6
- scikit-image: 0.4.16

**Comment by aeisenbarth** [comment]
I found the cause, the run configuration had environment variables set: NAPARI_OCTREE=0;NAPARI_ASYNC=1

After removing these (so no async), the crash does not happen.
