### ISSUE TITLE
Label layer not displaying in 3d

### ISSUE THREAD

**Issue by Charles-Fieseler-Vienna** [napari/napari#4789]
## 🐛 Bug

3d viewing of label layers produces an error and does not display. Does not crash the viewer. In preliminary investigation, may be due to napari 0.4.14 (napari 0.4.13 works).

## To Reproduce

```
import napari
import numpy as np

volume = np.random.randint(0, 10, size=(5,100,100))

viewer = napari.Viewer(ndisplay=3)
viewer.add_labels(volume)
```

## Expected behavior

Correct display of layer. Note that sometimes it works; I don't have a reproducible working example, only a failing one!

## Environment
napari: 0.4.14
Platform: Linux-5.15.0-40-generic-x86_64-with-debian-bookworm-sid
System: Ubuntu 22.04 LTS
Python: 3.7.12 | packaged by conda-forge | (default, Oct 26 2021, 06:08:21) [GCC 9.4.0]
Qt: 5.15.2
PyQt5: 5.15.7
NumPy: 1.21.6
SciPy: 1.7.3
Dask: 2022.02.0
VisPy: 0.10.0

OpenGL:
- GL version: 4.6.0 NVIDIA 470.129.06
- MAX_TEXTURE_SIZE: 32768

Screens:
- screen 1: resolution 3840x1600, scale 1.0

Plugins:
- console: 0.0.4
- scikit-image: 0.4.14
- svg: 0.1.6

## Traceback

WARNING: Error drawing visual <Volume at 0x7f28139a6fd0>
Traceback (most recent call last):
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/app/backends/_qt.py", line 903, in paintGL
    self._vispy_canvas.events.draw(region=None)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/util/event.py", line 453, in __call__
    self._invoke_callback(cb, event)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/util/event.py", line 473, in _invoke_callback
    self, cb_event=(cb, event))
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/util/event.py", line 469, in _invoke_callback
    cb(event)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/scene/canvas.py", line 218, in on_draw
    self._draw_scene()
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/scene/canvas.py", line 277, in _draw_scene
    self.draw_visual(self.scene)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/scene/canvas.py", line 315, in draw_visual
    node.draw()
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/scene/visuals.py", line 103, in draw
    self._visual_superclass.draw(self)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/visuals/visual.py", line 452, in draw
    self._vshare.index_buffer)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/visuals/shaders/program.py", line 102, in draw
    Program.draw(self, *args, **kwargs)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/gloo/program.py", line 526, in draw
    canvas.context.flush_commands()
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/gloo/context.py", line 172, in flush_commands
    self.glir.flush(self.shared.parser)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/gloo/glir.py", line 582, in flush
    self._shared.flush(parser)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/gloo/glir.py", line 504, in flush
    parser.parse(self._filter(self.clear(), parser))
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/gloo/glir.py", line 822, in parse
    self._parse(command)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/gloo/glir.py", line 792, in _parse
    ob.set_data(*args)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/gloo/glir.py", line 932, in set_data
    (self._target, errormsg))
RuntimeError: Shader compilation error in 35632:
    on line 494: error C1503: undefined variable "surface_point"
      surface_point = iloc * u_shape;
    on line 495: error C1503: undefined variable "surface_found"
      surface_found = true;
    on line 514: error C1503: undefined variable "surface_found"
      if (surface_found == false) {
WARNING: Error drawing visual <Volume at 0x7f28139a6fd0>
Traceback (most recent call last):
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/app/backends/_qt.py", line 903, in paintGL
    self._vispy_canvas.events.draw(region=None)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/util/event.py", line 453, in __call__
    self._invoke_callback(cb, event)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/util/event.py", line 473, in _invoke_callback
    self, cb_event=(cb, event))
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/util/event.py", line 469, in _invoke_callback
    cb(event)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/scene/canvas.py", line 218, in on_draw
    self._draw_scene()
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/scene/canvas.py", line 277, in _draw_scene
    self.draw_visual(self.scene)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/scene/canvas.py", line 315, in draw_visual
    node.draw()
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/scene/visuals.py", line 103, in draw
    self._visual_superclass.draw(self)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/visuals/visual.py", line 452, in draw
    self._vshare.index_buffer)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/visuals/shaders/program.py", line 102, in draw
    Program.draw(self, *args, **kwargs)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/gloo/program.py", line 526, in draw
    canvas.context.flush_commands()
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/gloo/context.py", line 172, in flush_commands
    self.glir.flush(self.shared.parser)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/gloo/glir.py", line 582, in flush
    self._shared.flush(parser)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/gloo/glir.py", line 504, in flush
    parser.parse(self._filter(self.clear(), parser))
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/gloo/glir.py", line 822, in parse
    self._parse(command)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/gloo/glir.py", line 779, in _parse
    'does not exist' % (cmd, id_))
RuntimeError: Cannot SIZE object 85 because it does not exist
WARNING: Error drawing visual <Volume at 0x7f28139a6fd0>
Traceback (most recent call last):
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/app/backends/_qt.py", line 903, in paintGL
    self._vispy_canvas.events.draw(region=None)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/util/event.py", line 453, in __call__
    self._invoke_callback(cb, event)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/util/event.py", line 473, in _invoke_callback
    self, cb_event=(cb, event))
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/util/event.py", line 469, in _invoke_callback
    cb(event)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/scene/canvas.py", line 218, in on_draw
    self._draw_scene()
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/scene/canvas.py", line 277, in _draw_scene
    self.draw_visual(self.scene)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/scene/canvas.py", line 315, in draw_visual
    node.draw()
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/scene/visuals.py", line 103, in draw
    self._visual_superclass.draw(self)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/visuals/visual.py", line 452, in draw
    self._vshare.index_buffer)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/visuals/shaders/program.py", line 102, in draw
    Program.draw(self, *args, **kwargs)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/gloo/program.py", line 526, in draw
    canvas.context.flush_commands()
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/gloo/context.py", line 172, in flush_commands
    self.glir.flush(self.shared.parser)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/gloo/glir.py", line 582, in flush
    self._shared.flush(parser)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/gloo/glir.py", line 504, in flush
    parser.parse(self._filter(self.clear(), parser))
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/gloo/glir.py", line 822, in parse
    self._parse(command)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/gloo/glir.py", line 779, in _parse
    'does not exist' % (cmd, id_))
RuntimeError: Cannot SIZE object 85 because it does not exist
WARNING: Error drawing visual <Volume at 0x7f28139a6fd0>
Traceback (most recent call last):
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/app/backends/_qt.py", line 903, in paintGL
    self._vispy_canvas.events.draw(region=None)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/util/event.py", line 453, in __call__
    self._invoke_callback(cb, event)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/util/event.py", line 473, in _invoke_callback
    self, cb_event=(cb, event))
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/util/event.py", line 469, in _invoke_callback
    cb(event)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/scene/canvas.py", line 218, in on_draw
    self._draw_scene()
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/scene/canvas.py", line 277, in _draw_scene
    self.draw_visual(self.scene)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/scene/canvas.py", line 315, in draw_visual
    node.draw()
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/scene/visuals.py", line 103, in draw
    self._visual_superclass.draw(self)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/visuals/visual.py", line 452, in draw
    self._vshare.index_buffer)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/visuals/shaders/program.py", line 102, in draw
    Program.draw(self, *args, **kwargs)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/gloo/program.py", line 526, in draw
    canvas.context.flush_commands()
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/gloo/context.py", line 172, in flush_commands
    self.glir.flush(self.shared.parser)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/gloo/glir.py", line 582, in flush
    self._shared.flush(parser)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/gloo/glir.py", line 504, in flush
    parser.parse(self._filter(self.clear(), parser))
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/gloo/glir.py", line 822, in parse
    self._parse(command)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/gloo/glir.py", line 779, in _parse
    'does not exist' % (cmd, id_))
RuntimeError: Cannot SIZE object 85 because it does not exist
WARNING: Error drawing visual <Volume at 0x7f28139a6fd0>
Traceback (most recent call last):
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/app/backends/_qt.py", line 903, in paintGL
    self._vispy_canvas.events.draw(region=None)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/util/event.py", line 453, in __call__
    self._invoke_callback(cb, event)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/util/event.py", line 473, in _invoke_callback
    self, cb_event=(cb, event))
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/util/event.py", line 469, in _invoke_callback
    cb(event)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/scene/canvas.py", line 218, in on_draw
    self._draw_scene()
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/scene/canvas.py", line 277, in _draw_scene
    self.draw_visual(self.scene)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/scene/canvas.py", line 315, in draw_visual
    node.draw()
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/scene/visuals.py", line 103, in draw
    self._visual_superclass.draw(self)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/visuals/visual.py", line 452, in draw
    self._vshare.index_buffer)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/visuals/shaders/program.py", line 102, in draw
    Program.draw(self, *args, **kwargs)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/gloo/program.py", line 526, in draw
    canvas.context.flush_commands()
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/gloo/context.py", line 172, in flush_commands
    self.glir.flush(self.shared.parser)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/gloo/glir.py", line 582, in flush
    self._shared.flush(parser)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/gloo/glir.py", line 504, in flush
    parser.parse(self._filter(self.clear(), parser))
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/gloo/glir.py", line 822, in parse
    self._parse(command)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/gloo/glir.py", line 779, in _parse
    'does not exist' % (cmd, id_))
RuntimeError: Cannot SIZE object 85 because it does not exist
WARNING: Error drawing visual <Volume at 0x7f28139a6fd0>
Traceback (most recent call last):
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/app/backends/_qt.py", line 903, in paintGL
    self._vispy_canvas.events.draw(region=None)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/util/event.py", line 453, in __call__
    self._invoke_callback(cb, event)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/util/event.py", line 473, in _invoke_callback
    self, cb_event=(cb, event))
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/util/event.py", line 469, in _invoke_callback
    cb(event)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/scene/canvas.py", line 218, in on_draw
    self._draw_scene()
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/scene/canvas.py", line 277, in _draw_scene
    self.draw_visual(self.scene)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/scene/canvas.py", line 315, in draw_visual
    node.draw()
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/scene/visuals.py", line 103, in draw
    self._visual_superclass.draw(self)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/visuals/visual.py", line 452, in draw
    self._vshare.index_buffer)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/visuals/shaders/program.py", line 102, in draw
    Program.draw(self, *args, **kwargs)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/gloo/program.py", line 526, in draw
    canvas.context.flush_commands()
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/gloo/context.py", line 172, in flush_commands
    self.glir.flush(self.shared.parser)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/gloo/glir.py", line 582, in flush
    self._shared.flush(parser)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/gloo/glir.py", line 504, in flush
    parser.parse(self._filter(self.clear(), parser))
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/gloo/glir.py", line 822, in parse
    self._parse(command)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/gloo/glir.py", line 779, in _parse
    'does not exist' % (cmd, id_))
RuntimeError: Cannot SIZE object 85 because it does not exist
WARNING: Error drawing visual <Volume at 0x7f28139a6fd0>
Traceback (most recent call last):
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/app/backends/_qt.py", line 903, in paintGL
    self._vispy_canvas.events.draw(region=None)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/util/event.py", line 453, in __call__
    self._invoke_callback(cb, event)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/util/event.py", line 473, in _invoke_callback
    self, cb_event=(cb, event))
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/util/event.py", line 469, in _invoke_callback
    cb(event)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/scene/canvas.py", line 218, in on_draw
    self._draw_scene()
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/scene/canvas.py", line 277, in _draw_scene
    self.draw_visual(self.scene)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/scene/canvas.py", line 315, in draw_visual
    node.draw()
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/scene/visuals.py", line 103, in draw
    self._visual_superclass.draw(self)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/visuals/visual.py", line 452, in draw
    self._vshare.index_buffer)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/visuals/shaders/program.py", line 102, in draw
    Program.draw(self, *args, **kwargs)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/gloo/program.py", line 526, in draw
    canvas.context.flush_commands()
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/gloo/context.py", line 172, in flush_commands
    self.glir.flush(self.shared.parser)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/gloo/glir.py", line 582, in flush
    self._shared.flush(parser)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/gloo/glir.py", line 504, in flush
    parser.parse(self._filter(self.clear(), parser))
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/gloo/glir.py", line 822, in parse
    self._parse(command)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/gloo/glir.py", line 779, in _parse
    'does not exist' % (cmd, id_))
RuntimeError: Cannot SIZE object 85 because it does not exist
WARNING: Error drawing visual <Volume at 0x7f28139a6fd0>
Traceback (most recent call last):
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/app/backends/_qt.py", line 903, in paintGL
    self._vispy_canvas.events.draw(region=None)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/util/event.py", line 453, in __call__
    self._invoke_callback(cb, event)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/util/event.py", line 473, in _invoke_callback
    self, cb_event=(cb, event))
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/util/event.py", line 469, in _invoke_callback
    cb(event)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/scene/canvas.py", line 218, in on_draw
    self._draw_scene()
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/scene/canvas.py", line 277, in _draw_scene
    self.draw_visual(self.scene)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/scene/canvas.py", line 315, in draw_visual
    node.draw()
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/scene/visuals.py", line 103, in draw
    self._visual_superclass.draw(self)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/visuals/visual.py", line 452, in draw
    self._vshare.index_buffer)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/visuals/shaders/program.py", line 102, in draw
    Program.draw(self, *args, **kwargs)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/gloo/program.py", line 526, in draw
    canvas.context.flush_commands()
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/gloo/context.py", line 172, in flush_commands
    self.glir.flush(self.shared.parser)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/gloo/glir.py", line 582, in flush
    self._shared.flush(parser)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/gloo/glir.py", line 504, in flush
    parser.parse(self._filter(self.clear(), parser))
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/gloo/glir.py", line 822, in parse
    self._parse(command)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/gloo/glir.py", line 779, in _parse
    'does not exist' % (cmd, id_))
RuntimeError: Cannot SIZE object 85 because it does not exist
WARNING: Error drawing visual <Volume at 0x7f28139a6fd0>
Traceback (most recent call last):
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/app/backends/_qt.py", line 903, in paintGL
    self._vispy_canvas.events.draw(region=None)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/util/event.py", line 453, in __call__
    self._invoke_callback(cb, event)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/util/event.py", line 473, in _invoke_callback
    self, cb_event=(cb, event))
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/util/event.py", line 469, in _invoke_callback
    cb(event)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/scene/canvas.py", line 218, in on_draw
    self._draw_scene()
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/scene/canvas.py", line 277, in _draw_scene
    self.draw_visual(self.scene)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/scene/canvas.py", line 315, in draw_visual
    node.draw()
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/scene/visuals.py", line 103, in draw
    self._visual_superclass.draw(self)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/visuals/visual.py", line 452, in draw
    self._vshare.index_buffer)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/visuals/shaders/program.py", line 102, in draw
    Program.draw(self, *args, **kwargs)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/gloo/program.py", line 526, in draw
    canvas.context.flush_commands()
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/gloo/context.py", line 172, in flush_commands
    self.glir.flush(self.shared.parser)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/gloo/glir.py", line 582, in flush
    self._shared.flush(parser)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/gloo/glir.py", line 504, in flush
    parser.parse(self._filter(self.clear(), parser))
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/gloo/glir.py", line 822, in parse
    self._parse(command)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/gloo/glir.py", line 779, in _parse
    'does not exist' % (cmd, id_))
RuntimeError: Cannot SIZE object 85 because it does not exist
WARNING: Error drawing visual <Volume at 0x7f28139a6fd0>
Traceback (most recent call last):
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/app/backends/_qt.py", line 903, in paintGL
    self._vispy_canvas.events.draw(region=None)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/util/event.py", line 453, in __call__
    self._invoke_callback(cb, event)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/util/event.py", line 473, in _invoke_callback
    self, cb_event=(cb, event))
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/util/event.py", line 469, in _invoke_callback
    cb(event)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/scene/canvas.py", line 218, in on_draw
    self._draw_scene()
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/scene/canvas.py", line 277, in _draw_scene
    self.draw_visual(self.scene)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/scene/canvas.py", line 315, in draw_visual
    node.draw()
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/scene/visuals.py", line 103, in draw
    self._visual_superclass.draw(self)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/visuals/visual.py", line 452, in draw
    self._vshare.index_buffer)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/visuals/shaders/program.py", line 102, in draw
    Program.draw(self, *args, **kwargs)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/gloo/program.py", line 526, in draw
    canvas.context.flush_commands()
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/gloo/context.py", line 172, in flush_commands
    self.glir.flush(self.shared.parser)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/gloo/glir.py", line 582, in flush
    self._shared.flush(parser)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/gloo/glir.py", line 504, in flush
    parser.parse(self._filter(self.clear(), parser))
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/gloo/glir.py", line 822, in parse
    self._parse(command)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/gloo/glir.py", line 779, in _parse
    'does not exist' % (cmd, id_))
RuntimeError: Cannot SIZE object 85 because it does not exist
WARNING: Error drawing visual <Volume at 0x7f28139a6fd0>
Traceback (most recent call last):
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/app/backends/_qt.py", line 903, in paintGL
    self._vispy_canvas.events.draw(region=None)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/util/event.py", line 453, in __call__
    self._invoke_callback(cb, event)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/util/event.py", line 473, in _invoke_callback
    self, cb_event=(cb, event))
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/util/event.py", line 469, in _invoke_callback
    cb(event)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/scene/canvas.py", line 218, in on_draw
    self._draw_scene()
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/scene/canvas.py", line 277, in _draw_scene
    self.draw_visual(self.scene)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/scene/canvas.py", line 315, in draw_visual
    node.draw()
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/scene/visuals.py", line 103, in draw
    self._visual_superclass.draw(self)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/visuals/visual.py", line 452, in draw
    self._vshare.index_buffer)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/visuals/shaders/program.py", line 102, in draw
    Program.draw(self, *args, **kwargs)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/gloo/program.py", line 526, in draw
    canvas.context.flush_commands()
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/gloo/context.py", line 172, in flush_commands
    self.glir.flush(self.shared.parser)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/gloo/glir.py", line 582, in flush
    self._shared.flush(parser)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/gloo/glir.py", line 504, in flush
    parser.parse(self._filter(self.clear(), parser))
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/gloo/glir.py", line 822, in parse
    self._parse(command)
  File "/home/charles/anaconda3/envs/wbfm/lib/python3.7/site-packages/vispy/gloo/glir.py", line 779, in _parse
    'does not exist' % (cmd, id_))
RuntimeError: Cannot SIZE object 85 because it does not exist

## Additional context

1. Possibly related to: https://github.com/napari/napari/issues/4587
2. Does NOT happen in 0.4.13, info here:

napari: 0.4.13
Platform: Linux-5.15.0-40-generic-x86_64-with-debian-bookworm-sid
System: Ubuntu 22.04 LTS
Python: 3.7.12 | packaged by conda-forge | (default, Oct 26 2021, 06:08:21) [GCC 9.4.0]
Qt: 5.15.2
PyQt5: 5.15.4
NumPy: 1.20.3
SciPy: 1.5.3
Dask: 2022.02.0
VisPy: 0.9.4

OpenGL:
- GL version: 4.6.0 NVIDIA 470.129.06
- MAX_TEXTURE_SIZE: 32768

Screens:
- screen 1: resolution 3840x1600, scale 1.0

Plugins:
- console: 0.0.4
- napari-animated-gif-io: 0.1.1
- napari-tools-menu: 0.1.9
- scikit-image: 0.4.13
- svg: 0.1.5

**Comment by perlman** [comment]
I believe you are seeing an incompatibility between napari & vispy versions.
`setup.cfg` for `v0.4.14` specifies `vispy>=0.9.4`, but I don't believe support for vispy 1.10 came until later.

I'd recommend trying to install an older vispy into your environment, e.g., `pip install vispy==0.9.4`.

Current versions of napari are more strict with vispy versions, e.g. the current version, `v0.4.16` requires `vispy>=0.10.0,<0.11`.

**Comment by Charles-Fieseler-Vienna** [comment]
Thank you for the quick response! I thought I read that discussion carefully, but I clearly missed things
