### ISSUE TITLE
Builtin reader plugin is not handling HDF5 files correctly

### ISSUE THREAD

**Issue by GenevieveBuckley** [napari/napari#4834]
## 🐛 Bug

Although HDF5 files are listed as accepted by the napari builtin reader, attempting to 
drag and drop a `.hdf5` file into napari produces an error.

Is there an extra, optional dependency I need to install? I've tried installing [h5py](https://www.h5py.org/).

## To Reproduce

1. Download [one of the CREMI HDF5 files](https://cremi.org/data/)) as an example dataset
2. Install napari into a clean conda environment
3. Launch napari, then drag and drop the file onto the canvas, and observe the error message.

<details>
<summary>Error message (click to expand):</summary>

```pytho-traceback
Traceback (most recent call last):
  File "/Users/genevieb/Documents/GitHub/napari/napari/components/viewer_model.py", line 1075, in _open_or_raise_error
    added = self._add_layers_with_plugins(
  File "/Users/genevieb/Documents/GitHub/napari/napari/components/viewer_model.py", line 1165, in _add_layers_with_plugins
    layer_data, hookimpl = read_data_with_plugins(
  File "/Users/genevieb/Documents/GitHub/napari/napari/plugins/io.py", line 75, in read_data_with_plugins
    res = _npe2.read(paths, plugin, stack=stack)
  File "/Users/genevieb/Documents/GitHub/napari/napari/plugins/_npe2.py", line 56, in read
    raise e from e
  File "/Users/genevieb/Documents/GitHub/napari/napari/plugins/_npe2.py", line 50, in read
    layer_data, reader = io_utils.read_get_reader(
  File "/Users/genevieb/mambaforge/envs/napari-dev/lib/python3.9/site-packages/npe2/io_utils.py", line 56, in read_get_reader
    return _read(
  File "/Users/genevieb/mambaforge/envs/napari-dev/lib/python3.9/site-packages/npe2/io_utils.py", line 153, in _read
    layer_data = read_func(paths, stack=stack)
  File "/Users/genevieb/mambaforge/envs/napari-dev/lib/python3.9/site-packages/npe2/manifest/contributions/_readers.py", line 60, in npe1_compat
    return callable_(path)  # type: ignore
  File "/Users/genevieb/Documents/GitHub/napari/napari/types.py", line 153, in reader_function
    result = func(*args, **kwargs)
  File "/Users/genevieb/Documents/GitHub/napari/napari/utils/io.py", line 257, in magic_imread
    image = imread(filename)
  File "/Users/genevieb/Documents/GitHub/napari/napari/utils/io.py", line 150, in imread
    return imageio.imread(filename)
  File "/Users/genevieb/mambaforge/envs/napari-dev/lib/python3.9/site-packages/imageio/v2.py", line 201, in imread
    return file.read(index=0, **kwargs)
  File "/Users/genevieb/mambaforge/envs/napari-dev/lib/python3.9/site-packages/imageio/core/legacy_plugin_wrapper.py", line 145, in read
    reader = self.legacy_get_reader(**kwargs)
  File "/Users/genevieb/mambaforge/envs/napari-dev/lib/python3.9/site-packages/imageio/core/legacy_plugin_wrapper.py", line 114, in legacy_get_reader
    return self._format.get_reader(self._request)
  File "/Users/genevieb/mambaforge/envs/napari-dev/lib/python3.9/site-packages/imageio/core/format.py", line 220, in get_reader
    return self.Reader(self, request)
  File "/Users/genevieb/mambaforge/envs/napari-dev/lib/python3.9/site-packages/imageio/core/format.py", line 311, in __init__
    self._open(**self.request.kwargs.copy())
  File "/Users/genevieb/mambaforge/envs/napari-dev/lib/python3.9/site-packages/imageio/plugins/pillow_legacy.py", line 300, in _open
    pil_try_read(self._im)
  File "/Users/genevieb/mambaforge/envs/napari-dev/lib/python3.9/site-packages/imageio/plugins/pillow_legacy.py", line 665, in pil_try_read
    raise ValueError(error_message)
ValueError: Could not load ""
Reason: "cannot find loader for this HDF5 file"
Please see documentation at: http://pillow.readthedocs.io/en/latest/installation.html#external-libraries

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/genevieb/Documents/GitHub/napari/napari/_qt/qt_viewer.py", line 765, in _qt_open
    self.viewer.open(
  File "/Users/genevieb/Documents/GitHub/napari/napari/components/viewer_model.py", line 971, in open
    layers = self._open_or_raise_error(
  File "/Users/genevieb/Documents/GitHub/napari/napari/components/viewer_model.py", line 1084, in _open_or_raise_error
    raise ReaderPluginError(
napari.errors.reader_errors.ReaderPluginError: Tried opening with napari, but failed.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/genevieb/Documents/GitHub/napari/napari/_qt/qt_viewer.py", line 1118, in dropEvent
    self._qt_open([filename], stack=bool(shift_down))
  File "/Users/genevieb/Documents/GitHub/napari/napari/_qt/qt_viewer.py", line 773, in _qt_open
    handle_gui_reading(
  File "/Users/genevieb/Documents/GitHub/napari/napari/_qt/dialogs/qt_reader_dialog.py", line 146, in handle_gui_reading
    readers = prepare_remaining_readers(paths, plugin_name, error)
  File "/Users/genevieb/Documents/GitHub/napari/napari/_qt/dialogs/qt_reader_dialog.py", line 201, in prepare_remaining_readers
    raise ReaderPluginError(
napari.errors.reader_errors.ReaderPluginError: Tried to read /Volumes/GENEVIEVE/data/public-datasets/cremi/test.hdf5 with plugin napari, because it was associated with that file extension/because it is the only plugin capable of reading that path, but it gave an error. Try associating a different plugin or installing a different plugin for this kind of file.

If you suspect this is an IPython 8.4.0 bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True
```

</details>

## Expected behavior

I expected napari to open (at least some) of the datasets contained in the HDF5 file.

## Environment

 - Please copy and paste the information at napari info option in help menubar here:
napari: 0.4.13.dev558+g338dc3ac.d20220614
Platform: macOS-12.3.1-arm64-arm-64bit
System: MacOS 12.3.1
Python: 3.9.13 | packaged by conda-forge | (main, May 27 2022, 17:00:33) [Clang 13.0.1 ]
Qt: 5.15.2
PyQt5: 5.15.4
NumPy: 1.22.4
SciPy: 1.8.1
Dask: 2022.6.0
VisPy: 0.10.0

OpenGL:
- GL version: 2.1 Metal - 76.3
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1440x900, scale 2.0
- screen 2: resolution 3440x1440, scale 1.0

 - Any other relevant information:

## Additional context

Here is where `.hdf5`, `.hdf`, and `.h5` files are all listed as supported by napari's built-in reader:
https://github.com/napari/napari/blob/c33de311e851f9ffa0875f971afa066a16304a3f/napari/builtins.yaml#L135

napari is passing off the file to imageio, which in turn passes it off to pillow, which fails to open the file. This is the last resort, we couldn't find anything else that said it knew how to handle these files option.

I found this page: https://imageio.readthedocs.io/en/v2.5.0/format_hdf5-pil.html
...but the pillow version I have seems much newer than this
```python
In [3]: import PIL
In [4]: PIL.__version__
Out[4]: '9.1.1'
```

 I've also poked around with a couple of napari plugins:
* ([napari-hdf5-labels-io](https://github.com/yapic/napari-hdf5-labels-io) which seems to require a plugin specific format; and 
* [napari-hdf5](https://github.com/portugueslab/napari-hdf5) which seems incomplete).

**Comment by Czaki** [comment]
I think that h5 support should be removed from builtins as h5 is not a specific file format but rather a generic container that inner structure depends on an author's idea.

**Comment by kephale** [comment]
I was pointed to this issue by @yunhal because I also had expected some basic hdf5 reading/writing support.

I do understand @Czaki's point because hdf5 is just a container file format, but there are some reasonable default behaviors that would align with `napari` usage. For example, when using the N5 Viewer plugin in Fiji from https://github.com/bigdataviewer to open an HDF5 you get a generic hierarchy of the HDF5's contents:

<img width="619" alt="image" src="https://user-images.githubusercontent.com/400105/195120800-e88f8ceb-3f53-4480-9c8b-42c8856aabf8.png">

It is reasonable that this should be done by a plugin particularly because h5py isn't a `napari` dependency. However, this is a pretty commonly used feature that isn't available. 

The issues that @GenevieveBuckley points out about the existing plugins either having a specific format or not working are definitely important because it makes it harder for the team to realize that HDF5 reading/writing is not properly supported in `napari` right now.

**Comment by yunhal** [comment]
I am new to the napari viewer. I find that napari is very attractive because it is not only an interactive viewer but also an GUI app (not from python script). As a GUI app, I expect the napari program to handle a hdf5 file. I understand that HDF5 can have different internal file structure/metadata but it is still quite doable to handle that. To give you an idea, One of the HDF5/NETCDF4 viewers, Panoply (developed by NASA GISS), is designed for Earth Science, but this app handles bio HDF5 files just fine.  I attached the screenshot of Panoply here to give you an idea. Panoply shows a file structure with metadata information and a user can select which variable to visualize. It would be great if napari can do a similar job. 

<img width="1264" alt="Screen Shot 2022-10-11 at 10 17 58 AM" src="https://user-images.githubusercontent.com/28872346/195124351-b6aab937-e865-4149-b689-7bf2b9456844.png">

**Comment by Czaki** [comment]
The general problem needs to be handled on the napari side (and maybe a good target for 0.5) releases is that napari provides options for load/save operations (load/save data without user interactions), but does not provide import/export operations (load/save with some interactions from the user side). 

Currently, such interfaces like in @kephale and @yunhal show in their comments could be implemented as a plugin (as for 0.5.0, we will wait at least until January). If someone needs help implementing such a plugin, I could help/support them with knowledge about napari.

**Comment by yunhal** [comment]
Thanks @kephale and @Czaki for the response.  Since the current plugins do not support to read generic hdf5 files, I would be interested in building such plugin.  Having said that, I am currently working on a plugin to handle netcdf files for napari.  I will reach out for some help when I need. Thanks!

**Comment by psobolewskiPhD** [comment]
For anyone looking at this, there are a few plugins that appear to address this:
The simple approach of just loading datasets as images:
https://www.napari-hub.org/plugins/napari-h5
Github: https://github.com/rosalindfranklininstitute/napari-h5

And an approach using a widget to select things:
https://www.napari-hub.org/plugins/napari-hierarchical
GitHub: https://github.com/jwindhager/napari-hierarchical
Alas it needs to be updated for npe2 and modern napari. Still a starting point.

Frankly, I think we should close this.
We could consider removing the extensions, but there probably are hdf5 files that imageio can open, so I think we're better of leaving them, so it's possible.
