### ISSUE TITLE
Issue with 3D visualization of images and vispy with MacOs M1 chips (with possible workaround/fix)

### ISSUE THREAD

**Issue by leoguignard** [napari/napari#4918]
Hello again,

Still trying to make napari work as well as I can on __MacOs M1 chips__.

## 🐛 Bug

When installing napari the way described in #4917, napari runs but 3D visualisation of intensity and label images does not work.

## To Reproduce

Steps to reproduce the behaviour:
```
$ conda create -n test
$ conda install numpy napari
$ python
```
then, in `python` I run:
```python
import numpy as np
from napari import Viewer

im = (np.random.random((10, 10, 10)) * 10000).astype(np.uint16)
v = Viewer()
v.add_image(im)
```
which opens the napari viewer as intended. But when I click on the `toggle ndisplay` button I get the following error:
```
WARNING: Unsubstituted placeholders in code: ['$sample', '$sample', '$sample', '$sample', '$sample', '$sample', '$sample']
  replacements made: ['viewtransformf', 'raycasting_setup', 'before_loop', 'in_loop', 'after_loop', 'sampler_type', 'post', 'pre', 'clip_with_planes', 'cmap', 'get_data']
WARNING: Error drawing visual <Volume at 0x14c322cb0>
WARNING: Traceback (most recent call last):
  File "/Users/leo.guignard/miniforge3/envs/test/lib/python3.10/site-packages/vispy/app/backends/_qt.py", line 903, in paintGL
    self._vispy_canvas.events.draw(region=None)
  File "/Users/leo.guignard/miniforge3/envs/test/lib/python3.10/site-packages/vispy/util/event.py", line 453, in __call__
    self._invoke_callback(cb, event)
  File "/Users/leo.guignard/miniforge3/envs/test/lib/python3.10/site-packages/vispy/util/event.py", line 471, in _invoke_callback
    _handle_exception(self.ignore_callback_errors,
  File "/Users/leo.guignard/miniforge3/envs/test/lib/python3.10/site-packages/vispy/util/event.py", line 469, in _invoke_callback
    cb(event)
  File "/Users/leo.guignard/miniforge3/envs/test/lib/python3.10/site-packages/vispy/scene/canvas.py", line 218, in on_draw
    self._draw_scene()
  File "/Users/leo.guignard/miniforge3/envs/test/lib/python3.10/site-packages/vispy/scene/canvas.py", line 277, in _draw_scene
    self.draw_visual(self.scene)
  File "/Users/leo.guignard/miniforge3/envs/test/lib/python3.10/site-packages/vispy/scene/canvas.py", line 315, in draw_visual
    node.draw()
  File "/Users/leo.guignard/miniforge3/envs/test/lib/python3.10/site-packages/vispy/scene/visuals.py", line 103, in draw
    self._visual_superclass.draw(self)
  File "/Users/leo.guignard/miniforge3/envs/test/lib/python3.10/site-packages/vispy/visuals/visual.py", line 451, in draw
    self._program.draw(self._vshare.draw_mode,
  File "/Users/leo.guignard/miniforge3/envs/test/lib/python3.10/site-packages/vispy/visuals/shaders/program.py", line 102, in draw
    Program.draw(self, *args, **kwargs)
  File "/Users/leo.guignard/miniforge3/envs/test/lib/python3.10/site-packages/vispy/gloo/program.py", line 526, in draw
    canvas.context.flush_commands()
  File "/Users/leo.guignard/miniforge3/envs/test/lib/python3.10/site-packages/vispy/gloo/context.py", line 172, in flush_commands
    self.glir.flush(self.shared.parser)
  File "/Users/leo.guignard/miniforge3/envs/test/lib/python3.10/site-packages/vispy/gloo/glir.py", line 582, in flush
    self._shared.flush(parser)
  File "/Users/leo.guignard/miniforge3/envs/test/lib/python3.10/site-packages/vispy/gloo/glir.py", line 504, in flush
    parser.parse(self._filter(self.clear(), parser))
  File "/Users/leo.guignard/miniforge3/envs/test/lib/python3.10/site-packages/vispy/gloo/glir.py", line 822, in parse
    self._parse(command)
  File "/Users/leo.guignard/miniforge3/envs/test/lib/python3.10/site-packages/vispy/gloo/glir.py", line 792, in _parse
    ob.set_data(*args)
  File "/Users/leo.guignard/miniforge3/envs/test/lib/python3.10/site-packages/vispy/gloo/glir.py", line 931, in set_data
    raise RuntimeError("Shader compilation error in %s:\n%s" %
RuntimeError: Shader compilation error in GL_FRAGMENT_SHADER:
    on line 329: '<' : syntax error: syntax error
      vec4 color0 = $sample(u_volumetex, loc);
[1]    51812 abort      python
```

## Expected behavior

Display the 3D view.

## Environment

```
napari: 0.4.14
Platform: macOS-12.2.1-arm64-arm-64bit
System: MacOS 12.2.1
Python: 3.10.5 | packaged by conda-forge | (main, Jun 14 2022, 07:07:06) [Clang 13.0.1 ]
Qt: 5.15.4
PyQt5: 5.15.7
NumPy: 1.23.1
SciPy: 1.9.0
Dask: 2022.8.0
VisPy: 0.11.0

OpenGL:
- GL version: 2.1 Metal - 76.3
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1512x982, scale 2.0

Plugins:
- console: 0.0.4
- scikit-image: 0.4.14
- svg: 0.1.6
```

## Additional context

Now I can fix that specific issue by using a downgraded version of `vispy`:
```
$ conda create -n test
$ conda activate test
$ conda install numpy vispy=0.10.0 napari
$ python
```
then in `python` I run:
```python
import numpy as np
from napari import Viewer

im = (np.random.random((10, 10, 10)) * 10000).astype(np.uint16)
v = Viewer()
v.add_image(im)
```
then click on the `toggle ndisplay` button and it works as intended.

That being said, it is specified in the `napari` config file that `vispy` should be of version `0.11.0` or higher which might mean that some other functionalities of `napari` will not be working.

**Comment by Czaki** [comment]
The core problem here is that you installed napari 0.4.14. Since napari 0.4.16, we pin not only the lower version of napari but also the upper.

For napari 0.4.14, you need to install vispy in version 0.9.6.

You have installed version 0.4.14 because of some problem with conda described in #4891

**Comment by leoguignard** [comment]
Ok it seems to have solve the issue indeed, sorry for missing the other issue and thanks a lot for the quick answer!
