### ISSUE TITLE
TypeError when running gallery examples

### ISSUE THREAD

**Issue by melissawm** [napari/napari#4957]
## 📚 Documentation

When building the docs from `main`, the gallery outputs several `TypeError` messages related to `napari.Viewer`:

```
Traceback (most recent call last):
  File "/Users/mwebermendonca/napari/examples/custom_mouse_functions.py", line 16, in <module>
    viewer = napari.Viewer()
TypeError: 'module' object is not callable
```

Full output:
<details>

```
Sphinx-Gallery successfully executed 62 out of 80 files subselected by:

    gallery_conf["filename_pattern"] = '/*.py'
    gallery_conf["ignore_pattern"]   = 'README.rst|/*_.py'

after excluding 0 files that had previously been run (based on MD5).

WARNING: Here is a summary of the problems encountered when running the examples

Unexpected failing examples:
/Users/mwebermendonca/napari/examples/custom_mouse_functions.py failed leaving traceback:
Traceback (most recent call last):
  File "/Users/mwebermendonca/napari/examples/custom_mouse_functions.py", line 16, in <module>
    viewer = napari.Viewer()
TypeError: 'module' object is not callable


/Users/mwebermendonca/napari/examples/magic_image_arithmetic.py failed leaving traceback:
Traceback (most recent call last):
  File "/Users/mwebermendonca/napari/examples/magic_image_arithmetic.py", line 45, in <module>
    viewer = napari.Viewer()
TypeError: 'module' object is not callable


/Users/mwebermendonca/napari/examples/tracks_3d_with_graph.py failed leaving traceback:
Traceback (most recent call last):
  File "/Users/mwebermendonca/napari/examples/tracks_3d_with_graph.py", line 48, in <module>
    viewer = napari.Viewer(ndisplay=3)
TypeError: 'module' object is not callable


/Users/mwebermendonca/napari/examples/add_vectors_color_by_angle.py failed leaving traceback:
Traceback (most recent call last):
  File "/Users/mwebermendonca/napari/examples/add_vectors_color_by_angle.py", line 16, in <module>
    viewer = napari.Viewer()
TypeError: 'module' object is not callable


/Users/mwebermendonca/napari/examples/update_console.py failed leaving traceback:
Traceback (most recent call last):
  File "/Users/mwebermendonca/napari/examples/update_console.py", line 16, in <module>
    viewer = napari.Viewer()
TypeError: 'module' object is not callable


/Users/mwebermendonca/napari/examples/3Dimage_plane_rendering.py failed leaving traceback:
Traceback (most recent call last):
  File "/Users/mwebermendonca/napari/examples/3Dimage_plane_rendering.py", line 13, in <module>
    viewer = napari.Viewer(ndisplay=3)
TypeError: 'module' object is not callable


/Users/mwebermendonca/napari/examples/points-over-time.py failed leaving traceback:
Traceback (most recent call last):
  File "/Users/mwebermendonca/napari/examples/points-over-time.py", line 19, in <module>
    viewer = napari.Viewer(ndisplay=3)
TypeError: 'module' object is not callable


/Users/mwebermendonca/napari/examples/tracks_3d.py failed leaving traceback:
Traceback (most recent call last):
  File "/Users/mwebermendonca/napari/examples/tracks_3d.py", line 72, in <module>
    viewer = napari.Viewer(ndisplay=3)
TypeError: 'module' object is not callable


/Users/mwebermendonca/napari/examples/affine_transforms.py failed leaving traceback:
Traceback (most recent call last):
  File "/Users/mwebermendonca/napari/examples/affine_transforms.py", line 21, in <module>
    viewer = napari.Viewer()
TypeError: 'module' object is not callable


/Users/mwebermendonca/napari/examples/interactive_move_point_3d.py failed leaving traceback:
Traceback (most recent call last):
  File "/Users/mwebermendonca/napari/examples/interactive_move_point_3d.py", line 15, in <module>
    viewer = napari.Viewer(ndisplay=3)
TypeError: 'module' object is not callable


/Users/mwebermendonca/napari/examples/tracks_2d.py failed leaving traceback:
Traceback (most recent call last):
  File "/Users/mwebermendonca/napari/examples/tracks_2d.py", line 58, in <module>
    viewer = napari.Viewer()
TypeError: 'module' object is not callable


/Users/mwebermendonca/napari/examples/magic_parameter_sweep.py failed leaving traceback:
Traceback (most recent call last):
  File "/Users/mwebermendonca/napari/examples/magic_parameter_sweep.py", line 38, in <module>
    viewer = napari.Viewer()
TypeError: 'module' object is not callable


/Users/mwebermendonca/napari/examples/mouse_drag_callback.py failed leaving traceback:
Traceback (most recent call last):
  File "/Users/mwebermendonca/napari/examples/mouse_drag_callback.py", line 24, in <module>
    viewer = napari.Viewer()
TypeError: 'module' object is not callable


/Users/mwebermendonca/napari/examples/shapes_to_labels.py failed leaving traceback:
Traceback (most recent call last):
  File "/Users/mwebermendonca/napari/examples/shapes_to_labels.py", line 17, in <module>
    viewer = napari.Viewer()
TypeError: 'module' object is not callable


/Users/mwebermendonca/napari/examples/cursor_ray.py failed leaving traceback:
Traceback (most recent call last):
  File "/Users/mwebermendonca/napari/examples/cursor_ray.py", line 39, in <module>
    viewer = napari.Viewer(ndisplay=3)
TypeError: 'module' object is not callable


/Users/mwebermendonca/napari/examples/interactive_move_rectangle_3d.py failed leaving traceback:
Traceback (most recent call last):
  File "/Users/mwebermendonca/napari/examples/interactive_move_rectangle_3d.py", line 28, in <module>
    viewer = napari.Viewer(ndisplay=3)
TypeError: 'module' object is not callable


/Users/mwebermendonca/napari/examples/multiple_viewer_widget.py failed leaving traceback:
Traceback (most recent call last):
  File "/Users/mwebermendonca/napari/examples/multiple_viewer_widget.py", line 445, in <module>
    view = napari.Viewer()
TypeError: 'module' object is not callable


/Users/mwebermendonca/napari/examples/to_screenshot.py failed leaving traceback:
Traceback (most recent call last):
  File "/Users/mwebermendonca/napari/examples/to_screenshot.py", line 17, in <module>
    viewer = napari.Viewer()
TypeError: 'module' object is not callable
```

</details>

**Comment by Czaki** [comment]
Did you meet this error on your computer or CI?

**Comment by Czaki** [comment]
I determine that have `napari` directory in my `site-packages` that contain some non-python files and this cause problems with build docs. After I remove this directory I do not see such error.

**Comment by melissawm** [comment]
I believe this can be closed, please reopen otherwise.
