### ISSUE TITLE
Running from `napari` entry point fails after #5007

### ISSUE THREAD

**Issue by alisterburt** [napari/napari#5026]
## 🐛 Bug
running from our main entry point `napari` fails with the following error after #5007 

```sh
(napari) ➜  napari git:(6d18f104) ✗ napari  # succesful launch!
(napari) ➜  napari git:(f5cee842) ✗ napari
Traceback (most recent call last):
  File "/Users/alisterburt/mambaforge/envs/napari/bin/napari", line 8, in <module>
    sys.exit(main())
  File "/Users/alisterburt/programming/napari/napari/__main__.py", line 506, in main
    _run()
  File "/Users/alisterburt/programming/napari/napari/__main__.py", line 297, in _run
    viewer = Viewer()
  File "/Users/alisterburt/programming/napari/napari/viewer.py", line 65, in __init__
    _initialize_plugins()
  File "/Users/alisterburt/programming/napari/napari/plugins/__init__.py", line 44, in _initialize_plugins
    mf = PluginManifest.from_distribution('napari')
  File "/Users/alisterburt/mambaforge/envs/napari/lib/python3.10/site-packages/npe2/manifest/schema.py", line 225, in from_distribution
    dist = metadata.distribution(name)  # may raise PackageNotFoundError
  File "/Users/alisterburt/mambaforge/envs/napari/lib/python3.10/importlib/metadata/__init__.py", line 957, in distribution
    return Distribution.from_name(distribution_name)
  File "/Users/alisterburt/mambaforge/envs/napari/lib/python3.10/importlib/metadata/__init__.py", line 548, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for napari
```

I will revert for now because this is pretty bad - we should add a test for this usage too

cc @jaimergp @psobolewskiPhD

**Comment by psobolewskiPhD** [comment]
Hmm.
I used python 3.9 for testing, you're on 3.10?
I'll try making a 3.10 env later to test.

**Comment by alisterburt** [comment]
Yeah, do you know why that might make a difference?

```
napari: 0.4.16rc2.dev254+g703dbe1f
Platform: macOS-12.5.1-arm64-arm-64bit
System: MacOS 12.5.1
Python: 3.10.6 | packaged by conda-forge | (main, Aug 22 2022, 20:41:22) [Clang 13.0.1 ]
Qt: 5.15.4
PyQt5: 5.15.7
NumPy: 1.23.2
SciPy: 1.9.0
Dask: 2022.8.1
VisPy: 0.11.0

OpenGL:
  - GL version:  2.1 Metal - 76.3
  - MAX_TEXTURE_SIZE: 16384

Screens:
  - screen 1: resolution 1512x982, scale 2.0

Plugins:
  - napari-console: 0.0.4 (0 contributions)
  - napari-svg: 0.1.6 (2 contributions)
```

**Comment by Czaki** [comment]
there is a comment in code: `# may raise PackageNotFoundError`, and we do not handle it...

**Comment by psobolewskiPhD** [comment]
The plot thickens. Fresh 3.10 env and it works fine.
```
╰─ napari --info                                                   (test-env) ─╯
napari: 0.4.16rc2.dev263+g95482a52
Platform: macOS-12.5.1-arm64-arm-64bit
System: MacOS 12.5.1
Python: 3.10.6 | packaged by conda-forge | (main, Aug 22 2022, 20:41:22) [Clang 13.0.1 ]
Qt: 5.15.4
PyQt5: 5.15.7
NumPy: 1.23.2
SciPy: 1.9.1
Dask: 2022.9.0
VisPy: 0.11.0

OpenGL:
  - GL version:  2.1 Metal - 76.3
  - MAX_TEXTURE_SIZE: 16384

Screens:
  - screen 1: resolution 1680x1050, scale 2.0

Plugins:
  - napari: 0.4.16rc2.dev263+g95482a52 (77 contributions)
  - napari-console: 0.0.6 (0 contributions)
  - napari-svg: 0.1.6 (2 contributions)

```

**Comment by Czaki** [comment]
but in which directory? 
I think that we meet again path pollution problem.

**Comment by jaimergp** [comment]
+1 on needing to know the structure of working directory.

**Comment by psobolewskiPhD** [comment]
In my case it was in the parent of napari and in my user home dir.
Edit: I do see a diff in napari-console version? 🤷‍♂️ 
(it's a totally fresh 3.10 env with pyqt from conda-forge via mamba, then `pip install -e .`)

**Comment by Czaki** [comment]
and what in napari directory?

**Comment by alisterburt** [comment]
I reproduced both in directories containing a `napari` directory and without... will try outside of pycharm

**Comment by Czaki** [comment]
> I reproduced both in directories containing a `napari` directory and without... will try outside of pycharm

it may be source of problem.

**Comment by alisterburt** [comment]
outside of pycharm, in a directory with no `napari` subdirectory and the problem persists

**Comment by psobolewskiPhD** [comment]
What happens if you update napari-console?
```
╰─ pip list | grep napari                                          (test-env) ─╯
napari                        0.4.16rc2.dev263+g95482a52 /Users/piotrsobolewski/Dev/napari
napari-console                0.0.6
napari-plugin-engine          0.2.0
napari-svg                    0.1.6
```

Just in case, I checked out `main` and that still works too.

**Comment by jaimergp** [comment]
Two more things to try:

* Export `_NAPARI_RERUN_WITH_FIXES=1` and then run `napari`
* Same but try `python -m napari`

**Comment by alisterburt** [comment]
```sh
(napari) ➜  ~ export _NAPARI_RERUN_WITH_FIXES=1
(napari) ➜  ~ napari
Traceback (most recent call last):
  File "/Users/alisterburt/mambaforge/envs/napari/bin/napari", line 8, in <module>
    sys.exit(main())
  File "/Users/alisterburt/programming/napari/napari/__main__.py", line 506, in main
    _run()
  File "/Users/alisterburt/programming/napari/napari/__main__.py", line 297, in _run
    viewer = Viewer()
  File "/Users/alisterburt/programming/napari/napari/viewer.py", line 65, in __init__
    _initialize_plugins()
  File "/Users/alisterburt/programming/napari/napari/plugins/__init__.py", line 44, in _initialize_plugins
    mf = PluginManifest.from_distribution('napari')
  File "/Users/alisterburt/mambaforge/envs/napari/lib/python3.10/site-packages/npe2/manifest/schema.py", line 225, in from_distribution
    dist = metadata.distribution(name)  # may raise PackageNotFoundError
  File "/Users/alisterburt/mambaforge/envs/napari/lib/python3.10/importlib/metadata/__init__.py", line 957, in distribution
    return Distribution.from_name(distribution_name)
  File "/Users/alisterburt/mambaforge/envs/napari/lib/python3.10/importlib/metadata/__init__.py", line 548, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for napari
(napari) ➜  ~ python -m napari                    
Traceback (most recent call last):
  File "/Users/alisterburt/mambaforge/envs/napari/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/alisterburt/mambaforge/envs/napari/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/alisterburt/programming/napari/napari/__main__.py", line 510, in <module>
    sys.exit(main())
  File "/Users/alisterburt/programming/napari/napari/__main__.py", line 506, in main
    _run()
  File "/Users/alisterburt/programming/napari/napari/__main__.py", line 297, in _run
    viewer = Viewer()
  File "/Users/alisterburt/programming/napari/napari/viewer.py", line 65, in __init__
    _initialize_plugins()
  File "/Users/alisterburt/programming/napari/napari/plugins/__init__.py", line 44, in _initialize_plugins
    mf = PluginManifest.from_distribution('napari')
  File "/Users/alisterburt/mambaforge/envs/napari/lib/python3.10/site-packages/npe2/manifest/schema.py", line 225, in from_distribution
    dist = metadata.distribution(name)  # may raise PackageNotFoundError
  File "/Users/alisterburt/mambaforge/envs/napari/lib/python3.10/importlib/metadata/__init__.py", line 957, in distribution
    return Distribution.from_name(distribution_name)
  File "/Users/alisterburt/mambaforge/envs/napari/lib/python3.10/importlib/metadata/__init__.py", line 548, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for napari
```

**Comment by alisterburt** [comment]
updated napari console and no change

**Comment by jaimergp** [comment]
If `export _NAPARI_RERUN_WITH_FIXES=1` has been set, then the subprocess relaunch is not being used at all, so the problem lies somewhere else, I'd say.

**Comment by alisterburt** [comment]
very strange - the error is also reproducible in an ipython shell/from a script

**Comment by Czaki** [comment]
could you paste output of: 
```
ls `python -c 'import site; print(site.getsitepackages()[0])'` | grep napari
```

**Comment by psobolewskiPhD** [comment]
Does importlib.metadata work for you?
```
from importlib.metadata import metadata
list(metadata('wheel'))
```
Could try:
```
from importlib.metadata import version
version('napari')
```

**Comment by alisterburt** [comment]
```sh
(napari) ➜  ~ ls `python -c 'import site; print(site.getsitepackages()[0])'` | grep napari
__editable__.napari-0.4.16rc2.dev262+g50b3d733.pth
__editable___napari_0_4_16rc2_dev262_g50b3d733_finder.py
napari_console
napari_console-0.0.6.dist-info
napari_plugin_engine
napari_plugin_engine-0.2.0.dist-info
napari_sphinx_theme
napari_sphinx_theme-0.1.7.dist-info
napari_svg
napari_svg-0.1.6.dist-info
```

**Comment by alisterburt** [comment]
```ipython
In [1]: from importlib.metadata import metadata
   ...: list(metadata('wheel'))
Out[1]: 
['Metadata-Version',
 'Name',
 'Version',
 'Summary',
 'Home-page',
 'Author',
 'Author-email',
 'Maintainer',
 'Maintainer-email',
 'License',
 'Project-URL',
 'Project-URL',
 'Project-URL',
 'Keywords',
 'Platform',
 'Classifier',
 'Classifier',
 'Classifier',
 'Classifier',
 'Classifier',
 'Classifier',
 'Classifier',
 'Classifier',
 'Classifier',
 'Classifier',
 'Classifier',
 'Classifier',
 'Classifier',
 'Classifier',
 'Requires-Python',
 'Provides-Extra',
 'License-File',
 'Description']
```

```ipython
In [2]: from importlib.metadata import version
   ...: version('napari')
---------------------------------------------------------------------------
PackageNotFoundError                      Traceback (most recent call last)
Input In [2], in <cell line: 2>()
      1 from importlib.metadata import version
----> 2 version('napari')

File ~/mambaforge/envs/napari/lib/python3.10/importlib/metadata/__init__.py:984, in version(distribution_name)
    977 def version(distribution_name):
    978     """Get the version string for the named package.
    979 
    980     :param distribution_name: The name of the distribution package to query.
    981     :return: The version string for the package as defined in the package's
    982         "Version" metadata key.
    983     """
--> 984     return distribution(distribution_name).version

File ~/mambaforge/envs/napari/lib/python3.10/importlib/metadata/__init__.py:957, in distribution(distribution_name)
    951 def distribution(distribution_name):
    952     """Get the ``Distribution`` instance for the named package.
    953 
    954     :param distribution_name: The name of the distribution package as a string.
    955     :return: A ``Distribution`` instance (or subclass thereof).
    956     """
--> 957     return Distribution.from_name(distribution_name)

File ~/mambaforge/envs/napari/lib/python3.10/importlib/metadata/__init__.py:548, in Distribution.from_name(cls, name)
    546         return dist
    547 else:
--> 548     raise PackageNotFoundError(name)

PackageNotFoundError: No package metadata was found for napari
```

**Comment by psobolewskiPhD** [comment]
> could you paste output of:
> 
> ```
> ls `python -c 'import site; print(site.getsitepackages()[0])'` | grep napari
> ```

bash-3.2$ ls `python -c 'import site; print(site.getsitepackages()[0])'` | grep napari
__editable__.napari-0.4.16rc2.dev263+g95482a52.pth
__editable___napari_0_4_16rc2_dev263_g95482a52_finder.py
napari-0.4.16rc2.dev263+g95482a52.dist-info
napari_console
napari_console-0.0.6.dist-info
napari_plugin_engine
napari_plugin_engine-0.2.0.dist-info
napari_svg
napari_svg-0.1.6.dist-info

**Comment by Czaki** [comment]
reinstall napari with `pip -e` ? 

I do not see `dist-info` in your output.

**Comment by alisterburt** [comment]
that's likely the culprit - sorry, I should have caught this more quickly. 

I'm now facing that it gets stuck on

```
Obtaining file:///Users/alisterburt/programming/napari
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... \
```

but I think we can revert #5027

**Comment by Czaki** [comment]
So path polution again

**Comment by alisterburt** [comment]
all working, thank you all! I think so @Czaki 

Apologies for the noise here all
