### ISSUE TITLE
Sample data URI contributions do not support reader plugins returning null layer sentinel 

### ISSUE THREAD

**Issue by jwindhager** [napari/napari#5102]
## 🐛 Bug

Declarative [sample data URI contributions](https://napari.org/stable/plugins/contributions.html#sample-data-uri) that are read with a plugin  (e.g. explicitly by setting the `sample_data.reader_plugin` field) that provides a reader function returning a [null layer sentinel](https://github.com/napari/napari/blob/771b0cf092e06d02a48945fb63ce2fb9be46004b/napari/plugins/hook_specifications.py#L117-L118) `[(None,)]` raise a `TypeError`:

```bash
Traceback (most recent call last):
  File "/home/jonas/miniconda3/envs/napari-bioimage/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/jonas/miniconda3/envs/napari-bioimage/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/jonas/.vscode/extensions/ms-python.python-2022.14.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/home/jonas/.vscode/extensions/ms-python.python-2022.14.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/home/jonas/.vscode/extensions/ms-python.python-2022.14.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/home/jonas/.vscode/extensions/ms-python.python-2022.14.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/jonas/.vscode/extensions/ms-python.python-2022.14.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/jonas/.vscode/extensions/ms-python.python-2022.14.0/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/mnt/data/git/napari-bioimage/test.py", line 4, in <module>
    viewer.open_sample("napari-bioimage", "idr0052A", reader_plugin="napari-bioimage")
  File "/home/jonas/miniconda3/envs/napari-bioimage/lib/python3.10/site-packages/napari/components/viewer_model.py", line 837, in open_sample
    added.extend(self._add_layer_from_data(*datum))
  File "/home/jonas/miniconda3/envs/napari-bioimage/lib/python3.10/site-packages/napari/components/viewer_model.py", line 1237, in _add_layer_from_data
    raise exc
  File "/home/jonas/miniconda3/envs/napari-bioimage/lib/python3.10/site-packages/napari/components/viewer_model.py", line 1234, in _add_layer_from_data
    layer = add_method(data, **(meta or {}))
  File "/home/jonas/miniconda3/envs/napari-bioimage/lib/python3.10/site-packages/napari/components/viewer_model.py", line 745, in add_image
    layer = Image(data, **kwargs)
  File "/home/jonas/miniconda3/envs/napari-bioimage/lib/python3.10/site-packages/napari/layers/image/image.py", line 254, in __init__
    multiscale, data = guess_multiscale(data)
  File "/home/jonas/miniconda3/envs/napari-bioimage/lib/python3.10/site-packages/napari/layers/image/_image_utils.py", line 67, in guess_multiscale
    shapes = [d.shape for d in data]
TypeError: 'NoneType' object is not iterable
```

It seems that `Viewer.open_sample` (uses `Viewer._add_layer_from_data`), unlike `Viewer.open` (checks for the null layer sentinel in `Viewer._add_layers_with_plugins`) ignores the null layer sentinel.

## Expected behavior

The sample data should be loaded quietly, without new layers being added to the viewer.

## Environment

```
napari: 0.4.16
Platform: Linux-5.4.0-125-generic-x86_64-with-glibc2.31
System: Ubuntu 20.04.5 LTS
Python: 3.10.4 (main, Mar 31 2022, 08:41:55) [GCC 7.5.0]
Qt: 5.15.2
PyQt5: 5.15.7
NumPy: 1.23.3
SciPy: 1.9.1
Dask: 2022.9.0
VisPy: 0.10.0

OpenGL:
- GL version: 4.6 (Compatibility Profile) Mesa 21.2.6
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 2560x1440, scale 1.0
- screen 2: resolution 1920x1080, scale 1.0

Plugins:
- console: 0.0.6
- napari-bioimage: 0.1.dev6+ge4c2851.d20220917
- napari-svg: 0.1.6
- scikit-image: 0.4.16
```

The source code for the `napari-bioimage` plugin listed above is not yet publicly accessible.

**Comment by jwindhager** [comment]
Currently, a workaround is to use [sample data function contributions](https://napari.org/stable/plugins/contributions.html#sample-data-function) instead, with a function returning an empty list.

**Comment by ktsitsi** [comment]
Faced similar issue when trying to open a sample `URI` with my cookiecutter plugin on `napari 0.4.17`. Docs did not documented the constraint. `reader_plugin` when using `open_sample` in the `napari/_qt/file_menu.py:219` is not assigned even though set under the `sample_data` key in the `napari.yaml` file. I was able to make it work with a quick patch in the `napari/components/viewer_model:833` open_sample function, this way the `reader_plugin` value is set upon existence.
```python
 elif hasattr(data.__self__, 'uri'):
    if hasattr(data.__self__, 'reader_plugin'):
        reader_plugin = data.__self__.reader_plugin
    data = data.__self__.uri
```

**Comment by DragaDoncila** [comment]
Ok, so sorry for the delay folks 🙏 but I've had a look at this and there's a few things going on here.

With a Sample Data URI contribution like this,

```yaml
sample_data:
  - display_name: Some Random Data (10 x 10 x 10)
    key: random_data
    uri: "/Users/data/Tabuaeran_Kiribati.jpg"
```

Calling `viewer.open_sample("napari-demo", "random_data", reader_plugin="napari-demo")` where the `reader_plugin` returns `[(None,)]` works fine i.e. nothing happens. I think this is what you were reporting as throwing an error @jwindhager? If I change the contribution to use a command, then I can reproduce the behavior you reported i.e.

```yaml
sample_data:
  - display_name: Some Random Data (10 x 10 x 10)
    key: random_data
    command: napari-demo.generate_random_data # function returns [(None,)]
```

And I think that is a bug, yes.

@ktsitsi what you are reporting is also a bug - as you've correctly identified, we don't inspect the `reader_plugin` of the sample data URI.

PR incoming to fix these two things but @jwindhager if I've misunderstood anything about what you've reported, please let me know!

**Comment by psobolewskiPhD** [comment]
I think this is a proto version of https://github.com/napari/napari/issues/7834 that got overlooked.
I think we can close it, since we now explicitly check for valid LayerDataTuple https://github.com/napari/napari/pull/7851
cc: @DragaDoncila

**Comment by DragaDoncila** [comment]
@psobolewskiPhD I've just double checked and currently, if the user selects a plugin for a sample URI contribution and that plugin returns the null layer sentinel, there are no errors. If a user opens sample via a command contribution and that command returns a null layer sentinel, we get `ValueError: Sample "random_data" from plugin "napari-demo" did not return any valid layer data tuples.`

I think the latter is ok, it's what we decided in #7834, but it's a little weird that the URI contribution (for which you select a plugin, if multiple are available), doesn't error. What do you think?

**Comment by psobolewskiPhD** [comment]
It does sound a bit inconsistent. I wonder how common URI contributions are?

**Comment by DragaDoncila** [comment]
I'm not an expert with github search but [this search](https://github.com/search?q=path%3A**%2Fnapari.yaml+%22uri%3A%22&type=code) would imply there are not that many (and in my experience they're definitely more rare).
