### ISSUE TITLE
Text label positioning issues in 3D

### ISSUE THREAD

**Issue by dagewa** [napari/napari#5111]
## 🐛 Bug

I have been exploring how to add text labels to shapes in a 3D viewer. I wrote about this at https://forum.image.sc/t/display-text-for-shapes-in-3d/66677, but now I think it is clear there is at least one bug, so I'm "promoting" the discussion to an issue here. There are actually two sub-issues, which may have different causes. These are:

1. Whatever is set for `"anchor"` in the `text` dictionary is ignored, so that it always acts as if set to `"center"`
2. The `"translation"` may fail. In my original test case the lines were parallel to principal axes of the view. In that case, attempting to set translation crashes. If the lines are offset, it works.

## To Reproduce

This script demonstrates the crash:

```python
import numpy as np
import napari


def cell_edges(axes):
    astar, bstar, cstar = np.array(axes[0]), np.array(axes[1]), np.array(axes[2])
    farpoint = astar + bstar + cstar

    lines = [
        np.array([[0, 0, 0], astar]),
        np.array([[0, 0, 0], bstar]),
        np.array([[0, 0, 0], cstar]),
        np.array([astar, astar + bstar]),
        np.array([astar, astar + cstar]),
        np.array([bstar, bstar + astar]),
        np.array([bstar, bstar + cstar]),
        np.array([cstar, cstar + astar]),
        np.array([cstar, cstar + bstar]),
        np.array([farpoint, farpoint - astar]),
        np.array([farpoint, farpoint - bstar]),
        np.array([farpoint, farpoint - cstar]),
    ]
    return lines


if __name__ == "__main__":

    lines = cell_edges(((100, 0, 0), (0, 100, 0), (0, 0, 100)))
    # uncomment below to work:
    #lines = cell_edges(((100, 1, 0), (1, 100, 0), (1, 0, 100)))
    labels = ["a*", "b*", "c*"] + [""] * 9

    properties = {"label": labels}

    text_parameters = {
        "text": "label",
        "size": 14,
        "color": ["red",] * 12,
        "anchor": "center",
        "translation": [0, -5, 0],
    }

    viewer = napari.Viewer(ndisplay=3)

    viewer.add_shapes(
        lines,
        shape_type="line",
        edge_width=1,
        edge_color=["green",] * 12,
        properties=properties,
        text=text_parameters,
    )
    napari.run()
```
This results in a stacktrace ending with this:
```
ValueError: operands could not be broadcast together with shapes (4,2) (3,)
```
However, I discovered that uncommenting the specified line in the above script makes it work. That is, when the lines are not aligned exactly with the X,Y,Z view axes, then the `anchor_coords` that come from https://github.com/napari/napari/blob/b5c52e8b253ee8a6a11be31c480d78dcef80d4d5/napari/layers/utils/text_manager.py#L245
have the right shape.

## Expected behavior

1. When adding text labels to lines in 3D it should be possible to anchor at either end of the line, or in the middle.
2. It should be possible to offset the text label - at least in two dimensions, vertically and horizontally in the view. Possibly offset in the third (depth) dimension. This partially works, but not in the general case, as the reproducer shows.

## Environment

napari: 0.4.16rc2.dev210+gbe177d03
Platform: Linux-5.4.0-125-generic-x86_64-with-glibc2.27
System: Ubuntu 18.04.6 LTS
Python: 3.9.10 | packaged by conda-forge | (main, Feb 1 2022, 21:24:11) [GCC 9.4.0]
Qt: 5.12.9
PyQt5: 5.12.3
NumPy: 1.22.2
SciPy: 1.8.0
Dask: 2022.04.0
VisPy: 0.11.0

OpenGL:
- GL version: 3.0 Mesa 20.0.8
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1920x1080, scale 1.0
- screen 2: resolution 1920x1080, scale 1.0

**Comment by dagewa** [comment]
I'm finding this hard to track down. What I have been able to see is that when we get here
https://github.com/napari/napari/blob/c305b4607569b963ca4862172e9ef8a9715b52bc/napari/layers/shapes/shapes.py#L1537

during execution of the script above, the value of `ndisplay` is 2, and the script will go on to crash as described. However, when the second definition of `lines` is uncommented, when we get to this place, `ndisplay` is 3, and it works.

I have not worked out where this is getting set. The code paths seem to diverge somewhere in napari's event handling. It seems that in the version that works, we call this
https://github.com/napari/napari/blob/c305b4607569b963ca4862172e9ef8a9715b52bc/napari/components/viewer_model.py#L470

whilst in the version that crashes, we call this instead
https://github.com/napari/napari/blob/c305b4607569b963ca4862172e9ef8a9715b52bc/napari/_qt/qt_viewer.py#L525

To see the context here, my stacktrace from the crashing version is [error-crash.txt](https://github.com/napari/napari/files/9778359/error-crash.txt)

If I force an exception from the working version at the same place I get [forced-crash.txt](https://github.com/napari/napari/files/9778358/forced-crash.txt)

**Comment by dagewa** [comment]
Hi folks, has anyone had a chance to think about this? It's definitely a bug as shown by the simple reproducer script. I wish I could debug it further myself, but the alternate code paths are buried somewhere in the event handling and I haven't figured out how to track exactly what's happening.

**Comment by brisvag** [comment]
Hi @dagewa , sorry you had to wait, the issue must have slipped through the cracks!

I found the issue with problem 2: we need to index into `translation` so that only the displayed dimensions (in the correct order) are used. I opened a PR at #5321 with a fix.

As for the other one, I'm not sure, we need to dig a bit deeper. @andy-sweet might be of help here!

**Comment by brisvag** [comment]
Uhm, I might have been wrong :/

**Comment by brisvag** [comment]
Ok, I think I solved the issue. However, for number `2.`, it seems that it's by design that in 3D you cannot use for example the lower left anchor, and instead it will always fall back to `center`:

https://github.com/napari/napari/blob/8a78b3cc89fdcd7fd8595dcc714d63547240b30d/napari/layers/utils/_text_utils.py#L99-L103


I'm not sure why that's the case, but git `blame`s @kevinyamauchi, so maybe he can help us :)

**Comment by kevinyamauchi** [comment]
> I'm not sure why that's the case, but git blames @kevinyamauchi, so maybe he can help us :)

Sorry, I can't remember off the top of my head why we made that decision 😬 . If it seems unnecessary to restrict to `center` in 3D, I think it's fine to relax the constraint!

**Comment by dagewa** [comment]
Thanks @brisvag, #5321 is really great as that solves the issue that meant I couldn't work with some of my datasets. The other bit about text placement is more cosmetic. I hope #5321 makes it to release soon, as then I can actually roll out my reciprocal lattice viewer in https://github.com/dials/dials/pull/2229 to users for testing.

**Comment by brisvag** [comment]
@dagewa unfortunately it might be some time before this gets released. We just pushed `v0.4.17` yesterday, and the next planned release is `v0.5.0`, which will contain several breaking/big changes, so it might take longer than usual. There might be a possibility of a smaller `v0.4.18`, but likely only if big bugs show up in the wild, because it would be a lot of work to make it happen.

However, for the time being, maybe there's a workaround. What happens if you only provide a 2-dimensional translation, such as `[0, -5]`?

**Comment by dagewa** [comment]
Ah, is there a likely timeline for `v0.5.0` release? I can certainly still wait a bit longer. Now I have this fix on your branch I can continue working on some features for my viewer.

Back on `main` if I use `[0, -5]` as the translation, I get: 
```
ValueError: operands could not be broadcast together with shapes (12,3) (2,)
```

<details>
  <summary>full traceback</summary>
  
```
Traceback (most recent call last):
  File "/tmp/napari_test.py", line 45, in <module>
    viewer.add_shapes(
  File "/home/fcx32934/sw/napari/napari/components/viewer_model.py", line 5, in add_shapes
    import os
  File "/home/fcx32934/sw/cctbx/build/../conda_base/lib/python3.9/_collections_abc.py", line 1073, in append
    self.insert(len(self), value)
  File "/home/fcx32934/sw/napari/napari/components/layerlist.py", line 166, in insert
    super().insert(index, new_layer)
  File "/home/fcx32934/sw/napari/napari/utils/events/containers/_selectable_list.py", line 66, in insert
    super().insert(index, value)
  File "/home/fcx32934/sw/napari/napari/utils/events/containers/_evented_list.py", line 193, in insert
    self.events.inserted(index=index, value=value)
  File "/home/fcx32934/sw/napari/napari/utils/events/event.py", line 757, in __call__
    self._invoke_callback(cb, event if pass_event else None)
  File "/home/fcx32934/sw/napari/napari/utils/events/event.py", line 794, in _invoke_callback
    _handle_exception(
  File "/home/fcx32934/sw/napari/napari/utils/events/event.py", line 781, in _invoke_callback
    cb(event)
  File "/home/fcx32934/sw/napari/napari/components/viewer_model.py", line 508, in _on_add_layer
    self._update_layers(layers=[layer])
  File "/home/fcx32934/sw/napari/napari/components/viewer_model.py", line 354, in _update_layers
    layer._slice_dims(
  File "/home/fcx32934/sw/napari/napari/layers/base/base.py", line 923, in _slice_dims
    self._update_dims()
  File "/home/fcx32934/sw/napari/napari/layers/base/base.py", line 673, in _update_dims
    self.refresh()  # This call is need for invalidate cache of extent in LayerList. If you remove it pleas ad another workaround.
  File "/home/fcx32934/sw/napari/napari/layers/base/base.py", line 1139, in refresh
    self.events.set_data()  # refresh is called in _update_dims which means that extent cache is invalidated. Then, base on this event extent cache in layerlist is invalidated.
  File "/home/fcx32934/sw/napari/napari/utils/events/event.py", line 757, in __call__
    self._invoke_callback(cb, event if pass_event else None)
  File "/home/fcx32934/sw/napari/napari/utils/events/event.py", line 794, in _invoke_callback
    _handle_exception(
  File "/home/fcx32934/sw/napari/napari/utils/events/event.py", line 783, in _invoke_callback
    cb()
  File "/home/fcx32934/sw/napari/napari/_vispy/layers/shapes.py", line 57, in _on_data_change
    self._update_text(update_node=False)
  File "/home/fcx32934/sw/napari/napari/_vispy/layers/shapes.py", line 119, in _update_text
    update_text(node=self._get_text_node(), layer=self.layer)
  File "/home/fcx32934/sw/napari/napari/_vispy/utils/text.py", line 33, in update_text
    coords, anchor_x, anchor_y = layer._view_text_coords
  File "/home/fcx32934/sw/napari/napari/layers/shapes/shapes.py", line 1567, in _view_text_coords
    return self.text.compute_text_coords(sliced_in_view_coords, ndisplay)
  File "/home/fcx32934/sw/napari/napari/layers/utils/text_manager.py", line 252, in compute_text_coords
    text_coords = anchor_coords + self.translation
ValueError: operands could not be broadcast together with shapes (12,3) (2,)
```
</details>

**Comment by brisvag** [comment]
Yeah, no way around it... I guess you could just pass a scalar (`-5`) for now. It will be slightly off from the center, but at least it won't overlap with the line.

As for a timeline, hard to tell right now, but no less than a few of months I'm afraid :/

**Comment by dagewa** [comment]
Brilliant, the scalar actually works fine for now. I can go with that on the current release. Thanks!
