### ISSUE TITLE
Reading settings from an incompatible schema fails ungracefully

### ISSUE THREAD

**Issue by andy-sweet** [napari/napari#5314]
## 🐛 Bug

If napari tries to read the settings/preferences file, but fails, it does not start.

One common way this can occur is for people who have both a development install (i.e. some arbitrary commit on `main`) and at least one fixed version of napari in another environment. In this case, changes to `main` can break stable releases. See steps to reproduce for one way this can happen, though there may be many.

## To Reproduce

1. Create and activate an environment with napari==0.4.16
2. Run napari, then exit. This should create a preferences file in a user application directory (e.g. on macOS it may be `~/Library/Application\ Support/Napari/settings.yaml`).
3. Create and activate an environment with napari @ 6ba16c1af85ebb395633f6f18924599822a961e0
4. Run napari, open the preferences window, modify a keyboard shortcut, close the preferences window, then exit. This should edit the existing preferences file above.
5. Activate the v0.4.16 environment, open napari

<details>
<summary>When I go through these steps, I get the following error:</summary>

```
(napari-0-4-16) ➜  napari git:(main) napari
/Users/asweet/software/miniconda3/envs/napari-0-4-16/lib/python3.9/site-packages/napari/_qt/qt_viewer.py:339: UserWarning: Attempting to unbind an action which does not exists (napari:decrease_brush_size), this may have no effects. This can happen if your settings are out of date, if you upgraded napari, upgraded or deactivated a plugin, or made a typo in in your custom keybinding.
  action_manager.unbind_shortcut(action)
/Users/asweet/software/miniconda3/envs/napari-0-4-16/lib/python3.9/site-packages/napari/_qt/qt_viewer.py:339: UserWarning: Attempting to unbind an action which does not exists (napari:increase_brush_size), this may have no effects. This can happen if your settings are out of date, if you upgraded napari, upgraded or deactivated a plugin, or made a typo in in your custom keybinding.
  action_manager.unbind_shortcut(action)
/Users/asweet/software/miniconda3/envs/napari-0-4-16/lib/python3.9/site-packages/napari/_qt/qt_viewer.py:339: UserWarning: Attempting to unbind an action which does not exists (napari:toggle_preserve_labels), this may have no effects. This can happen if your settings are out of date, if you upgraded napari, upgraded or deactivated a plugin, or made a typo in in your custom keybinding.
  action_manager.unbind_shortcut(action)
/Users/asweet/software/miniconda3/envs/napari-0-4-16/lib/python3.9/site-packages/napari/_qt/qt_viewer.py:339: UserWarning: Attempting to unbind an action which does not exists (napari:select_all_in_slice), this may have no effects. This can happen if your settings are out of date, if you upgraded napari, upgraded or deactivated a plugin, or made a typo in in your custom keybinding.
  action_manager.unbind_shortcut(action)
/Users/asweet/software/miniconda3/envs/napari-0-4-16/lib/python3.9/site-packages/napari/_qt/qt_viewer.py:339: UserWarning: Attempting to unbind an action which does not exists (napari:select_all_data), this may have no effects. This can happen if your settings are out of date, if you upgraded napari, upgraded or deactivated a plugin, or made a typo in in your custom keybinding.
  action_manager.unbind_shortcut(action)
Traceback (most recent call last):
  File "/Users/asweet/software/miniconda3/envs/napari-0-4-16/bin/napari", line 8, in <module>
    sys.exit(main())
  File "/Users/asweet/software/miniconda3/envs/napari-0-4-16/lib/python3.9/site-packages/napari/__main__.py", line 446, in main
    _run()
  File "/Users/asweet/software/miniconda3/envs/napari-0-4-16/lib/python3.9/site-packages/napari/__main__.py", line 310, in _run
    viewer = Viewer()
  File "/Users/asweet/software/miniconda3/envs/napari-0-4-16/lib/python3.9/site-packages/napari/viewer.py", line 61, in __init__
    self._window = Window(self, show=show)
  File "/Users/asweet/software/miniconda3/envs/napari-0-4-16/lib/python3.9/site-packages/napari/_qt/qt_main_window.py", line 423, in __init__
    self._qt_window = _QtMainWindow(viewer)
  File "/Users/asweet/software/miniconda3/envs/napari-0-4-16/lib/python3.9/site-packages/napari/_qt/qt_main_window.py", line 81, in __init__
    self._qt_viewer = QtViewer(viewer, show_welcome_screen=True)
  File "/Users/asweet/software/miniconda3/envs/napari-0-4-16/lib/python3.9/site-packages/napari/_qt/qt_viewer.py", line 330, in __init__
    self._bind_shortcuts()
  File "/Users/asweet/software/miniconda3/envs/napari-0-4-16/lib/python3.9/site-packages/napari/_qt/qt_viewer.py", line 341, in _bind_shortcuts
    action_manager.bind_shortcut(action, shortcut)
  File "/Users/asweet/software/miniconda3/envs/napari-0-4-16/lib/python3.9/site-packages/napari/utils/action_manager.py", line 242, in bind_shortcut
    self._update_shortcut_bindings(name)
  File "/Users/asweet/software/miniconda3/envs/napari-0-4-16/lib/python3.9/site-packages/napari/utils/action_manager.py", line 174, in _update_shortcut_bindings
    km_provider.bind_key(shortcut, action.injected, overwrite=True)
  File "/Users/asweet/software/miniconda3/envs/napari-0-4-16/lib/python3.9/site-packages/napari/utils/key_bindings.py", line 274, in bind_key
    key = normalize_key_combo(key)
  File "/Users/asweet/software/miniconda3/envs/napari-0-4-16/lib/python3.9/site-packages/napari/utils/key_bindings.py", line 176, in normalize_key_combo
    raise TypeError(
TypeError: invalid key 
```

</details>

The warnings are a separate, but maybe related, issue that is less problematic.

## Expected behavior

At a minimum, I would expect napari to start, and warn me that the preferences file could not be read. An instruction to run `napari --reset` or delete that file and restart would also be very useful here. Maybe even better is an option to delete that file in the warning dialog.

In the best case, I would hope that settings between different versions/installations of napari could be isolated, would support forwards migration (i.e. when upgrading napari), and maybe even backwards migration.

## Environment

<details>
<summary>napari v0.4.16 conda env</summary>

```
(napari-0-4-16) ➜  napari git:(main) napari --info 
napari: 0.4.16
Platform: macOS-10.16-x86_64-i386-64bit
System: MacOS 12.6
Python: 3.9.13 (main, Aug 25 2022, 18:29:29)  [Clang 12.0.0 ]
Qt: 5.15.2
PyQt5: 5.15.7
NumPy: 1.23.3
SciPy: 1.9.1
Dask: 2022.9.1
VisPy: 0.10.0

OpenGL:
  - GL version:  2.1 INTEL-18.8.5
  - MAX_TEXTURE_SIZE: 16384

Screens:
  - screen 1: resolution 2560x1080, scale 1.0
  - screen 2: resolution 1440x900, scale 2.0

Plugins:
  - console: 0.0.6
  - napari-svg: 0.1.6
  - scikit-image: 0.4.16
```

</details>

<details>
<summary>napari dev conda env</summary>

```
(napari-dev) ➜  napari git:(main) napari --info
napari: 0.4.17rc6.dev2+g34351d967
Platform: macOS-10.16-x86_64-i386-64bit
System: MacOS 12.6
Python: 3.9.6 (default, Jul 30 2021, 09:31:09)  [Clang 10.0.0 ]
Qt: 5.15.2
PyQt5: 5.15.4
NumPy: 1.23.2
SciPy: 1.8.0
Dask: 2022.7.0
VisPy: 0.11.0
magicgui: 0.4.0
superqt: 0.3.2
in-n-out: 0.1.5
app-model: 0.1.0
npe2: 0.5.2

OpenGL:
  - GL version:  2.1 INTEL-18.8.5
  - MAX_TEXTURE_SIZE: 16384

Screens:
  - screen 1: resolution 2560x1080, scale 1.0
  - screen 2: resolution 1440x900, scale 2.0

Plugins:
  - napari: 0.4.17rc6.dev2+g34351d967 (77 contributions)
  - napari-animation: 0.1.dev298+ga955522 (2 contributions)
  - napari-bio-sample-data: 0.0.4 (10 contributions)
  - napari-blob-detection: 0.0.2 (4 contributions)
  - napari-console: 0.0.6 (0 contributions)
  - napari-ome-zarr: 0.5.2 (2 contributions)
  - napari-svg: 0.1.6 (2 contributions)
```

</details>

## Additional context

Related to https://github.com/napari/napari/issues/4697

This was found during v0.4.17 release testing - [see Zulip for more details](https://napari.zulipchat.com/#narrow/stream/215289-release/topic/0.2E4.2E17rc8/near/308055067).

**Comment by andy-sweet** [comment]
Though we have #4697, it's more of a feature, whereas this describes one related bug. Solutions might overlap, but might also be distinct.

**Comment by andy-sweet** [comment]
I did a quick test to see if bumping the [settings schema version](https://github.com/napari/napari/blob/1cc90a74211c6cbf3fc644da5866f9752cf1ac78/napari/settings/_napari_settings.py#L19) on my development branch would be a quick and easy fix for this, as I hoped that napari might detect that it's trying to read a schema from the future and fail gracefully or at least more informatively.

But I didn't see much success.

My steps were.

1. Activate my dev environment and switch to the `main` branch of napari.
2. Increase the minor number of `CURRENT_SCHEMA_VERSION`.
3. Change a preference value.
4. Activate a napari release environment (in this case a v0.4.17 RC where `CURRENT_SCHEMA_VERSION` could be read).

But this failed in a similar way. After inspecting the settings file, it looks like the schema version is not being written after my change (even after deleting the `settings.yaml` file), so I'll likely write up a separate bug for that.

**Comment by kcpevey** [comment]
I went through the steps you've described and I also got a TypeError, but it was slightly different:

<details><summary>Traceback</summary>

```
TypeError                                 Traceback (most recent call last)
Cell In [1], line 5
      2 import napari
      4 # create the viewer with an image
----> 5 viewer = napari.view_image(data.astronaut(), rgb=True)

File ~/miniconda3/envs/napari_0416/lib/python3.10/site-packages/napari/view_layers.py:142, in view_image(*args, **kwargs)
    140 @_merge_layer_viewer_sigs_docs
    141 def view_image(*args, **kwargs):
--> 142     return _make_viewer_then('add_image', args, kwargs)

File ~/miniconda3/envs/napari_0416/lib/python3.10/site-packages/napari/view_layers.py:122, in _make_viewer_then(add_method, args, kwargs)
    118 # separate dims kwargs because we want to set those after adding data
    119 dims_kwargs = {
    120     k: vkwargs.pop(k) for k in list(vkwargs) if k in _dims_params
    121 }
--> 122 viewer = Viewer(**vkwargs)
    123 kwargs.update(kwargs.pop("kwargs", {}))
    124 method = getattr(viewer, add_method)

File ~/miniconda3/envs/napari_0416/lib/python3.10/site-packages/napari/viewer.py:61, in Viewer.__init__(self, title, ndisplay, order, axis_labels, show)
     57 # having this import here makes all of Qt imported lazily, upon
     58 # instantiating the first Viewer.
     59 from .window import Window
---> 61 self._window = Window(self, show=show)
     62 self._instances.add(self)

File ~/miniconda3/envs/napari_0416/lib/python3.10/site-packages/napari/_qt/qt_main_window.py:423, in Window.__init__(self, viewer, show)
    420 self._unnamed_dockwidget_count = 1
    422 # Connect the Viewer and create the Main Window
--> 423 self._qt_window = _QtMainWindow(viewer)
    425 # connect theme events before collecting plugin-provided themes
    426 # to ensure icons from the plugins are generated correctly.
    427 _themes.events.added.connect(self._add_theme)

File ~/miniconda3/envs/napari_0416/lib/python3.10/site-packages/napari/_qt/qt_main_window.py:81, in _QtMainWindow.__init__(self, viewer, parent)
     79 super().__init__(parent)
     80 self._ev = None
---> 81 self._qt_viewer = QtViewer(viewer, show_welcome_screen=True)
     82 self._quit_app = False
     84 self.setWindowIcon(QIcon(self._window_icon))

File ~/miniconda3/envs/napari_0416/lib/python3.10/site-packages/napari/_qt/qt_viewer.py:330, in QtViewer.__init__(self, viewer, show_welcome_screen)
    327     self.chunk_receiver = None
    329 # bind shortcuts stored in settings last.
--> 330 self._bind_shortcuts()

File ~/miniconda3/envs/napari_0416/lib/python3.10/site-packages/napari/_qt/qt_viewer.py:341, in QtViewer._bind_shortcuts(self)
    339 action_manager.unbind_shortcut(action)
    340 for shortcut in shortcuts:
--> 341     action_manager.bind_shortcut(action, shortcut)

File ~/miniconda3/envs/napari_0416/lib/python3.10/site-packages/napari/utils/action_manager.py:242, in ActionManager.bind_shortcut(self, name, shortcut)
    240 self._validate_action_name(name)
    241 self._shortcuts[name].add(shortcut)
--> 242 self._update_shortcut_bindings(name)
    243 self._emit_shortcut_change(name, shortcut)

File ~/miniconda3/envs/napari_0416/lib/python3.10/site-packages/napari/utils/action_manager.py:174, in ActionManager._update_shortcut_bindings(self, name)
    166 if hasattr(km_provider, 'bind_key'):
    167     for shortcut in self._shortcuts[name]:
    168         # NOTE: it would be better if we could bind `self.trigger` here
    169         # as it allow the action manager to be a convenient choke point
   (...)
    172         # difficult at the moment, since `self.trigger(name)` is not a
    173         # generator function (but action.injected is)
--> 174         km_provider.bind_key(shortcut, action.injected, overwrite=True)

File ~/miniconda3/envs/napari_0416/lib/python3.10/site-packages/napari/utils/key_bindings.py:274, in bind_key(keymap, key, func, overwrite)
    271     return inner
    273 if key is not Ellipsis:
--> 274     key = normalize_key_combo(key)
    276 if func is not None and key in keymap and not overwrite:
    277     raise ValueError(
    278         trans._(
    279             'key combination {key} already used! specify \'overwrite=True\' to bypass this check',
   (...)
    282         )
    283     )

File ~/miniconda3/envs/napari_0416/lib/python3.10/site-packages/napari/utils/key_bindings.py:176, in normalize_key_combo(key_combo)
    173 key, modifiers = parse_key_combo(key_combo)
    175 if len(key) != 1 and key not in SPECIAL_KEYS:
--> 176     raise TypeError(
    177         trans._(
    178             'invalid key {key}',
    179             deferred=True,
    180             key=key,
    181         )
    182     )
    184 for modifier in modifiers:
    185     if modifier in KEY_SUBS.keys():

TypeError: invalid key Meta+C
```
</details>

One thing that strikes me is that the error is arising from 0.5.0/0.6.0 settings being applied to an older version of napari. There are migration tools in place, but they expect people to migrate from an older version, to a new version. 

Do you want to fail gracefully here or do you want to enable backwards migration?

>After inspecting the settings file, it looks like the schema version is not being written after my change (even after deleting the settings.yaml file), so I'll likely write up a separate bug for that.

This is because there is no migrator for those versions. It just sails past it [here](https://github.com/napari/napari/blob/main/napari/settings/_migrations.py#L28). There probably needs to be a catch or at least a warning added there for these cases.

**Comment by Czaki** [comment]
There are two opened PR connected with this problem:

#5333 - separate settings per environment. Remove the probability that older versions from different environments will crash and solve the problem of settings related to a different set of plugins in different environments
#5306 - separate settings per napari version. This will remove the problem that you describe.

**Comment by psobolewskiPhD** [comment]
@Czaki I think the schema issue is a different issue than the settings location.
The schema migration is supposed to handle migration between settings, at least from older to newer. But I didn't see from my reading the code, how older napari is to interpret newer schema.
#5306 ends up just being a work around for the newer -> older issue.
#5333 though ends up offering a feature, which is handling the same version in multiple envs. But it needs schema migration to work, at least from older to newer, so that updating napari in the same env works properly. It also solves the newer -> older issue.

**Comment by Czaki** [comment]
#5306 is solving this bug as there will be no import of older settings.

**Comment by psobolewskiPhD** [comment]
#5306 specifically does attempt to look for and import older settings. But it does not adress migrating the schema between older and newer napari.  It does mitigate the issue of older napari accessing newer napari settings. 

Edit: perhaps to make clearer: #5306 will attempt to *read* older settings. But it's the schema migrators https://github.com/napari/napari/blob/76a81e027e77b587d20ddbe9fa8e370dd4ce6c48/napari/settings/_migrations.py#L60 
that actually ensure the settings are properly interpreted.

**Comment by andy-sweet** [comment]
Sorry for the confusion here. Agreed that #5306 avoids the main issue here. We might also consider some extra safety measures (e.g. if we fail to read a settings file, then maybe just warn and continue) to avoid similar issues in the future that might be caused further changes. But I don't think that's too important.

I created #5316 to track the settings migration separately from this issue.

**Comment by psobolewskiPhD** [comment]
With #5333 and https://github.com/napari/napari/pull/7053 and assuming we keep up schema migrators, I think to close this we need a check if schema in settings.yaml is > current schema and suggest `napari --reset`
