### ISSUE TITLE
Napari with PySide2 backend broken

### ISSUE THREAD

**Issue by Chris-N-K** [napari/napari#5345]
## 🐛 Bug

I can not get `napari` to work with the PySide2 backend.
I tried several Python versions (9.8 to 9.10) and to install via `conda` or `pip`.
With `conda` even when generating the environment completely based on `napari` with `PySide2` the solver is not able to find a working configuration.
With `pip` the installation works but starting `napari` generates different errors depending on the python version.

When I use the `PyQt5` backend everything works perfectly.
I can use the PySide2 backend t run other Qt applications without any problems.

## To Reproduce

For conda:
1. conda create -n test -c conda-forge "napari=*=*pyside2"

For pip:
1. conda create -n test 'python==version'
2. conda activate test
3. pip install napari[pyside3]
4. napari

## Environment
Ubuntu 20.04.5 LTS
Python 3.8 to 3.10
napari 0.4.17
PySide2  5.15.6

## Error messages with the pip install
python 3.8 and 3.10
```
Traceback (most recent call last):
  File "/home/cnk/miniconda3/envs/test/bin/napari", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/cnk/miniconda3/envs/test/lib/python3.11/site-packages/napari/__main__.py", line 561, in main
    _run()
  File "/home/cnk/miniconda3/envs/test/lib/python3.11/site-packages/napari/__main__.py", line 327, in _run
    viewer = Viewer()
             ^^^^^^^^
  File "/home/cnk/miniconda3/envs/test/lib/python3.11/site-packages/napari/viewer.py", line 67, in __init__
    self._window = Window(self, show=show)
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cnk/miniconda3/envs/test/lib/python3.11/site-packages/napari/_qt/qt_main_window.py", line 463, in __init__
    self._qt_window = _QtMainWindow(viewer)
                      ^^^^^^^^^^^^^^^^^^^^^
  File "/home/cnk/miniconda3/envs/test/lib/python3.11/site-packages/napari/_qt/qt_main_window.py", line 88, in __init__
    self._qt_viewer = QtViewer(viewer, show_welcome_screen=True)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cnk/miniconda3/envs/test/lib/python3.11/site-packages/napari/_qt/qt_viewer.py", line 200, in __init__
    self.dims = QtDims(self.viewer.dims)
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cnk/miniconda3/envs/test/lib/python3.11/site-packages/napari/_qt/widgets/qt_dims.py", line 58, in __init__
    self._update_nsliders()
  File "/home/cnk/miniconda3/envs/test/lib/python3.11/site-packages/napari/_qt/widgets/qt_dims.py", line 123, in _update_nsliders
    self._create_sliders(self.dims.ndim)
  File "/home/cnk/miniconda3/envs/test/lib/python3.11/site-packages/napari/_qt/widgets/qt_dims.py", line 177, in _create_sliders
    slider_widget = QtDimSliderWidget(self, dim_axis)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cnk/miniconda3/envs/test/lib/python3.11/site-packages/napari/_qt/widgets/qt_dims_slider.py", line 90, in __init__
    self._create_play_button_widget()
  File "/home/cnk/miniconda3/envs/test/lib/python3.11/site-packages/napari/_qt/widgets/qt_dims_slider.py", line 168, in _create_play_button_widget
    self.play_button = QtPlayButton(
                       ^^^^^^^^^^^^^
  File "/home/cnk/miniconda3/envs/test/lib/python3.11/site-packages/napari/_qt/widgets/qt_dims_slider.py", line 502, in __init__
    self.popup = QtPopup(self)
                 ^^^^^^^^^^^^^
  File "/home/cnk/miniconda3/envs/test/lib/python3.11/site-packages/napari/_qt/dialogs/qt_modal.py", line 39, in __init__
    self.setWindowFlags(Qt.Popup | Qt.FramelessWindowHint)
TypeError: 'PySide2.QtCore.Qt.WindowType' object cannot be interpreted as an integer
```

python 3.9
```
TypeError: 'PySide2.QtCore.Qt.KeyboardModifier' object cannot be interpreted as an integer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/cnk/miniconda3/envs/test/bin/napari", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/cnk/miniconda3/envs/test/lib/python3.11/site-packages/napari/__main__.py", line 561, in main
    _run()
  File "/home/cnk/miniconda3/envs/test/lib/python3.11/site-packages/napari/__main__.py", line 218, in _run
    from napari import Viewer, run
  File "<frozen importlib._bootstrap>", line 1231, in _handle_fromlist
  File "/home/cnk/miniconda3/envs/test/lib/python3.11/site-packages/napari/_lazy.py", line 48, in __getattr__
    submod = import_module(
             ^^^^^^^^^^^^^^
  File "/home/cnk/miniconda3/envs/test/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cnk/miniconda3/envs/test/lib/python3.11/site-packages/napari/_event_loop.py", line 2, in <module>
    from ._qt.qt_event_loop import gui_qt, run
  File "/home/cnk/miniconda3/envs/test/lib/python3.11/site-packages/napari/_qt/__init__.py", line 54, in <module>
    from .qt_main_window import Window
  File "/home/cnk/miniconda3/envs/test/lib/python3.11/site-packages/napari/_qt/qt_main_window.py", line 56, in <module>
    from .qt_viewer import QtViewer
  File "/home/cnk/miniconda3/envs/test/lib/python3.11/site-packages/napari/_qt/qt_viewer.py", line 48, in <module>
    from .containers import QtLayerList
  File "/home/cnk/miniconda3/envs/test/lib/python3.11/site-packages/napari/_qt/containers/__init__.py", line 2, in <module>
    from .qt_layer_list import QtLayerList
  File "/home/cnk/miniconda3/envs/test/lib/python3.11/site-packages/napari/_qt/containers/qt_layer_list.py", line 10, in <module>
    from ._layer_delegate import LayerDelegate
  File "/home/cnk/miniconda3/envs/test/lib/python3.11/site-packages/napari/_qt/containers/_layer_delegate.py", line 46, in <module>
    from .._qapp_model import build_qmodel_menu
  File "/home/cnk/miniconda3/envs/test/lib/python3.11/site-packages/napari/_qt/_qapp_model/__init__.py", line 3, in <module>
    from ._menus import build_qmodel_menu
  File "/home/cnk/miniconda3/envs/test/lib/python3.11/site-packages/napari/_qt/_qapp_model/_menus.py", line 1, in <module>
    from app_model.backends.qt import QModelMenu
  File "/home/cnk/miniconda3/envs/test/lib/python3.11/site-packages/app_model/backends/qt/__init__.py", line 2, in <module>
    from ._qaction import QCommandAction, QCommandRuleAction, QMenuItemAction
  File "/home/cnk/miniconda3/envs/test/lib/python3.11/site-packages/app_model/backends/qt/_qaction.py", line 12, in <module>
    from ._qkeymap import QKeyBindingSequence
  File "/home/cnk/miniconda3/envs/test/lib/python3.11/site-packages/app_model/backends/qt/_qkeymap.py", line 180, in <module>
    KeyCode.NumpadMultiply: Qt.KeyboardModifier.KeypadModifier | Qt.Key.Key_Asterisk,
    ^^^^^^^^^^^^^^^^^^^^^^
SystemError: <method-wrapper '__getattribute__' of EnumType object at 0x55802006c760> returned a result with an exception set
```

**Comment by tlambert03** [comment]
Looks like you ended up with python 3.11 (look at the environment path names)

**Comment by Chris-N-K** [comment]
Oh well lol.
Suppose could be the reason. Will test. Not sure why.
Interesting the two errors are close but not exactly the same.

**Comment by Chris-N-K** [comment]
Ok with the correct python version <3.11 at least the `pip` path works.
Why installing it via `conda` wont work still puzzles me.
Doen't matter if I create the environment with python 3.10 first and install then or try to directly build the environment specific for `napari` with `PySide2`.

**Comment by tlambert03** [comment]
might need to paste the output of your `conda list` (and either @Czaki  or @jaimergp might know)

**Comment by psobolewskiPhD** [comment]
What error are you getting with conda-forge pyside2? I've run into issues with conda-forge pyside2 on macOS arm64.
See:
https://github.com/napari/napari/issues/5231
Minimal reproducer:
```
>>> from PySide2.QtWidgets import QOpenGLWidget
>>> hasattr(QOpenGLWidget, "defaultFramebufferObject")
```
Should be True, but on arm64 returns False.

**Comment by Chris-N-K** [comment]
So I did some more investigation as I'm still puzzeled that the installation using: 
`conda install -c conda-forge "napari=*=*pyside2"` 
fails.

If I install `PySide2` manually and then use the same call afterwards the solver does no longer commit suicide and the installation works. This way `napari` runs fine with `PySide2`. Going without a manual installation of `PySide2` doesn't work at all.

**Comment by psobolewskiPhD** [comment]
When you say fails, can you elaborate? post an error?
I wonder if it's also related to openssl migration, as
https://github.com/napari/napari/issues/5335
and #4891 
You could also try to install mamba (or libmamba-solver )
Running a linux-64 dry-run the solver succeeds for "napari=*=*pyside2"

**Comment by Chris-N-K** [comment]
@psobolewskiPhD the solver just runs till it kills itself without any real error message. Guess he's not able to solve the dependencies within a set time out.

`mamba` might be a solution. 

It's still very confusing that installing `PySide2` manually and napari afterwards with the call above works but the combined installation using the call above doesn't.

**Comment by psobolewskiPhD** [comment]
It's due to the solver. By installing pyside2 you're narrowing the solution space.
Mamba is not only faster but uses a better solver. You can install it in your base env to use it.
Again I'm pretty sure it's related to the openssl migration.

**Comment by Chris-N-K** [comment]
Yes works fine with mamba. I'm still annoyed over the `conda` solver >.< 
Would some hints in the doc be helpful for cases like these?
If so I could make a small pull request with the hints.
Will close this issue.

**Comment by psobolewskiPhD** [comment]
Mamba is now 1.0.0 so we could just outright recommend using it in the conda section.
@jaimergp and @goanpeca can chime in if there's any drawback to doing that, but my experience with mamba is basically 🔥

**Comment by jaimergp** [comment]
Mentioning both would definitely help. The mamba-org is pushing hard for micromamba as well, and it looks like it will be the focus moving forward. Anaconda is also promoting the experimental solver to non-experimental soon (but still not the default).. Anyway, yes, we can definitely mention it. If you open a PR, please feel fre to tag me so I can do a quick review on that info is articulated :D
