### ISSUE TITLE
Cannot open napari (bundled app version) on windows 11

### ISSUE THREAD

**Issue by ustcfdm** [napari/napari#5347]
## 🐛 Bug

Cannot open napari (bundled app version) on windows 11.

## To Reproduce

1. Download and install [napari bundled app version 0.4.17](https://github.com/napari/napari/releases/download/v0.4.17/napari-0.4.17-Windows-x86_64.exe) 
2. Doulbe click icon napari (0.4.17) to open.
3. A black powershell window appeared just one second then disappeared.

## Environment

CPU:	12th Gen Intel(R) Core(TM) i9-12900KF   3.19 GHz
RAM	32.0 GB (31.9 GB 可用)
System:    64-bit X64

Windows 11 professional
version	22H2
OS version	22621.819

**Comment by ustcfdm** [comment]
By the way, I installed it on my Surface Pro 4 (windows 10). It can be opened without problem.

**Comment by Czaki** [comment]
Could you try to run it from cmd to see what error will show?

**Comment by ustcfdm** [comment]
> Could you try to run it from cmd to see what error will show?

Should I run `napari.exe` in folder `napari-0.4.17\envs\napari-0.4.17\Scripts` from cmd? Here is what it shows:
```
Fatal Python error: init_sys_streams: can't initialize sys standard streams
Python runtime state: core initialized
Traceback (most recent call last):
  File "C:\Users\username\scoop\apps\python\current\lib\io.py", line 54, in <module>
ImportError: cannot import name 'text_encoding' from 'io' (unknown location)
```

It seems to be python version conflict? I have python 3.10 installed using [scoop](https://scoop.sh/), and system variable `PYTHONHOME` and `PYTHONPATH` .

**Comment by ustcfdm** [comment]
I deleted `PYTHONOME` and `PYTHONPATH`, and it works now. But what if I want to keep them?

**Comment by Czaki** [comment]
> I deleted `PYTHONOME` and `PYTHONPATH`, and it works now. But what if I want to keep them?

At this moment I do not know, but thanks to your check, we have a good starting point for investigating.

I'm linux man so could not simply validate ideas. 

My first idea is to overwrite environment variables in the napari shortcut (set them to empty string)
https://netlicensing.io/blog/2012/06/15/set-environment-variables-in-windows-shortcut/ 

For comparison. On your windows 10 (Surface Pro 4) you have settled these environment variables or not? It is important to know if the problem is specific to windows 11.

**Comment by ustcfdm** [comment]
> For comparison. On your windows 10 (Surface Pro 4) you have settled these environment variables or not? It is important to know if the problem is specific to windows 11.

No, those environment variables are not settled on my windows 10.

**Comment by Czaki** [comment]
@jaimergp @goanpeca It looks like a question for you. It is possible to add a proper step to bundle to separate it from existing environments on the machine?

**Comment by jaimergp** [comment]
I thought `conda activate` (which we run as part of the shortcut) handled that environment sanitization, but apparently it doesn't... We'll have to include some logic in the shortcut creation tool. I am working on updating it as we speak, so I can include a fix for the next release.

I'll come up with a hotfix for you in a bit, we can include an activation script.

**Comment by jaimergp** [comment]
Try this from any CMD:

```
% "C:\...\napari-0.4.17\Scripts\conda.exe" env config vars set -p "C:\...\napari-0.4.17\envs\napari-0.4.17" PYTHONPATH="" PYTHONHOME=""
```

`"C:\...\napari-0.4.17` should be absolute path to the root of napari installation.

**Comment by ustcfdm** [comment]
> Try this from any CMD:
> 
> ```
> % "C:\...\napari-0.4.17\Scripts\conda.exe" env config vars set -p "C:\...\napari-0.4.17\envs\napari-0.4.17" PYTHONPATH="" PYTHONHOME=""
> ```
> 
> `"C:\...\napari-0.4.17` should be absolute path to the root of napari installation.

This does not work on my computer. If I run it from Powershell, it shows the following message:
```Powershell
ForEach-Object : 无法绑定参数“Process”。无法将“System.String”类型的“C:\Users\fengm\AppData\Local\napari-0.4.17\env
s\napari-0.4.17”值转换为“System.Management.Automation.ScriptBlock”类型。
所在位置 行:1 字符: 89
+ ... vars set -p "C:\Users\fengm\AppData\Local\napari-0.4.17\envs\napari-0 ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [ForEach-Object]，ParameterBindingException
    + FullyQualifiedErrorId : CannotConvertArgumentNoMessage,Microsoft.PowerShell.Commands.ForEachObjectCommand
```

If I run it from Command Prompt, it shows the following message:
```CMD
Fatal Python error: init_sys_streams: can't initialize sys standard streams
Python runtime state: core initialized
Traceback (most recent call last):
  File "C:\Users\fengm\scoop\apps\python\current\lib\io.py", line 54, in <module>
ImportError: cannot import name 'text_encoding' from 'io' (unknown location)
```

**Comment by jaimergp** [comment]
Oh, you need to unset the offending PYTHON* vars before running the command, then. From CMD:

```
% set "PYTHONHOME="
% set "PYTHONPATH="
% "C:\...\napari-0.4.17\Scripts\conda.exe" env config vars set -p "C:\...\napari-0.4.17\envs\napari-0.4.17" PYTHONPATH="" PYTHONHOME=""
```

**Comment by jaimergp** [comment]
@ustcfdm - preview installers are available at https://github.com/napari/packaging/actions/runs/3522319169

If you want to give this a try! It's 'experimental' so some stuff might not work as you'd expect. But hopefully it should have fixed your issue? Let me know, your feedback will be appreciated!

**Comment by ustcfdm** [comment]
> @ustcfdm - preview installers are available at https://github.com/napari/packaging/actions/runs/3522319169
> 
> If you want to give this a try! It's 'experimental' so some stuff might not work as you'd expect. But hopefully it should have fixed your issue? Let me know, your feedback will be appreciated!

@jaimergp It seems the issue is not fixed in the preview version. Still the same error.

**Comment by jaimergp** [comment]
Hm, the shortcuts are supposedly unsetting the variables for you now... would you be available for a 1:1 debugging session, @ustcfdm ? You can book a slot in my calendar here: https://calendly.com/jaimergp-quansight/30-min-call?month=2022-12.

I am going to transfer this issue over to `napari/packaging` where I'll be doing the work.
