### ISSUE TITLE
Shape layer using shape_type = 'path' fails to be converted to mask/label

### ISSUE THREAD

**Issue by MalteMederacke** [napari/napari#5349]
## 🐛 Bug

Shape layer fails to be converted to mask/image if shapes are drawn with shape_type = 'path'. I use Napari to visualize some tree graphs, because I compute them from an image (skeletonizaiton). Now, I want to do a reverse thing, and compute images from graphs. I expected to simply use Napari to plot the lines and transform the shapes to labels, but that is not what happens. I get, given I choose a big enough shape value (2D for 3D graphs?)  an image that looks different from my graph. 

Here is what I do:

```
import napari
import pandas as pd
import numpy as np 
import networkx as nx

viewer = napari.Viewer()
tree = nx.random_tree(5)
positions = {0:[0,0,0],1:[10,5,10],2:[-10,5,10],3:[15,30,-15],4:[-25,10,15],5:[20,15,40]}
nx.set_node_attributes(tree,positions,name  = 'pos')

edge_points = []
for i in list(tree.edges):
        j,k = i
        if tree.nodes()[j] and tree.nodes()[k]:
            a = nx.get_node_attributes(tree, 'pos')[j]
            b = nx.get_node_attributes(tree, 'pos')[k]
            edge_points.append([a,b])

shape_layer = viewer.add_shapes(edge_points, shape_type='path', edge_color='white')
```
Giving me this output in the viewer:

<img width="473" alt="image" src="https://user-images.githubusercontent.com/65277828/202816321-d23eac3f-1030-4210-bcd3-136c6539ce7f.png">

So far, so good.

Now, I want to have this as an image array. So I tried to use:

```
shape_layer.to_masks() 
#or
shape_layer.to_label()
```
Throwing this error:

<img width="664" alt="image" src="https://user-images.githubusercontent.com/65277828/202816941-cb7af4f1-5b70-41ab-82e2-4e1e8817feda.png">

I can get an output with eg.:

```
shape_layer.to_masks([50,50])
viewer.add_image(shape_layer.to_masks([50,50])*1) #to transform to image
```
giving me an 3D image with shape (4,50,50) looking like:

<img width="1410" alt="image" src="https://user-images.githubusercontent.com/65277828/202817330-adb48f91-a02d-49e7-bde1-9be7705c91e1.png">

## Expected behavior

I would expect a similar output as image as seen in the shape layer. If I give a 3D array [z,x,y], I would expect to get an image with shape (z,x,y). But maybe I understand the function wrong?

## Environment
napari: 0.4.16
Platform: Linux-5.4.0-131-generic-x86_64-with-glibc2.31
System: Ubuntu 20.04.5 LTS
Python: 3.9.13 (main, Aug 25 2022, 23:26:10) [GCC 11.2.0]
Qt: 5.15.2
PyQt5: 5.15.7
NumPy: 1.23.3
SciPy: 1.9.1
Dask: 2022.9.0
VisPy: 0.10.0

OpenGL:
- GL version: 3.1 Mesa 21.2.6
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1425x781, scale 1.0

Plugins:
- console: 0.0.4
- ilastik-napari: 0.2.dev3+g95187d8
- napari-accelerated-pixel-and-object-classification: 0.9.0
- napari-hdf5-labels-io: 0.2.dev1
- napari-process-points-and-surfaces: 0.3.1
- napari-skeleton-curator: 0.1.dev21+gf2de859
- napari-svg: 0.1.6
- napari-time-slicer: 0.4.9
- napari-tools-menu: 0.1.17
- scikit-image: 0.4.16

Any help is appreciated!

**Comment by psobolewskiPhD** [comment]
I can reproduce this on 0.4.17 live, macOS arm64 just using the GUI contextual menu `Convert to Labels`
Can also be reproduced using the napari example `3D_paths.py`:
https://github.com/napari/napari/blob/main/examples/3D_paths.py

Full traceback:
```
Traceback (most recent call last):
  File "/Users/piotrsobolewski/Dev/app-model/src/app_model/backends/qt/_qaction.py", line 52, in _on_triggered
    self._app.commands.execute_command(self._command_id).result()
  File "/Users/piotrsobolewski/Dev/app-model/src/app_model/registries/_commands_reg.py", line 202, in execute_command
    raise e
  File "/Users/piotrsobolewski/Dev/app-model/src/app_model/registries/_commands_reg.py", line 197, in execute_command
    future.set_result(cmd(*args, **kwargs))
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/napari-dev/lib/python3.10/site-packages/in_n_out/_store.py", line 890, in _exec
    result = func(*args, **kwargs)
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/napari-dev/lib/python3.10/site-packages/in_n_out/_store.py", line 774, in _exec
    result = func(**_kwargs)
  File "/Users/piotrsobolewski/Dev/napari/napari/layers/_layer_actions.py", line 70, in _convert_to_labels
    return _convert(ll, 'labels')
  File "/Users/piotrsobolewski/Dev/napari/napari/layers/_layer_actions.py", line 57, in _convert
    data = lay.to_labels()
  File "/Users/piotrsobolewski/Dev/napari/napari/layers/shapes/shapes.py", line 2952, in to_labels
    labels = self._data_view.to_labels(labels_shape=labels_shape)
  File "/Users/piotrsobolewski/Dev/napari/napari/layers/shapes/_shape_list.py", line 1191, in to_labels
    mask = self.shapes[ind].to_mask(
  File "/Users/piotrsobolewski/Dev/napari/napari/layers/shapes/_shapes_models/shape.py", line 411, in to_mask
    mask_p = path_to_mask(shape_plane, (data - offset) * zoom_factor)
ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

If you suspect this is an IPython 8.5.0 bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True
```

**Comment by kcpevey** [comment]
I spent some time looking into this, but I need some extra eyes and advice on how to move forward. Here is a summary of what I've learned so far:

The offending bit of code from [this line](https://github.com/napari/napari/blob/main/napari/layers/shapes/_shapes_models/shape.py#L411) 
 in `Shape.to_mask()` is 
```
data - offset
```
which is causing the error `ValueError: operands could not be broadcast together with shapes (2,3) (2,)` because `data` is 3D, but the offset is 2D.

The default value for offset (both [here](https://github.com/napari/napari/blob/main/napari/layers/shapes/_shapes_models/shape.py#L355) and [here](https://github.com/napari/napari/blob/main/napari/layers/shapes/_shape_list.py#L1161)) is `offset=[0,0]`. It seems we are only hitting this when we get the default. 

Interesting - if you attempt to convert to labels outside of the viewer, you don't hit the error. Example:
```
    path = np.array([np.array([[0, 0, 0], [0, 10, 10], [0, 5, 15], [20, 5, 15],
        [56, 70, 21], [127, 127, 127]]),
        np.array([[0, 0, 0], [0, 10, 10], [0, 5, 15], [0, 5, 15],
        [0, 70, 21], [0, 127, 127]])])
    layer = Shapes(path, shape_type='path')
    labels = layer.to_labels()
```
I don't know why that is the case. 

In an attempt to fix, I changed the offset default value to `None` and then added this check
```
        if offset is None:
            offset = np.zeros(len(mask_shape))
```
to [this line](https://github.com/napari/napari/blob/main/napari/layers/shapes/_shapes_models/shape.py#L384) in `_shapes_models/shape.py`. 

That DOES fix the original error with broadcasting, but it seems that `shapes_utils.path_to_mask` isn't actually designed for 3D points ([see here](https://github.com/napari/napari/blob/main/napari/layers/shapes/_shapes_utils.py#L868) and [here](https://github.com/napari/napari/blob/main/napari/layers/shapes/_shapes_utils.py#L888-L891))

The question is **Should path_to_mask (and to_labels) be able to handle 3D?**
