### ISSUE TITLE
AttributeError: 'Window' object has no attribute '_qt_window' on exit

### ISSUE THREAD

**Issue by tlambert03** [napari/napari#5400]
## 🐛 Bug
```python
import napari

viewer = napari.Viewer()
viewer.show(block=True)
``` 

on exit:
```pytb
WARNING: Traceback (most recent call last):
  File "/Users/talley/mambaforge/envs/napari-release/lib/python3.10/site-packages/napari/_qt/qt_viewer.py", line 380, in _leave_canvas
    self.viewer.status = ""
  File "/Users/talley/mambaforge/envs/napari-release/lib/python3.10/site-packages/napari/utils/events/evented_model.py", line 241, in __setattr__
    getattr(self.events, name)(value=after)  # emit event
  File "/Users/talley/mambaforge/envs/napari-release/lib/python3.10/site-packages/napari/utils/events/event.py", line 757, in __call__
    self._invoke_callback(cb, event if pass_event else None)
  File "/Users/talley/mambaforge/envs/napari-release/lib/python3.10/site-packages/napari/utils/events/event.py", line 794, in _invoke_callback
    _handle_exception(
  File "/Users/talley/mambaforge/envs/napari-release/lib/python3.10/site-packages/napari/utils/events/event.py", line 781, in _invoke_callback
    cb(event)
  File "/Users/talley/mambaforge/envs/napari-release/lib/python3.10/site-packages/napari/_qt/qt_main_window.py", line 1178, in _status_changed
    self._status_bar.setStatusText(event.value)
  File "/Users/talley/mambaforge/envs/napari-release/lib/python3.10/site-packages/napari/_qt/qt_main_window.py", line 608, in _status_bar
    return self._qt_window.statusBar()
AttributeError: 'Window' object has no attribute '_qt_window'
```

looks like this was discussed a bit in https://github.com/napari/napari/issues/5382 ... but there it was suggested to be a usage pattern problem.  The above code appears to be pretty normal usage, but still has an Attribute error

**Comment by Carreau** [comment]
I cannot reproduce on MacOS, Python 3.11.0. 

Both `python foo.py` with above content, or entering line one by one in Python REPL or IPython repl, so I'm a tiny bit confused.

**Comment by Czaki** [comment]
What method of exit is used?

**Comment by psobolewskiPhD** [comment]
I'm on python 3.10 and if i run that code block in ipython, and then hit Command-W (close window) or click the red dot to close, it goes back to ipython fine.
But if I hit command-Q to quit napari, then I get a slightly different error than the OP:
```
/Users/piotrsobolewski/Dev/napari/napari/viewer.py:139: RuntimeWarning: The window geometry settings could not be loaded due to the following error: 'Window' object has no attribute '_qt_window'
  self.window.show(block=block)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[1], line 4
      1 import napari
      3 viewer = napari.Viewer()
----> 4 viewer.show(block=True)

File ~/Dev/napari/napari/viewer.py:139, in Viewer.show(self, block)
    137 def show(self, *, block=False):
    138     """Resize, show, and raise the viewer window."""
--> 139     self.window.show(block=block)

File ~/Dev/napari/napari/_qt/qt_main_window.py:1242, in Window.show(self, block)
   1231         warnings.warn(
   1232             trans._(
   1233                 "The window geometry settings could not be loaded due to the following error: {err}",
   (...)
   1238             stacklevel=2,
   1239         )
   1241 # Resize axis labels now that window is shown
-> 1242 self._qt_viewer.dims._resize_axis_labels()
   1244 # We want to bring the viewer to the front when
   1245 # A) it is our own event loop OR we are running in jupyter
   1246 # B) it is not the first time a QMainWindow is being created
   (...)
   1250 # _qt_window has been created.
   1251 # See #721, #732, #735, #795, #1594
   1252 app_name = QApplication.instance().applicationName()

File ~/Dev/napari/napari/_qt/qt_main_window.py:705, in Window._qt_viewer(self)
    702 @property
    703 def _qt_viewer(self):
    704     # this is starting to be "vestigial"... this property could be removed
--> 705     return self._qt_window._qt_viewer

AttributeError: 'Window' object has no attribute '_qt_window'
```

**Comment by Carreau** [comment]
> But if I hit command-Q to quit napari, then I get a slightly different error than the OP:

Ha ! Yes, same here.

**Comment by Carreau** [comment]
The main difference seem to be that closing via Cmd-Q (and going through the confirmation dialog if you don't have. "do not ask" set), is that it calls 


```
def quit_app():
    """Close all windows and quit the QApplication if napari started it."""
    for v in list(Viewer._instances):
        v.close() # and this is triggering the issue.
```

The `close()` method seem to be reentrant and store some state in (`_quit_app`) when it is re-called, so maybe we should refactor that a bit to make the flow simpler/more understandable.
