### ISSUE TITLE
CLI broken on master

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#543]
## 🐛 Bug

On master right now launching `napari` gives 
```
napari
Traceback (most recent call last):
  File "/anaconda3/bin/napari", line 11, in <module>
    load_entry_point('napari', 'console_scripts', 'napari')()
  File "/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2434, in load
    return self.resolve()
  File "/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'napari.main'
```

**Comment by kne42** [comment]
This is due to the contents of `setup.py` changing in #529. `setup.py` is what determines what is used for the entry point of the `napari` script and does not update automatically even in development mode.

This is only an issue for people who have are using an editable installation (e.g. with `pip install -e .`) which has not been fully updated since #529 was introduced. To fix this, simply re-run `pip install -e .`.
