### ISSUE TITLE
napari .zip briefcase bundled app does not work (windows, macOS)

### ISSUE THREAD

**Issue by orena1** [napari/napari#5506]
## 🐛 Bug & To Reproduce
Hi,
I've downloaded and installed the windows bundled app and I get the following error:
```cmd
C:\Users\oren>C:\Users\oren\AppData\Local\Programs\napari\python\python.exe -m napari
Traceback (most recent call last):
  File "runpy.py", line 194, in _run_module_as_main
  File "runpy.py", line 87, in _run_code
  File "C:\Users\oren\AppData\Local\Programs\napari\\app\napari\__main__.py", line 565, in <module>
    sys.exit(main())
  File "C:\Users\oren\AppData\Local\Programs\napari\\app\napari\__main__.py", line 561, in main
    _run()
  File "C:\Users\oren\AppData\Local\Programs\napari\\app\napari\__main__.py", line 327, in _run
    viewer = Viewer()
  File "C:\Users\oren\AppData\Local\Programs\napari\\app\napari\viewer.py", line 65, in __init__
    _initialize_plugins()
  File "C:\Users\oren\AppData\Local\Programs\napari\\app\napari\plugins\__init__.py", line 46, in _initialize_plugins
    mf = PluginManifest.from_distribution('napari')
  File "C:\Users\oren\AppData\Local\Programs\napari\\app_packages\npe2\manifest\schema.py", line 228, in from_distribution
    raise ValueError(
ValueError: Distribution {name!r} exists but does not provide a napari manifest

C:\Users\oren>
```

## Environment

Windows 10 & also in windows server 2012

I'm installing with pip now, and it is working, but the `bundled app` not working

**Comment by psobolewskiPhD** [comment]
Thank you for the report.
Can you just clarify one thing, from the title I get that you used the `...Windows...zip` bundle from the Assets pane of https://github.com/napari/napari/releases/tag/v0.4.17:
<img width="1046" alt="image" src="https://user-images.githubusercontent.com/76622105/214399565-15ad062c-e677-4ec5-9c08-fec5cb3541e7.png">
Is that correct?

And if so, can you try the `...Windows...exe` bundle and see if that works?
They use different backends.
🙏

**Comment by orena1** [comment]
Thanks @psobolewskiPhD! with the .exe it does start, but when I click 
![image](https://user-images.githubusercontent.com/8983713/214476310-fe4ae520-e8de-489d-b312-f2a0d007e846.png)
I get this:
```python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
File ~\AppData\Local\napari-0.4.17\envs\napari-0.4.17\lib\site-packages\napari\_qt\qt_viewer.py:735, in QtViewer._open_files_dialog(self=<napari._qt.qt_viewer.QtViewer(0x262c1da1f40)>, choose_plugin=False)
    732 hist = get_open_history()
    733 dlg.setHistory(hist)
--> 735 filenames, _ = dlg.getOpenFileNames(
        dlg = <PySide2.QtWidgets.QFileDialog(0x262d91282d0) at 0x00000262D7C2C440>
        self = <napari._qt.qt_viewer.QtViewer(0x262c1da1f40) at 0x00000262C43A05C0>
        trans = <napari.utils.translations.TranslationBundle object at 0x00000262BCD3FD30>
        hist = ['C:\\Users\\oren']
        hist[0] = 'C:\\Users\\oren'
        QFileDialog = <class 'PySide2.QtWidgets.QFileDialog'>
        QFileDialog.DontUseNativeDialog = PySide2.QtWidgets.QFileDialog.Option.DontUseNativeDialog
    736     parent=self,
    737     caption=trans._('Select file(s)...'),
    738     directory=hist[0],
    739     options=(
    740         QFileDialog.DontUseNativeDialog
    741         if in_ipython()
    742         else QFileDialog.Options()
    743     ),
    744 )
    746 if (filenames != []) and (filenames is not None):
    747     for filename in filenames:

AttributeError: PySide2.QtWidgets.QFileDialog.getOpenFileNames(): unsupported keyword 'directory'
```

**Comment by psobolewskiPhD** [comment]
Eep, another bug! Sorry about this.
I can reproduce this without the bundle on my mac with pyside2. 
I will make a new issue for this.
```
AttributeError                            Traceback (most recent call last)
File ~/Dev/miniforge3/envs/nap-test/lib/python3.10/site-packages/napari/_qt/qt_viewer.py:735, in QtViewer._open_files_dialog(self=<napari._qt.qt_viewer.QtViewer(0x6000008e1810)>, choose_plugin=False)
    732 hist = get_open_history()
    733 dlg.setHistory(hist)
--> 735 filenames, _ = dlg.getOpenFileNames(
        dlg = <PySide2.QtWidgets.QFileDialog(0x600000851180) at 0x16bb672c0>
        self = <napari._qt.qt_viewer.QtViewer(0x6000008e1810) at 0x16fcf2140>
        trans = <napari.utils.translations.TranslationBundle object at 0x14f201930>
        hist = ['/Users/piotrsobolewski']
        hist[0] = '/Users/piotrsobolewski'
        QFileDialog = <class 'PySide2.QtWidgets.QFileDialog'>
        QFileDialog.DontUseNativeDialog = PySide2.QtWidgets.QFileDialog.Option.DontUseNativeDialog
    736     parent=self,
    737     caption=trans._('Select file(s)...'),
    738     directory=hist[0],
    739     options=(
    740         QFileDialog.DontUseNativeDialog
    741         if in_ipython()
    742         else QFileDialog.Options()
    743     ),
    744 )
    746 if (filenames != []) and (filenames is not None):
    747     for filename in filenames:

AttributeError: PySide2.QtWidgets.QFileDialog.getOpenFileNames(): unsupported keyword 'directory'
```
Looks like the bug being fixed here https://github.com/napari/napari/pull/5492/files for pyside6 also affects pyside2.

**Comment by Czaki** [comment]
> Looks like the bug being fixed here [#5492 (files)](https://github.com/napari/napari/pull/5492/files) for pyside6 also affects pyside2.

I was sure that I had tested it, and because of this, I select only PySide6. I need to revalidate it. 

@orena1 At this moment, I can only suggest opening files using the drag-and-drop mechanism. We will work to fix this asap.

**Comment by orena1** [comment]
Thanks @Czaki I installed it with pip and it is working, just wanted to let you know about the probelm.

**Comment by sheldonsebastian** [comment]
Is the fix for AttributeError: PySide2.QtWidgets.QFileDialog.getOpenFileNames(): unsupported keyword 'directory' available in the bundled app?

**Comment by psobolewskiPhD** [comment]
@sheldonsebastian 
The issue has been fixed, but the fix isn't released yet, so it won't be in the official releases bundles until we make a new napari release.
However, we do have experimental Nightly builds of the bundle app (which will have the fix):
https://github.com/napari/napari/releases/tag/latest
You want to look at the .sh, the .pkg and the .exe which all use the conda backend.

**Comment by psobolewskiPhD** [comment]
The mac one also doesn't run. Here's the traceback I get:
```
Traceback (most recent call last):
  File "napari.app/Contents/Resources/app/napari/__main__.py", line 565, in <module>
    sys.exit(main())
  File "napari.app/Contents/Resources/app/napari/__main__.py", line 561, in main
    _run()
  File "napari.app/Contents/Resources/app/napari/__main__.py", line 218, in _run
    from napari import Viewer, run
  File "napari.app/Contents/Resources/app_packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "<frozen importlib._bootstrap>", line 1055, in _handle_fromlist
  File "napari.app/Contents/Resources/app/napari/_lazy.py", line 48, in __getattr__
    submod = import_module(
  File "napari.app/Contents/Resources/Support/Python/Resources/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "napari.app/Contents/Resources/app/napari/viewer.py", line 8, in <module>
    from .components.viewer_model import ViewerModel
  File "napari.app/Contents/Resources/app_packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "napari.app/Contents/Resources/app/napari/components/__init__.py", line 19, in <module>
    from .layerlist import LayerList
  File "napari.app/Contents/Resources/app_packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "napari.app/Contents/Resources/app/napari/components/layerlist.py", line 9, in <module>
    from ..layers import Layer
  File "napari.app/Contents/Resources/app_packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "napari.app/Contents/Resources/app/napari/layers/__init__.py", line 11, in <module>
    from .base import Layer
  File "napari.app/Contents/Resources/app_packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "napari.app/Contents/Resources/app/napari/layers/base/__init__.py", line 1, in <module>
    from .base import Layer, no_op
  File "napari.app/Contents/Resources/app_packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "napari.app/Contents/Resources/app/napari/layers/base/base.py", line 14, in <module>
    from npe2 import plugin_manager as pm
  File "napari.app/Contents/Resources/app_packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "napari.app/Contents/Resources/app_packages/npe2/__init__.py", line 8, in <module>
    from ._dynamic_plugin import DynamicPlugin
  File "napari.app/Contents/Resources/app_packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "napari.app/Contents/Resources/app_packages/npe2/_dynamic_plugin.py", line 19, in <module>
    from ._plugin_manager import PluginManager
  File "napari.app/Contents/Resources/app_packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "napari.app/Contents/Resources/app_packages/npe2/_plugin_manager.py", line 30, in <module>
    from ._command_registry import CommandRegistry
  File "napari.app/Contents/Resources/app_packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "napari.app/Contents/Resources/app_packages/npe2/_command_registry.py", line 10, in <module>
    from .manifest import utils
  File "napari.app/Contents/Resources/app_packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "napari.app/Contents/Resources/app_packages/npe2/manifest/__init__.py", line 2, in <module>
    from .schema import ENTRY_POINT, PluginManifest
  File "napari.app/Contents/Resources/app_packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "napari.app/Contents/Resources/app_packages/npe2/manifest/schema.py", line 18, in <module>
    from .contributions import ContributionPoints
  File "napari.app/Contents/Resources/app_packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "napari.app/Contents/Resources/app_packages/npe2/manifest/contributions/__init__.py", line 2, in <module>
    from ._configuration import ConfigurationContribution, ConfigurationProperty
  File "napari.app/Contents/Resources/app_packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "napari.app/Contents/Resources/app_packages/npe2/manifest/contributions/_configuration.py", line 5, in <module>
    from ._json_schema import (
  File "napari.app/Contents/Resources/app_packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "napari.app/Contents/Resources/app_packages/npe2/manifest/contributions/_json_schema.py", line 84, in <module>
    class _JsonSchemaBase(BaseModel):
  File "pydantic/main.py", line 179, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/typing.py", line 395, in pydantic.typing.resolve_annotations
TypeError: __init__() got an unexpected keyword argument 'is_class'
```
