### ISSUE TITLE
[Python>3.11.0] A distribution name is required

### ISSUE THREAD

**Issue by massimovassalli** [napari/napari#5554]
## 🐛 Bug

Aftre fresh installation, napari does not import (or start) and exits with a ValueError "A distribution name is required"
## To Reproduce

1. just by importing or starting

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\massi\AppData\Local\Programs\Python\Python311\Scripts\napari.exe\__main__.py", line 7, in <module>
  File "C:\Users\massi\AppData\Local\Programs\Python\Python311\Lib\site-packages\napari\__main__.py", line 561, in main
    _run()
  File "C:\Users\massi\AppData\Local\Programs\Python\Python311\Lib\site-packages\napari\__main__.py", line 218, in _run
    from napari import Viewer, run
  File "<frozen importlib._bootstrap>", line 1231, in _handle_fromlist
  File "C:\Users\massi\AppData\Local\Programs\Python\Python311\Lib\site-packages\napari\_lazy.py", line 48, in __getattr__
    submod = import_module(
             ^^^^^^^^^^^^^^
  File "C:\Users\massi\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\massi\AppData\Local\Programs\Python\Python311\Lib\site-packages\napari\viewer.py", line 8, in <module>
    from .components.viewer_model import ViewerModel
  File "C:\Users\massi\AppData\Local\Programs\Python\Python311\Lib\site-packages\napari\components\__init__.py", line 19, in <module>
    from .layerlist import LayerList
  File "C:\Users\massi\AppData\Local\Programs\Python\Python311\Lib\site-packages\napari\components\layerlist.py", line 9, in <module>
    from ..layers import Layer
  File "C:\Users\massi\AppData\Local\Programs\Python\Python311\Lib\site-packages\napari\layers\__init__.py", line 11, in <module>
    from .base import Layer
  File "C:\Users\massi\AppData\Local\Programs\Python\Python311\Lib\site-packages\napari\layers\base\__init__.py", line 1, in <module>
    from .base import Layer, no_op
  File "C:\Users\massi\AppData\Local\Programs\Python\Python311\Lib\site-packages\napari\layers\base\base.py", line 28, in <module>
    from ...utils.key_bindings import KeymapProvider
  File "C:\Users\massi\AppData\Local\Programs\Python\Python311\Lib\site-packages\napari\utils\key_bindings.py", line 46, in <module>
    from ..settings import get_settings
  File "C:\Users\massi\AppData\Local\Programs\Python\Python311\Lib\site-packages\napari\settings\__init__.py", line 6, in <module>
    from ._napari_settings import CURRENT_SCHEMA_VERSION, NapariSettings
  File "C:\Users\massi\AppData\Local\Programs\Python\Python311\Lib\site-packages\napari\settings\_napari_settings.py", line 14, in <module>
    from ._plugins import PluginsSettings
  File "C:\Users\massi\AppData\Local\Programs\Python\Python311\Lib\site-packages\napari\settings\_plugins.py", line 27, in <module>
    class PluginsSettings(EventedSettings):
  File "C:\Users\massi\AppData\Local\Programs\Python\Python311\Lib\site-packages\napari\settings\_plugins.py", line 75, in PluginsSettings
    class NapariConfig:
  File "C:\Users\massi\AppData\Local\Programs\Python\Python311\Lib\site-packages\napari\settings\_plugins.py", line 83, in NapariConfig
    if running_as_bundled_app() or running_as_constructor_app():
       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\massi\AppData\Local\Programs\Python\Python311\Lib\site-packages\napari\utils\misc.py", line 67, in running_as_bundled_app
    metadata = importlib.metadata.metadata(app_module)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\massi\AppData\Local\Programs\Python\Python311\Lib\importlib\metadata\__init__.py", line 998, in metadata
    return Distribution.from_name(distribution_name).metadata
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\massi\AppData\Local\Programs\Python\Python311\Lib\importlib\metadata\__init__.py", line 561, in from_name
    raise ValueError("A distribution name is required.")
ValueError: A distribution name is required.

## Expected behavior

Should start the interface or import

## Environment

- Windows 10
- napari 0.4.17
- Python 3.11

**Comment by Czaki** [comment]
napari is currently incompatible with python 3.11. Please use an older python release.

**Comment by psobolewskiPhD** [comment]
Thanks for the issue; can you confirm you're on python 3.11.1? (the last .1 is important!)
`python --version`
If so, we actually have a fix in the works for this issue: https://github.com/napari/napari/pull/5482

But we don't yet support python 3.11.
If you want to test, you can use 3.11.0 via conda-forge, see: https://github.com/napari/napari/issues/5514

**Comment by massimovassalli** [comment]
> Thanks for the issue; can you confirm you're on python 3.11.1? (the last .1 is important!) `python --version` If so, we actually have a fix in the works for this issue: #5482
> 
> But we don't yet support python 3.11. If you want to test, you can use 3.11.0 via conda-forge, see: #5514

Hi,
Yes, I'm on 3.11.1 
I don't know how to apply the fix so I cannot help in reporting 
Thanks

**Comment by psobolewskiPhD** [comment]
Well, the PR isn't merged and then it would need to be released.
In the meantime you can use 3.10 which we do support or try 3.11.0 which should work, but we don't officially support.
If you **really** need to use 3.11.1 you could clone our repository and checkout the branch of the linked PR.

**Comment by psobolewskiPhD** [comment]
Lost track of this one. We still don't officially support python 3.11, but I checked and the lastest conda nightly (use ` -c "napari/label/nightly"`) runs fine on python 3.11.2 as far as I can tell.
