### ISSUE TITLE
CircleCI build of documentation preview contains multiple Runtime errors 

### ISSUE THREAD

**Issue by Czaki** [napari/napari#5572]
## 🐛 Bug

CircleCI build of documentation preview contains multiple Runtime errors. It may lead to multiple problems in the future.  

## To Reproduce

https://app.circleci.com/pipelines/github/napari/docs/20/workflows/4157c9f8-9808-4f01-a152-5f6bdf3b68df/jobs/11

```
/home/circleci/project/napari/examples/add_vectors.py failed leaving traceback:
Traceback (most recent call last):
  File "/home/circleci/project/napari/examples/add_vectors.py", line 20, in <module>
    viewer = napari.Viewer()
  File "/home/circleci/project/napari/napari/viewer.py", line 67, in __init__
    self._window = Window(self, show=show)
  File "/home/circleci/project/napari/napari/_qt/qt_main_window.py", line 575, in __init__
    self._add_menus()
  File "/home/circleci/project/napari/napari/_qt/qt_main_window.py", line 731, in _add_menus
    self.view_menu = build_qmodel_menu(
  File "/home/circleci/project/napari/napari/_qt/_qapp_model/_menus.py", line 32, in build_qmodel_menu
    return QModelMenu(
  File "/home/circleci/project/venv/lib/python3.10/site-packages/app_model/backends/qt/_qmenu.py", line 145, in __init__
    _MenuMixin.__init__(self, menu_id, app)
  File "/home/circleci/project/venv/lib/python3.10/site-packages/app_model/backends/qt/_qmenu.py", line 56, in __init__
    self.rebuild()
  File "/home/circleci/project/venv/lib/python3.10/site-packages/app_model/backends/qt/_qmenu.py", line 81, in rebuild
    submenu = QModelSubmenu(item, self._app, parent=self)
  File "/home/circleci/project/venv/lib/python3.10/site-packages/app_model/backends/qt/_qmenu.py", line 189, in __init__
    super().__init__(
  File "/home/circleci/project/venv/lib/python3.10/site-packages/app_model/backends/qt/_qmenu.py", line 145, in __init__
    _MenuMixin.__init__(self, menu_id, app)
  File "/home/circleci/project/venv/lib/python3.10/site-packages/app_model/backends/qt/_qmenu.py", line 56, in __init__
    self.rebuild()
  File "/home/circleci/project/venv/lib/python3.10/site-packages/app_model/backends/qt/_qmenu.py", line 84, in rebuild
    action = QMenuItemAction(
  File "/home/circleci/project/venv/lib/python3.10/site-packages/app_model/backends/qt/_qaction.py", line 166, in __init__
    self.update_from_context({})
  File "/home/circleci/project/venv/lib/python3.10/site-packages/app_model/backends/qt/_qaction.py", line 170, in update_from_context
    super().update_from_context(ctx)
  File "/home/circleci/project/venv/lib/python3.10/site-packages/app_model/backends/qt/_qaction.py", line 94, in update_from_context
    self.setEnabled(expr.eval(ctx) if (expr := self._cmd_rule.enablement) else True)
RuntimeError: Internal C++ object (QMenuItemAction) already deleted.
```

## Expected behavior

Build log should not contain any such bug. 

## Environment

 - Please copy and paste the information at napari info option in help menubar here:

 - Any other relevant information:

**Comment by melissawm** [comment]
BTW, all of these are related to examples - they probably need to be updated to account for changes in recent versions of napari.

**Comment by psobolewskiPhD** [comment]
This is being discussed/addressed here:
https://github.com/napari/docs/pull/178
Those errors appear related to pyside2, but there also appears to be a memory issue, probably due to clean up of viewers?

**Comment by Czaki** [comment]
I close this issue as it is properly traced in the docs repo
