### ISSUE TITLE
Development Installation Error

### ISSUE THREAD

**Issue by zoccoler** [napari/napari#5581]
## 📚 Documentation

Hi everyone,

I followed the development installation instructions provided [here](https://napari.org/stable/developers/contributing.html#setting-up-a-development-installation). After that (`pip install -e ".[dev]"`), when I call napari, I get this error:

```
Traceback (most recent call last):
  File "C:\Users\mazo260d\mambaforge\envs\napari-dev\lib\site-packages\qtpy\__init__.py", line 252, in <module>
    from PySide6 import __version__ as PYSIDE_VERSION  # analysis:ignore
ModuleNotFoundError: No module named 'PySide6'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mazo260d\Documents\GitHub\napari\napari\_qt\__init__.py", line 9, in <module>
    from qtpy import API_NAME, QT_VERSION, QtCore
  File "C:\Users\mazo260d\mambaforge\envs\napari-dev\lib\site-packages\qtpy\__init__.py", line 259, in <module>
    raise QtBindingsNotFoundError()
qtpy.QtBindingsNotFoundError: No Qt bindings could be found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\mazo260d\mambaforge\envs\napari-dev\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\mazo260d\mambaforge\envs\napari-dev\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\mazo260d\mambaforge\envs\napari-dev\Scripts\napari.exe\__main__.py", line 7, in <module>
  File "C:\Users\mazo260d\Documents\GitHub\napari\napari\__main__.py", line 560, in main
    _maybe_rerun_with_macos_fixes()
  File "C:\Users\mazo260d\Documents\GitHub\napari\napari\__main__.py", line 442, in _maybe_rerun_with_macos_fixes
    from napari._qt import API_NAME
  File "C:\Users\mazo260d\Documents\GitHub\napari\napari\_qt\__init__.py", line 12, in <module>
    raise ImportError(
ImportError: No Qt bindings could be found.

napari requires either PyQt5 or PySide2 to be installed in the environment.
To install the default backend (currently PyQt5), run "pip install napari[all]"
You may also use "pip install napari[pyside2]"for Pyside2, or "pip install napari[pyqt5]" for PyQt5
```

I could then install PyQt5, but I remember some discussions where this was not recommended. Should I do it anyway?
Is there something missing in the documentation of this installation procedure?

**Comment by psobolewskiPhD** [comment]
Those are the stable, released napari docs, while we've made a change to dev env installation. 
😂 
Any how, now by default dev doesn't install Qt. Please use the version switcher of the docs for the details and let us know if it's sufficiently clear.

**Comment by Czaki** [comment]
It was changed, but the change is visible only in the dev version of docs: 
https://napari.org/dev/developers/contributing.html

We remove the backend selection in `dev` extra, so you need to specify it manually or install it in a separate call.

**Comment by zoccoler** [comment]
Ah all good then, my bad for looking at the wrong page version 😆 
It works like a charm now.
