### ISSUE TITLE
napari surfaces do not support non-triangular faces

### ISSUE THREAD

**Issue by GenevieveBuckley** [napari/napari#5601]
## 🚀 Feature
Support for non-triangular faces in napari surface meshes (eg: square cell faces)

## Motivation
Ideally, it'd be good if users could drag and drop any surface mesh created by a third party program into napari. Currently, only meshes with triangular faces are supported.

## Pitch
I think napari should adopt an internal surface data structure similar to the [meshio](https://github.com/nschloe/meshio) mesh data structure. 

This doesn't necessarily mean including meshio as a dependency, we could use dictionaries and numpy arrays to handle it.

Vispy supports meshes with quad faces. At least, this example did not make an error when I tried it:
```python
import numpy as np
from vispy.visuals import MeshVisual

# A rectangle made out of two triangles.
vertices = np.array([(0, 0, 0), (1, 0, 1), (1, 1, 1), (0, 1, 0)])
faces = np.array([(0, 1, 2), (0, 2, 3)])
mesh = MeshVisual(vertices=vertices, faces=faces)

# A rectangle made out of one quad.
vertices = np.array([(0, 0, 0), (1, 0, 1), (1, 1, 1), (0, 1, 0)])
faces = np.array([(0, 1, 2, 3)])
mesh = MeshVisual(vertices=vertices, faces=faces)
```

I'm unsure if Vispy supports meshes with a combination of both triangle and quad faces in the same mesh (probably not?). But that might not be a very common format, I don't know.

## Alternatives

I haven't thought much about alternatives, I wanted to open a discussion first.

One obvious alternative is to leave it unsupported, but that seems like a pity to do, especially when it seems to be a limitation of napari, not Vispy.

## Additional context

I've been working more recently with surface mesh data. So, one of the things I was doing was writing a plugin to support reading/writing these formats. That's how I'm finding out about all these funny edge cases.

* plugin: [napari-meshio](https://github.com/GenevieveBuckley/napari-meshio)
* triangular mesh example data: [TurboSquid model page "Absinthe Glass"](https://www.turbosquid.com/3d-models/3d-absinthe-glass-2006611); [google drive link](https://drive.google.com/file/d/1b8dfrMAGJY88TC3PhVxO8zgICNR9UIu9/view?usp=share_link)
* quad mesh example data: [TurboSquid model page "Quad sphere"](https://www.turbosquid.com/3d-models/quads-sphere-3ds-free/730832); [google drive link](https://drive.google.com/file/d/1Jg2B3ewpTNVOszwa8ciK2F7BXWeEgxeJ/view?usp=share_link)

**Comment by GenevieveBuckley** [comment]
Here's a minimal, reproducible example in napari.

```python
import napari
import numpy as np
from vispy.visuals import MeshVisual

# We can make a triangle mesh in VisPy, this works
# A rectangle made out of two triangles.
tri_vertices = np.array([(0, 0, 0), (1, 0, 1), (1, 1, 1), (0, 1, 0)])
tri_faces = np.array([(0, 1, 2), (0, 2, 3)])
tri_mesh = MeshVisual(vertices=tri_vertices, faces=tri_faces)  # works

# We can also make a quad mesh in VisPy, this doesn't give an error either
# A rectangle made out of one quad.
quad_vertices = np.array([(0, 0, 0), (1, 0, 1), (1, 1, 1), (0, 1, 0)])
quad_faces = np.array([(0, 1, 2, 3)])
quad_mesh = MeshVisual(vertices=quad_vertices, faces=quad_faces)  # also works


viewer = napari.Viewer(ndisplay=3)
viewer.add_surface((tri_vertices, tri_faces))  # this works
```

![vispy-tri-mesh](https://user-images.githubusercontent.com/30920819/222624665-97f76f23-f0de-4a8d-89cf-3cd0a1ecc7ba.png)

But when we try to display the quad mesh, there is an error

```python
import napari

viewer = napari.Viewer(ndisplay=3)
viewer.add_surface((quad_vertices, quad_faces))  # ERROR
```

```python-traceback
WARNING: Error drawing visual <SurfaceVisual at 0x151357910>
Traceback (most recent call last):
  File "/Users/genevieb/mambaforge/envs/napari-dev/lib/python3.10/site-packages/vispy/app/backends/_qt.py", line 903, in paintGL
    self._vispy_canvas.events.draw(region=None)
  File "/Users/genevieb/mambaforge/envs/napari-dev/lib/python3.10/site-packages/vispy/util/event.py", line 453, in __call__
    self._invoke_callback(cb, event)
  File "/Users/genevieb/mambaforge/envs/napari-dev/lib/python3.10/site-packages/vispy/util/event.py", line 471, in _invoke_callback
    _handle_exception(self.ignore_callback_errors,
  File "/Users/genevieb/mambaforge/envs/napari-dev/lib/python3.10/site-packages/vispy/util/event.py", line 469, in _invoke_callback
    cb(event)
  File "/Users/genevieb/mambaforge/envs/napari-dev/lib/python3.10/site-packages/vispy/scene/canvas.py", line 218, in on_draw
    self._draw_scene()
  File "/Users/genevieb/mambaforge/envs/napari-dev/lib/python3.10/site-packages/vispy/scene/canvas.py", line 277, in _draw_scene
    self.draw_visual(self.scene)
  File "/Users/genevieb/mambaforge/envs/napari-dev/lib/python3.10/site-packages/vispy/scene/canvas.py", line 315, in draw_visual
    node.draw()
  File "/Users/genevieb/mambaforge/envs/napari-dev/lib/python3.10/site-packages/vispy/scene/visuals.py", line 103, in draw
    self._visual_superclass.draw(self)
  File "/Users/genevieb/mambaforge/envs/napari-dev/lib/python3.10/site-packages/vispy/visuals/visual.py", line 451, in draw
    self._program.draw(self._vshare.draw_mode,
  File "/Users/genevieb/mambaforge/envs/napari-dev/lib/python3.10/site-packages/vispy/visuals/shaders/program.py", line 102, in draw
    Program.draw(self, *args, **kwargs)
  File "/Users/genevieb/mambaforge/envs/napari-dev/lib/python3.10/site-packages/vispy/gloo/program.py", line 505, in draw
    raise RuntimeError('All attributes must have the same size, got:\n{msg}')
RuntimeError: All attributes must have the same size, got:
{msg}

If you suspect this is an IPython 8.8.0 bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

In [26]: %tb
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
File ~/mambaforge/envs/napari-dev/lib/python3.10/site-packages/vispy/util/event.py:453, in EventEmitter.__call__(self, *args, **kwargs)
    450 if self._emitting > 1:
    451     raise RuntimeError('EventEmitter loop detected!')
--> 453 self._invoke_callback(cb, event)
    454 if event.blocked:
    455     break

File ~/mambaforge/envs/napari-dev/lib/python3.10/site-packages/vispy/util/event.py:471, in EventEmitter._invoke_callback(self, cb, event)
    469     cb(event)
    470 except Exception:
--> 471     _handle_exception(self.ignore_callback_errors,
    472                       self.print_callback_errors,
    473                       self, cb_event=(cb, event))

File ~/mambaforge/envs/napari-dev/lib/python3.10/site-packages/vispy/util/event.py:469, in EventEmitter._invoke_callback(self, cb, event)
    467 def _invoke_callback(self, cb, event):
    468     try:
--> 469         cb(event)
    470     except Exception:
    471         _handle_exception(self.ignore_callback_errors,
    472                           self.print_callback_errors,
    473                           self, cb_event=(cb, event))

File ~/mambaforge/envs/napari-dev/lib/python3.10/site-packages/vispy/scene/canvas.py:218, in SceneCanvas.on_draw(self, event)
    215 # Now that a draw event is going to be handled, open up the
    216 # scheduling of further updates
    217 self._update_pending = False
--> 218 self._draw_scene()

File ~/mambaforge/envs/napari-dev/lib/python3.10/site-packages/vispy/scene/canvas.py:277, in SceneCanvas._draw_scene(self, bgcolor)
    275     bgcolor = self._bgcolor
    276 self.context.clear(color=bgcolor, depth=True)
--> 277 self.draw_visual(self.scene)

File ~/mambaforge/envs/napari-dev/lib/python3.10/site-packages/vispy/scene/canvas.py:315, in SceneCanvas.draw_visual(self, visual, event)
    313         else:
    314             if hasattr(node, 'draw'):
--> 315                 node.draw()
    316                 prof.mark(str(node))
    317 else:

File ~/mambaforge/envs/napari-dev/lib/python3.10/site-packages/vispy/scene/visuals.py:103, in VisualNode.draw(self)
    101 if self.picking and not self.interactive:
    102     return
--> 103 self._visual_superclass.draw(self)

File ~/mambaforge/envs/napari-dev/lib/python3.10/site-packages/vispy/visuals/visual.py:451, in Visual.draw(self)
    449 self._configure_gl_state()
    450 try:
--> 451     self._program.draw(self._vshare.draw_mode,
    452                        self._vshare.index_buffer)
    453 except Exception:
    454     logger.warning("Error drawing visual %r" % self)

File ~/mambaforge/envs/napari-dev/lib/python3.10/site-packages/vispy/visuals/shaders/program.py:102, in ModularProgram.draw(self, *args, **kwargs)
    100 self.build_if_needed()
    101 self.update_variables()
--> 102 Program.draw(self, *args, **kwargs)

File ~/mambaforge/envs/napari-dev/lib/python3.10/site-packages/vispy/gloo/program.py:505, in Program.draw(self, mode, indices, check_error)
    503 if not all(s == sizes[0] for s in sizes[1:]):
    504     msg = '\n'.join([f'{str(a)}: {a.size}' for a in attrs])
--> 505     raise RuntimeError('All attributes must have the same size, got:\n{msg}')
    507 attrs_with_div = [a for a in attributes if a not in attrs]
    508 if attrs_with_div:

RuntimeError: All attributes must have the same size, got:
{msg}

ipdb> msg
'<VertexBuffer size=4 last_dim=1>: 4\n<VertexBuffer size=3 last_dim=3>: 3\n<VertexBuffer size=4 last_dim=3>: 4\n<VertexBuffer size=4 last_dim=3>: 4'
```

**Comment by GenevieveBuckley** [comment]
I should add, I don't personally need this feature right now. But it seems like it exists more because of an oversight, rather than a considered decision not to support these cases, so I think we should have the discussion.

**Comment by jni** [comment]
Thanks @GenevieveBuckley! If vispy supports it then it should be pretty easy for us to do the same, I think...!

**Comment by aganders3** [comment]
I'm not positive, but I don't think vsipy currently supports quad meshes. Have you tried to actually draw it? The `MeshData` class seems to specifically expect triangles at least:
https://vispy.org/api/vispy.geometry.meshdata.html#module-vispy.geometry.meshdata
https://github.com/vispy/vispy/blob/c0d7457a7b1717d47baa8b8622faa2c67bbe4be0/vispy/geometry/meshdata.py#L122

Is converting to triangles acceptable? I'm not sure if that better fits in the reader or when constructing the Surface layer. I suppose this would not be sufficient if you want to render the quad wireframe.

**Comment by GenevieveBuckley** [comment]
You're right, we run into problems when vispy actually tries to draw a quad mesh.

I took the vispy [`mesh_normals.py` example](https://github.com/vispy/vispy/blob/main/examples/scene/mesh_normals.py) and confirmed that it runs. Then I made a copy of that script, called the copy `mesh_normals_quad.py`, and changed the line that loads the data to:

```
mesh_file = "path/to/only_quad_sphere.obj"
```

Then I tried to run the example again with our new data, and there is an error when the mesh is drawn.

<details>
<summary>Error message:</summary>

```python-traceback
python mesh_normals_quad.py
WARNING: Notice reading .OBJ: material properties are ignored.
WARNING: Error drawing visual <Mesh at 0x116d0b8e0>
WARNING: Traceback (most recent call last):
  File "/Users/genevieb/Documents/temp/vispy_examples/mesh_normals_quad.py", line 50, in <module>
    canvas.show()
  File "/Users/genevieb/mambaforge/envs/napari-dev/lib/python3.10/site-packages/vispy/app/canvas.py", line 435, in show
    self._backend._vispy_set_visible(visible)
  File "/Users/genevieb/mambaforge/envs/napari-dev/lib/python3.10/site-packages/vispy/app/backends/_qt.py", line 471, in _vispy_set_visible
    self.showNormal()
  File "/Users/genevieb/mambaforge/envs/napari-dev/lib/python3.10/site-packages/vispy/app/backends/_qt.py", line 567, in event
    out = super(QtBaseCanvasBackend, self).event(ev)
  File "/Users/genevieb/mambaforge/envs/napari-dev/lib/python3.10/site-packages/vispy/app/backends/_qt.py", line 567, in event
    out = super(QtBaseCanvasBackend, self).event(ev)
  File "/Users/genevieb/mambaforge/envs/napari-dev/lib/python3.10/site-packages/vispy/app/backends/_qt.py", line 903, in paintGL
    self._vispy_canvas.events.draw(region=None)
  File "/Users/genevieb/mambaforge/envs/napari-dev/lib/python3.10/site-packages/vispy/util/event.py", line 453, in __call__
    self._invoke_callback(cb, event)
  File "/Users/genevieb/mambaforge/envs/napari-dev/lib/python3.10/site-packages/vispy/util/event.py", line 471, in _invoke_callback
    _handle_exception(self.ignore_callback_errors,
  << caught exception here: >>
  File "/Users/genevieb/mambaforge/envs/napari-dev/lib/python3.10/site-packages/vispy/util/event.py", line 469, in _invoke_callback
    cb(event)
  File "/Users/genevieb/mambaforge/envs/napari-dev/lib/python3.10/site-packages/vispy/scene/canvas.py", line 218, in on_draw
    self._draw_scene()
  File "/Users/genevieb/mambaforge/envs/napari-dev/lib/python3.10/site-packages/vispy/scene/canvas.py", line 277, in _draw_scene
    self.draw_visual(self.scene)
  File "/Users/genevieb/mambaforge/envs/napari-dev/lib/python3.10/site-packages/vispy/scene/canvas.py", line 315, in draw_visual
    node.draw()
  File "/Users/genevieb/mambaforge/envs/napari-dev/lib/python3.10/site-packages/vispy/scene/visuals.py", line 103, in draw
    self._visual_superclass.draw(self)
  File "/Users/genevieb/mambaforge/envs/napari-dev/lib/python3.10/site-packages/vispy/visuals/visual.py", line 451, in draw
    self._program.draw(self._vshare.draw_mode,
  File "/Users/genevieb/mambaforge/envs/napari-dev/lib/python3.10/site-packages/vispy/visuals/shaders/program.py", line 102, in draw
    Program.draw(self, *args, **kwargs)
  File "/Users/genevieb/mambaforge/envs/napari-dev/lib/python3.10/site-packages/vispy/gloo/program.py", line 505, in draw
    raise RuntimeError('All attributes must have the same size, got:\n{msg}')
RuntimeError: All attributes must have the same size, got:
{msg}
ERROR: Invoking <bound method SceneCanvas.on_draw of <SceneCanvas (PyQt5) at 0x1331eebc0>> for DrawEvent
Key bindings:
 f : toggle face normals
 v : toggle vertex normals
WARNING: Error drawing visual <Mesh at 0x116d0b8e0>
ERROR: Invoking <bound method SceneCanvas.on_draw of <SceneCanvas (PyQt5) at 0x1331eebc0>> repeat 2
WARNING: Error drawing visual <Mesh at 0x116d0b8e0>
```

</details>

**Comment by GenevieveBuckley** [comment]
Summary:
1. Vispy does not support quad meshes. 
2. Vispy *definitely* does not support mixed shape meshes, containing both quads and triangles.

Here is an issue also discussing problems displaying quad meshes with Vispy:  https://github.com/vispy/vispy/issues/1938
