### ISSUE TITLE
[Python>3.11.1] Conda-forge deployments of napari-plugins suddenly fail because of some issue with napari settings

### ISSUE THREAD

**Issue by haesleinhuepf** [napari/napari#5705]
## 🐛 Bug

Hi all,

updating some of my napari-plugins on conda-forge currently fails because of an issue with bundled-app and something in napari (see [here](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=685942&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d&l=769) and error log below.

## To Reproduce

I updated one of my plugins on pypi and afterwards a github-CI bot updating the conda-package failed with this error:
```
import: 'napari_assistant'
Traceback (most recent call last):
  File "/home/conda/feedstock_root/build_artifacts/napari-assistant_1680827280743/test_tmp/run_test.py", line 2, in <module>
    import napari_assistant
  File "/home/conda/feedstock_root/build_artifacts/napari-assistant_1680827280743/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python3.11/site-packages/napari_assistant/__init__.py", line 1, in <module>
    from ._gui import Assistant
  File "/home/conda/feedstock_root/build_artifacts/napari-assistant_1680827280743/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python3.11/site-packages/napari_assistant/_gui/__init__.py", line 1, in <module>
    from ._Assistant import Assistant
  File "/home/conda/feedstock_root/build_artifacts/napari-assistant_1680827280743/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python3.11/site-packages/napari_assistant/_gui/_Assistant.py", line 9, in <module>
    from .._categories import CATEGORIES, Category, filter_categories, find_function, get_category_of_function
  File "/home/conda/feedstock_root/build_artifacts/napari-assistant_1680827280743/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python3.11/site-packages/napari_assistant/_categories.py", line 6, in <module>
    from napari.layers import Image, Labels, Layer
  File "/home/conda/feedstock_root/build_artifacts/napari-assistant_1680827280743/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python3.11/site-packages/napari/layers/__init__.py", line 11, in <module>
    from .base import Layer
  File "/home/conda/feedstock_root/build_artifacts/napari-assistant_1680827280743/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python3.11/site-packages/napari/layers/base/__init__.py", line 1, in <module>
    from .base import Layer, no_op
  File "/home/conda/feedstock_root/build_artifacts/napari-assistant_1680827280743/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python3.11/site-packages/napari/layers/base/base.py", line 28, in <module>
    from ...utils.key_bindings import KeymapProvider
  File "/home/conda/feedstock_root/build_artifacts/napari-assistant_1680827280743/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python3.11/site-packages/napari/utils/key_bindings.py", line 46, in <module>
    from ..settings import get_settings
  File "/home/conda/feedstock_root/build_artifacts/napari-assistant_1680827280743/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python3.11/site-packages/napari/settings/__init__.py", line 6, in <module>
    from ._napari_settings import CURRENT_SCHEMA_VERSION, NapariSettings
  File "/home/conda/feedstock_root/build_artifacts/napari-assistant_1680827280743/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python3.11/site-packages/napari/settings/_napari_settings.py", line 14, in <module>
    from ._plugins import PluginsSettings
  File "/home/conda/feedstock_root/build_artifacts/napari-assistant_1680827280743/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python3.11/site-packages/napari/settings/_plugins.py", line 27, in <module>
    class PluginsSettings(EventedSettings):
  File "/home/conda/feedstock_root/build_artifacts/napari-assistant_1680827280743/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python3.11/site-packages/napari/settings/_plugins.py", line 75, in PluginsSettings
    class NapariConfig:
  File "/home/conda/feedstock_root/build_artifacts/napari-assistant_1680827280743/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python3.11/site-packages/napari/settings/_plugins.py", line 83, in NapariConfig
    if running_as_bundled_app() or running_as_constructor_app():
       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/conda/feedstock_root/build_artifacts/napari-assistant_1680827280743/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python3.11/site-packages/napari/utils/misc.py", line 67, in running_as_bundled_app
    metadata = importlib.metadata.metadata(app_module)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/conda/feedstock_root/build_artifacts/napari-assistant_1680827280743/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python3.11/importlib/metadata/__init__.py", line 998, in metadata
    return Distribution.from_name(distribution_name).metadata
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/conda/feedstock_root/build_artifacts/napari-assistant_1680827280743/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python3.11/importlib/metadata/__init__.py", line 561, in from_name
    raise ValueError("A distribution name is required.")
ValueError: A distribution name is required.

```

Any hint is welcome!

**Comment by psobolewskiPhD** [comment]
Is this on python 3.11.1 btw? It looks like this issue:
https://github.com/napari/napari/issues/5554

Which has been solved on main, but the fix isn't release yet:
https://github.com/napari/napari/pull/5482/files

Edit: Looks like yes, python 3.11: 
`    python:                        3.11.3-h2755cc3_0_cpython   conda-forge`

**Comment by haesleinhuepf** [comment]
Thanks for the light speed response @psobolewskiPhD !

I'll try to pin python < 3.11 and see if this helps

**Comment by psobolewskiPhD** [comment]
If you need 3.11, you should be able to use 3.11.0

**Comment by haesleinhuepf** [comment]
No I don't. None of my napari-plugins have 3.11 specified as compatible. Thanks for the hint though!

**Comment by psobolewskiPhD** [comment]
OK, conda-forge was on python 3.11.0 for a while, so it masked the issue.
Frankly, I wonder if we should rebuilt napari 0.4.17 conda-forge package with python pin to <3.11.1, because of this—and maybe repo-patch ?
@jaimergp @goanpeca any thoughts?

**Comment by haesleinhuepf** [comment]
[Pinning Python to <3.11](https://github.com/conda-forge/napari-assistant-feedstock/pull/31/commits/18e99bbdb526f0d72b4c0ebe6c16f53979ee17c8) resolved the issue. Thanks again @psobolewskiPhD

**Comment by jaimergp** [comment]
> OK, conda-forge was on python 3.11.0 for a while, so it masked the issue. Frankly, I wonder if we should rebuilt napari 0.4.17 conda-forge package with python pin to <3.11.1, because of this—and maybe repo-patch ? @jaimergp @goanpeca any thoughts?

Repodata patching might be enough. Are we certain the incompatibility is only with 3.11.1, or also versions to come? IOW, `!=3.11.1` or `<=3.11.1`?

**Comment by psobolewskiPhD** [comment]
3.11.1, 3.11.2, and 3.11.3 all fail in the same way.
The change to `importlib.metadata.Distribution` was introduced in 3.11.1

Edit: to be safe, because we don't have tests running on 3.11, so there may be (likely are?) other issues, I would just pin <3.11

**Comment by jaimergp** [comment]
Patched in https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/438

**Comment by psobolewskiPhD** [comment]
I can confirm that the fix works:
`mamba create -n napari-311 python=3.11 napari --dry-run `
yields:
```
Could not solve for environment specs
The following packages are incompatible
├─ napari   is installable and it requires
│  └─ python [>=3.6,<3.11.0a0 |>=3.7,<3.11.0a0 |>=3.8,<3.11.0a0 ], which can be installed;
└─ python 3.11**  is uninstallable because it conflicts with any installable versions previously reported.
```
Thanks @dstansby and @jaimergp
