### ISSUE TITLE
feature_defaults in add_points does not work when not providing features

### ISSUE THREAD

**Issue by constantinpape** [napari/napari#5790]
## 🐛 Bug

Passing `feature_defaults` to `add_points` fails when features are not provided. However, there are use cases where `features` (and also points) are not known yet when creating the layer.

## To Reproduce

This code can reproduce the error:
```python
import napari
v = napari.Viewer()
v.add_points(
    data=[[0.0, 0.0], [1.0, 1.0]],
    # features={"label": ["True", "True"]},
    feature_defaults={"label": ["True"]},
)
napari.run()
```
and fails with
```
Traceback (most recent call last):
  File "/home/pape/Work/playground/napari/check_points.py", line 3, in <module>
    v.add_points(
  File "/home/pape/Work/my_projects/napari/napari/napari/components/viewer_model.py", line 4, in add_points
    import itertools
  File "/home/pape/Work/my_projects/napari/napari/napari/layers/points/points.py", line 440, in __init__
    self._feature_table = _FeatureTable.from_layer(
  File "/home/pape/Work/my_projects/napari/napari/napari/layers/utils/layer_utils.py", line 882, in from_layer
    return cls(features, defaults=feature_defaults, num_data=num_data)
  File "/home/pape/Work/my_projects/napari/napari/napari/layers/utils/layer_utils.py", line 714, in __init__
    self._defaults = _validate_feature_defaults(defaults, self._values)
  File "/home/pape/Work/my_projects/napari/napari/napari/layers/utils/layer_utils.py", line 947, in _validate_feature_defaults
    raise ValueError(
ValueError: Feature defaults contain some extra columns not in feature values: {'label'}
```
Note that it works when passing `features` (removing the comment in the code).

## Expected behavior

This should work and the viewer with a point layer should open.

## Environment

```
napari: 0.5.0a2.dev108+g9fb9fbe1
Platform: Linux-5.15.0-71-generic-x86_64-with-glibc2.31
System: Ubuntu 20.04.6 LTS
Python: 3.10.10 | packaged by conda-forge | (main, Mar 24 2023, 20:08:06) [GCC 11.3.0]
Qt: 5.15.2
PyQt5: 5.15.9
NumPy: 1.24.3
SciPy: 1.10.1
Dask: 2023.4.1
VisPy: 0.12.2
magicgui: 0.7.2
superqt: unknown
in-n-out: 0.1.7
app-model: 0.1.4
npe2: 0.7.0

OpenGL:
- GL version: 4.6 (Compatibility Profile) Mesa 21.2.6
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1920x1200, scale 1.0

Settings path:
- /home/pape/.config/napari/napari-dev_3f7349573134419bc6e0579d36ac230a3ffe2f50/settings.yaml
```

## Additional context

I encountered this while working on https://github.com/napari/docs/pull/145.

**Comment by andy-sweet** [comment]
Thanks for the detailed bug description.

To clarify, do you want `data` and `features` to have a different length (i.e. 2 points, but 0 `label` features yet) as in the reproducer? I'm worried that could open napari up to more bugs in the future due to the lengths (and other related things) getting out of sync as points are interactively added.

Or would you only want to provide `feature_defaults` and not `features` when `data` is empty?

Alternatively, would providing missing values (e.g. [using pandas](https://pandas.pydata.org/docs/user_guide/missing_data.html)) be a viable solution here?

**Comment by constantinpape** [comment]
> Or would you only want to provide `feature_defaults` and not `features` when `data` is empty?

Yes, that's the use case. I only want to provide the `feature_defaults`, because the points have not been added yet. So both `features` and `data` are empty upon layer creation as they will be provided by user annotations.

I see now that my example is a bit confusing since I pass non-empty data. But the same error is thrown for the following:
```python
import napari
v = napari.Viewer()
v.add_points(
    feature_defaults={"label": ["True"]},
)
napari.run()
```

> Alternatively, would providing missing values (e.g. [using pandas](https://pandas.pydata.org/docs/user_guide/missing_data.html)) be a viable solution here?

This sounds like a viable solution. How exactly would I do this in the situation here?

**Comment by andy-sweet** [comment]
Thanks for clarifying!

If you need a workaround in that case that should work on `main` and `v0.4.17`, then you could specify explicitly empty arrays with their intended dtype:

```python
import napari
import numpy as np
viewer = napari.Viewer()
points = viewer.add_points(
    features={"label": np.array([], dtype=bool)},
)
# Optionally force the default value.
points.feature_defaults["label"] = False
napari.run()
```

For true missing features values (but present points data), you could do

```python
import napari
import pandas as pd
viewer = napari.Viewer()
points = viewer.add_points(
    data=[[0, 0], [1, 1]],
    features=pd.DataFrame({"label": pd.array([pd.NA, pd.NA], dtype="boolean")}),
)
napari.run()
```

though this is not well tested (at least by me!) and is a little sensitive to the exact form you pass to napari (since it may do some value coercion.

**Comment by andy-sweet** [comment]
I'll also look at adding some logic to handle the case when `feature_defaults` is passed but `features` is not, so that `features` is populated with correctly type empty columns.

**Comment by constantinpape** [comment]
Thanks @andy-sweet,
the first snippet you have shared works for my use case. (Though not that it won't work in 0.4.17 because `feature_defaults` are immutable, but this does not matter for me right now.)
I will continue with this for now.

> I'll also look at adding some logic to handle the case when `feature_defaults` is passed but `features` is not, so that `features` is populated with correctly type empty columns.

Great! Happy to test that once it's there.

**Comment by andy-sweet** [comment]
> (Though not that it won't work in 0.4.17 because `feature_defaults` are immutable, but this does not matter for me right now.)

Actually, they should be mutable in-place (as in the example above). It's just that there is no setter in v0.4.17.
