### ISSUE TITLE
3D viewing in-n-out bug

### ISSUE THREAD

**Issue by JoOkuma** [napari/napari#5803]
## 🐛 Bug

Sometimes napari doesn't allow to change from 2D to 3D mode, resulting in the error:

```python3
Traceback (most recent call last):
  File "/home/jordao/miniconda3/envs/embed/lib/python3.10/site-packages/in_n_out/_store.py", line 805, in _exec
    result = func(**bound.arguments)
TypeError: toggle_ndisplay() missing 1 required positional argument: 'viewer'
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
File ~/miniconda3/envs/embed/lib/python3.10/site-packages/in_n_out/_store.py:805, in Store.inject.<locals>._inner.<locals>._exec(*args=(), **kwargs={})
    804 try:
--> 805     result = func(**bound.arguments)
        bound = <BoundArguments ()>
        func = <function toggle_ndisplay at 0x7f600fe9b010>
        bound.arguments = {}
    806 except TypeError as e:

TypeError: toggle_ndisplay() missing 1 required positional argument: 'viewer'

The above exception was the direct cause of the following exception:

TypeError                                 Traceback (most recent call last)
File ~/miniconda3/envs/embed/lib/python3.10/site-packages/napari/utils/action_manager.py:227, in ActionManager.bind_button.<locals>.<lambda>()
    219     if isgeneratorfunction(action):
    220         raise ValueError(
    221             trans._(
    222                 '`bind_button` cannot be used with generator functions',
    223                 deferred=True,
    224             )
    225         )
--> 227 button.clicked.connect(lambda: self.trigger(name))
        name = 'napari:toggle_ndisplay'
        self = <napari.utils.action_manager.ActionManager object at 0x7f601ca27a00>
    228 if name in self._actions:
    229     button.setToolTip(
    230         f'{self._build_tooltip(name)} {extra_tooltip_text}'
    231     )

File ~/miniconda3/envs/embed/lib/python3.10/site-packages/napari/utils/action_manager.py:427, in ActionManager.trigger(self=<napari.utils.action_manager.ActionManager object>, name='napari:toggle_ndisplay')
    425 def trigger(self, name: str) -> Any:
    426     """Trigger the action `name`."""
--> 427     return self._actions[name].injected()
        self._actions[name].injected = <function toggle_ndisplay at 0x7f5f90279f30>
        self._actions[name] = Action(command=<function toggle_ndisplay at 0x7f600fe9b010>, description='Toggle ndisplay.', keymapprovider=<class 'napari.components.viewer_model.ViewerModel'>, repeatable=False)
        self._actions = {'napari:orient_plane_normal_along_z': Action(command=<function orient_plane_normal_along_z at 0x7f601c6a4e50>, description='Orient plane normal along z-axis', keymapprovider=<class 'napari.layers.image.image.Image'>, repeatable=False), 'napari:orient_plane_normal_along_y': Action(command=<function orient_plane_normal_along_y at 0x7f601c6a4f70>, description='orient plane normal along y-axis', keymapprovider=<class 'napari.layers.image.image.Image'>, repeatable=False), 'napari:orient_plane_normal_along_x': Action(command=<function orient_plane_normal_along_x at 0x7f601c6a5000>, description='orient plane normal along x-axis', keymapprovider=<class 'napari.layers.image.image.Image'>, repeatable=False), 'napari:orient_plane_normal_along_view_direction': Action(command=<function orient_plane_normal_along_view_direction at 0x7f601c6a4dc0>, description='orient plane normal along view direction', keymapprovider=<class 'napari.layers.image.image.Image'>, repeatable=False), 'napari:activate_image_select_mode': Action(command=<function activate_image_select_mode at 0x7f601c6a51b0>, description='Transform', keymapprovider=<class 'napari.layers.image.image.Image'>, repeatable=False), 'napari:activate_image_pan_zoom_mode': Action(command=<function activate_image_pan_zoom_mode at 0x7f601c6a5240>, description='Pan/zoom', keymapprovider=<class 'napari.layers.image.image.Image'>, repeatable=False), 'napari:activate_paint_mode': Action(command=<function activate_paint_mode at 0x7f601c6b4b80>, description='Activate the paint brush', keymapprovider=<class 'napari.layers.labels.labels.Labels'>, repeatable=False), 'napari:activate_fill_mode': Action(command=<function activate_fill_mode at 0x7f601c6b4ca0>, description='Activate the fill bucket', keymapprovider=<class 'napari.layers.labels.labels.Labels'>, repeatable=False), 'napari:activate_label_pan_zoom_mode': Action(command=<function activate_label_pan_zoom_mode at 0x7f601c6b4dc0>, description='Pan/zoom mode', keymapprovider=<class 'napari.layers.labels.labels.Labels'>, repeatable=False), 'napari:activate_label_picker_mode': Action(command=<function activate_label_picker_mode at 0x7f601c6b4ee0>, description='Pick mode', keymapprovider=<class 'napari.layers.labels.labels.Labels'>, repeatable=False), 'napari:activate_label_erase_mode': Action(command=<function activate_label_erase_mode at 0x7f601c6b5000>, description='Activate the label eraser', keymapprovider=<class 'napari.layers.labels.labels.Labels'>, repeatable=False), 'napari:new_label': Action(command=<function new_label at 0x7f601c6b5090>, description='Set the currently selected label to the largest used label plus one.', keymapprovider=<class 'napari.layers.labels.labels.Labels'>, repeatable=False), 'napari:decrease_label_id': Action(command=<function decrease_label_id at 0x7f601c6b5120>, description='Decrease the currently selected label by one.', keymapprovider=<class 'napari.layers.labels.labels.Labels'>, repeatable=False), 'napari:increase_label_id': Action(command=<function increase_label_id at 0x7f601c6b51b0>, description='Increase the currently selected label by one.', keymapprovider=<class 'napari.layers.labels.labels.Labels'>, repeatable=False), 'napari:decrease_brush_size': Action(command=<function decrease_brush_size at 0x7f601c6b5240>, description='Decrease the paint brush size by one.', keymapprovider=<class 'napari.layers.labels.labels.Labels'>, repeatable=True), 'napari:increase_brush_size': Action(command=<function increase_brush_size at 0x7f601c6b52d0>, description='Increase the paint brush size by one.', keymapprovider=<class 'napari.layers.labels.labels.Labels'>, repeatable=True), 'napari:toggle_preserve_labels': Action(command=<function toggle_preserve_labels at 0x7f601c6b53f0>, description='Toggle preserve labels', keymapprovider=<class 'napari.layers.labels.labels.Labels'>, repeatable=False), 'napari:activate_points_add_mode': Action(command=<function activate_points_add_mode at 0x7f601c527f40>, description='Add points', keymapprovider=<class 'napari.layers.points.points.Points'>, repeatable=False), 'napari:activate_points_select_mode': Action(command=<function activate_points_select_mode at 0x7f601c52c040>, description='Select points', keymapprovider=<class 'napari.layers.points.points.Points'>, repeatable=False), 'napari:activate_points_pan_zoom_mode': Action(command=<function activate_points_pan_zoom_mode at 0x7f601c52c160>, description='Pan/zoom', keymapprovider=<class 'napari.layers.points.points.Points'>, repeatable=False), 'napari:select_all_in_slice': Action(command=<function select_all_in_slice at 0x7f601c52c3a0>, description='Select all points in the current view slice.', keymapprovider=<class 'napari.layers.points.points.Points'>, repeatable=False), 'napari:select_all_data': Action(command=<function select_all_data at 0x7f601c52c430>, description='Select all points in the layer.', keymapprovider=<class 'napari.layers.points.points.Points'>, repeatable=False), 'napari:delete_selected_points': Action(command=<function delete_selected_points at 0x7f601c52c310>, description='Delete selected points', keymapprovider=<class 'napari.layers.points.points.Points'>, repeatable=False), 'napari:activate_add_rectangle_mode': Action(command=<function activate_add_rectangle_mode at 0x7f600ff57be0>, description='Add rectangles', keymapprovider=<class 'napari.layers.shapes.shapes.Shapes'>, repeatable=False), 'napari:activate_add_ellipse_mode': Action(command=<function activate_add_ellipse_mode at 0x7f600ff57d00>, description='Add ellipses', keymapprovider=<class 'napari.layers.shapes.shapes.Shapes'>, repeatable=False), 'napari:activate_add_line_mode': Action(command=<function activate_add_line_mode at 0x7f600ff57e20>, description='Add lines', keymapprovider=<class 'napari.layers.shapes.shapes.Shapes'>, repeatable=False), 'napari:activate_add_path_mode': Action(command=<function activate_add_path_mode at 0x7f600ff57f40>, description='Add path', keymapprovider=<class 'napari.layers.shapes.shapes.Shapes'>, repeatable=False), 'napari:activate_add_polygon_mode': Action(command=<function activate_add_polygon_mode at 0x7f600ff580d0>, description='Add polygons', keymapprovider=<class 'napari.layers.shapes.shapes.Shapes'>, repeatable=False), 'napari:activate_direct_mode': Action(command=<function activate_direct_mode at 0x7f600ff581f0>, description='Select vertices', keymapprovider=<class 'napari.layers.shapes.shapes.Shapes'>, repeatable=False), 'napari:activate_select_mode': Action(command=<function activate_select_mode at 0x7f600ff58310>, description='Select shapes', keymapprovider=<class 'napari.layers.shapes.shapes.Shapes'>, repeatable=False), 'napari:activate_shape_pan_zoom_mode': Action(command=<function activate_shape_pan_zoom_mode at 0x7f600ff58430>, description='Pan/Zoom', keymapprovider=<class 'napari.layers.shapes.shapes.Shapes'>, repeatable=False), 'napari:activate_vertex_insert_mode': Action(command=<function activate_vertex_insert_mode at 0x7f600ff58550>, description='Insert vertex', keymapprovider=<class 'napari.layers.shapes.shapes.Shapes'>, repeatable=False), 'napari:activate_vertex_remove_mode': Action(command=<function activate_vertex_remove_mode at 0x7f600ff58670>, description='Remove vertex', keymapprovider=<class 'napari.layers.shapes.shapes.Shapes'>, repeatable=False), 'napari:copy_selected_shapes': Action(command=<function copy_selected_shapes at 0x7f600ff58700>, description='Copy any selected shapes', keymapprovider=<class 'napari.layers.shapes.shapes.Shapes'>, repeatable=False), 'napari:paste_shape': Action(command=<function paste_shape at 0x7f600ff58790>, description='Paste any copied shapes', keymapprovider=<class 'napari.layers.shapes.shapes.Shapes'>, repeatable=False), 'napari:select_all_shapes': Action(command=<function select_all_shapes at 0x7f600ff58820>, description='Select all shapes in the current view slice', keymapprovider=<class 'napari.layers.shapes.shapes.Shapes'>, repeatable=False), 'napari:delete_selected_shapes': Action(command=<function delete_selected_shapes at 0x7f600ff588b0>, description='Delete any selected shapes', keymapprovider=<class 'napari.layers.shapes.shapes.Shapes'>, repeatable=False), 'napari:move_shapes_selection_to_front': Action(command=<function move_shapes_selection_to_front at 0x7f600ff58940>, description='Move to front', keymapprovider=<class 'napari.layers.shapes.shapes.Shapes'>, repeatable=False), 'napari:move_shapes_selection_to_back': Action(command=<function move_shapes_selection_to_back at 0x7f600ff589d0>, description='Move to back', keymapprovider=<class 'napari.layers.shapes.shapes.Shapes'>, repeatable=False), 'napari:finish_drawing_shape': Action(command=<function finish_drawing_shape at 0x7f600ff58a60>, description='Finish any drawing, for example when using the path or polygon tool.', keymapprovider=<class 'napari.layers.shapes.shapes.Shapes'>, repeatable=False), 'napari:reset_scroll_progress': Action(command=<function reset_scroll_progress at 0x7f600fe9ae60>, description='Reset scroll.', keymapprovider=<class 'napari.components.viewer_model.ViewerModel'>, repeatable=False), 'napari:toggle_ndisplay': Action(command=<function toggle_ndisplay at 0x7f600fe9b010>, description='Toggle ndisplay.', keymapprovider=<class 'napari.components.viewer_model.ViewerModel'>, repeatable=False), 'napari:toggle_theme': Action(command=<function toggle_theme at 0x7f600fe9b0a0>, description='Toggle theme.', keymapprovider=<class 'napari.components.viewer_model.ViewerModel'>, repeatable=False), 'napari:reset_view': Action(command=<function reset_view at 0x7f600fe9ad40>, description='Reset view to original state.', keymapprovider=<class 'napari.components.viewer_model.ViewerModel'>, repeatable=False), 'napari:increment_dims_left': Action(command=<function increment_dims_left at 0x7f600fe9aef0>, description='Increment dimensions slider to the left.', keymapprovider=<class 'napari.components.viewer_model.ViewerModel'>, repeatable=False), 'napari:increment_dims_right': Action(command=<function increment_dims_right at 0x7f600fe9a950>, description='Increment dimensions slider to the right.', keymapprovider=<class 'napari.components.viewer_model.ViewerModel'>, repeatable=False), 'napari:focus_axes_up': Action(command=<function focus_axes_up at 0x7f600fe9af80>, description='Move focus of dimensions slider up.', keymapprovider=<class 'napari.components.viewer_model.ViewerModel'>, repeatable=False), 'napari:focus_axes_down': Action(command=<function focus_axes_down at 0x7f600fe9ab90>, description='Move focus of dimensions slider down.', keymapprovider=<class 'napari.components.viewer_model.ViewerModel'>, repeatable=False), 'napari:roll_axes': Action(command=<function roll_axes at 0x7f600fe9a560>, description='Change order of the visible axes, e.g. [0, 1, 2] -> [2, 0, 1].', keymapprovider=<class 'napari.components.viewer_model.ViewerModel'>, repeatable=False), 'napari:transpose_axes': Action(command=<function transpose_axes at 0x7f600fe9b130>, description='Transpose order of the last two visible axes, e.g. [0, 1] -> [1, 0].', keymapprovider=<class 'napari.components.viewer_model.ViewerModel'>, repeatable=False), 'napari:toggle_grid': Action(command=<function toggle_grid at 0x7f600fe9b1c0>, description='Toggle grid mode.', keymapprovider=<class 'napari.components.viewer_model.ViewerModel'>, repeatable=False), 'napari:toggle_selected_visibility': Action(command=<function toggle_selected_visibility at 0x7f600fe9b2e0>, description='Toggle visibility of selected layers', keymapprovider=<class 'napari.components.viewer_model.ViewerModel'>, repeatable=False), 'napari:toggle_console_visibility': Action(command=<function toggle_console_visibility at 0x7f600fe9b370>, description='Show/Hide IPython console (only available when napari started as standalone application)', keymapprovider=<class 'napari.components.viewer_model.ViewerModel'>, repeatable=False), 'napari:show_shortcuts': Action(command=<function show_shortcuts at 0x7f5fee507130>, description='Show all key bindings', keymapprovider=<class 'napari.components.viewer_model.ViewerModel'>, repeatable=False), 'napari:reset_active_layer_affine': Action(command=<bound method InteractionBoxMouseBindings._reset_active_layer_affine of <napari.components._interaction_box_mouse_bindings.InteractionBoxMouseBindings object at 0x7f5f903e0eb0>>, description='Reset the affine transform of the active layer', keymapprovider=Viewer(axes=Axes(visible=False, labels=True, colored=True, dashed=False, arrows=True), camera=Camera(center=(0.0, 528.5841371303569, 498.6509764999495), zoom=0.700173010380623, angles=(0.0, 0.0, 90.0), perspective=0.0, interactive=True), cursor=Cursor(position=(395.0, 741.0, 1138.4333960957028, -619.6440302737203), scaled=True, size=1, style=<CursorStyle.STANDARD: 'standard'>), dims=Dims(ndim=4, ndisplay=2, last_used=1, range=((0.0, 791.0, 1.0), (69.0, 1234.0, 1.0), (2.0, 1159.0, 1.0), (3.0, 1061.0, 1.0)), current_step=(395, 672, 578, 529), order=(0, 1, 2, 3), axis_labels=('0', '1', '2', '3')), grid=GridCanvas(stride=1, shape=(-1, -1), enabled=False), layers=[<Points layer 'original' at 0x7f5dad55d7b0>, <Points layer 'learned' at 0x7f5dad55d6c0>], scale_bar=ScaleBar(visible=False, colored=False, color=<class 'numpy.ndarray'> (4,) float32, ticks=True, position=<Position.BOTTOM_RIGHT: 'bottom_right'>, font_size=10.0, box=False, box_color=<class 'numpy.ndarray'> (4,) float32, unit=None), text_overlay=TextOverlay(visible=False, color=<class 'numpy.ndarray'> (4,) float32, font_size=10.0, position=<TextOverlayPosition.TOP_LEFT: 'top_left'>, text=''), overlays=Overlays(interaction_box=InteractionBox(points=None, show=False, show_handle=False, show_vertices=False, selection_box_drag=None, selection_box_final=None, transform_start=<napari.utils.transforms.transforms.Affine object at 0x7f600fd311b0>, transform_drag=<napari.utils.transforms.transforms.Affine object at 0x7f600fd31210>, transform_final=<napari.utils.transforms.transforms.Affine object at 0x7f600fd31270>, transform=<napari.utils.transforms.transforms.Affine object at 0x7f600fd312d0>, allow_new_selection=True, selected_vertex=None)), help='use <2> for add points, use <3> for select points', status='', tooltip=Tooltip(visible=False, text=''), theme='dark', title='napari', mouse_over_canvas=False, mouse_move_callbacks=[<function InteractionBoxMouseBindings.initialize_mouse_events.<locals>.mouse_move at 0x7f5f9027a290>], mouse_drag_callbacks=[<function InteractionBoxMouseBindings.initialize_mouse_events.<locals>.mouse_drag at 0x7f5f90279510>], mouse_double_click_callbacks=[], mouse_wheel_callbacks=[<function dims_scroll at 0x7f600fe98310>], _persisted_mouse_event={}, _mouse_drag_gen={}, _mouse_wheel_gen={}, keymap={'Shift': <function InteractionBoxMouseBindings.initialize_key_events.<locals>.hold_to_lock_aspect_ratio at 0x7f5f902797e0>, 'Control-Shift-R': <function InteractionBoxMouseBindings._reset_active_layer_affine at 0x7f5f9022dab0>, 'Control-Shift-A': <function InteractionBoxMouseBindings._transform_active_layer at 0x7f5f9022c040>}), repeatable=False), 'napari:transform_active_layer': Action(command=<bound method InteractionBoxMouseBindings._transform_active_layer of <napari.components._interaction_box_mouse_bindings.InteractionBoxMouseBindings object at 0x7f5f903e0eb0>>, description='Activate transform mode for the active layer', keymapprovider=Viewer(axes=Axes(visible=False, labels=True, colored=True, dashed=False, arrows=True), camera=Camera(center=(0.0, 528.5841371303569, 498.6509764999495), zoom=0.700173010380623, angles=(0.0, 0.0, 90.0), perspective=0.0, interactive=True), cursor=Cursor(position=(395.0, 741.0, 1138.4333960957028, -619.6440302737203), scaled=True, size=1, style=<CursorStyle.STANDARD: 'standard'>), dims=Dims(ndim=4, ndisplay=2, last_used=1, range=((0.0, 791.0, 1.0), (69.0, 1234.0, 1.0), (2.0, 1159.0, 1.0), (3.0, 1061.0, 1.0)), current_step=(395, 672, 578, 529), order=(0, 1, 2, 3), axis_labels=('0', '1', '2', '3')), grid=GridCanvas(stride=1, shape=(-1, -1), enabled=False), layers=[<Points layer 'original' at 0x7f5dad55d7b0>, <Points layer 'learned' at 0x7f5dad55d6c0>], scale_bar=ScaleBar(visible=False, colored=False, color=<class 'numpy.ndarray'> (4,) float32, ticks=True, position=<Position.BOTTOM_RIGHT: 'bottom_right'>, font_size=10.0, box=False, box_color=<class 'numpy.ndarray'> (4,) float32, unit=None), text_overlay=TextOverlay(visible=False, color=<class 'numpy.ndarray'> (4,) float32, font_size=10.0, position=<TextOverlayPosition.TOP_LEFT: 'top_left'>, text=''), overlays=Overlays(interaction_box=InteractionBox(points=None, show=False, show_handle=False, show_vertices=False, selection_box_drag=None, selection_box_final=None, transform_start=<napari.utils.transforms.transforms.Affine object at 0x7f600fd311b0>, transform_drag=<napari.utils.transforms.transforms.Affine object at 0x7f600fd31210>, transform_final=<napari.utils.transforms.transforms.Affine object at 0x7f600fd31270>, transform=<napari.utils.transforms.transforms.Affine object at 0x7f600fd312d0>, allow_new_selection=True, selected_vertex=None)), help='use <2> for add points, use <3> for select points', status='', tooltip=Tooltip(visible=False, text=''), theme='dark', title='napari', mouse_over_canvas=False, mouse_move_callbacks=[<function InteractionBoxMouseBindings.initialize_mouse_events.<locals>.mouse_move at 0x7f5f9027a290>], mouse_drag_callbacks=[<function InteractionBoxMouseBindings.initialize_mouse_events.<locals>.mouse_drag at 0x7f5f90279510>], mouse_double_click_callbacks=[], mouse_wheel_callbacks=[<function dims_scroll at 0x7f600fe98310>], _persisted_mouse_event={}, _mouse_drag_gen={}, _mouse_wheel_gen={}, keymap={'Shift': <function InteractionBoxMouseBindings.initialize_key_events.<locals>.hold_to_lock_aspect_ratio at 0x7f5f902797e0>, 'Control-Shift-R': <function InteractionBoxMouseBindings._reset_active_layer_affine at 0x7f5f9022dab0>, 'Control-Shift-A': <function InteractionBoxMouseBindings._transform_active_layer at 0x7f5f9022c040>}), repeatable=False)}
        name = 'napari:toggle_ndisplay'
        self = <napari.utils.action_manager.ActionManager object at 0x7f601ca27a00>

File ~/miniconda3/envs/embed/lib/python3.10/site-packages/in_n_out/_store.py:817, in Store.inject.<locals>._inner.<locals>._exec(*args=(), **kwargs={})
    811     _argnames = (
    812         f"arguments: {_injected_names!r}"
    813         if _injected_names
    814         else "NO arguments"
    815     )
    816     logger.exception(e)
--> 817     raise TypeError(
        _argnames = 'NO arguments'
    818         f"After injecting dependencies for {_argnames}, {e}"
    819     ) from e
    821 return result

TypeError: After injecting dependencies for NO arguments, toggle_ndisplay() missing 1 required positional argument: 'viewer'
```

## To Reproduce

It doesn't happen every time, but just clicking the button to make the canvas 3D leads to an error, and it doesn't work.

## Expected behavior

Change the canvas to 3D mode when clicked.

## Environment

```
napari: 0.4.17
Platform: Linux-5.15.0-69-generic-x86_64-with-glibc2.31
System: Ubuntu 20.04.4 LTS
Python: 3.10.10 | packaged by conda-forge | (main, Mar 24 2023, 20:08:06) [GCC 11.3.0]
Qt: 5.15.6
PyQt5: 5.15.7
NumPy: 1.24.3
SciPy: 1.10.1
Dask: 2023.4.1
VisPy: 0.11.0
magicgui: 0.7.2
superqt: unknown
in-n-out: 0.1.7
app-model: 0.1.4
npe2: 0.7.0

OpenGL:
- GL version: 4.6.0 NVIDIA 510.108.03
- MAX_TEXTURE_SIZE: 32768

Screens:
- screen 1: resolution 3440x1440, scale 1.0
```

**Comment by Czaki** [comment]
@tlambert03 did you have any idea?

**Comment by tlambert03** [comment]
hmmm, without a minimum reproducible example it's hard to do much but guess.  The error suggests that `napari.current_viewer` is returning None somehow, but exactly why that would be i'm not sure.

here's how it works:
1. `toggle_ndisplay` is registered as a viewer_action in `_viewer_key_bindings` (with the old action_manager).
2. When triggered (by a user action or button press), the "dependency-injected" version of the `toggle_ndisplay` is called... where the injected version is returned by `action_manager.Action.injected`.
3. You can always see what functions are used to provide a given type by looking at the injection store:
    ```python
    In [1]: from napari._app_model import get_app

    In [2]: get_app().injection_store
    Out[2]: <in_n_out._store.Store at 0x10dab1f90>

    In [3]: get_app().injection_store._providers
    Out[3]:
    [_RegisteredCallback(origin=<class 'napari.viewer.Viewer'>, callback=<function _provide_viewer at 0x1321e6cb0>, hint_optional=True, weight=0, subclassable=True),
    _RegisteredCallback(origin=<class 'napari.layers.base.base.Layer'>, callback=<function _provide_active_layer at 0x132239cf0>, hint_optional=True, weight=0, subclassable=True),
    _RegisteredCallback(origin=<class 'napari.components.layerlist.LayerList'>, callback=<function _provide_active_layer_list at 0x132239b40>, hint_optional=True, weight=0, subclassable=True)]
   ```
   notice when asked to provide a `Viewer`, the injection store calls `napari._app_model.injection._providers._provide_viewer` (which simply returns `viewer.current_viewer()`

so that brings us back to why `viewer.current_viewer()` would be returning `None` for @JoOkuma?  do you have multiple viewers open?  is it possible you closed one?  can you give more info on how to reproduce it?

**Comment by Czaki** [comment]
Why when `viewer.current_viewer()` return none it is not passed to function as a value?

**Comment by tlambert03** [comment]
well, at the very least, the function doesn't state that it can take `Optional[Viewer]` ... so that would be bad (i.e. I don't think in-n-out should inject `None` into a function that doesn't explicitly state that it's ok).  The next question would be what would in-n-out do if you _did_ annotate it as such, and for that we'd have to try and/or look at in-n-out to see what would happen

**Comment by tlambert03** [comment]
ok, looks like in-n-out won't pass `None`, so if you want to just side-step this error you could do this:

```py
def toggle_ndisplay(viewer: Optional[Viewer] = None):
    ...
```

and you should be fine.  However, that has a code smell to me and seems like a cop-out.  I think you should rather try to figure out in what scenario it's ever possible for `current_viewer` to actually return `None` even as someone is clicking a button *in* a viewer :joy:

**Comment by Czaki** [comment]
In general, I prefer to pass `None` instead of having `TypeError: toggle_ndisplay() missing 1 required positional argument: 'viewer'` exception. But after rethinking the best option will be if `in-n-out` raise the proper exception (like: the provider returns `None`, when function request `Viewer` instance). To have clear messages.

**Comment by JoOkuma** [comment]
@tlambert03 @Czaki, thanks for the explanation; I'll check the `current_viewer` when this happens again.

**Comment by dalthviz** [comment]
Hi, just in case, while checking the addition of some tests at #5848 I was able to get a similar traceback that the one here by creating an instance of `ViewerModel`, `QtViewerButtons` and then simulating with `qtbot` a left mouse click over the ndisplay button. So creating and running a test like:


```python
from qtpy.QtCore import Qt

from napari._qt.widgets.qt_viewer_buttons import QtViewerButtons
from napari.components.viewer_model import ViewerModel


def test_ndisplay_button_toggle(qtbot):
    """
    Make sure the QtViewerButtons.ndisplayButton works.
    """
    # create viewer model and buttons
    viewer = ViewerModel()
    viewer_buttons = QtViewerButtons(viewer)
    assert viewer_buttons.ndisplayButton

    # toggle ndisplay
    qtbot.mouseClick(viewer_buttons.ndisplayButton, Qt.LeftButton)

```

Fails and leaves a traceback in the test captured stderr like:

```python-traceback
CALL ERROR: Exceptions caught in Qt event loop:
________________________________________________________________________________
Traceback (most recent call last):
  File "C:\Users\dalth\anaconda3\envs\napari-dev\lib\site-packages\in_n_out\_store.py", line 774, in _exec
    result = func(**_kwargs)
TypeError: toggle_ndisplay() missing 1 required positional argument: 'viewer'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\Acer\Documentos\Quansight\Napari\napari\napari\utils\action_manager.py", line 227, in <lambda>
    button.clicked.connect(lambda: self.trigger(name))
  File "E:\Acer\Documentos\Quansight\Napari\napari\napari\utils\action_manager.py", line 427, in trigger
    return self._actions[name].injected()
  File "C:\Users\dalth\anaconda3\envs\napari-dev\lib\site-packages\in_n_out\_store.py", line 781, in _exec
    raise TypeError(
TypeError: After injecting dependencies for NO arguments, toggle_ndisplay() missing 1 required positional argument: 'viewer'
```

**Comment by tlambert03** [comment]
Correct, because viewer model doesn't create a Qt viewer

**Comment by tlambert03** [comment]
(Ie without a main Qt window, there will be no current viewer)
