### ISSUE TITLE
Circular import issue when using constants from napari.components in napari.layers

### ISSUE THREAD

**Issue by ksofiyuk** [napari/napari#5846]
## 🐛 Bug

When I tried to replace the cursor style strings in `napari/layers/labels/_labels_mouse_bindings.py` with the corresponding enum members to improve readability of the code (https://github.com/napari/napari/pull/5842/commits/10c748ceafe4cae424014907960e8da466561d92, #5842 ), I faced a circular import issue when building the docs:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/hostedtoolcache/Python/3.9.[16](https://github.com/napari/napari/actions/runs/5012373806/jobs/8984257710#step:8:17)/x64/lib/python3.9/site-packages/napari/layers/__init__.py", line 11, in <module>
    from napari.layers.labels import Labels
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/napari/layers/labels/__init__.py", line 1, in <module>
    from napari.layers.labels import _labels_key_bindings
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/napari/layers/labels/_labels_key_bindings.py", line 5, in <module>
    from napari.layers.labels.labels import Labels
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/napari/layers/labels/labels.py", line [22](https://github.com/napari/napari/actions/runs/5012373806/jobs/8984257710#step:8:23), in <module>
    from napari.layers.labels._labels_mouse_bindings import (
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/napari/layers/labels/_labels_mouse_bindings.py", line 1, in <module>
    from napari.components._viewer_constants import CursorStyle
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/napari/components/__init__.py", line [24](https://github.com/napari/napari/actions/runs/5012373806/jobs/8984257710#step:8:25), in <module>
    from napari.components import _viewer_key_bindings  # isort:skip
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/napari/components/_viewer_key_bindings.py", line 5, in <module>
    from napari.components.viewer_model import ViewerModel
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/napari/components/viewer_model.py", line 46, in <module>
    from napari.layers import (
ImportError: cannot import name 'Labels' from partially initialized module 'napari.layers' (most likely due to a circular import) (/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/napari/layers/__init__.py)
Error: Process completed with exit code 1.
```

**Comment by Czaki** [comment]
One of the solutions is using delayed import. In the napari/components/_viewer_key_bindings.py the ViewerModel is used in one function. So import may be moved to the body of this function and under `if TYPE_CHECKIN` clause. 

The general solution will be to rewrite action registration, but it requires many working hours.

**Comment by andy-sweet** [comment]
I'll also mention https://github.com/napari/napari/issues/5289 as one general way to identify other lurking circular imports.

**Comment by ksofiyuk** [comment]
> One of the solutions is using delayed import. In the napari/components/_viewer_key_bindings.py the ViewerModel is used in one function. So import may be moved to the body of this function and under `if TYPE_CHECKIN` clause.

It doesn't work, I've just tried that in https://github.com/napari/napari/pull/5842/commits/38107e8208676e24a578e1fd96575b4168d37ac7, it is still getting circular import error. It is used in a decorator, so it is called during a function instantiation, it cannot be delayed.

The actual problem is not with this decorator. It comes from `napari/components/__init__.py`, which is called when you try to import anything from `napari.components`. Even if you solve the problem with the actions registration, the circular import will still be present, because `napari/components/__init__.py` imports `ViewerModel` directly after `_viewer_key_bindings`, which in turn imports `napari.layers` and so on.

**Comment by ksofiyuk** [comment]
I think the root of the issue with circular imports in napari is that constants like in `_viewer_constants.py` sit deeply inside modules and when you try get access to them they import a lot of unnecessary things through `__init__.py` in the root of modules. The same thing applies to `napari/layers/labels/_labels_constants.py` and so on.

At least constants should not be dependent on anything and should be accessible without the need to import entire modules.
