### ISSUE TITLE
Need to manually install numpydoc -- version 0.2.1

### ISSUE THREAD

**Issue by bioimage-analysis** [napari/napari#597]
## 🐛 Bug

Not sure if you are aware but after updating napari to version 0.2.1, I had to manually install numpydoc, which I didn't need before. 

## To Reproduce

Not have numpydoc installed

**Comment by jni** [comment]
@bioimage-analysis do you mean nothing works at all without numpydoc installed? Could you post the full traceback? Thanks!

**Comment by bioimage-analysis** [comment]
Well, I just tried it on a different env, I upgraded napari from 0.2.0 to 0.2.1 on that environment and here is the error message I get when I tried to import napari:

`import napari
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Applications/anaconda3/envs/chloe/lib/python3.7/site-packages/napari/__init__.py", line 29, in <module>
    from .viewer import Viewer
  File "/Applications/anaconda3/envs/chloe/lib/python3.7/site-packages/napari/viewer.py", line 1, in <module>
    from ._qt.qt_viewer import QtViewer
  File "/Applications/anaconda3/envs/chloe/lib/python3.7/site-packages/napari/_qt/qt_viewer.py", line 24, in <module>
    from .qt_dims import QtDims
  File "/Applications/anaconda3/envs/chloe/lib/python3.7/site-packages/napari/_qt/qt_dims.py", line 5, in <module>
    from ..components.dims import Dims
  File "/Applications/anaconda3/envs/chloe/lib/python3.7/site-packages/napari/components/__init__.py", line 16, in <module>
    from .dims import Dims
  File "/Applications/anaconda3/envs/chloe/lib/python3.7/site-packages/napari/components/dims.py", line 6, in <module>
    from ..util.event import EmitterGroup
  File "/Applications/anaconda3/envs/chloe/lib/python3.7/site-packages/napari/util/__init__.py", line 1, in <module>
    from .misc import is_rgb, segment_normal
  File "/Applications/anaconda3/envs/chloe/lib/python3.7/site-packages/napari/util/misc.py", line 8, in <module>
    from numpydoc.docscrape import FunctionDoc
ModuleNotFoundError: No module named 'numpydoc'`

**Comment by AhmetCanSolak** [comment]
experienced same with conda env py3.7 on mac osx mojave

**Comment by jni** [comment]
Ah, got it. This was added in #583, but we missed it because numpydoc was in our test dependencies rather than default! Fix in #598.
