### ISSUE TITLE
Can't open napari after installing it with conda in a M1 Mac

### ISSUE THREAD

**Issue by LucaMarconato** [napari/napari#6031]
## 🐛 Bug

I installed napari with conda in a clean conda env on M1 Mac and run `napari`, but it doesn't work.

## To Reproduce

1. use an M1 Mac
2. `mamba create -n napari python=3.10`
3. `conda activate napari`
4. `mamba install -c conda-forge napari`
5. `napari`

I get:
```
(napari) macbook@Lucas-MacBook-Pro ~ % napari
Traceback (most recent call last):
  File "/Users/macbook/miniconda3/envs/napari/bin/napari", line 6, in <module>
    from napari.__main__ import main
  File "/Users/macbook/miniconda3/envs/napari/lib/python3.10/site-packages/napari/__main__.py", line 16, in <module>
    from .utils.translations import trans
  File "/Users/macbook/miniconda3/envs/napari/lib/python3.10/site-packages/napari/utils/__init__.py", line 2, in <module>
    from .colormaps import Colormap
  File "/Users/macbook/miniconda3/envs/napari/lib/python3.10/site-packages/napari/utils/colormaps/__init__.py", line 2, in <module>
    from .colormap import Colormap
  File "/Users/macbook/miniconda3/envs/napari/lib/python3.10/site-packages/napari/utils/colormaps/colormap.py", line 9, in <module>
    from ..events import EventedModel
  File "/Users/macbook/miniconda3/envs/napari/lib/python3.10/site-packages/napari/utils/events/__init__.py", line 15, in <module>
    from .evented_model import EventedModel
  File "/Users/macbook/miniconda3/envs/napari/lib/python3.10/site-packages/napari/utils/events/evented_model.py", line 66, in <module>
    class EventedMetaclass(main.ModelMetaclass):
  File "/Users/macbook/miniconda3/envs/napari/lib/python3.10/site-packages/pydantic/_migration.py", line 289, in wrapper
    raise AttributeError(f'module {__name__!r} has no attribute {name!r}')
AttributeError: module 'pydantic._migration' has no attribute 'ModelMetaclass'
```

## Expected behavior

Napari should open without errors.

## Environment

I can't use `napari info` because I get the same error, but here is my `conda list` output:

```
# packages in environment at /Users/macbook/miniconda3/envs/napari:
#
# Name                    Version                   Build  Channel
alabaster                 0.7.13             pyhd8ed1ab_0    conda-forge
annotated-types           0.5.0              pyhd8ed1ab_0    conda-forge
aom                       3.5.0                h7ea286d_0    conda-forge
app-model                 0.1.4              pyhd8ed1ab_0    conda-forge
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
appnope                   0.1.3              pyhd8ed1ab_0    conda-forge
asciitree                 0.3.3                      py_2    conda-forge
asttokens                 2.2.1              pyhd8ed1ab_0    conda-forge
attrs                     23.1.0             pyh71513ae_1    conda-forge
aws-c-auth                0.6.28               h60b404a_9    conda-forge
aws-c-cal                 0.6.0                h43a37b4_0    conda-forge
aws-c-common              0.8.23               hb547adb_0    conda-forge
aws-c-compression         0.2.17               h31a6291_1    conda-forge
aws-c-event-stream        0.3.0                h537fd75_8    conda-forge
aws-c-http                0.7.10               h5019b2f_2    conda-forge
aws-c-io                  0.13.27              hf096fb3_0    conda-forge
aws-c-mqtt                0.8.13               hb92fe9a_5    conda-forge
aws-c-s3                  0.3.11               hea045c8_2    conda-forge
aws-c-sdkutils            0.1.11               h31a6291_1    conda-forge
aws-checksums             0.1.16               h31a6291_1    conda-forge
aws-crt-cpp               0.20.2              h82328f6_14    conda-forge
aws-sdk-cpp               1.10.57             h6c89a89_15    conda-forge
babel                     2.12.1             pyhd8ed1ab_1    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                pyhd8ed1ab_3    conda-forge
backports.functools_lru_cache 1.6.5              pyhd8ed1ab_0    conda-forge
blosc                     1.21.4               hc338f07_0    conda-forge
bokeh                     3.2.0              pyhd8ed1ab_0    conda-forge
brotli                    1.0.9                h1a8c8d9_9    conda-forge
brotli-bin                1.0.9                h1a8c8d9_9    conda-forge
brotli-python             1.0.9           py310h0f1eb42_9    conda-forge
brunsli                   0.1                  h9f76cd9_0    conda-forge
bzip2                     1.0.8                h620ffc9_4  
c-ares                    1.19.1               hb547adb_0    conda-forge
c-blosc2                  2.9.3                h068da5f_0    conda-forge
ca-certificates           2023.05.30           hca03da5_0  
cachey                    0.2.1              pyh9f0ad1d_0    conda-forge
certifi                   2023.5.7           pyhd8ed1ab_0    conda-forge
cfitsio                   4.2.0                h2f961c4_0    conda-forge
charls                    2.4.2                h13dd4ca_0    conda-forge
charset-normalizer        3.1.0              pyhd8ed1ab_0    conda-forge
click                     8.1.3           unix_pyhd8ed1ab_2    conda-forge
cloudpickle               2.2.1              pyhd8ed1ab_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
comm                      0.1.3              pyhd8ed1ab_0    conda-forge
contourpy                 1.1.0           py310h38f39d4_0    conda-forge
cytoolz                   0.12.0          py310h8e9501a_1    conda-forge
dask                      2023.6.1           pyhd8ed1ab_0    conda-forge
dask-core                 2023.6.1           pyhd8ed1ab_0    conda-forge
dav1d                     1.2.1                hb547adb_0    conda-forge
debugpy                   1.6.7           py310h0f1eb42_0    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
distributed               2023.6.1           pyhd8ed1ab_0    conda-forge
docstring_parser          0.15               pyhd8ed1ab_0    conda-forge
docutils                  0.17.1          py310hbe9552e_3    conda-forge
entrypoints               0.4                pyhd8ed1ab_0    conda-forge
executing                 1.2.0              pyhd8ed1ab_0    conda-forge
expat                     2.5.0                hb7217d7_1    conda-forge
fasteners                 0.17.3             pyhd8ed1ab_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.14.2               h82840c6_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
freetype                  2.12.1               hd633e50_1    conda-forge
freetype-py               2.4.0              pyhd8ed1ab_0    conda-forge
fsspec                    2023.6.0           pyh1a96a4e_0    conda-forge
gettext                   0.21.1               h0186832_0    conda-forge
gflags                    2.2.2             hc88da5d_1004    conda-forge
giflib                    5.2.1                h1a8c8d9_3    conda-forge
glib                      2.76.3               ha614eb4_0    conda-forge
glib-tools                2.76.3               ha614eb4_0    conda-forge
glog                      0.6.0                h6da1cb0_0    conda-forge
gst-plugins-base          1.22.4               h27255cc_0    conda-forge
gstreamer                 1.22.4               h8c52bba_0    conda-forge
heapdict                  1.0.1                      py_0    conda-forge
hsluv                     5.0.2              pyh44b312d_0    conda-forge
icu                       72.1                 he12128b_0    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
imagecodecs               2023.1.23       py310hcb660b6_2    conda-forge
imageio                   2.31.1             pyh24c5eb1_0    conda-forge
imagesize                 1.4.1              pyhd8ed1ab_0    conda-forge
importlib-metadata        6.7.0              pyha770c72_0    conda-forge
importlib_metadata        6.7.0                hd8ed1ab_0    conda-forge
importlib_resources       5.12.0             pyhd8ed1ab_0    conda-forge
in-n-out                  0.1.7              pyhd8ed1ab_0    conda-forge
ipykernel                 6.23.3             pyh5fb750a_0    conda-forge
ipython                   8.14.0             pyhd1c38e8_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
jedi                      0.18.2             pyhd8ed1ab_0    conda-forge
jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
jsonschema                4.17.3             pyhd8ed1ab_0    conda-forge
jupyter_client            8.3.0              pyhd8ed1ab_0    conda-forge
jupyter_core              5.3.1           py310hbe9552e_0    conda-forge
jxrlib                    1.1                  h27ca646_2    conda-forge
kiwisolver                1.4.4           py310h2887b22_1    conda-forge
krb5                      1.20.1               h69eda48_0    conda-forge
lazy_loader               0.2                pyhd8ed1ab_0    conda-forge
lcms2                     2.15                 hd835a16_1    conda-forge
lerc                      4.0.0                h9a09cb3_0    conda-forge
libabseil                 20230125.3      cxx17_h13dd4ca_0    conda-forge
libaec                    1.0.6                hb7217d7_1    conda-forge
libarrow                  12.0.1           h88bd06b_2_cpu    conda-forge
libavif                   0.11.1               h9f83d30_2    conda-forge
libblas                   3.9.0           17_osxarm64_openblas    conda-forge
libbrotlicommon           1.0.9                h1a8c8d9_9    conda-forge
libbrotlidec              1.0.9                h1a8c8d9_9    conda-forge
libbrotlienc              1.0.9                h1a8c8d9_9    conda-forge
libcblas                  3.9.0           17_osxarm64_openblas    conda-forge
libclang                  15.0.7          default_h5dc8d65_2    conda-forge
libclang13                15.0.7          default_hc7183e1_2    conda-forge
libcrc32c                 1.1.2                hbdafb3b_0    conda-forge
libcurl                   8.1.2                h912dcd9_0    conda-forge
libcxx                    16.0.6               h4653b0c_0    conda-forge
libdeflate                1.18                 h1a8c8d9_0    conda-forge
libedit                   3.1.20191231         hc8eb9b7_2    conda-forge
libev                     4.33                 h642e427_1    conda-forge
libevent                  2.1.12               h2757513_1    conda-forge
libexpat                  2.5.0                hb7217d7_1    conda-forge
libffi                    3.4.4                hca03da5_0  
libgfortran               5.0.0           12_2_0_hd922786_31    conda-forge
libgfortran5              12.2.0              h0eea778_31    conda-forge
libglib                   2.76.3               h24e9cb9_0    conda-forge
libgoogle-cloud           2.12.0               h05652e3_1    conda-forge
libgrpc                   1.56.0               h9075ed4_2    conda-forge
libiconv                  1.17                 he4db4b2_0    conda-forge
libjpeg-turbo             2.1.5.1              h1a8c8d9_0    conda-forge
liblapack                 3.9.0           17_osxarm64_openblas    conda-forge
libllvm15                 15.0.7               h504e6bf_2    conda-forge
libnghttp2                1.52.0               hae82a92_0    conda-forge
libogg                    1.3.4                h27ca646_1    conda-forge
libopenblas               0.3.23          openmp_hc731615_0    conda-forge
libopus                   1.3.1                h27ca646_1    conda-forge
libpng                    1.6.39               h76d750c_0    conda-forge
libpq                     15.3                 h7126958_1    conda-forge
libprotobuf               4.23.3               hf32f9b9_0    conda-forge
libsodium                 1.0.18               h27ca646_1    conda-forge
libsqlite                 3.42.0               hb31c410_0    conda-forge
libssh2                   1.11.0               h7a5bd25_0    conda-forge
libthrift                 0.18.1               ha061701_2    conda-forge
libtiff                   4.5.1                h23a1a89_0    conda-forge
libutf8proc               2.8.0                h1a8c8d9_0    conda-forge
libvorbis                 1.3.7                h9f76cd9_0    conda-forge
libwebp-base              1.3.1                hb547adb_0    conda-forge
libxcb                    1.15                 hf346824_0    conda-forge
libxml2                   2.11.4               he3bdae6_0    conda-forge
libzlib                   1.2.13               h53f4e23_5    conda-forge
libzopfli                 1.0.3                h9f76cd9_0    conda-forge
llvm-openmp               16.0.6               h1c12783_0    conda-forge
locket                    1.0.0              pyhd8ed1ab_0    conda-forge
lz4                       4.3.2           py310ha6df754_0    conda-forge
lz4-c                     1.9.4                hb7217d7_0    conda-forge
magicgui                  0.7.2              pyhd8ed1ab_0    conda-forge
markdown-it-py            3.0.0              pyhd8ed1ab_0    conda-forge
markupsafe                2.1.3           py310h2aa6e3c_0    conda-forge
matplotlib-inline         0.1.6              pyhd8ed1ab_0    conda-forge
mdurl                     0.1.0              pyhd8ed1ab_0    conda-forge
msgpack-python            1.0.5           py310h2887b22_0    conda-forge
mypy_extensions           1.0.0              pyha770c72_0    conda-forge
mysql-common              8.0.33               h7b5afe1_1    conda-forge
mysql-libs                8.0.33               hb292caa_1    conda-forge
napari                    0.4.17          pyh275ddea_0_pyqt    conda-forge
napari-console            0.0.8              pyhd8ed1ab_0    conda-forge
napari-plugin-engine      0.2.0              pyhd8ed1ab_2    conda-forge
napari-svg                0.1.10             pyhd8ed1ab_0    conda-forge
ncurses                   6.4                  h313beb8_0  
nest-asyncio              1.5.6              pyhd8ed1ab_0    conda-forge
networkx                  3.1                pyhd8ed1ab_0    conda-forge
npe2                      0.6.2              pyhd8ed1ab_0    conda-forge
nspr                      4.35                 hb7217d7_0    conda-forge
nss                       3.89                 h789eff7_0    conda-forge
numcodecs                 0.11.0          py310h0f1eb42_1    conda-forge
numpy                     1.25.0          py310haa1e00c_0    conda-forge
numpydoc                  1.5.0              pyhd8ed1ab_0    conda-forge
openjpeg                  2.5.0                hbc2ba62_2    conda-forge
openssl                   3.1.1                h53f4e23_1    conda-forge
orc                       1.9.0                h858f345_1    conda-forge
packaging                 23.1               pyhd8ed1ab_0    conda-forge
pandas                    2.0.3           py310h1cdf563_0    conda-forge
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
partd                     1.4.0              pyhd8ed1ab_0    conda-forge
pcre2                     10.40                hb34f9b4_0    conda-forge
pexpect                   4.8.0              pyh1a96a4e_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    10.0.0          py310h60ecbdf_0    conda-forge
pint                      0.22               pyhd8ed1ab_1    conda-forge
pip                       23.1.2          py310hca03da5_0  
pkgutil-resolve-name      1.3.10             pyhd8ed1ab_0    conda-forge
platformdirs              3.8.0              pyhd8ed1ab_0    conda-forge
ply                       3.11                       py_1    conda-forge
pooch                     1.7.0              pyha770c72_3    conda-forge
prompt-toolkit            3.0.38             pyha770c72_0    conda-forge
prompt_toolkit            3.0.38               hd8ed1ab_0    conda-forge
psutil                    5.9.5           py310h8e9501a_0    conda-forge
psygnal                   0.9.0              pyhd8ed1ab_0    conda-forge
pthread-stubs             0.4               h27ca646_1001    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
pyarrow                   12.0.1          py310hfbab16f_2_cpu    conda-forge
pydantic                  2.0             py310h2aa6e3c_0    conda-forge
pydantic-core             2.0.1           py310had9acf8_0    conda-forge
pygments                  2.15.1             pyhd8ed1ab_0    conda-forge
pyopengl                  3.1.6              pyhd8ed1ab_1    conda-forge
pyproject_hooks           1.0.0              pyhd8ed1ab_0    conda-forge
pyqt                      5.15.7          py310h7aaa74b_3    conda-forge
pyqt5-sip                 12.11.0         py310h0f1eb42_3    conda-forge
pyrsistent                0.19.3          py310h8e9501a_0    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
python                    3.10.12         h01493a6_0_cpython    conda-forge
python-build              0.10.0             pyhd8ed1ab_1    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-tzdata             2023.3             pyhd8ed1ab_0    conda-forge
python_abi                3.10                    3_cp310    conda-forge
pytomlpp                  1.0.13          py310h2887b22_0    conda-forge
pytz                      2023.3             pyhd8ed1ab_0    conda-forge
pywavelets                1.4.1           py310hf1a086a_0    conda-forge
pyyaml                    6.0             py310h8e9501a_5    conda-forge
pyzmq                     25.1.0          py310h30b7201_0    conda-forge
qt-main                   5.15.8              hcac2fde_14    conda-forge
qtconsole-base            5.4.3              pyha770c72_0    conda-forge
qtpy                      2.3.1              pyhd8ed1ab_0    conda-forge
re2                       2023.03.02           hc5e2d97_0    conda-forge
readline                  8.2                  h1a28f6b_0  
requests                  2.31.0             pyhd8ed1ab_0    conda-forge
rich                      13.4.2             pyhd8ed1ab_0    conda-forge
scikit-image              0.20.0          py310h2b830bf_1    conda-forge
scipy                     1.11.1          py310h0975f3d_0    conda-forge
setuptools                67.8.0          py310hca03da5_0  
shellingham               1.5.1              pyhd8ed1ab_0    conda-forge
sip                       6.7.9           py310h1253130_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
snappy                    1.1.10               h17c5cce_0    conda-forge
snowballstemmer           2.2.0              pyhd8ed1ab_0    conda-forge
sortedcontainers          2.4.0              pyhd8ed1ab_0    conda-forge
sphinx                    4.5.0              pyh6c4a22f_0    conda-forge
sphinxcontrib-applehelp   1.0.4              pyhd8ed1ab_0    conda-forge
sphinxcontrib-devhelp     1.0.2                      py_0    conda-forge
sphinxcontrib-htmlhelp    2.0.1              pyhd8ed1ab_0    conda-forge
sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
sphinxcontrib-qthelp      1.0.3                      py_0    conda-forge
sphinxcontrib-serializinghtml 1.1.5              pyhd8ed1ab_2    conda-forge
sqlite                    3.41.2               h80987f9_0  
stack_data                0.6.2              pyhd8ed1ab_0    conda-forge
superqt                   0.4.1              pyhd8ed1ab_0    conda-forge
tblib                     1.7.0              pyhd8ed1ab_0    conda-forge
tifffile                  2023.4.12          pyhd8ed1ab_0    conda-forge
tk                        8.6.12               hb8d0fd4_0  
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
toolz                     0.12.0             pyhd8ed1ab_0    conda-forge
tornado                   6.3.2           py310h2aa6e3c_0    conda-forge
tqdm                      4.65.0             pyhd8ed1ab_1    conda-forge
traitlets                 5.9.0              pyhd8ed1ab_0    conda-forge
typer                     0.9.0              pyhd8ed1ab_0    conda-forge
typing-extensions         4.7.1                hd8ed1ab_0    conda-forge
typing_extensions         4.7.1              pyha770c72_0    conda-forge
tzdata                    2023c                h04d1e81_0  
urllib3                   2.0.3              pyhd8ed1ab_1    conda-forge
vispy                     0.11.0          py310hb614ae6_1    conda-forge
wcwidth                   0.2.6              pyhd8ed1ab_0    conda-forge
wheel                     0.38.4          py310hca03da5_0  
wrapt                     1.15.0          py310h8e9501a_0    conda-forge
xorg-libxau               1.0.11               hb547adb_0    conda-forge
xorg-libxdmcp             1.1.3                h27ca646_0    conda-forge
xyzservices               2023.5.0           pyhd8ed1ab_1    conda-forge
xz                        5.4.2                h80987f9_0  
yaml                      0.2.5                h3422bc3_2    conda-forge
zarr                      2.15.0             pyhd8ed1ab_0    conda-forge
zeromq                    4.3.4                hbdafb3b_1    conda-forge
zfp                       1.0.0                hb6e4faa_3    conda-forge
zict                      3.0.0              pyhd8ed1ab_0    conda-forge
zipp                      3.15.0             pyhd8ed1ab_0    conda-forge
zlib                      1.2.13               h53f4e23_5    conda-forge
zlib-ng                   2.0.7                h1a8c8d9_0    conda-forge
zstd                      1.5.2                hf913c23_6    conda-forge
```

**Comment by psobolewskiPhD** [comment]
Thanks for reporting--we're aware of this issue with pydantic v2. I think if you downgrade to 1.10.10 everything should work. We should have the feedstock patched soon.

**Comment by jni** [comment]
This has been fixed by @jaimergp in conda-forge/conda-forge-repodata-patches-feedstock#477! 🥳

**Comment by LucaMarconato** [comment]
@jni amazing! Is the fix already available via conda/do you know when it will be available to install via conda?

**Comment by jni** [comment]
Yes it's available, try it out!

**Comment by LucaMarconato** [comment]
I confirm that it works now!
