### ISSUE TITLE
Napari Viewer PySide6 Backend AttributeError

### ISSUE THREAD

**Issue by ovalerio** [napari/napari#6067]
## 🐛 Bug

Dear **napari team**,

I would like to use the `napari-deeplabcut` plugin to annotate images.  I get the error:
`AttributeError: 'PySide6.QtGui.QSurfaceFormat' object has no attribute 'DoubleBuffer'`
when I open the config.yaml file.

## To Reproduce

1. Installed napari
2. Installed deeplabcut-napari
3. Installed PySide6

```
Starting GUI...
Traceback (most recent call last):
  File "/lib/python3.8/site-packages/deeplabcut/gui/tabs/label_frames.py", line 55, in label_frames
    _ = launch_napari(folder)
  File "/lib/python3.8/site-packages/deeplabcut/gui/widgets.py", line 38, in launch_napari
    viewer = napari.Viewer()
  File "/lib/python3.8/site-packages/napari/viewer.py", line 67, in __init__
    self._window = Window(self, show=show)
  File "/lib/python3.8/site-packages/napari/_qt/qt_main_window.py", line 463, in __init__
    self._qt_window = _QtMainWindow(viewer)
  File "/lib/python3.8/site-packages/napari/_qt/qt_main_window.py", line 88, in __init__
    self._qt_viewer = QtViewer(viewer, show_welcome_screen=True)
  File "/lib/python3.8/site-packages/napari/_qt/qt_viewer.py", line 217, in __init__
    self._create_canvas()
  File "/lib/python3.8/site-packages/napari/_qt/qt_viewer.py", line 401, in _create_canvas
    self.canvas = VispyCanvas(
  File "/lib/python3.8/site-packages/napari/_vispy/canvas.py", line 33, in __init__
    super().__init__(*args, **kwargs)
  File "/lib/python3.8/site-packages/vispy/scene/canvas.py", line 135, in __init__
    super(SceneCanvas, self).__init__(
  File "/lib/python3.8/site-packages/vispy/app/canvas.py", line 211, in __init__
    self.create_native()
  File "/lib/python3.8/site-packages/vispy/app/canvas.py", line 228, in create_native
    self._app.backend_module.CanvasBackend(self, **self._backend_kwargs)
  File "/lib/python3.8/site-packages/vispy/app/backends/_qt.py", line 372, in __init__
    self._init_specific(p, kwargs)
  File "/lib/python3.8/site-packages/vispy/app/backends/_qt.py", line 791, in _init_specific
    glformat = _set_config(p.context.config)
  File "/lib/python3.8/site-packages/vispy/app/backends/_qt.py", line 283, in _set_config
    glformat.setSwapBehavior(glformat.DoubleBuffer if c['double_buffer']
AttributeError: 'PySide6.QtGui.QSurfaceFormat' object has no attribute 'DoubleBuffer'

```

## Environment
```
napari: 0.4.17
Platform: Linux-3.10.0-1160.el7.x86_64-x86_64-with-glibc2.10
Python: 3.8.17 | packaged by conda-forge | (default, Jun 16 2023, 07:06:00) [GCC 11.4.0]
Qt: 5.15.6
PyQt5: 5.15.7
NumPy: 1.24.4
SciPy: 1.10.1
Dask: 2023.5.0
VisPy: 0.11.0
magicgui: 0.7.2
superqt: unknown
in-n-out: 0.1.8
app-model: 0.1.4
npe2: 0.7.0

OpenGL:
- GL version: 
- MAX_TEXTURE_SIZE: ()

Screens:
- screen 1: resolution 1920x1080, scale 1.0
- screen 2: resolution 2560x1440, scale 1.0
- screen 3: resolution 2560x1440, scale 1.0
```
## Additional context

np

**Comment by Czaki** [comment]
napari 0.4.17 does not support PySide6, Please update napari to 0.4.18 and ensure that Pyside6 is bellow version 6.4.3

**Comment by psobolewskiPhD** [comment]
Also, it looks like you have two different QT backends installed, because your traceback has Pyside6 while your `--info` has pyqt5. Also if you need Qt6, you may want to move to python 3.10 because there are some QT6 limitations in the older versions.
