### ISSUE TITLE
TypeError when drawing lasso polygons in napari Shapes layer

### ISSUE THREAD

**Issue by GenevieveBuckley** [napari/napari#6260]
## 🐛 Bug

`TypeError: argument of type 'numpy.int64' is not iterable` happens when drawing lasso polygons on the napari Shapes layer.

## To Reproduce

1. Launch napari (using the main development branch)
    ```python
    import napari
    viewer = napari.Viewer()
    viewer.open_sample('napari', 'camera')
    ```
2. Click to open a new Shapes layer
3. Click the lasso polygon shapes tool, and draw several polygons until you see an error. (I can't figure out exactly what is triggering the error for some polygons but not others, but it's consistently popping up within about three or four polygons for me)
<details>
<summary>Full error message (click to expand)</summary>

```python-traceback
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
Cell In[2], line 1
----> 1 viewer = napari.Viewer()

NameError: name 'napari' is not defined

In [3]: import napari

In [4]: viewer = napari.Viewer()
Installed qt5 event loop hook.

In [5]: viewer.open_sample('napari', 'camera')
Out[5]: [<Image layer 'camera' at 0x11b184670>]

Traceback (most recent call last):
  File "/Users/genevieb/mambaforge/envs/napari-dev/lib/python3.10/site-packages/vispy/app/backends/_qt.py", line 496, in mousePressEvent
    self._vispy_mouse_press(
  File "/Users/genevieb/mambaforge/envs/napari-dev/lib/python3.10/site-packages/vispy/app/base.py", line 184, in _vispy_mouse_press
    ev = self._vispy_canvas.events.mouse_press(**kwargs)
  File "/Users/genevieb/mambaforge/envs/napari-dev/lib/python3.10/site-packages/vispy/util/event.py", line 453, in __call__
    self._invoke_callback(cb, event)
  File "/Users/genevieb/mambaforge/envs/napari-dev/lib/python3.10/site-packages/vispy/util/event.py", line 471, in _invoke_callback
    _handle_exception(self.ignore_callback_errors,
  File "/Users/genevieb/mambaforge/envs/napari-dev/lib/python3.10/site-packages/vispy/util/event.py", line 469, in _invoke_callback
    cb(event)
  File "/Users/genevieb/Documents/GitHub/napari/napari/_vispy/canvas.py", line 457, in _on_mouse_press
    self._process_mouse_event(mouse_press_callbacks, event)
  File "/Users/genevieb/Documents/GitHub/napari/napari/_vispy/canvas.py", line 404, in _process_mouse_event
    mouse_callbacks(layer, event)
  File "/Users/genevieb/Documents/GitHub/napari/napari/utils/interactions.py", line 130, in mouse_press_callbacks
    next(gen)
  File "/Users/genevieb/Documents/GitHub/napari/napari/layers/shapes/_shapes_mouse_bindings.py", line 336, in add_path_polygon_lasso
    initiate_polygon_draw(layer, coordinates)
  File "/Users/genevieb/Documents/GitHub/napari/napari/layers/shapes/_shapes_mouse_bindings.py", line 308, in initiate_polygon_draw
    layer.add(data, shape_type='path', gui=True)
  File "/Users/genevieb/Documents/GitHub/napari/napari/layers/shapes/shapes.py", line 2022, in add
    self._add_shapes(
  File "/Users/genevieb/Documents/GitHub/napari/napari/layers/shapes/shapes.py", line 2252, in _add_shapes
    self._update_dims()
  File "/Users/genevieb/Documents/GitHub/napari/napari/layers/base/base.py", line 778, in _update_dims
    self._clear_extents_and_refresh()
  File "/Users/genevieb/Documents/GitHub/napari/napari/layers/base/base.py", line 905, in _clear_extents_and_refresh
    self.refresh()
  File "/Users/genevieb/Documents/GitHub/napari/napari/layers/base/base.py", line 1368, in refresh
    self._refresh_sync()
  File "/Users/genevieb/Documents/GitHub/napari/napari/layers/base/base.py", line 1376, in _refresh_sync
    self._set_highlight(force=True)
  File "/Users/genevieb/Documents/GitHub/napari/napari/layers/shapes/shapes.py", line 2541, in _set_highlight
    self.events.highlight()
  File "/Users/genevieb/Documents/GitHub/napari/napari/utils/events/event.py", line 763, in __call__
    self._invoke_callback(cb, event if pass_event else None)
  File "/Users/genevieb/Documents/GitHub/napari/napari/utils/events/event.py", line 801, in _invoke_callback
    _handle_exception(
  File "/Users/genevieb/Documents/GitHub/napari/napari/utils/events/event.py", line 790, in _invoke_callback
    cb()
  File "/Users/genevieb/Documents/GitHub/napari/napari/_vispy/layers/shapes.py", line 65, in _on_highlight_change
    vertices, faces = self.layer._outline_shapes()
  File "/Users/genevieb/Documents/GitHub/napari/napari/layers/shapes/shapes.py", line 2420, in _outline_shapes
    centers, offsets, triangles = self._data_view.outline(index)
  File "/Users/genevieb/Documents/GitHub/napari/napari/layers/shapes/_shape_list.py", line 965, in outline
    triangle_indices = [
  File "/Users/genevieb/Documents/GitHub/napari/napari/layers/shapes/_shape_list.py", line 968, in <listcomp>
    if x[0] in indices and x[1] == 1
TypeError: argument of type 'numpy.int64' is not iterable

If you suspect this is an IPython 8.14.0 bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

Traceback (most recent call last):
  File "/Users/genevieb/mambaforge/envs/napari-dev/lib/python3.10/site-packages/vispy/app/backends/_qt.py", line 928, in paintGL
    self._vispy_canvas.events.draw(region=None)
  File "/Users/genevieb/mambaforge/envs/napari-dev/lib/python3.10/site-packages/vispy/util/event.py", line 453, in __call__
    self._invoke_callback(cb, event)
  File "/Users/genevieb/mambaforge/envs/napari-dev/lib/python3.10/site-packages/vispy/util/event.py", line 471, in _invoke_callback
    _handle_exception(self.ignore_callback_errors,
  File "/Users/genevieb/mambaforge/envs/napari-dev/lib/python3.10/site-packages/vispy/util/event.py", line 469, in _invoke_callback
    cb(event)
  File "/Users/genevieb/Documents/GitHub/napari/napari/_vispy/canvas.py", line 529, in on_draw
    layer._update_draw(
  File "/Users/genevieb/Documents/GitHub/napari/napari/layers/shapes/shapes.py", line 2733, in _update_draw
    self._set_highlight(force=True)
  File "/Users/genevieb/Documents/GitHub/napari/napari/layers/shapes/shapes.py", line 2541, in _set_highlight
    self.events.highlight()
  File "/Users/genevieb/Documents/GitHub/napari/napari/utils/events/event.py", line 763, in __call__
    self._invoke_callback(cb, event if pass_event else None)
  File "/Users/genevieb/Documents/GitHub/napari/napari/utils/events/event.py", line 801, in _invoke_callback
    _handle_exception(
  File "/Users/genevieb/Documents/GitHub/napari/napari/utils/events/event.py", line 790, in _invoke_callback
    cb()
  File "/Users/genevieb/Documents/GitHub/napari/napari/_vispy/layers/shapes.py", line 65, in _on_highlight_change
    vertices, faces = self.layer._outline_shapes()
  File "/Users/genevieb/Documents/GitHub/napari/napari/layers/shapes/shapes.py", line 2420, in _outline_shapes
    centers, offsets, triangles = self._data_view.outline(index)
  File "/Users/genevieb/Documents/GitHub/napari/napari/layers/shapes/_shape_list.py", line 965, in outline
    triangle_indices = [
  File "/Users/genevieb/Documents/GitHub/napari/napari/layers/shapes/_shape_list.py", line 968, in <listcomp>
    if x[0] in indices and x[1] == 1
TypeError: argument of type 'numpy.int64' is not iterable

If you suspect this is an IPython 8.14.0 bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

Traceback (most recent call last):
  File "/Users/genevieb/mambaforge/envs/napari-dev/lib/python3.10/site-packages/vispy/app/backends/_qt.py", line 928, in paintGL
    self._vispy_canvas.events.draw(region=None)
  File "/Users/genevieb/mambaforge/envs/napari-dev/lib/python3.10/site-packages/vispy/util/event.py", line 453, in __call__
    self._invoke_callback(cb, event)
  File "/Users/genevieb/mambaforge/envs/napari-dev/lib/python3.10/site-packages/vispy/util/event.py", line 471, in _invoke_callback
    _handle_exception(self.ignore_callback_errors,
  File "/Users/genevieb/mambaforge/envs/napari-dev/lib/python3.10/site-packages/vispy/util/event.py", line 469, in _invoke_callback
    cb(event)
  File "/Users/genevieb/Documents/GitHub/napari/napari/_vispy/canvas.py", line 529, in on_draw
    layer._update_draw(
  File "/Users/genevieb/Documents/GitHub/napari/napari/layers/shapes/shapes.py", line 2733, in _update_draw
    self._set_highlight(force=True)
  File "/Users/genevieb/Documents/GitHub/napari/napari/layers/shapes/shapes.py", line 2541, in _set_highlight
    self.events.highlight()
  File "/Users/genevieb/Documents/GitHub/napari/napari/utils/events/event.py", line 763, in __call__
    self._invoke_callback(cb, event if pass_event else None)
  File "/Users/genevieb/Documents/GitHub/napari/napari/utils/events/event.py", line 801, in _invoke_callback
    _handle_exception(
  File "/Users/genevieb/Documents/GitHub/napari/napari/utils/events/event.py", line 790, in _invoke_callback
    cb()
  File "/Users/genevieb/Documents/GitHub/napari/napari/_vispy/layers/shapes.py", line 65, in _on_highlight_change
    vertices, faces = self.layer._outline_shapes()
  File "/Users/genevieb/Documents/GitHub/napari/napari/layers/shapes/shapes.py", line 2420, in _outline_shapes
    centers, offsets, triangles = self._data_view.outline(index)
  File "/Users/genevieb/Documents/GitHub/napari/napari/layers/shapes/_shape_list.py", line 965, in outline
    triangle_indices = [
  File "/Users/genevieb/Documents/GitHub/napari/napari/layers/shapes/_shape_list.py", line 968, in <listcomp>
    if x[0] in indices and x[1] == 1
TypeError: argument of type 'numpy.int64' is not iterable

If you suspect this is an IPython 8.14.0 bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

In [6]: %tb
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
File ~/mambaforge/envs/napari-dev/lib/python3.10/site-packages/vispy/util/event.py:453, in EventEmitter.__call__(self, *args, **kwargs)
    450 if self._emitting > 1:
    451     raise RuntimeError('EventEmitter loop detected!')
--> 453 self._invoke_callback(cb, event)
    454 if event.blocked:
    455     break

File ~/mambaforge/envs/napari-dev/lib/python3.10/site-packages/vispy/util/event.py:471, in EventEmitter._invoke_callback(self, cb, event)
    469     cb(event)
    470 except Exception:
--> 471     _handle_exception(self.ignore_callback_errors,
    472                       self.print_callback_errors,
    473                       self, cb_event=(cb, event))

File ~/mambaforge/envs/napari-dev/lib/python3.10/site-packages/vispy/util/event.py:469, in EventEmitter._invoke_callback(self, cb, event)
    467 def _invoke_callback(self, cb, event):
    468     try:
--> 469         cb(event)
    470     except Exception:
    471         _handle_exception(self.ignore_callback_errors,
    472                           self.print_callback_errors,
    473                           self, cb_event=(cb, event))

File ~/Documents/GitHub/napari/napari/_vispy/canvas.py:529, in VispyCanvas.on_draw(self, event)
    527 else:
    528     displayed_axes = list(self.viewer.dims.displayed[-nd:])
--> 529 layer._update_draw(
    530     scale_factor=1 / self.viewer.camera.zoom,
    531     corner_pixels_displayed=canvas_corners_world[
    532         :, displayed_axes
    533     ],
    534     shape_threshold=self._scene_canvas.size,
    535 )

File ~/Documents/GitHub/napari/napari/layers/shapes/shapes.py:2733, in Shapes._update_draw(self, scale_factor, corner_pixels_displayed, shape_threshold)
   2727 def _update_draw(
   2728     self, scale_factor, corner_pixels_displayed, shape_threshold
   2729 ):
   2730     super()._update_draw(
   2731         scale_factor, corner_pixels_displayed, shape_threshold
   2732     )
-> 2733     self._set_highlight(force=True)

File ~/Documents/GitHub/napari/napari/layers/shapes/shapes.py:2541, in Shapes._set_highlight(self, force)
   2539 self._value_stored = copy(self._value)
   2540 self._drag_box_stored = copy(self._drag_box)
-> 2541 self.events.highlight()

File ~/Documents/GitHub/napari/napari/utils/events/event.py:763, in EventEmitter.__call__(self, *args, **kwargs)
    760     self._block_counter.update([cb])
    761     continue
--> 763 self._invoke_callback(cb, event if pass_event else None)
    764 if event.blocked:
    765     break

File ~/Documents/GitHub/napari/napari/utils/events/event.py:801, in EventEmitter._invoke_callback(self, cb, event)
    799     self.disconnect(cb)
    800     return
--> 801 _handle_exception(
    802     self.ignore_callback_errors,
    803     self.print_callback_errors,
    804     self,
    805     cb_event=(cb, event),
    806 )

File ~/Documents/GitHub/napari/napari/utils/events/event.py:790, in EventEmitter._invoke_callback(self, cb, event)
    788         cb(event)
    789     else:
--> 790         cb()
    791 except Exception as e:  # noqa: BLE001
    792     # dead Qt object with living python pointer. not importing Qt
    793     # here... but this error is consistent across backends
    794     if (
    795         isinstance(e, RuntimeError)
    796         and 'C++' in str(e)
    797         and str(e).endswith(('has been deleted', 'already deleted.'))
    798     ):

File ~/Documents/GitHub/napari/napari/_vispy/layers/shapes.py:65, in VispyShapesLayer._on_highlight_change(self)
     62 self.layer._highlight_width = settings.appearance.highlight_thickness
     64 # Compute the vertices and faces of any shape outlines
---> 65 vertices, faces = self.layer._outline_shapes()
     67 if vertices is None or len(vertices) == 0 or len(faces) == 0:
     68     vertices = np.zeros((3, self.layer._slice_input.ndisplay))

File ~/Documents/GitHub/napari/napari/layers/shapes/shapes.py:2420, in Shapes._outline_shapes(self)
   2417 else:
   2418     index = self._value[0]
-> 2420 centers, offsets, triangles = self._data_view.outline(index)
   2421 vertices = centers + (
   2422     self._normalized_scale_factor * self._highlight_width * offsets
   2423 )
   2424 vertices = vertices[:, ::-1]

File ~/Documents/GitHub/napari/napari/layers/shapes/_shape_list.py:965, in ShapeList.outline(self, indices)
    963 else:
    964     meshes = self._mesh.triangles_index
--> 965     triangle_indices = [
    966         i
    967         for i, x in enumerate(meshes)
    968         if x[0] in indices and x[1] == 1
    969     ]
    970     meshes = self._mesh.vertices_index
    971     vertices_indices = [
    972         i
    973         for i, x in enumerate(meshes)
    974         if x[0] in indices and x[1] == 1
    975     ]

File ~/Documents/GitHub/napari/napari/layers/shapes/_shape_list.py:968, in <listcomp>(.0)
    963 else:
    964     meshes = self._mesh.triangles_index
    965     triangle_indices = [
    966         i
    967         for i, x in enumerate(meshes)
--> 968         if x[0] in indices and x[1] == 1
    969     ]
    970     meshes = self._mesh.vertices_index
    971     vertices_indices = [
    972         i
    973         for i, x in enumerate(meshes)
    974         if x[0] in indices and x[1] == 1
    975     ]

TypeError: argument of type 'numpy.int64' is not iterable
```

</details>

## Expected behavior

I expected the error not to occur, and to be able to continue drawing shapes.

## Environment

napari: 0.5.0a2.dev243+g4e08272e
Platform: macOS-13.5.2-arm64-arm-64bit
System: MacOS 13.5.2
Python: 3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:41:52) [Clang 15.0.7 ]
Qt: 5.15.6
PyQt5: 5.15.7
NumPy: 1.23.5
SciPy: 1.11.1
Dask: 2023.7.0
VisPy: 0.13.0
magicgui: 0.7.2
superqt: 0.5.4
in-n-out: 0.1.8
app-model: 0.1.4
npe2: 0.7.0

OpenGL:
- GL version: 2.1 Metal - 83.1
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1440x900, scale 2.0
- screen 2: resolution 1920x1080, scale 1.0

Settings path:
- /Users/genevieb/Library/Application Support/napari/napari-dev_8a798ce8db3962d716d33109f1c23fa2f783f2dd/settings.yaml

## Additional context

I am sometimes noticing the napari canvas turn black when the error happens (or turn black until you click back on the napari viewer/canvas, and then the canvas view restores itself (but you still can't interact properly with it due to the error).

**Comment by dalthviz** [comment]
Hi, I think this is a duplicate of https://github.com/napari/napari/issues/6212, if that is the case then maybe the fix being worked on at https://github.com/napari/napari/pull/6215 could help :)

**Comment by GenevieveBuckley** [comment]
Yes, I think this is a duplicate of https://github.com/napari/napari/issues/6212, thanks for linking it
