### ISSUE TITLE
Error when using asynchronous image rendering with linked layers

### ISSUE THREAD

**Issue by m-albert** [napari/napari#6372]
### 🐛 Bug Report

When using asynchronous image rendering with linked layers, I get the error shown below.

I only get the error when not explicitly specifying which attributes to share between layers in `link_layers`. Therefore I suspect that the problem comes from the attribute `loaded` (used during async image rendering) being shared between layers, although it shouldn't.

### 💡 Steps to Reproduce

1. Activate experimental option "Render Images Asynchronously".
2. 
```python
import dask.array as da
import napari
from napari.experimental import link_layers

viewer = napari.Viewer()

layers = [viewer.add_image([da.random.randint(0, 100, (3,3))], multiscale=True)
      for _ in range(2)]

link_layers(layers)
```
3. Zoom in and out

Error:
```
Traceback (most recent call last):
  File "/Users/malbert/mambaforge/envs/napari_test/lib/python3.10/site-packages/napari/_qt/experimental/qt_chunk_receiver.py", line 61, in _slot
    self.events.gui_event(original_event=event)
  File "/Users/malbert/mambaforge/envs/napari_test/lib/python3.10/site-packages/napari/utils/events/event.py", line 768, in __call__
    self._invoke_callback(cb, event if pass_event else None)
  File "/Users/malbert/mambaforge/envs/napari_test/lib/python3.10/site-packages/napari/utils/events/event.py", line 806, in _invoke_callback
    _handle_exception(
  File "/Users/malbert/mambaforge/envs/napari_test/lib/python3.10/site-packages/napari/utils/events/event.py", line 793, in _invoke_callback
    cb(event)
  File "/Users/malbert/mambaforge/envs/napari_test/lib/python3.10/site-packages/napari/_qt/experimental/qt_chunk_receiver.py", line 123, in _on_chunk_loaded_gui
    layer.on_chunk_loaded(request)  # Pass the chunk to its layer.
  File "/Users/malbert/mambaforge/envs/napari_test/lib/python3.10/site-packages/napari/layers/image/image.py", line 1032, in on_chunk_loaded
    self._on_data_loaded(data, sync=False)
  File "/Users/malbert/mambaforge/envs/napari_test/lib/python3.10/site-packages/napari/layers/image/image.py", line 897, in _on_data_loaded
    self.events.loaded()
  File "/Users/malbert/mambaforge/envs/napari_test/lib/python3.10/site-packages/napari/utils/events/event.py", line 768, in __call__
    self._invoke_callback(cb, event if pass_event else None)
  File "/Users/malbert/mambaforge/envs/napari_test/lib/python3.10/site-packages/napari/utils/events/event.py", line 806, in _invoke_callback
    _handle_exception(
  File "/Users/malbert/mambaforge/envs/napari_test/lib/python3.10/site-packages/napari/utils/events/event.py", line 793, in _invoke_callback
    cb(event)
  File "/Users/malbert/mambaforge/envs/napari_test/lib/python3.10/site-packages/napari/layers/utils/_link_layers.py", line 124, in setter
    setattr(l2, attr, new_val)
AttributeError: can't set attribute 'loaded'
```

### 🌎 Environment

napari: 0.4.18
Platform: macOS-12.6-arm64-arm-64bit
System: MacOS 12.6
Python: 3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:41:52) [Clang 15.0.7 ]
Qt: 5.15.8
PyQt5: 5.15.9
NumPy: 1.26.0
SciPy: 1.11.3
Dask: 2023.10.0
VisPy: 0.12.2
magicgui: 0.8.0
superqt: 0.6.1
in-n-out: 0.1.9
app-model: 0.2.2
npe2: 0.7.2

OpenGL:
  - GL version:  2.1 Metal - 76.3
  - MAX_TEXTURE_SIZE: 16384

Screens:
  - screen 1: resolution 1440x900, scale 2.0
  - screen 2: resolution 1920x1080, scale 2.0
  - screen 3: resolution 1920x1080, scale 2.0

Settings path:
  - /Users/malbert/Library/Application Support/napari/napari_test_cedd16f321c09946af74e2bb09095696d358ee04/settings.yaml
Plugins:
  - napari: 0.4.18 (77 contributions)
  - napari-console: 0.0.8 (0 contributions)
  - napari-manual-transforms: 0.0.3 (2 contributions)
  - napari-svg: 0.1.10 (2 contributions)

**Comment by andy-sweet** [comment]
While I think this experimental async image rendering has unfortunately been broken and unmaintained for a while, it seems like this might be a [more general problem with linking layers](https://github.com/napari/napari/blob/10775732425017c84d881d52391070c987ed6209/napari/layers/utils/_link_layers.py#L120).

A derived property of a layer could also have an associated event, but is not settable, so should be skipped.

**Comment by m-albert** [comment]
@andy-sweet Thank you for fixing this and the hints towards functionality available on `main`!
