### ISSUE TITLE
Napari fails to start with both PySide2 5.13.2 and PySide6 6.6 on Python=3.11

### ISSUE THREAD

**Issue by Chris-N-K** [napari/napari#6381]
### 🐛 Bug Report

If installed into a new environment with `Python=3.11` and either `PySide2` or `PySide6` as GUI backend napari will raise an error upon startup.

### 💡 Steps to Reproduce

1. Make clean python 3.11 environment
2. Install a pyside backend
3. Install napari
4. Try to start from command line

### 💡 Expected Behavior

Normal startup, displaying the viewer.

### 🌎 Environment

**napari: 0.4.18 and higher**
Platform: Linux-5.14.0-1054-oem-x86_64-with-glibc2.35
System: Ubuntu 22.04.3 LTS
Python: 3.12.0 | packaged by conda-forge | (main, Oct 3 2023, 08:43:22) [GCC 12.3.0]
Qt: 5.15.2
**PySide2 and PySide6**
NumPy: 1.26.1
SciPy: 1.11.3
Dask: 2023.10.0
VisPy: 0.12.2
magicgui: 0.8.0
superqt: 0.6.1
in-n-out: 0.1.9
app-model: 0.2.2
npe2: 0.7.3

OpenGL:
- GL version: 4.6 (Compatibility Profile) Mesa 23.0.4-0ubuntu1~22.04.1
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1920x1080, scale 1.0

Settings path:
- /home/cnk/.config/napari/napari-rc_9639b478d5af653ad6ae00d86257bed4bc02b3fd/settings.yaml

### 💡 Additional Context

The different backends produce different error messages:
PySide2 -> memory access error
PySide6:
```
Traceback (most recent call last):
  File "/home/cnk/miniconda3/envs/napari-rc/bin/napari", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/cnk/miniconda3/envs/napari-rc/lib/python3.12/site-packages/napari/__main__.py", line 564, in main
    _run()
  File "/home/cnk/miniconda3/envs/napari-rc/lib/python3.12/site-packages/napari/__main__.py", line 326, in _run
    viewer = Viewer()
             ^^^^^^^^
  File "/home/cnk/miniconda3/envs/napari-rc/lib/python3.12/site-packages/napari/viewer.py", line 67, in __init__
    self._window = Window(self, show=show)
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cnk/miniconda3/envs/napari-rc/lib/python3.12/site-packages/napari/_qt/qt_main_window.py", line 577, in __init__
    self._qt_viewer.dockLayerList, tabify=False, menu=self.window_menu
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cnk/miniconda3/envs/napari-rc/lib/python3.12/site-packages/napari/_qt/qt_viewer.py", line 356, in dockLayerList
    layerListLayout.addWidget(self.layers)
                              ^^^^^^^^^^^
  File "/home/cnk/miniconda3/envs/napari-rc/lib/python3.12/site-packages/napari/_qt/qt_viewer.py", line 334, in layers
    self._layers = QtLayerList(self.viewer.layers)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cnk/miniconda3/envs/napari-rc/lib/python3.12/site-packages/napari/_qt/containers/qt_layer_list.py", line 46, in __init__
    super().__init__(root, parent)
  File "/home/cnk/miniconda3/envs/napari-rc/lib/python3.12/site-packages/napari/_qt/containers/qt_list_view.py", line 43, in __init__
    self.setRoot(root)
  File "/home/cnk/miniconda3/envs/napari-rc/lib/python3.12/site-packages/napari/_qt/containers/_base_item_view.py", line 87, in setRoot
    self.setModel(create_model(root, self))
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cnk/miniconda3/envs/napari-rc/lib/python3.12/site-packages/napari/_qt/containers/_factory.py", line 72, in create_model
    return QtLayerListModel(obj, parent=parent)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cnk/miniconda3/envs/napari-rc/lib/python3.12/site-packages/napari/_qt/containers/_base_item_model.py", line 80, in __init__
    super().__init__(parent=parent)
TypeError: object.__init__() takes exactly one argument (the instance to initialize)

```

**Comment by psobolewskiPhD** [comment]
Your env appears to be python 3.12 not 3.11. We don't yet support 3.12. Could you clarify that and edit the issue if needed?

Also can you give the pyside versions? Thanks !

**Comment by psobolewskiPhD** [comment]
Re: pyside6, your error is the same as this issue:
https://github.com/napari/napari/issues/5703
pyside6 support is still experimental, you can see the constraints we use on our tests:
https://github.com/napari/napari/blob/ae384aec33a50a1abebf1e081a055cf3aec34d3f/resources/constraints/version_denylist.txt#L2-L3

Can you try 6.4.2? 
On my mac that works with python 3.11, but has the flashing issue: https://github.com/napari/napari/issues/5644

**Comment by Chris-N-K** [comment]
>Your env appears to be python 3.12 not 3.11. We don't yet support 3.12. Could you clarify that and edit the issue if needed?
>On my mac, pyside2 and python3.11 everything seems to work with 0.4.18 using:
>mamba create -n napari-pyside2 python=3.11 napari pyside2
>Also can you give the pyside versions? Thanks !

Hi, sorry ssems like my pinned python version got messed up.

But even with 3.11 and PySide2==PySide2-5.13.2 napari fails upon start-up.
Now with a different error:
```
TypeError: 'PySide2.QtCore.Qt.WindowType' object cannot be interpreted as an integer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/cnk/miniconda3/envs/napari-rc/bin/napari", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/cnk/miniconda3/envs/napari-rc/lib/python3.11/site-packages/napari/__main__.py", line 564, in main
    _run()
  File "/home/cnk/miniconda3/envs/napari-rc/lib/python3.11/site-packages/napari/__main__.py", line 213, in _run
    from napari import Viewer, run
  File "<frozen importlib._bootstrap>", line 1229, in _handle_fromlist
  File "/home/cnk/miniconda3/envs/napari-rc/lib/python3.11/site-packages/napari/_lazy.py", line 45, in __getattr__
    submod = import_module(
             ^^^^^^^^^^^^^^
  File "/home/cnk/miniconda3/envs/napari-rc/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cnk/miniconda3/envs/napari-rc/lib/python3.11/site-packages/napari/_event_loop.py", line 2, in <module>
    from napari._qt.qt_event_loop import gui_qt, run
  File "/home/cnk/miniconda3/envs/napari-rc/lib/python3.11/site-packages/napari/_qt/__init__.py", line 52, in <module>
    from napari._qt.qt_event_loop import get_app, gui_qt, quit_app, run
  File "/home/cnk/miniconda3/envs/napari-rc/lib/python3.11/site-packages/napari/_qt/qt_event_loop.py", line 15, in <module>
    from napari._qt.dialogs.qt_notification import NapariQtNotification
  File "/home/cnk/miniconda3/envs/napari-rc/lib/python3.11/site-packages/napari/_qt/dialogs/qt_notification.py", line 26, in <module>
    from superqt import QElidingLabel, ensure_main_thread
  File "/home/cnk/miniconda3/envs/napari-rc/lib/python3.11/site-packages/superqt/__init__.py", line 11, in <module>
    from .combobox import QColorComboBox, QEnumComboBox, QSearchableComboBox
  File "/home/cnk/miniconda3/envs/napari-rc/lib/python3.11/site-packages/superqt/combobox/__init__.py", line 3, in <module>
    from ._color_combobox import QColorComboBox
  File "/home/cnk/miniconda3/envs/napari-rc/lib/python3.11/site-packages/superqt/combobox/_color_combobox.py", line 20, in <module>
    from superqt.utils import signals_blocked
  File "/home/cnk/miniconda3/envs/napari-rc/lib/python3.11/site-packages/superqt/utils/__init__.py", line 29, in <module>
    from ._errormsg_context import exceptions_as_dialog
  File "/home/cnk/miniconda3/envs/napari-rc/lib/python3.11/site-packages/superqt/utils/_errormsg_context.py", line 17, in <module>
    class exceptions_as_dialog(AbstractContextManager):
SystemError: <built-in method __prepare__ of type object at 0x56102f372e60> returned a result with an exception set

```

With PySide6==6.4.2 start-up works fine.

**Comment by psobolewskiPhD** [comment]
> But even with 3.11 and PySide2==PySide2-5.13.2 napari fails upon start-up.

That's a pretty old pyside2 it is actually our minimum req:
https://github.com/napari/napari/blob/ae384aec33a50a1abebf1e081a055cf3aec34d3f/setup.cfg#L95-L97
But we don't run min req CI testing on all python versions, just 3.8.

No arm64 wheels/binaries for that pyside2 so I can't do any easy testing locally.
Do you specifically need that pyside2? if so, try an older python and report back.
If not, try a recent 5.15.x pyside2 which should work with python 3.11.

**Comment by Czaki** [comment]
Because newer pyside2 releases directly specify compatibility up to Python 3.10. So `pip` will not bring them.

**Comment by psobolewskiPhD** [comment]
Ah so newer python gets old pyside2. 😬

**Comment by Czaki** [comment]
Should I add python 3.11 check to startup of napari to inform that it will not work with pyside2?

**Comment by psobolewskiPhD** [comment]
I don't think so? 
conda-forge is fine and pyside2 >5.15.11 is officially supported on python 3.11, they just haven't updated pypi wheels, see:
https://wiki.qt.io/Qt_for_Python
Also, we don't officially support python 3.11 yet anyways.

I think this issue is closable, the only question is whether pyside2 5.13.2 really functions with python 3.9/3.10 or whether we need to bump that min_req.

**Comment by Czaki** [comment]
We explicitly exclude python 3.11 PySide 2 tests:

https://github.com/napari/napari/blob/cf3ad37c8738b3a4894094f55fe35095779e34ad/.github/workflows/test_comprehensive.yml#L73-L75

So I think that we should bump min req to 5.14.2 for Python 3.11+. This will not block usage of PySide if they upload wheels, but should block current problems.

**Comment by psobolewskiPhD** [comment]
I meant that current min_req test run only uses pyqt, so doesn't test pyside2 minimum.

I get the bump to 5.14.2 sort of—to prevent the old wheels—but pyside doesn't consider that supported for 3.11, so maybe best to just go with 5.15.11? same effect and in theory supported if someone compiles?

**Comment by Czaki** [comment]
> I meant that current min_req test run only uses pyqt, so doesn't test pyside2 minimum.

I run the pyside2 min req test locally. It pass. However, we set 5.14.2 as min req for 3.8. So we may just bump pyside min req to 5.14.2

**Comment by psobolewskiPhD** [comment]
@Czaki Unless I'm missing something, pyside2 doesn't have *any* recent wheels on pypi:
https://pypi.org/project/PySide2/#history
shows last version as PySide2 5.15.2.1

So we may need to rethink support for pyside2 in general?

**Comment by Czaki** [comment]
Last upload on conda forge is 5 months old. https://anaconda.org/conda-forge/pyside2

**Comment by psobolewskiPhD** [comment]
Yeah, conda-forge appears up to date, but our tests use pip.

**Comment by willingc** [comment]
Closing this as resolved by clarifying supported versions.
