### ISSUE TITLE
Uninstalling napari breaks test discovery in VSCode (plugin manager related)

### ISSUE THREAD

**Issue by VolkerH** [napari/napari#6759]
### 🐛 Bug Report

If I have a virtual python environment in which I install napari with some plugins and then later on uninstall napari (in my case I used poetry to manage the environment), napari (more likely, one of the plugin-related dependencies) doesn't clean up properly after itself, breaking test discovery in the virtual environment.
 
I haven't looked at the exact details, but IIRC the napari plugin infrastructure uses some tools from the pytest plugin infrastructure and in this case seems to make some changes to a config file that don't get cleaned up properly.

Here is a slightly sanitized console log from runnning test discovery in VSCode (seems to just be regular pytest stuff):

```
2024-03-19 15:19:14.278 [info] > ~\AppData\Local\pypoetry\Cache\virtualenvs\some-venv-qFJqo2lY-py3.11\Scripts\python.exe -m pytest -p vscode_pytest --collect-only tests
2024-03-19 15:19:14.278 [info] cwd: .
2024-03-19 15:19:14.581 [error] C:\Users\some-user\AppData\Local\pypoetry\Cache\virtualenvs\some-venv-qFJqo2lY-py3.11\Lib\site-packages\_pytest\config\__init__.py:331: PluggyTeardownRaisedWarning: A plugin raised an exception during an old-style hookwrapper teardown.
Plugin: helpconfig, Hook: pytest_cmdline_parse
ModuleNotFoundError: No module named 'napari.utils._testsupport'
For more information see https://pluggy.readthedocs.io/en/stable/api_reference.html#pluggy.PluggyTeardownRaisedWarning
  config = pluginmanager.hook.pytest_cmdline_parse(
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\some-user\AppData\Local\pypoetry\Cache\virtualenvs\some-venv-qFJqo2lY-py3.11\Lib\site-packages\pytest\__main__.py", line 5, in <module>
    raise SystemExit(pytest.console_main())
                     ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\some-user\AppData\Local\pypoetry\Cache\virtualenvs\some-venv-qFJqo2lY-py3.11\Lib\site-packages\_pytest\config\__init__.py", line 192, in console_main

2024-03-19 15:19:14.581 [error]     code = main()
           ^^^^^^
  File "C:\Users\some-user\AppData\Local\pypoetry\Cache\virtualenvs\some-venv-qFJqo2lY-py3.11\Lib\site-packages\_pytest\config\__init__.py", line 150, in main
    config = _prepareconfig(args, plugins)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\some-user\AppData\Local\pypoetry\Cache\virtualenvs\some-venv-qFJqo2lY-py3.11\Lib\site-packages\_pytest\config\__init__.py", line 331, in _prepareconfig
    config = pluginmanager.hook.pytest_cmdline_parse(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\some-user\AppData\Local\pypoetry\Cache\virtualenvs\some-venv-qFJqo2lY-py3.11\Lib\site-packages\pluggy\_hooks.py", line 501, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-19 15:19:14.581 [error] ^^^
  File "C:\Users\some-user\AppData\Local\pypoetry\Cache\virtualenvs\some-venv-qFJqo2lY-py3.11\Lib\site-packages\pluggy\_manager.py", line 119, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\some-user\AppData\Local\pypoetry\Cache\virtualenvs\some-venv-qFJqo2lY-py3.11\Lib\site-packages\pluggy\_callers.py", line 155, in _multicall
    teardown[0].send(outcome)
  File "C:\Users\some-user\AppData\Local\pypoetry\Cache\virtualenvs\some-venv-qFJqo2lY-py3.11\Lib\site-packages\_pytest\helpconfig.py", line 104, in pytest_cmdline_parse
    config: Config = outcome.get_result()
         
2024-03-19 15:19:14.582 [error]             ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\some-user\AppData\Local\pypoetry\Cache\virtualenvs\some-venv-qFJqo2lY-py3.11\Lib\site-packages\pluggy\_result.py", line 99, in get_result

2024-03-19 15:19:14.582 [error]     raise exc.with_traceback(exc.__traceback__)
  File "C:\Users\some-user\AppData\Local\pypoetry\Cache\virtualenvs\some-venv-qFJqo2lY-py3.11\Lib\site-packages\pluggy\_callers.py", line 102, in _multicall
    res = hook_impl.function(*args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\some-user\AppData\Local\pypoetry\Cache\virtualenvs\some-venv-qFJqo2lY-py3.11\Lib\site-packages\_pytest\config\__init__.py", line 1075, in pytest_cmdline_parse

2024-03-19 15:19:14.582 [error]     self.parse(args)
  File "C:\Users\some-user\AppData\Local\pypoetry\Cache\virtualenvs\some-venv-qFJqo2lY-py3.11\Lib\site-packages\_pytest\config\__init__.py", line 1425, in parse
    self._preparse(args, addopts=addopts)
  File "C:\Users\some-user\AppData\Local\pypoetry\Cache\virtualenvs\some-venv-qFJqo2lY-py3.11\Lib\site-packages\_pytest\config\__init__.py", line 1305, in _preparse

2024-03-19 15:19:14.582 [error]     self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File "C:\Users\some-user\AppData\Local\pypoetry\Cache\virtualenvs\some-venv-qFJqo2lY-py3.11\Lib\site-packages\pluggy\_manager.py", line 414, in load_setuptools_entrypoints
    plugin = ep.load()
2024-03-19 15:19:14.582 [error] 
             ^^^^^^^^^
  File "C:\Users\some-user\AppData\Local\Programs\Python\Python311\Lib\importlib\metadata\__init__.py", line 198, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-19 15:19:14.583 [error] ^^^^^^^^^^^
  File "C:\Users\some-user\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1142, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'napari.utils._testsupport'

2024-03-19 15:19:14.607 [error] Subprocess exited unsuccessfully with exit code 1 and signal null on workspace c:\Users\some-user\Gitlab\some-venv.
2024-03-19 15:19:14.607 [error] Subprocess exited unsuccessfully with exit code 1 and signal null on workspace c:\Users\some-user\Gitlab\some-venv. Creating and sending error discovery payload
2024-03-19 15:19:14.607 [error] pytest test discovery error for workspace:  c:\Users\some-user\Gitlab\some-venv 
  
 The python test process was terminated before it could exit on its own, the process errored with: Code: 1, Signal: null for workspace c:\Users\some-user\Gitlab\some-venv
2024-03-19 15:19:14.607 [info] ResultResolver EOT received for discovery.
2024-03-19 15:19:14.607 [info] Disposing data receiver for c:\Users\some-user\Gitlab\some-venv and deleting UUID; pytest discovery.
```

### 💡 Steps to Reproduce

1. Create a venv with some complex projects inside, including one that has tests
2. install and use napari with plugins in the environment
3. Remove napari from the environment
4. Try to run test discovery with pytest.

### 💡 Expected Behavior

After uninstall napari should no longer interfere with test discovery.

### 🌎 Environment

observed in napari 0.5.0 and earlier versions

**Comment by Czaki** [comment]
Napari itself do not perform any code on clean. It looks like a bug in poetry.
