### ISSUE TITLE
[plugins] Command line use: failure to load a layer closes the viewer

### ISSUE THREAD

**Issue by psobolewskiPhD** [napari/napari#6966]
### 🐛 Bug Report

Loading a ome zarr (2 image layers, 1 labels layer) from the command line:
`NAPARI_ASYNC=1 napari https://uk1s3.embassy.ebi.ac.uk/idr/zarr/v0.4/idr0001A/2551.zarr/A/1/0`
gives traceback due to the labels kwarg issue and **crashes the viewer (!!)**.
Here's the validation of the ome zarr:
https://ome.github.io/ome-ngff-validator/?source=https://uk1s3.embassy.ebi.ac.uk/idr/zarr/v0.4/idr0001A/2551.zarr/A/1/0/
```
Traceback (most recent call last):
  File "/Users/sobolp/Documents/dev/napari/napari/components/viewer_model.py", line 1474, in _add_layer_from_data
    layer = add_method(data, **(meta or {}))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: add_labels() got an unexpected keyword argument 'color'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/sobolp/Documents/dev/napari/napari/components/viewer_model.py", line 1283, in _open_or_raise_error
    added = self._add_layers_with_plugins(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sobolp/Documents/dev/napari/napari/components/viewer_model.py", line 1401, in _add_layers_with_plugins
    added.extend(self._add_layer_from_data(*_data))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sobolp/Documents/dev/napari/napari/components/viewer_model.py", line 1479, in _add_layer_from_data
    raise TypeError(
TypeError: _add_layer_from_data received an unexpected keyword argument ('color') for layer type labels

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/sobolp/Documents/dev/napari/napari/_qt/qt_viewer.py", line 1014, in _qt_open
    self.viewer.open(
  File "/Users/sobolp/Documents/dev/napari/napari/components/viewer_model.py", line 1183, in open
    layers = self._open_or_raise_error(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sobolp/Documents/dev/napari/napari/components/viewer_model.py", line 1292, in _open_or_raise_error
    raise ReaderPluginError(
napari.errors.reader_errors.ReaderPluginError: Tried opening with napari-ome-zarr, but failed.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/sobolp/micromamba/envs/napari-dev/bin/napari", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/sobolp/Documents/dev/napari/napari/__main__.py", line 576, in main
    _run()
  File "/Users/sobolp/Documents/dev/napari/napari/__main__.py", line 346, in _run
    viewer._window._qt_viewer._qt_open(
  File "/Users/sobolp/Documents/dev/napari/napari/_qt/qt_viewer.py", line 1022, in _qt_open
    handle_gui_reading(
  File "/Users/sobolp/Documents/dev/napari/napari/_qt/dialogs/qt_reader_dialog.py", line 190, in handle_gui_reading
    readers = prepare_remaining_readers(paths, plugin_name, error)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sobolp/Documents/dev/napari/napari/_qt/dialogs/qt_reader_dialog.py", line 245, in prepare_remaining_readers
    raise ReaderPluginError(
napari.errors.reader_errors.ReaderPluginError: Tried to read https://uk1s3.embassy.ebi.ac.uk/idr/zarr/v0.4/idr0001A/2551.zarr/A/1/0 with plugin napari-ome-zarr, because it was associated with that file extension/because it is the only plugin capable of reading that path, but it gave an error. Try associating a different plugin or installing a different plugin for this kind of file.
```

This same file works as expected using the new `New from clipboard` opens the image layers and notifies of the labels failure.

### 💡 Steps to Reproduce

Install napari-ome-zarr plugin.
run:
`NAPARI_ASYNC=1 napari https://uk1s3.embassy.ebi.ac.uk/idr/zarr/v0.4/idr0001A/2551.zarr/A/1/0`

### 💡 Expected Behavior

Ideally, load the layers, as 0.4.19, but it looks like the kwarg is actually removed in 0.5.0
https://github.com/napari/napari/pull/6641/files#diff-11f2c63f66f3e9b0271b3c1584a67e2eb682b8638c1c679bcd9d036f977675c5
This needs to be fixed in the plugin.
But in that case, don't load the labels layer with the TypeError, but **do** load the rest of the layers into the viewer rather than having the viewer crash.

### 🌎 Environment

napari: 0.5.0a2.dev694+g7b46a844
Platform: macOS-14.5-arm64-arm-64bit
System: MacOS 14.5
Python: 3.11.7 | packaged by conda-forge | (main, Dec 23 2023, 14:38:07) [Clang 16.0.6 ]
Qt: 6.6.0
PyQt6: 
NumPy: 1.26.4
SciPy: 1.12.0
Dask: 2024.1.1
VisPy: 0.14.3.dev15
magicgui: 0.8.1
superqt: 0.6.1
in-n-out: 0.1.9
app-model: 0.2.4
npe2: 0.7.4

OpenGL:
  - GL version:  2.1 Metal - 88.1
  - MAX_TEXTURE_SIZE: 16384
  - GL_MAX_3D_TEXTURE_SIZE: 2048

Screens:
  - screen 1: resolution 2560x1440, scale 2.0
  - screen 2: resolution 2560x1440, scale 2.0

Optional:
  - numba: 0.59.0
  - triangle not installed

Settings path:
  - /Users/sobolp/Library/Application Support/napari/napari-dev_36963bf0846bfe99dcf4f566a2cc780b6a723afa/settings.yaml
Plugins:
  - napari: 0.5.0a2.dev533+gc6abeb5d (81 contributions)
  - napari-animation: 0.0.8.dev36+g921f872 (2 contributions)
  - napari-console: 0.0.9 (0 contributions)
  - napari-foobar: 0.0.1 (8 contributions)
  - napari-ome-zarr: 0.5.2 (2 contributions)
  - napari-svg: 0.1.10 (2 contributions)
  - napari-threedee: 0.0.20.dev7+g2c86986 (24 contributions)

**Comment by Czaki** [comment]
cc @melonora 
We discussed this in the past. Did you still plan to open PR with bugfix, or should I do this?

**Comment by melonora** [comment]
I will do it.
