### ISSUE TITLE
Providing a points layerdatatuple with both `ndim` and `name` gives an ugly stacktrace if run twice

### ISSUE THREAD

**Issue by jni** [napari/napari#7050]
### 🐛 Bug Report

When using a magicgui widget to return a layerdatatuple that

1. is a points layer
2. has `ndim` set (e.g. to make an empty points layer, you can provide `(None, {'ndim': 2}, 'points')`)
3. has `name` set (this means that an existing layer with that name will be updated, not created from scratch)

if you run the widget twice, you will get a stack trace, because can only be set at construction time, not by setting an attribute on the layer.

The stacktrace produced:

```pytb
Traceback (most recent call last):
  File "<string>", line 16, in <module>
  File "/Users/jni/projects/napari/napari/_qt/_qapp_model/injection/_qprocessors.py", line 59, in _add_layer_data_tuples_to_viewer
    setattr(layer, k, v)
AttributeError: property 'ndim' of 'Points' object has no setter
```

### 💡 Steps to Reproduce

```python
import napari
import numpy as np

from napari._qt._qapp_model.injection._qprocessors import _add_layer_data_tuples_to_viewer

viewer = napari.Viewer()

# once runs fine
_add_layer_data_tuples_to_viewer(
        [(None, {'ndim': 2, 'name': 'inspector'}, 'points')],
        viewer=viewer,
        source=None
        )

# the next run errors
_add_layer_data_tuples_to_viewer(
        [(None, {'ndim': 2, 'name': 'inspector'}, 'points')],
        viewer=viewer,
        source=None
        )

napari.run()
```

### 💡 Expected Behavior

Not sure! At a minimum, a better error message. But, we might want to rethink not having parity between constructor arguments and settable attributes.

### 🌎 Environment

napari: 0.5.0a2.dev774+g6281842d0
Platform: macOS-14.5-arm64-arm-64bit
System: MacOS 14.5
Python: 3.11.9 | packaged by conda-forge | (main, Apr 19 2024, 18:34:54) [Clang 16.0.6 ]
Qt: 5.15.8
PyQt5: 5.15.9
NumPy: 1.26.4
SciPy: 1.13.0
Dask: 2024.5.1
VisPy: 0.14.3
magicgui: 0.8.2
superqt: 0.6.7
in-n-out: 0.2.0
app-model: 0.2.7
npe2: 0.7.6

OpenGL:
  - GL version:  2.1 Metal - 88.1
  - MAX_TEXTURE_SIZE: 16384
  - GL_MAX_3D_TEXTURE_SIZE: 2048

Screens:
  - screen 1: resolution 1800x1169, scale 2.0

Optional:
  - numba: 0.60.0
  - triangle not installed

Settings path:
  - /Users/jni/Library/Application Support/napari/all_f206df4881e2999baa22e6df448393db299c70d6/settings.yaml
Plugins:
  - affinder: 0.4.0rc1.dev1+g3ac2d0f.d20240626 (11 contributions)
  - napari: 0.5.0a2.dev774+g6281842d0 (81 contributions)
  - napari-aicsimageio: 0.7.2 (2 contributions)
  - napari-console: 0.0.9 (0 contributions)
  - napari-defdap: 0.1.dev18+g3f6496a.d20240606 (6 contributions)
  - napari-matplotlib: 2.0.1 (10 contributions)
  - napari-svg: 0.1.11.dev10+g7c18c89.d20240620 (2 contributions)
  - ome-types: 0.5.1.post1 (2 contributions)
  - skan: 0.11.2.dev9+gb703cf6 (4 contributions)
  - zarpaint: 0.3.2.dev1+g4eff43a (19 contributions)

### 💡 Additional Context

originally reported here: https://forum.image.sc/t/add-point-across-layers/98256/13

**Comment by psobolewskiPhD** [comment]
This is a duplicate of: https://github.com/napari/napari/issues/3005 which has a lot more discussion on it.
