### ISSUE TITLE
file menu error on closing/opening napari from jupyter

### ISSUE THREAD

**Issue by guiwitz** [napari/napari#7105]
### 🐛 Bug Report

When running napari from a notebook, after closing the viewer and reopening it, just opening the ```File``` menu triggers an error and makes it then impossible to open a new viewer. The bug appeared in napari 5.0.

### 💡 Steps to Reproduce

1. Open a viewer:
    ```
    import napari
    viewer = napari.Viewer()
    ```
2. Close it.
3. Make a new viewer
    ```
    viewer = napari.Viewer()
    ```
4. Go to the file menu

Generates the following error message in the notebook:
```python
Traceback (most recent call last):
  File "[/Users/gw18g940/mambaforge/envs/napari5bug/lib/python3.11/site-packages/app_model/expressions/_expressions.py", line 187](http://localhost:8887/Users/gw18g940/mambaforge/envs/napari5bug/lib/python3.11/site-packages/app_model/expressions/_expressions.py#line=186), in eval
    return cast(T, eval(code, {}, context))
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "<Expr>", line 1, in <module>
NameError: name 'new_layer_empty' is not defined

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "[/Users/gw18g940/mambaforge/envs/napari5bug/lib/python3.11/site-packages/napari/_qt/qt_main_window.py", line 838](http://localhost:8887/Users/gw18g940/mambaforge/envs/napari5bug/lib/python3.11/site-packages/napari/_qt/qt_main_window.py#line=837), in _update_file_menu_state
    self._update_menu_state('file_menu')
  File "[/Users/gw18g940/mambaforge/envs/napari5bug/lib/python3.11/site-packages/napari/_qt/qt_main_window.py", line 835](http://localhost:8887/Users/gw18g940/mambaforge/envs/napari5bug/lib/python3.11/site-packages/napari/_qt/qt_main_window.py#line=834), in _update_menu_state
    menu_model.update_from_context(get_context(layerlist))
  File "[/Users/gw18g940/mambaforge/envs/napari5bug/lib/python3.11/site-packages/app_model/backends/qt/_qmenu.py", line 90](http://localhost:8887/Users/gw18g940/mambaforge/envs/napari5bug/lib/python3.11/site-packages/app_model/backends/qt/_qmenu.py#line=89), in update_from_context
    _update_from_context(self.actions(), ctx, _recurse=_recurse)
  File "[/Users/gw18g940/mambaforge/envs/napari5bug/lib/python3.11/site-packages/app_model/backends/qt/_qmenu.py", line 352](http://localhost:8887/Users/gw18g940/mambaforge/envs/napari5bug/lib/python3.11/site-packages/app_model/backends/qt/_qmenu.py#line=351), in _update_from_context
    menu.update_from_context(ctx)
  File "[/Users/gw18g940/mambaforge/envs/napari5bug/lib/python3.11/site-packages/app_model/backends/qt/_qmenu.py", line 151](http://localhost:8887/Users/gw18g940/mambaforge/envs/napari5bug/lib/python3.11/site-packages/app_model/backends/qt/_qmenu.py#line=150), in update_from_context
    super().update_from_context(ctx, _recurse=_recurse)
  File "[/Users/gw18g940/mambaforge/envs/napari5bug/lib/python3.11/site-packages/app_model/backends/qt/_qmenu.py", line 90](http://localhost:8887/Users/gw18g940/mambaforge/envs/napari5bug/lib/python3.11/site-packages/app_model/backends/qt/_qmenu.py#line=89), in update_from_context
    _update_from_context(self.actions(), ctx, _recurse=_recurse)
  File "[/Users/gw18g940/mambaforge/envs/napari5bug/lib/python3.11/site-packages/app_model/backends/qt/_qmenu.py", line 350](http://localhost:8887/Users/gw18g940/mambaforge/envs/napari5bug/lib/python3.11/site-packages/app_model/backends/qt/_qmenu.py#line=349), in _update_from_context
    action.update_from_context(ctx)
  File "[/Users/gw18g940/mambaforge/envs/napari5bug/lib/python3.11/site-packages/app_model/backends/qt/_qaction.py", line 184](http://localhost:8887/Users/gw18g940/mambaforge/envs/napari5bug/lib/python3.11/site-packages/app_model/backends/qt/_qaction.py#line=183), in update_from_context
    self.setVisible(expr.eval(ctx) if (expr := self._menu_item.when) else True)
                    ^^^^^^^^^^^^^^
  File "[/Users/gw18g940/mambaforge/envs/napari5bug/lib/python3.11/site-packages/app_model/expressions/_expressions.py", line 366](http://localhost:8887/Users/gw18g940/mambaforge/envs/napari5bug/lib/python3.11/site-packages/app_model/expressions/_expressions.py#line=365), in eval
    return super().eval(context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[/Users/gw18g940/mambaforge/envs/napari5bug/lib/python3.11/site-packages/app_model/expressions/_expressions.py", line 190](http://localhost:8887/Users/gw18g940/mambaforge/envs/napari5bug/lib/python3.11/site-packages/app_model/expressions/_expressions.py#line=189), in eval
    raise NameError(
NameError: Names required to eval this expression are missing: {'new_layer_empty'}
```

At this point the viewer is usable, i.e. one can add a labels layer, draw in it etc. However, upon closing it and opening yet another one, one gets a new error:
```python
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[4], line 1
----> 1 viewer = napari.Viewer()

File [~/mambaforge/envs/napari5bug/lib/python3.11/site-packages/napari/viewer.py:66](http://localhost:8887/lab/tree/book/~/mambaforge/envs/napari5bug/lib/python3.11/site-packages/napari/viewer.py#line=65), in Viewer.__init__(self, title, ndisplay, order, axis_labels, show, **kwargs)
     62 from napari.window import Window
     64 _initialize_plugins()
---> 66 self._window = Window(self, show=show)
     67 self._instances.add(self)

File [~/mambaforge/envs/napari5bug/lib/python3.11/site-packages/napari/_qt/qt_main_window.py:680](http://localhost:8887/lab/tree/book/~/mambaforge/envs/napari5bug/lib/python3.11/site-packages/napari/_qt/qt_main_window.py#line=679), in Window.__init__(self, viewer, show)
    677 # import and index all discovered shimmed npe1 plugins
    678 index_npe1_adapters()
--> 680 self._add_menus()
    681 # TODO: the dummy actions should **not** live on the layerlist context
    682 # as they are unrelated. However, we do not currently have a suitable
    683 # enclosing context where we could store these keys, such that they
    684 # **and** the layerlist context key are available when we update
    685 # menus. We need a single context to contain all keys required for
    686 # menu update, so we add them to the layerlist context for now.
    687 if self._qt_viewer._layers is not None:

File [~/mambaforge/envs/napari5bug/lib/python3.11/site-packages/napari/_qt/qt_main_window.py:909](http://localhost:8887/lab/tree/book/~/mambaforge/envs/napari5bug/lib/python3.11/site-packages/napari/_qt/qt_main_window.py#line=908), in Window._add_menus(self)
    905 self._main_menu_shortcut.activated.connect(
    906     self._toggle_menubar_visible
    907 )
    908 # file menu
--> 909 self.file_menu = build_qmodel_menu(
    910     MenuId.MENUBAR_FILE, title=trans._('&File'), parent=self._qt_window
    911 )
    912 self._setup_npe1_samples_menu()
    913 self.file_menu.aboutToShow.connect(
    914     self._update_file_menu_state,
    915 )

File [~/mambaforge/envs/napari5bug/lib/python3.11/site-packages/napari/_qt/_qapp_model/_menus.py:32](http://localhost:8887/lab/tree/book/~/mambaforge/envs/napari5bug/lib/python3.11/site-packages/napari/_qt/_qapp_model/_menus.py#line=31), in build_qmodel_menu(menu_id, title, parent)
     14 """Build a QModelMenu from the napari app model
     15 
     16 Parameters
   (...)
     28     QMenu subclass populated with all items in `menu_id` menu.
     29 """
     30 from napari._app_model import get_app
---> 32 return QModelMenu(
     33     menu_id=menu_id, app=get_app(), title=title, parent=parent
     34 )

File [~/mambaforge/envs/napari5bug/lib/python3.11/site-packages/app_model/backends/qt/_qmenu.py:53](http://localhost:8887/lab/tree/book/~/mambaforge/envs/napari5bug/lib/python3.11/site-packages/app_model/backends/qt/_qmenu.py#line=52), in QModelMenu.__init__(self, menu_id, app, title, parent)
     51 self._app = Application.get_or_create(app) if isinstance(app, str) else app
     52 self.setObjectName(menu_id)
---> 53 self.rebuild()
     54 self._app.menus.menus_changed.connect(self._on_registry_changed)
     55 self.destroyed.connect(self._disconnect)

File [~/mambaforge/envs/napari5bug/lib/python3.11/site-packages/app_model/backends/qt/_qmenu.py:96](http://localhost:8887/lab/tree/book/~/mambaforge/envs/napari5bug/lib/python3.11/site-packages/app_model/backends/qt/_qmenu.py#line=95), in QModelMenu.rebuild(self, include_submenus, exclude)
     92 def rebuild(
     93     self, include_submenus: bool = True, exclude: Collection[str] | None = None
     94 ) -> None:
     95     """Rebuild menu by looking up self._menu_id in menu_registry."""
---> 96     _rebuild(
     97         menu=self,
     98         app=self._app,
     99         menu_id=self._menu_id,
    100         include_submenus=include_submenus,
    101         exclude=exclude,
    102     )

File [~/mambaforge/envs/napari5bug/lib/python3.11/site-packages/app_model/backends/qt/_qmenu.py:323](http://localhost:8887/lab/tree/book/~/mambaforge/envs/napari5bug/lib/python3.11/site-packages/app_model/backends/qt/_qmenu.py#line=322), in _rebuild(menu, app, menu_id, include_submenus, exclude)
    321             cast("QMenu", menu).addMenu(submenu)
    322     elif item.command.id not in _exclude:
--> 323         action = QMenuItemAction.create(item, app=app, parent=menu)
    324         menu.addAction(action)
    325 if n < n_groups - 1:

File [~/mambaforge/envs/napari5bug/lib/python3.11/site-packages/app_model/backends/qt/_qaction.py:175](http://localhost:8887/lab/tree/book/~/mambaforge/envs/napari5bug/lib/python3.11/site-packages/app_model/backends/qt/_qaction.py#line=174), in QMenuItemAction.create(cls, menu_item, app, parent)
    173 if cache_key in cls._cache:
    174     res = cls._cache[cache_key]
--> 175     res.setParent(parent)
    176     return res
    178 cls._cache[cache_key] = obj = cls(menu_item, app, parent)

RuntimeError: wrapped C[/C](http://localhost:8887/C)++ object of type QMenuItemAction has been deleted
```

### 💡 Expected Behavior

It should be possible to open and close the viewer.

### 🌎 Environment

napari: 0.5.0
Platform: macOS-14.5-arm64-arm-64bit
System: MacOS 14.5
Python: 3.11.9 | packaged by conda-forge | (main, Apr 19 2024, 18:34:54) [Clang 16.0.6 ]
Qt: 5.15.8
PyQt5: 5.15.9
NumPy: 2.0.0
SciPy: 1.14.0
Dask: 2024.7.0
VisPy: 0.14.3
magicgui: 0.8.3
superqt: 0.6.7
in-n-out: 0.2.1
app-model: 0.2.7
npe2: 0.7.6

OpenGL:
  - GL version:  2.1 Metal - 88.1
  - MAX_TEXTURE_SIZE: 16384
  - GL_MAX_3D_TEXTURE_SIZE: 2048

Screens:
  - screen 1: resolution 1512x982, scale 2.0

Optional:
  - numba: 0.60.0
  - triangle not installed

Settings path:
  - /Users/gw18g940/Library/Application Support/napari/napari5bug_b2501c9bab335f04457c00d9c75c5501857c5b41/settings.yaml
Plugins:
  - napari: 0.5.0 (81 contributions)
  - napari-console: 0.0.9 (0 contributions)
  - napari-svg: 0.2.0 (2 contributions)

**Comment by DragaDoncila** [comment]
Thanks for the report @guiwitz, @jni and I found this one yesterday and I'm looking into it now. It's definitely a side-effect of #7038 but I don't understand why it's happening yet. Can confirm it's only from a notebook so far (but probably also for ipython).

**Comment by Czaki** [comment]
@DragaDoncila problem is caused by this line: https://github.com/napari/napari/blob/5a42fd9af1a174381a63a049742b63643be439b6/napari/_qt/_qapp_model/qactions/__init__.py#L117

So next time a viewer is created, the elements are not added to context.

Maybe dedent of this line may solve it

https://github.com/napari/napari/blob/5a42fd9af1a174381a63a049742b63643be439b6/napari/_qt/_qapp_model/qactions/__init__.py#L119

**Comment by DragaDoncila** [comment]
@Czaki I agree that's possibly part of the problem for that second viewer trying to launch, but it's not the whole story. Why is the `context_key` not there on the first launch of the `viewer`? Is there some race condition going on? I also can't reliably reproduce the missing `context_key` in debugging

**Comment by DragaDoncila** [comment]
> Why is the context_key not there on the first launch of the viewer?

Hmm ok maybe I'm trippin' actually, because now I can't get the `Empty` error on first launch, but I'm so sure it was happening before... If it's not ever seen on first launch then the dedent should fix it.

**Comment by Czaki** [comment]
> Why is the `context_key` not there on the first launch of the `viewer`? Is there some race condition going on? I also can't reliably reproduce the missing `context_key` in debugging

I was unable to get a problem on first launch of viewer, so I was not investigating. But now I have opened #7109, that connected with #7106 may solve it (as the menu will be broken in no layerlist widget is created now).

**Comment by DragaDoncila** [comment]
> I was unable to get a problem on first launch of viewer

Yeah, I was never able to reproduce that either. I think when I did see it, I had actually forgot to restart the kernel so it was just a rendition of the second launch
