### ISSUE TITLE
Napari crashes when add_image() called with negative z-axis translation and nD data

### ISSUE THREAD

**Issue by ptbrown1729** [napari/napari#7248]
### 🐛 Bug Report

I am working with nD microscopy data which I use Napari to display. Often my data has up to 9-dimensions for e.g. z-stacking, xy-positions, illumination patterns, time-series, etc. When I want to display data acquired using different z-positions, I need use the translate argument to align these in napari. I recently created a Python 3.12 environment and upgraded to Napari 0.5.3, and my previous display code is no longer working. I created a minimal example to reproduce the problem I am seeing.

### 💡 Steps to Reproduce

```
import numpy as np
import napari

m = np.random.rand(1, 3, 10, 512, 512)

v = napari.Viewer()
v.add_image(m,
            translate=(-1.0, 0., 0.),
            )
v.show(block=True)
```

```
Traceback (most recent call last):
  File "/home/ptbrown/.config/JetBrains/PyCharmCE2024.1/scratches/scratch_14.py", line 7, in <module>
    v.add_image(m,
  File "/home/ptbrown/mambaforge/envs/mcsim312/lib/python3.12/site-packages/napari/utils/migrations.py", line 101, in _update_from_dict
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ptbrown/mambaforge/envs/mcsim312/lib/python3.12/site-packages/napari/components/viewer_model.py", line 990, in add_image
    self.layers.append(layer)
  File "<frozen _collections_abc>", line 1130, in append
  File "/home/ptbrown/mambaforge/envs/mcsim312/lib/python3.12/site-packages/napari/components/layerlist.py", line 188, in insert
    super().insert(index, new_layer)
  File "/home/ptbrown/mambaforge/envs/mcsim312/lib/python3.12/site-packages/napari/utils/events/containers/_selectable_list.py", line 68, in insert
    super().insert(index, value)
  File "/home/ptbrown/mambaforge/envs/mcsim312/lib/python3.12/site-packages/napari/utils/events/containers/_evented_list.py", line 202, in insert
    self.events.inserted(index=index, value=value)
  File "/home/ptbrown/mambaforge/envs/mcsim312/lib/python3.12/site-packages/napari/utils/events/event.py", line 764, in __call__
    self._invoke_callback(cb, event if pass_event else None)
  File "/home/ptbrown/mambaforge/envs/mcsim312/lib/python3.12/site-packages/napari/utils/events/event.py", line 802, in _invoke_callback
    _handle_exception(
  File "/home/ptbrown/mambaforge/envs/mcsim312/lib/python3.12/site-packages/napari/utils/events/event.py", line 789, in _invoke_callback
    cb(event)
  File "/home/ptbrown/mambaforge/envs/mcsim312/lib/python3.12/site-packages/napari/components/viewer_model.py", line 655, in _on_add_layer
    self._on_layers_change()
  File "/home/ptbrown/mambaforge/envs/mcsim312/lib/python3.12/site-packages/napari/components/viewer_model.py", line 517, in _on_layers_change
    self.dims.range = ranges
    ^^^^^^^^^^^^^^^
  File "/home/ptbrown/mambaforge/envs/mcsim312/lib/python3.12/site-packages/napari/utils/events/evented_model.py", line 307, in __setattr__
    with ComparisonDelayer(self):
  File "/home/ptbrown/mambaforge/envs/mcsim312/lib/python3.12/site-packages/napari/utils/events/evented_model.py", line 520, in __exit__
    self._target._check_if_values_changed_and_emit_if_needed()
  File "/home/ptbrown/mambaforge/envs/mcsim312/lib/python3.12/site-packages/napari/utils/events/evented_model.py", line 345, in _check_if_values_changed_and_emit_if_needed
    getattr(self.events, name)(value=new_value)
  File "/home/ptbrown/mambaforge/envs/mcsim312/lib/python3.12/site-packages/napari/utils/events/event.py", line 764, in __call__
    self._invoke_callback(cb, event if pass_event else None)
  File "/home/ptbrown/mambaforge/envs/mcsim312/lib/python3.12/site-packages/napari/utils/events/event.py", line 802, in _invoke_callback
    _handle_exception(
  File "/home/ptbrown/mambaforge/envs/mcsim312/lib/python3.12/site-packages/napari/utils/events/event.py", line 791, in _invoke_callback
    cb()
  File "/home/ptbrown/mambaforge/envs/mcsim312/lib/python3.12/site-packages/napari/components/viewer_model.py", line 475, in _update_layers
    position[ind] = self.dims.point[ind]
    ~~~~~~~~^^^^^
IndexError: list assignment index out of range
WARNING: QThread: Destroyed while thread is still running

Process finished with exit code 134 (interrupted by signal 6:SIGABRT)
```

### 💡 Expected Behavior

Napari should display the nD image without crashing

### 🌎 Environment

napari: 0.5.3
Platform: Linux-5.15.0-113-generic-x86_64-with-glibc2.31
System: Ubuntu 20.04.6 LTS
Python: 3.12.5 | packaged by conda-forge | (main, Aug 8 2024, 18:36:51) [GCC 12.4.0]
Qt: 5.15.8
PyQt5: 5.15.9
NumPy: 2.0.2
SciPy: 1.14.1
Dask: 2024.8.1
VisPy: 0.14.3
magicgui: 0.8.3
superqt: 0.6.7
in-n-out: 0.2.1
app-model: 0.2.8
npe2: 0.7.7

OpenGL:
- GL version: 4.6.0 NVIDIA 535.183.01
- MAX_TEXTURE_SIZE: 32768
- GL_MAX_3D_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1600x900, scale 1.0

Optional:
- numba: 0.60.0
- triangle not installed
- napari-plugin-manager: 0.1.0

### 💡 Additional Context

The crash occurs in `viewer_model.py` in the function `_update_layers()`. The problem seems to be that `self.cursor_position` is a 2D array, but it should not be. I was stepping through with my debugger, and it looks like what happens is `_on_layers_changed` gets called and should update the dimensionality of `self.cursor_position`, but after it resets the ranges using `self.dims.range = ranges` in line 517 this emits an event, and `_update_layers()` gets called before `_on_layers_changed()` is finished

**Comment by jni** [comment]
Thanks for the report @ptbrown1729! It looks like this is a regression in (at least) v0.5.0, because I still get the error in 0.5.0.

**Comment by jni** [comment]
Culprit from git bisect is #5522. Which ironically should have made things like arbitrary positions *better*. That is unfortunately a really big PR so it's not really going to be a great clue in terms of a fix — your own investigation will be more useful @ptbrown1729! 😂 🙏 But I don't a-priori know how to make the fix. But we'll make it a priority for 0.5.4.
