### ISSUE TITLE
Cannot save annotated h5 file

### ISSUE THREAD

**Issue by YugaKimura** [napari/napari#7320]
### 🐛 Bug Report

When I annotate an image and try to save the layer using Ctrl+S in the GUI, I get an error keyeroor:root at metadata=["root"] in _writer.py. viewer.layers[1].save("annotated.csv"), the csv file comes up, but viewer.layers[1].save("annotated.h5") also gives the above error. How can I deal with this error and save the annotated data?

### 💡 Steps to Reproduce

Annotate 25 .png data, click on tag layer and Ctrl+S or viewer.layers[1].save("annotated.h5") to console

### 💡 Expected Behavior

I can save an annotated layer.

### 🌎 Environment
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.1 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/home/erato_0/.pyenv/versions/kimuradlc/bin/napari", line 8, in <module>
    sys.exit(main())
  File "/home/erato_0/.pyenv/versions/kimuradlc/lib/python3.10/site-packages/napari/__main__.py", line 564, in main
    _run()
  File "/home/erato_0/.pyenv/versions/kimuradlc/lib/python3.10/site-packages/napari/__main__.py", line 213, in _run
    from napari import Viewer, run
  File "/home/erato_0/.pyenv/versions/kimuradlc/lib/python3.10/site-packages/napari/_lazy.py", line 45, in __getattr__
    submod = import_module(
  File "/home/erato_0/.pyenv/versions/3.10.7/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/erato_0/.pyenv/versions/kimuradlc/lib/python3.10/site-packages/napari/viewer.py", line 8, in <module>
    from napari.components.viewer_model import ViewerModel
  File "/home/erato_0/.pyenv/versions/kimuradlc/lib/python3.10/site-packages/napari/components/__init__.py", line 19, in <module>
    from napari.components.layerlist import LayerList
  File "/home/erato_0/.pyenv/versions/kimuradlc/lib/python3.10/site-packages/napari/components/layerlist.py", line 9, in <module>
    from napari.layers import Layer
  File "/home/erato_0/.pyenv/versions/kimuradlc/lib/python3.10/site-packages/napari/layers/__init__.py", line 9, in <module>
    from napari.layers.base import Layer
  File "/home/erato_0/.pyenv/versions/kimuradlc/lib/python3.10/site-packages/napari/layers/base/__init__.py", line 2, in <module>
    from napari.layers.base.base import Layer, no_op
  File "/home/erato_0/.pyenv/versions/kimuradlc/lib/python3.10/site-packages/napari/layers/base/base.py", line 45, in <module>
    from napari.utils.key_bindings import KeymapProvider
  File "/home/erato_0/.pyenv/versions/kimuradlc/lib/python3.10/site-packages/napari/utils/key_bindings.py", line 46, in <module>
    from napari.settings import get_settings
  File "/home/erato_0/.pyenv/versions/kimuradlc/lib/python3.10/site-packages/napari/settings/__init__.py", line 4, in <module>
    from napari.settings._base import _NOT_SET
  File "/home/erato_0/.pyenv/versions/kimuradlc/lib/python3.10/site-packages/napari/settings/_base.py", line 16, in <module>
    from napari.settings._yaml import PydanticYamlMixin
  File "/home/erato_0/.pyenv/versions/kimuradlc/lib/python3.10/site-packages/napari/settings/_yaml.py", line 9, in <module>
    from napari.settings._fields import Version
  File "/home/erato_0/.pyenv/versions/kimuradlc/lib/python3.10/site-packages/napari/settings/_fields.py", line 6, in <module>
    from napari.utils.theme import available_themes, is_theme_available
  File "/home/erato_0/.pyenv/versions/kimuradlc/lib/python3.10/site-packages/napari/utils/theme.py", line 25, in <module>
    from qtpy import QT_VERSION
  File "/home/erato_0/.pyenv/versions/kimuradlc/lib/python3.10/site-packages/qtpy/__init__.py", line 280, in <module>
    from PySide6 import __version__ as PYSIDE_VERSION  # analysis:ignore
  File "/home/erato_0/.pyenv/versions/kimuradlc/lib/python3.10/site-packages/PySide6/__init__.py", line 124, in <module>
    _setupQtDirectories()
  File "/home/erato_0/.pyenv/versions/kimuradlc/lib/python3.10/site-packages/PySide6/__init__.py", line 64, in _setupQtDirectories
    from shiboken6 import Shiboken
  File "/home/erato_0/.pyenv/versions/kimuradlc/lib/python3.10/site-packages/shiboken6/__init__.py", line 27, in <module>
    from shiboken6.Shiboken import *
Traceback (most recent call last):
  File "/home/erato_0/.pyenv/versions/kimuradlc/bin/napari", line 8, in <module>
    sys.exit(main())
  File "/home/erato_0/.pyenv/versions/kimuradlc/lib/python3.10/site-packages/napari/__main__.py", line 564, in main
    _run()
  File "/home/erato_0/.pyenv/versions/kimuradlc/lib/python3.10/site-packages/napari/__main__.py", line 213, in _run
    from napari import Viewer, run
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "/home/erato_0/.pyenv/versions/kimuradlc/lib/python3.10/site-packages/napari/_lazy.py", line 45, in __getattr__
    submod = import_module(
  File "/home/erato_0/.pyenv/versions/3.10.7/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/erato_0/.pyenv/versions/kimuradlc/lib/python3.10/site-packages/napari/viewer.py", line 8, in <module>
    from napari.components.viewer_model import ViewerModel
  File "/home/erato_0/.pyenv/versions/kimuradlc/lib/python3.10/site-packages/napari/components/__init__.py", line 19, in <module>
    from napari.components.layerlist import LayerList
  File "/home/erato_0/.pyenv/versions/kimuradlc/lib/python3.10/site-packages/napari/components/layerlist.py", line 9, in <module>
    from napari.layers import Layer
  File "/home/erato_0/.pyenv/versions/kimuradlc/lib/python3.10/site-packages/napari/layers/__init__.py", line 12, in <module>
    from napari.layers.points import Points
  File "/home/erato_0/.pyenv/versions/kimuradlc/lib/python3.10/site-packages/napari/layers/points/__init__.py", line 1, in <module>
    from napari.layers.points import _points_key_bindings
  File "/home/erato_0/.pyenv/versions/kimuradlc/lib/python3.10/site-packages/napari/layers/points/_points_key_bindings.py", line 4, in <module>
    from napari.layers.points.points import Points
  File "/home/erato_0/.pyenv/versions/kimuradlc/lib/python3.10/site-packages/napari/layers/points/points.py", line 38, in <module>
    from napari.layers.utils.text_manager import TextManager
  File "/home/erato_0/.pyenv/versions/kimuradlc/lib/python3.10/site-packages/napari/layers/utils/text_manager.py", line 29, in <module>
    class TextManager(EventedModel):
  File "/home/erato_0/.pyenv/versions/kimuradlc/lib/python3.10/site-packages/napari/layers/utils/text_manager.py", line 83, in TextManager
    string: StringEncoding = ConstantStringEncoding(constant='')
  File "/home/erato_0/.pyenv/versions/kimuradlc/lib/python3.10/site-packages/napari/utils/events/evented_model.py", line 242, in __init__
    super().__init__(**kwargs)
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for ConstantStringEncoding
constant
  Unable to avoid copy while creating an array as requested.
If using `np.array(obj, copy=False)` replace it with `np.asarray(obj)` to allow a copy when needed (no behavior change in NumPy 1.x).
For more details, see https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword. (type=value_error)

**Comment by psobolewskiPhD** [comment]
Do you have a plugin providing an .h5 writer? Because without a way to write such a file, there isn't much napari can do I don't think. Unless I am misunderstanding something, in which case my apologies!

**Comment by YugaKimura** [comment]
> Do you have a plugin providing an .h5 writer? Because without a way to write such a file, there isn't much napari can do I don't think. Unless I am misunderstanding something, in which case my apologies!


https://www.napari-hub.org/plugins/napari-h5

Are you talking about this plugin? It can read h5 files but not sure if it can write them out. Maybe it is a problem on the DeepLabCut side.

**Comment by psobolewskiPhD** [comment]
Sorry, I'm still not following what's happening:
- Are you suing that plugin and having an issue writing h5? 
- Are you using some other plugin (DeepLabCut)?

Could you please post the output of `napari --info` so we have some insight into what you have installed?
Likewise, we will need the complete traceback from when you get the error. You can paste it between sets of 3 backticks on empty lines to ensure it's formatted in a readable way.

**Comment by YugaKimura** [comment]
Traceback (most recent call last):
  File "/home/erato_0/.pyenv/versions/kimuradlc/lib/python3.10/site-packages/napari_deeplabcut/_widgets.py", line 656, in <lambda>
    lambda: _save_layers_dialog(
  File "/home/erato_0/.pyenv/versions/kimuradlc/lib/python3.10/site-packages/napari_deeplabcut/_widgets.py", line 300, in _save_layers_dialog
    self.viewer.layers.save("", selected=True, plugin="napari-deeplabcut")
  File "/home/erato_0/.pyenv/versions/kimuradlc/lib/python3.10/site-packages/napari/utils/_proxies.py", line 188, in __call__
    return self.create(self.__wrapped__(*args, **kwargs))
  File "/home/erato_0/.pyenv/versions/kimuradlc/lib/python3.10/site-packages/napari/components/layerlist.py", line 476, in save
    return save_layers(path, layers, plugin=plugin, _writer=_writer)
  File "/home/erato_0/.pyenv/versions/kimuradlc/lib/python3.10/site-packages/napari/plugins/io.py", line 229, in save_layers
    _written, writer_name = _write_single_layer_with_plugins(
  File "/home/erato_0/.pyenv/versions/kimuradlc/lib/python3.10/site-packages/napari/plugins/io.py", line 442, in _write_single_layer_with_plugins
    written_paths, writer_name = _npe2.write_layers(
  File "/home/erato_0/.pyenv/versions/kimuradlc/lib/python3.10/site-packages/napari/plugins/_npe2.py", line 111, in write_layers
    paths, writer = io_utils.write_get_writer(
  File "/home/erato_0/.pyenv/versions/kimuradlc/lib/python3.10/site-packages/npe2/io_utils.py", line 115, in write_get_writer
    return _write(path, layer_data, plugin_name=plugin_name, return_writer=True)
  File "/home/erato_0/.pyenv/versions/kimuradlc/lib/python3.10/site-packages/npe2/io_utils.py", line 320, in _write
    res = writer.exec(args=args)
  File "/home/erato_0/.pyenv/versions/kimuradlc/lib/python3.10/site-packages/npe2/manifest/utils.py", line 61, in exec
    return self.get_callable(reg)(*args, **kwargs)
  File "/home/erato_0/.pyenv/versions/kimuradlc/lib/python3.10/site-packages/napari_deeplabcut/_writer.py", line 51, in write_hdf
    root = metadata["root"]
KeyError: 'root'

These are error messages.

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.1 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/home/erato_0/.pyenv/versions/kimuradlc/bin/napari", line 8, in <module>
    sys.exit(main())
  File "/home/erato_0/.pyenv/versions/kimuradlc/lib/python3.10/site-packages/napari/__main__.py", line 564, in main
    _run()
  File "/home/erato_0/.pyenv/versions/kimuradlc/lib/python3.10/site-packages/napari/__main__.py", line 213, in _run
    from napari import Viewer, run
  File "/home/erato_0/.pyenv/versions/kimuradlc/lib/python3.10/site-packages/napari/_lazy.py", line 45, in __getattr__
    submod = import_module(
  File "/home/erato_0/.pyenv/versions/3.10.7/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/erato_0/.pyenv/versions/kimuradlc/lib/python3.10/site-packages/napari/viewer.py", line 8, in <module>
    from napari.components.viewer_model import ViewerModel
  File "/home/erato_0/.pyenv/versions/kimuradlc/lib/python3.10/site-packages/napari/components/__init__.py", line 19, in <module>
    from napari.components.layerlist import LayerList
  File "/home/erato_0/.pyenv/versions/kimuradlc/lib/python3.10/site-packages/napari/components/layerlist.py", line 9, in <module>
    from napari.layers import Layer
  File "/home/erato_0/.pyenv/versions/kimuradlc/lib/python3.10/site-packages/napari/layers/__init__.py", line 9, in <module>
    from napari.layers.base import Layer
  File "/home/erato_0/.pyenv/versions/kimuradlc/lib/python3.10/site-packages/napari/layers/base/__init__.py", line 2, in <module>
    from napari.layers.base.base import Layer, no_op
  File "/home/erato_0/.pyenv/versions/kimuradlc/lib/python3.10/site-packages/napari/layers/base/base.py", line 45, in <module>
    from napari.utils.key_bindings import KeymapProvider
  File "/home/erato_0/.pyenv/versions/kimuradlc/lib/python3.10/site-packages/napari/utils/key_bindings.py", line 46, in <module>
    from napari.settings import get_settings
  File "/home/erato_0/.pyenv/versions/kimuradlc/lib/python3.10/site-packages/napari/settings/__init__.py", line 4, in <module>
    from napari.settings._base import _NOT_SET
  File "/home/erato_0/.pyenv/versions/kimuradlc/lib/python3.10/site-packages/napari/settings/_base.py", line 16, in <module>
    from napari.settings._yaml import PydanticYamlMixin
  File "/home/erato_0/.pyenv/versions/kimuradlc/lib/python3.10/site-packages/napari/settings/_yaml.py", line 9, in <module>
    from napari.settings._fields import Version
  File "/home/erato_0/.pyenv/versions/kimuradlc/lib/python3.10/site-packages/napari/settings/_fields.py", line 6, in <module>
    from napari.utils.theme import available_themes, is_theme_available
  File "/home/erato_0/.pyenv/versions/kimuradlc/lib/python3.10/site-packages/napari/utils/theme.py", line 25, in <module>
    from qtpy import QT_VERSION
  File "/home/erato_0/.pyenv/versions/kimuradlc/lib/python3.10/site-packages/qtpy/__init__.py", line 280, in <module>
    from PySide6 import __version__ as PYSIDE_VERSION  # analysis:ignore
  File "/home/erato_0/.pyenv/versions/kimuradlc/lib/python3.10/site-packages/PySide6/__init__.py", line 124, in <module>
    _setupQtDirectories()
  File "/home/erato_0/.pyenv/versions/kimuradlc/lib/python3.10/site-packages/PySide6/__init__.py", line 64, in _setupQtDirectories
    from shiboken6 import Shiboken
  File "/home/erato_0/.pyenv/versions/kimuradlc/lib/python3.10/site-packages/shiboken6/__init__.py", line 27, in <module>
    from shiboken6.Shiboken import *
Traceback (most recent call last):
  File "/home/erato_0/.pyenv/versions/kimuradlc/bin/napari", line 8, in <module>
    sys.exit(main())
  File "/home/erato_0/.pyenv/versions/kimuradlc/lib/python3.10/site-packages/napari/__main__.py", line 564, in main
    _run()
  File "/home/erato_0/.pyenv/versions/kimuradlc/lib/python3.10/site-packages/napari/__main__.py", line 213, in _run
    from napari import Viewer, run
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "/home/erato_0/.pyenv/versions/kimuradlc/lib/python3.10/site-packages/napari/_lazy.py", line 45, in __getattr__
    submod = import_module(
  File "/home/erato_0/.pyenv/versions/3.10.7/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/erato_0/.pyenv/versions/kimuradlc/lib/python3.10/site-packages/napari/viewer.py", line 8, in <module>
    from napari.components.viewer_model import ViewerModel
  File "/home/erato_0/.pyenv/versions/kimuradlc/lib/python3.10/site-packages/napari/components/__init__.py", line 19, in <module>
    from napari.components.layerlist import LayerList
  File "/home/erato_0/.pyenv/versions/kimuradlc/lib/python3.10/site-packages/napari/components/layerlist.py", line 9, in <module>
    from napari.layers import Layer
  File "/home/erato_0/.pyenv/versions/kimuradlc/lib/python3.10/site-packages/napari/layers/__init__.py", line 12, in <module>
    from napari.layers.points import Points
  File "/home/erato_0/.pyenv/versions/kimuradlc/lib/python3.10/site-packages/napari/layers/points/__init__.py", line 1, in <module>
    from napari.layers.points import _points_key_bindings
  File "/home/erato_0/.pyenv/versions/kimuradlc/lib/python3.10/site-packages/napari/layers/points/_points_key_bindings.py", line 4, in <module>
    from napari.layers.points.points import Points
  File "/home/erato_0/.pyenv/versions/kimuradlc/lib/python3.10/site-packages/napari/layers/points/points.py", line 38, in <module>
    from napari.layers.utils.text_manager import TextManager
  File "/home/erato_0/.pyenv/versions/kimuradlc/lib/python3.10/site-packages/napari/layers/utils/text_manager.py", line 29, in <module>
    class TextManager(EventedModel):
  File "/home/erato_0/.pyenv/versions/kimuradlc/lib/python3.10/site-packages/napari/layers/utils/text_manager.py", line 83, in TextManager
    string: StringEncoding = ConstantStringEncoding(constant='')
  File "/home/erato_0/.pyenv/versions/kimuradlc/lib/python3.10/site-packages/napari/utils/events/evented_model.py", line 242, in __init__
    super().__init__(**kwargs)
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for ConstantStringEncoding
constant
  Unable to avoid copy while creating an array as requested.
If using `np.array(obj, copy=False)` replace it with `np.asarray(obj)` to allow a copy when needed (no behavior change in NumPy 1.x).
For more details, see https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword. (type=value_error)

These are napari --info massages.




> Sorry, I'm still not following what's happening:
> 
>     * Are you suing that plugin and having an issue writing h5?
> 
>     * Are you using some other plugin (DeepLabCut)?
> 
> 
> Could you please post the output of `napari --info` so we have some insight into what you have installed? Likewise, we will need the complete traceback from when you get the error. You can paste it between sets of 3 backticks on empty lines to ensure it's formatted in a readable way.

**Comment by psobolewskiPhD** [comment]
Are you selecting the right layer?
Looking at the deeplabcut code:
https://github.com/DeepLabCut/napari-deeplabcut/blob/0ceba4f203135aeeeaf8edfb8a8689d0517a5e1e/src/napari_deeplabcut/napari.yaml#L45-L51

This means that you have to have exactly 1 points layer selected to use their h5 writer and exactly 1 shapes to use the .csv writer.

Also I don't understand from your traceback:
````
packages/napari_deeplabcut/_writer.py", line 51, in write_hdf
root = metadata["root"]
```

That line doesn't match the code:
`    root = meta["root"]`

Probably you should open an issue with the plugin....

**Comment by YugaKimura** [comment]
I resolved in `pip install napari-save-transformed -U` ! Thank you!
