### ISSUE TITLE
Weird issue with dask/zarr datasets

### ISSUE THREAD

**Issue by vigji** [napari/napari#733]
I am experiencing a weird issue when trying to use napery to explore dask arrays stored in zarr files. I would like to integrate napari as the viewer for a calcium imaging data pipeline that I am building using dask (x)arrays stored in zarr datasets. Up to some size of the dask array, when I open the napari viewer everything runs smoothly. After increasing a dimension of the dask array, keeping the same chunking, when starting the viewer it tries to load the entire dataset in memory and crashes.

## To Reproduce
This creates dummy data similar to what I am using for my real case scenario:
```python
# Generate dummy dataset:
def get_dummy_dset(shape, chunks):
    dims = ["t", "z", "y", "x"]
    dask_data = da.random.random(shape, chunks=chunks)
    xdataset = xa.Dataset({"fluorescence": (dims, dask_data)}, 
                          coords={k: np.arange(dask_data.shape[i]) 
                                  for i, k in enumerate(dims)})
    return xdataset

# Save zarr groups with slightly different 1st dimension:
data_path = ".../somefolder/"
ds1 = get_dummy_dset((8100, 8, 100, 200), chunks=(50, 8, 100, 200))
ds1.to_zarr(data_path + "/example_dataset_large_good.zarr", 
            encoding=dict(fluorescence=dict(compressor=None)))

ds2 = get_dummy_dset((8500, 8, 100, 200), chunks=(50, 8, 100, 200))
ds2.to_zarr("{}/example_dataset_large_bad.zarr".format(data_path), 
            encoding=dict(fluorescence=dict(compressor=None)))
```

Then, I try to load them in napari with the following code:
```python
import napari
import xarray as xa

with napari.gui_qt():
    ds1 = xa.open_zarr(data_path + "/example_dataset_large_good.zarr")
    stack1 = ds1["fluorescence"]
    viewer = napari.view_image(stack1)
```

When loading the first dataset, everything run nicely. On the second one, only 5% bigger, napari tries to load everything in memory and it crashes. To my preliminary testing it seems that:
 - this is not related to absolute size: increasing of the same amount other dimensions does not look critical;
 - this is not related to chunk number, as different chunking does not fix it.

I experience this both on a macBook and on a Windows 10 desktop computer with different specs in memory and processor. 

Do you have any pointer on why/where this might be happening?

By the way, amazing project! I have been waiting a long time for something like this to happen, I would be happy to contribute with examples from our data analysis pipeline once I get more into it!

**Comment by jni** [comment]
Hi @vigji!

Thanks for the enthusiasm, and we certainly can't get enough examples of people using napari with their own data! 😊 

I think your issue is probably related to https://github.com/napari/napari/issues/699 or https://github.com/napari/napari/issues/731 or both. (But my intuition says #699 is the culprit.) We are working on a fix! Thanks for reporting!

**Comment by s-m-e** [comment]
Does [this](https://github.com/napari/napari/issues/710#issuecomment-556444450) fix your issue? Then it is #699.

**Comment by vigji** [comment]
Thank you everyone for the feedback!
Yes, in the end it was #699, setting `is_pyramid=False` solves the issue. For clarifying this to other people coming to this issue, there is a threshold at 2**13 after which some a for pyramid guessing returns true:
```
misc.py 108: return np.log2(shape) >= 13
```
And my datasets were at the edge of that :) 
To be precise, the line that seems to be decompressing the entire dataset is after that call, in `fast_pyramid`, i think line 234. The `is_pyramid=False` argument prevents this call.

On a related note, the line that was mentioned (discussion  of #710 ):
```
misc.py 69: size = np.array([np.prod(d.shape) for d in data])
```
it does not try to load everything in memory, but does result in a significant delay when opening the gui (6-7 seconds, I am using `xa.open_zarr()` to create the data array).

Also, this took a while to test because on my laptop only (macBook), if I pass only `is_pyramid=False` with my previously described example, I get the following error:
```
Traceback (most recent call last):
  File "/Users/luigipetrucco/lab_code/napari/examples/dask_nD_image.py", line 22, in <module>
    viewer = napari.view_image(stack1, is_pyramid=True)
  File "/Users/luigipetrucco/lab_code/napari/napari/view_layers.py", line 109, in view_image
    path=path,
  File "/Users/luigipetrucco/lab_code/napari/napari/components/viewer_model.py", line 490, in add_image
    self.add_layer(layer)
  File "/Users/luigipetrucco/lab_code/napari/napari/components/viewer_model.py", line 385, in add_layer
    self.layers.append(layer)
  File "/Users/luigipetrucco/lab_code/napari/napari/util/list/_model.py", line 56, in append
    self.events.added(item=object, index=len(self) - 1)
  File "/Users/luigipetrucco/lab_code/napari/napari/util/event.py", line 508, in __call__
    self._invoke_callback(cb, event)
  File "/Users/luigipetrucco/lab_code/napari/napari/util/event.py", line 529, in _invoke_callback
    cb_event=(cb, event),
  File "/Users/luigipetrucco/lab_code/napari/napari/util/event.py", line 523, in _invoke_callback
    cb(event)
  File "/Users/luigipetrucco/lab_code/napari/napari/_qt/qt_controls.py", line 50, in _add
    controls = create_qt_controls(layer)
  File "/Users/luigipetrucco/lab_code/napari/napari/_qt/layers/util.py", line 36, in create_qt_controls
    controls = layer_to_controls[type(layer)](layer)
  File "/Users/luigipetrucco/lab_code/napari/napari/_qt/layers/qt_image_layer.py", line 11, in __init__
    super().__init__(layer)
  File "/Users/luigipetrucco/lab_code/napari/napari/_qt/layers/qt_image_base_layer.py", line 38, in __init__
    self.contrast_limits_slider_update()
  File "/Users/luigipetrucco/lab_code/napari/napari/_qt/layers/qt_image_base_layer.py", line 80, in contrast_limits_slider_update
    self.contrastLimitsSlider.setValues((slidermin, slidermax))
  File "/Users/luigipetrucco/lab_code/napari/napari/_qt/qt_range_slider.py", line 104, in setValues
    self.updateDisplayValues()
  File "/Users/luigipetrucco/lab_code/napari/napari/_qt/qt_range_slider.py", line 252, in updateDisplayValues
    range_min = int(size * (self.scale_min - self.start) / self.scale)
ValueError: cannot convert float NaN to integer
```
This can be solved by also passing contrast_limits argument. Funnily, this happens only with the dataset bigger than the critical 8192 size, and it does not happen on my desktop Windows. I can look more into this and open a separate issue.

**Comment by sofroniewn** [comment]
@vigji sorry about this, we're actively working to try and improve this - see #736 for a meta issue and #737 for an attempt. We're working on dropping that magic `8192` number and this pyramid calculation.

As to the contrast_limits calculation, I can look into that too

**Comment by sofroniewn** [comment]
We have now released `0.2.6` it should fix some, but maybe not all of these issue. If you can continue any testing with that release that would be great. We'll be working on further changes in #737 which is still in progress

**Comment by vigji** [comment]
I tried to run all the above tests with the new version and (as expected in #740 ) it seem that everything reported above still happen!
No big deal, I will keep the `is_pyramid` argument for now. I just need to figure out why passing that without setting the `contrast_limits` argument crashes on my mac.

**Comment by sofroniewn** [comment]
I'm going to close this now as it seems like the `contrast_limits` issue with our range slider was fixed and we now have good testing for making sure the https://github.com/napari/napari/blob/dec5b9965d4a3fcea2d8314064465af14a97fec7/napari/layers/layer_utils.py#L25-L65
function doesn't take too long if big data is provided - both zarr and dask - see https://github.com/napari/napari/blob/dec5b9965d4a3fcea2d8314064465af14a97fec7/napari/layers/image/_tests/test_big_image_timing.py#L14-L25

If anyone is continuing to have to pass `contrast_limits` in order to avoid expensive computations can they please open a fresh issue with a minimal example so we can make sure that isn't still happening for people. You might still need to pass the `is_pyramid=False` or `is_pyramid=True` depending on your circumstances

**Comment by vigji** [comment]
Yep! Tested it again recently and I had no troubles with the `contrast_limit`. I confirm that for my case I still had to pass `is_pyramid=False` but this is definitively reasonable.
