### ISSUE TITLE
TypeError and sometimes UnboundLocalError when viewing a volume with extreme skew

### ISSUE THREAD

**Issue by jni** [napari/napari#7363]
### 🐛 Bug Report

When viewing a layer with extreme levels of skew, I get the following traceback while rotating the volume:

```pytb
    220 """Get the coordinate for a given face in an axis-aligned bounding box.
    221 For example, if the bounding box has extents [[0, 10], [0, 20], [0, 30]]
    222 (ordered zyx), then the face with normal [0, 1, 0] is described by
   (...)
    238     the axis its normal is aligned with.
    239 """
    240 axis = np.argwhere(face_normal)
--> 241 if face_normal[axis] > 0:
        axis = array([], shape=(0, 0), dtype=int64)
        face_normal = None
    242     # face is pointing in the positive direction,
    243     # take the max extent
    244     face_coordinate = bounding_box[axis, 1]
    245 else:
    246     # face is pointing in the negative direction,
    247     # take the min extent

TypeError: 'NoneType' object is not subscriptable
```

On occasion, I've also seen the following (though I can't reproduce right now):

```pytb
Traceback (most recent call last):
  File "/Users/jni/micromamba/envs/amms/lib/python3.12/site-packages/napari/_qt/threads/status_checker.py", line 86, in run
    self.calculate_status()
  File "/Users/jni/micromamba/envs/amms/lib/python3.12/site-packages/napari/_qt/threads/status_checker.py", line 110, in calculate_status
    self.status_and_tooltip_changed.emit(res)
                                         ^^^
UnboundLocalError: cannot access local variable 'res' where it is not associated with a value
```

Both should be avoided.

### 💡 Steps to Reproduce

```python
import napari
import numpy as np

affine = np.eye(4)
affine[2, 0] = 1280

viewer = napari.Viewer(ndisplay=3)
layer = viewer.add_image(
        np.random.random((12, 1280, 1024)),
        rendering='translucent',
        affine=affine,
        )

napari.run()
```

then rotate/hover over the volume.

### 💡 Expected Behavior

There should be no error raised.

### 🌎 Environment

```
napari: 0.5.4rc4.dev0+gc73e9d5ec.d20241014
Platform: macOS-14.5-arm64-arm-64bit
System: MacOS 14.5
Python: 3.11.10 | packaged by conda-forge | (main, Sep 30 2024, 17:58:42) [Clang 17.0.6 ]
Qt: 5.15.8
PyQt5: 5.15.9
NumPy: 2.0.2
SciPy: 1.14.1
Dask: 2024.9.1
VisPy: 0.14.3
magicgui: 0.8.3
superqt: 0.6.7
in-n-out: 0.2.1
app-model: 0.3.0
psygnal: 0.11.1
npe2: 0.7.7
pydantic: 2.9.2

OpenGL:
  - GL version:  2.1 Metal - 88.1
  - MAX_TEXTURE_SIZE: 16384
  - GL_MAX_3D_TEXTURE_SIZE: 2048

Screens:
  - screen 1: resolution 1800x1169, scale 2.0

Optional:
  - numba: 0.60.0
  - triangle not installed
  - napari-plugin-manager: 0.1.3

Settings path:
  - /Users/jni/Library/Application Support/napari/all_f206df4881e2999baa22e6df448393db299c70d6/settings.yaml
Plugins:
  - napari: 0.5.4rc4.dev0+gc73e9d5ec.d20241014 (81 contributions)
  - napari-console: 0.1.0 (0 contributions)
  - napari-svg: 0.2.0 (2 contributions)
  - skan: 0.11.2.dev38+g669eeba.d20241014 (4 contributions)
```

**Comment by willingc** [comment]
This is reproducible with Juan's code.

Seems as if there is some issue with the bounding box and the intersection. Need someone with domain knowledge to further troubleshoot.

```
File ~/Code/repos-napari/napari/napari/utils/geometry.py:739, in intersect_line_with_axis_aligned_bounding_box_3d(line_point=array([-3.21495e+02,  5.46622e+02,  3.29099e+05]), line_direction=array([ 9.77466e-04,  1.22071e-04, -1.00000e+00]), bounding_box=array([[   0.,   12.],
       [   0., 1280.],
       [   0., 1024.]]), face_normal=None)
    709 def intersect_line_with_axis_aligned_bounding_box_3d(
    710     line_point: np.ndarray,
    711     line_direction: np.ndarray,
    712     bounding_box: np.ndarray,
    713     face_normal: np.ndarray,
    714 ):
    715     """Find the intersection of a ray with the specified face of an
    716     axis-aligned bounding box.
    717 
   (...)
    737         the specified face.
    738     """
--> 739     front_face_coordinate = face_coordinate_from_bounding_box(
        bounding_box = array([[   0.,   12.],
       [   0., 1280.],
       [   0., 1024.]])
        face_normal = None
    740         bounding_box, face_normal
    741     )
    742     intersection_point = np.squeeze(
    743         intersect_line_with_axis_aligned_plane(
    744             front_face_coordinate,
   (...)
    748         )
    749     )
    751     return intersection_point

File ~/Code/repos-napari/napari/napari/utils/geometry.py:241, in face_coordinate_from_bounding_box(bounding_box=array([[   0.,   12.],
       [   0., 1280.],
       [   0., 1024.]]), face_normal=None)
    220 """Get the coordinate for a given face in an axis-aligned bounding box.
    221 For example, if the bounding box has extents [[0, 10], [0, 20], [0, 30]]
    222 (ordered zyx), then the face with normal [0, 1, 0] is described by
   (...)
    238     the axis its normal is aligned with.
    239 """
    240 axis = np.argwhere(face_normal)
--> 241 if face_normal[axis] > 0:
        axis = array([], shape=(0, 0), dtype=int64)
        face_normal = None
    242     # face is pointing in the positive direction,
    243     # take the max extent
    244     face_coordinate = bounding_box[axis, 1]
    245 else:
    246     # face is pointing in the negative direction,
    247     # take the min extent

TypeError: 'NoneType' object is not subscriptable
```

**Comment by Czaki** [comment]
> On occasion, I've also seen the following (though I can't reproduce right now):
> 
> ```
> Traceback (most recent call last):
>   File "/Users/jni/micromamba/envs/amms/lib/python3.12/site-packages/napari/_qt/threads/status_checker.py", line 86, in run
>     self.calculate_status()
>   File "/Users/jni/micromamba/envs/amms/lib/python3.12/site-packages/napari/_qt/threads/status_checker.py", line 110, in calculate_status
>     self.status_and_tooltip_changed.emit(res)
>                                          ^^^
> UnboundLocalError: cannot access local variable 'res' where it is not associated with a value
> ```

This is fixed in #7337, so you may see this with some old branches without recent main changes.

**Comment by willingc** [comment]
@Czaki Any reason not to move `self.status_and_tooltip_changed.emit(res)` inside the try block in the fix #7337

**Comment by Czaki** [comment]
> @Czaki Any reason not to move `self.status_and_tooltip_changed.emit(res)` inside the try block in the fix #7337

I do not understand. The #7337 is fixing pointed bug.

There is no need for creating try, except block.

**Comment by jni** [comment]
I think @willingc was suggesting the following structure:

```
        try:
            res = viewer._calc_status_from_cursor()
            self.status_and_tooltip_changed.emit(res)
        except Exception as e:  # pragma: no cover # noqa: BLE001
            notification_manager.dispatch(Notification.from_exception(e))
```

**Comment by willingc** [comment]
Yup @jni. I suspect that `res` may be invalid if checked outside the try block.

**Comment by jni** [comment]
it's not invalid, and an early return in the except is a valid way to avoid the error. But indeed I do like your suggestion's structure slightly better. I think the only caveat is that it's typically considered good practice to make try blocks as small as possible, because you want to make sure that the error you're catching is the error you *think* you're catching.

**Comment by willingc** [comment]
I wish that I had copied the place where I was seeing a funky error in the CI runs where it looked as if `res` was unknown/unavailable in the thread.

> In status_checker.py::calculate_status add missed return to prevent self.status_and_tooltip_changed.emit(res) with uninitialized res.

#7337 fixed the most common case, but I'm not sure that there isn't weird behavior if something else changes state before the code hits In `self.status_and_tooltip_changed.emit(res)`. If I see the error again in the CI runs, I will flag here.

**Comment by Czaki** [comment]
> I think @willingc was suggesting the following structure:
> 
> ```
>         try:
>             res = viewer._calc_status_from_cursor()
>             self.status_and_tooltip_changed.emit(res)
>         except Exception as e:  # pragma: no cover # noqa: BLE001
>             notification_manager.dispatch(Notification.from_exception(e))
> ```

I prefer to follow in this case the [PEP-8](https://peps.python.org/pep-0008/)

> Additionally, for all try/except clauses, limit the try clause to the absolute minimum amount of code necessary. Again, this avoids masking bugs:

If we want to catch exceptions in signal emission, we should catch it in a separate clause.

**Comment by willingc** [comment]
Hmm... fair enough re: PEP-8. In this case `res` is a placeholder value that could be removed by the following:

```python
def calculate_status(self) -> None:
        """Calculate the status and emit the signal.

        If the viewer is not available, do nothing.
        """
        viewer = self.viewer_ref()
        if viewer is None:
            return

        try:
            self.status_and_tooltip_changed.emit(viewer._calc_status_from_cursor())
        except Exception as e:  # pragma: no cover # noqa: BLE001
            # Our codebase is not threadsafe. It is possible that an
            # ViewerModel or Layer state is changed while we are trying to
            # calculate the status, which may lead to an exception.
            # We catch all exceptions here to prevent the thread from
            # crashing. The error is logged and a notification is shown.
            #
            # We do not want to crash the thread to keep the status updates.
            notification_manager.dispatch(Notification.from_exception(e))
            return
```

**Comment by Czaki** [comment]
It is not a placeholder. It is moving, emitting calls outside the `try: ... except` block. That any error that happens in emit call will not be redirected to the notification manager.

**Comment by willingc** [comment]
I'm not following how `res` is used being here. 

If something goes wrong with the thread between the try execution and the following emit statement, then there is indeterminate behavior where `res` is no longer valid or in existence.

**Comment by Czaki** [comment]
In general, the `StatusChecker` thread is used to not have lagging interface because of status text calculation. 

However, as the status is calculated in a separate branch, it may happen, that the data will be updated during status calculation, that may lead to exception. 

Such an exception is not critical, as in most situations it is just a result of an update, of a layer state. As it may be something different, we decided not to silence it, but just report to the notification manager. 

However, if we successfully calculate state information, we report it using Qt Signal machinery. If some exception happens during event emission, it is a critical error and needs to be treated separately. 

And in linked PEP-8 there is exactly example to not join handler with potentially problematic code:
![obraz](https://github.com/user-attachments/assets/f69431fb-0c12-47c6-af86-8c56ca9580c2)

**Comment by willingc** [comment]
Cool. Thanks for the helpful context explanation @Czaki . I was looking at this as a normal Python thread and missed the Signal behavior. I will close the existing PR and open a new PR to clarify the behavior and perhaps reduce confusion for a future contributor. 🙏🏼
