### ISSUE TITLE
async slicing does not propagate errors during slicing

### ISSUE THREAD

**Issue by jni** [napari/napari#7456]
### 🐛 Bug Report

If your array object generates errors during slicing *and async slicing is on*, napari will simply sit on the loading animation for that layer and there will be no indication of what is going wrong:

<img width="910" alt="Screenshot 2024-12-19 at 3 51 19 pm" src="https://github.com/user-attachments/assets/af8d2457-a6ab-4942-9d37-4388e3ede39d" />

if you run the code below with `NAPARI_ASYNC=0`, then you will get the appropriate traceback:

```pytb
$ NAPARI_ASYNC=0 python error-slicer.py
Traceback (most recent call last):
  File "/Users/jni/projects/play/error-slicer.py", line 11, in <module>
    viewer, layer = napari.imshow(arr)
                    ^^^^^^^^^^^^^^^^^^
  File "/Users/jni/projects/napari/napari/view_layers.py", line 405, in imshow
    return _make_viewer_then(
           ^^^^^^^^^^^^^^^^^^
  File "/Users/jni/projects/napari/napari/view_layers.py", line 173, in _make_viewer_then
    added = method(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jni/projects/napari/napari/utils/migrations.py", line 101, in _update_from_dict
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jni/projects/napari/napari/components/viewer_model.py", line 1004, in add_image
    layer = Image(data, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jni/projects/napari/napari/layers/base/base.py", line 115, in __call__
    obj._post_init()
  File "/Users/jni/projects/napari/napari/layers/_scalar_field/scalar_field.py", line 311, in _post_init
    self.refresh()
  File "/Users/jni/projects/napari/napari/layers/base/base.py", line 1553, in refresh
    self._refresh_sync(
  File "/Users/jni/projects/napari/napari/layers/base/base.py", line 1577, in _refresh_sync
    self.set_view_slice()
  File "/Users/jni/projects/napari/napari/layers/base/base.py", line 1269, in set_view_slice
    self._set_view_slice()
  File "/Users/jni/projects/napari/napari/layers/_scalar_field/scalar_field.py", line 490, in _set_view_slice
    response = request()
               ^^^^^^^^^
  File "/Users/jni/projects/napari/napari/layers/image/_slice.py", line 212, in __call__
    else self._call_single_scale()
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jni/projects/napari/napari/layers/image/_slice.py", line 217, in _call_single_scale
    data = self._project_thick_slice(self.data, self.data_slice)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jni/projects/napari/napari/layers/image/_slice.py", line 316, in _project_thick_slice
    return np.asarray(data[slices])
                      ~~~~^^^^^^^^
  File "/Users/jni/projects/play/error-slicer.py", line 7, in __getitem__
    raise RuntimeError('knife block! 🥋')
RuntimeError: knife block! 🥋
```

### 💡 Steps to Reproduce

Run the code below with `NAPARI_ASYNC=1` or `NAPARI_ASYNC=0`.

```python
import numpy as np
import wrapt
import napari

class DontSliceMeBro(wrapt.ObjectProxy):
    def __getitem__(self, key):
        raise RuntimeError('knife block! 🥋')

arr = DontSliceMeBro(np.array([[[1, 0.5], [0.3, 1]],] * 2))

viewer, layer = napari.imshow(arr)

napari.run()
```

### 💡 Expected Behavior

There should be some indication that an error has occurred during slicing and that we are not actually doing anything.

### 🌎 Environment

```
napari: 0.5.5
Platform: macOS-15.1.1-arm64-arm-64bit
System: MacOS 15.1.1
Python: 3.11.10 | packaged by conda-forge | (main, Sep 30 2024, 17:58:42) [Clang 17.0.6 ]
Qt: 5.15.8
PyQt5: 5.15.9
NumPy: 1.26.4
SciPy: 1.14.1
Dask: 2024.9.1
VisPy: 0.14.3
magicgui: 0.10.0rc1
superqt: 0.6.7
in-n-out: 0.2.1
app-model: 0.3.0
psygnal: 0.11.1
npe2: 0.7.7
pydantic: 2.9.2

OpenGL:
  - GL version:  2.1 Metal - 89.3
  - MAX_TEXTURE_SIZE: 16384
  - GL_MAX_3D_TEXTURE_SIZE: 2048

Screens:
  - screen 1: resolution 3200x1800, scale 2.0
  - screen 2: resolution 1800x1169, scale 2.0

Optional:
  - numba: 0.60.0
  - triangle not installed
  - napari-plugin-manager: 0.1.3

Settings path:
  - /Users/jni/Library/Application Support/napari/all_f206df4881e2999baa22e6df448393db299c70d6/settings.yaml
Plugins:
  - affinder: 0.4.0 (10 contributions)
  - midi-app-controller: 0.0.13.dev6+g180a6ba (2 contributions)
  - napari: 0.5.5 (81 contributions)
  - napari-console: 0.1.1 (0 contributions)
  - napari-defdap: 0.1.dev30+gb77d57b.d20241204 (8 contributions)
  - napari-ome-zarr: 0.6.1 (2 contributions)
  - napari-signal-selector: 0.0.6 (10 contributions)
  - napari-svg: 0.2.0 (2 contributions)
  - skan: 0.12.1 (4 contributions)
  - zarpaint: 0.4.0 (19 contributions)
```

**Comment by andy-sweet** [comment]
There is a [unit test for `LayerSlicer`](https://github.com/napari/napari/blob/fcb31c14249e7ef1df30fbc98bc4d2ec335f6875/napari/components/_tests/test_layer_slicer.py#L248) to handle this case.

But the usage in the application is a little different because it relies on [the event that's emitted on the task/thread](https://github.com/napari/napari/blob/fcb31c14249e7ef1df30fbc98bc4d2ec335f6875/napari/components/_layer_slicer.py#L281) rather than resolving the future returned.

The simplest fix I can think of now is to move the event emission to the [`_on_slice_done` callback](https://github.com/napari/napari/blob/fcb31c14249e7ef1df30fbc98bc4d2ec335f6875/napari/components/_layer_slicer.py#L284). I have a vague memory that was done initially and caused some other problems (I will try to recall those), so may be the reason for this issue/regression.

**Comment by andy-sweet** [comment]
Also, the best place to add a reproducing test is probably [`test_async_slicing.py`](https://github.com/napari/napari/blob/fcb31c14249e7ef1df30fbc98bc4d2ec335f6875/napari/_qt/_tests/test_async_slicing.py#L1), which contains heavier integration tests, which should generally match the behavior of the application.

**Comment by jni** [comment]
Thanks for the hints @andy-sweet! 🙏

**Comment by psobolewskiPhD** [comment]
I ran into this error I think recently using bioformats. There was a crash on the Java side and no error in napari, just spinning loading indicator.
