### ISSUE TITLE
Passing a numpy array as the "scale" argument crashes napari

### ISSUE THREAD

**Issue by jni** [napari/napari#751]
## 🐛 Bug

This one is probably my fault for promoting the `x = y or default_value` syntax for None arguments: it crashes when `y` is a NumPy array. :grimacing: Now, when you pass a NumPy array as the `scale=` parameter, it crashes with `ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()`

## To Reproduce

```python
import numpy as np
from skimage import data, util
import napari


camera = util.img_as_float(data.camera())

with napari.gui_qt():
    napari.view_image(camera, scale=np.array([1, 1]))
```

```pytb
Traceback (most recent call last):
  File "test_array_spacing.py", line 9, in <module>
    napari.view_image(camera, scale=np.array([1, 1]))
  File "/home/jni/projects/napari/napari/view_layers.py", line 130, in view_image
    path=path,
  File "/home/jni/projects/napari/napari/components/viewer_model.py", line 512, in add_image
    visible=visible,
  File "/home/jni/projects/napari/napari/layers/image/image.py", line 163, in __init__
    visible=visible,
  File "/home/jni/projects/napari/napari/layers/base/base.py", line 133, in __init__
    self._scale = scale or [1] * ndim
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

## Expected behavior

It should work the same as if the input was a list.

**Comment by sofroniewn** [comment]
yup, should be fixed
