### ISSUE TITLE
Python 3.8 not currently supported with PySide2

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#766]
## 🐛 Bug

As noted by @kne42 in https://github.com/napari/napari/issues/729#issuecomment-561836861 it seems like we currently do not have support for Python 3.8 and get the following error:

```
[I 21:03:54.961 NotebookApp] Adapting from protocol version 5.1 (kernel 74092921-9466-477e-b15a-3074468ac75b) to 5.3 (client).
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/home/sebi06/anaconda3/envs/napari/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3319, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-1-e580eceeb872>", line 2, in <module>
    import napari
  File "/home/sebi06/anaconda3/envs/napari/lib/python3.8/site-packages/napari/__init__.py", line 29, in <module>
    from .viewer import Viewer
  File "/home/sebi06/anaconda3/envs/napari/lib/python3.8/site-packages/napari/viewer.py", line 3, in <module>
    from napari._qt.qt_update_ui import QtUpdateUI
  File "/home/sebi06/anaconda3/envs/napari/lib/python3.8/site-packages/napari/_qt/__init__.py", line 1, in <module>
    from .qt_range_slider import QHRangeSlider, QVRangeSlider
  File "/home/sebi06/anaconda3/envs/napari/lib/python3.8/site-packages/napari/_qt/qt_range_slider.py", line 316, in <module>
    class QHRangeSlider(QRangeSlider):
TypeError: 'Shiboken.ObjectType' object is not iterable
```

what's interesting is this in one of our custom Qt elements. Maybe @AhmetCanSolak has an idea on how to fix and then we'd be `3.8` compatible

**Comment by kne42** [comment]
See [this reply](https://bugreports.qt.io/browse/PYSIDE-1140?focusedCommentId=486074&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-486074) from a Qt developer that says that they plan to provide Python 3.8 compatibility in Qt 5.14.

**Comment by sofroniewn** [comment]
Python 3.8 support has been added with #878
