### ISSUE TITLE
Windows RDP Open GL Vispy error: AttributeError: function 'glBindFramebuffer' not found

### ISSUE THREAD

**Issue by MaximilianHoffmann** [napari/napari#804]
## ❓ Questions and Help

Hi, I get an error:
`AttributeError: function 'glBindFramebuffer' not found`

when opening Napari on a Windows 10 machine via remote desktop (Geforce GTX 960). 
I have used Napari on other windows machines via RDP an cannot really spot the difference.
I know, that there are problems with OpenGL/RDP on Windows, though.
Are there any work arounds?

**Comment by tlambert03** [comment]
I'm actually more surprised that you've been able to get to work on other systems!  I've never had success on RDP, and I can definitely replicate the GL context issues that you see here (full stack trace below just for sake of completeness, using RDP to a Win10 computer).

If you have a moment, could describe the environments where it _did_ work a little more?  For instance, are you certain it was RDP and not VNC or a teamviewer-like thing?  OS, GPU, driver versions?  You can use the napari `Help > napari info`  menu to get and paste relevant info here.

```
(napdev) python\napari>napari
Traceback (most recent call last):
  File "miniconda3\envs\napdev\lib\site-packages\vispy\app\backends\_qt.py", line 818, in paintGL
    self._vispy_canvas.events.draw(region=None)
  File "miniconda3\envs\napdev\lib\site-packages\vispy\util\event.py", line 455, in __call__
    self._invoke_callback(cb, event)
  File "miniconda3\envs\napdev\lib\site-packages\vispy\util\event.py", line 475, in _invoke_callback
    self, cb_event=(cb, event))
  File "miniconda3\envs\napdev\lib\site-packages\vispy\util\event.py", line 471, in _invoke_callback
    cb(event)
  File "miniconda3\envs\napdev\lib\site-packages\vispy\gloo\context.py", line 175, in flush_commands
    self.shared.parser.parse([('CURRENT', 0, fbo)])
  File "miniconda3\envs\napdev\lib\site-packages\vispy\gloo\glir.py", line 819, in parse
    self._parse(command)
  File "miniconda3\envs\napdev\lib\site-packages\vispy\gloo\glir.py", line 743, in _parse
    self._gl_initialize()
  File "miniconda3\envs\napdev\lib\site-packages\vispy\gloo\glir.py", line 851, in _gl_initialize
    if this_version < '2.1':
  File "miniconda3\envs\napdev\lib\distutils\version.py", line 52, in __lt__
    c = self._cmp(other)
  File "miniconda3\envs\napdev\lib\distutils\version.py", line 335, in _cmp
    if self.version == other.version:
AttributeError: 'LooseVersion' object has no attribute 'version'
Traceback (most recent call last):
  File "miniconda3\envs\napdev\lib\site-packages\vispy\gloo\gl\_gl2.py", line 53, in glBindFramebuffer
    nativefunc = glBindFramebuffer._native
AttributeError: 'function' object has no attribute '_native'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "miniconda3\envs\napdev\lib\site-packages\vispy\gloo\gl\gl2.py", line 72, in _get_gl_func
    func = getattr(_lib, name)
  File "miniconda3\envs\napdev\lib\ctypes\__init__.py", line 377, in __getattr__
    func = self.__getitem__(name)
  File "miniconda3\envs\napdev\lib\ctypes\__init__.py", line 382, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'glBindFramebuffer' not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "miniconda3\envs\napdev\lib\site-packages\vispy\app\backends\_qt.py", line 818, in paintGL
    self._vispy_canvas.events.draw(region=None)
  File "miniconda3\envs\napdev\lib\site-packages\vispy\util\event.py", line 455, in __call__
    self._invoke_callback(cb, event)
  File "miniconda3\envs\napdev\lib\site-packages\vispy\util\event.py", line 475, in _invoke_callback
    self, cb_event=(cb, event))
  File "miniconda3\envs\napdev\lib\site-packages\vispy\util\event.py", line 471, in _invoke_callback
    cb(event)
  File "miniconda3\envs\napdev\lib\site-packages\vispy\gloo\context.py", line 175, in flush_commands
    self.shared.parser.parse([('CURRENT', 0, fbo)])
  File "miniconda3\envs\napdev\lib\site-packages\vispy\gloo\glir.py", line 819, in parse
    self._parse(command)
  File "miniconda3\envs\napdev\lib\site-packages\vispy\gloo\glir.py", line 745, in _parse
    gl.glBindFramebuffer(gl.GL_FRAMEBUFFER, args[0])
  File "miniconda3\envs\napdev\lib\site-packages\vispy\gloo\gl\_gl2.py", line 55, in glBindFramebuffer
    nativefunc = glBindFramebuffer._native = _get_gl_func("glBindFramebuffer", None, (ctypes.c_uint, ctypes.c_uint,))
  File "miniconda3\envs\napdev\lib\site-packages\vispy\gloo\gl\gl2.py", line 87, in _get_gl_func
    raise RuntimeError('Using %s with no OpenGL context.' % name)
RuntimeError: Using glBindFramebuffer with no OpenGL context.
Traceback (most recent call last):
  File "miniconda3\envs\napdev\lib\site-packages\vispy\gloo\gl\_gl2.py", line 53, in glBindFramebuffer
    nativefunc = glBindFramebuffer._native
AttributeError: 'function' object has no attribute '_native'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "miniconda3\envs\napdev\lib\site-packages\vispy\gloo\gl\gl2.py", line 72, in _get_gl_func
    func = getattr(_lib, name)
  File "miniconda3\envs\napdev\lib\ctypes\__init__.py", line 377, in __getattr__
    func = self.__getitem__(name)
  File "miniconda3\envs\napdev\lib\ctypes\__init__.py", line 382, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'glBindFramebuffer' not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "miniconda3\envs\napdev\lib\site-packages\vispy\app\backends\_qt.py", line 818, in paintGL
    self._vispy_canvas.events.draw(region=None)
  File "miniconda3\envs\napdev\lib\site-packages\vispy\util\event.py", line 455, in __call__
    self._invoke_callback(cb, event)
  File "miniconda3\envs\napdev\lib\site-packages\vispy\util\event.py", line 475, in _invoke_callback
    self, cb_event=(cb, event))
  File "miniconda3\envs\napdev\lib\site-packages\vispy\util\event.py", line 471, in _invoke_callback
    cb(event)
  File "miniconda3\envs\napdev\lib\site-packages\vispy\gloo\context.py", line 175, in flush_commands
    self.shared.parser.parse([('CURRENT', 0, fbo)])
  File "miniconda3\envs\napdev\lib\site-packages\vispy\gloo\glir.py", line 819, in parse
    self._parse(command)
  File "miniconda3\envs\napdev\lib\site-packages\vispy\gloo\glir.py", line 745, in _parse
    gl.glBindFramebuffer(gl.GL_FRAMEBUFFER, args[0])
  File "miniconda3\envs\napdev\lib\site-packages\vispy\gloo\gl\_gl2.py", line 55, in glBindFramebuffer
    nativefunc = glBindFramebuffer._native = _get_gl_func("glBindFramebuffer", None, (ctypes.c_uint, ctypes.c_uint,))
  File "miniconda3\envs\napdev\lib\site-packages\vispy\gloo\gl\gl2.py", line 87, in _get_gl_func
    raise RuntimeError('Using %s with no OpenGL context.' % name)
RuntimeError: Using glBindFramebuffer with no OpenGL context.
```

```
Platform: Windows-10-10.0.17763-SP0
Python:   3.7.5 (default, Oct 31 2019, 15:18:51) [MSC v.1916 64 bit (AMD64)]
Backend:  PySide2
GL version:  ''
MAX_TEXTURE_SIZE: ()
```

**Comment by sofroniewn** [comment]
I'm afraid I don't know any work arounds right now, you might want to poke around the vispy issue tracker https://github.com/vispy/vispy/issues, I know there have been some problems with remote windows that have been reported there before. The error messages might be slightly different though as I think things used to fail at a different point in older versions of vispy.

**Comment by MaximilianHoffmann** [comment]
The Napari Info is
```napari, 0.2.6
Qt, 5.12.5
NumPy, 1.17.4
SciPy, 1.3.1
VisPy, 0.6.3
scikit-image, 0.16.2

Platform: Windows-10-10.0.18362-SP0
Python:   3.7.5 (default, Oct 31 2019, 15:18:51) [MSC v.1916 64 bit (AMD64)]
Backend:  PyQt5
GL version:  '4.6.0 NVIDIA 431.86'
MAX_TEXTURE_SIZE: 32768
```

I think it is the RDP, since I am using the Microsoft Remote Desktop client on my macbook, and have no VNC installed on the other computer

Btw, thanks for this great tool//

**Comment by tlambert03** [comment]
cool, and that one works?

**Comment by AhmetCanSolak** [comment]
@MaximilianHoffmann I have heard before that openGL has issues with RDP. Could you please try with VNC? It suppose to work.

**Comment by MaximilianHoffmann** [comment]
@tlambert03  Yes, somehow this one works. (It only has an NIVIDA Quadro P2000, could this make the difference?)

I tried nomachine on the other PC and it did not work either, but I'll try to also try VNC.

**Comment by cgohlke** [comment]
> Hi, I get an error:
AttributeError: function 'glBindFramebuffer' not found 
> when opening Napari on a Windows 10 machine via remote desktop (Geforce GTX 960).

> Yes, somehow this one works. (It only has an NIVIDA Quadro P2000, could this make the difference?)

Yes, NIVIDA doesn't "support" OpenGL + RDP on GeForce cards, only on Quadro cards.

Microsoft's software OpenGL driver only supports OpenGL 1.1, which is too old for napari.

As a workaround, try another OpenGL DLL that renders software-only (e.g. MESA, QT5/PyQT5 includes `opengl32sw.dll`) or through DirectX ([ANGLE](https://github.com/google/angle)), or try a different remote desktop protocol (VNC, TeamViewer). I have not tried any of these with napari myself...

**Comment by VolkerH** [comment]
Just encountered the same issue on an OpenStack Windows virtual machine instance: 

![image](https://user-images.githubusercontent.com/2210044/82792448-c71aa180-9eb2-11ea-9ab9-f75e1e97c49f.png)

The machine supposedly has an Nvidia P4.
I will have to check whether the workarounds suggested by @cgohlke work.

Also pinging @jni : this is on NeCTAR

**Comment by cgohlke** [comment]
Nvidia has since released a [tool to enable OpenGL over RDP](https://developer.nvidia.com/nvidia-opengl-rdp), which works well with GeForce cards on Windows 10. Maybe it works for P4 cards on Windows Server too?

Windows Server 2016 might need the “Use the hardware default graphics adapter for all Remote Desktop Services sessions” group policy setting enabled in "Local Computer Policy\Computer Configuration\Administrative Templates\Windows Components\Remote Desktop Services\Remote Desktop Session Host\Remote Session Environment".

I have tried the software OpenGL from Qt5 (opengl32sw.dll): it does not support 3D textures required by napari.

**Comment by VolkerH** [comment]
Thanks for these additional hints @cgohlke. 
My colleague from the IT department installed the nvidia tool you linked to above. So far, no success.

I'm not sure whether this driver would work anyway as not only are we accessing a desktop machine remotely, we're accessing a VM instance remotely.  Imaris also crashes on that VM as soon as a volume is loaded. My colleague from our IT research software team was busy today but he may have some other ideas to try out. 

However, I just heard from @constantinpape that napari also has the OpenGL issue on vmware horizon Windows VMs with GPU acceleration, a platform that runs Imaris just fine.

**Comment by berl** [comment]
just chiming in here that I am running into a likely similar problem with XRDP on a linux host:
```
WARNING: failed to initialize XRandr

WARNING: XKeyboard extension not present on the X server

WARNING: qglx_findConfig: Failed to finding matching FBConfig for QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 0, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize 0, stencilBufferSize 0, samples 0, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)

WARNING: qglx_findConfig: Failed to finding matching FBConfig for QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 0, redBufferSize 1, greenBufferSize 1, blueBufferSize 1, alphaBufferSize 0, stencilBufferSize 0, samples 0, swapBehavior QSurfaceFormat::SingleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)

WARNING: Could not initialize GLX
Aborted (core dumped)
```

I'll look into the nvidia fix mentioned above although I never have fun messing around with nvidia drivers

**Comment by VolkerH** [comment]
Hi @berl 

not familiar with XRDP, but I have also experienced the `XKeyboard` extension error with tightvnc (linux server)/ turbovnc (client). It seems to affect all PyQt (and likely all Qt-based) applications and I also noticed it in VSCode. It does not mean the keyboard won't work at all, but certain keyboard combinations don't work. That's why I have given up using napari remotely on turbovnc on a Linux box. (turbovnc has no problem with GL though, so if you find a workaround for the keyboard issues it may be an option).

**Comment by berl** [comment]
@VolkerH  thanks for the note- I dug around a bit last night and came to a similar conclusion. I don't have the time / chops to mess with the various configs on the host side so I'll come back to this if the underlying issues get sorted out.  I have other workarounds I can use for debugging and building with napari (i.e. do the work on local machine) so it's not exactly blocking me.

**Comment by sofroniewn** [comment]
Hi all, I just wanted to let people know that we merged a PR with a docker file last month, see https://github.com/napari/napari/pull/1496. I'm not sure if that will be helpful here or if people have made further advances on this issue. More feedback and discussion is welcome, but if no one else has anything to add right now then I will close this issue soon. Thanks all!
