### ISSUE TITLE
Support for n5 

### ISSUE THREAD

**Issue by howff** [napari/napari#805]
## 🐛 Bug

Trying to display a zarr/n5 image gives the error
`ValueError: Could not find a format to read the specified file in mode 'i'`

It does display something but looks more like a thumbnail as I can't zoom in.
But the error message keeps reoccurring.

## Environment

```
napari, 0.2.6
Qt, 5.13.2
NumPy, 1.17.4
SciPy, 1.3.3
VisPy, 0.6.3
scikit-image, 0.16.2
Platform: Linux-3.10.0-957.21.3.el7.x86_64-x86_64-with-centos-7.6.1810-Core
Python:   3.6.8 (default, Aug  7 2019, 17:28:10)  [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
Backend:  PySide2
GL version:  '2.1 Mesa 18.0.5'
MAX_TEXTURE_SIZE: 8192
```

## Additional context

```
$ napari /data/testdata/1.raw
Traceback (most recent call last):
  File "/home/me/src/napari/lib/python3.6/site-packages/napari/_qt/qt_dims.py", line 334, in slider_change_listener
    self.dims.set_point(axis, value)
  File "/home/me/src/napari/lib/python3.6/site-packages/napari/components/dims.py", line 353, in set_point
    self.events.axis(axis=axis, value=value)
  File "/home/me/src/napari/lib/python3.6/site-packages/napari/util/event.py", line 508, in __call__
    self._invoke_callback(cb, event)
  File "/home/me/src/napari/lib/python3.6/site-packages/napari/util/event.py", line 529, in _invoke_callback
    cb_event=(cb, event),
  File "/home/me/src/napari/lib/python3.6/site-packages/napari/util/event.py", line 523, in _invoke_callback
    cb(event)
  File "/home/me/src/napari/lib/python3.6/site-packages/napari/components/viewer_model.py", line 90, in <lambda>
    self.dims.events.axis.connect(lambda e: self._update_layers())
  File "/home/me/src/napari/lib/python3.6/site-packages/napari/components/viewer_model.py", line 1024, in _update_layers
    layer.dims.set_point(axis, point)
  File "/home/me/src/napari/lib/python3.6/site-packages/napari/components/dims.py", line 353, in set_point
    self.events.axis(axis=axis, value=value)
  File "/home/me/src/napari/lib/python3.6/site-packages/napari/util/event.py", line 508, in __call__
    self._invoke_callback(cb, event)
  File "/home/me/src/napari/lib/python3.6/site-packages/napari/util/event.py", line 529, in _invoke_callback
    cb_event=(cb, event),
  File "/home/me/src/napari/lib/python3.6/site-packages/napari/util/event.py", line 523, in _invoke_callback
    cb(event)
  File "/home/me/src/napari/lib/python3.6/site-packages/napari/layers/base/base.py", line 176, in <lambda>
    self.dims.events.axis.connect(lambda e: self._set_view_slice())
  File "/home/me/src/napari/lib/python3.6/site-packages/napari/layers/image/image.py", line 482, in _set_view_slice
    image = np.asarray(self.data[self.dims.indices]).transpose(order)
  File "/home/me/src/napari/lib/python3.6/site-packages/numpy/core/_asarray.py", line 85, in asarray
    return array(a, dtype, copy=False, order=order)
  File "/home/me/src/napari/lib/python3.6/site-packages/dask/array/core.py", line 1314, in __array__
    x = self.compute()
  File "/home/me/src/napari/lib/python3.6/site-packages/dask/base.py", line 165, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/home/me/src/napari/lib/python3.6/site-packages/dask/base.py", line 436, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/home/me/src/napari/lib/python3.6/site-packages/dask/threaded.py", line 81, in get
    **kwargs
  File "/home/me/src/napari/lib/python3.6/site-packages/dask/local.py", line 486, in get_async
    raise_exception(exc, tb)
  File "/home/me/src/napari/lib/python3.6/site-packages/dask/local.py", line 316, in reraise
    raise exc
  File "/home/me/src/napari/lib/python3.6/site-packages/dask/local.py", line 222, in execute_task
    result = _execute_task(task, data)
  File "/home/me/src/napari/lib/python3.6/site-packages/dask/core.py", line 118, in _execute_task
    args2 = [_execute_task(a, cache) for a in args]
  File "/home/me/src/napari/lib/python3.6/site-packages/dask/core.py", line 118, in <listcomp>
    args2 = [_execute_task(a, cache) for a in args]
  File "/home/me/src/napari/lib/python3.6/site-packages/dask/core.py", line 118, in _execute_task
    args2 = [_execute_task(a, cache) for a in args]
  File "/home/me/src/napari/lib/python3.6/site-packages/dask/core.py", line 118, in <listcomp>
    args2 = [_execute_task(a, cache) for a in args]
  File "/home/me/src/napari/lib/python3.6/site-packages/dask/core.py", line 119, in _execute_task
    return func(*args2)
  File "/home/me/src/napari/lib/python3.6/site-packages/skimage/io/_io.py", line 48, in imread
    img = call_plugin('imread', fname, plugin=plugin, **plugin_args)
  File "/home/me/src/napari/lib/python3.6/site-packages/skimage/io/manage_plugins.py", line 210, in call_plugin
    return func(*args, **kwargs)
  File "/home/me/src/napari/lib/python3.6/site-packages/skimage/io/_plugins/imageio_plugin.py", line 10, in imread
    return np.asarray(imageio_imread(*args, **kwargs))
  File "/home/me/src/napari/lib/python3.6/site-packages/imageio/core/functions.py", line 264, in imread
    reader = read(uri, format, "i", **kwargs)
  File "/home/me/src/napari/lib/python3.6/site-packages/imageio/core/functions.py", line 182, in get_reader
    "Could not find a format to read the specified file " "in mode %r" % mode
ValueError: Could not find a format to read the specified file in mode 'i'
```

**Comment by sofroniewn** [comment]
I think right now we're looking for zarr files to have the `.zarr` extension - see here https://github.com/napari/napari/blob/d758a0bf154d7c5f30ba53b1c48a805cd8409d78/napari/util/io.py#L53 and here https://github.com/napari/napari/blob/d758a0bf154d7c5f30ba53b1c48a805cd8409d78/napari/util/io.py#L73

If you can rename your file from `.raw` to `.zarr` for testing purposes I'm curious what happens.

You can also load in your data from a python script, and use `dask` or `zarr` explicitly but that is more work.

Thanks for flagging this, I think we can improve the situation here

**Comment by howff** [comment]
Ah, sorry, it's n5 not zarr. When I try the napari gui with "pyramid.n5" (which is a directory) it just crashes with the error given above. That directory contains attributes.json with "n5": "2.0.0" if it helps.

**Comment by jni** [comment]
Ah! Right now we don't support `.n5` at all in our IO, so that makes more sense. I suggest using a Python script like [this one](https://github.com/sofroniewn/image-demos/blob/master/examples/AOLLSM.py), but replacing zarr with an n5 IO library such as [z5](https://pypi.org/project/z5/)...

**Comment by d-v-b** [comment]
zarr natively supports N5: https://github.com/zarr-developers/zarr-python/blob/c959d11821da3b3e2b46be9dbac53e358d2a19a6/zarr/n5.py

**Comment by jni** [comment]
we use `dask.array.from_zarr` rather than zarr directly. There's a few advantages... =\

**Comment by d-v-b** [comment]
I think it should be easy to get N5-reading functionality added to `from_zarr`, i'll look into writing a PR soon

**Comment by howff** [comment]
Thanks for the explanations, and thanks d-v-b for the offer of code!

I have got it sort-of working so far with this:
```
filename  = 'test1.zarr/pyramid.n5' 
import numpy as np 
from napari import Viewer, gui_qt 
import zarr 
data = zarr.open(filename, mode='r') # there's an is_pyramid=True option somewhere? 
print(data[0].shape) # each pyramid level N is in data[N] 
with gui_qt(): 
    Viewer().add_image(data[0]) # can't use rgb=True because shape is (3,x,y) but needs to be (x,y,3) 
```

A couple of things to note:
* it doesn't auto-detect the pyramid levels
* it doesn't do RGB (dimensions in the wrong order?)

**Comment by jakirkham** [comment]
FWIW [`from_zarr`]( https://docs.dask.org/en/latest/array-api.html#dask.array.from_zarr ) does accept a [`MutableMapping`]( https://docs.python.org/3/library/collections.abc.html#collections.abc.MutableMapping ) or an [`Array`]( https://zarr.readthedocs.io/en/stable/api/core.html ) as well. So if one is able to construct an [`N5Strore`]( https://zarr.readthedocs.io/en/stable/api/n5.html#zarr.n5.N5Store ) with Zarr for their data, this could be passed in along with the path to the `Array`. Alternatively one could just select out the Zarr `Array` from the `N5Store` themselves and pass this in. So one could imagine code like this (note I've not tried this 😉)...

```python
import dask.array
import napari
import zarr

s = zarr.N5Store("stuff/data.n5")
d = s["group/array"]
a = dask.array.from_zarr(d)

with napari.gui_qt():
    viewer = napari.Viewer()
    layer = v.add_image(a)
```

**Comment by clbarnes** [comment]
Is this issue still relevant? There is a Zarr V3 extension codec (by me) which defines how to read N5 default-mode data which is also implemented (by me) in python and rust, along with a storage layer which will on-the-fly convert N5 metadata to zarr metadata. Not every compressor is supported (but the most common ones are) and it would be a bigger lift to understand e.g. bigdataviewer multiscale metadata, but basic viewing should be very feasible.

Would this be worth its own plugin or is it better to fold in to regular zarr support?

**Comment by psobolewskiPhD** [comment]
Good question? 
I'm not at all familiar with n5, so I'm not sure about the specifics, but generally, it seems like programmatically n5 can be viewed but there is no plugin to make drag-and-drop work? See also: https://forum.image.sc/t/opening-n5-in-napari/96565/5

In general I think we've preferred to have specifics/niche elements in plugins. So e.g. the builtin reader can open zarr arrays -- rather bare bones functionality -- but you need napari-ome-zarr for the metadata, etc. handling.
Likewise the builtin reader uses tifffile, but you need napari-tiff for multiscales and (in progress) metadata handling.

I'm not sure where n5 fits in that schema, but I don't think it's nearly as broadly used as tiff or zarr to warrant adding it to builtins? Certainly a PR can sway that 😉 
So for me a plugin feels like the right spot?

**Comment by clbarnes** [comment]
Sounds right to me; N5 world could also come with its own multiscale schemas https://github.com/janelia-cellmap/schemas/blob/master/multiscale.md which add too much complexity for mainline. Simply opening N5 arrays as plain arrays would only add a couple of lines to the existing zarr support, but would add zarr-n5 as a dependency so a plugin is probably best. I have started a prototype with the goal of supporting the current n5-viewer multiscale metadata (which is also generated by n5-spark).
