### ISSUE TITLE
picking label outside 

### ISSUE THREAD

**Issue by tlambert03** [napari/napari#857]
## 🐛 Bug
Tiny little bug that I can't fix now but don't want to forget.  When using "pick mode" in a label layer, if you click outside the image, you get:
```
Traceback (most recent call last):
  File "~/miniconda3/envs/napdev/lib/python3.7/site-packages/vispy/app/backends/_qt.py", line 447, in mousePressEvent
    modifiers=self._modifiers(ev),
  File "~/miniconda3/envs/napdev/lib/python3.7/site-packages/vispy/app/base.py", line 181, in _vispy_mouse_press
    ev = self._vispy_canvas.events.mouse_press(**kwargs)
  File "~/miniconda3/envs/napdev/lib/python3.7/site-packages/vispy/util/event.py", line 455, in __call__
    self._invoke_callback(cb, event)
  File "~/miniconda3/envs/napdev/lib/python3.7/site-packages/vispy/util/event.py", line 475, in _invoke_callback
    self, cb_event=(cb, event))
  File "~/miniconda3/envs/napdev/lib/python3.7/site-packages/vispy/util/event.py", line 471, in _invoke_callback
    cb(event)
  File "~/napari/napari/_qt/qt_viewer.py", line 338, in on_mouse_press
    self.layer_to_visual[layer].on_mouse_press(event)
  File "~/napari/napari/_vispy/vispy_base_layer.py", line 194, in on_mouse_press
    self.layer.on_mouse_press(event)
  File "~/napari/napari/layers/labels/labels.py", line 542, in on_mouse_press
    self.selected_label = self._value
  File "~/napari/napari/layers/labels/labels.py", line 270, in selected_label
    if selected_label < 0:
TypeError: '<' not supported between instances of 'NoneType' and 'int'
```

**Comment by sofroniewn** [comment]
ah good catch - should be fixed
