### ISSUE TITLE
Error when locking shape aspect ratio with shift 

### ISSUE THREAD

**Issue by tlambert03** [napari/napari#870]
## 🐛 Bug
haven't looked too far into yet, but just want to note it somewhere:
In `examples/mouse_drag_callback.py`, if I try to use the `Shift` key to constrain the aspect ratio of a shape, I get the following error in `hold_to_lock_aspect_ratio`:

```
Traceback (most recent call last):
  File "napdev/lib/python3.7/site-packages/vispy/app/backends/_qt.py", line 502, in keyPressEvent
    self._keyEvent(self._vispy_canvas.events.key_press, ev)
  File "napdev/lib/python3.7/site-packages/vispy/app/backends/_qt.py", line 551, in _keyEvent
    func(native=ev, key=key, text=text_type(ev.text()), modifiers=mod)
  File "napdev/lib/python3.7/site-packages/vispy/util/event.py", line 455, in __call__
    self._invoke_callback(cb, event)
  File "napdev/lib/python3.7/site-packages/vispy/util/event.py", line 475, in _invoke_callback
    self, cb_event=(cb, event))
  File "napdev/lib/python3.7/site-packages/vispy/util/event.py", line 471, in _invoke_callback
    cb(event)
  File "napari/napari/_qt/qt_viewer.py", line 394, in on_key_press
    next(gen)
  File "napari/napari/layers/shapes/keybindings.py", line 39, in hold_to_lock_aspect_ratio
    layer._move(layer.coordinates[layer.dims.displayed])
TypeError: tuple indices must be integers or slices, not list
```

**Comment by sofroniewn** [comment]
I can work on a fix for this for `0.2.10`, should be a one-liner
