### ISSUE TITLE
Selecting points in 3D

### ISSUE THREAD

**Issue by HagaiHargil** [napari/napari#901]
## 🐛 Bug

When I select a 3D point while `ndisplay == 2` and then try to change the viewer to a 3D one napari crashes.

## To Reproduce
```python
with napari.gui_qt():
    v = napari.view_points(np.array([[1, 0, 0], [0, 0, 1]]))
```
Then select a point with the cursor and try to change the display to a 3D one.

## Expected behavior

I expect napari to transition to a 3D view of the data without crashing. When I come back to the 2D view it would be nice if the points would still be highlighted. This is not currently the case with 2D points, though.

## Environment

Python 3.7, napari 0.2.10

## Additional context
```
WARNING: Traceback (most recent call last):
  File "/home/hagai/.conda/envs/ncd/lib/python3.7/site-packages/napari/_qt/qt_viewer_buttons.py", line 173, in <lambda>
    lambda state=self: self.change_ndisplay(state)
  File "/home/hagai/.conda/envs/ncd/lib/python3.7/site-packages/napari/_qt/qt_viewer_buttons.py", line 178, in change_ndisplay
    self.viewer.dims.ndisplay = 3
  File "/home/hagai/.conda/envs/ncd/lib/python3.7/site-packages/napari/components/dims.py", line 296, in ndisplay
    self.events.ndisplay()
  File "/home/hagai/.conda/envs/ncd/lib/python3.7/site-packages/napari/utils/event.py", line 508, in __call__
    self._invoke_callback(cb, event)
  File "/home/hagai/.conda/envs/ncd/lib/python3.7/site-packages/napari/utils/event.py", line 529, in _invoke_callback
    cb_event=(cb, event),
  File "/home/hagai/.conda/envs/ncd/lib/python3.7/site-packages/napari/utils/event.py", line 523, in _invoke_callback
    cb(event)
  File "/home/hagai/.conda/envs/ncd/lib/python3.7/site-packages/napari/components/viewer_model.py", line 88, in <lambda>
    self.dims.events.ndisplay.connect(lambda e: self._update_layers())
  File "/home/hagai/.conda/envs/ncd/lib/python3.7/site-packages/napari/components/viewer_model.py", line 1037, in _update_layers
    layer.dims.ndisplay = self.dims.ndisplay
  File "/home/hagai/.conda/envs/ncd/lib/python3.7/site-packages/napari/components/dims.py", line 296, in ndisplay
    self.events.ndisplay()
  File "/home/hagai/.conda/envs/ncd/lib/python3.7/site-packages/napari/utils/event.py", line 508, in __call__
    self._invoke_callback(cb, event)
  File "/home/hagai/.conda/envs/ncd/lib/python3.7/site-packages/napari/utils/event.py", line 529, in _invoke_callback
    cb_event=(cb, event),
  File "/home/hagai/.conda/envs/ncd/lib/python3.7/site-packages/napari/utils/event.py", line 523, in _invoke_callback
    cb(event)
  File "/home/hagai/.conda/envs/ncd/lib/python3.7/site-packages/napari/layers/base/base.py", line 180, in <lambda>
    self.dims.events.ndisplay.connect(lambda e: self._update_dims())
  File "/home/hagai/.conda/envs/ncd/lib/python3.7/site-packages/napari/layers/base/base.py", line 383, in _update_dims
    self.refresh()
  File "/home/hagai/.conda/envs/ncd/lib/python3.7/site-packages/napari/layers/base/base.py", line 600, in refresh
    self._set_view_slice()
  File "/home/hagai/.conda/envs/ncd/lib/python3.7/site-packages/napari/layers/points/points.py", line 654, in _set_view_slice
    self._selected_box = self.interaction_box(self._selected_view)
  File "/home/hagai/.conda/envs/ncd/lib/python3.7/site-packages/napari/layers/points/points.py", line 480, in interaction_box
    data = points_to_squares(data, size)
  File "/home/hagai/.conda/envs/ncd/lib/python3.7/site-packages/napari/layers/points/points.py", line 972, in points_to_squares
    points + np.sqrt(2) / 2 * np.array([sizes, sizes]).T,
ValueError: operands could not be broadcast together with shapes (1,3) (1,2)
WARNING:vispy:Traceback (most recent call last):
  File "/home/hagai/.conda/envs/ncd/lib/python3.7/site-packages/napari/_qt/qt_viewer_buttons.py", line 173, in <lambda>
    lambda state=self: self.change_ndisplay(state)
  File "/home/hagai/.conda/envs/ncd/lib/python3.7/site-packages/napari/_qt/qt_viewer_buttons.py", line 178, in change_ndisplay
    self.viewer.dims.ndisplay = 3
  File "/home/hagai/.conda/envs/ncd/lib/python3.7/site-packages/napari/components/dims.py", line 296, in ndisplay
    self.events.ndisplay()
  File "/home/hagai/.conda/envs/ncd/lib/python3.7/site-packages/napari/utils/event.py", line 508, in __call__
    self._invoke_callback(cb, event)
  File "/home/hagai/.conda/envs/ncd/lib/python3.7/site-packages/napari/utils/event.py", line 529, in _invoke_callback
    cb_event=(cb, event),
  File "/home/hagai/.conda/envs/ncd/lib/python3.7/site-packages/napari/utils/event.py", line 523, in _invoke_callback
    cb(event)
  File "/home/hagai/.conda/envs/ncd/lib/python3.7/site-packages/napari/components/viewer_model.py", line 88, in <lambda>
    self.dims.events.ndisplay.connect(lambda e: self._update_layers())
  File "/home/hagai/.conda/envs/ncd/lib/python3.7/site-packages/napari/components/viewer_model.py", line 1037, in _update_layers
    layer.dims.ndisplay = self.dims.ndisplay
  File "/home/hagai/.conda/envs/ncd/lib/python3.7/site-packages/napari/components/dims.py", line 296, in ndisplay
    self.events.ndisplay()
  File "/home/hagai/.conda/envs/ncd/lib/python3.7/site-packages/napari/utils/event.py", line 508, in __call__
    self._invoke_callback(cb, event)
  File "/home/hagai/.conda/envs/ncd/lib/python3.7/site-packages/napari/utils/event.py", line 529, in _invoke_callback
    cb_event=(cb, event),
  File "/home/hagai/.conda/envs/ncd/lib/python3.7/site-packages/napari/utils/event.py", line 523, in _invoke_callback
    cb(event)
  File "/home/hagai/.conda/envs/ncd/lib/python3.7/site-packages/napari/layers/base/base.py", line 180, in <lambda>
    self.dims.events.ndisplay.connect(lambda e: self._update_dims())
  File "/home/hagai/.conda/envs/ncd/lib/python3.7/site-packages/napari/layers/base/base.py", line 383, in _update_dims
    self.refresh()
  File "/home/hagai/.conda/envs/ncd/lib/python3.7/site-packages/napari/layers/base/base.py", line 600, in refresh
    self._set_view_slice()
  File "/home/hagai/.conda/envs/ncd/lib/python3.7/site-packages/napari/layers/points/points.py", line 654, in _set_view_slice
    self._selected_box = self.interaction_box(self._selected_view)
  File "/home/hagai/.conda/envs/ncd/lib/python3.7/site-packages/napari/layers/points/points.py", line 480, in interaction_box
    data = points_to_squares(data, size)
  File "/home/hagai/.conda/envs/ncd/lib/python3.7/site-packages/napari/layers/points/points.py", line 972, in points_to_squares
    points + np.sqrt(2) / 2 * np.array([sizes, sizes]).T,
ValueError: operands could not be broadcast together with shapes (1,3) (1,2)
```

**Comment by sofroniewn** [comment]
> I expect napari to transition to a 3D view of the data without crashing.

For sure, a bug must have crept in here - I can work on a fix + test to make sure it doesn't happen again

> When I come back to the 2D view it would be nice if the points would still be highlighted.

Right now we don't support any type of selection in 3D - which maybe isn't so great, but doing so isn't trivial. There has been some discussion around this in #515, but maybe until that get's implemented we might just unselect everything when you move to 3D, which I know isn't ideal either, but is definitely better than crashing

**Comment by HagaiHargil** [comment]
I understand selecting in 3D is hard - any Blender\3D modeling software user can tell you that :)
I think that the best outcome of this bug fix is that if I have data selected before transitioning to 3D - the data will still be selected after the transition. It might also be nice to be able to select data from the command line (by writing `Layer.selected_data = [1, 13, 27, 30]`).

If this is too complicated then I'd be happy if the selected points will be cleared during the 3D phase, but when we go back to 2D the points will be re-selected. 

Finally - simply not crashing is also an improvement :D

**Comment by kevinyamauchi** [comment]
> For sure, a bug must have crept in here - I can work on a fix + test to make sure it doesn't happen again

@sofroniewn , it sounds like you're on it, but I have time this afternoon to work on it if you're busy.

**Comment by sofroniewn** [comment]
@kevinyamauchi I havn't started yet - would be great if you could take this one!!

**Comment by kevinyamauchi** [comment]
In order to address this quickly, I made a small PR (#902) that fixes the bug.

I like the other suggestions made by @HagaiHargil to add support for: (1) the selected points get "remembered" when going to 3D and then re-selected when transitioning back to 2D and (2) allow points to be selected via that command line when in 3D. I didn't include them in that initial PR because they will require a bit more of a refactor and I didn't want to hold up the bug fix. I can look into adding those futures later this week.

**Comment by kevinyamauchi** [comment]
Hey, @HagaiHargil. We just merged the quick fix (i.e., napari no longer crashes when switching from 2D to 3D with a point selected). Feel free to pull master and give it a go. I like your other suggestions, so I'll work on getting a prototype together in the next couple of days.
